### ISSUE TITLE
[Feature Request] Add effects per track/media

### ISSUE THREAD

**Issue by sallecta** [olive-editor/olive#1001]
**Problem applying same effects chain to same video source .**

Today effects are assigned per bar (single or nested).

For instance, I need to apply exactly same effect's chain to same media source:
- I have to copy/paste effects for each bar that contain original media
- If I decide to adjust, for example, colour grading, I have to reimplement copy/paste operations to Each bar that contains target media source.

So for now, there is a problem applying same effect's chain to selected media/track, and it is better to avoid such technique otherwise work on project turns into over-complex routine.

**Solution (new features)**

**Effects per track:**
- select track to edit it's effects chain
-- selected track highlighted now
- in Effects window we see effects assigned to track
-- Effects window gets caption "Effects **of Track**"
-- Effects window gets label of  selected **$TrackNumber**

**Effects per media:**
- select media in media browser to edit it's effects chain
-- selected media highlighted now
- in Effects window we see effects assigned to media
-- Effects window gets caption "Effects **of Media**"
-- Effects window gets label of  selected  **$MediaName**

**Effects per bar** (already implemented, but have to be clarified):
- select bar in timeline to edit it's effects chain
-- selected media highlighted now
- in Effects window we see effects assigned to bar
-- Effects window gets caption "Effects of **Bar** "
-- Effects window gets label of  selected  **$BarName**

**Describe alternatives you've considered**

No solutions, just avoid even thinking to apply same effects chain to media/track, or your project will be bloated.

**Do you know any libraries or sources that can help the Olive Team include the feature?**

I believe, [Shotcut](https://github.com/mltframework/shotcut) has effects per track/bar feature.

**Additional context**

Fake interface screenshots of implemented features.

Effects per Bar:
![Olive EffectsChain-Bar](https://user-images.githubusercontent.com/11870308/59706462-31d64e00-9209-11e9-8f96-069324d925ae.png)

Effects per Track:
![Olive EffectsChain-Track](https://user-images.githubusercontent.com/11870308/59706489-3e5aa680-9209-11e9-9671-fbde8b17cf81.png)

Effects per Media:
![Olive EffectsChain-Media](https://user-images.githubusercontent.com/11870308/59706528-4fa3b300-9209-11e9-97cf-252e311c2ddb.png)

**Comment by sallecta** [comment]
What I get when this request will be applied:
- Prepare media for use in project
-- resize to project needs (ex, zoom vertical videos to widescreen)
- Style all bars in same track 
-- ex, one track contains b/w versions of media
-- ex, other track contains shaked versions of same media)
- And, finally, apply last level effects per selected bar


video render of project used in screenshots
https://www.youtube.com/watch?v=dlxwolB-8ac

**Comment by Simran-B** [comment]
The upcoming node-based pipeline will change a few things, among them should be the ability to re-use a group of effects for arbitrary clips and IIRC also for tracks. Not sure about per-medium effects, but I guess it depends on whether media will also be a type of input node...
