### ISSUE TITLE
[Bug] Freior effects do not work on title clips (and under render effects in general)

### ISSUE THREAD

**Issue by Nobelix** [olive-editor/olive#1002]
**Your Setup:**
- Olive version: Olive (April 2019 | Alpha | 1e3cf53)
- Source: PPA
- Operating system: Ubuntu 19.04 64-bit
- CPU: Intel® Core™ i5-7400 CPU @ 3.00GHz × 4 
- RAM: 8GB
- GPU: GeForce GTX 1050/PCIe/SSE2 2GB (Driver ver 430.26)

**Describe the Bug**
When trying to apply a Frei0r effect under a render effect (text fro example), the text will not be affected by the Frei0r effect.

**To Reproduce**
1. Go to the effects tab of a video clip
2. Add an render effect such as a "RichText"
3. Add a Frei0r effect such as "Glitch0r" under it
4. Play the video clip
5. Observe how the effect is only applied to the base clip and the text stay untouched 

**Screenshots**
Applying built-in effect under a text clip:
![image](https://user-images.githubusercontent.com/30960698/59774868-7832b800-92b0-11e9-997b-0692fe0a4502.png)
Applying frei0effects under a text clip:
![image](https://user-images.githubusercontent.com/30960698/59775379-67cf0d00-92b1-11e9-9a0e-68ef8cc57549.png)

**Comment by sobotka** [comment]
Freior is obsoleted.

**Comment by Symbian9** [comment]
> Frei0r is obsoleted.

Frei0r "would be" obsoleted for next *Olive* versions, but still usable for *Olive* `v0.1.0`:

- https://github.com/olive-editor/olive/releases/tag/0.1.0

**Comment by Symbian9** [comment]
> Frei0r effects do not work on title clips

This known limitation of `frei0r` support in *Olive* `v0.1.0` (newer version of *Olive* would be fully incompatible with `frei0r`).

-  https://github.com/olive-editor/olive/issues/663#issuecomment-475273381

> Frei0r effects won't affect Titles/Bars/Solids.
