### ISSUE TITLE
[Enhancement] UI Tweaking Suggestion.

### ISSUE THREAD

**Issue by Fatih20** [olive-editor/olive#1006]
The UI of Olive is not great. I know to some extent, how it can be improved. Here, I will present my case to how the Olive UI should be changed. 
![Screenshot-20190624145101-2560x1412](https://user-images.githubusercontent.com/51940383/60068182-e0ade900-9737-11e9-801e-e90ab23290a7.png)
So, here is the original UI. I will pick apart which one it does wrong.
![Too Cramped](https://user-images.githubusercontent.com/51940383/60068272-2e2a5600-9738-11e9-8415-be4f26e6d905.png)
The space between the button is too small, it makes them look cramped and make it hard to look.
![None Ugly](https://user-images.githubusercontent.com/51940383/60068319-62057b80-9738-11e9-8200-6481fb11c8ee.png)
The : none looks horrible and unsophisticated.
![Not Enough Space](https://user-images.githubusercontent.com/51940383/60068367-9b3deb80-9738-11e9-8466-1fd922891c1d.png)
The space between the button and other UI element is too small making them, again, cramped
![Tab Button](https://user-images.githubusercontent.com/51940383/60068383-b9a3e700-9738-11e9-9518-98cd96ee7ea2.png)
You can barely see the shape of the button on the tab. And the button itself looks ugly.
![Ugly Icons](https://user-images.githubusercontent.com/51940383/60068465-08518100-9739-11e9-8986-8750661a5aa1.png)
Enough said.
So, here's my proposal.
![Mock-Up Olive](https://user-images.githubusercontent.com/51940383/60068484-261ee600-9739-11e9-8e98-097138faf239.png)
Link to the SVG download : https://drive.google.com/open?id=1Aal2AqeOg6UkYJGhDTqfECnPmWB82g3v
Please note that I can't code, I'm not a programmer, so it would take someone else to make this changes happen.

**Comment by Fatih20** [comment]
![Screenshot-20190625123851-1577x645](https://user-images.githubusercontent.com/51940383/60076810-af8ee200-9752-11e9-8fbf-296a2d80343e.png)
This is the original UI
![Mock-Up Olive 2](https://user-images.githubusercontent.com/51940383/60076829-b7e71d00-9752-11e9-9bd6-275cf89322c9.png)
This is what I propose with the same reasoning that I have used for the previous one.

**Comment by Fatih20** [comment]
![Screenshot-20190625141455-800x595](https://user-images.githubusercontent.com/51940383/60077994-4ceb1580-9755-11e9-9afa-c48c69e2fd78.png)
This is the current graph editor
![Mock-Up Olive 3](https://user-images.githubusercontent.com/51940383/60078016-54122380-9755-11e9-8660-7a8b07a6e529.png)
This is what I propose

**Comment by deilias** [comment]
This look very promising.
