### ISSUE TITLE
[Feature Request] Create a frame server

### ISSUE THREAD

**Issue by reynum2** [olive-editor/olive#1007]
**Is your feature request related to a problem? Please describe.**
Actually the render of the exported video is not very good quality and we can't adjust manually the codec.

**Describe the solution you'd like**
In order to enable the possibility to use all options of ffmpeg it could be nice to develop a frame server (https://en.wikipedia.org/wiki/Frameserver) like in Blender for example.

**Comment by Simran-B** [comment]
> not very good quality

That is extremely vague. What encoding settings did you use?

**Comment by reynum2** [comment]
There is no many choice :
![olive_codec](https://user-images.githubusercontent.com/11191723/60157803-e404ab80-97ef-11e9-926b-37bda15dc81a.jpg)

In input I try with a 1080p and 2.7K videos, and the output result is very noisy and colors are little faded

I try the same videos with the frame server of blender and my custom ffmpeg settings and the result is much better and the file size is smaller.

**Comment by Simran-B** [comment]
The next Olive version will come with OpenColorIO, but I'm not sure if this is a pixel management issue if the colors are faded. What might help your particular problem: add an option so that users can specify custom FFMPEG encoding settings.

**Comment by reynum2** [comment]
Yes, let the user having the control on the ffmpeg settings is a good idea.
The implementation of OpenColorIO is a very good news too.

But a frame server allow many usages and is not very difficult to implement, so it was just an idea.

**Comment by sobotka** [comment]
I’m going to close this for the time being, given that encoding is a huge kettle of fish, and that encoding to still frames and leaving the muxing to an external approach would probably be a useful first step with the new code paths.

An encoding unit and discussion is worthwhile, just a wee bit premature given the current state of the code base.
