### ISSUE TITLE
[Bug] CMake INSTALL cannot find cornerpin.frag

### ISSUE THREAD

**Issue by martinkg** [olive-editor/olive#1008]
Hi,

when compiling the recent olive version olive-771572f65b4e1b42d4448b4f4161fdc703727f7e
on Fedora 30, i get this error message:

`/usr/include/qt5/QtCore/qvector.h:1022:13: note:   template argument deduction/substitution failed:
/home/martin/rpmbuild/BUILD/olive-771572f65b4e1b42d4448b4f4161fdc703727f7e/panels/viewer.cpp:474:72: note:   mismatched types 'const QVector<T>' and 'long int'
  474 |       } else if (c->timeline_out() < n_cut && c->timeline_out() > seq->playhead) {
      |                                                                        ^~~~~~~~
/home/martin/rpmbuild/BUILD/olive-771572f65b4e1b42d4448b4f4161fdc703727f7e/panels/viewer.cpp: In member function 'void Viewer::set_in_point()':
/home/martin/rpmbuild/BUILD/olive-771572f65b4e1b42d4448b4f4161fdc703727f7e/panels/viewer.cpp:523:32: error: cannot convert 'rational' to 'long int'
  523 |     headers->set_in_point(seq->playhead);
      |                           ~~~~~^~~~~~~~
      |                                |
      |                                rational`

**Comment by martinkg** [comment]
more information to CXX compiler and ffmpeg version.

`+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON .
-- The CXX compiler identification is GNU 9.1.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib64/libOpenGL.so   
-- Found OpenColorIO: /usr/lib64/libOpenColorIO.so;/usr/lib64/libtinyxml.so  
-- Found FFMPEG: /usr/include/ffmpeg (found suitable version "4.1.3", minimum required is "3.4") found components:  avutil avcodec avformat avfilter swscale swresample 
Olive: Git hash = 0ac9dd9
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.15") found components:  doxygen dot 
-- Configuring done
-- Generating done`

**Comment by martinkg** [comment]
with the recent git version olive-8f6cb7a2cbe7bb0258e0e8dc4d49daddd3afde4a
i get this error message at the end of the compilation/installation.

`Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Installing: /home/martin/rpmbuild/BUILDROOT/olive-0.1.0-0.4.20190701git8f6cb7a.fc30.x86_64/usr/bin/olive-editor
CMake Error at app/cmake_install.cmake:57 (file):
  file INSTALL cannot find`

**Comment by martinkg** [comment]
correct error message again:

`Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Installing: /home/martin/rpmbuild/BUILDROOT/olive-0.1.0-0.4.20190703git85b5bbd.fc30.x86_64/usr/bin/olive-editor
CMake Error at app/cmake_install.cmake:57 (file):
  file INSTALL cannot find
  "/home/martin/rpmbuild/BUILD/olive-85b5bbd5d6fb97ef215efd118b3fc156ebfba9bd/app/effects/internal/cornerpin.frag".
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)`

**Comment by itsmattkc** [comment]
Olive is in no shape to be installed at the moment, regardless there was no reason to leave this old code around so it should work as expected now.

**Comment by eszlari** [comment]
Installing is still broken. You will have to disable installing translations until you have generated the TS files.

**Comment by itsmattkc** [comment]
Try cf267440d7f5b55bbe87d8bd0e9b2a89fa379023

**Comment by martinkg** [comment]
@itsmattkc
Thanks, works for me.

**Comment by xenogenesi** [comment]
It doesn't work for me, I used for months a docker (which I can possibly supply as a gist or repository) based on "debian: sid-slim" to build the deb package, the last version I managed to build is d3b00efc (there may be other good commits I've skipped but this is the last version I've built and installed). Currently I have upgraded to 98bb3e8d but cmake install fails.

    Install the project...
    /usr/bin/cmake -P cmake_install.cmake
    -- Install configuration: "None"
    -- Installing: /usr/src/olive/debian/olive-editor/usr/bin/olive-editor
    CMake Error at app/cmake_install.cmake:57 (file):
      file INSTALL cannot find
      "/usr/src/olive/app/effects/internal/cornerpin.frag".
    Call Stack (most recent call first):
      cmake_install.cmake:42 (include)
    
    
    make[1]: *** [Makefile:77: install] Error 1
    make[1]: Leaving directory '/usr/src/olive/obj-x86_64-linux-gnu'
    dh_auto_install: cd obj-x86_64-linux-gnu && make -j8 install DESTDIR=/usr/src/olive/debian/olive-editor AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true" returned exit code 2
    make: *** [debian/rules:18: binary] Error 2
    dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
    make: *** [Makefile:45: olive-build] Error 2
