### ISSUE TITLE
[Bug ]XVID mp4 encoded video file can't be used in Olive and causes it to freeze if open debug log

### ISSUE THREAD

**Issue by user2155** [olive-editor/olive#1010]
**Your Setup:**
- Olive version (Olive (April 2019 | Alpha | 1e3cf533):
- Source: (website  Olive-1e3cf53-Windows-x86_64.zip)
- Operating system: (Windows 10 pro 64-bit Version 1903 (Build 18362.207) 18362.19h1_release.190318-1202)
- CPU: (AMD Athlon II)
- RAM: (4GB)
- GPU: (Onboard ATI Radeon 3000 Graphics)

**Describe the Bug**
If add an XVID mp4 encoded video file to the Olive's timeline, the sequence viewer shows black screen. If then open Debug log, Olive freezes. 

**To Reproduce**
1. Download video file https://filebin.net/rx9ndnp5gfdjcxnh
2. Add it to a new project.
3. Drag and drop the file to the time line.
4. See the black screen in Sequence viewer.
5. Open Help-->Debug Log.
6. See Olive freezes, can't copy debug information..

**Screenshots**
https://i.postimg.cc/cHHF2VYR/olive-debug-log.jpg

**Comment by sobotka** [comment]
I’m going to close this as `master` will see the newer decoding model implemented. If it reappears, this can be opened as required.
