### ISSUE TITLE
[Feature Request] Compacted View

### ISSUE THREAD

**Issue by Fatih20** [olive-editor/olive#1011]
![Mock-Up Olive 4](https://user-images.githubusercontent.com/51940383/60380140-afe8ef00-9a6a-11e9-97ff-79447765aeb1.png)
This is the timeline normally
![Mock-Up Olive 5](https://user-images.githubusercontent.com/51940383/60380141-afe8ef00-9a6a-11e9-90d6-f280471e2083.png)
This is the timeline under a feature I propose called "Compact View"

This feature can be useful when someone wanted to look at the bigger picture instead of the individual object when it comes to the timeline.

**Comment by AGI-THB** [comment]
You already can make the Tracks smaller... CTRL+-

It's not a new feature.

**Comment by elsandosgrande** [comment]
I think that the person is suggesting for there to be a quick toggle between two views. 
Given that, perhaps there could be other adjustments made to the timeline that are controlled by this feature. Perhaps some added overlays in the future? 

This feature could be promising, or it could be merely a lazy man's size control. It all depends on how this is handled.

**Comment by Fatih20** [comment]
> I think that the person is suggesting for there to be a quick toggle between two views.
> Given that, perhaps there could be other adjustments made to the timeline that are controlled by this feature. Perhaps some added overlays in the future?
> 
> This feature could be promising, or it could be merely a lazy man's size control. It all depends on how this is handled.

Yes, that's what I'm proposing here.
