### ISSUE TITLE
[Feature Request] Toggle Button to Only Show Sequence, Image, or Video.

### ISSUE THREAD

**Issue by Fatih20** [olive-editor/olive#1014]
**Is your feature request related to a problem? Please describe.**
Someone could probably use a lot of nested sequence, images, and video. It would be hard navigating the media pool in that case.
![Mock-Up Olive](https://user-images.githubusercontent.com/51940383/60386558-8fe41a80-9ac0-11e9-8e49-27a05fa029a9.png)

**Comment by Simran-B** [comment]
Taking up a whole row seems pretty wasteful for a filter feature without any evidence that it actually improves the workflow. It's also unclear how many additional types there will be at some point (audio, subtitles, text, image sequences...). A filter by type feature could be integrated into the search bar (text-based) or maybe via a popover at the end of the search field for various advanced search options.
