### ISSUE TITLE
[Enhancement] Make Objects in Timelines Look Better

### ISSUE THREAD

**Issue by Fatih20** [olive-editor/olive#1015]
**Is your feature request related to a problem? Please describe.**
The objects in the timeline looks too unsaturated and not so vibrant, also, the 3D effect applied by a slight hint of white on top and a slight hint of black below makes the whole thing looks archaic. This is how it looks like right now.
![Screenshot-20190629105607-2560x1412](https://user-images.githubusercontent.com/51940383/60387252-72b44980-9aca-11e9-8a4a-27cc835f6b81.png)
This is my proposal
![Mock-Up Olive 5](https://user-images.githubusercontent.com/51940383/60387263-924b7200-9aca-11e9-9919-dfd94432a064.png)

**Comment by elsandosgrande** [comment]
The image above reminds me of Windows 9x if I squint while looking at the timeline. I would not mind a refined shadow being incorporated into the mock-up below, but the white line has to go.
Maybe the shadow could be an elegant way of noting what was selected without highlighting the elements in question, toggleable in the settings, of course.

**Comment by Fatih20** [comment]
> The image above reminds me of Windows 9x if I squint while looking at the timeline. I would not mind a refined shadow being incorporated into the mock-up below, but the white line has to go.
> Maybe the shadow could be an elegant way of noting what was selected without highlighting the elements in question, toggleable in the settings, of course.

I will look into macking a Mock-up of this suggestion.

**Comment by elsandosgrande** [comment]
I am linking this! Yeah, toggleable. 

You know what, there should be three preference options: 
 * Flat - All timeline elements are flat; selected elements are highlighted
 * Shaded - All timeline elements are shaded; selected elements are highlighted
 * Fused - All timeline elements are flat; selected elements are shaded; no elements are highlighted

Just watch Matt scoff at the last one.

**Comment by Simran-B** [comment]
Rounding off the corners of clips to make the timeline visually more pleasing is a terrible idea. It shifts the perceived boundaries inwards, making it harder to comprehend where a clip starts or ends in time and in relation to one another. It's also not compatible with thumbnails:

- bottom left corner of thumbnail is lost
  ![image](https://user-images.githubusercontent.com/7819991/60431801-ec4e5380-9c00-11e9-8394-4d01d65da134.png)

- full thumbnail, but not aligned with clip name, visually noisy
  ![image](https://user-images.githubusercontent.com/7819991/60431265-a6dd5680-9bff-11e9-94f8-9c9ec806a8a7.png)

- full thumbnail, aligned with clip name, but unclear what frame is actually shown
  (first frame or the frame at the position where it is displayed?), also visually noisy
  ![image](https://user-images.githubusercontent.com/7819991/60431302-bfe60780-9bff-11e9-9961-ab6e84e75a77.png)

The shaded design adds pseudo-perspective, making it look they the clips are about to fall over.

**Comment by Fatih20** [comment]
> Rounding off the corners of clips to make the timeline visually more pleasing is a terrible idea. It shifts the perceived boundaries inwards, making it harder to comprehend where a clip starts or ends in time and in relation to one another. It's also not compatible with thumbnails:
> 
>     * bottom left corner of thumbnail is lost
>       ![image](https://user-images.githubusercontent.com/7819991/60431801-ec4e5380-9c00-11e9-8394-4d01d65da134.png)
> 
>     * full thumbnail, but not aligned with clip name, visually noisy
>       ![image](https://user-images.githubusercontent.com/7819991/60431265-a6dd5680-9bff-11e9-94f8-9c9ec806a8a7.png)
> 
>     * full thumbnail, aligned with clip name, but unclear what frame is actually shown
>       (first frame or the frame at the position where it is displayed?), also visually noisy
>       ![image](https://user-images.githubusercontent.com/7819991/60431302-bfe60780-9bff-11e9-9961-ab6e84e75a77.png)
> 
> 
> The shaded design adds pseudo-perspective, making it look they the clips are about to fall over.

This is definitely a very interesting criticism. I will look into making it look better without compromising functionality.

**Comment by maxxxlarsson** [comment]
I did a quick mockup of rounded corners in the timeline as well today. And I really really really think Fatih20 is on to something with his more flat approach to the UI. It's used in almost all other software and OS components nowadays and makes it seem a little more modern. If I had the option in settings to have round corners and hence make it "harder to comprehend", I'd do it instantly.

![timeline](https://user-images.githubusercontent.com/7046942/62356632-cffc4a00-b511-11e9-89b5-65e9bd157435.png)
