### ISSUE TITLE
[Enhancement] Dedicated Button for Making Viewer Full Screen

### ISSUE THREAD

**Issue by Fatih20** [olive-editor/olive#1017]
**Is your feature request related to a problem? Please describe.**
When I want to make the viewer, be it sequence or media, fullscreen, I need to do 2 click. Right click on viewer>Show Fullscreen. It's 3 click when I have multi monitor setup because after that, I still need to choose which monitor. This is not a good UX at all. There are situations where someone would like to quickly switch fullscreen and not fullscreen quickly.

**Describe the solution you'd like**
There should be a barely opaque button in the corner of the viewer when the video is playing or when the cursor move towards the corner that instantly make the viewer fullscreen. For a multi-monitor setup, we should be able to just set the default monitor used for fullscreen viewing in the preferences. And then, we have the option to right click the button to show an option to switch the used monitor to other monitor in that particular instance.
![Mock-Up Olive 7](https://user-images.githubusercontent.com/51940383/60388101-fffd9b00-9ad6-11e9-989b-eeb7c9934bc0.png)
Now, suppose that I have 3 monitor. I have set up monitor A as the default, but in this particular instance, I wanted it to show up in other monitor. I can right click (instead of left clicking that will make it fullscreen on monitor A) to give me an option whether I wanted it in monitor B or C.
![Mock-Up Olive 7-A](https://user-images.githubusercontent.com/51940383/60388192-135d3600-9ad8-11e9-8623-aad02022cc1c.png)
If, instead of 3, I have 2 monitor, right clicking the button will not show me the option, it will just make it fullscreen on monitor B because there are only 2 option instead of 3.

I haven't thought about the icons on the button.

**Comment by Fatih20** [comment]
Any reason that this is closed?

**Comment by elsandosgrande** [comment]
Query seconded @sobotka .

**Comment by sobotka** [comment]
Because this isn’t against `notracks`, and the entire thing is predicated on a reductionist mode of design regarding clicks.

**Comment by Fatih20** [comment]
> Because this isn’t against `notracks`, and the entire thing is predicated on a reductionist mode of design regarding clicks.

Can you elaborate? And it's a good thing for the user to click a lot of times for doing something that might be done a lot of time?

**Comment by sobotka** [comment]
> Can you elaborate? And it's a good thing for the user to click a lot of times for doing something that might be done a lot of time?

Design doesn’t exist in a vacuum. The seductive reduction to “user” implies a tautology; the statement can’t be false because assumptions that someone is doing something “a lot of times.” Further still, reducing everything down to a metric of clicks is not a terribly useful axis.

At any rate, the current code base is under tremendous change, and keeping the tracker focused on the master, when it actually is capable of testing against higher priorities, is the main goal of closing these sorts of issues. Under this, 99% of the issues in this tracker are mostly non-issues, and need to be closed.

**Comment by Fatih20** [comment]
> > Can you elaborate? And it's a good thing for the user to click a lot of times for doing something that might be done a lot of time?
> 
> Design doesn’t exist in a vacuum. The seductive reduction to “user” implies a tautology; the statement can’t be false because assumptions that someone is doing something “a lot of times.” Further still, reducing everything down to a metric of clicks is not a terribly useful axis.
> 
> At any rate, the current code base is under tremendous change, and keeping the tracker focused on the master, when it actually is capable of testing against higher priorities, is the main goal of closing these sorts of issues. Under this, 99% of the issues in this tracker are mostly non-issues, and need to be closed.

So, improving the UI/UX shouldn't be done under this supposed rewrite?

**Comment by sobotka** [comment]
>So, improving the UI/UX shouldn't be done under this supposed rewrite?

Focusing on the rewrite is key. 

The larger takeaway is evaluating one’s idea of “improvement”.

**Comment by Fatih20** [comment]
Alright, fair enough. Then this idea shouldn't be debated? We as a user shouldn't debate how the user  interface/user experience can be improved? You want to call my idea trash and shit, fine. But give me a reason why and how the UI/UX should be then. What's the reason of decreasing the amount of click is a bad idea, then?

**Comment by sobotka** [comment]
I didn’t call your idea “trash” nor “shit”. I find the path reductio ad absurdum in the sense that you are predicating the entire claim on something already decided; that clicks are bad and that there is a singular user.

Read through the hundreds of reports in this tracker and you’ll see that exactly zero of them are focused on design. That is, every single one is forwarded in good faith, yet each has a specific idea of “user” in mind. Some folks want a page curl and swirl, others want complex audio Fairlight-esque mixing controls, and others want sophisticated encoding controls.

Who is right? Where do you draw a line? What is the current design context? And most specifically, who specifically is the audience that these issues are directed at?

You’ll find in all cases, it is just random thoughts thrown against the wall without a specific target audience identified.

**Comment by rubenwardy** [comment]
Having a dedicated full screen button is standard across nearly every video display you find in the wild
