### ISSUE TITLE
[Feature Request] - minor feature request: wider timeline marker when zoomed in

### ISSUE THREAD

**Issue by crotalidae75** [olive-editor/olive#1019]
It occurred to me that the marker on the timeline doesn't cover a whole frame when zoomed in - it always remains as a thin line, so it sort of confusing to find where the end of a clip is when you are zoomed in down to a high level.  I thought it might be more useful to have it a bit wider, wide enough to cover a single frame after zoomed in past a certain point.  It would make it a bit easier to know where clips end.

Currently, the marker, at the end of a clip, sits just immediately left or right (of the beginning or end), but not *right on* it -- if you move it past that point, to the (apparent) edge of the clip, the viewer shows that you are not on that clip anymore, if that makes sense.

**Comment by musaire** [comment]
I think markers should be located at precise points in time, at frame resolution. If its width is a frame, then I wouldn't know if the marker is set before the frame or after the frame.
The viewer should always show the next frame on timeline - if your cursor is after the frame, it shouldn't show the frame. Step a frame back to take a look, or drag the clip longer for visual effects preview and cut it at the marker later.
If your video frame rate and timeline frame rate doesn't match (not a good reason for it to not happen), then I am not sure how it shows up.

**Comment by crotalidae75** [comment]
It's sort of moot, because I realized, the program does in fact show a one-frame wide marker, when you zoom in far enough.  It's just kind of hard to see.  It is a pale band, covering one frame, to the right of the red marker line, when you zoom in.  It's not very visible in the theme I use (Native Linux theme).

It just needs to be a bit more visible.
