### ISSUE TITLE
[Feature Request] Video Event Pan and Crop

### ISSUE THREAD

**Issue by JellyOsaurus** [olive-editor/olive#1023]
**Is your feature request related to a problem? Please describe.**
Yes, I am fustrated when i have multiple layers of objects and sequences and i can't have a event based pan, crop, and zoom. I want to be able to zoom into my projects in an event of keyframes without having to select everything from the timeline and adjust the size and messing up the positioning of the objects and everything

![1](https://user-images.githubusercontent.com/22872180/60401100-27eb0e00-9b6c-11e9-94a2-e269aa958e24.png)

**Describe the solution you'd like**
A great solution to this issue is introduce a feature called Event Pan and Crop so you can use keyframes to manipulate a pan and zoom of a project. You would have the ability to right click on your sequence viewer and select Event Pan/Zoom

![2](https://user-images.githubusercontent.com/22872180/60401261-14d93d80-9b6e-11e9-978c-5ccbd765f085.png)

and be able to create keyframes of your zooms and pans in your video. 

You can take inspiration from Vegas Pro, and have an entire pop up once you click "Event Pan/Zoom" and be able to adjust the pan and zoom like this 

![image](https://user-images.githubusercontent.com/22872180/60401304-be203380-9b6e-11e9-9d52-c9ee86bf8558.png)

That way a user is able to have as many objects and layers and have the ability to have the video zoom into that project without having to select all the objects and possibly messing up their entire project.

**Comment by sobotka** [comment]
Incompatible with the current nodal design. There will be a reasonable opportunity to implement via Gizmo-like wrapping.
