### ISSUE TITLE
Gamma Correction and Color Space Profiles [Feature Request]

### ISSUE THREAD

**Issue by nwaxiomatic** [olive-editor/olive#1026]
**Is your feature request related to a problem? Please describe.**
There is no gamma correction, so importing linear color space images / videos is not really possible. In general there should be support for non-sRGB encoded files.

**Describe the solution you'd like**
There should be a gamma slider in the color correction effect and imported files should be able to specify their color space profile.

**Describe alternatives you've considered**
This cannot be fixed with features such as contrast / exposure since it is a fundamental property of how the pixel colors are interpreted.

**Do you know any libraries or sources that can help the Olive Team include the feature?**
https://learnopengl.com/Advanced-Lighting/Gamma-Correction
https://github.com/tobspr/GLSL-Color-Spaces

**Additional context**
Very basic / easy feature, but doesn't come up until you get deep into compositing / color correction stuff

**Comment by Simran-B** [comment]
See #237 regarding pixel management. Olive is currently being rewritten to deal with color properly.

**Comment by sobotka** [comment]
Core design principle that extends well beyond “gamma” and is already implemented to a degree in 0.1.0.
