### ISSUE TITLE
Support for offline/invalid clips

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#103]

**Comment by itsmattkc** [comment]
Also should be implemented alongside #85

**Comment by itsmattkc** [comment]
Added, but still no support for relinking or replacing media

**Comment by itsmattkc** [comment]
There should be extra support for if a clip has changed (including if a media stream in use by a clip no longer exists). This will also help with implementing replacing footage.

I suppose we just need to include cases for MediaStream references to be NULL (and visually depict that). Also handle a duration change.

**Comment by maingi2** [comment]
I'd request that this is treated with some better support than Vegas/Premiere, say a menu allowing drag/drop to also work to replace a missing file or a macro that removes all offline / invalid clips.

**Comment by itsmattkc** [comment]
Implemented in b8b99901d8f71ebc1583cb9b7c49e26d38e01ec9
