### ISSUE TITLE
Video does not show, only shows black screen

### ISSUE THREAD

**Issue by neontrebleperseverance** [olive-editor/olive#1031]
PLease help

**Comment by AGI-THB** [comment]
Fill out the issue template...

**Comment by itsmattkc** [comment]
I've added this to the FAQ since it was a common enough question:

> Make sure your graphics drivers are installed and up-to-date. Olive's display is hardware accelerated by design and most (if not all) issues like this are caused by the computer have no/outdated graphics drivers.
