### ISSUE TITLE
Edit - Duplicate it does not work

### ISSUE THREAD

**Issue by RafaMartorell** [olive-editor/olive#1032]
**Your Setup:**
- Olive version: **Olive (April 2019 | Alpha | 1e3cf53)**
- Source:  **Flatpack**
- Operating system: **Mint 18 64bit**
- CPU:  **Intel i7**
- RAM: **16GB**
- GPU:  **NVIDIA Geforce GTX 1050 4GB (Driver ver 384.130)**

**Describe the Bug**
The Edit - Duplicate (Ctrl D) command does not work, does nothing

**To Reproduce**
1. Select clip
2. Ctrl+D or menu edit Duplicate
3. does nothing
4. :-( No problem, solution is easy, copy and paste ;-)

**Comment by itsmattkc** [comment]
Duplicate technically _does_ do what it was written to do: duplicates Sequence objects in the Project panel. It was never fleshed out much beyond that, we'll see if it's necessary to implement it again in the rewrite

**Comment by Simran-B** [comment]
A Duplicate action could place a copy(?) of the active clip on the timeline. It could put it after the active clip or at the playhead, but rather the former - unless a concept of active track is added, in which case you might want to have it placed on the selected track at the playhead position.

However, the same could be achieved using copy & paste. To make it a useful action, it would need to do something else, like adding a linked duplicate of a clip. I agree however that in the rewrite with a node-based system this has to be rethought and evaluated if it makes sense in the timeline context or elsewhere.

**Comment by RafaMartorell** [comment]
In a video editor it does not make much sense to duplicate, so it would be best to remove it, because when you want to duplicate a clip simply copy and paste where you want to paste (CTRL + V) or insert (CTRL + SHIFT + V)

Duplicating or creating a clone is more common in 3D or composition applications.

It is a personal opinion, I use this option a lot in 3D applications or in After Effects, but I do not use it in video editors, if I want a repeat I copy and paste.
