### ISSUE TITLE
[Bug] Crashes When Exporting Video

### ISSUE THREAD

**Issue by Nordy13** [olive-editor/olive#1044]
- Olive version: (April 2019 | Alpha | 1e3cf533)
- Source: https://olivevideoeditor.org/download.php
- Operating system: Windows 8.1

Every time I export an mp4 or any file Olive crashes. Please fix the issue, I may not export anything again (until it is fixed).

**Comment by AGI-THB** [comment]
Your report lacks information.

If you are not willing to put time into writing a meaningful bug report then you don't need to wonder why your problem is getting ignored.

**Comment by giutor73** [comment]
I would close this non bug, the operator is quite arrogant. Thanks.
