### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by YouTuber2017** [olive-editor/olive#1045]
**Your Setup:**
- Olive version (window title or Help > About):
- Source: (e.g. AppImage, PPA, AUR, website etc.)
- Operating system: (e.g. Ubuntu 18.04 64-bit)
- CPU: (e.g. Intel i5-4300U)
- RAM: (e.g. 8GB)
- GPU: (e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx))

**Describe the Bug**

**To Reproduce**

** Debug Log and/or Crash Report **

```
[Paste log/report]
Version: 5e0e0334
Operating System: Manjaro Linux x86_64
Build ABI: x86_64-little_endian-lp64

Signal: 11

olive-editor(_Z7handleri+0x42) [0x563eb68e46b2]
/usr/lib/libc.so.6(+0x3a7e0) [0x7fae9d5c97e0]
/usr/lib/libQt5Core.so.5(_ZN7QObject10disconnectEPKS_PKcS1_S3_+0x164) [0x7fae9dd58994]
olive-editor(_ZN10NodeEditor17DisconnectAllRowsEv+0x45) [0x563eb68ff9e5]
olive-editor(_ZN10NodeEditor10ClearEdgesEv+0xd7) [0x563eb68ffd57]
olive-editor(_ZN10NodeEditor17AboutToClearEventEv+0xbe) [0x563eb68fff2e]
olive-editor(_ZN12EffectsPanel5ClearEb+0x172) [0x563eb68fd6d2]
olive-editor(_ZN12EffectsPanel8SetClipsEv+0x2d) [0x563eb68fd8dd]
olive-editor(_Z9update_uib+0x96) [0x563eb69013b6]
olive-editor(_ZN12TimelineView9dropEventEP10QDropEvent+0x227) [0x563eb69810b7]

**Comment by AGI-THB** [comment]
That is exactly how to not file a bug report.

Change the title of this report to something meaningful.

Describe the steps that lead to the bug / crash.
