### ISSUE TITLE
[Bug] missing Qt5LinguistTools on Ubuntu 19.04

### ISSUE THREAD

**Issue by hellocatfood** [olive-editor/olive#1047]
**Your Setup:**
- Olive version (window title or Help > About):
- Source: github checkout 
- Operating system: Ubuntu 19.04
- CPU: Intel® Core™ i7-7700HQ CPU @ 2.80GHz × 8 
- RAM: 15.2
- GPU: GeForce GTX 1050/PCIe/SSE2

I'm trying to follow these compilation instructions to build Olive on Ubuntu 19.04 https://olivevideoeditor.org/compile.php

After awhile this error pops up
```
Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

	Qt5LinguistToolsConfig.cmake
	qt5linguisttools-config.cmake
```
As detailed here https://stackoverflow.com/a/51698165/326819 qttools5-dev needs to be installed as well.

(also libopencolorio-dev )

**Comment by RafaMartorell** [comment]
It is easier to install from the repositories themselves, from synaptic install:
qttools5-dev-tools
and dependencies, or from a terminal with a simple
sudo apt install qttools5-dev-tools
After this look in the applications with the header qt5 and you will see the assistant to perform the translations called QT 5 Linguist
