### ISSUE TITLE
[Feature Request] Automatic scaling of images

### ISSUE THREAD

**Issue by mrshroomy** [olive-editor/olive#1048]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when i'm trying to use high resolution pictures (>1080p) in Olive video editor because it lags my computer when i preview the pictures in Olive and i also only want my video to be 1080p, i don't need higher resolution.

**Describe the solution you'd like**

I would like if Olive video editor could scale pictures so that they are of a certain resolution for the video quality that you want. I would like Olive video editor to be able to scale big images to 1080p or 720p for example. It would be best if the aspect ratio was kept and that the image that you're scaling does not become smaller than your desired resolution. 

**Describe alternatives you've considered**
You could use any image editing software to scale the images to make them smaller but it would be neat to have this feature built in into Olive video editor. 

**Do you know any libraries or sources that can help the Olive Team include the feature?**
List open-source libraries related to the feature.

**Additional context**

**Comment by itsmattkc** [comment]
You can change the sequence settings to 1080p or or 720p, or create a sequence from the beginning at that resolution.
