### ISSUE TITLE
mts file wont play

### ISSUE THREAD

**Issue by MarvinRomeo** [olive-editor/olive#1052]
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing custom cursors (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[WARNING] QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) (:0, )
[INFO] Clip opened on track 0 (took 92 ms) (:0, )
[INFO] Clip opened on track -1 (took 98 ms) (:0, )
[ERROR] Couldn't retrieve an appropriate frame. This is an error and may mean this media is corrupt. (:0, )
[ERROR] Couldn't retrieve an appropriate frame. This is an error and may mean this media is corrupt. (:0, )[ERROR] Couldn't retrieve an appropriate frame. This is an error and may mean this media is corrupt. (:0, )
[ERROR] Couldn't retrieve an appropriate frame. This is an error and may mean this media is corrupt. (:0, )

**Comment by AGI-THB** [comment]
repost #919

Also: You haven't filled out the ISSUE TEMPLATE

And no, MTS Support has no priority right now.
