### ISSUE TITLE
[NODES] Support for DAG / Node Wrapping ala Nuke Gizmos

### ISSUE THREAD

**Issue by sobotka** [olive-editor/olive#1059]
Putting this here as a milestone marker.

Given the nature of the internal DAG and exposed nodal representation, it becomes important to implement low level wrapping of node chains by creators for reuse and redistribution. It also is a step towards providing sane interface elements to avoid working out low level, repeated chains over and over.

[The Nuke Gizmo approach](https://learn.foundry.com/nuke/content/comp_environment/configuring_nuke/creating_sourcing_gizmos.html)  is a well defined paradigm, and well worth emulating. [Exposing particular controls is also covered.](https://learn.foundry.com/nuke/content/comp_environment/configuring_nuke/managing_controls.html)

This report segues in with many of the existing issues, including but not limited to #1055, #1023, and very likely 80-90% of most new “Feature Requests”.

**Comment by itsmattkc** [comment]
This is largely implemented now. While it could probably do with some refining, that can happen at a later time
