### ISSUE TITLE
[Bug] Title with crossfade causes imported sequence to go black

### ISSUE THREAD

**Issue by ghost** [olive-editor/olive#1060]
**Your Setup:**
- Olive version: Olive (April 2019 | Alpha | 1e3cf53)
- Source: Flathub
- Operating system: Arch Linux
- CPU: Ryzen 2700
- RAM: 32GB
- GPU: Radeon 580

If I set up a sequence with a background and a title that fades in, then import that sequence into another, when the title fades in, it starts from black, without whatever background it should be over.

The the following sample project for a demonstration:
[bug.zip](https://github.com/olive-editor/olive/files/3495646/bug.zip)

**Comment by measlytwerp** [comment]
The bug does seem files in the latest commit, of course it's far from stable: Olive (May 2019 | Alpha | 5e0e0334).

[bug-2.zip](https://github.com/olive-editor/olive/files/3499266/bug-2.zip)
