### ISSUE TITLE
[Feature Request]Simplified and Traditional Chinese Translation

### ISSUE THREAD

**Issue by FunctionSir** [olive-editor/olive#1062]
There are many Chinese users (such as me), if there is a Chinese translation, maybe it will be easier for us.

**Comment by alcomposer** [comment]
If you are comfortable with English <-> Chinese look at: https://github.com/olive-editor/olive/wiki/Translations

It is a very important to have Olive translated, especially if there are already users of the language in question.

Having a diverse user-base will only make Olive better, and is so important to collaboration.

**Comment by ave4** [comment]
It used to be localization, but now it has disappeared somewhere.

**Comment by itsmattkc** [comment]
0.1.1 has a Chinese translation, however it's not yet in any compiled build. It may be soon.
