### ISSUE TITLE
"Yes to all" / "No to all" / "Skip" / "Cancel" buttons on multiples of an action

### ISSUE THREAD

**Issue by maingi2** [olive-editor/olive#107]
I had this 'issue' while importing a bunch of clips for a video concatenation at once. A message box about "image sequence" popped up; this is likely the result of the video clips being labelled with 1-6 at the end of the names, and I don't really know much about that. This is just background information; I don't know if that is an unintended issue.

The real topic this is about is that that message box only has "Yes" or "No" and users should probably have a bit more freedom with that. This message box is likely not the only one that only offers Yes or No. (Skip would skip the current action, cancel would stop it and all further actions as well.)

**Comment by itsmattkc** [comment]
This looks more like an issue with the image sequence detection algorithm:
- It picks up videos, not just images.
- It shouldn't keep asking about files from the same "image sequence".
I believe fixing these will solve this issue more effectively.
