### ISSUE TITLE
Unable to enter Chinese on Linux

### ISSUE THREAD

**Issue by Eiffi** [olive-editor/olive#1071]
When used on Linux, type Chinese from other places and copy it

Sogou input

**Comment by elsandosgrande** [comment]
1. Which desktop environment are you using (KDE, GNOME, Cinnamon, XFCE, ...)? 
2. Are you using Ibus or FCITX for IME (Input Method Editor) handling? Sougou is an IME.
3. Where in the program (in which text input field) are you trying to type Mandarin?

**Comment by Eiffi** [comment]
> 1. Which desktop environment are you using (KDE, GNOME, Cinnamon, XFCE, ...)?
> 2. Are you using Ibus or FCITX for IME (Input Method Editor) handling? Sougou is an IME.
> 3. Where in the program (in which text input field) are you trying to type Mandarin?
> 
> EDIT: Also, which version of Olive are you using?

1. Deepin Desktop Environment (DDE)
2. FCITX
3. Edit Text editor
4.https://github.com/olive-editor/olive/releases/download/0.1.0/Olive-1e3cf53-i386.AppImage


Screenshot from Windows
![QQ截图20190901105510](https://user-images.githubusercontent.com/48773068/64071199-05c65700-cca7-11e9-94fe-8000c2dd160d.png)

**Comment by elsandosgrande** [comment]
Hmm... I will have to look into that. I use KDE though, so...
