### ISSUE TITLE
[Bug] 0.1.1 compilation error: Unexpected tag html in olive_tr.ts:8:16

### ISSUE THREAD

**Issue by bebosudo** [olive-editor/olive#1072]
## My setup:
- Olive version 0.1.1, as released on github
- Source: github source
- Operating system: Fedora 29/30 and CentOS 7, both x86_64

## Description:
Building 0.1.1 on Fedora or RHEL fails with this traceback:
```
..
[  3%] Automatic RCC for icons/icons.qrc
/usr/bin/cmake -E cmake_autorcc /builddir/build/BUILD/olive-0.1.1/CMakeFiles/olive-editor_autogen.dir/RCCiconsInfo.cmake 
make[2]: Leaving directory '/builddir/build/BUILD/olive-0.1.1'
make[2]: Entering directory '/builddir/build/BUILD/olive-0.1.1'
[  8%] Generating olive_id.qm
/usr/lib64/qt5/bin/lrelease /builddir/build/BUILD/olive-0.1.1/ts/olive_id.ts -qm /builddir/build/BUILD/olive-0.1.1/olive_id.qm
Updating '/builddir/build/BUILD/olive-0.1.1/olive_id.qm'...
    Generated 665 translation(s) (642 finished and 23 unfinished)
    Ignored 13 untranslated source text(s)
make[2]: Leaving directory '/builddir/build/BUILD/olive-0.1.1'
make[2]: Entering directory '/builddir/build/BUILD/olive-0.1.1'
[ 10%] Generating olive_tr.qm
/usr/lib64/qt5/bin/lrelease /builddir/build/BUILD/olive-0.1.1/ts/olive_tr.ts -qm /builddir/build/BUILD/olive-0.1.1/olive_tr.qm
lrelease error: Unexpected tag <html> at /builddir/build/BUILD/olive-0.1.1/ts/olive_tr.ts:8:16
make[2]: *** [CMakeFiles/olive-editor.dir/build.make:105: olive_tr.qm] Error 1
```

## Steps to reproduce the behavior:
1. Download and untar 0.1.1
2. Build sources with cmake: `cmake .`
3. Profit.

I normally configure with `cmake -DBUILD_DOXYGEN=ON .`, which fails in the same way. 

## Additional info
I use COPR to build RPMs of olive for Fedora and RHEL, which uses mock to build packages in a clean environment/chroot (no "contamination" with dependencies already installed), so I believe it is not related to doxygen.
The copr repo is located here: https://copr.fedorainfracloud.org/coprs/bebosudo/olive-editor/
The scripts used to build RPMS on copr are available here: https://github.com/bebosudo/olive-editor-rpm/ (I just changed version from 0.1.0 to 0.1.1, nothing else).
A manual build produces the same result.

I tried searching for the file reported, but I didn't find it; is it produced during the cmake/build?
If you need further info, don't hesitate to ask. Thanks for your work!

**Comment by itsmattkc** [comment]
This was overlooked when I made the release and fixed by #1069, I may create 0.1.2 to address this

**Comment by bebosudo** [comment]
@itsmattkc If you could create a new release I could update the RPM packages for Fedora and EPEL 7.

**Comment by muziker** [comment]
I'm getting this as well. Should i use 0.1.0 and replace that file?

**Comment by muziker** [comment]
I removed the translation for compilation to work
