### ISSUE TITLE
Play back quality [Feature Request]

### ISSUE THREAD

**Issue by zakkichukak** [olive-editor/olive#1075]
Pleas add feature for playback quality for making faster to play video. like feature in Adobe After Effect, (Full, Half, Quarter) like that. when I work for FHD my computer so lag

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Do you know any libraries or sources that can help the Olive Team include the feature?**
List open-source libraries related to the feature.

**Additional context**

**Comment by Simon-Laux** [comment]
can you remove the placeholder part that you didn't fill out?

**Comment by CodigoCristo** [comment]
.Edit text directly on screen
.Video quality  1/2 1/4 1/8 
![image](https://user-images.githubusercontent.com/34531165/65833760-3810a780-e299-11e9-91f4-aa03f8ae890f.png)
