### ISSUE TITLE
[Bug] Dropdowns do not appear due to focus policy in KDE Plasma on Debian Stretch

### ISSUE THREAD

**Issue by gerrycocco** [olive-editor/olive#1077]
**Setup:**
- Olive (April 2019 | Alpha | 1e3cf53)
- Source: AppImage
- Operating system:    Linux sake 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux
- CPU: Intel i7-4790S (8M Cache, up to 4GHz)
- RAM: 16GB
- GPU: Intel HD Graphics 4600 

**Describe the Bug**
This is new installation (appImage).  As I was following a tutorial for my first session, I noticed that dropdowns did not work.  It turns out it is a "Focus Policy" issue on my KDE setup.  I can modify it slightly and the dropdowns work as designed.

I'm filing this bug for two reasons:
1) It's a subtle problem that happens on first use  of the software and could be mistakenly attributed to Olive.  It is hard to diagnose, but easy to "fix" for this user.

2) At some point way  down the development cycle, it might be  nice to detect this condition on Olive startup and warn user.  I understand this bug probably affects a small part of the user community, but it does adversely affect first use, which is very frustrating.

**To Reproduce**
1. Attempt to click on a dropdown (for instance "Add Title")
2. Nothing happens
![image](https://user-images.githubusercontent.com/4722852/64045996-4ea7cf80-cb30-11e9-8163-c4e46fe0f9a0.png)

3. Current Settings of Window Focus Policy (Focus Strictly Under Mouse)
![image](https://user-images.githubusercontent.com/4722852/64046032-68e1ad80-cb30-11e9-837c-3c50a342b905.png)

4. Change Setting of Window Focus Policy (Focus Under Mouse)
![image](https://user-images.githubusercontent.com/4722852/64046106-9e869680-cb30-11e9-8c4f-b08aa3d73d4a.png)

5. Dropdowns now show up
![image](https://user-images.githubusercontent.com/4722852/64046140-b1996680-cb30-11e9-8881-c6e2eee6ffd0.png)

**Debug Log and/or Crash Report**
Not applicable.

**Additional Details**
I expect the best use for this "bug" is to close it and have it in the searchable bug list.  Perhaps it will help someone in the future.  Thanks for all the hard work on Olive!  It is coming along great.

**Comment by elsandosgrande** [comment]
That's the default policy in Debian? I had to manually switch to it. Either way, KDE's hover-controlling policy is not that great in comparison to GNOME's. I am speaking as a former GNOME and current KDE user.

**Comment by gerrycocco** [comment]
No.  That is NOT the default, so it probably doesn't affect that many folks.  I've had this set this way for many releases now.  It turns out I can use a less "severe" setting and get the same effect I want, so I now have it set there.  

The behavior I want and was never able to duplicate in GNOME is this: when you have overlapped windows, you can hover over and type into the window that is partially covered and it does NOT get raised.  At least when I had tried this many moons ago, GNOME couldn't do that.  Other than that, I  could work with either one.

**Comment by elsandosgrande** [comment]
@gerrycocco What is it? I had the most severe one without it being the one selected above, but it was still a pain.

**Comment by gerrycocco** [comment]
I'm sorry.  I don't understand your question.

**Comment by elsandosgrande** [comment]
"Which setting?" is what I meant.

**Comment by gerrycocco** [comment]
"Focus under mouse" and those to the "left" in the menu **work**.  I show  that system setting above.
"Focus strictly under mouse" - causes Olive to **fail**.  By fail, I mean I don't see any dropdown menus when using Olive.

I am now using "Focus under mouse" and everything I like to do with that setting works for me.  The old setting "Focus strictly under mouse" was a hold over from many releases ago when things worked differently.  Olive is the first application I am using that had a problem with it.

**Comment by elsandosgrande** [comment]
In my experience, the setting to the left of it is nice as well and still has focus stealing prevention to boot!
