### ISSUE TITLE
[Bug] Reducing frames per second results in visual artifacts

### ISSUE THREAD

**Issue by CMCDragonkai** [olive-editor/olive#1078]
**Your Setup:**
- Olive version (window title or Help > About): Olive (April 2019 | Alpha)
- Source: (e.g. AppImage, PPA, AUR, website etc.) NixOS
- Operating system: (e.g. Ubuntu 18.04 64-bit) NixOS
- CPU: (e.g. Intel i5-4300U) Ryzen 7 and Intel
- RAM: (e.g. 8GB) - 8 and 16
- GPU: (e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx)) - GTX 580 and RTX 2070

I've tried this on Linux olive-editor and Windows olive-editor. Same problem.

**Describe the Bug**

I've recorded videos in 50 fps on my gopro. When I try exporting to a video with only 25 FPS. The resulting video has many visual artifacts including random pixels, colours... it's just garbage.

I'm not sure if this is happening due to something in the encoding or if it specific to gopro footage. But surely I should be able to reduce 50fps to 25 fps by just dropping frames?

**Comment by CMCDragonkai** [comment]
@itsmattkc Does this mean it no longer happens?

**Comment by itsmattkc** [comment]
I don't believe 0.2 exhibits this issue, if it does feel free to update here.
