### ISSUE TITLE
[Bug] Split and delete not working as intended.

### ISSUE THREAD

**Issue by Mayravixx** [olive-editor/olive#1079]
**Your Setup:**
- Olive version: April 2019 Alpha 1e3cf533
- Source: Website
- Operating system: Windows 10
- CPU: AMD Phenom II X4 955
- RAM: 7GB DDR3
- GPU: NVIDIA GeForce GT 610 (391.35)

**Describe the Bug**
Simply put: I'm trying to edit a small project, and I'm not able to split audio or video and have it behave as it's own separate clip, any time I try to delete it, it seems to delete the whole thing it's attached to, even unlinking it doesn't seem to help.

The only thing that does is deleting the selection and then undoing the delete, this seems to result in them acting as two separate pieces.

**To Reproduce**
1. Import video
2. Drag it to the timeline
3. Click at any random point in the video and click "split"
4. Attempting to delete it will cause both parts to be removed.
5. Undo the deletion and click the section you want to remove and it'll work fine.

**Screenshots**
Not quite a screenshot, but I do have this: 
![olivebug](https://user-images.githubusercontent.com/50846413/64186321-3f789880-ce34-11e9-89ed-8c3e547a8503.gif)

** Debug Log and/or Crash Report **

```
[Paste log/report]
```

**Additional Details**
Add any other information about the problem here.

**Comment by NathanSalapat** [comment]
When you split the track both haves are selected. Click on another track and then on the split half you want to delete.

**Comment by Mayravixx** [comment]
Ah ok, thanks
