### ISSUE TITLE
Select time region / "work area"

### ISSUE THREAD

**Issue by maingi2** [olive-editor/olive#108]
This feature will likely be added at some point since it appears in both Vegas and Premiere, I am just mainly documenting the main uses of it.

In Vegas, there are actually "two" bars where the playhead rests. The top is for selection and markers, and the bottom is like a ruler for seconds/minutes/hours. In that workflow, people just click on the timeline rather than moving up to the playhead each time. While the bottom bar allows for the same "time scrubbing" as in Adobe editors, dragging along the top in Vegas is a selection, which can also be looped through right click, but the main purpose is likely so that a specific region is exported. The top bar right click menu is also used for markers of time or regions of time.

**Comment by itsmattkc** [comment]
I'm not sure about having two bars for this, but a work area selection is definitely on its way.
