### ISSUE TITLE
Website download not up to date.

### ISSUE THREAD

**Issue by N6REJ** [olive-editor/olive#1080]
Just went to website to update my install of olive ( ability to update from within would be great ) 
and was surprised to find the download out of date.
![image](https://user-images.githubusercontent.com/1850089/64283572-53e49000-cf1d-11e9-9370-5c693a823b1b.png)

Win 10 x64 pro

**Comment by rubenwardy** [comment]
That is the latest release. The next version has been in development for the last few months, and so April is the last stable release

**Comment by N6REJ** [comment]
oh, cause I looked @ releases and see https://github.com/olive-editor/olive/releases/tag/0.1.1
ok, ty.
