### ISSUE TITLE
[Bug] Extra file in image sequence export

### ISSUE THREAD

**Issue by eliemichel** [olive-editor/olive#1088]
**Your Setup:**
- Olive version: Olive (April 2019 | Alpha | 1e3cf533)
- Source: Website
- Operating system: Windows 10
- CPU: Intel i5-7400 3GHz
- RAM: 16GB
- GPU: NVIDIA Geforce GTX 1070 6GB (Driver ver 23.21.13.8819))

**Describe the Bug**
When exporting as a sequence of images, an extra file is created with the formatting string not evaluated, e.g. "frame%05d.png" instead of "frame00000.png".

**To Reproduce**
1. Create some project and sequence
2. Export as a sequence of PNG
3. Look at the export directory

**Screenshots**
![olive-bug001](https://user-images.githubusercontent.com/5802849/64760613-70468500-d53a-11e9-9e9d-47996086eded.png)

**Comment by sobotka** [comment]
Master is still undergoing significant development.

**Comment by eliemichel** [comment]
Euh yes, but don't you want to keep this open as some kind of milestone or reminder while developping? What is the point of a bug tracker if threads are closed "because the whole project is wip"? Should we wait for a v1 for reporting any bug?

**Comment by sobotka** [comment]
It’s a fair question. I’d prefer to close it down until development is at a useful level and there are significant enough numbers to maintain the tracker in a sensible manner as well as tackle issues. That isn’t the case currently, and an accruing list isn’t useful to anyone.

**Comment by eliemichel** [comment]
Fair enough! I'm not well aware of the current status of the project. BTW do you plan on tagging issues with labels such as "easy fix" or "good first issue", something to help newcomers to give a shot at contributing?
