### ISSUE TITLE
Compilation on Linux fails

### ISSUE THREAD

**Issue by sc3sc3** [olive-editor/olive#1090]
Olive version: latest git source
Operating system: Ubuntu 16.04 64-bit
CPU: Intel i7
RAM: 16GB
GPU: NVIDIA Geforce GTX 1060 3GB

When building latest git source on Linux compilation fails:
https://pastebin.com/whFpAzdt
( cc1plus: all warnings being treated as errors )

When manually removing -Werror make option then compilation fails also:
https://pastebin.com/3NPcUgn4

Thanks for any insight.

**Comment by itsmattkc** [comment]
Olive currently requires OpenImageIO 2.0+ and won't compile with 1.x. The master is also highly unstable at the moment, it's recommended you use a release from the releases tab.
