### ISSUE TITLE
[Bug] Sequence Viewer's timeline freezes Olive

### ISSUE THREAD

**Issue by blopware** [olive-editor/olive#1091]
**Your Setup:**
- Olive (April 2019 | Alpha | 0ac9dd9)
- Source:  AUR
- Operating system: ArchLinux

**Describe the Bug**

**To Reproduce**
1. Import any video and add it onto a video sequence.
2. Click on the right most edge of the Sequence Viewer's horizontal scroll bar in order to zoom the timeline. 
3. Without releasing the mouse button, move the cursor to the left most part of the screen. 
4. Release the mouse button. Olive can not recover from this step.

The problem seems to be in TimeLineHeader::paintEvent. The code won't ever break the condition 
`if (lineX > width()) break;`, so the infinite loop keeps running.

**Comment by AGI-THB** [comment]
Your Commit-Hash indicates your version is from february, not april.

Use a recent version.
