### ISSUE TITLE
[Bug] No audio in first 5 seconds with mkv

### ISSUE THREAD

**Issue by razcore-art** [olive-editor/olive#1092]
Brief thanks: it isn't stated enough in my opinion how much gratitude we have for developers in open source projects so thanks a lot for giving us the tools we would otherwise not have access to!

**Your Setup:**
- Olive version (window title or Help > About): Olive (April 2019 | Alpha | 1e3cf53)
- Source (e.g. AppImage, PPA, AUR, website etc.): website
- Operating system (e.g. Ubuntu 18.04 64-bit): Ubuntu 19.04 64-bit
- CPU (e.g. Intel i5-4300U): Intel® Core™ i7-4710MQ CPU @ 2.50GHz × 8
- RAM (e.g. 8GB): 16GB
- GPU (e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx)): GeForce GT 750M/PCIe/SSE2 (Driver ver. 430.50)

**Describe the Bug**
Like the title says, not much more than that: first 5 seconds of the mkv clip have no sound when previewing in Olive. This is per video strip, not per project. I haven't tried rendering yet to see if this persists.

**To Reproduce**
1. Make a sequence with the attached clip
2. Preview it and notice that there's no audio in the first 5 seconds of the clip

** Debug Log and/or Crash Report **

```
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing custom cursors (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Clip opened on track 0 (took 61 ms) (:0, )
[INFO] Clip opened on track -1 (took 63 ms) (:0, )
[INFO] Auto-recovery project saved (:0, )
```
I haven't seen anything suspicious in the logs

**Additional Details**
Play the mkv file in any other player and notice that there's audio in the first 5 seconds.

[2019-09-21 14-21-00.zip](https://github.com/olive-editor/olive/files/3638620/2019-09-21.14-21-00.zip)

**Comment by razcore-art** [comment]
I just tested it and unfortunately this happens on render/export as well.

**Comment by Ryuji12** [comment]
I have the same problem.
I use OBS to record desktop, you too?
I will try another video editor. If this problem comes out again, I think the problem is with OBS and not Olive.

**Comment by razcore-art** [comment]
Yeah I only got `mkv`s from OBS but it doesn't make any sense that OBS would be the problem since other editors (eg. Blender) or any other video player has no problem properly playing the files so...

**Comment by djnotes** [comment]
Me too. This is really annoying. It seems using CBR for recording and using frame interval of 2 helps but still this is happening. Not specific to MKV by the way, ridiculous audio mutes when previewing the video occur with almost every type of video.

**Comment by sobotka** [comment]
Work on `0.1.x` has ceased. Test against current master.

**Comment by djnotes** [comment]
@sobotka did you see  #1102 ?

**Comment by sobotka** [comment]
I haven’t.

The codec landscape is a bit of a nightmare, so it might be wise to block specific encodings and then unblock them as they are sorted out.
