### ISSUE TITLE
Compilation fails on Linux Mint 19

### ISSUE THREAD

**Issue by amsaid1989** [olive-editor/olive#1093]
**Your Setup:**
- Olive version (window title or Help > About): 0.1.1 release
- Source: Source code
- Operating system: Linux Mint 19 Tara
- CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
- RAM: 32 GB
- GPU: NVIDIA GeForce 1080 TI

**Describe the Bug**
Can't compile Olive from source. I can install from the repositories, but I would like to be testing the newer builds. I tried compiling the 0.1.1 release version, but it failed.

**To Reproduce**
Just followed the compiling guidelines installing everything required.

** Debug Log and/or Crash Report **

https://pastebin.com/7Md1GeUa

**Comment by AGI-THB** [comment]
Why are you reposting?
There is no need to open new tickets, when the compilation issues can be discussed in an already existing ticket.

#1090

**Comment by amsaid1989** [comment]
I checked the output posted in that ticket and it seemed like there might be different reasons for why compilation is failing.

Also, in the #1090 issue, the OP seems to be compiling from the master, while I am compiling from the latest release on the releases page, so I thought it made more sense to have a different issue.

I am happy to move to the other issue, of course, if that it would be better.

**Comment by AGI-THB** [comment]
Why not use the appimage?

Version 0.1.1 introduces nothing new.

Use Appimage of Version 0.1 

https://github.com/olive-editor/olive/releases/download/0.1.0/Olive-1e3cf53-x86_64.AppImage

**Comment by Stephen100** [comment]
Are we on **0.1.1** now, fellas?

**Comment by AGI-THB** [comment]
There is nothing new in 0.1.1, except translation updates.

Makes no sense to invest time into fixing the compilation issues for that version.

Just use the Appimage for 0.1

**Comment by amsaid1989** [comment]
That makes sense. Sorry, I missed the Appimage for 0.1. Thought I will have to build from source as well.

Thank you very much. I will close this issue now.
