### ISSUE TITLE
[Feature Request] Text capability to keep an editing log/notes and shotlist.

### ISSUE THREAD

**Issue by Exomancer** [olive-editor/olive#1094]
**Is your feature request related to a problem? Please describe.**
It would be very helpful to have a simple text capability to keep an editing log or notes and a shotlist.

**Describe the solution you'd like**
A simple text capable pane.

**Describe alternatives you've considered**
Use an external text editor.

**Do you know any libraries or sources that can help the Olive Team include the feature?**
Sorry I'm not a coder.

**Additional context**
KEDnlive has a Project Notes pane.

**Comment by sobotka** [comment]
#1003
