### ISSUE TITLE
[Design] Keyboard Interactions

### ISSUE THREAD

**Issue by sobotka** [olive-editor/olive#1097]
Collection of information on keyboard interactions.

 * [Baselight keyboard shortcut outline](https://www.filmlight.ltd.uk/resources/download.php)
 * Lightworks
![F2568271-FAC6-462E-B58C-B3CDC7F91556](https://user-images.githubusercontent.com/59577/65807749-e0612780-e144-11e9-934a-aa7371a74da3.jpeg)
 * [Avid Media Composer](http://resources.avid.com/SupportFiles/attach/Keyboard%20Shortcuts.pdf)

**Comment by tin2tin** [comment]
If Olivie could support a common Keyboard Preferences file format, then it would be easy for people to move their personalized shortcut from ex. Avid to Olive. I don't know if such a thing exists, but here are the Preferences files from Lightworks(including Avid and Final Cut)

![image](https://user-images.githubusercontent.com/1322593/65812211-375a1180-e1c4-11e9-888c-75a779a37de5.png)

[Preferences.zip](https://github.com/olive-editor/olive/files/3665133/Preferences.zip)
