### ISSUE TITLE
[Question] When should the next release be expected. 

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#1098]
I know this question might be hasty, but I can't wait to see how the next release will look like. So, when the next release should be expected and is it possible to make a quick release just to see how the program looks like now. 

Besr regards.

**Comment by rubenwardy** [comment]
> so, when the next release should be expected and is it possible to make a quick release just to see how the program looks like now.

You can try out the latest development version, the source code is public. Is the reason you ask for "a quick release" because you can't compile it yourself?

**Comment by AGI-THB** [comment]
Maybe in November. And even then it's still far from finished.

I don't know what you mean by "see how the next release will look like".

The development process can be followed by joing the discord, where people posted pics of the node system and stuff like that.

Most of the changes are internal rewrites, you cannot see that in the running app...

**Comment by malnaanah** [comment]
Actually I am not familiar with the compilation process, but if you can post a step by stap procedre for the latest code (for Ubuntu Linux) I can try it.

I will try joining the Discord too.

Thanks for the reply.

**Comment by AGI-THB** [comment]
@malnaanah  You can close this ticket...

Also: Next time go directly to discord and ask there.
This is an issue tracker and not a QA-forum.
