### ISSUE TITLE
[Bug] Build failure - OCIO not linking correctly?

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#1103]
**Olive Version:**  Git Master
**System:** Arch (updated)

Build failure - opencolorio 1.1.1 installed

```
/usr/bin/ld: /usr/lib/libOpenColorIO.so: undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]'
collect2: error: ld returned 1 exit status
make[2]: *** [app/CMakeFiles/olive-editor.dir/build.make:2824: app/olive-editor] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: app/CMakeFiles/olive-editor.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I only have one libyaml-cpp installed, as per this SO post:
https://stackoverflow.com/questions/36866043/undefined-reference-with-yamlnodescalar

**Comment by AGI-THB** [comment]
Maybe you need version OCIO2. But that is just a guess.

"Olive currently requires OpenImageIO 2.0+ and won't compile with 1.x. The master is also highly unstable at the moment, it's recommended you use a release from the releases tab."

https://github.com/olive-editor/olive/issues/1090#issuecomment-534161113

**Comment by alcomposer** [comment]
I have OIIO2, but I have had OCIO1.1.1 and there have been no issues until today. This does look like a problem on my end (hopefully).

**Comment by itsmattkc** [comment]
I've been able to confirm this is an issue with the most recent **yaml-cpp-0.6.3** update on Arch. Downgrading to 0.6.2 (`pacman -U /var/cache/pacman/pkg/yaml-cpp-0.6.2-1-x86_64.pkg.tar.xz`) allows Olive to compile again. Looks like us Arch users might have to [disable yaml-cpp updates](https://wiki.archlinux.org/index.php/Pacman#Skip_package_from_being_upgraded) until this is fixed.
