### ISSUE TITLE
[Feature Request] DROPPER TO SELECT A SPECIFIC COLOR

### ISSUE THREAD

**Issue by CodigoCristo** [olive-editor/olive#1105]
YOU MUST HAVE A DROPPER TO SELECT A SPECIFIC COLOR - A dropper

![image](https://user-images.githubusercontent.com/34531165/65833551-23cbab00-e297-11e9-888e-f7209bb0e612.png)

They could use this method that they use in gimp

![image](https://user-images.githubusercontent.com/34531165/65834296-2af6b700-e29f-11e9-9064-80587f30c0ef.png)

**Comment by itsmattkc** [comment]
Duplicate of #781, technically this is down to your OS, but the next release should feature custom color picking anyway.
