### ISSUE TITLE
[Feature Request] Auto-Scale check in sequence preference and restore effetcs 

### ISSUE THREAD

**Issue by CodigoCristo** [olive-editor/olive#1106]
-What I do is reduce the dimensions of my timeline to have better performance, but they should add an option to auto scale

![image](https://user-images.githubusercontent.com/34531165/65833946-98084d80-e29b-11e9-864d-ffb3f1a5f4a8.png)

Because then I have to reset each individual clip to fit the sequence change

![image](https://user-images.githubusercontent.com/34531165/65833948-a0608880-e29b-11e9-8bf2-ecc645d4fd47.png)

And the button to restore the overall effects settings

![image](https://user-images.githubusercontent.com/34531165/65834245-c0457b80-e29e-11e9-8048-f3f7d04619fd.png)

**Comment by itsmattkc** [comment]
Right click clip > Auto-Scale
Tools > Auto-scale By Default

Alt+Click values to reset them to their defaults
