### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by chlowden** [olive-editor/olive#1108]
Insert and Lift timeline editing functions for 3 point editing would be excellent. These functions are in all the pro apps and none of the open source ones. Thank you a great app.

**Comment by sobotka** [comment]
What’s a “pro”?

**Comment by chlowden** [comment]
For me, Pro are enterprise class edit apps that have tools that 
correspond to the needs of efficiency, stability and exchange with other 
users / apps. They rely heavily on a lot of very specific keyboard short 
cuts. Avid is best example that comes to mind.

Prosumer edit apps have a tendency to short cut procedures using 
automation and interface sensitive tools. Final Cut X is a good example. 
they are designed to finish projects on the same machine. (Adobe is also 
in here for me, but that is my personal opinion)

Consumer apps use a large amount of automation and are more designed for 
assembling on a timeline for export than editing. Blender VSE is the 
most obvious example but shotcut and Pitivi are not far off.

Each variant serves a specific purpose. I prefer the Avid style because 
that is how I work and I feel that Olive is the closest thing I have 
found so far to this method. My son, on the other hand, prefers the 
consumer app, but then we don't have the same editing ambitions

Thanks

Christopher
