### ISSUE TITLE
Zoom in and out based on marker position

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#112]

**Comment by itsmattkc** [comment]
Seems to be affecting current build - possible regression?

**Comment by itsmattkc** [comment]
I'm somewhat confused as to whether this was ever _actually_ fixed or whether it was half done and the issue was closed anyway... Regardless, along with the timeline drawing revamp in 7800bc4712b951f625754de63484cbf53001f091, this was re-addressed.
