### ISSUE TITLE
[feature request] dragging and dropping media onto timeline automatically imports it

### ISSUE THREAD

**Issue by Ephemeralic** [olive-editor/olive#113]
a feature that was very handy in VEGAS, especially since i'm terrible at file management and bad at remembering paths

VEGAS handles it with a few additional factors in mind. if the media is the first thing imported into the sequence, a box follows asking if you want to mirror the media settings to the project as well. [shown here.](https://www.youtube.com/watch?v=oy4h_6Nufz0) it also snaps the playhead to where you initially dragged the media, which is really nice (though it does not have to work 1:1 like this in olive)

**Comment by itsmattkc** [comment]
Added dragging a file into the timeline in 90035ce54988c6c782833a73ea05e036e62a1abf (togglable as an option in the Tools menu, enabled by default).

Added automatically seeking to a clip when importing in 229674f5e2f6076c6b610981c2a20671f375c5d7 (togglable as an option in the Tools menu, disabled by default).
