### ISSUE TITLE
[PLAYBACK] Negative values in Audio / Video speed parameter freeze up system

### ISSUE THREAD

**Issue by massyntesium** [olive-editor/olive#1177]
**Commit Hash**
4f65e83322481eca4055a021e0b7d32a17ea25d9

**Platform**
Windows 10 64 bit (zip executable)

**Summary**
Choosing non positive value (including zero) in the parameter editor for audio or video, Olive doesn't work anymore: no import, no more disk caching; needed to close forcely the program from task manager

**Additional Information / Output**
I want to report a problem about the parameters of a clip in Olive 0.2.x, and I hope this is the correct section cause this problems are not related only in the playback, but also in the disk cache and a crash of the program (from the playback I have these issues in consequence)

The last version I used is the one of 8 days ago for Windows 10 64 bit.

When I play with the speed parameter of audio and video in the parameter editor, apparently it works fine until I put positive value for it: also the graphic part on the timeline when I change the speed (stretching or enlarge heigth)works at the beginning pretty well (just little graphic UI glitches after few use in case from enlarged clip I stretch it again, but nothing serious).

The problems begin when I put a non positive value (including zero) in the speed parameter of audio or video (I was thinking it could realize a reverse or a static effect): not only the playback freezes and works no more, but also, at least seeing the UI, the Disk caching seems not working anymore (only red bar). Come back in the positive value domain after doing this not change the situation and Olive doesn't work anymore: no playback, no disk caching, importing works but playback doesn't work any more. So I have to close forcely using the task manager, cause it seems freezed.

Sadly now I cannot attach a backtrace cause I haven't the computer with Olive 0.2.x on it, and if you need it I could provide to send to you the report when I could put the hands on it again, but if you try to play with speed parameter in the parameter editor you could have the same effect I had.

Thank you so much for your help :)

**Comment by sobotka** [comment]
If you can’t follow the outline to include hashes, it isn’t fair to expect people to read your issue.

**Comment by massyntesium** [comment]
> If you can’t follow the outline to include hashes, it isn’t fair to expect people to read your issue.
> 
> When you include the commit hash, this can be reopened.

I am sorry. I will correct it ASAP (I notice now there were some labels in the request). Ok I will copy the text foe optional and I respect the guide line. Just a question: what I have to write in the commit hash?

**Comment by sobotka** [comment]
The hash is a commit hash of the version you are using. If you build it locally, it will be the hash of the commit you built. If you downloaded it pre-built, it will probably appear in the filename or the About box. Try to answer the other lines too.

Sorry to be strict, but the last time the issue tracker was opened, there were hundreds of reports that were creating work. The trick to a good report is to do all of the work in advance so a volunteer can spend a few minutes to make the issue easier to track and ultimately solve.

**Comment by massyntesium** [comment]
@sobotka I made the correction as I saw in the template of a basic issue report (don't know why I notice it now). I hope it is good now :)

Thank you for your patience :)

**Comment by sobotka** [comment]
If you can get a backtrace, it will help tremendously. Thanks.

**Comment by massyntesium** [comment]
> If you can get a backtrace, it will help tremendously. Thanks.

I hope to put hands on my pc ASAP, cause I haven't it now. When I take it again I will do it!

**Comment by ThomasWilshaw** [comment]
I'm getting slightly different issue here (Windows 7,  dbd54d06 , Debug). For videos the speed control sort of works as expected, greater than `1.0` makes the clip faster and less than `1.0` makes it slower. However the length of the clip doesn't change in the timeline, if the speed has been increased the last frame is displayed for the remaining length of the original clip length and if the speed is decreased we lose some of the end of the clip.  If the speed is `0` or less we Olive just displays the first frame for the original length of the clip. The caching also behaves strangely, if the clip is made slower it caches every nth frame at first.

For audio it is much the same except setting the speed value to `0` or less results in a fatal assert error:
```
[WARNING] Tried to allocate sample buffer with zero sample count (void __cdecl olive::SampleBuffer::allocate(void):134)
[FATAL] ASSERT: "nb_samples > 0" in file C:\Users\Tom\Documents\repos\olive\app\codec\samplebuffer.cpp, line 287 ((null):287)
```

I guess a short term fix here would be to set a minimum value for the audio speed of `0.001` or something?
