### ISSUE TITLE
Playback Lags a Lot.

### ISSUE THREAD

**Issue by thatoneXman** [olive-editor/olive#1180]
1e3cf533

Windows 10

I've used Olive before. It's a Great program. But On my Crappy 2013 Dell Laptop, The playback makes it so I am Unable to Edit my Videos. I REALLY hope this is just me. What can I do?

**Comment by elsandosgrande** [comment]
@thatoneXman Olive 0.1.x has been deprecated for some time now. If you can, compile the latest commits from the master branch and try to reaffirm the issue. If you cannot, wait until the continuous (master) builds have been reinstated, which should not take long (***should***, not _will_).

Have a nice day!

**Comment by Simran-B** [comment]
In addition, fill out the issue template and provide actionable information in future reports. If your hardware is too weak, then the only solution is buy better one I suppose.

**Comment by thatoneXman** [comment]
I didn't Know I had version 0.1. I don't know how to check what version I have.

**Comment by itsmattkc** [comment]
I've updated the sticky to make it clearer what hash/version 0.1 is.

**Comment by Simran-B** [comment]
Anything from 2019 is definitely obsolete, and I would even say any version older than a 2-3 months is.
