### ISSUE TITLE
[CRASH] Switching to a different sequence in a project and changing the value of a node = SEGFAULT

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#1182]
**Commit Hash**
b1c3b0e4511bd39c038f0e8d1a3ad671e12099a3

**Platform**
Ubuntu Focal Fossa, FFmpeg 4.2.4, Qt 5.12.8

**Summary**
Changing some value of a node, like volume or speed, in a sequence after switching sequences and closing without saving will result in a segmentation fault.

**Steps to Reproduce**
http://mellemws.my.to/direct/Screencast_from_2020年09月14日_20時29分52秒.webm

**Backtrace**
[backtrace b1c3b0e one.txt](https://github.com/olive-editor/olive/files/5220283/backtrace.b1c3b0e.one.txt)

**Additional Information**
I have, thus far, only tried changing the speed of a clip and the volume of a clip.  
Doing the same things without changing the sequence, that is changing the volume of a clip in the sequence with which the project opens does not result in the crash above: http://mellemws.my.to/direct/Screencast_from_2020年09月14日_20時37分34秒.webm

**Comment by elsandosgrande** [comment]
_I'm really horrible at titling things…_

**Comment by elsandosgrande** [comment]
I have reaffirmed the issue with 67f0795795f2425e840b69bf6e124cb8430abbb7.

**Comment by AngeloFrancabandiera** [comment]
I have tried to dig a little into the problem under Ubuntu 19.10. When there are more than one sequence, as long as no clip is selected (empty node graph scene), you can switch between sequences as long as you want, without any problem. But when a clip is selected, when you switch sequence, function

NodeView::UpdateBlockFilter()

is invoked. It seems that 'selected_blocks_' still holds the reference to the items of the clip of previous sequence. However, method

NodeViewScene::ReorganizeFrom()

tries to set the position of the first node of previous scene, thus invoking slot

NodeViewScene::NodePositionChanged()

In this method, hash table 'item_map_' holds the node for the new scene, but 'sender()' is a node for the old scene. Hash table returns a NULL object whose invocation of method 'SetNodePosition' result in segmentation fault.

**Comment by itsmattkc** [comment]
Ah thanks for the analysis @AngeloFrancabandiera. Much of that code has been changed now, so can you confirm if this issue is fixed in the latest commit @elsandosgrande?

**Comment by AngeloFrancabandiera** [comment]
I have tried under Windows 7 with nightly build: cd6544ba.
I can reproduce the same problem. You can find the crash report attached.

Tonight I will try the same on Ubuntu 20.04

[crash.txt](https://github.com/olive-editor/olive/files/6210009/crash.txt)

**Comment by itsmattkc** [comment]
Looks like a very different source either way, so if it's still occurring it's probably a similar presentation of a different bug.

**Comment by elsandosgrande** [comment]
@itsmattkc I don't have that project file anymore (I deleted it along with the Arri test footage, since I needed the space :sweat_smile:), so I can't try replicating it exactly, but I haven't been able to replicate it with a new project which has never been saved. I'll try it with a saved project (a project that is actually in storage), but I wouldn't get your hopes up. 

Side note  
I actually ran into a completely different bug while trying to reproduce this one. I'll see if it has already been reported and report it if it has not yet been.

@AngeloFrancabandiera Given how much has changed with regards to the node structure, exactly which nodes have you manipulated?

**Comment by AngeloFrancabandiera** [comment]
Actually I did not manipulate the values of a node. What I did is:
- create two sequences
- put a clip on one sequence (I used a still image)
- select the clip on the timeline
- switch to the other sequence  ==> crash

**Comment by AngeloFrancabandiera** [comment]
On Ubuntu 20.04 the problem can't be reproduced. I can switch between sequences without any problem.

**Comment by elsandosgrande** [comment]
> On Ubuntu 20.04 the problem can't be reproduced. I can switch between sequences without any problem.

What about when you close Olive? Watch the screen recording and replicate everything done in it (create two sequences with video, modify the volume for example, switch between them, and close Olive without saving).

My gut tells me that this is no longer an issue though.

**Comment by AngeloFrancabandiera** [comment]
I have tried to reproduce the steps in the screen shot with version f99600ed on Ubuntu and on a different Windows machine. I did not experience any crash in either machine; I could not even replicate the crash I had yesterday on my PC at work. (Our IT is introducing much shit-ware on our workstation to enhance security).
For me this is no longer an issue also.

**Comment by elsandosgrande** [comment]
@AngeloFrancabandiera Well then, it's settled. This is no longer an issue.
