### ISSUE TITLE
[CRASH] while fiddling with the Ladder gizmo

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#1185]
**Commit Hash**

`76112f70` (x86_64.appimage build)

**Platform**

Manajro Linux 20

**Summary**

Crash after fiddling with the ladder gizmo.

**Steps to Reproduce**

Fiddle with the ladder Gizmo.

**Backtrace**

```
(gdb) bt
#0  olive::SliderLadder::SetValue(QString const&) (this=0x0, s=...) at /home/travis/build/olive-editor/olive/app/widget/slider/sliderladder.cpp:97
#1  0x00000000006bf5aa in olive::SliderBase::LadderDragged(int, double) (this=0x1b13750, value=<optimized out>, multiplier=<optimized out>) at /home/travis/build/olive-editor/olive/app/widget/slider/sliderbase.cpp:311
#2  0x00007ffff2cafb56 in QMetaObject::activate(QObject*, int, int, void**) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#3  0x0000000000537688 in olive::SliderLadder::DraggedByValue(int, double) (this=this@entry=0x2458830, _t1=_t1@entry=-3, _t2=1) at /home/travis/build/olive-editor/olive/app/olive-editor_autogen/VFJFOAHRY6/moc_sliderladder.cpp:214
#4  0x00000000006c0b3c in olive::SliderLadder::TimerUpdate() (this=0x2458830) at /home/travis/build/olive-editor/olive/app/widget/slider/sliderladder.cpp:167
#5  0x00007ffff2cafb56 in QMetaObject::activate(QObject*, int, int, void**) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#6  0x00007ffff2cbc3b7 in QTimer::timeout(QTimer::QPrivateSignal) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#7  0x00007ffff2cbc6b8 in QTimer::timerEvent(QTimerEvent*) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#8  0x00007ffff2cb0823 in QObject::event(QEvent*) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#9  0x00007ffff36fec4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Widgets.so.5
#10 0x00007ffff37062c7 in QApplication::notify(QObject*, QEvent*) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Widgets.so.5
#11 0x00007ffff2c82ad8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#12 0x00007ffff2cd8c4e in QTimerInfoList::activateTimers() () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#13 0x00007ffff2cd94d1 in  () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#14 0x00007ffff0b5a43c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#15 0x00007ffff0ba81d9 in  () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff0b59221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff2cd986f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#18 0x00007fffd1a1df41 in  () at /tmp/.mount_Olive-tY1G55/local/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#19 0x00007ffff2c80e6a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#20 0x00007ffff2c89f74 in QCoreApplication::exec() () at /tmp/.mount_Olive-tY1G55/local/bin/../lib/libQt5Core.so.5
#21 0x000000000052da42 in main(int, char**) (argc=1, argv=0x7fffffffdbc8) at /home/travis/build/olive-editor/olive/app/main.cpp:161
```

**Additional Information**

I was trying to go from the "Default Step" of the ladder to some higher one and it wouldn't move - I kept trying and suddenly my mouse cursor became invisible when hovering over Olive's window - _ realized it has crashed. I run in through gdb at all times.

**Comment by ThomasWilshaw** [comment]
The mouse should disappear when using sliders so you can scroll as far left/right as you want. Couple of questions:
Is this all sliders or a specific slider? 
Does holding Ctrl whilst moving the mouse successfully change the multiplier value? 
Does the console give any useful output here?

**Comment by itsmattkc** [comment]
@unfa Can you tell me which slider you were dragging?

**Comment by boboyadahipo** [comment]
The same happens to me when i to change the value of a slider in the Parameter Editor. I tested it with the Speed and another slider, but i think it happens to all slider.
When i click and hold the value with one of the mouse buttons, the mouse gets invisible and a little multiplier window appears. Now i can adjust the value by moving the mouse. That's fine. But when i click another mouse button while i am doing this and release all mouse buttons, the mouse stays invisible, the multiplier window disappears and i can still adjust the value by moving the mouse. When i now click any of the mouse buttons and move the mouse, Olive crashes.

I am on PopOs 20.04 and using Olive 0.2.0-27a4dbc8.

**Comment by itsmattkc** [comment]
Ahh that's helpful @boboyadahipo, 3103359cd6898fe219af5a1c0c421d1dc20fc54e should fix your issue.

Does that also fix yours @unfa?

**Comment by boboyadahipo** [comment]
I can confirm it. 3103359 fixed the issue i had.

**Comment by unfa** [comment]
> @unfa Can you tell me which slider you were dragging?

I'm sorry, I don't remember unfortunately. It was something random - I just wanted to try the ladder widget.
I can try to reproduce it with a new build.

**Comment by itsmattkc** [comment]
If you'd like, unless you assume your bug is the same as @boboyadahipo's in which case we'll close this unless you encounter it again

**Comment by unfa** [comment]
I think we can close it for now and assume it's fixed. If it creeps up again I can reopen the issue.
