### ISSUE TITLE
Olive 0.2 won't start on windows 10

### ISSUE THREAD

**Issue by kiltel** [olive-editor/olive#1188]
Olive 0.2 won't run on windows 10. Messages about missing .dll files are popping up.

![olive 0 2](https://user-images.githubusercontent.com/5685617/93396363-d1a0e280-f877-11ea-8763-feee90bc7065.png)

![olive](https://user-images.githubusercontent.com/5685617/93396797-8804c780-f878-11ea-9cb2-69f2a23cfdca.png)
![bl](https://user-images.githubusercontent.com/5685617/93396803-8a672180-f878-11ea-838d-4fdca5b54890.png)

**Comment by Simran-B** [comment]
Looks like it's a debug build, because it seems to be searching for debug libraries (`*d.dll`). The missing ones are all related to Microsoft Visual C++. Microsoft doesn't allow to ship the debug versions of these runtime libraries.

Olive should be compiled in a RelWithDebInfo config instead of as Debug (I thought this was already fixed?). As a workaround, you may install Visual Studio and the Windows SDK, which come with the necessary files.

**Comment by Beastmastah64** [comment]
same
![image](https://user-images.githubusercontent.com/61039641/93409184-eb601b00-f8b3-11ea-8611-9808266d683c.png)

**Comment by itsmattkc** [comment]
Current download ix fixed.

**Comment by kiltel** [comment]
Now, after downloading the current version, this error pops up.
![Bez nazwy](https://user-images.githubusercontent.com/5685617/93429296-36ccf600-f8c1-11ea-86bc-c98efd562adc.png)

**Comment by itsmattkc** [comment]
Try installing the latest Visual C++ redistributable: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Simran-B** [comment]
The error message just says that the application did not start properly. The code appears to be `STATUS_INVALID_IMAGE_FORMAT`. Possible causes are indeed missing libraries, or an incompatibility e.g. as a result of Windows-as-a-service. What Windows 10 build version are you on?

The GitHub virtual environment `windows-latest` is Microsoft Windows Server 2019 Datacenter, OS Version: 10.0.17763 Build 1397. As it starts just fine on my end on Windows 10, I doubt that there is a general incompatibility.

**Comment by kiltel** [comment]
I use Windows 10 Pro build: 2004, version:19041.508
