### ISSUE TITLE
[UI] Olive Dark

### ISSUE THREAD

**Issue by klwemu** [olive-editor/olive#1189]
**Commit Hash**

**Platform**
Win10

**Summary**
Text in menu not visible with Theme "Olive Dark".

![Olive Dark](https://user-images.githubusercontent.com/3965097/93449807-7bfb2300-f8d5-11ea-826e-17365df41f97.png)

**Comment by ThomasWilshaw** [comment]
Please provide a commit hash as per the pinned issue. Thanks

**Comment by klwemu** [comment]
Commit Hash
007b9f2

**Comment by itsmattkc** [comment]
Confirmed Qt bug starting with Qt 5.15: https://bugreports.qt.io/browse/QTBUG-85226

**Comment by itsmattkc** [comment]
Worked around in b5863fdadd91d531fc70c656cd7b0eacfa53e93f

**Comment by Simran-B** [comment]
When using linuxdeployqt, I always see these warnings:

```
WARNING: Plugin "/usr/local/plugins/platformthemes/libqgtk2.so" not found, skipping
WARNING: Plugin "/usr/local/plugins/styles/libqgtk2style.so" not found, skipping
```

Could that be related?

**Comment by itsmattkc** [comment]
Nah unrelated, those are plugins for getting Qt to use GTK's native theming/dialogs instead of Qt's own.
