### ISSUE TITLE
[EDIT] Minor visual glitches in timeline

### ISSUE THREAD

**Issue by klwemu** [olive-editor/olive#1190]
**Commit Hash**

**Platform**
Win10

**Summary**
When you delete a clip wich is a bit longer displayed on screen (does not depend on the real clip time length) a part is visually not deleted.

**Additiona
![Delete Clip](https://user-images.githubusercontent.com/3965097/93452061-4277e700-f8d8-11ea-8e90-ce3d7e10f8d1.png)
l Information / Output**

**Comment by ThomasWilshaw** [comment]
Please provide a commit hash. Thanks.

**Comment by klwemu** [comment]
Commit hash:
007b9f2

**Comment by itsmattkc** [comment]
I've seen this before. I believe it's bugs in Qt's update system that we can workaround by setting the TimelineView to `QGraphicsView::FullViewportUpdate`. That's technically less optimized, but should address such glitches.
