### ISSUE TITLE
[CRASH] Clip speed change with keyframes

### ISSUE THREAD

**Issue by klwemu** [olive-editor/olive#1192]
**Commit Hash**
007b9f2

**Platform**
Win10

**Summary**
Change Clip Speed with Keyframes. There are serveral issues:
1. Speed change is not affecting in Preview
2. Length of final rendered clip (if rendering finishes) is not correct
3. Olive crashes after MP4 file rendering is finished

**Steps to Reproduce**
![Speed-Keyframes](https://user-images.githubusercontent.com/3965097/93513889-cd7fce00-f926-11ea-9614-a9513935c350.png)

**Backtrace**

**Additional Information**

**Comment by ThomasWilshaw** [comment]
Can you provide the console output for the operations and a backtrace for the crash if possible. See here for instructionson to generatea backtrace: https://github.com/olive-editor/olive/wiki/Debugging-Olive

**Comment by klwemu** [comment]
Does not crash now.   :-( 
But nevertheless it does not work at all.  And if you change the speed the timeline should become longer/shorter.
