### ISSUE TITLE
[UI] Color Selector is limited to 3 hues (Cyan, Magenta and Yellow)

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#1199]
**Commit Hash (8 character string of letters/numbers in title bar)**
`3103359c` (Olive-3103359c-x86_64.AppImage)

**Platform**

Manjaro Linux 20

**Summary**

I've created a Solid Color strip and wnated to change the color, this is what I got:
![image](https://user-images.githubusercontent.com/491704/93638229-39ca0280-f9f7-11ea-8f47-d7032718d3df.png)

**Comment by itsmattkc** [comment]
Known issue with the AppImage unfortunately. Might have to compile it yourself while we work that out.

**Comment by itsmattkc** [comment]
I've disabled the AppImage for now, we can expect the newest to address this problem
