### ISSUE TITLE
[CRASH] Importing Alexa mini raw mxf container

### ISSUE THREAD

**Issue by Gluke79** [olive-editor/olive#1201]
**Commit Hash (8 character string of letters/numbers in title bar)**

**Platform**
Win 10
**Summary**
Whend drag&drop mxf files from Arri Alexa mini Olive just close without any message
**Steps to Reproduce**
open Olive, drag&drop an Alexa mxf raw file
**Backtrace**

**Additional Information**
Maybe can be related to an unsupported arriraw sdk

**Comment by itsmattkc** [comment]
MXF files should be compatible, could you send the video? You can DM it to me if you don't want to make it public.

**Comment by Gluke79** [comment]
Unfortunately I cannot share the footage since is part of the movie I'm working on, but I can try to reproduce the crash importing some sample footage from Alexa.

**Comment by itsmattkc** [comment]
That's understandable, yeah if you can find any sample footage that exhibits the same issue, do let me know

**Comment by Gluke79** [comment]
Changed from laptop (gtx 1060) to a workstation (gtx 1080ti) and tested with a sample footage.
Now Olive doesn't crash, imports the file but it doesn't recognize the codec. It's definitely a missing importer based on Alexa sdk.
Are you planning to implement it?

![image](https://user-images.githubusercontent.com/57181019/93768583-e388d980-fc19-11ea-855f-936d8d823da1.png)

**Comment by ThomasWilshaw** [comment]
I know you can't share the footage but can you give us an`ffprobe` of the clip/s in question?

**Comment by Gluke79** [comment]
Sure I can, It's a sample footage.
Here is the link:

https://arriwebgate.com/directlink/77689a9b6ef6ddc1/995148

**Comment by ThomasWilshaw** [comment]
Thanks, I thought this was still your footage. I'll give it a test later.

**Comment by ThomasWilshaw** [comment]
I didn't realise this was Arri raw footage, sorry about that. Olive currently has no support for any raw formats but it is an eventual goal once Olive is stable. Here's a link to Arri's raw converter for anyone coming across this issue:
https://www.arri.com/en/learn-help/learn-help-camera-system/tools/arriraw-converter

Also here's a link to the partner program for future reference:
https://www.arri.com/en/company/about-arri/partner-programs/camera-partner-program

**Comment by itsmattkc** [comment]
Yeah unfortunately ARRIRAW is not currently supported (DNxHD is though), and while we would like to implement it eventually, it may take some time since it appears partnering with ARRI directly is necessary to acquire the SDK. So hopefully eventually, but no ETA on it. I'll close this issue for now.
