### ISSUE TITLE
[Node Editor] Nothing appeared on [Squence Viewer: Sequence 1]

### ISSUE THREAD

**Issue by alex2345** [olive-editor/olive#1202]
Step1. Make a Sequence, then drag your [video clip.mp4] onto timeline;
Step1.  Delete the link between [Video input] and [video clip.mp4];
Step2. Add > Filter > [Blur];
Step3. Link [Video input] to [Blur], then link [Blur] to [video clip.mp4];

Step4. Click on [Blur] then see [Parameter Editor: Blur], 
you can see all parameters of the [Blur],
but you can not see anything on the [Squence Viewer: Sequence 1],
there is no available [Preview window] for the [video clip.mp4],
so I said Nothing appeared on [Squence Viewer: Sequence 1].

Hope you understand what I said,
I mean, I have no  [Preview window] 
for the [video clip.mp4] when I use [Node Editor] on Olive 0.2.

**Comment by itsmattkc** [comment]
When you connected the blur node to the clip node, did you connect to the "buffer" input specifically?

**Comment by alex2345** [comment]
> When you connected the blur node to the clip node, did you connect to the "buffer" input specifically?

Oh, I've not noticed on the options before your hint (the icon is too small, any suggestion to enlarge it?  I'm using Win10),

there are 2 options [Speed | Buffer], could you please tell me what does [Speed] mean?

I've seen the video on [Squence Viewer: Sequence 1] now, Thank you very much!

**Comment by itsmattkc** [comment]
The speed input is for controlling the speed of the clip. Buffer is for the image/audio.
