### ISSUE TITLE
[Disk Cache] SSD only ? 

### ISSUE THREAD

**Issue by alex2345** [olive-editor/olive#1203]
Generally, the physical speed of the hard disk is actually much slower than DDR memory,

unless everyone uses static SSDs for the video editor,

or it is better to cache video or any things that need speed on the DDR memory (or GPU memory).

it is my personal experience for your reference.

**Comment by itsmattkc** [comment]
We're aware of the speed differences between memory and disk. Of course we recommend SSDs, but in my experience, the cache has been very performant even when storing it on a mechanical disk.
