### ISSUE TITLE
[CACHE] Olive becomes unstable after changing the speed of a clip

### ISSUE THREAD

**Issue by ZoomTen** [olive-editor/olive#1204]
**Commit Hash (8 character string of letters/numbers in title bar)**
0798dbb0

**Platform**
Manjaro Linux 20.1, manual build

**Summary**
Sometimes, after changing the speed of a clip, Olive couldn't cache frames anymore and playback is no longer possible. Additionally, Olive freezes entirely after creating a new sequence and opening it.

**Steps to Reproduce**
1. Run Olive through `gdb olive-editor`, `run`.
2. Drag a video file from a file manager to the project bin.
3. Drag the video file to the timeline, creating a new sequence.
4. Go into the parameter editor, and change the speed of the clip several times.
5. A situation happens where the timeline cache bar doesn't update anymore and Olive refuses to play the sequence.
6. Create another sequence in the project and open it.
7. Olive freezes, press Ctrl+C on the terminal to halt Olive's execution. Obtain backtrace.

<details>
<summary><b>Backtrace</b></summary>
<pre><code>
Thread 1 "olive-editor" received signal SIGINT, Interrupt.
0x00007ffff4e4e6a2 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
(gdb) bt
#0  0x00007ffff4e4e6a2 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#1  0x00007ffff3ac2e84 in QWaitCondition::wait(QMutex*, QDeadlineTimer) () at /usr/lib/libQt5Core.so.5
#2  0x00005555557ad910 in olive::RenderTicket::WaitForFinished() (this=0x555558e9cf50)
    at /usr/include/qt/QtCore/qdeadlinetimer.h:68
#3  0x00005555557a42ca in olive::RenderBackend::SetViewerNode(olive::ViewerOutput*)
    (this=0x5555587c1200, viewer_node=0x555558f59160)
    at /home/zumid/desktop/Apps/Olive Git/app/render/backend/renderbackend.cpp:83
#4  0x0000555555816b30 in olive::TimeBasedWidget::ConnectViewerNode(olive::ViewerOutput*)
    (this=0x555558942030, node=0x555558f59160) at /home/zumid/desktop/Apps/Olive Git/app/common/rational.h:36
#5  0x0000555555787cca in olive::TimeBasedPanel::ConnectViewerNode(olive::ViewerOutput*)
    (this=0x5555587c5d10, node=0x555558f59160) at /home/zumid/desktop/Apps/Olive Git/app/panel/timebased/timebased.cpp:136
#6  0x000055555585ba95 in olive::MainWindow::TimelineFocused(olive::ViewerOutput*) (this=0x555557d0c060, viewer=0x555558f59160)
    at /home/zumid/desktop/Apps/Olive Git/app/window/mainwindow/mainwindow.cpp:547
#7  0x00007ffff3cd8a06 in  () at /usr/lib/libQt5Core.so.5
#8  0x00005555556c9f0f in olive::PanelManager::FocusedPanelChanged(olive::PanelWidget*)
    (this=this@entry=0x555557d0a730, _t1=<optimized out>)
    at /home/zumid/desktop/Apps/Olive Git/build/app/olive-editor_autogen/2M4IF6KQHC/moc_panelmanager.cpp:175
#9  0x000055555578a623 in olive::PanelManager::FocusChanged(QWidget*, QWidget*)
    (this=0x555557d0a730, old=<optimized out>, now=<optimized out>)
    at /home/zumid/desktop/Apps/Olive Git/app/panel/panelmanager.cpp:134
#10 0x00007ffff3cd8a06 in  () at /usr/lib/libQt5Core.so.5
#11 0x00007ffff476a12c in QApplication::focusChanged(QWidget*, QWidget*) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff47a6b2f in QWidget::setFocus(Qt::FocusReason) () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff4770597 in QApplication::setActiveWindow(QWidget*) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff477060c in QApplicationPrivate::notifyActiveWindowChange(QWindow*) () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff407783d in QGuiApplicationPrivate::processActivatedEvent(QWindowSystemInterfacePrivate::ActivatedWindowEvent*)
    () at /usr/lib/libQt5Gui.so.5
#16 0x00007ffff4050b4c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Gui.so.5
#17 0x00007fffec650c8c in  () at /usr/lib/libQt5XcbQpa.so.5
#18 0x00007fffef13543c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#19 0x00007fffef1831d9 in  () at /usr/lib/libglib-2.0.so.0
#20 0x00007fffef134221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff3cfa311 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#22 0x00007ffff3ca011c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#23 0x00007ffff3ca85a4 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#24 0x00005555556c05d0 in main(int, char**) (argc=<optimized out>, argv=0x7fffffffe1a8)
    at /home/zumid/desktop/Apps/Olive Git/app/main.cpp:161

</code></pre>
</details>

**Additional Information / Output**

I am using the following library versions to compile my copy of Olive 0.2:
  * openimageio 2.1.18.1-2
  * opencolorio 1.1.1-4
  * openexr 2.5.3-1
  * qt5-base 5.15.0-5
  * ffmpeg-git 4.4.r99100.g6d71a25cc4-1

When this problem happens, `[WARNING] Playback queue failed to keep up ((null):0)` will be spammed in the terminal window.

The circumstances that trigger this bug vary, but it seems more likely to happen when the clip speed is changed while playing the sequence.

I believe this is related to #1192.

**Comment by ThomasWilshaw** [comment]
I can recreate this (Windows 7,  dbd54d0 , Debug). If I play around with the speed slider enough whilst playing back a clip the cache does eventually break (stops caching and the line goes red) and the viewer window goes black. The Footage Viewer will play back clips fine but will not cache them. Olive doesn't actually crash unless I then proceed to step 6 (although I don't have ot even open the sequence, just creating causes a hang).

I think the crash is possibly a separate issue, @ZoomTen, can you reproduce the crash if you only create a new sequence (step 6)? I've noticed that switching back and forth a lot between two separate sequences seems to break the cache as well. If you cache a sequence, switch to a new sequence then switch back the cache line will have turned red and never goes green again, even if it appears to play back as if it is cached.

**Comment by ZoomTen** [comment]
@ThomasWilshaw You're right - I just checked with two new sequences, switching the sequence while the other one is caching seems to trip Olive, producing a similar backtrace on interrupt
