### ISSUE TITLE
[EDIT] What does "green" and "red"  color on Timeline mean?

### ISSUE THREAD

**Issue by alex2345** [olive-editor/olive#1208]
**Olive 0.2**
**Win10**
**What does "green" and "red"  color on Timeline mean?**

**Additional Information / Output**
After I drag a video clip onto the Timeline, 
some part of the color on the Timeline ruler changed from "red" to "green",
but some part of them remains "red".

Please tell me what does it mean, Thank you very much!
![image](https://user-images.githubusercontent.com/5210872/93726968-70686e80-fbeb-11ea-978c-2ab2c547928d.png)

**Comment by itsmattkc** [comment]
Green is cached so playback and seeking will be immediate. Red is uncached so don't expect it to return frames immediately (Olive caches based on the playhead position).

It would be preferable for you to ask questions on the Discord and leave posting issues for reporting bugs or crashes.
