### ISSUE TITLE
Mask effect

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#121]

**Comment by itsmattkc** [comment]
This isn't hard in theory, but editing a mask without #119 would be a pain so that should probably come first.

**Comment by Symbian9** [comment]
> This isn't hard in theory, but editing a mask without #119 would be a pain

#119 already fixed.

FTR, what about set mask using grayscale picture placed between video clips?

**Comment by Symbian9** [comment]
Any news on "Mask" effect implementing?

**Comment by oc1024** [comment]
I currently implemented them as set of blending effects on my fork of Olive.

Though I'd like to hear about this before making a pull request.

**Comment by itsmattkc** [comment]
I do have a plan for this and it should be coming soon, it's just a matter of having time to write the infrastructure for it.

**Comment by metadr0n13** [comment]
Hi i was wondering if the masking request is still being worked on? Maybe an alpha version to implement for testing

**Comment by Simran-B** [comment]
It is rather not being worked on _yet_.

**Comment by metadr0n13** [comment]
What does that mean, sorry maybe im misunderstanding

**Comment by Simran-B** [comment]
Olive is undergoing a core rewrite, making it a node-based editor. The focus is on making it work again at all at the moment, not features like masking.

**Comment by metadr0n13** [comment]
Awesome thanks for the reply looking forward to the changes

**Comment by CodigoCristo** [comment]
Similar to cropping option
![image](https://user-images.githubusercontent.com/34531165/65833744-16afbb80-e299-11e9-8f6b-0cc2beb582f8.png)
