### ISSUE TITLE
[EDIT] Audio unintuitively uses last volume after deleting keyframes.

### ISSUE THREAD

**Issue by jarro2783** [olive-editor/olive#1210]
**Commit Hash (8 character string of letters/numbers in title bar)**

90f28b68

**Platform**

Linux

**Summary**

Editing a clip's volumes with keyframes and then deleting keyframes removes the audio completely. If you do a fade-in by setting a keyframe with volume -200db, then another one later at 0db, then delete all keyframes with the marker at the -200db frame, the audio of the track is left at -200. This seems unintuitive to me, and I thought the audio was gone, as I expect deleting keyframes to reset things back to the initial state.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
This is intentional behavior. It's assumed that even if the user disables keyframes, the values they set while keyframing are probably closer to what they want than the defaults. Your case was just particularly confusing since the value you removed them on happened to be essentially muted.

**Comment by jarro2783** [comment]
Fair enough, thanks.
