### ISSUE TITLE
[EDIT] keyframes are offset by video start position

### ISSUE THREAD

**Issue by jarro2783** [olive-editor/olive#1213]
**Commit Hash** 

90f28b68

**Platform**

Linux

**Summary**

Keyframes on videos that do not start at frame zero are offset by the same amount as the frame that the video starts at. To reproduce:
1. Insert a video starting at 2s.
2. Move the playhead to 2s.
3. Insert a keyframe on the volume of the audio.

At this point the keyframe will be at 4 seconds.

**Additional Information / Output**

![Screenshot from 2020-09-22 19-39-34](https://user-images.githubusercontent.com/1456242/93867177-04315c00-fd0c-11ea-9f43-111127695bcf.png)

Note that the editor thinks it is on the keyframe I added, but the box shows the keyframe further along.

**Comment by ThomasWilshaw** [comment]
I can confirm this, it does seem to be only the audio volume key frame that is doing this (although I've not exhaustively tested all keyframable options).

**Comment by ThomasWilshaw** [comment]
Also only seems to happen when the volume node is connected to an offset video (whether offset with blank space or another clip). A unconnected volume node keyframes fine.

**Comment by ZoomTen** [comment]
Confirmed with trying to keyframe an Ortographic Matrix node on a Title clip, around 3 seconds into the sequence:
![nokey webm](https://user-images.githubusercontent.com/13794376/93880763-2de88400-fd08-11ea-899d-e2b16e1afc24.gif)

**Comment by ThomasWilshaw** [comment]
Do the keyframes show up correctly if the title clip is at the start of the timeline?

**Comment by ZoomTen** [comment]
Yes, that appears to be the case

**Comment by ThomasWilshaw** [comment]
Can confirm this appears to have fixed it for me.
