### ISSUE TITLE
[CRASH] Opening multiple projects messes up and crashes

### ISSUE THREAD

**Issue by jarro2783** [olive-editor/olive#1216]
**Commit Hash** 

d196689c2d42882a4

**Platform**

Linux

**Summary**

Opening two projects messes up the UI, and interacting with one of the timelines crashes Olive.

**Steps to Reproduce**

1. Open a saved project.
2. Open another saved project.
3. Click in the timeline on the right-hand side of the screen (see screenshot below).

<details><summary><strong>Backtrace</strong></summary><pre><code>

olive::NodeViewItem::SetNodePosition (this=0x0, pos=...) at ../app/widget/nodeview/nodeviewitem.cpp:104
104	  switch (flow_dir_) {
(gdb) bt
#0  olive::NodeViewItem::SetNodePosition(QPointF const&) (this=0x0, pos=...) at ../app/widget/nodeview/nodeviewitem.cpp:104
#1  0x000055555582adf3 in olive::NodeViewScene::NodePositionChanged(QPointF const&) (this=0x555558144e18, pos=...) at /usr/include/qt5/QtCore/qhash.h:637
#2  0x00007ffff3f2a082 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#3  0x00005555556ca8f5 in olive::Node::PositionChanged(QPointF const&) (this=this@entry=0x7fffcc2ba1b0, _t1=...) at app/olive-editor_autogen/MFLS3X56JO/moc_node.cpp:210
#4  0x00005555557976e1 in olive::Node::SetPosition(QPointF const&) (this=this@entry=0x7fffcc2ba1b0, pos=...) at ../app/node/node.cpp:793
#5  0x000055555582c10e in olive::NodeViewScene::ReorganizeFrom(olive::Node*) (this=this@entry=0x555558144e18, n=0x7fffcc037ea0) at /usr/include/qt5/QtCore/qpoint.h:291
#6  0x0000555555822a7a in olive::NodeView::UpdateBlockFilter() (this=0x555558144db0) at ../app/widget/nodeview/nodeview.cpp:860
#7  0x0000555555823d3b in olive::NodeView::SetGraph(olive::NodeGraph*) (this=0x555558144db0, graph=<optimized out>) at ../app/widget/nodeview/nodeview.cpp:101
#8  0x00007ffff3f2a082 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#9  0x00005555556cb21f in olive::PanelManager::FocusedPanelChanged(olive::PanelWidget*) (this=this@entry=0x55555741a8e0, _t1=<optimized out>)
    at app/olive-editor_autogen/2M4IF6KQHC/moc_panelmanager.cpp:175
#10 0x00005555557ad98d in olive::PanelManager::FocusChanged(QWidget*, QWidget*) (this=0x55555741a8e0, old=<optimized out>, now=<optimized out>) at ../app/panel/panelmanager.cpp:134
#11 0x00007ffff3f2a082 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#12 0x00007ffff48de4fb in QApplication::focusChanged(QWidget*, QWidget*) () at /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff48e66c0 in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () at /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff491ca9f in QWidget::setFocus(Qt::FocusReason) () at /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff48e029d in QApplicationPrivate::giveFocusAccordingToFocusPolicy(QWidget*, QEvent*, QPoint) () at /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff48ead00 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff3ef744f in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#18 0x00007ffff48e81bc in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff493d4cb in QWidgetWindow::handleMouseEvent(QMouseEvent*) () at /usr/lib64/libQt5Widgets.so.5
#20 0x00007ffff49403f4 in QWidgetWindow::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#21 0x00007ffff48dfd0f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#22 0x00007ffff48e8ed0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#23 0x00007ffff3ef744f in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#24 0x00007ffff42ee41b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib64/libQt5Gui.so.5
#25 0x00007ffff42efc05 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib64/libQt5Gui.so.5
#26 0x00007ffff42ca93b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Gui.so.5
#27 0x00007fffeb16b5da in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () at /usr/lib64/libQt5XcbQpa.so.5
#28 0x00007fffefa601dd in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#29 0x00007fffefa60458 in g_main_context_iterate.isra () at /usr/lib64/libglib-2.0.so.0
#30 0x00007fffefa604ef in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#31 0x00007ffff3f4b730 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#32 0x00007ffff3ef630b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#33 0x00007ffff3efe0e2 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#34 0x00005555556c1a99 in main(int, char**) (argc=<optimized out>, argv=0x7fffffffd898) at ../app/main.cpp:161
olive::NodeViewItem::SetNodePosition (this=0x0, pos=...) at ../app/widget/nodeview/nodeviewitem.cpp:104
104	  switch (flow_dir_) {
(gdb) bt
#0  olive::NodeViewItem::SetNodePosition(QPointF const&) (this=0x0, pos=...) at ../app/widget/nodeview/nodeviewitem.cpp:104
#1  0x000055555582adf3 in olive::NodeViewScene::NodePositionChanged(QPointF const&) (this=0x555558144e18, pos=...) at /usr/include/qt5/QtCore/qhash.h:637
#2  0x00007ffff3f2a082 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#3  0x00005555556ca8f5 in olive::Node::PositionChanged(QPointF const&) (this=this@entry=0x7fffcc2ba1b0, _t1=...) at app/olive-editor_autogen/MFLS3X56JO/moc_node.cpp:210
#4  0x00005555557976e1 in olive::Node::SetPosition(QPointF const&) (this=this@entry=0x7fffcc2ba1b0, pos=...) at ../app/node/node.cpp:793
#5  0x000055555582c10e in olive::NodeViewScene::ReorganizeFrom(olive::Node*) (this=this@entry=0x555558144e18, n=0x7fffcc037ea0) at /usr/include/qt5/QtCore/qpoint.h:291
#6  0x0000555555822a7a in olive::NodeView::UpdateBlockFilter() (this=0x555558144db0) at ../app/widget/nodeview/nodeview.cpp:860
#7  0x0000555555823d3b in olive::NodeView::SetGraph(olive::NodeGraph*) (this=0x555558144db0, graph=<optimized out>) at ../app/widget/nodeview/nodeview.cpp:101
#8  0x00007ffff3f2a082 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#9  0x00005555556cb21f in olive::PanelManager::FocusedPanelChanged(olive::PanelWidget*) (this=this@entry=0x55555741a8e0, _t1=<optimized out>)
    at app/olive-editor_autogen/2M4IF6KQHC/moc_panelmanager.cpp:175
#10 0x00005555557ad98d in olive::PanelManager::FocusChanged(QWidget*, QWidget*) (this=0x55555741a8e0, old=<optimized out>, now=<optimized out>) at ../app/panel/panelmanager.cpp:134
#11 0x00007ffff3f2a082 in void doActivate<false>(QObject*, int, void**) () at /usr/lib64/libQt5Core.so.5
#12 0x00007ffff48de4fb in QApplication::focusChanged(QWidget*, QWidget*) () at /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff48e66c0 in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () at /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff491ca9f in QWidget::setFocus(Qt::FocusReason) () at /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff48e029d in QApplicationPrivate::giveFocusAccordingToFocusPolicy(QWidget*, QEvent*, QPoint) () at /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff48ead00 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff3ef744f in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#18 0x00007ffff48e81bc in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff493d4cb in QWidgetWindow::handleMouseEvent(QMouseEvent*) () at /usr/lib64/libQt5Widgets.so.5
#20 0x00007ffff49403f4 in QWidgetWindow::event(QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#21 0x00007ffff48dfd0f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#22 0x00007ffff48e8ed0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQt5Widgets.so.5
#23 0x00007ffff3ef744f in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt5Core.so.5
#24 0x00007ffff42ee41b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib64/libQt5Gui.so.5
#25 0x00007ffff42efc05 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib64/libQt5Gui.so.5
#26 0x00007ffff42ca93b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Gui.so.5
#27 0x00007fffeb16b5da in xcbSourceDispatch(_GSource*, int (*)(void*), void*) () at /usr/lib64/libQt5XcbQpa.so.5
#28 0x00007fffefa601dd in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#29 0x00007fffefa60458 in g_main_context_iterate.isra () at /usr/lib64/libglib-2.0.so.0
#30 0x00007fffefa604ef in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#31 0x00007ffff3f4b730 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#32 0x00007ffff3ef630b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5
#33 0x00007ffff3efe0e2 in QCoreApplication::exec() () at /usr/lib64/libQt5Core.so.5
#34 0x00005555556c1a99 in main(int, char**) (argc=<optimized out>, argv=0x7fffffffd898) at ../app/main.cpp:161

</code></pre></details>

**Additional Information**

The bottom panel looks like this after opening the second project.
![image](https://user-images.githubusercontent.com/1456242/93965705-2677b800-fda6-11ea-9678-3921f3c013eb.png)

**Comment by Simran-B** [comment]
_Cross-post from internal ticket:_

It's currently possible to open multiple projects at one time in Olive, however there's no functionality for sharing anything between the projects (in fact it often crashes if you try - so this is a known issue).

Low priority feature, but would be good to implement eventually.

**Comment by jarro2783** [comment]
Is the UI mess up a separate issue though? I notice if I do "New Project" twice I get two tabs on the left instead of this corrupted looking attempt at two projects at the same time.

**Comment by itsmattkc** [comment]
Merging into #1351 and #1390
