### ISSUE TITLE
[UI] Greyed out menu items looks "off" in dark theme

### ISSUE THREAD

**Issue by irafaz** [olive-editor/olive#1217]
**Commit Hash** 
871bc08

**Platform**
Windows 10

**Summary**
Greyed out menu items looks wierd with some sort of "displaced shadow effect".

In a new install, new unsaved project without any sequence - greyed out options for `Sequence` -> `Cache Entire Sequence` and `Cache Sequence In/Out` looks a bit wierd.

I'm using the dark theme for Olive. In the light theme, I think it looks as it's supposed to do.

Dark theme:
![image](https://user-images.githubusercontent.com/7046942/93975652-0cbf7c00-fd78-11ea-808e-f6d553f5588c.png)

Light theme:
![image](https://user-images.githubusercontent.com/7046942/93975999-996a3a00-fd78-11ea-9594-43d335579f87.png)

**Additional Information / Output**

**Comment by Simran-B** [comment]
Confirmed. Not sure if this is Windows' native rendering or if it can be changed on Qt side.

**Comment by itsmattkc** [comment]
Historically we actually used Windows' own menu styling for the menus, but Qt broke that in 5.15 (see #1189 and [the Qt bug report I filed](https://bugreports.qt.io/browse/QTBUG-85226)). Since they've confirmed it, I'm hoping they fix it soon so we can restore the native styling which will fix this issue.

**Comment by Simran-B** [comment]
Native probably means bright even if the rest of the UI is in dark mode? I'm in favor of Qt styling because of that.

**Comment by itsmattkc** [comment]
Personal preference I'm sure, but IMO it looks a little more polished with the native menus (Qt 5.14.2):
![image](https://user-images.githubusercontent.com/34096995/94220597-a6c82580-ff2c-11ea-8137-1e0ad4c939df.png)
