### ISSUE TITLE
[EXPORT] export dialogue doesn't always show up

### ISSUE THREAD

**Issue by jarro2783** [olive-editor/olive#1218]
**Commit Hash** 

d196689c2d4288

**Platform**

Linux

**Summary**

The export dialogue doesn't show up under some circumstances when I expect it to.

1. Open a project.
2. Export without clicking anything else in the UI.

The dialogue will not show up here, and no message is shown.

If you press play in the viewer, then subsequent export works.

**Additional Information / Output**

**Comment by Simran-B** [comment]
Confirmed on Windows 10 d5595ccd

If you start Olive and immediately click _File > Export_, then nothing happens. Same if you open a project file and try to export. If you focus the timeline panel or click on a clip, then the export dialog shows up as expected.

**Comment by ThomasWilshaw** [comment]
I think we just need a bit more logic and a error dialog in `Core::DialogExportShow()`. It currently just returns if there is no recently used `TimeBasesPanel`.

**Comment by Simran-B** [comment]
While it's an improvement to show an error instead of silently failing, it does not seem right to me that there is no recently used time based panel / active sequence in the project load case. Can't this be set on load?

**Comment by ThomasWilshaw** [comment]
What would you do in the case of loading a project with multiple sequences?

**Comment by jarro2783** [comment]
Currently when I open a project, it already shows the first frame of the video in the preview window. So it seems reasonable for that video to be "selected", and be the one exported.

For multiple sequences it's probably reasonable enough to pick the one that appears first in the list. As long as what you see in the preview is the one exported, that seems intuitive enough to me.

**Comment by ThomasWilshaw** [comment]
I've updated this so it falls back to the timeline if there is no recently selected time based panel.

**Comment by itsmattkc** [comment]
Should be fixed in fd143f1d519cf41f7770d0d3849e0daaadc5bc91
