### ISSUE TITLE
[UI] Window title and About dialog actually shows 7 char hash

### ISSUE THREAD

**Issue by Simran-B** [olive-editor/olive#1219]
**Commit Hash** 
d5595ccd

**Platform**
Windows 10

**Summary**
Our issue template says

    **Commit Hash** 

but Olive actually reports 7 characters only.

**Additional Information / Output**

Screenshot:

![image](https://user-images.githubusercontent.com/7819991/93998129-70f03900-fd94-11ea-9b40-553d3070f27f.png)

GitHub truncates commit hashes to 7 characters as well (as can be see above). Should we go for 7 instead? I read that huge projects like the Linux kernel require 12 characters to avoid collisions, so 8 seems safer than 7, but dunno.

**Comment by itsmattkc** [comment]
Thanks for pointing this out, yeah I'd rather err on the side of caution. I wonder if there's a way to increase the short hash length on GitHub?

**Comment by Simran-B** [comment]
Don't think so... The Linux kernel repo on GitHub has almost a million commits but they still only show 7 chars. On the other hand, 6 chars seem to be enough to view a commit? (In case of collisions they might just go with the most recent one perhaps).
