### ISSUE TITLE
[BUILD] faf3670 doesn't install the executable bin/olive-editor

### ISSUE THREAD

**Issue by yurivict** [olive-editor/olive#1223]
0.1.2 built with qmake installed it, but faf3670 built with cmake doesn't.
The ```effects/``` directory is also gone, not sure if that is intended.

**Comment by sobotka** [comment]
It doesn’t need installing.

**Comment by yurivict** [comment]
How can it be used if it isn't installed?

**Comment by ZoomTen** [comment]
You can simply run it from the terminal through e.g. `app/olive-editor` or `build/app/olive-editor`

**Comment by yurivict** [comment]
I need to build a package so that users who don't how to build anything can also run it.

**Comment by ZoomTen** [comment]
The nightly AppImage builds has recently been made available again on the Olive website
It only requires a `chmod +x` and then it should be runnable

**Comment by yurivict** [comment]
The AppImage only works on Linux, and I need to update the FreeBSD port.

**Comment by ZoomTen** [comment]
Ahh, okay. (You haven't specified earlier, so that's why I assumed)
Is the port marked as "unstable" or "bleeding-edge"? I think that because Olive 0.2 isn't quite ready for an "official" release, the install targets might have not been created yet.

**Comment by yurivict** [comment]
We don't have such an official label as "unstable", Usually if the version is <1.0.0 people assume it's not there yet.

**Comment by Simran-B** [comment]
Some relevant information:
- Compile instructions: https://olivevideoeditor.org/compile.php
- CI workflow: https://github.com/olive-editor/olive/blob/master/.github/workflows/ci.yml

Note that the project is mainly funded through ads on the official website currently. If you upload builds to software repositories etc., less users will go to the website and the project is harmed financially. If a random, very unstable build is published, it may also harm the reputation. Please take that into consideration before you distribute custom builds and perhaps encourage people to support the project in other ways. Thanks

**Comment by yurivict** [comment]
Ok, I will add a note asking users to support your project, and will make sure that it works.
