### ISSUE TITLE
[UI] Cross dissolve transitions are not deleted after removing video the dissolve is associated with

### ISSUE THREAD

**Issue by rpatros1979** [olive-editor/olive#1224]
**Commit Hash** 
commit faf36708508dc40ef689ef99588e7e747f04aa23

**Platform**
------------------------------------ 

> OS: Arch Linux x86_64 
> Host: Latitude E6430 01 
> Kernel: 5.4.66-1-lts 
> Uptime: 1 day, 6 hours, 25 mins 
> Packages: 1123 (pacman) 
> Shell: bash 5.0.18 
> Resolution: 1680x1050, 1920x1080 
> DE: Xfce 4.14 
> CPU: Intel i7-3520M (4) @ 3.600GHz 
> GPU: Intel 3rd Gen Core processor Graphics Controller 
> Memory: 2817MiB / 7846MiB 

**Summary**
Cross dissolve transitions added to a title strip are not deleted.

1. Create a sequence
2. Click on the "+" icon in Tools and add "Title"
3. Add "Cross Dissolve" transition at both the beginning and the end of the title
4. Delete the "Title" strip

It seems that the transitions are not deleted once the video (in this case the Title) strip is deleted
[olive2_bug_cross-dissolve-2020-09-23_19.52.59.mp4.zip](https://github.com/olive-editor/olive/files/5273189/olive2_bug_cross-dissolve-2020-09-23_19.52.59.mp4.zip)

 

**Additional Information / Output**
I have attached a brief video displaying the behavior

**Comment by ThomasWilshaw** [comment]
I can confirm that this happens but I'm not sure if it is unexpected behavior or not.

**Comment by itsmattkc** [comment]
Transition logic in the timeline definitely needs some work.

**Comment by rpatros1979** [comment]
Thank you @itsmattkc  and @ThomasWilshaw
