### ISSUE TITLE
New Window Opens

### ISSUE THREAD

**Issue by Suganth526** [olive-editor/olive#1225]
**New Window Opening** 

**Platform**
I have just downloaded my olive 0.2,when i opens olive, it also opens any debug like this:
[DEBUG] Extracting default OCIO config to "C:/Users/HP/AppData/Local/Temp/olivevideoeditor.org/Olive/ocioconf" ((null):0)

![Screenshot (172)](https://user-images.githubusercontent.com/69079041/94130897-e2a2b280-fe7a-11ea-9b02-9fac9aa2f5ea.png)

**Summary**
So how could i close that, even i close that the software closes

**Additional Information / Output**
When i Do any edit in the olive editor, it is counting the process and showing in the other window

**Comment by ThomasWilshaw** [comment]
That console window is supposed to open. This is not a bug

**Comment by itsmattkc** [comment]
Not a bug, it outputs potentially useful information for how the software is running. While we may add an option to toggle it in the future, you'll just have to minimize it for now.
