### ISSUE TITLE
[UI] Menus are not opening in the full-screen

### ISSUE THREAD

**Issue by YashPatel000** [olive-editor/olive#1226]
**Commit Hash** 

**Platform**
windows 10

**Summary**
After doing full screen from view-> full screen, Menus are not opening.

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
I can confirm this on Windows and it looks like it may be a known issue:

https://bugreports.qt.io/browse/QTBUG-47156
https://bugreports.qt.io/browse/QTBUG-41309
https://doc.qt.io/qt-5/windows-issues.html#fullscreen-opengl-based-windows
https://doc.qt.io/qt-5/qwindowswindowfunctions.html
