### ISSUE TITLE
[BUILD] Compile instructions prerequisite wrong (Qt 5.9+ is required)

### ISSUE THREAD

**Issue by gerrycocco** [olive-editor/olive#1227]
**Commit Hash** 
76d73b17

**Platform**
Linux sake 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

**Summary**
The "Compiling Olive 2.0" webpage (https://www.olivevideoeditor.org/compile.php) says that Qt version 5.6+ is required.  Actually 5.9+ is required due to the QFloat16 types that are now being used by Olive.

**Additional Information / Output**
Note that Debian stretch (v9) repos include Qt at 5.7 and you must install Qt manually to upgrade to Qt at a later level.  This will most likely affect new users attempting to install and test Olive.

### cmake issue
```   
cmake --build .
   ISSUE: ~/work/olive/app/audio/audiovisualwaveform.h:24:20: fatal error: QFloat16: No such file or directory
```

### Minor build issue
I downloaded and ran the Qt installer (./qt-unified-linux-x64-3.2.3-online.run) and installed Qt at version 5.15.1.   The cmake had one additional error:
```
/home/gcocco/work/olive/app/render/color.cpp:30:57: error: call of overloaded ‘abs(double)’ is ambiguous
   float X = C * (1.0f - abs(fmod(h / 60.0f, 2.0f) - 1.0f));
```
I assume this is a transient build issue.  I got around it by changing `abs` to `fabs`.   Then the cmake completed normally and I was able to launch and test Olive.

### Olive web page - change 5.6+ to 5.9+
![image](https://user-images.githubusercontent.com/4722852/94168806-a3ad3680-fe53-11ea-8ba1-fda774955f3d.png)

### Qt doc on qfloat
![image](https://user-images.githubusercontent.com/4722852/94168837-aad44480-fe53-11ea-8959-78177060f3d4.png)

**Comment by itsmattkc** [comment]
Updated now
