### ISSUE TITLE
[CACHE] Cache does not get invalidated when moving sequences

### ISSUE THREAD

**Issue by ngreve** [olive-editor/olive#1228]
**Commit Hash** 

Tested with:
- a9935a6b (newest tested)
- 4082f6d9
- faf36708

**Platform**
Linux

**Summary**
Cache does not get invalidated when moving sequences (only tested with text).
I move the text around and the preview still shows it, although it is no longer in that place.

**Additional Information / Output**
Video:
[olive_cache_problem.zip](https://github.com/olive-editor/olive/files/5278326/olive_cache_problem.zip)

**Comment by itsmattkc** [comment]
Does the latest commit fix this?

**Comment by ngreve** [comment]
**Disclaimer:** Unfortunately you are using OpenColorIO 2.0 which does not have an official release yet. So I compiled it from scratch and modified Olive's cmake file to find the library in the temporary build directory. What I want to say is, that there is the slight chance that I compiled olive in the wrong way, even though there were no errors while compiling or running olive.

Long story short: The bug is still there.

**Comment by Simran-B** [comment]
Note that the latest AppImage [nightly builds](https://olivevideoeditor.org/nightly.php) are compiled with OCIO 2.0. To point CMake to a different OCIO package when compiling locally, it should be sufficient to supply `-DOCIO_LOCATION=/path/to/ocio2` when configuring cmake.

**Comment by ngreve** [comment]
Tested it with the latest AppImage and unfortunately the issue can be found there, too

**Comment by ngreve** [comment]
Bug is still there, but when resizing sequences (tested with nightly AppImage):
![olive-cache-bug](https://user-images.githubusercontent.com/18660100/99504941-7fb43000-2980-11eb-8443-60b1e1fe526e.gif)

Better quality mp4 video: 
[olive-cache-bug.zip](https://github.com/olive-editor/olive/files/5558740/olive-cache-bug.zip)

**Comment by itsmattkc** [comment]
Try afbd3ada

**Comment by ngreve** [comment]
Yep seems to be fixed now, thanks!
