### ISSUE TITLE
[CRASH] double_fork_and_exec.cc crashing because it cannot find the crashpad handler

### ISSUE THREAD

**Issue by ilar** [olive-editor/olive#1230]
**Commit Hash** 
fd143f1d

**Platform**
Linux ######## 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Summary**
On starting the program, it waits a second, and then displays the error message 
[175178:175178:20200925,043329.248933:FATAL double_fork_and_exec.cc:131] execv crashpad_handler: No such file or directory (2)

It then just hangs there, with nothing appearing/no interactivity. I'm considering this a 'crash' but if it's not I can change the issue template. Bit of an ironic crash, really considering it appears to be crashing specifically because it cannot find the crash handler!

I can only assume something went wrong in commit 65437042.

**Steps to Reproduce**

1. Run the AppImage from terminal.
2. Error occurs.

<details><summary><strong>Backtrace</strong></summary><pre><code>

(gdb) exec-file Olive-fd143f1d-Linux-x86_64.AppImage 
(gdb) run
Starting program: /home/#######/Downloads/Olive-fd143f1d-Linux-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 175169]
process 175165 is executing new program: /tmp/.mount_Olive-eEMCsn/usr/bin/olive-editor
warning: Loadable section ".dynstr" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9914700 (LWP 175174)]
[New Thread 0x7fffe9113700 (LWP 175175)]
[Detaching after fork from child process 175177]
[175178:175178:20200925,043329.248933:FATAL double_fork_and_exec.cc:131] execv crashpad_handler: No such file or directory (2)

^C
Thread 1 "AppRun" received signal SIGINT, Interrupt.
__libc_recvmsg (flags=0, msg=0x7fffffffd290, fd=11) at ../sysdeps/unix/sysv/linux/recvmsg.c:28
28	../sysdeps/unix/sysv/linux/recvmsg.c: No such file or directory.
(gdb) bt
#0  __libc_recvmsg (flags=0, msg=0x7fffffffd290, fd=11) at ../sysdeps/unix/sysv/linux/recvmsg.c:28
#1  __libc_recvmsg (fd=11, msg=0x7fffffffd290, flags=0) at ../sysdeps/unix/sysv/linux/recvmsg.c:25
#2  0x0000000000728aac in crashpad::UnixCredentialSocket::RecvMsg(int, void*, unsigned long, ucred*, std::vector<base::ScopedGeneric<int, base::internal::ScopedFDCloseTraits>, std::allocator<base::ScopedGeneric<int, base::internal::ScopedFDCloseTraits> > >*) ()
#3  0x0000000000725de5 in crashpad::ExceptionHandlerClient::GetHandlerCredentials(ucred*) ()
#4  0x000000000071897d in crashpad::(anonymous namespace)::RequestCrashDumpHandler::Initialize(base::ScopedGeneric<int, base::internal::ScopedFDCloseTraits>, int, std::set<int, std::less<int>, std::allocator<int> > const*) ()
#5  0x00000000007185cc in crashpad::CrashpadClient::StartHandler(base::FilePath const&, base::FilePath const&, base::FilePath const&, std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::string, std::allocator<std::string> > const&, bool, bool, std::vector<base::FilePath, std::allocator<base::FilePath> > const&) ()
#6  0x00000000005a9885 in InitializeCrashpad () at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/new_allocator.h:80
#7  0x000000000054d4dc in main (argc=<optimized out>, argv=0x7fffffffdb48) at ../app/main.cpp:152

</code></pre></details>

**Additional Information**

**Comment by okhostok** [comment]
I also confirm that this behavior happens when starting olive, however it did not happen 2 commits before: faf3670.
