### ISSUE TITLE
[NODES] Nodes clips are reset to center view when connecting to other node properties

### ISSUE THREAD

**Issue by rpatros1979** [olive-editor/olive#1234]
**Commit Hash** 
faf36708

**Platform**
OS: Arch Linux x86_64
Host: Latitude E6430 01
Kernel: 5.4.66-1-lts
Resolution: 1680x1050, 1920x1080
DE: Xfce 4.14
CPU: Intel i7-3520M (4) @ 3.600GHz
GPU: Intel 3rd Gen Core processor Graphics Controller
Memory: 2817MiB / 7846MiB

**Summary**
In the nodes windows after adding a clip to the timeline, you adjust the positions of the nodes in the node editor and when you try to add orthographic generator between the clip and the viewer and once you try to link another section to any other points, the boxes all reset to the center page and does not keep it's original position. The below video shows it clearly

[olive2_bug_node_reset-2020-09-25_11.25.27.mkv.zip](https://github.com/olive-editor/olive/files/5284662/olive2_bug_node_reset-2020-09-25_11.25.27.mkv.zip)

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Addressed as of merge of `nodearchchanges`
