### ISSUE TITLE
[CODEC] Using some footage results in stuck import dialog

### ISSUE THREAD

**Issue by okhostok** [olive-editor/olive#1235]
**Commit Hash** faf3670

**Platform** Ubuntu 20.04.1

**Summary** While importing files with certain codecs, olive results in stuck import dialog.
I will post codecs there using `ffprobe`:

1. Video: h264 (High 10), yuv420p10le(progressive), 1920x1080, SAR 1:1 DAR 16:9, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default) (length: 23 minutes)
2. Video: hevc (Main 10), yuv420p10le(tv), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default) (length: 23 minutes)
3. Video: hevc (Main 10), yuv420p10le(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default) (length: 117 minutes)

However, these did not get stuck:
1. Video: hevc (Main 10), yuv420p10le(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default) (length: 1 minute) - interestingly the length influenced importability.
2. Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 2357 kb/s, 23.98 fps, 23.98 tbr, 16k tbn, 47.95 tbc (default) (length: 23 minutes)
3. Video: h264 (High 10) (avc1 / 0x31637661), yuv420p10le, 1280x720 [SAR 1:1 DAR 16:9], 6503 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default) (length: 112 minutes)
4. Video: vp9 (Profile 0), yuv420p(tv, bt709), 3840x2160, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn, 1k tbc (default) (length: 14 seconds)
5. Video: png (png  / 0x20676E70), rgb24(pc, bt709), 1280x720 [SAR 1:1 DAR 16:9], 389082 kb/s, 30 fps, 30 tbr, 3k tbn, 3k tbc (default) (2 seconds)

**Additional Information / Output**

I will test other codecs and update this post accordingly.

**Comment by okhostok** [comment]
Tested ALEXA Mini LF ProRes sample footage (https://arriwebgate.com/directlink/b043cddb9c4658e0), no problem has occured:
Video: prores (4444) (ap4h / 0x68347061), yuv444p12le(tv, GBR, progressive), 1920x1080, SAR 1:1 DAR 16:9, 24 tbr, 24 tbn, 24 tbc (length 8:30 minutes)

**Comment by ThomasWilshaw** [comment]
Do you get any console output when the dialog gets stuck?

**Comment by okhostok** [comment]
@ThomasWilshaw, on terminal no. Used `gdb` and this is the output:
<details><summary><strong>`gdb` output</strong></summary><pre><code>(gdb) exec-file ./olive-editor
(gdb) run
Starting program: /home/hpuser/Dev/src/olive/build/app/olive-editor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdf570700 (LWP 5669)]
[New Thread 0x7fffde1b3700 (LWP 5670)]
[New Thread 0x7fffdd9b2700 (LWP 5671)]
[DEBUG] Extracting default OCIO config to "/tmp/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[New Thread 0x7fffdcbc4700 (LWP 5672)]
[New Thread 0x7fffca2ed700 (LWP 5673)]
[New Thread 0x7fffc9aec700 (LWP 5674)]
[New Thread 0x7fffc92eb700 (LWP 5675)]
[New Thread 0x7fffc8aea700 (LWP 5676)]
[INFO] Using Qt version: 5.12.8 ((null):0)
[New Thread 0x7fffb3fff700 (LWP 5677)]
[New Thread 0x7fffb37fe700 (LWP 5678)]
[New Thread 0x7fffb2ffd700 (LWP 5679)]
[New Thread 0x7fffb27fc700 (LWP 5680)]
[DEBUG] Using graphics driver: Intel ((null):0)
[New Thread 0x7fffa2fff700 (LWP 5681)]
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1f.3.analog-stereo" ((null):0)
[New Thread 0x7fffa27fe700 (LWP 5682)]
[New Thread 0x7fffa1ffd700 (LWP 5683)]
[New Thread 0x7fffa17fc700 (LWP 5684)]
[New Thread 0x7fffa0ffb700 (LWP 5685)]
[New Thread 0x7fff87fff700 (LWP 5686)]
[New Thread 0x7fff877fe700 (LWP 5687)]
[New Thread 0x7fff86ffd700 (LWP 5688)]
[New Thread 0x7fff867fc700 (LWP 5689)]
[New Thread 0x7fff85ffb700 (LWP 5690)]
[Thread 0x7fffb3fff700 (LWP 5677) exited]
--Type <RET> for more, q to quit, c to continue without paging--c
Thread 1 "olive-editor" received signal SIGTERM, Terminated.
0x00007ffff3c75aff in __GI___poll (fds=<error reading variable: Cannot access memory at address 0x7fffffffd8f8>, nfds=<error reading variable: Cannot access memory at address 0x7fffffffd900>, timeout=<error reading variable: Cannot access memory at address 0x7fffffffd90c>) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) bt
#0  0x00007ffff3c75aff in __GI___pollPython Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x7fffffffd8f8: 
</code></pre></details>

Some explanation about the output after SIGTERM:
I do not think the output after SIGTERM belongs to the current, as it is only called when I do `pkill` - process kill by name, whether olive is stuck or not.
I think, the main problem is in this line: `[Thread 0x7fffb3fff700 (LWP 5677) exited]`.

**Comment by okhostok** [comment]
**Sample**
I think it is better to include the sample video (black screen - 48 minutes, hevc):
[output.mkv.zip](https://github.com/olive-editor/olive/files/5305923/output.mkv.zip)
This video also results stuck import dialog. 
If this works for you, then the cause may be Olive's memory management for large length videos.

**Comment by ThomasWilshaw** [comment]
Thanks for that, I was able to successfully import that onto the timeline but Olive hung on the import loading dialogue for a few minutes time at 100% CPU usage. The dialogue sat at 0% and both timers sat at 0.

**Comment by okhostok** [comment]
Well, now it works (I do not know which commit did it, however). Thank you for your hardwork, Olive Team. :)
