### ISSUE TITLE
[CRASH] Removed Audio Node

### ISSUE THREAD

**Issue by MatthewRusson** [olive-editor/olive#1241]
**Commit Hash** 
610f4c54

**Platform**
Windows

**Summary**
Olive crashed when I imported a clip into a sequence, removed the audio node, and tried to move the clip.

**Steps to Reproduce**

1. Add Video with audio track to a sequence.
2. Delete the audio node from the node editor
3. Try to move the remaining video clip.

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

[crash.txt](https://github.com/olive-editor/olive/files/5293730/crash.txt)

**Additional Information**

Also, I don't think the crash reporter works. It kept saying "Failed to send error report."

**Comment by ThomasWilshaw** [comment]
I'm not able to reproduce this, can you provide an example video file? Also did you download this or build it yourself? It doesn't appear to have debug symbols loaded.

**Comment by MatthewRusson** [comment]
I downloaded the portable version from the website. (I tried a bit ago and
wasn't able to build it from the source). I tried redownloading it on a
different computer and it still crashed. I'll try to upload an example file
soon.

**Comment by MatthewRusson** [comment]
Here's a sample video I found online that crashes for me with the same steps as above.
[SampleVideo_360x240_1mb.zip](https://github.com/olive-editor/olive/files/5300101/SampleVideo_360x240_1mb.zip)

Could it be a problem with just the portable version?

**Comment by ThomasWilshaw** [comment]
Thanks for the file. I can sort of reproduce this if I delete the audio clip node, not the Audio in node (in red below), is that what you meant?

![image](https://user-images.githubusercontent.com/7781683/94586426-1dd92300-0279-11eb-9aaf-20ce5cfe2dbe.png)
