### ISSUE TITLE
[UI] Open Recent doesn't work

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1243]
**fec97749**
**macOS 10.14.6**

**Summary**
The "Open recent" menu list the last files opened but it actually doesn't open them.

**Additional Information / Output**
The full path is correct but, as said, they doesn't open the project.

Cheers

**Comment by ThomasWilshaw** [comment]
I'm not able to reproduce this, can you provide any more details? Does anything actually happen when you open a project? Do you get any useful output in the console? Worth noting that projects wont necessarily be compatible between builds atm so try creating a new project in your current build and re opening that.

**Comment by pgilfernandez** [comment]
It happens nothing when you press the recent project you want to open. If I use the open project menu it opens fine.
It is already a new project, created and saved with the same 0.2 build.

Sorry to ask: what console? how could I activate and check if there is any error?

**Comment by ThomasWilshaw** [comment]
Can you try running Olive through the terminal (https://support.apple.com/en-gb/guide/terminal/apdb66b5242-0d18-49fc-9c47-a2498b7c91d5/mac) and showing what output you get when you open a recent project.

**Comment by pgilfernandez** [comment]
Opening the app using Terminal doesn't seem do anything but just opening the app:
`open /Applications/Olive.app`
It opens correctly the app but when I perform any task it doesn't write anything into the terminal...

I guess it has to done with **gdb** as suggested [here](https://github.com/olive-editor/olive/wiki/Debugging-Olive) but the steps are not valid for macOS because when I launch:
`(gdb) exec-file /Applications/Olive.app`
it tells me that "Olive.app" is a folder not a executable which is totally true.

Any other idea?

**Comment by pgilfernandez** [comment]
I struggled making gdb usable in macOS but I think I have finally done it.
The following is the output that I got after opening Olive, trying to open a recent project (any output text), opening a project with Open, playing a sequence, stopping it:
`[DEBUG] Extracting default OCIO config to "/Users/pablo/Library/Caches/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.15.1 ((null):0)
[INFO] Setting output audio device to "Built-in Output" ((null):0)
objc[52967]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8b9c43d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x112bbcf50). One of the two will be used. Which one is undefined.
[DEBUG] Project version: "0.2.0" ((null):0)
[INFO] Setting output audio device to "Built-in Output" ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[swscaler @ 0x114fb4000] Warning: data is not aligned! This can lead to a speed loss
[WARNING] QGestureManager::deliverEvent: could not find the target for gesture ((null):0)`

Then when trying to quit Olive, it gets stuck and never quits, I have to force quit and this is the details I get:
[error.txt](https://github.com/olive-editor/olive/files/5323353/error.txt)

I hope it helps...

**Comment by pgilfernandez** [comment]
Hi,

I'm still trying to debug Olive in order to find a clue about this issue.
I tried opening Olive with the Terminal but opening like the following:

`/Applications/Olive.app/Contents/MacOS/Olive`

This way, the Terminal writes the following at startup:
`[DEBUG] Extracting default OCIO config to "/Users/pablo/Library/Caches/olivevideoeditor.org/Olive/ocioconf" ((null):0)`
`[INFO] Using Qt version: 5.15.1 ((null):0)`
`[INFO] Setting output audio device to "Built-in Output" ((null):0)`

Then I try to open a recent project from the File/Open Recent menu **nothing happens and nothing is written in the Terminal**... so, I'm still out of luck.

Any idea?

**Comment by pgilfernandez** [comment]
Hi again,

I have tried too debug with gdb as suggested in the wiki.

I think a finally got it semi-working but now the problem might be related on how Olive has been compiled because, [as suggested here](https://dev.to/jasonelwood/setup-gdb-on-macos-in-2020-489k#generate-builds), the program must be compiled with the "-ggdb" option... is it done like this? or is it supposed that I compile my own Olive with this option and then try to debug it?

I get errors saying "can´t open to read symbols: No such file or directory"

Any idea?

**Comment by itsmattkc** [comment]
Appears to be a Qt bug that occurs only on macOS and only when you call `insertAction` before a separator.
