### ISSUE TITLE
[BUILD] Windows installer launches Olive as administrator

### ISSUE THREAD

**Issue by Simran-B** [olive-editor/olive#1245]
**Commit Hash** 
b9359ce5

**Platform**
Windows 10

**Summary**
The Windows installer offers to "Run Olive" in the last step. As the installer runs with elevated privileges, it seems to start olive-editor.exe as administrator too. Aside from possible security aspects, this breaks drag'n'drop from e.g. Explorer. Windows prevents dropping things onto applications which run with elevated privileges, including from other elevated programs.

Marking as low priority, as there is a simple workaround (restart Olive as normal process).

**Additional Information / Output**
OBS had a [similar issue](https://github.com/obsproject/obs-studio/commit/078ea5222dab23084b91b8476441d37cbdc2cbaf) which they fixed in v26, but that's in their auto-updater C++ code. Not sure how to do this with NSIS.

**Comment by itsmattkc** [comment]
Oh wow, good pickup.

The only thing I've found so far is this thread, where the OP ultimately decides to ignore the issue: https://nsis-dev.github.io/NSIS-Forums/html/t-314204.html
