### ISSUE TITLE
[UI] Missing icon in about dialog

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#1246]
When downloading the latest portable Olive nightly for windows and opening the about dialog the default symbol for missing icon appears instead of the olive logo. As far as I remember the same issue was in the Linux AppImage.

**Comment by itsmattkc** [comment]
This is a known issue, the idea of a new icon has been thrown around for quite some time and it's _generally_ assumed we'll have one by the time 0.2 is stable, so I've never bothered restoring the old one there.

**Comment by libalis** [comment]
Oh, ok. thank you very much for the explanation. Looking forward to seeing the new icon.
And while I'm here, I just wanted to say how amazing your work and olive in general is turning out.
It's simply amazing and I am so greatfull for everything this project achieved. So thank you and keep it up.
