### ISSUE TITLE
[PLAYBACK] No sound

### ISSUE THREAD

**Issue by Suganth526** [olive-editor/olive#1247]
**Commit hash** 

**Platform**
Windows

**Summary**
I just downloaded Olive 0.2 and imported media where I can't here any sound while playback of footage.
I imported media and playing the footage in Olive 0.2, the footage have sound but no sound while playing.

**Comment by itsmattkc** [comment]
Can you post a sample of the footage that has no sound?

**Comment by Suganth526** [comment]
> Can you post a sample of the footage that has no sound?

Google drive file link
[https://drive.google.com/file/d/1Imb2BBnjEnSTdPAq631ybE4_pBt3x6AH/view?usp=drivesdk]()

**Comment by itsmattkc** [comment]
Are you using the Windows installer?

**Comment by Simran-B** [comment]
@Suganth526  Please edit your initial post to include the commit hash (you find these 8 characters/digits in Olive's window title as well as in the _Help > About_ box) and whether you use Windows 10 or a different version.

> Can you post a sample of the footage that has no sound?

Thanks for sharing a video which shows the problem, but what we need is rather the video file that you imported into Olive (if possible). Then we can try to reproduce the problem.

**Comment by itsmattkc** [comment]
Indeed I was asking for the footage file itself, however the video we were sent does narrow it down a little since we can see the waveform in the timeline, which rules out a codec issue.

I ask if it's the installer because Olive still (incorrectly) tries to save PCM data in the working directory, which it wouldn't have access to if it was installed in `C:\Program Files`.

@Suganth526 If you're using the installer, you should try the portable version.

**Comment by Simran-B** [comment]
Or perhaps run Olive as administrator (elevated privileges), which should allow it to write to `C:\Program Files`?

**Comment by Suganth526** [comment]
> Are you using the Windows installer?

Yes

**Comment by Suganth526** [comment]
> @Suganth526  Please edit your initial post to include the commit hash (you find these 8 characters/digits in Olive's window title as well as in the _Help > About_ box) and whether you use Windows 10 or a different version.
> 
> > Can you post a sample of the footage that has no sound?
> 
> Thanks for sharing a video which shows the problem, but what we need is rather the video file that you imported into Olive (if possible). Then we can try to reproduce the problem.

I tested many footages but same problem

**Comment by Suganth526** [comment]
Thanks for all Suggestion , I installed portable version......
Thanks it is working..
![Screenshot (175)](https://user-images.githubusercontent.com/69079041/94814182-9e815600-0416-11eb-8de0-805db0a4c91a.png)

**Comment by itsmattkc** [comment]
I've made a general issue about this bug here: #1248

**Comment by Simran-B** [comment]
Using the Windows installer (b9359ce5), I can reproduce the problem with the Alexa footage (`Alexa_LF_B001C003_180327_R1ZA.mov`). There is no audio output, the meter doesn't show anything and it reports that it failed to open .pcm files in console:

```
[INFO] Setting output audio device to "Default Output Device" ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[INFO] Setting output audio device to "Default Output Device" ((null):0)
[WARNING] Failed to open "./18467.pcm" ((null):0)
[WARNING] Failed to write PCM data to "./18467.pcm" ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Playback queue failed to keep up ((null):0)
[ERROR] Failed to open "./18467.pcm" for audio playback ((null):0)
```

olive-editor.exe is in `C:\Program Files\Olive\`, so `.` refers to this folder which requires elevated privileges for writes. If I run Olive as admin, then audio works and it writes the .pcm files into the program folder.
