### ISSUE TITLE
[CACHE] PCM files are stored in the working directory

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1248]
**Summary**
Olive's audio cache files are incorrectly placed in the working directory. This is because disk caches are configurable per project and audio cache hasn't been updated to be able to move PCM data. On some platforms, this can lead to audio failing to play as Olive may not have write permission to the working directory.

**Additional Information / Output**
Audio cache needs rework in general, PCM data shouldn't be stored in one contiguous file like it s now. It's safer to store in chunks and we can also make some editing optimizations if we do that.

**Comment by Simran-B** [comment]
On Windows using the Installer version and the default installation path `C:\Program Files\Olive\`, there will be no audio unless olive-editor.exe is run as administrator because elevated privileges are required to write to this folder (where Olive tries to write .pcm files to).

**Comment by skinkie** [comment]
I have this issue on Linux. I have permissions on the working directory. Olive is able to play pcm audio on the _Sequence_ but not the _Footage_.

After changing the cache folder I am also able to crash the application.
```
[ERROR] Failed to open cached file "/home/skinkie/Opnames voor Boek en website/olive-test/23f8ac2fce5a4975c14471295890b2737da31fd21.44100.4.3" ((null):0)
Segmentation fault (core dumped)
```

I have also attempted to change the cache folder, save the project, close the application and reopen it. The PCM audio is not with the footage. To me this is a blocker for testing olive.

**Comment by itsmattkc** [comment]
Fixed in f7ab0bb640c7ee7b9d551eafa49213b33fa4366b

**Comment by skinkie** [comment]
@itsmattkc fails to compile

```
In file included from /home/skinkie/Sources/olive/app/audio/outputmanager.cpp:21:
/home/skinkie/Sources/olive/app/audio/outputmanager.h: In constructor 'olive::AudioOutputManager::AudioOutputManager(QObject*)':
/home/skinkie/Sources/olive/app/audio/outputmanager.h:78:26: error: 'olive::AudioOutputManager::device_proxy_' will be initialized after [-Werror=reorder]
   78 |   AudioOutputDeviceProxy device_proxy_;
      |                          ^~~~~~~~~~~~~
/home/skinkie/Sources/olive/app/audio/outputmanager.h:72:14: error:   'QIODevice* olive::AudioOutputManager::push_device_' [-Werror=reorder]
   72 |   QIODevice* push_device_;
      |              ^~~~~~~~~~~~
/home/skinkie/Sources/olive/app/audio/outputmanager.cpp:30:1: error:   when initialized here [-Werror=reorder]
   30 | AudioOutputManager::AudioOutputManager(QObject *parent) :
      | ^~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

```

**Comment by itsmattkc** [comment]
Fixed in 6ced8504d6ccafad04311a3e30a8bdaf3713470c

**Comment by skinkie** [comment]
@itsmattkc please reopen the issue. PCM playback in the "Footage" view is still muted.

**Comment by Simran-B** [comment]
Sound works in the timeline (6ced8504), but I also don't hear any audio from the footage viewer - but there seems to be a different problem: `[WARNING] Failed to read data from segment ((null):0)`
Olive hangs and spams the console with this message shortly after I start the playback in the footage viewer. It does not play the footage. Seems to occur with any footage, same with four completely different video files.

**Comment by skinkie** [comment]
@Simran-B to me the sound already worked in the timeline before the cache fixes, but not in the footage viewer.

@itsmattkc this is the output for just opening a clip, and playing it in the footage viewer;
```
[DEBUG] Extracting default OCIO config to "/home/skinkie/.cache/olivevideoeditor.org/Olive/ocioconf" (static void olive::ColorManager::SetUpDefaultConfig():92)
[INFO] Using Qt version: 5.15.0 (void olive::Core::Start():140)
[DEBUG] Using graphics driver: X.Org (virtual void olive::MainWindow::showEvent(QShowEvent*):641)
[INFO] Setting output audio device to "default" (void olive::AudioManager::SetOutputDevice(const QAudioDeviceInfo&):115)
[swscaler @ 0x7fdddc076280] deprecated pixel format used, make sure you did set range correctly
[WARNING] Tried to allocate sample buffer with zero sample count (void olive::SampleBuffer::allocate():134)
[DEBUG] No arenas, creating new... (olive::MemoryPool<T>::ElementPtr olive::MemoryPool<T>::Get() [with T = unsigned char; olive::MemoryPool<T>::ElementPtr = std::shared_ptr<olive::MemoryPool<unsigned char>::Element>]:336)
[swscaler @ 0x7fdddc03d080] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fddd4076280] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fddbc076280] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fddc8076280] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fddc4076280] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fddd8076280] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fddcc076280] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fdddc2b7480] deprecated pixel format used, make sure you did set range correctly
[INFO] Setting output audio device to "default" (void olive::AudioManager::SetOutputDevice(const QAudioDeviceInfo&):115)
[DEBUG] All arenas are full, creating new... (olive::MemoryPool<T>::ElementPtr olive::MemoryPool<T>::Get() [with T = unsigned char; olive::MemoryPool<T>::ElementPtr = std::shared_ptr<olive::MemoryPool<unsigned char>::Element>]:338)
[DEBUG] Removing an empty arena (void olive::MemoryPool<T>::ArenaIsEmpty(olive::MemoryPool<T>::Arena*) [with T = unsigned char]:373)
[DEBUG] All arenas are full, creating new... (olive::MemoryPool<T>::ElementPtr olive::MemoryPool<T>::Get() [with T = unsigned char; olive::MemoryPool<T>::ElementPtr = std::shared_ptr<olive::MemoryPool<unsigned char>::Element>]:338)
[DEBUG] Removing an empty arena (void olive::MemoryPool<T>::ArenaIsEmpty(olive::MemoryPool<T>::Arena*) [with T = unsigned char]:373)
```

**Comment by Simran-B** [comment]
@skinkie What was the working directory? This issue is about .pcm files getting written to `C:\Program Files\Olive` where Olive has no write permissions unless you run it as administrator. With the portable Olive package this wasn't an issue and audio played for the timeline without issues for me too.

**Comment by skinkie** [comment]
@skinkie the build folder. I came here via #1247 (the no sound issue).

**Comment by Simran-B** [comment]
That's explains why audio worked for you in the timeline. No sound in footage viewer doesn't seem to be related to either of the issues, I think you should create a new one.

**Comment by skinkie** [comment]
@Simran-B done via #1266
