### ISSUE TITLE
[PROJECT] Cannot open projects made with olive 0.1

### ISSUE THREAD

**Issue by sergiocallegari** [olive-editor/olive#1250]
**Commit Hash**
b9359ce5

**Platform**
Kubuntu linux 20.04

**Summary**
This summer I made some work using olive 0.1. Now I cannot open those ove files. When I point olive editor to them, simply nothing happens. There is no error, but the project pane remains at Project untitled.

It is my understanding that olive 0.2 should be able to open projects from olive 0.1. If this is not the case, at least a failure message should be provided.

**Comment by itsmattkc** [comment]
0.2 will not be able to open 0.1 project files. While an upgrade tool may be created at some point (either by us or the community), the project files are incompatible and not interchangeable.

I've added a message about this in de9c67a0f8db440942dd88faa339b3ba0805929b.

**Comment by sergiocallegari** [comment]
Thanks for the prompt action. I guess, this is no time to open a feature request about back compatibility because of the need to stabilize 0.2 first. But I hope that the matter is given due consideration right after. Without any polemic intent and in fact with great appreciation to the project, I'd like to suggest that otherwise the message that the users may hear is that it was a mistake to base their projects on Olive 0.1 and that a similar issue may repeat with future releases after 0.2. In the end, even if we are at a zero-dot- release, the "professional" label used by Olive comes with great expectations including the ability to base new work on older one.

In the meantime, if there is any workaround for the issue (e.g., exporting the project in some common external format with Olive 0.1 and importing that in 0.2) would be great if that could be documented too in the error message provided by de9c67a.

**Comment by sobotka** [comment]
This is a complete and utter waste of time. How many projects actually are so large and mandatory to forward port? You can always use 0.1.x infinitely.

If there were some crazy project that desperately needed this (Hint: There are zero), the wisest path would be for someone to adopt the 0.1.x lineage and integrate OpenTimelineIO, then load the result in the 0.2.x lineage.
