### ISSUE TITLE
[UI] Timeline does not update properly on new sequence

### ISSUE THREAD

**Issue by JellyOsaurus** [olive-editor/olive#1253]
ebd9e271

Windows 10 64 Bit

You can add extra tracks with ease by just adding clips in other areas of the timeline, but once you have multiple tracks and decide maybe you wanna go delete that sequence and create a new one, the timeline UI does not update properly. 

Steps to Reproduce:
1. create a new sequence
2. add as many tracks as you want, as long as there is more than 2
3. Delete your sequence
4. Make a new sequence

Result: you get 2 tracks, but the track lables and controls do not update properly back to 2 tracks only. 
![image](https://user-images.githubusercontent.com/22872180/95159055-ede6bf80-0751-11eb-9346-cba14af434ab.png)

**Comment by ThomasWilshaw** [comment]
I can confirm this. I'd add that if I then drag a clip onto the new sequence it can mess up the vertical alignment of clips a tracks even more (note the scroll bar doesn't do anything even thought the clip is partially hidden)

![image](https://user-images.githubusercontent.com/7781683/95518667-7320dd00-09bb-11eb-9f82-25497cb7cdee.png)
