### ISSUE TITLE
[CRASH] Deleting a specific Math node in the attached Project crashes Olive

### ISSUE THREAD

**Issue by FirasH** [olive-editor/olive#1261]
**Commit Hash** 
Olive 0.2.0 ac4be090

**Platform**
Windows 10

**Summary**
Deleting a specific `Math` node in the `Node Editor` crashes Olive with the attached project file.
The project file has been simplified and does not contain any imported media for easier uploading.

**Steps to Reproduce**

1. Open the attached project file:
[CRASH-MATH-NODE-MINIMAL.zip](https://github.com/olive-editor/olive/files/5355574/CRASH-MATH-NODE-MINIMAL.zip)

2.  Go to the `Node Editor`, right-click and select `Filter > Show All`
Now you'll see the following Node graph:
![Math-Node](https://user-images.githubusercontent.com/6705690/95595815-e4f53700-0a4c-11eb-8b12-7cf37af3937c.jpg)

3. Delete the highlighted `Node`

Olive crashes consistently.

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
I didn't do anything fancy with this project, just moved around some audio and video clips on more tracks.
Something seemed to be strange before the crash, because at some point a whole Audio Track was completely muted, no idea why though.

**Comment by ThomasWilshaw** [comment]
Sorry for the delay on this, are you still getting this issue on the latest master?

**Comment by FirasH** [comment]
@ThomasWilshaw, doesn't crash anymore 👍 
Thanks for the quick fix!
