### ISSUE TITLE
[PLAYBACK] No Sound for PCM audio footage in Footage Viewer

### ISSUE THREAD

**Issue by skinkie** [olive-editor/olive#1266]
**Commit Hash** 
6ced8504d6ccafad04311a3e30a8bdaf3713470c

**Platform**
Linux 64 bit

**Summary**
No Sound for PCM audio footage in Footage Viewer

**Additional Information / Output**
Same footage in the timeline does play audio.

**Comment by itsmattkc** [comment]
Can you send a file that exhibits this issue? Every file works for me.

Also can you confirm it happens in the AppImage?

**Comment by skinkie** [comment]
@itsmattkc http://stefan.konink.de/P6092423.AVI

The app image does **not** give me sound for both the footage **and** the timeline.

**Comment by skinkie** [comment]
@itsmattkc confirmed! Thanks.
