### ISSUE TITLE
[PLAYBACK] First audio track is played mistakenly

### ISSUE THREAD

**Issue by jesusvimlet** [olive-editor/olive#1273]
**e5b18fa** 

**Platform**
Windows 10

**Summary**
When I hit play if there is no audio at the current start point, it plays the first audio track in the timeline. It is annoying to record while watching the video.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Fixed in 921608e1df8c4ba64ddb2fb9104937f8ec5ed0a4
