### ISSUE TITLE
cannot open

### ISSUE THREAD

**Issue by khlee9007** [olive-editor/olive#1274]
Build Environment: arm64 (arm64-little_endian-lp64)
Run Environment: arm64
Kernel: linux 4.14.117-perf+
System: Ubuntu 20.10 (ubuntu 20.10)

olive-editor(_ZN5olive13crash_handlerEi+0xf8)[0x300019cfe8]
linux-vdso.so.1(__kernel_rt_sigreturn+0x0)[0x71cb6bc63c]
/lib/aarch64-linux-gnu/libc.so.6(gsignal+0xd8)[0x71c7595f58]
/lib/aarch64-linux-gnu/libc.so.6(abort+0xf4)[0x71c758250c]
/lib/aarch64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x19c)[0x71c784a87c]
/lib/aarch64-linux-gnu/libstdc++.so.6(+0x9f1dc)[0x71c78471dc]
/lib/aarch64-linux-gnu/libstdc++.so.6(+0x9f240)[0x71c7847240]
/lib/aarch64-linux-gnu/libstdc++.so.6(+0x9f534)[0x71c7847534]
/lib/libOpenColorIO.so.1(_ZN11OpenColorIO2v16Config14CreateFromFileEPKc+0x254)[0x71c977c7c4]
olive-editor(_ZN5olive12ColorManager20CreateConfigFromFileERK7QString+0x68)[0x3000234f98]
Version: 
Signal: 6

**Comment by sobotka** [comment]
This is a completely awful report, that doesn’t follow the template.

**Comment by Simran-B** [comment]
Olive only targets x86_64. No ARM support.
