### ISSUE TITLE
[EXPORT] Lack of audio

### ISSUE THREAD

**Issue by Dashingo** [olive-editor/olive#1276]
**Platform** 
Windows10
**Problem**
Um, when I export there is no sound, and yeah that's it.
Additional Information

**Comment by AGI-THB** [comment]
Not helpful at all.

**Comment by Dashingo** [comment]
> Not helpful at all.
Well, what other information would be needed?

**Comment by ThomasWilshaw** [comment]
What input file format? What export settings? Any console output? What are playing the export in to confirm there's no audio? Can you provide sample footage? What commit hash? Etc.
