### ISSUE TITLE
Sound after the video soundtrack

### ISSUE THREAD

**Issue by PatLabGit** [olive-editor/olive#1281]
**Commit Hash** 
I have no idea what's a hash (which title bar?)

**Ubuntu-MATE 20.04 / Olive 0.2.0**

The sound starts after the track on the timeline, which make it impossible to edit (see screenshot)
![Screenshot at 2020-10-27 14-38-00](https://user-images.githubusercontent.com/47497693/97266545-996fc500-1863-11eb-953a-7171cdb15560.png)

**Comment by Simran-B** [comment]
@PatLabGit It's typically in the top left, but your title bar only says `Olive` for some reason. Please click the menu _Help > About_ and check for the version there. The relevant part is the 7 or 8 alphanumeric characters, like 379a799a, which refer to a specific code change (commit). `0.1.0` or `0.2.0` is not a useful version information because it's ambiguous. Could be a build from yesterday or from several months back.

**Comment by itsmattkc** [comment]
That looks like a very, very old build. Did you install from `sudo apt install olive-editor` by any chance? We didn't create that distribution and have no way of updating it. Please try again with the [current nightly](https://olivevideoeditor.org/nightly.php).

**Comment by PatLabGit** [comment]
> @PatLabGit It's typically in the top left, but your title bar only says `Olive` for some reason. Please click the menu _Help > About_ and check for the version there. The relevant part is the 7 or 8 alphanumeric characters, like [379a799](https://github.com/olive-editor/olive/commit/379a799ad9b16696388367e0242be399ab12951d), which refer to a specific code change (commit). `0.1.0` or `0.2.0` is not a useful version information because it's ambiguous. Could be a build from yesterday or from several months back.

Still... no hash
![screenshot_20201028-134358](https://user-images.githubusercontent.com/47497693/97397275-d69b8c00-1923-11eb-9b21-5bfc8d735e71.png)

**Comment by PatLabGit** [comment]
> Did you install from `sudo apt install olive-editor` by any chance? 

That's very possible (in the software center it says Version:20200210-1 => from february..?)
![screenshot_20201028-135850](https://user-images.githubusercontent.com/47497693/97398214-c1bff800-1925-11eb-98fb-84c3d5b12be0.png)
> Please try again with the current nightly.
I'll do, i'll try the appImage.
Thanks a lot
