### ISSUE TITLE
[CRASH] JPG images lock Olive on import

### ISSUE THREAD

**Issue by Electrice** [olive-editor/olive#1283]
**Commit Hash** 
5f5d6e8

**Platform**
Windows 10

**Summary**
Jpg images lock up Olive on import

**Steps to Reproduce**

1. Drag jpg image into project
2. Stare at locked up Import Dialog
3. 

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
![image](https://user-images.githubusercontent.com/58629417/97284978-0f4e3f00-1818-11eb-9354-5aae124c18aa.png)

**Comment by Simran-B** [comment]
I can reproduce the problem with 379a799a. The import dialog is stuck. If I close it and try again, then an access violation crashes Olive (submitted crashpad report).

**Comment by itsmattkc** [comment]
Confirmed, but only on the CI build. Might be something to do with the OIIO or turbojpeg package we're using.

**Comment by Simran-B** [comment]
Is there a known good version of OIIO/turbojpeg?

**Comment by itsmattkc** [comment]
Fixed as of 10d2ea823c45dccd058cbb2d06bd9fcadcf5c375
