### ISSUE TITLE
[NODES] Polygons add default points on reload

### ISSUE THREAD

**Issue by Electrice** [olive-editor/olive#1285]
**Commit Hash** 
5f5d6e8

**Platform**
Windows 10

**Summary**
Change a polygon in some significant way like moving all it's points into a corner and adding some new points. Then save the project, close it and relopen it. The polygon will get the original points added back in on reloading. 

**Additional Information / Output**
Before
![image](https://user-images.githubusercontent.com/58629417/97363904-a4cdeb00-1879-11eb-81d1-33aba82a16ac.png)
After
![image](https://user-images.githubusercontent.com/58629417/97364061-d9da3d80-1879-11eb-9456-bcb72443390f.png)

**Comment by itsmattkc** [comment]
Semi-known issue. Polygon node is still pretty crude and has never really been "finished".

**Comment by mattxjohnston** [comment]
I can confirm this on Ubuntu Linux as well. 
5.4.0-52-generic #57~18.04.1-Ubuntu SMP x86_64 GNU/Linux

There is also a thread ongoing about this in the Facebook group:
https://www.facebook.com/groups/olivevideoeditor/permalink/807239960027620/

For me, I don't even need to change the polygon. Open project > add polygon with 5 sides > save and close Olive > reopen the project > Polygon now has 10 points. If I run through that save > close > reopen process again it will bump the point count to 15.

I can add any debugging info that the devs think will help.

**Comment by Simran-B** [comment]
No need, it's clear what the issue is. It's simply not fully implemented yet.

**Comment by itsmattkc** [comment]
Merging this with #1339
