### ISSUE TITLE
[REQUEST] Time interpolation on video clips and on export.

### ISSUE THREAD

**Issue by leg7** [olive-editor/olive#1289]
It would be really cool to add time interpolation settings such as frame blending, optical flow and frame sampling to individual video clips and to the whole video on export.

Here's a video showcasing the three effects in premiere pro: 
https://youtu.be/jScpocUJGAQ

Tell me if I'm being unclear.

**Comment by sobotka** [comment]
What part of “No feature requests” is not clear at this point?

**Comment by Simran-B** [comment]
See #1175

**Comment by leg7** [comment]
> What part of “No feature requests” is not clear at this point?
> 
> Reading is critical.

![image](https://user-images.githubusercontent.com/68823179/97506211-b4812880-197a-11eb-95be-dfac07df0136.png)

Maybe you should chill out and rephrase this so that it says "No feature requests allowed" as you would like it to be instead of "Most feature requests will be rejected".

You can't just expect ppl to read your mind and throw tantrum like an 8 year old when they can't.

**Comment by sobotka** [comment]
Maybe being a genius and suggesting something that literally every single person on the planet knows about isn’t as smart as you think?

**Comment by Simran-B** [comment]
Adjusted #1175 to "No feature requests" and removed reference to Discord server, which is no longer an official server but only a community platform.

> Our current focus is on making Olive 0.2 a stable and usable program for editing video, so we would appreciate if you primarily provide issues that support this goal.

In case it isn't clear: the goal is to make Olive **work at all**. Things like frame blending, optical flow etc. are way out of scope.

**Comment by leg7** [comment]
> Adjusted #1175 to "No feature requests" and removed reference to Discord server, which is no longer an official server but only a community platform.
> 
> > Our current focus is on making Olive 0.2 a stable and usable program for editing video, so we would appreciate if you primarily provide issues that support this goal.
> 
> In case it isn't clear: the goal is to make Olive **work at all**. Things like frame blending, optical flow etc. are way out of scope.

I understand, I thought this would just be added to the backlog. Olive 2.0 instantly crashes for me when I try to add footage to the timeline, will make a report soon.

**Comment by elsandosgrande** [comment]
I presume that you manually compiled Olive. If your version of FFmpeg is 
4.3.0, then you're encountering a know FFmpeg bug which causes Olive to 
crash whenever you add a video to the timeline (see pinned issue). If 
your version of FFmpeg is 4.3.1, then it might depend on your operating 
system whether or not it is affected by the same bug. The 4.3.1 tag in 
the FFmpeg Git repository hosted by VLAN came four days before the fix 
for the bug was committed to the repository, yet I am not encountering 
any crashes with FFmpeg 4.3.1 on Ubuntu Groovy.


Also, a backlog would not make much sense as things may or may not stay 
similar enough to make going through the backlog worth the effort.

**Comment by leg7** [comment]
> I presume that you manually compiled Olive. If your version of FFmpeg is 4.3.0, then you're encountering a know FFmpeg bug which causes Olive to crash whenever you add a video to the timeline (see pinned issue). If your version of FFmpeg is 4.3.1, then it might depend on your operating system whether or not it is affected by the same bug. The 4.3.1 tag in the FFmpeg Git repository hosted by VLAN came four days before the fix for the bug was committed to the repository, yet I am not encountering any crashes with FFmpeg 4.3.1 on Ubuntu Groovy. Also, a backlog would not make much sense as things may or may not stay similar enough to make going through the backlog worth the effort.

Olive is crashing when adding footage to the timeline with ffmpeg 4.3.1-2 on Arch Linux 5.9.1-zen2-1-zen. (Olive freshly compiled)

**Comment by elsandosgrande** [comment]
Yeah, that seems like it's the FFmpeg bug described in the pinned issue. 
You'll need to either downgrade FFmpeg to the latest version on the 4.2 
branch, or get the AppImage from the website.

/Now I wonder why **I** am not affected across any of my six Olive 
builds in spite of having 4.3.1/
