### ISSUE TITLE
Auto-scaling

### ISSUE THREAD

**Issue by main-gi** [olive-editor/olive#129]
Honestly I'm not sure what this is formally, but when you put in lower resolution footage into the timeline I wish I didn't have to scale it up to fill the screen, which is what I usually want.

**Comment by itsmattkc** [comment]
Will add tomorrow

**Comment by itsmattkc** [comment]
Implemented in b88468f9e3f0c4cf53edeef056cd07dc659efede with a setting to auto-scale by default
