### ISSUE TITLE
[NODES] Polygon "subtract" element

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1293]
**Commit Hash**
34cb7c96

**Platform**
Any

**Summary**
As is possible to add new elements to the polygon, it would be nice to have a delete or subtract elements, as simple as that.

**Additional Information / Output**

**Comment by Simran-B** [comment]
As in make holes into the polygon using another polygon? Or use a single polygon and use it as mask, but inverted?

**Comment by sobotka** [comment]
Bear in mind that polygons might need to be used in conjunction with emissions, so the data range should be negative infinity to positive infinity.

**Comment by Simran-B** [comment]
@sobotka Doesn't that concern the math node rather than the polygon node?

**Comment by ThomasWilshaw** [comment]
I suppose it's a question of whether polygon nodes should be a 0-1 mask or something that can take an arbitrary value and therefore be directly used as a power window or whatever.

**Comment by sobotka** [comment]
Depends. The filling of the data is where it would be relevant.

**Comment by Simran-B** [comment]
From a design standpoint, I'd say that polygon nodes should merely define a shape and the value ("strength") should be defined by a math or primitive value node (remeber ZoomTen's [absolute value node](https://discord.com/channels/549629829730009089/550374368383991821/759715707784527892)?).

From a pixel management perspective, I'm not sure about the implications, e.g. regarding anti-aliasing. UI-wise it might be sensible to have a soft min of 0 but hard min of negative infinity.

**Comment by sobotka** [comment]
The range of values along subpixel geometry can likely start with a simple lerp and then be expanded.

**Comment by pgilfernandez** [comment]
I feel like I didn't correctly explain myself...

I was suggesting to modify the Polygon Node in order to be able to select the nodes I want:
<img width="286" alt="polygons" src="https://user-images.githubusercontent.com/5942369/97678894-d373dd80-1a94-11eb-94b3-e227292a9e84.png">
As you see, by default it starts with a pentagon (5 elements). I'm able to press the "+" button to have an hexagon, etc.
But **there is not available a "-" button to decrease the number of elements** and get, for instance, a square or triangle.
It would be handy also if you create my mistake too many elements and want the node to have less ones.

Thanks!

**Comment by ThomasWilshaw** [comment]
Thanks for clarifying :)

**Comment by AngeloFrancabandiera** [comment]
From the default 5 points poliygon, I have tried to close Olive, manually erase 2 points in .ove XML file (by deleting the <input> tag), then reloaded the project in olive. The result is a mask with 8 points: the original 5 points and 3 new points that are the same as the first 3 points of the original polygon.
I really can't explain this behavior. Is there a kind of consistency check in project file?

**Comment by Simran-B** [comment]
No, there is a simple explanation: the polygon node isn't fully implemented. The polygon is initialized with 5 points. It is also initialized on load. So it's +5 points on every load. This was already reported here: #1285

**Comment by itsmattkc** [comment]
Merging this with #1339
