### ISSUE TITLE
[UI] Project can't be saved

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1294]
**Commit Hash** 
34cb7c9

**Platform**
macOS

**Summary**
When trying to save a project with "save", "save as" or "save all" results on the "open project" window so it's impossible to save the project.

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
I can confirm this. However I think it's only a typo rather than a bug, projects still save although the button is labeled as "Open".

**Comment by Simran-B** [comment]
Should be fixed by:
https://github.com/olive-editor/olive/commit/de48eba7131232314878205dae3664991a752435
Let's wait for the CI results.

**Comment by pgilfernandez** [comment]
I have compiled it by myself and I can confirm it's fixed =)

Thanks!
