### ISSUE TITLE
[UI] Preference entry for "node editor direction"

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1295]
**Commit Hash** 
34cb7c9

**Platform**
Any

**Summary**
It would be nice to have an option inside Preferences to set a default for the "node editor direction".

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
Linked:
https://github.com/sobotka/olive/issues/80

**Comment by Dead-M** [comment]
ill have a look where would this be at and exactly what did you want it to do no grantees.

**Comment by Simran-B** [comment]
You should probably take a look here:
- https://github.com/olive-editor/olive/blob/master/app/widget/nodeview/nodeviewscene.cpp#L38
- https://github.com/olive-editor/olive/blob/master/app/config/config.cpp
- https://github.com/olive-editor/olive/blob/master/app/dialog/preferences/preferences.cpp

**Comment by itsmattkc** [comment]
I actually think have a setting in preferences is the wrong approach and it would be better to simply make the last flow direction used persistent. It might even make sense to have a "default new project" similar to Blender.
