### ISSUE TITLE
[EXPORT] Exporting a Video (27 minutes) stuck at 0% and then Olive crashes

### ISSUE THREAD

**Issue by NitroTheFlygon** [olive-editor/olive#1296]
**Commit Hash** 
34cb7c96

**Platform** Windows 10

**Summary** Anything I'm doing wrong here? I've been attempting this for like seven times to the same crash. I'm new to this so maybe I'm doing something wrong, but maybe the crash report will explain...

Yeah, when I click export, it stays stuck at 0%, Olive lags and/or freezes, and then it crashes.

Operating system: Windows NT
                  10.0.19041 546
CPU: amd64
     family 6 model 158 stepping 13
     6 CPUs

GPU: UNKNOWN

Crash reason:  EXCEPTION_INT_DIVIDE_BY_ZERO
Crash address: 0x7ffae316cc30
Process uptime: 1573 seconds

**Additional Information / Output**

**Comment by Simran-B** [comment]
Please provide the exact version (commit hash).

Does it always crash with a division by zero error?

**Comment by NitroTheFlygon** [comment]
> Please provide the exact version (commit hash).
> 
> Does it always crash with a division by zero error?

Yeah, and it's version 0.2.0-34cb7c96.

**Comment by itsmattkc** [comment]
Can you provide more information about your timeline/project? How many clips do you have, what kind of footage, etc.

**Comment by NitroTheFlygon** [comment]
I was using recordings of the desktop screen, with a total of two 5 audio lanes and 2 video lanes, 27 minutes long. When I inserted some audio files, it crashed as well.
![Screenshot 2020-10-30 103025](https://user-images.githubusercontent.com/73679714/97718119-ed64ee80-1a9b-11eb-9bab-9263b5396529.png)

**Comment by Simran-B** [comment]
Can you reproduce the problem with black exports also with a single, short clip of the same footage? Can you share that footage? Also, have you tried to play the expected video in VLC?

**Comment by NitroTheFlygon** [comment]
> Can you reproduce the problem with black exports also with a single, short clip of the same footage? Can you share that footage? Also, have you tried to play the expected video in VLC?

I tried playing it in VLC ad the same thing happened; still a black screen.

**Comment by NitroTheFlygon** [comment]
> Can you reproduce the problem with black exports also with a single, short clip of the same footage? Can you share that footage? Also, have you tried to play the expected video in VLC?

Have you ever had your exports be black screens?

**Comment by itsmattkc** [comment]
Does the latest commit fix this?

**Comment by itsmattkc** [comment]
I will assume this is fixed in the latest commit unless otherwise specified.
