### ISSUE TITLE
[UI] Unable to change language

### ISSUE THREAD

**Issue by aaronbcn** [olive-editor/olive#1298]
**Commit Hash** 
34cb7c96

**Platform**
Windows 10 (Portable version)

**Summary**
In the Preferences-General section, only shows American English this one option. The select list won´t open.

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/65270897/97791537-aaa63200-1bd3-11eb-8cb5-4a2771796e4c.png)

**Comment by ThomasWilshaw** [comment]
There's currently no translations available in Olive 0.2. It's currently low priority till everything is more stable but if anyone is able to provide/maintain translations that would be more than welcome

**Comment by elsandosgrande** [comment]
Yeah, I'm just waiting for Matthew to say that Olive is ready to be translated and I'll do it for the Serbo-Croatian languages. Olive is currently fortifying its base and that is the main priority at the moment.

**Comment by itsmattkc** [comment]
Yeah, this isn't a bug, we just don't have any other languages yet.
