### ISSUE TITLE
Audio/video effects for entire tracks

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#13]

**Comment by itsmattkc** [comment]
later my child

**Comment by maingi2** [comment]
audio/video effects for E N T I R E S E Q U E N C E ?

**Comment by itsmattkc** [comment]
**_ENTIRE SEQUENCES_**

**Comment by elsandosgrande** [comment]
Wait, how would it even work for entire sequences?

**Comment by frink** [comment]
I think this has to do with things like coloration effects or overlays which are both handled differently in Olive...

**Comment by unfa** [comment]
+1 for effects for tracks
+1 for effects for sequences

This'd allow to have a master audio limiter, which is a really needed thing.

**Comment by Simran-B** [comment]
I wonder how this could be integrated the most sensible way...

1. Right-click a Sequence in the Project panel > *Preview in Media Viewer* and the Effects tab could then be updated to the Sequence. The user would need to switch to the Effects panel manually though, which wouldn't be very obvious.

   ![image](https://user-images.githubusercontent.com/7819991/56373942-5e1e2000-6202-11e9-805d-a0cede3ed795.png)

2. Same as above, but with a dedicated entry in the menu to *Edit Effects*. This would switch to the Effects tab and be thus straightforward.

   ![image](https://user-images.githubusercontent.com/7819991/56374342-38dde180-6203-11e9-990d-4e5ce43dd244.png)

3. Integrated into the *Properties* dialog. Transitions don't make much sense here I guess, and some parameters not either (the entire transformation panel?!). This would make the dialog quite convoluted and introduce the need for a scrollbar.

   ![image](https://user-images.githubusercontent.com/7819991/56376014-3087a580-6207-11e9-83ac-6f24d59e6d8e.png)

4. Tweak the audio meter into something like a muster bus. Not sure how I feel about adding the *Add Video Effect* button there... but it would require distinct icons for video and audio effects.

   ![image](https://user-images.githubusercontent.com/7819991/56376951-83625c80-6209-11e9-95d0-73697b5144fc.png)

5. Somewhere else?

For effects per track, an obvious solution would be to add a column in front of the timeline:

![image](https://user-images.githubusercontent.com/7819991/56378917-bbb86980-620e-11e9-97b3-6bc8c14d7019.png)

In my mockup there is a title and the button to add an effect to a track, but this could actually be extended a lot:
- hide/mute track
- lock track
- collapse/expand track to save vertical space
- set color for track to visually group tracks (common in DAWs, not sure if useful in a video editor)

**Comment by itsmattkc** [comment]
This will be addressed in the node rewrite.

**Comment by frink** [comment]
Are we going to reopen these issues when we do the restructure? Or what is your thought?
