### ISSUE TITLE
[EDIT] Playback loop not behaving correctly

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1302]
**Commit Hash** 
de48eba7

**Platform**
macOS 10.14.6

**Summary**
When you create IN and OUT points you expect to preview the entire timeline hitting the spacebar (Play) and preview just the IN-OUT selection when pressing SHIFT+spacebar (Play In to Out). This works fine.

If you mark Playback/**Loop** and play with just spacebar (Play) you expect to preview the entire timeline in a loop but the result is the Play In to Out loop.

**Additional Information / Output**
This is my timeline, it's just a simple sequence:
<img width="464" alt="timeline" src="https://user-images.githubusercontent.com/5942369/98013292-7e202f00-1dfa-11eb-8cdf-cf93146d5416.png">

**Comment by itsmattkc** [comment]
I believe that's actually working completely as intended. Whether that behavior is desirable I guess is up to debate.

**Comment by Simran-B** [comment]
There's definitely something odd about it.

- If Playback > Loop is enabled and the playhead is **before** the selection, then hitting Space starts the playback at the current playhead position and it will loop once it reaches the selection.

- With the playhead **after** the selection, hitting Space teleports the playhead to the beginning of the selection and it is looped.

Wouldn't it be better if Space consistently started/stopped playback from the current playhead position?

Shift+Space starts the playback from the beginning of the selection, and loops if looping is enabled - all good.

Not sure whether Space should loop the selection or rather the sequence - or maybe both? If the playhead reaches the end of the sequence, then it could start from the beginning of the sequence. If it encounters a selection, then it could start to loop that. It's unclear to me what behavior is the most useful for editing. Is it worth to split the Loop option into two, one for selection and one for sequence, or would that be too much?

**Comment by pgilfernandez** [comment]
That's the point, I would say that space always plays the entire sequence, no matter if looped or not while "shift-space" always plays the In-Out selection, looped or not.
