### ISSUE TITLE
[PLAYBACK] Playback queue failed to keep up

### ISSUE THREAD

**Issue by Laanis** [olive-editor/olive#1304]
I was mixing a audio with a minecraft gameplay, and tried to cut some parts to get them on the same size.. when it only have that!
![image](https://user-images.githubusercontent.com/73965901/98164914-c5262700-1ec3-11eb-819a-1eb6cddc1ce0.png)
and i just did this, only get my audio with a minecraft gameplay and have this.

My computer it's a acer aspire 3 A315-53-32U4

**Comment by ThomasWilshaw** [comment]
That's not an error, it's just telling you the playback cache can't keep up. Maybe set your cache resolution lower

**Comment by itsmattkc** [comment]
You're getting no video? Could you share some of the footage?

**Comment by itsmattkc** [comment]
Does the latest commit fix this?

**Comment by Laanis** [comment]
> You're getting no video? Could you share some of the footage?

i get video, but it's lagging

**Comment by Simran-B** [comment]
Acer Aspire 3 A315-53-32U4 specs:

- Intel Core i3-7020U, 2.30 GHz base frequency, 3MB Cache
- Intel HD Graphics 620, 300 MHz - 1.00 GHz, OpenGL 4.5, DirectX 12
- 4GB RAM
- 1TB HD

https://www.magazinevoce.com.br/magazinepablomax/p/notebook-acer-aspire-3-a315-53-32u4-intel-core-i3-4gb-1tb-156-windows-10/3984823/
https://ark.intel.com/content/www/de/de/ark/products/122590/intel-core-i3-7020u-processor-3m-cache-2-30-ghz.html

That's a pretty low powered system with an ultra-low voltage mobile CPU, a not very powerful integrated GPU and a spinning disk with unknown RPM. I'm pretty sure lag is to be expected on such hardware.

**Comment by Laanis** [comment]
I thought that was potent.. That's why roblox crashes my computer!!
