### ISSUE TITLE
[CACHE] Clear cache menu entry

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1305]
**Commit Hash** 
de48eba7

**Platform** 
macOS 10.14.6

**Summary**
It would be nice to have a menu entry inside "Sequence" to clear the entire cache. Maybe it's something not useful while in production and when the software is robust, but in the meanwhile it would be nice to have a fast way to launch this task.

Thanks

**Additional Information / Output**

**Comment by Simran-B** [comment]
So basically a quicker way to do this?

![image](https://user-images.githubusercontent.com/7819991/98237593-6b763900-1f65-11eb-8d45-ba706528617d.png)

**Comment by pgilfernandez** [comment]
Yes, this is just what I'm looking for, without the need to close Olive. Have in mind that sometimes Olive crashes and it doesn't clear the cache...

**Comment by Simran-B** [comment]
I guess it would make sense to change the feature to "Automatically clear disk cache on close and start", so that you can be sure that there are no leftovers, even if a crash occurred.

**Comment by pgilfernandez** [comment]
Yes, that would make sense too, "on close and start".
But I still think the option to easily clear the cache on demand from the menu would be great (I'm experimenting cache issues and it would be handy... I guess more people will find it also handy)

**Comment by Simran-B** [comment]
Here's a PR: #1306

I'm slightly concerned that the path it tries to delete is `''`. This is also the case with the existing dialog...

![image](https://user-images.githubusercontent.com/7819991/98245708-a0888880-1f71-11eb-8eb5-849362a6a112.png)

**Comment by elsandosgrande** [comment]
> Here's a PR: #1306
> 
> I'm slightly concerned that the path it tries to delete is `''`. This is also the case with the existing dialog...
> 
> ![image](https://user-images.githubusercontent.com/7819991/98245708-a0888880-1f71-11eb-8eb5-849362a6a112.png)

I'm still seeing this to this day:
![image](https://user-images.githubusercontent.com/40576902/113406680-34893f80-93ac-11eb-9717-8a88dfa197f3.png)

As expected, it does not clear even a single byte of the cache (it couldn't have forgotten all of it, since I had cached and regularly closed Olive several times).
