### ISSUE TITLE
[UI] Several Full Screen Viewers can be created on the same monitor

### ISSUE THREAD

**Issue by samytichadou** [olive-editor/olive#1307]
**Commit Hash** 
de48eba7

**Platform** 
Windows 10

**Summary**
No clear way to exit full screen display

**Additional Information / Output**

Hi guys, congrats for nightly builds of Olive, feels a lot more stable than versions from a few months back ! 
I didn't find a clear way to exit full screen display of program monitor, i have to exit through an alt-f4 or ctl-q every time i use it. I tried to toggle it through the right click menu of the playback window, didn't work.
Am i missing something or is it a missing feature ?
Cheers an thanks for your hard work !

**Comment by Simran-B** [comment]
- _View > Full Screen_ shows <kbd>F11</kbd> as hotkey, which acts as a toggle to get in and out of borderless window mode (on Windows).

- _View > Full Screen Viewer_ displays the viewer fullscreen and you can get back out with <kbd>Esc</kbd>.

- Right-click on Viewer, _Full Screen > Screen 0: 1920x1080_ (or another screen/resolution) displays the viewer fullscreen on the respective display. You can exit it with <kbd>Esc</kbd>.

Note that for the Escape key to work, the window needs to be active. Move your cursor over to the right screen, click with the left mouse button once, then hit <kbd>Esc</kbd>.

There's also a bit of a bug: If you right-click on the fullscreen viewer, the main window becomes visible and the context menu shows up. If you dismiss the menu, then the UI is seemingly unresponsive including the Windows task bar. But I think the fullscreen mode is actually blocking events, even though it isn't visible in this case. Hitting Escape fixes it (by closing the invisible fullscreen viewer).

**Comment by samytichadou** [comment]
Thanks for the explanation, i was indeed talking about the "right click on Viewer" situation. 

I was able to reproduce what went wrong in my case, here it is :

- 1 : I **toggled** full screen viewer on my second monitor through right clicking in the _sequence viewer->full screen->screen 1_ (
- 2 : when my edit finished, i didn't press escape to exit from full screen, my first thought was to right click again and try to "untoggle" _context menu sequence viewer->full screen->screen 1_. By doing that, i accidently created a second _Full Screen viewer_ on the same monitor, but from a user point of view, it seems to do nothing
- 3 : After that unsuccessful try, i pressed escape, and nothing happened (because it actually closed one of the two _full screen viewers_ opened on this monitor.

So yep, i had a weird "instinct" : _sequence viewer->full screen->screen 1_ for me was a switch to turn on and off (i think this is the case in another nle i used some days) and this will probably not be the case of other users, but the fact that you can open several _full screen viewers_ on the same monitor could be problematic i think.

But the main function works as expected, sorry for the misunderstanding on my side ! :) 

Cheers !

**Comment by Simran-B** [comment]
Thanks for analyzing the situation you got into. There are definitely a few things to improve here. Multiple full screen viewers on the same screen is something the UI shouldn't allow for sure.
