### ISSUE TITLE
[PROJECT] No audio, can't delete footage

### ISSUE THREAD

**Issue by alemottaz** [olive-editor/olive#1308]
Hello,
I installed the OLIVE 0.2  in UBUNTU 20.10, the first problem I faced, it was not reading sounds i mean any type of sound, even the sounds included in video footage, so I tryed  to delete the all the fotage and here's the big surprise I can't delete them.
I think, that's all.
Best regards

**Commit Hash** 

**Platform** Ubuntu 20.10

**Summary** 

**Additional Information / Output**

**Comment by elsandosgrande** [comment]
@alemottaz Please, share all of the necessary information. #1301 is another example of somebody who did not supply the necessary information (look at Simran's comment and mine for further details).

**Comment by itsmattkc** [comment]
I get the impression you used `sudo apt install olive-editor` (or the Ubuntu Software Centre). For some reason, they have an old development build in there that we have no control over. Please only use the AppImages on https://olivevideoeditor.org/nightly.php

**Comment by elsandosgrande** [comment]
I was holding off on that remark until more information was supplied, but I get the same feeling as you Matthew.

**Comment by alemottaz** [comment]
Hi thanks for the respone, i'll check the Appimage, yes i installed the OLIVE using the Ubuntu Software Centre.
Thanks

**Comment by alemottaz** [comment]
Thanks The AppImage worked fine, GOOOD JOB
