### ISSUE TITLE
[UI] New logo

### ISSUE THREAD

**Issue by akhilesh-balaji** [olive-editor/olive#1310]
This isn't a bug report of anything; just a feature request.

**Commit Hash** 
Applies to all versions

**Platform** 
Windows 10

**Summary**
Currently, the olive logo doesn't look as great on my start menu because the logo doesn't match with Windows 10's new fluent design system. So, I would like to propose a new logo for olive. Please have a look at the presentation here (In the "Additional info section"), if you are interested.

**Additional Information / Output**
![1](https://user-images.githubusercontent.com/69246693/98333744-70032600-2027-11eb-8333-ffb9749afc68.jpg)
![2](https://user-images.githubusercontent.com/69246693/98333751-72fe1680-2027-11eb-9377-fa1828f6e08e.jpg)
![3](https://user-images.githubusercontent.com/69246693/98333752-7396ad00-2027-11eb-8041-de48f9b105a5.jpg)
![4](https://user-images.githubusercontent.com/69246693/98333753-742f4380-2027-11eb-862f-2d31b27c1593.jpg)
![5](https://user-images.githubusercontent.com/69246693/98333756-74c7da00-2027-11eb-80ad-8b61320c938c.jpg)
![6](https://user-images.githubusercontent.com/69246693/98333757-74c7da00-2027-11eb-8b83-1e396e1e02f6.jpg)
![7](https://user-images.githubusercontent.com/69246693/98333758-75607080-2027-11eb-9478-00c5426eb216.jpg)
![8](https://user-images.githubusercontent.com/69246693/98333759-75f90700-2027-11eb-8587-0dee84f753ce.jpg)
![9](https://user-images.githubusercontent.com/69246693/98333761-75f90700-2027-11eb-98a0-4f16b5f8707d.jpg)

**Comment by Simran-B** [comment]
Thanks for this experiment, but UI/brand design is currently out of scope: #1175 

Note that there was also a previous discussion #429 and even a poll on Patreon. But as I said, there are way more important things like making Olive 0.2 usable, so this will have to wait for a while.

**Comment by itsmattkc** [comment]
Yeah, we've been hearing about this for the better part of a year and a half, there have just been much higher priorites and it's also been hard to reach a consensus on a new logo. But it's more or less expected that there will be one for 0.2 (see #1246).

**Comment by mamarilmanson** [comment]
When that happens I +1 this... :D

**Comment by pafri** [comment]
The shown fruit looks like two green (unripe) mirabelles, or something. :-) I like the idea of twig of olive tree more. The olive branch is one of the symbols of peace - The branch of an olive tree is used as a symbol of peace and victory.

**Comment by akhilesh-balaji** [comment]
@pafri Interesting...
I wasn't aware of that.

**Comment by pafri** [comment]
This is a symbol, a tag used to distinguish a program from other projects on the menu (launchers, etc.). Aesthetic thing. The question might also be (unless explained somewhere), why is Olive called Olive? And what's the point of asking? I know the CherryTree program (hierarchical note taking application) and it has a cherry symbol. The leaves are visible in the icon. Does the author like cherries? Sure. The symbol resembles cherries in shape (it is easily recognizable), and not, for example, some red plum.

**Comment by itsmattkc** [comment]
I don't think we need this issue open to remind us. Like I said, we've been hearing this for over a year now.

**Comment by elsandosgrande** [comment]
> […] The question might also be (unless explained somewhere), why is Olive called Olive? […]

@pafri In case you were curious, Matthew explained that in the Discord server some time ago (#general-discussion, oldest pinned message):
![image](https://user-images.githubusercontent.com/40576902/98593832-0e1b1880-22d4-11eb-8177-23f54d5e3c50.png)
