### ISSUE TITLE
[PLAYBACK] No way of changing the playback quality

### ISSUE THREAD

**Issue by samytichadou** [olive-editor/olive#1311]
**Commit hash**
de48eba7

**Platform**
Windows 10 64 bits

**Summary**
When playing timeline, user doesn't seem to be able to select better quality for the video cache (and so the playback) than the default one

**Additional information**

Hi, i'm not sure if this report will help, it may be something i am missing, or a feature on the feature list that i didn't see, sorry if it is the case.
When playing back the timeline, i didn't find a way to bump up the quality of the video cache. For now, i'd say the generated cache is 1/4 quality (something like that), but when playing in full screen viewer, it would be great sometime to have it in 1/2, or 1/1, even if it is laggy. This can be useful to check a specific frame, cut...

Cheers, and thanks for your great work !

**Comment by Simran-B** [comment]
Can you check the Sequence Properties whether the Preview Resolution is set to Full?

![image](https://user-images.githubusercontent.com/7819991/98364377-fa03bc80-2030-11eb-9d0d-f2e9ca2f39c4.png)

**Comment by samytichadou** [comment]
Oh yep works perfectly thanks, i didn't thought of looking in the sequence properties ! 

I somehow find this location unintuitive, i get that it IS a sequence properties, but some button around the sequence viewer would be really useful to change this more quickly, or some button which brings you to the sequence properties. 

I know this is definitely not a high priority issue, just my thought on this as an editor :) 

Cheers !

**Comment by michaelharmonart** [comment]
I know this is closed, but I looked for a good 15 minutes before finding this and learning that this is in the sequence properties. Having a right click option in the preview window to change resolution would be great.

**Comment by Simran-B** [comment]
Everything will need to be cached again if you change it though. Not sure how useful it is to make it easier to change.
