### ISSUE TITLE
[UI] [UX] Improve visibility of audio tracks

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1316]
**Commit Hash** 
c69b63dc

**Platform** 
Any

**Summary**
I guess it's low priority but, it's hard to me to clearly differentiate audio tracks from video ones. Of course I know they are located below the video ones but, looking at the timeline, it's hard to visually know where the separator is.

1) A simple approach would be to color the tracks of different color for the audio ones but I think this is not possible because the nodal system.

2) Another approach would be to change the separator color:
<img width="1234" alt="audio_1" src="https://user-images.githubusercontent.com/5942369/98542803-c4a9d980-2291-11eb-82b5-03e99ebc73f3.png">

3) A final approach would be to change the audio timeline tracks background (my preferred one):
<img width="1234" alt="audio_2" src="https://user-images.githubusercontent.com/5942369/98542813-c96e8d80-2291-11eb-8c3f-04c23aa19ec7.png">

What do you think?

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Much, much bigger fish to fry. I also think by the time video clips display thumbnails, the difference will be clear.
