### ISSUE TITLE
The installation was successful but the Olive app did not open

### ISSUE THREAD

**Issue by bisigreat** [olive-editor/olive#1318]
**Commit Hash** 
c69b63d

**Platform** 
Windows 10

**Summary**

**Steps to Reproduce**

1. 
2. 
3. 

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**

**Comment by yasharya2901** [comment]
Please fill in the details such as what is the commit hash and the platform (OS) you are using.

**Comment by bisigreat** [comment]
I am using Windows 10 64-bit.

The version is Version: c69b63dc (Nov 9 2020 5:38:08)

**Comment by bisigreat** [comment]
I am using Windows 10 64-bit.

The version is Version: c69b63d (Nov 9 2020 5:38:08)

**Comment by itsmattkc** [comment]
The template isn't for looking at, you should fill it out.

Are you getting any error messages or crash reports?

**Comment by bisigreat** [comment]
I am getting error report



    On Tuesday, 10 November 2020, 03:27:32 pm GMT+1, itsmattkc <notifications@github.com> wrote:  
 
 


The template isn't for looking at, you should fill it out.

Are you getting any error messages or crash reports?

**Comment by Simran-B** [comment]
Still no useful information. Update your initial post with actionable information or we will have to close this issue.

BTW. replies via email do not support attachments, if that is what you tried.

**Comment by itsmattkc** [comment]
Closing until more information is provided.
