### ISSUE TITLE
unable to install olive installer 64 bit for windows 

### ISSUE THREAD

**Issue by Tamilsham** [olive-editor/olive#1319]
VCRUNTIME140_1.dll was not found error. even after trying unintall & install isn't working

**Comment by Tamilsham** [comment]
#Olive #OliveissueInstall

**Comment by Simran-B** [comment]
Do not remove the issue template and fill it out.

https://aka.ms/vs/16/release/vc_redist.x64.exe should solve it.

---

@itsmattkc The zip package seems to lack the DLL, whereas the installer contains vcredist_x64.exe and seems to run it:

https://github.com/olive-editor/olive/blob/9a46d4a57fc30d95f63d109ac8601fb6106846b4/app/packaging/windows/nsis/olive.nsi#L41-L44

As per the comment, it's VC 2010 - is that actually true?

Not entirely sure whether 140_1 refers to 14.0 (2015) or 14.1 (2017). The redist package I linked above is the 2015-2019 version, which seems to be different to individual redist packages that also seem to exist...

https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B
https://answers.microsoft.com/en-us/windows/forum/all/vcruntime1401dll-missing-where-to-get/268964c7-6910-4cdd-9a96-b03f4c1f6954

**Comment by itsmattkc** [comment]
There is an argument for forgoing any `vc_redist.x64.exe` and just including the necessary DLLs in the package. Simplifies the installer and also means the portable build should always work out of the box.

**Comment by Simran-B** [comment]
I agree, let's simply bundle the DLLs (just not the debug versions, because it's not allowed to distribute them).
I hope that it's always `VCRUNTIME140_1.dll` which it looks for, and not `VCRUNTIME140.dll` or similar on another system, but I guess this depends on how we compile/link it in the CI and it should then be the same on all target systems.

**Comment by itsmattkc** [comment]
Latest CI builds should fix this
