### ISSUE TITLE
[bug] major audio playback issues in long clips in macosx version

### ISSUE THREAD

**Issue by Ephemeralic** [olive-editor/olive#132]
in clips above 10 seconds (from what I have gathered, at least) audio gets really finnicky, half the time playing for a split second and then cutting out. sometimes it comes back but it is out of sync with the corresponding video

pretty sure this one is macosx exclusive

**Comment by itsmattkc** [comment]
Recent audio enhancements may have corrected this, will need to test properly.

**Comment by itsmattkc** [comment]
Testing has shown that this issue no longer affects Olive.
