### ISSUE TITLE
Audio: Subclips derived from cutting a larger clip seem to be linked

### ISSUE THREAD

**Issue by FoxWhiskey** [olive-editor/olive#1320]
**Commit Hash** c69b63dc 

**Platform** Mint 19.2 

**Summary**
When cutting a -in my case- large audio file into 2 or more *subclips*, these subclips seem to share properties - at least they are somehow related.

**Details**
I cut two songs from a podcast (one file, two different time positions within the same file) and pasted them on two audio tracks, intending to mix them by overlapping the end of subclip1/the beginning of subclip2.
When selecting subclip1 on the timeline and applying a fade out with two key frames ( 0 dB --> -200dB), the fade out operation is applied on subclip2 (!).
Moreover, when adding volume key frames, they are not shown on the time line view of the parameter editor! However, when moving the time marker over the (invisible) key frame, the "add key frame" button is inverted. 

Time marker on the key frame:
![grafik](https://user-images.githubusercontent.com/74262352/98727686-9c58d280-2398-11eb-8ef5-8128d19bb919.png)

Time marker not on the key frame:
![grafik](https://user-images.githubusercontent.com/74262352/98727914-ff4a6980-2398-11eb-8e00-e66870a16ea3.png)

**Additional Information / Output**
I run the Appimage on a AMD Phenom II X4 955. When moving the audio tracks back and forth in time or creating key frames, all 4 cores go up to 100% load for quite some time... 
This is my first issue on Github, please let me know if I (unintentionally) violated any *contributing guidelines*...

**Comment by itsmattkc** [comment]
Known issue, splitting a clip currently just makes a new clip and connects it to the same node. This will eventually be a user preference thing, since depending on the circumstance, it may be desirable to share the nodes between multiple clips or it may not, and in many it may not, such as your situation.

**Comment by FoxWhiskey** [comment]
OK, what about the missing key frame display? Related, or new issue?

**Comment by itsmattkc** [comment]
Sounds like a separate issue to me.
