### ISSUE TITLE
[NODES] Connecting Time input to the position of an Orthographic Matrix puts the position eternally at (0; 0) 

### ISSUE THREAD

**Issue by Astavie** [olive-editor/olive#1321]
**Commit Hash**
c69b63dc

**Platform** 
elementary OS 5.1.7 Hera

**Summary**
When connecting the Time node to the position of the orthographic matrix, nothing happens. It doesn't move a single pixel even when waiting 100 seconds.

I assume this is because position is a 2d input and time just 1d, however I cannot seem to figure out how to single out a coordinate from the position and attach that to the time input.

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/7745457/98821213-89451180-242f-11eb-83af-afae16ee25cc.png)

**Comment by itsmattkc** [comment]
Known issue. Olive doesn't currently have a way of converting a float type to a vec2.

**Comment by itsmattkc** [comment]
Merging into #1357
