### ISSUE TITLE
[CRASH] Exporting video created from image seqence with alpha channel

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#1322]
**Commit Hash**  c69b63dc

**Platform** 
Windows 10

**Summary** I imported large number of animation frames (1 121 bmp images with transparent areas and size (1586x5495)) and tryed to export them with default settings after changing the hight to 5496 (and CRF set to 23  which should not matter as I encountered the crash with CRF of 10).

**Steps to Reproduce**

1. Import bmp files with transparency with size of (1586x5495) as seqence. Other sizes might work too.
2. add them to timeline (seqence parameters decided by olive)
3. export the timeline (default settings)

Exception:
`Exception caught at 0x00007FFEA05FB9B0 (OpenImageIO.dll) in olive-editor.exe: 0xC0000005: Access Violation: read 0x0000021C02104000` (I translated it from my language so it might not be correct name of the error)

<details><summary><strong>Crash report</strong></summary><pre><code>
OpenImageIO.dll!00007ffea05fb9b0()	Unknown
 	OpenImageIO.dll!00007ffea068d7a2()	Unknown
 	olive-editor.exe!olive::OIIODecoder::FrameToBuffer(std::shared_ptr<olive::Frame> frame, OpenImageIO_v2_3::ImageBuf * buf) Line 206	C++
 	olive-editor.exe!olive::PixelFormat::ConvertPixelFormat(std::shared_ptr<olive::Frame> frame, const olive::PixelFormat::Format & dest_format) Line 282	C++
 	olive-editor.exe!olive::OpenGLProxy::FrameToValue(std::shared_ptr<olive::Frame> frame, std::shared_ptr<olive::Stream> stream, const olive::VideoParams & params, const olive::RenderMode::Mode & mode) Line 119	C++
 	olive-editor.exe!olive::OpenGLProxy::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 111	C++
 	Qt5Core.dll!00007ffe9eb2ca51()	Unknown
 	Qt5Widgets.dll!00007ffe9f5e56f0()	Unknown
 	Qt5Widgets.dll!00007ffe9f5e4768()	Unknown
 	Qt5Core.dll!00007ffe9eb051ca()	Unknown
 	Qt5Core.dll!00007ffe9eb06f75()	Unknown
 	Qt5Core.dll!00007ffe9eb4f887()	Unknown
 	Qt5Core.dll!00007ffe9eb0130c()	Unknown
 	Qt5Core.dll!00007ffe9e9551af()	Unknown
 	Qt5Core.dll!00007ffe9e956e93()	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
</code></pre></details>

**Additional Information**

Registers:

    | Name |   Value   | Type
-- |   --  |       --        | --
    | EAX | 00000000 |  
   | RAX | 0000000000000000 |  
   | RDX | FFFFFFFFFA522DE0 |  
   | RDI | 0000021BFC626DE0 |  
   | R8 | 0000021C02104000 |

**Comment by mcDandy** [comment]
In formatting code of the issue is report from the utility which watches olive for crashes. I am not able to show it in the collapsable thing and do not want to add it as text becouse it is very long.

**Comment by itsmattkc** [comment]
Known issue. 0.2 doesn't yet implement any export codec except for H.264.

**Comment by mcDandy** [comment]
Am I missing something? I see options H.264 and H.265 in the export settings and I was exporting to H.264.
I thought it exports from internal format to selected format.

**Comment by itsmattkc** [comment]
Sorry I misunderstood, I thought you were trying to export an image sequence.

Does the latest commit fix this?

**Comment by itsmattkc** [comment]
I will assume this is fixed in the latest commit unless otherwise specified.
