### ISSUE TITLE
[AUDIO] Unexpected behaviour when adding volume key frames to subclips 

### ISSUE THREAD

**Issue by FoxWhiskey** [olive-editor/olive#1323]
**Commit Hash** c69b63d 

**Platform** Mint 19.2 

**Summary**
The actual position of a volume key frame when clicking the Add button in the Parameter Window, depends on the overlap time of two subclips. If the overlap time is negative (i.e. the clips do not overlap), a key frame is created but not displayed on the time line display. The latter effect has already been reported in #1320 

**Additional Information / Output**

Superposition of two subclips, overlap time is 30"
![grafik](https://user-images.githubusercontent.com/74262352/98869377-f8dbf080-2471-11eb-9c2e-516b87c1d801.png)

Position of actual volume key frame, when adding it at time position 0"
![grafik](https://user-images.githubusercontent.com/74262352/98869822-a949f480-2472-11eb-8b37-3029638f1564.png)

**Comment by itsmattkc** [comment]
Is this reproducible in the latest commit?

**Comment by FoxWhiskey** [comment]
Let me check, I will report back ASAP (likely tonight)

**Comment by FoxWhiskey** [comment]
> Let me check, I will report back ASAP (likely tonight)

Ok, just  downloaded & ran 2851164c. It _seems_ as if the issue no longer occurs (congrats!!) - however, I wasn't able to complete my tests, as the build keeps crashing unexpectedly while setting audio levels on clips.
Let me know if you want me to open a separate issue!

**Comment by Simran-B** [comment]
Yes, please create a new issue for that. Thanks!
