### ISSUE TITLE
[EXPORT] Not even in a alpha stage

### ISSUE THREAD

**Issue by thefishydripz** [olive-editor/olive#1327]
**Commit Hash** 

**Platform** 
Windows 10

**Summary**
Crashes half of the time and has 100% of the time stopped at 14% for an absurd amount of time

**Additional Information / Output**

**Comment by elsandosgrande** [comment]
@thefishydripz 
1. Olive is sometimes said to be in alpha, sometimes pre-alpha. Razor (0.2) is practically a complete rewrite, so this is a given.
2. Could you please share the commit hash and as many details about your project and timeline as possible?

**Comment by Simran-B** [comment]
https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha

> Alpha software may contain serious errors, and any resulting instability could cause crashes or data loss. Alpha software may not contain all of the features that are planned for the final version

Consider the export feature as incomplete.
