### ISSUE TITLE
[RENDER] Render is far too slow to catch up after using ripple delete tool

### ISSUE THREAD

**Issue by caseyleenb** [olive-editor/olive#1328]
**Commit Hash** 

**Platform** Windows 10

**Summary**
While doing a longer edit requiring me to use ripple delete about every two seconds, i found that the programme and the renderer can't seem to keep up after being used. i use it to cut out a bit of footage, and it takes as much as a minute for it to properly sync and the program to not be locked up thinking about what it needs to do. playback is also impacted, as it takes time for it to catch up.

**Additional Information / Output**
"playback queue failed to keep up" in the shell

**Comment by caseyleenb** [comment]
this might not have been the right tag to use, but i wasn't sure what else to use.

**Comment by itsmattkc** [comment]
This should be fixed with the recent merge of `nodearchchanges`. Reply back if this still occurs in the latest commit.
