### ISSUE TITLE
[CI] Move linuxdeployqt into bin folder

### ISSUE THREAD

**Issue by Simran-B** [olive-editor/olive#1336]
`/usr/local/bin`, `usr/bin` and `/bin` are all in PATH in the `ci-olive` Docker image.
If `linuxdeployqt-x86_64.AppImage` is moved to either, calls can be shortened from `/usr/local/linuxdeployqt-x86_64.AppImage` to `linuxdeployqt-x86_64.AppImage`.

- [ ] Update Dockerfile
- [ ] Push updated image to Docker Hub
- [ ] Update ci.yml
- [ ] Update www/compile.php

**Comment by itsmattkc** [comment]
By now I assume this issue is either resolved or not crucial enough to keep around. Closing.
