### ISSUE TITLE
[TODO] Finish implementing export formats that aren't H.264

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1345]
_Originally opened as https://github.com/sobotka/olive/issues/76_

**General TODO Summary**
Ensure the output codecs that we do support actually work properly.

**Additional Information / Notes**
The export dialog offers codecs such as H.265, ProRes, DNxHD, image sequences, etc. however only H.264 has actually been tested. The rest of the codecs have extremely varying degrees of usefulness and should at some point be tested to output as expected.

**Comment by itsmattkc** [comment]
<a href="https://github.com/sobotka"><img src="https://avatars1.githubusercontent.com/u/59577?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sobotka](https://github.com/sobotka)**
_Saturday May 02, 2020 at 15:15 GMT_

----

Only note here is to handle each codec on a case by case basis to properly and robustly support them, within the design constraints of an NLE.

General Do:
* Do “generally” support encoding characteristics. For example, ProRes offers the standardized and general categories of output. Support those.
* Do keep the encoder to useful, but perhaps not “industrial”. This is a fuzzy line of qualia of course, but *O*live *I*s *N*ot *A*n *E*ncoder. As such, trying to keep a “sane” hand on encoding quality, while at the same time acknowledging that Olive can export native, raw frames, of the highest possible quality, provides the audience with a means to take Olive footage elsewhere for encoding.
* Do support limited codecs, and support them sanely and well. The more codecs that are supported, the more tech overhead and nightmare unfolds.

General Don’ts:
* Don’t support general things across all codecs and then arbitrarily not have feedback in the UI where they are or are not exposed due to the nature of the codec. Plenty of software does this, and it is nightmare.
* Don’t try to support more codecs than the most baseline offerings suitable for editing. Robust support of DNxHD, ProRes, H264, H265, and still image EXR, DPX, TIFF cover a majority of bases. Some require additional colourimetry handling etc. As such, handling fewer robustly versus many half-assedly.

A decent example of “robust” handling is Fusion’s handling of DPX. It is a nuanced still image encoding format, but it shows the complexity of handling it with the details required.

**Comment by itsmattkc** [comment]
<a href="https://github.com/itsmattkc"><img src="https://avatars1.githubusercontent.com/u/34096995?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [itsmattkc](https://github.com/itsmattkc)**
_Saturday May 09, 2020 at 07:01 GMT_

----

Completely agreed, I think we should try to keep our supported export formats to a minimum so we can best ensure each is handled properly. As you say, as long as Olive can export raw frames, other, more tailor-made encoding tools can be used for compression.

**Comment by philiplb** [comment]
As this got mentioned in #1467, it might be worth noting down the audio codecs as well. Maybe something along the lines of Wav, MP3, AAC and FLAC?
With the possibility to export audio only as it seems a reasonable workflow to export the edited audio, work on it in Audacity or Ardour and re-import it into Olive again or add the result as audiostream to the exported file of Olive.

**Comment by itsmattkc** [comment]
Yes, I think WAV, AIFF, MP3, AAC, FLAC, and Ogg should cover all our bases.

**Comment by philiplb** [comment]
Ou, yeah, Ogg of course! :)

**Comment by Simran-B** [comment]
The formats you mentioned could be the officially supported ones, but we could allow other formats supported by FFmpeg as well at your own risk, Same for video formats. Just need to find a good UI solution to communicate that you leave the official territory.

**Comment by ThomasWilshaw** [comment]
I think as per Troy's initial post, that wouldn't be a good idea, it'll lead to a wormhole of messy settings. Users can always export exr/proceed and use ffmpeg externally to convert to whatever random codec they want.

**Comment by Luni-4** [comment]
It would also be good exporting `FFV1` as lossless format, since it is supported by `FFmpeg` and `olive` can currently open it. Thanks in advance for consideration!

**Comment by PeterBindels-TomTom** [comment]
> Ogg

Ogg is a container format (like AVI), not a codec. I think this might have meant Vorbis, or Opus?

**Comment by itsmattkc** [comment]
Keeping this open is unnecessary, the remaining codecs will be implemented over time.
