### ISSUE TITLE
[ANIM] Copy/paste keyframes

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1349]
_Originally opened as https://github.com/sobotka/olive/issues/86_

**General TODO Summary**
Keyframes currently aren't able to be copied or pasted which is obviously not desirable from a user perspective.

**Additional Information / Notes**
We can probably use the same strategy that nodes use to copy (serializing to text by re-using their project save code) making this relatively simple to implement.

**Comment by Simran-B** [comment]
Seems to be related to #1346

**Comment by itsmattkc** [comment]
Implemented in 182e1599af0a074e6ed7cc07d456a05841e90734
