### ISSUE TITLE
[UI] Add Reset to Defaults button in Preferences

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1363]
<a href="https://github.com/ThomasWilshaw"><img src="https://avatars0.githubusercontent.com/u/7781683?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ThomasWilshaw](https://github.com/ThomasWilshaw)**
_Thursday May 07, 2020 at 20:51 GMT_
_Originally opened as https://github.com/sobotka/olive/issues/116_

----

**General TODO Summary**
Add a reset to defaults button in the preferences dialog.

**Additional Information / Notes**
Should this be per page of for the whole dialoge?

**Comment by pgilfernandez** [comment]
IHMO it should go here, apply for whole Preferences with a popup advising about that it will apply to whole Preferences:

<img width="761" alt="reset" src="https://user-images.githubusercontent.com/5942369/100064493-e29b4080-2e32-11eb-94e8-9aa2645adf7e.png">

**Comment by ThomasWilshaw** [comment]
See the PR, that's exactly what it does :)
