### ISSUE TITLE
[CODEC] Occasionally, the first frame of an image sequence is wrong

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1376]
**Commit Hash** 
640b157

**Platform** 
All

**Summary**
Unpredictably, a condition can occur where the first frame of an image sequence is cached incorrectly.

**Additional Information / Output**
I feel like it has to be either the filename resolution in `OIIODecoder` or a race condition in `StillImageCache`.

**Comment by pgilfernandez** [comment]
It also happens to me occasionally. The workaround is to save your project, close and open Olive.

**Comment by itsmattkc** [comment]
@pgilfernandez Does it only happen with image sequences for you too?

**Comment by pgilfernandez** [comment]
That's right. It happens with a png image sequence.
