### ISSUE TITLE
[PLAYBACK] Preview doesn't scale properly on Retina displays

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1377]
**Commit Hash** 
afbd3ada

**Platform** 
macOS 10.14.6

**Summary**
Footage and Sequence viewers are shrink to a quarter... it worked with `2d2d6d2a` but then is started to behave as described.
<img width="1128" alt="screenshot" src="https://user-images.githubusercontent.com/5942369/99530924-468cb780-29a2-11eb-94e8-1d3e61aa6e57.png">

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Looks like you have a retina display, that's probably messing with the renderer viewport

**Comment by pgilfernandez** [comment]
You are right, it's a Retina display. But Olive worked fine till some commits ago, even v0.1 worked and works fine...

**Comment by itsmattkc** [comment]
Yes, I understand. Olive's render code was completely rewritten a few days ago, so some bugs like this are expected. I was merely remarking on the likely cause.
