### ISSUE TITLE
[UI] Olive shows a black screen after running the cmd prompt

### ISSUE THREAD

**Issue by ZodTheTod** [olive-editor/olive#1388]
**Commit Hash** 

**Platform** <!-- Windows 10>

**Summary** When I opened Oliver 0.2, it executed some commands in cmd then opened Oliver but all I could see was a black screen

**Additional Information / Output**

**Comment by sobotka** [comment]
Follow the template.

**Comment by Simran-B** [comment]
Possible duplicate of #1385
