### ISSUE TITLE
VST/AU support for audio effects

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#14]

**Comment by itsmattkc** [comment]
not in v1.0 but hopefully shortly after

**Comment by itsmattkc** [comment]
seems to contain helpful information for this purpose: http://teragonaudio.com/article/How-to-make-your-own-VST-host.html

**Comment by prokoudine** [comment]
Does the VST branch support VST2, VST3, or both?

**Comment by itsmattkc** [comment]
I've just finished support for VST2.4 on Windows (still working on the frontend). More coming soon :)

**Comment by prokoudine** [comment]
How do you feel about using VeSTige headers for a fully GPL experience on all platforms? :)

**Comment by prokoudine** [comment]
You can take the one from https://github.com/Ardour/ardour/tree/master/libs/ardour/ardour/vestige

**Comment by prokoudine** [comment]
OTOH, rgareus from Ardour tells me: "if he starts from scratch, perhaps using VST3 is the correct way -- that also includes VST2 support -- https://github.com/steinbergmedia/vst3sdk/"

**Comment by itsmattkc** [comment]
I'll take a proper look tomorrow, but if it's a more or less drop-in replacement for the Steinberg headers, I'm all for it.

**Comment by prokoudine** [comment]
@itsmattkc Well, it's GPLv2+, so you are free to add the opcodes, especially since your changes are public :)

**Comment by itsmattkc** [comment]
VST support implemented for Mac and Linux (in addition to existing Windows support) in 637c2414ed45b7c70a77a8a627e3a0f3042b55ba. Also uses included VeSTige header.
