### ISSUE TITLE
[UI] Audio monitor failing to render

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#1401]
**Commit Hash** 3cf4d58

**Platform**  Windows 10 20H2

**Summary**
Sound meter is completly black and does not react to sound

**Additional Information / Output**
![2020-11-22 (5)](https://user-images.githubusercontent.com/18588943/99917534-3150b980-2d11-11eb-9080-444084b37395.png)

**Comment by Simran-B** [comment]
Can you check the console window of Olive for errors and warnings and post them here?

**Comment by mcDandy** [comment]
only warnings, but they does not correspond to this issue.
[WARNING] Playback queue failed to keep up ((null):0)
[WARNING] Tried to finish a ticket that hadn't started ((null):0)

**Comment by itsmattkc** [comment]
Can you try with the latest commit? (ade4369199e95fa5177b7ac7e982762f2dee806a)

**Comment by mcDandy** [comment]
Fixed in ade4369
