### ISSUE TITLE
[NODES] Transition alpha is incorrect 

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1404]
**Commit Hash** 
2c4f781e

**Platform** 
macOS 10.14.6

**Summary**
Video track blending doesn't work.
In the following example, in the cross dissolve transition the text would be expected to blend with lower video track that has a red solid element:

![error](https://user-images.githubusercontent.com/5942369/99947834-d783da00-2d78-11eb-98d3-c4ca76687382.gif)

**Additional Information / Output**

**Comment by AngeloFrancabandiera** [comment]
Is your transition a "dip to color" or a "cross dissolve"?

**Comment by ThomasWilshaw** [comment]
It looks like transitions are messing up the alpha channel in some way.

**Comment by pgilfernandez** [comment]
> Is your transition a "dip to color" or a "cross dissolve"?

It's cross dissolve

**Comment by sobotka** [comment]
If it’s alpha encoded, it should be a merge.

**Comment by ThomasWilshaw** [comment]
I think it should just generate an image with an alpha channel that gets sent into merge later but the alpha is lost somehow

**Comment by sobotka** [comment]
Crosses aren’t akin to alphas; they end up being an add / multiply usually. It’s perfectly fine to have a cross respect an alpha, but I don’t believe the node does yet?

**Comment by ThomasWilshaw** [comment]
I think I see the problem, ` job.SetAlphaChannelRequired(true);` isn't set any where in `transittion.cpp`. Working on a fix now.
