### ISSUE TITLE
[CRASH] Removing a part of a footage crashes the program.

### ISSUE THREAD

**Issue by miromarszal** [olive-editor/olive#1405]
**Commit Hash** 2c4f781e 

**Platform** Windows 10 

**Summary**
I'm trying to use Olive to do simple cut and crop edits on a video. Removing a part of a footage that has been cut with the razor tool most of the times results in an immediate crash. This does not happen every time though.

**Steps to Reproduce**

1. Cut a footage on the timeline with the razor tool.
2. Remove one of the parts.

<details><summary><strong>Backtrace</strong></summary><pre><code>

Thread 10 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 11156.0x3198]
0x00007ff8708b11e6 in Qt5Core!??0QString@@QEAA@AEBV0@@Z () from c:\Program Files\Olive\Qt5Core.dll
(gdb) bt
#0  0x00007ff8708b11e6 in Qt5Core!??0QString@@QEAA@AEBV0@@Z () from c:\Program Files\Olive\Qt5Core.dll
#1  0x00007ff771b5bf86 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

</code></pre></details>

**Additional Information**
Crash report attached. 
[crash_report.txt](https://github.com/olive-editor/olive/files/5582734/crash_report.txt)

**Comment by itsmattkc** [comment]
I can't seem to recreate this. Could you provide more specific steps to reproduce (maybe a screen recording)?

**Comment by miromarszal** [comment]
Sorry for a delayed response. I was not able to reproduce this with any other file, so I guess that one was somehow corrupted. Unfortunately, I can't really share that file with you.

**Comment by Simran-B** [comment]
Thanks. Closing the issue as there is nothing actionable without a way to reproduce the problem.
