### ISSUE TITLE
[PLAYBACK] Footage viewer window not updated when playing back audio

### ISSUE THREAD

**Issue by FoxWhiskey** [olive-editor/olive#1406]
**Commit Hash** 7e6dc55d and earlier

**Platform** Mint 19.2

**Summary**
On audio playback in the footage viewer, the time marker disappears at the right frame border, without waveform or time axis being updated

**Expected behaviour**
When the time marker hits the right frame border, the window is updated in a way that the user is able to keep track of the audio data. Two methods are proposed:
1) Keep the time marker at the right end, while scrolling the waveform data to the left
2) Update the waveform data by the time span displayed in the window, place the time marker at the left end and scroll the marker to the right.

**Comment by itsmattkc** [comment]
Could you elaborate? What are you expecting to happen vs what is happening?

**Comment by FoxWhiskey** [comment]
Sorry. I have updated the issue. Hope it's clear now. I think 0.1 worked in the proposed way... Will have to check, though.

**Comment by itsmattkc** [comment]
Oh, do you mean the footage viewer's scroll doesn't keep up with the playhead?

**Comment by FoxWhiskey** [comment]
Bingo. You nailed it down without tons of words ;-)
