### ISSUE TITLE
[CRASH] Crashed while using transition tool 

### ISSUE THREAD

**Issue by CHJ85** [olive-editor/olive#1411]
**Commit Hash** 

**Platform** 
Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 5.8.0-29-generic
System: Ubuntu 20.10 (ubuntu 20.10)

**Summary**

**Steps to Reproduce**

1. 
2. 
3. 

<details><summary><strong>Backtrace</strong></summary><pre><code>
/usr/bin/olive-editor(_ZN5olive13crash_handlerEi+0x107)[0x55fcf92297f7]
/lib/x86_64-linux-gnu/libc.so.6(+0x41950)[0x7f429aa95950]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN7QObject9setParentEPS_+0x4)[0x7f429b2687c4]
/usr/bin/olive-editor(_ZN5olive14NodeAddCommandC2EPNS_9NodeGraphEPNS_4NodeEP12QUndoCommand+0x4f)[0x55fcf92f10ef]
/usr/bin/olive-editor(_ZN5olive14TimelineWidget14TransitionTool12MouseReleaseEPNS_22TimelineViewMouseEventE+0x140)[0x55fcf9319de0]
/usr/bin/olive-editor(_ZN5olive14TimelineWidget17ViewMouseReleasedEPNS_22TimelineViewMouseEventE+0x55)[0x55fcf9326955]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2e12e6)[0x7f429b26a2e6]
/usr/bin/olive-editor(_ZN5olive12TimelineView13MouseReleasedEPNS_22TimelineViewMouseEventE+0x46)[0x55fcf91dd786]
/usr/bin/olive-editor(_ZN5olive12TimelineView17mouseReleaseEventEP11QMouseEvent+0xbc)[0x55fcf9321e0c]
/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x1ce)[0x7f429bd2d30e]
Version: 
Signal: 11
</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
We appreciate providing the backtrace, but can you fill out the rest of the template?
