### ISSUE TITLE
[UI] Custom keyboard shortcuts are not saved

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1412]
**Commit Hash** 
b4b0cd6b

**Platform** 
macOS 10.14.6

**Summary**
Only a few Preferences are saved to file, I don't know if this is known or if it's just me...

**Additional Information / Output**
 Preferences settings are reset to default when you close and reopen Olive.

**Comment by itsmattkc** [comment]
Which settings? All settings that actually do something are saved, many of the settings under "behavior" are non-functional at the moment.

**Comment by pgilfernandez** [comment]
For example the keyboard settings, they are not saved at all here in my computer.

If you would like a more in deep test I'll be able to do it later today.

**Comment by pgilfernandez** [comment]
I had time to check it out and the "only" section that is not saved is the "Keyboard" one.
It works in the open session but if I close Olive and reopen it the keyboard shortcuts are again the default ones.

**Comment by itsmattkc** [comment]
Indeed it appears keyboard shortcuts have no save code. It was only recently that preference saving code was introduced, so I guess shortcuts got overlooked.

**Comment by pgilfernandez** [comment]
Another thing that is not saved (and was in v0.1) is the panels layout... it seems like it's saved as a project configuration but, is it somehow possible to set a default panels layout?

**Comment by Simran-B** [comment]
I think it's valid to have both, per project layouts as well as global layouts. How to handle that in a meaningful way in the UI is tricky though. Perhaps a nested menu like this?
- Global
  - Default
  - Custom 1
  - Custom 2
- Project
  - Default (copy of Global > Default with modifications)
  - Custom 3
