### ISSUE TITLE
[NODES] Transform node "gizmo" not dragable

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1413]
**Commit Hash** 
b4b0cd6b

**Platform** 
macOS 10.14.6

**Summary**
I'm able to rotate the Transform Node "gizmo" to affect the "rotation" but when I press in the gizmo center expecting to move it around it disappears. It seems to affect "scale" instead... the following video is self explanatory:

![nodes_transform](https://user-images.githubusercontent.com/5942369/100117096-c15b4400-2e74-11eb-8fe8-c9d97f62f236.gif)

**Additional Information / Output**

**Comment by itsmattkc** [comment]
This might be another retina display thing. I don't get this issue.
