### ISSUE TITLE
[NODES] Polygon node doesn't work

### ISSUE THREAD

**Issue by UltraSavageTM** [olive-editor/olive#1415]
**Commit Hash** 210417a5

**Platform** Windows 10  version 2004 (341)

**Summary** When using polygon node, it doesn't show on the sequence viewer

**Additional Information / Output** Was working from the version several days ago

**Comment by itsmattkc** [comment]
Known. Polygon node has always been incomplete and hasn't been updated to work with the new render system. I recommend following progress of it in #1339

**Comment by Simran-B** [comment]
Also see #1285 and #1293
