### ISSUE TITLE
[EXPORT] Memory leak when exporting on some newer versions of Linux

### ISSUE THREAD

**Issue by mikesbytes** [olive-editor/olive#1418]
**Commit Hash** 

210417a5

**Platform** 

Arch Linux

**Summary**

When exporting, olive consumes all of my 32gb of ram over the course of a couple minutes. If I cancel before I get OOM lockups, the memory stays used until exiting olive. Expected behavior would be for it to not use up all my memory.

**Additional Information / Output**

N/A

**Comment by itsmattkc** [comment]
What footage are you using?

**Comment by mikesbytes** [comment]
I am using a video I recorded with OBS. I replaced the video clip with just a solid and I get entirely different issue where the export progress never goes up and the estimated time remaining explodes while maxing out a single core. The recording is a 1080p h264 MKV file recorded with the OBS "indistinguishable" quality setting. Preview seems to work just fine however.

**Comment by itsmattkc** [comment]
The solid issue is probably related to #1408 (appears to be a Windows exclusive issue).

How long is the video you're trying to export?

**Comment by mikesbytes** [comment]
The video is about 6 mins 11 seconds. I do have another solid in the project that is only 3 seconds long that doesn't *seem* to cause any issues. I attached a zip of the project and associated files, not sure how olive handles paths changing though.

[olive-bugtest-proj.zip](https://github.com/olive-editor/olive/files/5599279/olive-bugtest-proj.zip)

**Comment by mrshroomy** [comment]
I get the same problem, I'm on manjaro linux (Unstable branch, arch linux package versions basically). The export uses my whole 16GB of ram and cause OOM for the OS if the video im rendering is longer than 1 minute.

**Comment by mikesbytes** [comment]
Some more findings:

It works correctly when exporting on my laptop running ubuntu 18.04 with linux 5.0.0

It does not work correctly when exporting on my desktop running arch with either the current 5.9.10 kernel or the 5.4 lts kernel.

I attempted to make another test project using some arri footage as recommended on the discord, and encountered the same problem. I also tried to pre-cache the arri test footage and it consumed over 48GB of memory before I killed it to avoid OOM lockup.

I was however successfully pre-cache the clip in the example project I posted earlier, but it still leaks like a sieve when I run the export.

I tried to profile the memory usage with perf but unfortunately it seems that memory events are not supported on my CPU and kernel (Ryzen 1700, linux 5.9)

**Comment by mikesbytes** [comment]
Okay so I did some more digging. I used valgrind to generate suppressions by running olive and doing everything except hitting the export button, then did another run with those supressions where I hit render, which drastically reduced the amount of junk in the log. I skimmed through it a bit and it looks like there's a lot of leaks coming through RenderManager::RenderFrame and RenderManager::RenderAudio.

I have attached the log to this comment.

[olivevg.log](https://github.com/olive-editor/olive/files/5609678/olivevg.log)

**Comment by itsmattkc** [comment]
Would be curious to know if ee2deb13657d367467b514e0149a2e09f22e230e makes a difference, this is testing the theory that blocking the main thread may be related.

**Comment by mikesbytes** [comment]
It does not seem to make a difference unfortunately.

**Comment by unfa** [comment]
I'm using `1cd07bc1` AppImage and processing a 30-second  4K 60 FPS V-log / V-gamut file (from a Panasonic GH5) eats 32 GB of RAM, 34 GB of swap, and 20 minutes. It produces a correct file and the memory usage goes back to normal after it's done, but during rendering the machine is completely unusable and still there's a high chance of freezing the OS completely.

**Comment by fmpwizard** [comment]
You can rename the ticket, I run into this under Fedora 33, so it is not only Arch

I'm using `Olive-19eabf28-Linux-x86_64.AppImage` (downloaded on 2021/1/1)
Video file is mp4 2.5k, 4 minutes long (recorded with a drone camera)
During export, olive's memory usage goes to 31GB and then it runs out of memory (laptop RAM is 32G)
I can upload the file here if you need a test file, it's `360MB`

**Comment by fmpwizard** [comment]
Here is the link to a sample video that will trigger the memory leak on Fedora 33 https://drive.protonmail.com/urls/QYFFB1PNRW#uagF2B90xLXK 363MB

**Comment by Mennaruuk** [comment]
> Here is the link to a sample video that will trigger the memory leak on Fedora 33 https://drive.protonmail.com/urls/QYFFB1PNRW#uagF2B90xLXK 363MB

On the latest commit (62332eb2), it did crash, but only once, and that was the first time. Following that, it didn't crash on me. and I was even able to duplicate the video and put it on several tracks while being able to save the project and reopen it without crashing.

[Here's another large sample file to try out ](https://mega.nz/file/vNhylJpL#vI_Bmobg0CSgKosKi0XXNF0pPtNINtdsoWzJenw3HJQ)(it's a black screen video). For me, Olive didn't crash at all importing this file, despite its size and duration.

**Comment by JoseOlin** [comment]
I'm having this same problem, except that in the end it doesn't release the memory and I have to close Olive for it to do so.

Linux Mint 20.2
Olive: 76831a2b (AppImage) running with gdb
8GB RAM
intel i3
