### ISSUE TITLE
[CACHE] Memory arenas stuck in a loop

### ISSUE THREAD

**Issue by ThomasWilshaw** [olive-editor/olive#1419]
**Commit Hash** 
f8a5e28c

**Platform** 
Windows 10 Nightly build

**Summary**
On Windows 10 at least Olive refuses to cache, the cache line stays red and playback is quite jerky. It seem like Olive gets stuck in a loop of filling and then emptying arenas. Every time I move the cursor I get the following ouptut in the console repeated many times:

```
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
```
It must have repeated about 30 times from one cursor move.
**Additional Information / Output**
The cache files are being written to the cache but Olive doesn't seem to be picking them up

**Comment by itsmattkc** [comment]
I've seen this issue but I can't recreate it reliably. For me it seems like 90% of the time it caches fine, and maybe I'll see this behavior 10% of the time, which has made it hard to track down. I'll test it on Windows to see if it's more common there.

**Comment by mcDandy** [comment]
I was going to make bug report on the exact same thing. (never chaces and I discovered while ago, that it is recreating areas). Using f8a5e28c

**Comment by itsmattkc** [comment]
This issue should be solved from the recent merge of `nodearchchanges`.
