### ISSUE TITLE
[TRANSLATION] [UI] Missing plural forms support

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#1421]
Here are all the instances (that I found) of translatable text that needs plural forms support:

./app/project/item/footage/audiostream.cpp: return QCoreApplication::translate("Stream", "%1: Audio - %2 Channels, %3Hz").arg(QString::number(index()),
./app/widget/nodeparamview/nodeparamviewarraywidget.cpp: count_lbl_->setText(tr("%1 elements").arg(array_->GetSize()));
./app/dialog/preferences/tabs/preferencesdisktab.cpp:  cache_ahead_slider_->SetFormat(tr("%1 seconds"));
./app/dialog/preferences/tabs/preferencesdisktab.cpp:  cache_behind_slider_->SetFormat(tr("%1 seconds"));
./app/dialog/preferences/tabs/preferencesgeneraltab.cpp:  default_still_length_->SetFormat(tr("%1 seconds"));
./app/task/project/import/import.cpp:  SetTitle(tr("Importing %1 files").arg(file_count_));

**Comment by prokoudine** [comment]
I'm afraid it doesn't fix the issue.

Here is how it's supposed to look: 

![image](https://user-images.githubusercontent.com/57467/100437683-2b146180-30b2-11eb-989e-f900fbf86e7d.png)

Note singular, dual, and plural forms.

Here is how it looks for Olive:

![image](https://user-images.githubusercontent.com/57467/100437800-5a2ad300-30b2-11eb-9e1f-84c1b60c4653.png)

**Comment by prokoudine** [comment]
I can easily fix it for the case in the screenshot above:

![image](https://user-images.githubusercontent.com/57467/100438289-fead1500-30b2-11eb-9ad5-bb295f1cc46d.png)

But I'm really not sure about others because e.g. for the count of seconds in Prefs there doesn't seem to be a variable to use.

**Comment by itsmattkc** [comment]
I see, it looks like I'm supposed to add extra parameters to the `tr()`. I thought it just required the "(s)".

**Comment by Simran-B** [comment]
`%1`, `%2` etc. are placeholders for `QString::arg()`, which does not do any handling of plurals.

For plural handling, one has to use `%n`. There can only be one per string. The actual value needs to be passed to `tr()` as 3rd argument:

`tr("Importing %n files(s)", nullptr, file_count_)`

I opened a WIP PR here: #1424

**Comment by Simran-B** [comment]
The following strings are now translatable with different grammatical number forms:

- `%1: Audio - %n Channel(s), %2Hz`
- `Running %n background task(s)`
- `%n element(s)`
- `Importing %n file(s)`
- `%n minute(s)`

Only integer values can be handled by Qt. Therefore, widgets like FloatSliders will only have a single translation with no singular/plural handling (`cache_ahead_slider_`, `cache_behind_slider_`. `default_still_length_`).
