### ISSUE TITLE
[CRASH] Timeline manipulation

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#1425]
**Commit Hash**  f8a5e28c

**Platform**  Windows 10 Insider preview beta channel

**Summary**
I was trying to edit clip recorded in h265, FHD at 60FPS. Olive lagged probably becouse of moving playhead. I accidently moved clip intending to delete it. Before It actually moved and olive lagged again leaving yellow rectangle in place I deleted the clip. 

**Steps to Reproduce**
I am not entirly sure what happened
1. have footage on timeline
2. cut a part
3. move playhead so olive lags and computes image
4. move cut piece to 2nd or third track
5. before it is moved delete the part
6.  crash? 

<details><summary><strong>Backtrace</strong></summary><pre><code>

>	olive-editor.exe!olive::NodeTraverser::GenerateTable(const olive::Node * n, const olive::TimeRange & range) Line 79	C++
 	olive-editor.exe!olive::NodeTraverser::ProcessInput(olive::NodeInput * input, const olive::TimeRange & range) Line 53	C++
 	olive-editor.exe!olive::NodeTraverser::GenerateDatabase(const olive::Node * node, const olive::TimeRange & range) Line 41	C++
 	olive-editor.exe!olive::NodeTraverser::GenerateTable(const olive::Node * n, const olive::TimeRange & range) Line 76	C++
 	olive-editor.exe!olive::NodeTraverser::GenerateBlockTable(const olive::TrackOutput * track, const olive::TimeRange & range) Line 99	C++
 	olive-editor.exe!olive::RenderProcessor::GenerateBlockTable(const olive::TrackOutput * track, const olive::TimeRange & range) Line 259	C++
 	olive-editor.exe!olive::NodeTraverser::GenerateTable(const olive::Node * n, const olive::TimeRange & range) Line 70	C++
 	olive-editor.exe!olive::NodeTraverser::ProcessInput(olive::NodeInput * input, const olive::TimeRange & range) Line 53	C++
 	olive-editor.exe!olive::NodeTraverser::GenerateDatabase(const olive::Node * node, const olive::TimeRange & range) Line 41	C++
 	olive-editor.exe!olive::NodeTraverser::GenerateTable(const olive::Node * n, const olive::TimeRange & range) Line 76	C++
 	olive-editor.exe!olive::NodeTraverser::ProcessInput(olive::NodeInput * input, const olive::TimeRange & range) Řádek 53	C++
 	olive-editor.exe!olive::RenderProcessor::Run() Line 57	C++
 	olive-editor.exe!olive::RenderProcessor::Process(std::shared_ptr<olive::RenderTicket> ticket, olive::Renderer * render_ctx, olive::StillImageCache * still_image_cache, olive::RenderCache<olive::Stream *,std::shared_ptr<olive::Decoder>> * decoder_cache, olive::RenderCache<QString,QVariant> * shader_cache, QVariant default_shader) Line 182	C++
 	olive-editor.exe!olive::RenderManager::RunTicket(std::shared_ptr<olive::RenderTicket> ticket) Line 200	C++
 	olive-editor.exe!olive::ThreadPoolThread::run() Line 122	C++
 	Qt5Core.dll!00007ff834696e93()	Neznámý
 	kernel32.dll!BaseThreadInitThunk()	Neznámý
 	ntdll.dll!RtlUserThreadStart()	Neznámý

</code></pre></details>

<details><summary><strong>Additional Information</strong></summary>
Image of values. I think when copyinlg text it would be a mess.

![2020-11-27 (10)](https://user-images.githubusercontent.com/18588943/100478606-fe7d3b80-30eb-11eb-907d-fde104f04f03.png)
</details>
I can provide memory dump file (757 519kB).

**Comment by itsmattkc** [comment]
Looking at the backtrace, I believe this is the same crash as #1420 so I'm going to merge it with that for now.
