### ISSUE TITLE
Video not viewing in sequence viewer!!!

### ISSUE THREAD

**Issue by CoderHardcore** [olive-editor/olive#1429]
This is the first time I ever downloaded olive 0.1 32-bit, I was extremely excited as I saw the preview and 32- bit don't have much video editors which are good. After the installation I Launched olive, the interface was exactly what i expected and I loved it, I decided to try out the program. I created a new project, imported a clip and when I viewed it in the sequence player... it was just a dark black screen I created new sequence player window and tried again but same result, There were no error message pop-ups so I checked the debug log and there was error called [ERROR] Failed to retrieve frame for clip "(video name)" (:0, )
[WARNING] Failed to create texture (:0, ). I know the problem is with my pc but i don't know what it is, is it directx problem or opengl, etc.Please give me a Solution!!!

**Comment by AGI-THB** [comment]
Fill out the issue template...

And version 0.1 is not supported anymore.

It's alpha software after all, so don't expect help for this version.

**Comment by pgilfernandez** [comment]
try this:

1. go to the installation folder
2. find opengl32sw.dll
3. rename it into opengl32.dll
4. try again

Cheers
