### ISSUE TITLE
Ability to Reorder Effects

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#143]

**Comment by itsmattkc** [comment]
Added through a right click menu. Maybe later we can add a drag-drop interface.

**Comment by oc1024** [comment]
Right click > Move up updates the viewer with the new effect stack, but the effects widget still shows the same order and one needs to click in and out of the video in order to update the effects tab.

**Comment by itsmattkc** [comment]
Should be fixed in 2ed9d6ba2ea793a726453aa41a16c21e9496e61c
