### ISSUE TITLE
[GOV] Adopt ClearlyDefined?

### ISSUE THREAD

**Issue by Simran-B** [olive-editor/olive#1435]
https://clearlydefined.io/about

**Comment by elsandosgrande** [comment]
@Simran-B If we're considering ClearlyDefined, then we should be considering [SPDX](https://spdx.dev/) as well in my opinion.

**Comment by sobotka** [comment]
Seems like a lot of bureaucracy.

**Comment by Simran-B** [comment]
I see it as a tool to get clarity on licensing down to a per-file level, which could be handy. 

@elsandosgrande They seem orthogonal to each other (i.e. not either/or but they rather go hand in hand). ClearlyDefined seems to scan repositories and determine the license for each file, which includes SPDX headers. Whether all files could have an SPDX headers only instead of a lengthy license preamble is a different question.

**Comment by elsandosgrande** [comment]
@Simran-B Well, the Linux kernel already uses SPDX exclusively. [Here's a random C file](https://github.com/torvalds/linux/blob/master/kernel/watchdog.c). [Here are the details of how the Linux kernel implements the SPDX headers](https://github.com/torvalds/linux/blob/master/Documentation/process/license-rules.rst).

**Comment by sobotka** [comment]
Given the size and the scope of the project, is it an issue?

Why not cross bridges as they are required?

**Comment by elsandosgrande** [comment]
@sobotka Nobody is saying that we **MUST** adopt ClearlyDefined **right now**. This ticket is merely for discussion and consideration in the future.

**Comment by sobotka** [comment]
You know I realize that?

It stinks of yet more bureaucratic rubbish, that does zip all in terms of actually making the software useful. Zero.

**Comment by Simran-B** [comment]
A tool that scans code for license information and dependencies:
https://github.com/nexB/scancode-toolkit

While generating a software bill of material (SBOM) includes license management aspects, its primary focus is on supply chain security. SPDX license identifiers seem like a good thing to do however, but it's unclear if license headers in third-party files can be substituted with such an identifier or if that would constitute a license violation in certain cases.
