### ISSUE TITLE
[NODES] When changing the value of a position-key-frame an additional keyframe is added on top

### ISSUE THREAD

**Issue by FoxWhiskey** [olive-editor/olive#1437]
**Commit Hash** 7dd9115e

**Platform** Mint 19.2 

**Summary**
When working with the transform node and setting several position key frames it is not possible to alter position values of a previously set key frame without (automagically) adding a new one on top of the previous key frame.
The playhead was positioned by using the < > buttons.

**Additional Information / Output**
I have tested the "scale" option as well and seems to work as expected (values can be altered without a new key frame being added)

**Comment by itsmattkc** [comment]
Are you sure this is a bug? The "position" allows you to keyframe the X and Y parameters separately so that might be what you're running into (see the "Curve View" panel for a better view of this)

**Comment by FoxWhiskey** [comment]
Well, I was contemplating as well before opening the issue. But I'd like to make two points that suggest that the current implementation is worth to be reconsidered:

1. A key frame - in my understanding - marks a unique point in time, defining a unique user defined state of a specific transform type. In case of the position transform, the "state" is defined by two values, x and y coordinate, which are independent, but - being an array of two - represent a unique property (at a unique point in time). Therefore, if two key frames are allowed for the same point in time, ambiguity is introduced! 
2. From a different perspective: when dragging a single (position-) key frame from t1 to t2 on the time scale, it is not obvious whether x or y key frame is affected. The (expected) behaviour is: the key frame relates to both - x *and* y parameter - and both are moved to t2. And actually, this is how the mechanism is currently implemented...

I also checked with 0.1 and wasn't able to reproduce the issue...
