### ISSUE TITLE
[CRASH] Exporting at 4K causes unexpected sigabrt  

### ISSUE THREAD

**Issue by FDDTheLucario** [olive-editor/olive#1439]
**Commit Hash** 
7dd9115e

**Platform** 
EndeavourOS with kernel version 5.4.80-2-lts

**Summary**
When exporting a video at 4K (3840 x 2160), the program will crash. Exporting works fine at 1080p resolutions. 

**Steps to Reproduce**

1. Open the Export window.
2. Ensure the codec is H.264, the resolution is 4K, and the file format is MPEG-4.
3. Attempt to export video.

<details><summary><strong>Backtrace</strong></summary><pre><code>
double free or corruption (out)
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 14 "olive::ThreadPo" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffb7fff640 (LWP 102144)]
0x00007ffff32ff615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff32ff615 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff32e8862 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff33415e8 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff334927a in  () at /usr/lib/libc.so.6
#4  0x00007ffff334aaf8 in _int_free () at /usr/lib/libc.so.6
#5  0x00005555557323df in olive::SampleBuffer::destroy_sample_buffer(float***, int)
    (nb_channels=<optimized out>, data=<optimized out>)
    at /home/soulcatcher/olive-git/src/olive/app/codec/samplebuffer.cpp:305
#6  olive::SampleBuffer::destroy_sample_buffer(float***, int)
    (data=0x7fffa80c04a8, nb_channels=<optimized out>)
    at /home/soulcatcher/olive-git/src/olive/app/codec/samplebuffer.cpp:301
#7  0x0000555555732ad3 in olive::SampleBuffer::~SampleBuffer()
    (this=<optimized out>, __in_chrg=<optimized out>)
    at /home/soulcatcher/olive-git/src/olive/app/codec/samplebuffer.cpp:33
#8  __gnu_cxx::new_allocator<olive::SampleBuffer>::destroy<olive::SampleBuffer>(olive::SampleBuffer*) (__p=<optimized out>, this=<optimized out>) at /usr/include/c++/10.2.0/ext/new_allocator.h:156
#9  std::allocator_traits<std::allocator<olive::SampleBuffer> >::destroy<olive::SampleBuffer>(std::allocator<olive::SampleBuffer>&, olive::SampleBuffer*) (__p=<optimized out>, __a=<optimized out>)
    at /usr/include/c++/10.2.0/bits/alloc_traits.h:531
#10 std::_Sp_counted_ptr_inplace<olive::SampleBuffer, std::allocator<olive::SampleBuffer>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (this=<optimized out>)
    at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:560
#11 0x00005555557fc19f in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
    (this=<optimized out>) at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:158
#12 std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count()
    (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:733
#13 std::__shared_ptr<olive::SampleBuffer, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr()
    (this=<optimized out>, __in_chrg=<optimized out>)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:1183
#14 std::shared_ptr<olive::SampleBuffer>::~shared_ptr()
    (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.2.0/bits/shared_ptr.h:121
#15 olive::RenderProcessor::GenerateBlockTable(olive::TrackOutput const*, olive::TimeRange const&)
    (this=<optimized out>, track=<optimized out>, range=<optimized out>)
    at /home/soulcatcher/olive-git/src/olive/app/render/renderprocessor.cpp:214
#16 0x00005555557b8e1b in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::TimeRange const&) (this=0x7fffb7ffe780, n=0x7fff18095450, range=...)
    at /home/soulcatcher/olive-git/src/olive/app/node/traverser.cpp:70
#17 0x00005555557b902b in olive::NodeTraverser::ProcessInput(olive::NodeInput*, olive::TimeRange const&) (this=this@entry=0x7fffb7ffe780, input=0x7fff18034330, range=...)
    at /home/soulcatcher/olive-git/src/olive/app/node/traverser.cpp:53
#18 0x00005555557f9ca0 in olive::RenderProcessor::Run() (this=0x7fffb7ffe780)
    at /home/soulcatcher/olive-git/src/olive/app/render/renderprocessor.cpp:136
#19 0x00005555557fb993 in olive::RenderProcessor::Process(std::shared_ptr<olive::RenderTicket>, olive::Renderer*, olive::StillImageCache*, olive::RenderCache<olive::Stream*, std::shared_ptr<olive::Decoder> >*, olive::RenderCache<QString, QVariant>*, QVariant)Python Exception <class 'gdb.error'> value has been optimized out: 

    (ticket=, render_ctx=0x555557d4c1a0, still_image_cache=<optimized out>, decoder_cache=0x7fffe4003fc0, shader_cache=0x555557a0af30, default_shader=...)
    at /home/soulcatcher/olive-git/src/olive/app/render/renderprocessor.cpp:186
#20 0x00005555557f35e4 in olive::RenderManager::RunTicket(std::shared_ptr<olive::RenderTicket>) const
    (this=0x555557d3cdc0, ticket=std::shared_ptr<olive::RenderTicket> (use count 5, weak count 0) = {...}) at /home/soulcatcher/olive-git/src/olive/app/render/rendermanager.cpp:212
#21 0x000055555580a0c5 in olive::ThreadPoolThread::run() (this=0x5555579be640)
    at /home/soulcatcher/olive-git/src/olive/app/threading/threadpool.cpp:124
#22 0x00007ffff3895f0f in  () at /usr/lib/libQt5Core.so.5
#23 0x00007ffff2f253e9 in start_thread () at /usr/lib/libpthread.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#24 0x00007ffff33c2293 in clone () at /usr/lib/libc.so.6
</code></pre></details>

**Additional Information**
EndeavourOS does not use version numbers; however, it is based on Arch Linux, and this bug should be reproducible on that distro if the same (or similar) kernel is used. My main GPU is also a Radeon RX 580 8 GB with the AMDGPU open-source drivers, in case this is a driver issue.

**Comment by ThomasWilshaw** [comment]
From a brief look at the bacltrace this looks like an audio issue. Are you able to provide a sample of footage you were using?

**Comment by itsmattkc** [comment]
This might be a duplicate of #1418. Try checking the memory usage of Olive while exporting and see if it crashes once it's consumed most of your RAM.

**Comment by unfa** [comment]
I've tested 4K export yesterday on a fresh AppImage build on Manjaro Linux, and it consumed around 60 GB of RAM (had to hot-add extra swap, as I *only* have 32 GB of RAM), but after that is seemed pretty steady. Though exporting a 5-minute clip was estimated to take 5 hours so I aborted this after 20-30 minutes of rendering.

**Comment by Simran-B** [comment]
@unfa can you try again with a build that includes https://github.com/olive-editor/olive/commit/3dae723bbc0776d40588f90f8f418ba51317de68 ?

**Comment by unfa** [comment]
I will - it sounds reasonable. The MKV file I was rendering into was below 1KB all the time, so I guess all the ~10% completion shown still didn't account for one GOP to be written to disk. Very strange.

**Comment by itsmattkc** [comment]
Closing this assuming it was a duplicate of #1418. Reply back if this is still an issue.
