### ISSUE TITLE
[NODES] String / Number node

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1443]
**Commit Hash** 
1cd07bc1

**Platform** 
macOS 10.14.6

**Summary**
I think it has been already said somewhere but I can't find a issue/feature request that covers it so, let me write it down in case you think it's important:

I'm missing a simple node that inputs a number (integer, float,...) or a simple node that inputs a text. Then they can be connected to any value of other nodes so that you save time and have everything "parametric".
For instance, I have done this little node group to stroke and drop a shadow of a text but, by now, I'm force to write the text in both nodes. I have also added in red a mockup of the "string node" that could be connected to the "text parameter" inside the Text node:
<img width="1679" alt="string" src="https://user-images.githubusercontent.com/5942369/102102571-43afa600-3e2c-11eb-96f2-5452d261d2c2.png">

The same would apply for numbers and any numeric value inside any node.

Thanks

**Additional Information / Output**
[EDIT]: Additionally I guess there are another kind of "input nodes" such as a boolean, percentage, 2D vector (X and Y numeric values), 2D vector with percentage, ...

**Comment by ThomasWilshaw** [comment]
This is a planned feature but won'tbe implemented for a while. Thanks for the suggestion.

**Comment by pgilfernandez** [comment]
Thanks to let us know, it will be great when it arrives  =)
