### ISSUE TITLE
[CACHE] Cache doesn't render at sequence preview resolution change

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1445]
**Commit Hash** 
1cd07bc1

**Platform** 
macOS 10.14.6

**Summary**
1. Open Olive
2. Create a new sequence (no matter what settings it has)
3. Place something (for instance a solid clip) so that the cache renders it
4. Go to sequence properties in Project Browser
5. Change Preview Resolution to anything but the actual one
6. Press OK button

You will see that the old cache is unloaded but an updated one is not created even if you force to render entire sequence from the menu.
Live preview also doesn't work and makes it hard to "unstuck" it, something similar what it happens in #1432 

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
I can confirm this happens with Windows 10 and with footage as well.

**Comment by itsmattkc** [comment]
This should be fixed with the recent merge of `nodearchchanges`.
