### ISSUE TITLE
Fresh windows install fresh olive install reveals Adware.FPL.Gen.vl. Please remove from windows package. :-(

### ISSUE THREAD

**Issue by digc16** [olive-editor/olive#1447]
**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**

**Comment by digc16** [comment]
Fresh windows install fresh olive install reveals Adware.FPL.Gen.vl. Please remove from windows package. :-(

**Comment by digc16** [comment]
crashpad_handler.exe
maindump_stackwalk.exe
olive_crash_handler.exe
olive_editor.exe
uninstall.exe

then something like 92 dll's as a part of Adware.FPL.Gen.vl

Gridinsoft Anti-Malware scanner was used. There was no incentive to report this other than I love your software and would like it to not be compromised. Best of luck. Time to uninstall. Thank you.

**Comment by ThomasWilshaw** [comment]
Can I just check, did this come directly from the Olive website?

**Comment by elsandosgrande** [comment]
@digc16 Since [VirusTotal](https://www.virustotal.com/gui/file/a8f22544b3676d9c15593e8345e3dff9506c6479c108f68c3a8ac512d2874115/detection) had no complaints whatsoever, I'm willing to bet that that antivirus is not worth any money.

**Comment by Simran-B** [comment]
Detection is often based on heuristics, and especially something like Crashpad has the potential of being detected as malicious because it ticks several boxes. It's also very common for Windows SmartScreen to block nightly builds, simply because they contain unsigned and uncommon binaries. There is no adware in official Olive builds however. Don't trust other sources, someone might have tampered with the executables.

**Comment by elsandosgrande** [comment]
@Simran-B Windows SmartScreen even‽ I can't tell if that's because it's very sensitive, or because it isn't as high of a quality as antivirus software as that of dedicated companies.

@digc16 Where did you acquire the build which was detected as adware?

**Comment by itsmattkc** [comment]
@elsandosgrande Windows SmartScreen isn't doing anything "smart" there, if an executable is unsigned and isn't in a list of "frequently downloaded executables", it blocks it by default (macOS does the same thing). Definitely should look into getting our executables signed by the time we have stable releases (probably not worth it for nightlies).

**Comment by elsandosgrande** [comment]
Oh. I know even less about Windows than I thought then :sweat_smile:.
