### ISSUE TITLE
Error with Snap Package

### ISSUE THREAD

**Issue by nerdgarden** [olive-editor/olive#1449]
if I do:
`sudo snap install --edge olive-editor`

I get:
**error: snap "olive-editor" not found**

even searched on the snap store but no results.

Michele

**Comment by elsandosgrande** [comment]
@nerdgarden No packaging other than that found on the official website is official. It seems that some people have tried to package Olive for Debian and such, but it's not officially supported. It's also not really wanted right now for two reasons:

1. Olive is still in alpha.
2. The people who currently try to package Olive do not do so consistently (with every nightly build), which causes more harm than good.

Once Olive reaches beta, packaging might be considered. If the beta version is to be packaged, then I'd mostly likely handle it and it would not be official, at least not strictly official, which would mean that it would again be wrong to mention issues with the packaging here (the community server is fine though).

**Comment by elsandosgrande** [comment]
Also, don't try to bypass the issue templates, they're there for a reason.
