### ISSUE TITLE
[CRASH] Olive crashes doing a cross desolve that spans the entirety of a clip

### ISSUE THREAD

**Issue by bkurdali** [olive-editor/olive#1450]
**Commit Hash** 
1cd07bc1

**Platform** 
Fedora Linux 33

**Summary**
When doing a cross desolve that spans the entirety of a clip, olive crashes on mouse release (this does not happen if the cross desolve leaves a bit at the end)

**Steps to Reproduce**

1. Create a Sequence with two clips in the timeline, one over the other
2. Switch your tool to add a cross disolve transition
3. drag from the beginning of the top clip all the way to the end
4. olive crashes on mouse release (this does not happen if you don't reach quite the end of the top clip)

<details><summary><strong>Backtrace</strong></summary><pre><code>

#0  olive::Item::parent (this=this@entry=0x51)
    at ../app/project/item/item.cpp:128
#1  0x000000000066e073 in olive::Item::root (this=<optimized out>)
    at ../app/project/item/item.cpp:135
#2  0x000000000066e089 in olive::Item::project (this=<optimized out>)
    at ../app/project/item/item.cpp:144
#3  0x00000000006cc066 in olive::UndoCommand::redo (this=0x4130430)
    at ../app/undo/undocommand.cpp:36
#4  0x00007ffff45e9122 in QUndoCommand::redo() ()
   from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#5  0x00007ffff45eafa6 in QUndoStack::push(QUndoCommand*) ()
   from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#6  0x0000000000744a82 in olive::TransitionTool::MouseRelease (this=0x3b3f060, 
    event=<optimized out>)
    at ../app/widget/timelinewidget/tool/transition.cpp:175
#7  0x0000000000755c95 in olive::TimelineWidget::ViewMouseReleased (
    this=0x3926f20, event=0x7fffffffce70)
    at ../app/widget/timelinewidget/timelinewidget.cpp:842
#8  0x00007ffff37e8e95 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Core.so.5
#9  0x0000000000564ae2 in olive::TimelineView::MouseReleased (
    this=this@entry=0x2dd09a0, _t1=<optimized out>, _t1@entry=0x7fffffffce70)
    at app/olive-editor_autogen/EYCRI7KD7O/moc_timelineview.cpp:228
--Type <RET> for more, q to quit, c to continue without paging--c
#10 0x000000000074f504 in olive::TimelineView::mouseReleaseEvent (this=0x2dd09a0, event=0x7fffffffd390) at ../app/widget/timelinewidget/view/timelineview.cpp:102
#11 0x00007ffff42c6836 in QWidget::event(QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#12 0x00007ffff436f9be in QFrame::event(QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#13 0x00007ffff45b279c in QGraphicsView::viewportEvent(QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#14 0x00007ffff37bf3b3 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Core.so.5
#15 0x00007ffff42875e1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#16 0x00007ffff4290808 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#17 0x00007ffff37bf692 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Core.so.5
#18 0x00007ffff428fa80 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff42e170f in ?? () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff42e43cc in ?? () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff42875f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#22 0x00007ffff42906a0 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Widgets.so.5
#23 0x00007ffff37bf692 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Core.so.5
#24 0x00007ffff3c396b3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Gui.so.5
#25 0x00007ffff3c3af22 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Gui.so.5
#26 0x00007ffff3c16f7b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Gui.so.5
#27 0x00007fffdd743c7a in ?? () from /tmp/.mount_Olive-7VSNeu/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#28 0x00007ffff2afd7ef in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#29 0x00007ffff2b4f5d8 in g_main_context_iterate.constprop () from /lib64/libglib-2.0.so.0
#30 0x00007ffff2afabc3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#31 0x00007ffff3812811 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Core.so.5
#32 0x00007ffff37be47b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Core.so.5
#33 0x00007ffff37c5a6e in QCoreApplication::exec() () from /tmp/.mount_Olive-7VSNeu/usr/bin/../lib/libQt5Core.so.5
#34 0x000000000055b11d in main (argc=<optimized out>, argv=0x7fffffffddb8) at ../app/main.cpp:184

</code></pre></details>

**Additional Information**
This may sound like a weird thing to do, explanation: I was creating "Alien Pro-Covenant" A slow disolve from Prometheus to Alien Covenant in an effort to make these movies watchable. In the end, the only program that succeeded was blender (I also tried pitivi, kdenlive, resolve and premier) - I think olive 0.2 would manage this stress-test if not for this bug.
The bug seems to get triggered with any clip I have here, but if you can't I'm uploading a (small) clip that crashes - you can then just double it up in the timeline

https://user-images.githubusercontent.com/4793742/103011120-65cdb600-4507-11eb-8368-ae17d2607be3.mp4

.

**Comment by ThomasWilshaw** [comment]
I can confirm this also happens on Windows 10.

**Comment by ThomasWilshaw** [comment]
@itsmattkc I've been taking a bit of a look at this one. The issue here is making the transition the length of the clip deletes  the clip so when the code tries to relink the nodes automatically it tries to link to a none existant node. What is the expected behaviour when dragging a transition onto a clip? I notice if you add a transition to say half the clip and then try to extend it, you cannot drag it right to the end of the clip,you always have to leave at least one frame.

**Comment by itsmattkc** [comment]
Expected behavior is the latter, a block must be at least 1 frame in length to exist as an entity in the timeline, however I've never been completely happy with this solution since it breaks situations like this. The only way around it is either to allow clips to be 0 frames in length (allowing a transition to overtake it entirely) or make transitions 0 frames in length at all times (using extra logic to determine if the next/previous block is a transition, and then checking its in/out offsets).

**Comment by bkurdali** [comment]
how about using nodes as a workaround? I'm guessing we could add a cross dissolve in the node editor?

**Comment by itsmattkc** [comment]
Merging into #1842
