### ISSUE TITLE
[BUILD] Website Compile Instructions failing on Ubuntu 20.04

### ISSUE THREAD

**Issue by chrishobcroft** [olive-editor/olive#1452]
**Commit Hash** 

`1d36d5b70eae1180aeb50e0ec3f094f3466f6b5a` (of OpenColorIO)

**Platform** 

Ubuntu 20.04

**Summary**

I am following these instructions: https://www.olivevideoeditor.org/compile.php#ubuntu

They fail when running ` cmake --build . --target install` on 

I know it's not an issue with `olive`, but it is an issue with `olive`'s build docs :) X X

**Additional Information / Output**

This is what the failure looks like:

```
Install the project...
-- Install configuration: "Release"
CMake Error at include/OpenColorIO/cmake_install.cmake:41 (file):
  file cannot create directory: /usr/local/include/OpenColorIO.  Maybe need
  administrative privileges.
Call Stack (most recent call first):
  include/cmake_install.cmake:42 (include)
  cmake_install.cmake:43 (include)


make: *** [Makefile:108: install] Error 1
```

**Comment by ThomasWilshaw** [comment]
Which exact command gives that error? And where are you trying to install?

**Comment by Simran-B** [comment]
The build instructions for Ubuntu don't say anything about `cmake --build . --target install`. You are supposed to build Olive with `cmake --build .`, after that you should be able to run it. You might have to append to `LD_LIBRARY_PATH` so that it finds additional libraries that aren't in the default locations. To install the files, you can try to run `cmake --install .`. Or `cmake --install . --prefix appdir` to copy the files to a folder `appdir` in the build folder.

**Comment by chrishobcroft** [comment]
@Simran-B wrote:
> The build instructions for Ubuntu don't say anything about cmake --build . --target install. 

This is what is shown when I load https://www.olivevideoeditor.org/compile.php#ubuntu :

![image](https://user-images.githubusercontent.com/2212651/103442183-f29c1080-4c79-11eb-9d6b-8e8df38782c0.png)

@ThomasWilshaw wrote:
> Which exact command gives that error? And where are you trying to install?

I am installing on Ubuntu 20.04.1. The exact command is in the original issue.

**Comment by Simran-B** [comment]
Oh, now I understand. This is only about building OCIO. I never tried to compile it using Unix Makefiles explicitly nor the install target, but rather with:

```bash
cmake .. -DCMAKE_BUILD_TYPE=Release -DOCIO_INSTALL_EXT_PACKAGES=ALL
cmake --build . --config Release
cmake --install . --config Release
```

**Comment by chrishobcroft** [comment]
I understand. I would recommend updating the compile instructions so that they work for anyone else. Thanks

**Comment by chrishobcroft** [comment]
@Simran-B if you are satisfied that adequate information has been provided, please remove the "inadequate information" tag.

Or if there is any further information to require, please let me know. Thanks.

**Comment by itsmattkc** [comment]
I think this is merely that the install needs to be run with `sudo`. If you run the following two commands instead of `cmake --build . --target install`, does it work?

```
cmake --build .
sudo cmake --install .
```

**Comment by itsmattkc** [comment]
Compile instructions should work now.
