### ISSUE TITLE
[EDIT] Audio noise removal

### ISSUE THREAD

**Issue by TheJaredWilcurt** [olive-editor/olive#1453]
**Commit Hash** 19eabf28

**Platform** Win

**Summary** Just requesting that analyzing a snippet of audio for noise and then removing the noise from that audio track be added in at some point down the line. Would really simplify my workflow if I didn't need to export audio out, import it into another program just to do noise removal, export it out of there and import it back in and replace the original audio track.

**Additional Information / Output** No rush. This can be thrown in the 0.3 or Revisit Later projects.

**Comment by Simran-B** [comment]
This seems really out of scope, even though I understand the desire to have something like this built in. Even DAWs typically don't come with such functionality out of the box. It's more of a plugin kind of thing. Could become possible via VST plugin support. Closing, but adding this feature request to the Revisit later project.
