### ISSUE TITLE
[CRASH] Windows 10 x64

### ISSUE THREAD

**Issue by DaZy4** [olive-editor/olive#1458]
**Commit Hash** 

**Windows 10**

https://user-images.githubusercontent.com/57320865/103526773-729cc300-4e92-11eb-836d-e40eee28e6a2.mp4

**Steps to Reproduce**

1. opened directory
2. try to open editor (CRASHED)
3. look at error from cmd.exe

<details><summary><strong> [DEBUG] Extracting default OCIO config to "C:/Users/▐Ёр/AppData/Local/olivevideoeditor.org/Olive/cache/ocioconf" ((null):0) </strong></summary><pre><code>

</code></pre></details>

**Version of crashed olive video editor = 0.2**

**Comment by mcDandy** [comment]
You should provide commit hash (if you remember when you downloaded it you should be able to get the hash in table at: https://www.olivevideoeditor.org/nightly.php ).
