### ISSUE TITLE
[UI] Assigning wrong button in non-english layout

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#1459]
**Commit Hash** 
19eabf28

**Platform** 
Windows 10 2H2

**Summary**
When changing the keyboard shortcuts in Olive 0.2.0 on Windows, e.g. when clicking <kbd>Strg</kbd>+<kbd>+</kbd> (Strg is Ctrl) in the German keyboard layout, Olive recognizes <kbd>Strg</kbd>+<kbd>]</kbd>.

**Additional Information / Output**

This does not happen on Linux.
Sadly don't quite know what causes it, but would be thrilled if this could be fixed.
Otherwise, thank you very much for the effort put into this amazing project.
Keep it up.

**Comment by Simran-B** [comment]
Please stick to the existing issue templates. Updated your post.

**Comment by itsmattkc** [comment]
Hmm not sure what could cause this, sounds like a Qt bug if anything if it only affects some platforms.

**Comment by itsmattkc** [comment]
It would appear the official solution would be to wrap keyboard shortcuts in `tr()` so that they're updated with the language, which would at least solve the problem for users using the "default" keyboard for their locale. This might be how this issue is ultimately solved?
