### ISSUE TITLE
[TRANSLATION] Spanish translation (es_ES)

### ISSUE THREAD

**Issue by RafaMartorell** [olive-editor/olive#1462]
More than a year ago I committed to collaborating with whatever was within my reach in this wonderful project.
Some time ago (2 years or so) I made the Spanish translation of version 0.1.x
And I also started writing the manual in Spanish. But one of the developers (I don't remember who) told me to pause the manual because the new version would bring a lot of changes and it was better to wait. But I have not forgotten my commitment, and now I see with great happiness that Olive is in a very good direction, but I also see a lot of new terms in the new version that are not translated, and I think I can take care of this, yes for you it is not an inconvenience.
I anticipate that if the answer is yes, as it did, almost two years ago, I needed some help, I am not a programmer, just an audiovisual technician, this time I think I will also need it to be able to carry out the task successfully, just like I carried it successfully in the previous version.
Waiting for news from you attentively Rafa.

**Comment by elsandosgrande** [comment]
Hi Rafa! Did you already try the process described in [the wiki](https://github.com/olive-editor/olive/wiki/Translations)?

**Comment by RafaMartorell** [comment]
Sorry, you're right, now I remember that this was my starting point, also on the recommendation of someone from the team. It wasn't easy for me but I got it, I guess this time I'll get it too, thanks for answering and refreshing my memory.
As soon as I finish some works that I have to finish, I will get back to the translation. Now I remember that I was even able to test the translations, I have the notes on a laptop that I don't have at work now, but as soon as I get home I will go over everything.
Thanks, I love Olive.

**Comment by elsandosgrande** [comment]
@RafaMartorell If you don't need any further help with making the translation, feel free to close this ticket.

I wish you good luck with getting everything going smoothly and have a nice day!

**Comment by RafaMartorell** [comment]
Thank you very much, for now I will leave it open, if it is not a problem, until I am sure that I can do the translation without help.

**Comment by RafaMartorell** [comment]
Thank you very much, for now I will leave it open, if it is not a problem,
until I am sure that I can do the translation without help.

**Comment by RafaMartorell** [comment]
This step I don't know how to do it 
> Get a copy of the Olive source code, preferably the latest commit. The recommended way to do this is by forking the GitHub repository and then cloning it to your own system. This will allow you to make a GitHub pull request that will make it easy for us to merge it and for you to be credited for writing it.

I have downloaded the zip with the code, is it correct if I work in this way or is it better to fork?

**Comment by elsandosgrande** [comment]
@RafaMartorell While simply downloading the ZIP again whenever you want to update the translations can work, you'll either have to upload all of the translation files over and over again in this ticket, or open a new ticket whenever you want to update a translation. If you have the time to learn Git more, it would be preferred for you to fork the repository and create a pull request for the first update and whenever you have an update to make.

**Comment by RafaMartorell** [comment]
I am very sorry for my little knowledge of these topics, is there any guide or advice to be able to do this as a fork? What are pull requests and how are they done?
At the moment I am translating the file that I have downloaded as zip following the instructions, but I cannot test because my system is based on Ubuntu 18.04, but now I will install in a 20.04 virtual machine to compile and test.
Thank you very much for the help and your response.

**Comment by elsandosgrande** [comment]
@RafaMartorell To the best of my knowledge, you _should_ be able to test it with Ubuntu 18.04 as well. Regarding Git and GitHub, [this](https://guides.github.com/) should cover you.

If you need further help, for example with getting things going just with 18.04, maybe you could take a peek at the Discord server? Simran and I are administrators there, so I (and maybe others as well) would be able to give help more quickly. If you don't wish to use Discord, we can continue using this ticket.

No worries and I wish you a nice day!

**Comment by RafaMartorell** [comment]
I have a problem with cmake file of OpenColorIO, see:

> cmake .. -G "Unix Makefiles" -DOCIO_BUILD_PYTHON=OFF
CMake Error at CMakeLists.txt:8 (cmake_minimum_required):
  CMake 3.12 or higher is required.  You are running version 3.10.2

Now I will prove in Mint 20.1 based in ubuntu 20.04

**Comment by RafaMartorell** [comment]
I follow the steps indicated in the wiki
https://github.com/olive-editor/olive/wiki/Translations
But I can't test the translation, I always get the same error.
In the virtual machine where I installed it:
![01](https://user-images.githubusercontent.com/47257587/106641593-a9e0bb80-6587-11eb-82f1-570bc6b7e09d.png)
![02](https://user-images.githubusercontent.com/47257587/106641612-b06f3300-6587-11eb-841e-30c6f70e50ce.png)

Or on my main system, Mint 19.3
![03](https://user-images.githubusercontent.com/47257587/106641653-ba913180-6587-11eb-89d6-62b8226a580f.png)
![04](https://user-images.githubusercontent.com/47257587/106641673-c3820300-6587-11eb-92c9-6d6828dffabc.png)

I can translate but not test and see the changes...

**Comment by RafaMartorell** [comment]
Solved !!!!
I changed the es_ES.ts file that I have translated in the ~/olive/app/ts folder that I downloaded, after that I compiled again, and now I see the translated lines.
Thank you very much.

**Comment by Simran-B** [comment]
This is great news! Can we close this issue then?

**Comment by RafaMartorell** [comment]
Just one last question, when do I have the file translated, how do I deliver it? Sorry, but I'm very new to these things. When I am told how to make the delivery, this thread can be closed.

**Comment by elsandosgrande** [comment]
@RafaMartorell If you made a fork (I can't tell from the above), then submit a pull request. If you did not, then you will have to share the file in here or on DIscord to get it submitted by somebody with the necessary privileges to write to the repository (I am currently working on something, so my local repository, which is a hybrid between my fork and the main repository, is not exactly usable at the moment).

**Comment by Simran-B** [comment]
The easiest option would be to edit the file directly on GitHub.

1. [Locate the .ts file on GitHub](https://github.com/olive-editor/olive/blob/master/app/ts/es_ES.ts)
2. Click on the pencil icon to edit it (in your case it should automatically fork the repo so that you can make edits, because you don't have permissions to directly edit the file in our repo)
3. Select everything and paste the content of your local file
4. At the bottom of the page you should have the option to commit the changes (I suggest to select the second option to create a new branch, give it some name like `translation-es`)
5. Afterwards, GitHub should allow you to open a pull request against our repo with your changes.

If this doesn't work out, then you can also share your file here and we can take care of it.

**Comment by RafaMartorell** [comment]
Ok thank you very much, I will try as you indicate, I am not sure I know how to do it, and otherwise I will upload it here. Thank you very much for the help.

**Comment by elsandosgrande** [comment]
> The easiest option would be to edit the file directly on GitHub.

That had completely slipped my mind :sweat_smile:.

**Comment by RafaMartorell** [comment]
I am an audiovisual technician, my computer skills are limited, but this is how I learn. Getting a bold text with markdown already makes me jump for joy. I sense that I am going to have many moments of happiness with Git. :-)
When I finish with the translation I will continue with the Spanish manual that I left incomplete on Olive's Wiki.
Thanks for the support. I really like this project.

**Comment by elsandosgrande** [comment]
@RafaMartorell We're happy to have you on board and I hope that you have a great time learning about Git and improving your computer skills in the process :smiley:!

**Comment by RafaMartorell** [comment]
I attach the file here, because I don't know how to make a clone of the repository, let alone a pull request. I tried to read the Github help, but it has a lot of text and is not practical at all for non-programmers.
The file is complete, but two words are missing, "Undo and Redo" are not in the ts file.
[es_ES.ts.zip](https://github.com/olive-editor/olive/files/5964387/es_ES.ts.zip)

**Comment by Simran-B** [comment]
Here's a video of the process: https://youtu.be/2X4jgHrf1VA

The forking and branching happens automatically, and it also asks you to create a pull request after you propose a change.

Regarding Undo and Redo, there's something fishy with Qt I guess and there's a TODO in the code:
https://github.com/olive-editor/olive/blob/master/app/window/mainwindow/mainmenu.cpp#L619-L620
