### ISSUE TITLE
The worst program ever!!!!

### ISSUE THREAD

**Issue by Ilektrokioydio** [olive-editor/olive#1465]

**Comment by kosmas12** [comment]
Please, if you are to open an issue, at least make it be something helpful (also it's noted as a warning that this is very unstable).

Good day.

**Comment by elsandosgrande** [comment]
@Ilektrokioydio Merely proclaiming that Olive is “The worst program ever!!!!” without any sort of explanation, let alone something actually worth spending time on, like saying where you think Olive should improve and perhaps providing some suggestions if you feel like you know enough to do so, only serves to make you look bad, either by virtue of you seeming to not understand anything, or by virtue of you seeming ignorant and/or feeble-minded. 

Either say how and why you think that Olive is the worst, maybe even adding some well-formed suggestions, or save your breath and take a minute to think everything through.

Good day.

**Comment by sobotka** [comment]
Don’t reply to stupid motherfuckers.
