### ISSUE TITLE
video wont play with a red line

### ISSUE THREAD

**Issue by Ayebae** [olive-editor/olive#1468]
it play and i see a red line. whats going on
![image_2021-01-18_181805](https://user-images.githubusercontent.com/63527909/104973154-816a9600-59b9-11eb-8e4e-2c0c94ec10da.png)

**Comment by Simran-B** [comment]
**Caching**

All footage is cached-on-demand, where demand currently means adding footage to the timeline. This system takes the frames from the encoded bitstream or disk encode, and re-encodes it to Olive's native state. The native state is a half float, sixteen bit still frame on disk. The details of this cache, including the option to cache-on-ingestion, results in the proper quality level required for work within Olive.

![Olive Pre-Alpha Cache UI Feedback](https://user-images.githubusercontent.com/59577/81485637-72fd9500-9203-11ea-9604-bccbf7fc4463.png)
