### ISSUE TITLE
[CRASH] Olive 0.2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by MickBuntu** [olive-editor/olive#1469]
**Commit Hash** 
19eabf28

**Platform** 
Ubuntu 20.04.1 LTS

**Summary**
Loaded valid viewable logo.mp4 clip into Olive 0.2 (AppImage 19eabf28-Linux-x86_64) no alterations, saved project as logo. Closed Olive. Reopened, chose recent files, logo. Olive crashed. Any other clip, reproducible. Crash report as follows.

**Steps to Reproduce**

1. Import, Run Logo.mp4, all OK, no alteration
2. save project as logo.ove
3. Restart Olive
4. use Files/Recent files to load logo.ove
5. Cannot seem to find the file??
6. Segmentation fault.

<details><summary><strong>Backtrace</strong></summary><pre><code>
(gdb) exec-file ~/olive/Olive-19eabf28-Linux-x86_64.AppImage 
(gdb) run
Starting program: /home/mike/olive/Olive-19eabf28-Linux-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 69672]
process 69668 is executing new program: /tmp/.mount_Olive-NFhQR9/usr/bin/olive-editor
warning: Loadable section ".dynstr" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9852700 (LWP 69677)]
[New Thread 0x7fffe9030700 (LWP 69678)]
[Detaching after fork from child process 69680]
[WARNING] Trying to use locale "en_US" but couldn't find a translation for it ((null):0)
[DEBUG] Extracting default OCIO config to "/home/mike/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[New Thread 0x7fffe882f700 (LWP 69684)]
[New Thread 0x7fffe3fff700 (LWP 69685)]
[New Thread 0x7fffe37fe700 (LWP 69686)]
[New Thread 0x7fffe2ffd700 (LWP 69687)]
[New Thread 0x7fffe086f700 (LWP 69688)]
[New Thread 0x7fffc305b700 (LWP 69689)]
[New Thread 0x7fffc285a700 (LWP 69690)]
[New Thread 0x7fffc2059700 (LWP 69691)]
[New Thread 0x7fffc17d8700 (LWP 69692)]
[INFO] Using Qt version: 5.12.8 ((null):0)
[New Thread 0x7fffc0c68700 (LWP 69693)]
[New Thread 0x7fffabfff700 (LWP 69694)]
[New Thread 0x7fffab7fe700 (LWP 69695)]
[DEBUG] Using graphics driver: Intel ((null):0)
[New Thread 0x7fffa8928700 (LWP 69696)]
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1f.3.analog-stereo" ((null):0)

Thread 14 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffabfff700 (LWP 69694)]
--Type <RET> for more, q to quit, c to continue without paging--c
0x0000000000651e12 in olive::NodeTraverser::PostProcessTable (this=0x7fffabffe3f0, node=0x7fffa40966b0, range=..., output_params=...) at ../app/node/traverser.cpp:194
194	../app/node/traverser.cpp: No such file or directory.
(gdb) bt
#0  0x0000000000651e12 in olive::NodeTraverser::PostProcessTable (this=0x7fffabffe3f0, 
    node=0x7fffa40966b0, range=..., output_params=...) at ../app/node/traverser.cpp:194
#1  0x0000000000652e7d in olive::NodeTraverser::GenerateTable (this=0x7fffabffe3f0, 
    n=0x7fffa40966b0, range=...) at ../app/node/traverser.cpp:81
#2  0x0000000000653049 in olive::NodeTraverser::ProcessInput (this=0x7fffabffe3f0, 
    input=0x7fffa4005cd0, range=...) at ../app/node/traverser.cpp:53
#3  0x000000000065318c in olive::NodeTraverser::GenerateDatabase (this=0x7fffabffe3f0, 
    node=0x7fffa4076900, range=...) at ../app/node/traverser.cpp:41
#4  0x0000000000652e59 in olive::NodeTraverser::GenerateTable (this=0x7fffabffe3f0, 
    n=0x7fffa4076900, range=...) at ../app/node/traverser.cpp:76
#5  0x0000000000653049 in olive::NodeTraverser::ProcessInput (this=0x7fffabffe3f0, 
    input=0x7fffa4027f40, range=...) at ../app/node/traverser.cpp:53
#6  0x000000000065318c in olive::NodeTraverser::GenerateDatabase (this=0x7fffabffe3f0, 
    node=0x7fffa4096f30, range=...) at ../app/node/traverser.cpp:41
#7  0x0000000000652e59 in olive::NodeTraverser::GenerateTable (this=0x7fffabffe3f0, 
    n=0x7fffa4096f30, range=...) at ../app/node/traverser.cpp:76
#8  0x00000000006535f0 in olive::NodeTraverser::GenerateBlockTable (this=0x7fffabffe3f0, 
    track=<optimised out>, range=...) at ../app/node/traverser.cpp:99
#9  0x0000000000652e2d in olive::NodeTraverser::GenerateTable (this=0x7fffabffe3f0, 
    n=0x7fffa40943b0, range=...) at ../app/node/traverser.cpp:70
#10 0x0000000000653586 in olive::NodeTraverser::GenerateTable (this=this@entry=0x7fffabffe3f0, 
    n=0x7fffa40943b0, in=..., out=...) at ../app/node/traverser.cpp:88
#11 0x000000000062b7f2 in olive::ViewerOutput::VerifyLength (this=0x7fffa4028210)
    at ../app/common/rational.h:40
--Type <RET> for more, q to quit, c to continue without paging--c
#12 0x000000000062f250 in olive::ViewerOutput::InvalidateCache (this=0x7fffa4028210, range=..., from=0x7fffa40a11a0, source=0x7fffa40a11a0) at ../app/node/output/viewer/viewer.cpp:133
Backtrace stopped: Cannot access memory at address 0x7fffabffe518
(gdb) bt
#0  0x0000000000651e12 in olive::NodeTraverser::PostProcessTable (this=0x7fffabffe3f0, 
    node=<error reading variable: Cannot access memory at address 0x7fffabffdd50>, range=..., 
    output_params=...) at ../app/node/traverser.cpp:194
#1  0x0000000000652e7d in olive::NodeTraverser::GenerateTable (this=0x7fffabffe3f0, 
    n=0x7fffa40966b0, range=...) at ../app/node/traverser.cpp:81
#2  0x0000000000653049 in olive::NodeTraverser::ProcessInput (this=0x7fffabffe3f0, 
    input=0x7fffa4005cd0, range=...) at ../app/node/traverser.cpp:53
#3  0x000000000065318c in olive::NodeTraverser::GenerateDatabase (this=0x7fffabffe3f0, 
    node=0x7fffa4076900, range=...) at ../app/node/traverser.cpp:41
#4  0x0000000000652e59 in olive::NodeTraverser::GenerateTable (this=0x7fffabffe3f0, 
    n=0x7fffa4076900, range=...) at ../app/node/traverser.cpp:76
#5  0x0000000000653049 in olive::NodeTraverser::ProcessInput (this=0x7fffabffe3f0, 
    input=0x7fffa4027f40, range=...) at ../app/node/traverser.cpp:53
#6  0x000000000065318c in olive::NodeTraverser::GenerateDatabase (this=0x7fffabffe3f0, 
    node=0x7fffa4096f30, range=...) at ../app/node/traverser.cpp:41
#7  0x0000000000652e59 in olive::NodeTraverser::GenerateTable (this=0x7fffabffe3f0, 
    n=0x7fffa4096f30, range=...) at ../app/node/traverser.cpp:76
#8  0x00000000006535f0 in olive::NodeTraverser::GenerateBlockTable (this=0x7fffabffe3f0, 
    track=<optimised out>, range=...) at ../app/node/traverser.cpp:99
#9  0x0000000000652e2d in olive::NodeTraverser::GenerateTable (this=0x7fffabffe3f0, 
    n=0x7fffa40943b0, range=...) at ../app/node/traverser.cpp:70
#10 0x0000000000653586 in olive::NodeTraverser::GenerateTable (this=this@entry=0x7fffabffe3f0, 
    n=0x7fffa40943b0, in=..., out=...) at ../app/node/traverser.cpp:88
#11 0x000000000062b7f2 in olive::ViewerOutput::VerifyLength (this=0x7fffa4028210)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../app/common/rational.h:40
#12 0x000000000062f250 in olive::ViewerOutput::InvalidateCache (this=0x7fffa4028210, range=..., 
    from=0x7fffa40a11a0, source=0x7fffa40a11a0) at ../app/node/output/viewer/viewer.cpp:133
Backtrace stopped: Cannot access memory at address 0x7fffabffe518
(gdb) </code></pre></details>

**Additional Information**

**Comment by Simran-B** [comment]
Please use and fill out an issue template. Updated above.

**Comment by Corvus69** [comment]
I think this is https://github.com/olive-editor/olive/issues/1456

**Comment by itsmattkc** [comment]
Can you test this with a new project file on the latest commit?

**Comment by itsmattkc** [comment]
Merging into #1456 since I believe it was the same bug.
