### ISSUE TITLE
[PLAYBACK] the video does not appear on the preview screen 

### ISSUE THREAD

**Issue by efaisalr** [olive-editor/olive#1470]
![Screenshot from 2021-01-20 21-33-29](https://user-images.githubusercontent.com/72137594/105189213-4efe9b80-5b67-11eb-944d-5421a2e593e1.png)
![Screenshot from 2021-01-20 21-34-21](https://user-images.githubusercontent.com/72137594/105189245-58880380-5b67-11eb-8b55-61a166c76f0b.png)

**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**

**Comment by Simran-B** [comment]
Please fill out the issue template and don't forget to include the video driver.

**Comment by efaisalr** [comment]
maybe this is what you mean, and sorry I do not understand the template you mean
![Screenshot from 2021-01-20 22-03-52](https://user-images.githubusercontent.com/72137594/105194098-d221f080-5b6b-11eb-9c8c-f2a3b965294f.png)

**Comment by efaisalr** [comment]
can you show the location where the tamplate is

**Comment by Simran-B** [comment]
Edit your initial post and fill out the fields that are pre-defined:

- Commit Hash
- Platform
- Summary
- Additional Information / Output

**Comment by Simran-B** [comment]
@efaisalr Updated the initial post for you, but still, we cannot help without further information. In particular, what does Olive log to standard output? Start it from a terminal, try to play back some a sequence and post the entire terminal output here. Also, what OpenGL versions does your graphics chip and driver support?

**Comment by Simran-B** [comment]
Olive requires OpenGL 3.2 Core profile, so that explains it. You will need newer graphics hardware (or run in software mode, but that's super slow).

**Comment by efaisalr** [comment]
Oke Thank you for the information
