### ISSUE TITLE
[CRASH] 4k video crash

### ISSUE THREAD

**Issue by t02143** [olive-editor/olive#1473]
**Commit Hash** 

4k video problem

**Platform** 

Ubuntu 20.04

**Summary**

Crashes when saving 4k video (29.97 fps, bitrate 100) after cutting the video shorter.

**Steps to Reproduce**

1. Upload 4K video
2. Cut out middle part, remove flanks 
3. Exprort mp4, original video quality

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**

**Comment by mcDandy** [comment]
no commit hash, backtrace could be handy, but little people know how to use gdb.
