### ISSUE TITLE
Rich Text: Center alignment gets lost when pasting a text in edit text from a previous window

### ISSUE THREAD

**Issue by UdoLauer** [olive-editor/olive#1478]
When pasting a copied center aligned rich text into a new rich text edit window the center alignment gets lost

![richtext](https://user-images.githubusercontent.com/51811688/106543870-dbfe0900-6506-11eb-8db4-d2f05f8c0c01.png)

![richtext2](https://user-images.githubusercontent.com/51811688/106543885-e28c8080-6506-11eb-9266-d3959b2d0361.png)

**Comment by AngeloFrancabandiera** [comment]
Are you using version 0.1 or 0.2? In new builds I can't even pop out the window you have posted.

**Comment by Simran-B** [comment]
It is clearly 0.1, which is unsupported: #1175

0.2 looks like this and does not support text alignment so far, even if you paste it from another program (all text ends up centered):

![image](https://user-images.githubusercontent.com/7819991/107029300-17bafc00-67af-11eb-9b57-aefdd6c7b273.png)
