### ISSUE TITLE
Issues with Scale

### ISSUE THREAD

**Issue by ZERICO2005** [olive-editor/olive#1479]
1. Setting the scale to a negative number will cause the program to crash in

**Comment by ZERICO2005** [comment]
1. Setting the scale to a negative number, even for a moment will cause Olive to crash, I didn't get a backup file, although that may be because the scene was only open for 3 minutes. 
2. Selecting two or more video clips and changing their Scales in the parameter editor won't do anything, meaning I have to change the Scale for each video clip one at a time

Version: Olive 0.2.0-19eabf28

**Comment by elsandosgrande** [comment]
@ZERICO2005 

1. Do not bypass the templates, period. Also, when using them, you must provide all of the information requested.
2. You must open two separate tickets for those two issues because they are separate issues.
