### ISSUE TITLE
Can't load files in folder named in cyrillic

### ISSUE THREAD

**Issue by Guliath** [olive-editor/olive#1481]
**Commit Hash** 

**Platform**  Windows 10 

**Summary**

**Additional Information / Output**

[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing custom cursors (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[INFO] Matched "??? ?????? - ?????? ?????.mp4" with absolute path (:0, )
[INFO] Matched "???????????.mp4" with absolute path (:0, )
[INFO] Matched "????/???????.mp4" with absolute path (:0, )
[INFO] Matched "???????/???11?.mp4" with absolute path (:0, )
[INFO] Matched "???????/??????????_10?_11?.mp4" with absolute path (:0, )
[INFO] Matched "../Roller Coaster.wav" relative to project's internal directory (:0, )
[INFO] Matched "video-54b4d13d29c59c1722e362893eb7cba9-V.mp4" with absolute path (:0, )
[WARNING] QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) (:0, )
[INFO] Clip opened on track 1 (took 0 ms) (:0, )
[INFO] Clip opened on track -1 (took 41 ms) (:0, )

**Comment by elsandosgrande** [comment]
@Guliath You need to provide all of the information that is requested in the issue template. Also, this could be related to https://github.com/olive-editor/olive/issues/1287, but we can't know for sure without more information.

**Comment by Simran-B** [comment]
A crash because of non-ASCII characters in the path to the OCIO config file would occur earlier from what I've seen, but I can't say for sure. There could be another general issue with Unicode characters or incorrect usage of a wchar_t Windows API. It would surprise me if Qt is responsible for this however.

**Comment by itsmattkc** [comment]
This is 0.1 console output. Reply back if you can recreate this issue in 0.2.
