### ISSUE TITLE
[CRASH] 

### ISSUE THREAD

**Issue by danthebanan** [olive-editor/olive#1488]
**Commit Hash** 

**Platform** 

**Summary**

olive keeps crashing whenever i try to open my project.

it says:
EXCEPTION_ACCESS_VIOLATION_READ
0x12214d564bc

**Steps to Reproduce**

1. open olive
2. go to open project
3. open a project

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
i need help

**Comment by AGI-THB** [comment]
Fill out the Issue Template.

Upload a BackTrace or a core file.

**Comment by itsmattkc** [comment]
Can you test this with a new project file on the latest commit?

**Comment by itsmattkc** [comment]
Merging into #1456 since I believe it was the same bug.
