### ISSUE TITLE
[EDIT] Title is not showing at all. All black

### ISSUE THREAD

**Issue by arindam-giri** [olive-editor/olive#1496]
**Commit Hash** 
19eabf28

**Platform** 
KDE Neon - Plasma 5.21

**Summary**
I am using the Olive 0.2.0 [19eabf28] AppImage in KDE Neon 5.21 Plasma

Imported a sample mp4 video
Then added Add -> Title 

But the Title is not showing at all. 

See screenshot below.

Am I doing something wrong? Or it is a bug?

![ksnip_20210224-002134](https://user-images.githubusercontent.com/18495475/108893210-d6dc3780-7636-11eb-8168-83097c0313e7.png)

**Additional Information / Output**
I even tried to add the only title in a new project. It's all black in preview. Nothing is showing.

**Comment by itsmattkc** [comment]
Does this issue still occur on the latest commit?

**Comment by arindam-giri** [comment]
Yes. 
![Workspace 1_017](https://user-images.githubusercontent.com/18495475/111902912-9faa4c00-8a65-11eb-8343-f961f557c63d.jpg)

**Comment by itsmattkc** [comment]
I'm afraid I can't recreate this. Can you provide console output?

**Comment by arindam-giri** [comment]
debugpoint@debugpoint-ubuntu:~/Downloads$ ./Olive-84c227c0-Linux-x86_64.AppImage 
[WARNING] Trying to use locale "en_US" but couldn't find a translation for it ((null):0)
[WARNING] Node "org.olivevideoeditor.Olive.time" has no inputs ((null):0)
[DEBUG] Extracting default OCIO config to "/home/debugpoint/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.12.8 ((null):0)
[DEBUG] Using graphics driver: Intel ((null):0)
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1f.3.analog-stereo" ((null):0)
[WARNING] Failed to set name of parameter "track_in_0" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)
[WARNING] Failed to set name of parameter "track_in_1" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)
[WARNING] Failed to set name of parameter "track_in_2" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[swscaler @ 0x7f184813ffc0] Warning: data is not aligned! This can lead to a speed loss
[INFO] Setting output audio device to "alsa_output.pci-0000_00_1f.3.analog-stereo" ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[DEBUG] Removing an empty arena ((null):0)
[DEBUG] No arenas, creating new... ((null):0)

**Comment by arindam-giri** [comment]
Here's a video of the issue..
This is on Ubuntu 20.04 LTS

https://user-images.githubusercontent.com/18495475/111914900-f0d43300-8a99-11eb-925b-9e90f2d0155b.mp4
