### ISSUE TITLE
[BUILD] Can we just get it the latest commit to build

### ISSUE THREAD

**Issue by abdulbadii** [olive-editor/olive#1497]
**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**
Just simply asking

As on instruction "Compiling Olive 0.2"
can we just get it the latest commit to build as correctly as the grabbed all build, so is:

`git clone --depth 1 https://github.com/olive-editor/olive`
just as fine as the common `git clone https`...  ?
I found `git clone --depth 1 https://github.com/AcademySoftwareFoundation/OpenColorIO.git` builds fine

Then error from olive configuring:
...
```
-- Found OpenColorIO: /usr/local/lib/libOpenColorIO.so.2.0 (found suitable version "2.0.0", minimum required is "2.0.0") 
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenImageIO: Found unsuitable version "2.0.5", but required
  is at least "2.1.12" (found usr/lib/x86_64-linux-gnu/libOpenImageIO.so;/usr/lib/x86_64-linux-gnu/libOpenImageIO_Util.so)

```
...
But on Debian buster having no any bleeding edge version of package, how can we solve this?
Where can we put its deps separated and make olive just like portable app put in container (here all big apps are on its own partition **/opt**)

**Comment by Simran-B** [comment]
The automated Linux builds are available as AppImages:
https://olivevideoeditor.org/nightly.php

I'm not sure what exact version of OpenImageIO is bundled, but you can try to use the .so files of the AppImage by extracting it:

    Olive-<version>.AppImage --appimage-extract

The libraries will be in squashfs-root/usr/lib IIRC. I suppose CMake will pick them up if you prepend the lib path to `LD_LIBRARY_PATH`, but there might be other ways.

The Linux CI uses a CentOS container, so you might wanna check that out:
https://github.com/olive-editor/olive/blob/master/.github/workflows/ci.yml
https://github.com/olive-editor/olive/tree/master/docker

**Comment by abdulbadii** [comment]
Thanks much
