### ISSUE TITLE
[BUILD] CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137: Could NOT find OpenGL..

### ISSUE THREAD

**Issue by abdulbadii** [olive-editor/olive#1500]
**Commit Hash** 
**f7c6de31**

**Platform** 
**Debian Stable buster (MX Linux)**

**Summary**
From clean olive cloning, mkdir build, then
```
$ sudo cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenGL (missing: OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR)

```
And these installed:
```

$ sudo apt install libopengl-dev
...
libopengl-dev is already the newest version (1.3.2-1~mx19ahs+

$ sudo apt install  libgl1-mesa-dev
...
libgl1-mesa-dev is already the newest version (20.1.8-1~mx19ahs+1)
```
Where's the mistake, how to solve it ?

**Comment by Simran-B** [comment]
It looks like you are missing GLX  Try to install `libgl1-mesa-glx` as well. Or maybe it's `libglx-dev`, not sure.

If you still receive an error about missing OPENGL_INCLUDE_DIR, then you are either missing additional packages or the files are in a non-standard location where CMake doesn't pick them up.

Some posts on the internet suggest that this package might be needed: `mesa-common-dev`. You might have to install the following two before you can install it: `libx11-dev libdrm-dev`.

**Comment by abdulbadii** [comment]
I almost frustrated, please help only this I could give
```
$ glxinfo | grep -n 'version string'

5:server glx version string: 1.4
19:client glx version string: 1.4
74:OpenGL core profile version string: 4.5 (Core Profile) Mesa 20.1.8
75:OpenGL core profile shading language version string: 4.50
178:OpenGL version string: 4.5 (Compatibility Profile) Mesa 20.1.8
179:OpenGL shading language version string: 4.50
311:OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.8
312:OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by Simran-B** [comment]
It seems to look for `GL/gl.h`:

https://github.com/Kitware/CMake/blob/master/Modules/FindOpenGL.cmake#L210-L214

Do you have that header file in a folder GL at one of the following locations?

- /usr/share/doc/NVIDIA_GLX-1.0/include
- /usr/openwin/share/include
- /opt/graphics/OpenGL/include

**Comment by abdulbadii** [comment]
MX Linux its mesa-common-dev in its repo has no gl.h (shame!)
and somehow it missed, so this solve:
`$ sudo apt reinstall libgl-dev`
