### ISSUE TITLE
[BUILD] Unmet dependencies on MX Linux

### ISSUE THREAD

**Issue by abdulbadii** [olive-editor/olive#1503]
**Commit Hash** 
f7c6de31

**Platform**
Debian Stable (MX Linux)

**Summary**
some unmet deps. such as encountering:
```
Could NOT find OpenImageIO: Found unsuitable version "2.0.5", but required
  is at least "2.1.12"
```
if we're to install from Debian main Testing should we get the dynamic/run-time or the static (-dev) package?

What'd be thumb rule here to easily decide whether it'd be one or the other.

**Comment by Simran-B** [comment]
Runtime libraries (.so) alone are insufficient in most if not all cases. Olive needs to be linked against them, which requires their header files. How you obtain the correct dependency versions is up to you. You can compile them yourself if there are no packages.

**Comment by abdulbadii** [comment]
Di you really mean olive is statically compiled and not having e.g.
` void* handle = dlopen("libopenimageio.so"` ...
`dlsym(handle,`  ... ?

**Comment by Simran-B** [comment]
Oh, I misunderstood your question. Olive uses dynamic linking, not dynamic loading or static linking. But it's possible that CMake would equally accept .a in some cases and automatically link it statically. It's not something we actively do however.

**Comment by abdulbadii** [comment]
God bless you, amen
