### ISSUE TITLE
[CRASH] SIGABRT on attempt to add a transition between two clips

### ISSUE THREAD

**Issue by mara004** [olive-editor/olive#1506]
**Commit Hash** 
a57bf35e

**Platform** 
KDE Neon 5.21 (based on Ubuntu 20.04)
Qt 5.15.2
Graphics platform: Wayland

**Summary**
Olive crashes on the attempt to add a transition between two clips

**Steps to Reproduce**

1. add two clips next to each other
2. choose the transitions tool from the toolbox
3. click between the two clips
4. drag the mouse cursor to set the duration of the transition
-> crash on left mouse button release

<details><summary><strong>Backtrace</strong></summary><pre><code>

[New Thread 0x7fff5e53d700 (LWP 9473)]
[New Thread 0x7fff5dd3c700 (LWP 9474)]
[New Thread 0x7fff5d53b700 (LWP 9475)]
[New Thread 0x7fff5cd3a700 (LWP 9476)]
[New Thread 0x7fff57fff700 (LWP 9477)]
[DEBUG] No arenas, creating new... (olive::MemoryPool<T>::ElementPtr olive::MemoryPool<T>::Get() [with T = unsigned char; olive::MemoryPool<T>::ElementPtr = std::shared_ptr<olive::MemoryPool<unsigned char>::Element>]:336)
[DEBUG] Removing an empty arena (void olive::MemoryPool<T>::ArenaIsEmpty(olive::MemoryPool<T>::Arena*) [with T = unsigned char]:373)
[Thread 0x7fff5e53d700 (LWP 9473) exited]
[Thread 0x7fff5dd3c700 (LWP 9474) exited]
[Thread 0x7fff5d53b700 (LWP 9475) exited]
[Thread 0x7fff57fff700 (LWP 9477) exited]
[Thread 0x7fff5cd3a700 (LWP 9476) exited]
[FATAL] ASSERT: "connected_out_block_->type() != Block::kTransition && !connected_out_block_->out_transition() && connected_out_block_ == this->previous()" in file /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/node/block/transition/transition.cpp, line 258 ((null):258)

Thread 1 "olive-editor" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff34ee859 in __GI_abort () at abort.c:79
#2  0x00007ffff3a98be7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff3a97ff3 in qt_assert_x(char const*, char const*, char const*, int) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00005555558dbfca in olive::TransitionBlock::InputConnectedEvent(QString const&, int, olive::NodeOutput const&) (this=
    0x55555aacbbf0, input=..., element=-1, output=...) at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/node/block/transition/transition.cpp:258
#5  0x0000555555913d56 in olive::Node::ConnectEdge(olive::NodeOutput const&, olive::NodeInput const&) (output=..., input=...)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/node/node.cpp:282
#6  0x0000555555a1cb35 in olive::NodeEdgeAddCommand::redo() (this=0x55555aaab250)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/widget/nodeview/nodeviewundo.cpp:50
#7  0x00005555559bab25 in olive::UndoCommand::redo_and_set_modified() (this=0x55555aaab250)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/undo/undocommand.cpp:43
#8  0x00005555559baa27 in olive::MultiUndoCommand::redo() (this=0x55555abcff00)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/undo/undocommand.cpp:30
#9  0x00005555559bab25 in olive::UndoCommand::redo_and_set_modified() (this=0x55555abcff00)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/undo/undocommand.cpp:43
#10 0x00005555559bb5b9 in olive::UndoStack::push(olive::UndoCommand*) (this=0x7fffffffda88, command=0x55555abcff00)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/undo/undostack.cpp:59
#11 0x0000555555a6407c in olive::TransitionTool::MouseRelease(olive::TimelineViewMouseEvent*) (this=0x555558f022e0, event=0x7fffffffcad0)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/widget/timelinewidget/tool/transition.cpp:171
#12 0x0000555555a6edb2 in olive::TimelineWidget::ViewMouseReleased(olive::TimelineViewMouseEvent*) (this=0x555558b22680, event=0x7fffffffcad0)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/widget/timelinewidget/timelinewidget.cpp:788
#13 0x0000555555a80be1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<olive::TimelineViewMouseEvent*>, void, void (olive::TimelineWidget::*)(olive::TimelineViewMouseEvent*)>::call(void (olive::TimelineWidget::*)(olive::TimelineViewMouseEvent*), olive::TimelineWidget*, void**) (f=
    (void (olive::TimelineWidget::*)(class olive::TimelineWidget * const, class olive::TimelineViewMouseEvent *)) 0x555555a6ed32 <olive::TimelineWidget::ViewMouseReleased(olive::TimelineViewMouseEvent*)>, o=0x555558b22680, arg=0x7fffffffca90) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
#14 0x0000555555a8001a in QtPrivate::FunctionPointer<void (olive::TimelineWidget::*)(olive::TimelineViewMouseEvent*)>::call<QtPrivate::List<olive::TimelineViewMouseEvent*>, void>(void (olive::TimelineWidget::*)(olive::TimelineViewMouseEvent*), olive::TimelineWidget*, void**) (f=
    (void (olive::TimelineWidget::*)(class olive::TimelineWidget * const, class olive::TimelineViewMouseEvent *)) 0x555555a6ed32 <olive::TimelineWidget::ViewMouseReleased(olive::TimelineViewMouseEvent*)>, o=0x555558b22680, arg=0x7fffffffca90) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
#15 0x0000555555a7e9c0 in QtPrivate::QSlotObject<void (olive::TimelineWidget::*)(olive::TimelineViewMouseEvent*), QtPrivate::List<olive::TimelineViewMouseEvent*>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x555558f05ab0, r=0x555558b22680, a=0x7fffffffca90, ret=0x0)
    at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
#16 0x00007ffff3cf06be in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x000055555583076a in olive::TimelineView::MouseReleased(olive::TimelineViewMouseEvent*) (this=0x555558ec3b50, _t1=0x7fffffffcad0)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/debugbuild/app/olive-editor_autogen/EYCRI7KD7O/moc_timelineview.cpp:229
#18 0x0000555555a656ea in olive::TimelineView::mouseReleaseEvent(QMouseEvent*) (this=0x555558ec3b50, event=0x7fffffffd0f0)
    at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/widget/timelinewidget/view/timelineview.cpp:105
#19 0x00007ffff47d5c06 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff4885f82 in QFrame::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff4af8aa1 in QGraphicsView::viewportEvent(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff3cb9403 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff4792db2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff479be77 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff3cb969a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff479b0a7 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff47f0e54 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff47f4174 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff4792dc3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff479bbb8 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff3cb969a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff409b4e8 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#33 0x00007ffff409cb55 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#34 0x00007ffff40747ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#35 0x00007fffd5a0e814 in  () at /lib/x86_64-linux-gnu/libQt5WaylandClient.so.5
#36 0x00007ffff1dabf9d in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff1dac220 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff1dac2c3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff3d13fa2 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007ffff3cb81ab in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007ffff3cc0354 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x000055555586196d in main(int, char**) (argc=1, argv=0x7fffffffdc58) at /home/manuel/Downloads/builds/Nodearch-Olive/olive/app/main.cpp:184

</code></pre></details>

**Additional Information**
generally reproducable

**Comment by itsmattkc** [comment]
Merging into #1522 as general transition issues.
