### ISSUE TITLE
[RENDER] Wayland: Window below is visible in the preview rendering (+ artifacts and flickering)

### ISSUE THREAD

**Issue by mara004** [olive-editor/olive#1507]
**Commit Hash** 
a57bf35e

**Platform** 
KDE Neon 5.21 (based on Ubuntu 20.04)
Qt 5.15.2
Graphics platform: Wayland only

**Summary**
On Wayland, the preview rendering works badly because parts of the window / wallpaper below are visible, and rendering is very flickery. Also, when resizing the panel, there are all kinds of artifacts and wrong content in the preview.

**Additional Information / Output**
Initially, I belived this to be an issue with `kwin` and filed a bug report at kde since I also had similar problems with other apps (https://bugs.kde.org/show_bug.cgi?id=433484), but they say it would be a common that needs to be addressed in the client applications, and they offered to help fixing it.

**Screenshots of the bug**
![Olive 0 2 x](https://user-images.githubusercontent.com/65915611/109795632-71301280-7c17-11eb-8a40-f83920f384d1.png)
![Olive 0 2 x II](https://user-images.githubusercontent.com/65915611/109795634-71c8a900-7c17-11eb-9b0e-1c86eedb83b6.png)

**Comment by Simran-B** [comment]
How strange. OBS removed `native="true"` from `<widget>` elements in their .ui files, which doesn't apply for us. But they also set `setAttribute(Qt::AA_DontCreateNativeWidgetSiblings);` on init (and revert it with `setAttribute(Qt::WA_NativeWindow)` for the browser source because the global option breaks something).

The [KDE fix](https://invent.kde.org/graphics/gwenview/commit/7ed543b53a9fb6d11ef95e439425ed71f952e66b) was to move from the deprecated `QGLWidget` to `QOpenGLWidget`, but we already use the latter. However, they also removed `OpenGL` from CMake's `find_package()` and `Qt5::OpenGL` from `target_link_libraries()` - not sure if this applies to us.

**Comment by mara004** [comment]
Hmm... Then it may be a different problem with Olive, indeed the behaviour is also a bit different from the other applications: While the content of the frames in OBS and Gwenview was completely invisible, the content in Olive is, though the window from behind is still visible in the place where no footage is.

**Comment by mara004** [comment]
What I find particularly interesting/suspicious is that on screenshot two, the Konsole terminal window from behind has adapted Olive's theme - my normal background is entirely black instead of grey.

**Comment by Simran-B** [comment]
@mara004 I added the `setAttribute()` call in #1528, GCC build:
https://github.com/olive-editor/olive/suites/2323475490/artifacts/48890317

Can you compare that to the latest [nightly build](https://olivevideoeditor.org/nightly.php) and report if it fixes the Wayland issue, please?

**Comment by mara004** [comment]
> @mara004 I added the `setAttribute()` call in #1528, GCC build:
> https://github.com/olive-editor/olive/suites/2323475490/artifacts/48890317
> 
> Can you compare that to the latest [nightly build](https://olivevideoeditor.org/nightly.php) and report if it fixes the Wayland issue, please?

I checked out from git and rebuilt. It did not fix the issue.

**Comment by Simran-B** [comment]
Ah, right. Linuxdeployqt doesn't include the Wayland plugin even though it is available in the build environment. That's something for #1487.

You checked out and built the `wayland-ui-issues` branch, right? Can you pull and build again? I applied the change that KDE did (not link Qt's OpenGL).

**Comment by mara004** [comment]
Initially yes, but I already switched back to master and rebuilt in the meantime. Lapse. Can I do it tomorrow?

**Comment by Simran-B** [comment]
Anytime is fine, really. If the OpenGL change makes a difference then we will need to test this on other platforms to confirm that it doesn't have negative effects on them. So this will take some time either way.

**Comment by mara004** [comment]
Thanks. I've just tried the current `wayland-ui-issues`, but unfortunately, it's still the same problem.

**Comment by Simran-B** [comment]
> The AppImages are useless for testing because they only support xcb (XWayland):

I checked our Qt 5 package but it doesn't seem to come with Qt Wayland

https://github.com/AcademySoftwareFoundation/aswf-docker/blob/37304c0ec6190b3f316d364ed81ff29a30608bd5/scripts/base/build_qt.sh#L31-L43

I guess we need to add `-feature-wayland-server` when configuring Qt and create our own package to support it in our CI. Or build just the qtwayland module separately and add it to the build image...
https://stackoverflow.com/questions/42352743/how-to-build-qtwayland

---

Anyway, we need to find a fix for the visual glitches.
@mara004 Shall I post an update to the KDE bug or do you want to continue the thread? At the moment it's completely unclear what we need to change and we need further suggestions.

**Comment by mara004** [comment]
@Simran-B Perhaps it's better if you could update the bug because you know the Olive code and I don't

**Comment by elsandosgrande** [comment]
@Simran-B As long as the `qtwayland` Git submodule is cloned and subsequently built, the Wayland QPA module should be there (I only needed to specifically mention XCB when configuring Qt for building because it doesn't get built by default for whatever reason). I don't see `init-repository` being run anywhere in that script, so I can't tell which submodules are being cloned.

**Comment by Simran-B** [comment]
They use the "Qt Everywhere" source code package:
https://download.qt.io/official_releases/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz
Qt Wayland is available separately:
https://download.qt.io/official_releases/qt/5.15/5.15.2/submodules/qtwayland-everywhere-src-5.15.2.tar.xz
I wonder if this is merely a source code distribution omitting the Git history and if it works the same otherwise...

**Comment by elsandosgrande** [comment]
> They use the "Qt Everywhere" source code package:

Where in the repository is this mentioned? I'd like to see if there's something that could be done there (presuming that the CI system doesn't just download a ready-build image of Qt from the ASFW).

**Comment by Simran-B** [comment]
@elsandosgrande We copy `aswftesting/ci-package-qt:2021` from Docker Hub into our build image,
[docker/ci-olive/Dockerfile](https://github.com/olive-editor/olive/blob/0cd40028d998fbd986344cd4eea3c892e5bc649a/docker/ci-olive/Dockerfile#L18) line 18 and 50. Download of qt-everywhere in aswf-docker: [scripts/base/build_qt.sh](https://github.com/AcademySoftwareFoundation/aswf-docker/blob/37304c0ec6190b3f316d364ed81ff29a30608bd5/scripts/base/build_qt.sh#L25) line 25.
The single package actually contains all submodules as far as I can see. Should only be a matter of adding extra arguments, but we would need to build our own Qt image.

**Comment by mara004** [comment]
I just checked out the `wayland-ui-issues` branch and rebuilt, but it's still not fixed, unfortunately. It's exactly the same as before. I can yet try witout #1528, but I think it's unlikely this changes anything.

**Comment by Simran-B** [comment]
Thanks @mara004, if it's broken in the Wayland branch then there's no point in testing the master branch. I'll try to get more information from the KDE guys.

**Comment by elsandosgrande** [comment]
For reference, the Sequence and Footage viewers being transparent is also a thing on GNOME, but it's a lot harder to notice (only black stuff doesn't get completely washed out):

![image](https://user-images.githubusercontent.com/40576902/116009494-5f1c9000-a61a-11eb-9d6d-304b16ba2b53.png)

![image](https://user-images.githubusercontent.com/40576902/116009500-66439e00-a61a-11eb-90eb-49cb1f0424ef.png)


The texture which shows what's in the timeline being mishandled, which is what I'm presuming is the case, definitely seems like a KDE bug then, at least in some way (maybe not strictly, but it's still a bug that only seems to appear on KDE).

**Comment by mara004** [comment]
@elsandosgrande Interesting. How is it if you resize or maximize a viewer panel (then I get the most artifacts)?

**Comment by elsandosgrande** [comment]
@mara004 I'm currently having a build issue, but I'll get back to you once all of the build subtypes can be built (mainly just different compiler flags).

**Comment by mara004** [comment]
JFYI, I found another app/framework with similar problems: NodeGraphQt for PySide: https://github.com/jchanvfx/NodeGraphQt/issues/207

**Comment by davidedmundson** [comment]
Please include output of 
WAYLAND_DEBUG=1 olive

**Comment by mara004** [comment]
Have fun!
[olive_wayland_log.txt](https://github.com/olive-editor/olive/files/6397820/olive_wayland_log.txt)

I redirected the output to a file (`WAYLAND_DEBUG=1 ./olive-editor &> ~/olive_wayland_log.txt`) as it was so much output.

**Comment by elsandosgrande** [comment]
@mara004 Resizing the widget made no difference: 
![image](https://user-images.githubusercontent.com/40576902/116624249-ea15c700-a947-11eb-8910-471190c0b773.png)

Once I have more time for doing things other than school assignments which are due either tomorrow or in a few days, I'll try using Olive with `WAYLAND_DEBUG=1`.

**Comment by mara004** [comment]
@davidedmundson Did the debug output contain any helpful information?

**Comment by davidedmundson** [comment]
Debug confirmed it's /not/ the same root cause as faced in that NodeJS link.  Rest of the log looked sensible.

**Comment by mara004** [comment]
Okay. What do you mean by "NodeJS link" ?

**Comment by mara004** [comment]
I just tried to take a look at the [rendering code](https://github.com/olive-editor/olive/blob/master/app/render/opengl/openglrenderer.cpp) but unfortunately my limited Python/PySide knowledege is far from sufficient to understand what is happening; this cpp/opengl code looks quite hairy to me.
Maybe we could ask for help at Qt?

**Comment by itsmattkc** [comment]
Merging all Wayland issues into #1630.
