### ISSUE TITLE
[BUILD] Nightly builds outdated

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#1510]
**Commit Hash** https://github.com/olive-editor/olive/commit/a57bf35e9341e0270a44f748dd8c186531c8252e

**Platform** All supported

**Summary**

Nightly Builds not updated since Dec 30, 2020:

- https://olivevideoeditor.org/nightly.php

**Additional Information / Output**

**Comment by Simran-B** [comment]
It's not outdated. The latest commit on the master branch is 19eabf28 from December.

All recent activity is on a feature branch with a PR here:
https://github.com/olive-editor/olive/pull/1476
The last successful CI run of that branch is currently https://github.com/olive-editor/olive/actions/runs/609100387 with artifacts attached.
