### ISSUE TITLE
[CRASH] The program does not open *.ove files and closes

### ISSUE THREAD

**Issue by Karamellzweig** [olive-editor/olive#1514]
**Commit Hash** 0x16c38bce21c 

**Platform** Windows 10

**Summary** I don't know at all how to use this template, if I did something wrong, I'm sorry. So: I saved the file in .ove format and then in .otio (the same). The program terminated so I figured it was normal after saving. Then I wanted to open these files, but with the .ove extension, the program only started for a moment, then it shut down and a window appeared with the possibility of reporting an error. I wrote what I was supposed to write, I click "send report", another window pops up with the information that the report cannot be sent. Okay, maybe I'll open the second file? Yes, it did open but showed no content. Is it still possible to recover the option to edit these files in Olive? I like this program very much and I don't have any other problems.

**Steps to Reproduce**

1. 
2. 
3. 

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
![Olive 18 03 2021 16_25_21](https://user-images.githubusercontent.com/80907592/111651636-b1da7f00-8806-11eb-9518-02523189214b.png)
Is it possible to add a filter to a single part of the video, not the whole? I searched but did not find.

**Comment by itsmattkc** [comment]
Can you provide these files?

We're still shifting things around with the project format so the *.ove file may not load, but the *.otio file should.

**Comment by itsmattkc** [comment]
Merging into #1456 since I believe it was the same bug.
