### ISSUE TITLE
[NODES] Setting colorspace messes with footage timebase

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1518]
**Commit Hash** 
1c7509e767075ac724cfc0cc906142382e247271

**Platform** 
Any

**Summary**
Changing the colorspace seems to invariable set the footage timebase to 10 FPS.

**Additional Information / Output**
Recent regression, should be a quick fix.

**Comment by ThomasWilshaw** [comment]
Doesn't happen with all footage, the Arri test stuff is fine.

**Comment by ThomasWilshaw** [comment]
Also I don't think it's just colour space, it seems to be any change to the footage node parameters.

**Comment by itsmattkc** [comment]
Should be fixed as of bb32048c653a86371e26f891576bee4b362a5ea6
