### ISSUE TITLE
[CACHE] Long sequences cause UI lag when caching

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1519]
**Commit Hash** 
1c7509e767075ac724cfc0cc906142382e247271

**Platform** 
Any.

**Summary**
The longer a sequence is, the more time each frame takes to cache. This is particularly noticeable with sequences that are 2+ hours long.

**Additional Information / Output**
Likely some kind of "frame list" or something that's getting iterated every time a frame is cached that naturally scales poorly as the number of frames increases. Should be simple to track down and fix.

**Comment by elSolus** [comment]
I faced that in the latest build on July 21.

**Comment by morrolinux** [comment]
If you edit at 60fps a 5+ minute timeline is enough to slow the entire playback down on an 8th gen Intel laptop

**Comment by itsmattkc** [comment]
Sounds like that's probably a different issue, this is specifically regarding caching, not playback

**Comment by itsmattkc** [comment]
I believe all frame-related slowdowns have been solved. There are some audio-related ones now, but I think those should be tracked in #1742
