### ISSUE TITLE
[NODES] Changing sequence settings doesn't invalidate cache

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1520]
**Commit Hash** 
1c7509e767075ac724cfc0cc906142382e247271

**Platform** 
Any.

**Summary**
Changing sequence parameters either in the sequence dialog or the parameter editor fails to signal a re-cache.

**Additional Information / Output**
Recent regression. Should be simple to track down and fix.

**Comment by Simran-B** [comment]
Could this be related to #1480?

**Comment by itsmattkc** [comment]
Don't think so, this was simply a regression from `nodearchchanges` where an invalidate call was missing, not a crash. Though I do suspect that crash will be fixed following the rewrite.
