### ISSUE TITLE
[EDIT] Transition "clip" disappears and doesn't work

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1522]
**Commit Hash** 
1c7509e7

**Platform** 
macOS 10.14.16

**Summary**
When adding a transition to a video, it disappears and doesn't work in the preview window the video is self explanatory:

https://user-images.githubusercontent.com/5942369/111987181-27986080-8b0f-11eb-8211-3504b8fdcccf.mp4

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Known issue, recent regression. Should be fixed soon.

**Comment by pgilfernandez** [comment]
Nice, thanks.

As in 2d420dec, now I can see the clip in the timeline but it renders in black. I guess you are aware of it, but just in case ;)

Cheers

**Comment by rcfoyn** [comment]
In Olive 0.2.0-72669761 (latest build as of now?), when adding Cross Dissolve between two clips, all I get is blackness. 19 days it "should be fixed soon". Isn't this like one of the most common features? Any idea when the issue will be addressed?

**Comment by UltraBlackLinux** [comment]
> In Olive 0.2.0-72669761 (latest build as of now?), when adding Cross Dissolve between two clips, all I get is blackness. 19 days it "should be fixed soon". Isn't this like one of the most common features? Any idea when the issue will be addressed?

You should note, that olive does indeed have many high priority problems. 
You can do it yourself, if this isn't quick enough for you.
