### ISSUE TITLE
[CRASH] Olive crashes on import file

### ISSUE THREAD

**Issue by dag-odoo** [olive-editor/olive#1524]
**Commit Hash** Olive 0.2.0-3dae723b

**Platform** Mac OS 10.13 High sierra

**Summary** Olive crashes when importing files

**Steps to Reproduce**

1.  Open Olive
2. Drag and drop or use import
3. Select file to import (HD 1920x1080 or 4K MP4 H264 with codec AAC)
4. Olive crashes

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
I've tried several files (also crashed with WAV import) and also tried GDB but I never got to make olive run using GDB on mac os.

**Comment by itsmattkc** [comment]
I assume this is the official download? I'm afraid I can't recreate this on my end on macOS.

You might need to use LLDB on macOS to get a backtrace?

Do you get a crash report from macOS? That would also be somewhat useful.

**Comment by dag-odoo** [comment]
I used the official download. There was no crash report from mac OS. I'll try with LLDB later today :) .
Forgot to give you the specs: Mac pro 5.1, 12 core x5780, 96GB ram at 1033MHz.

**Comment by dag-odoo** [comment]
Hello, it seems to be a lib problem.

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Olive.app/Contents/MacOS/../Frameworks/libavutil.56.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Olive.app/Contents/MacOS/../Frameworks/libavutil.56.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Process 975 stopped
* thread #32, name = 'Thread (pooled)', stop reason = signal SIGABRT
    frame #0: 0x000000010096d256 dyld`__abort_with_payload + 10
dyld`__abort_with_payload:
->  0x10096d256 <+10>: jae    0x10096d260               ; <+20>
    0x10096d258 <+12>: movq   %rax, %rdi
    0x10096d25b <+15>: jmp    0x10096cab4               ; cerror_nocancel
    0x10096d260 <+20>: retq   
Target 0: (Olive) stopped.

**Comment by dag-odoo** [comment]
And it seems to be linked to this issue https://github.com/PyAV-Org/PyAV/issues/662

**Comment by Simran-B** [comment]
We set ` -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13` for building Olive, but it's CMake only. My guess is that FFmpeg needs to be compiled with an equivalent flag (CFLAG `-mmacosx-version-min=10.3`?) to lower the minimum deployment target version.

**Comment by itsmattkc** [comment]
It's quite possible since those FFmpeg libraries were compiled locally on 10.15. I can ensure a minimum deployment version in the next automated dependency package.

**Comment by itsmattkc** [comment]
Fixed as of 62505456efe6cce1721cef161e5e251ae29591b5
