### ISSUE TITLE
[NODES] Reconnecting Footage-Node to Root-Node doesn't update Project tab

### ISSUE THREAD

**Issue by krischan941** [olive-editor/olive#1529]
**9e4d42da** 

**Ubuntu 20.10** 

**1. Import some footage
2. delete edge from footage-node to root-node (Item vanishes in Project tab)
3. reconnect them --> Item won't appear again in Project tab**

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Duplicate of #1353, Olive perceives it as connecting over the whole array rather than just one element of it.
