### ISSUE TITLE
[UI] Support alternative to Qt::MiddleButton for laptop users

### ISSUE THREAD

**Issue by Simran-B** [olive-editor/olive#1535]
`handmovableview` is hardcoded to MMB for panning the view (e.g. Node Editor), but it's not usable with input methods such as trackpads. Allowing users to remap the button to something else would be an option. Otherwise, another hardcoded key/button combination would also do, but increases the chance of conflicts.

**Comment by itsmattkc** [comment]
The official alternative to MMB is switching to the "hand tool" (H hotkey) and then dragging in any view.

**Comment by Simran-B** [comment]
How did I miss that 😳
Could there be any cases where the hand tool doesn't work? If no, then I guess this issue can be closed.

#1536 is somewhat related: the hand tool doesn't necessarily drag the view around, but also nodes. If there's little free space with a lot of nodes or if the view is zoomed in on a node then it becomes tricky to move the view.

**Comment by itsmattkc** [comment]
The hand tool _should_ work in all scenarios that MMB would since I believe they utilize the same code, but I guess that also means they inherit the same bugs, such as the one you mention

**Comment by Simran-B** [comment]
@philiplb Let us know if you find any cases where the hand tool is not sufficient, then we can re-open this issue.

**Comment by philiplb** [comment]
@Simran-B Just tried it and it is working just fine. Thank you!
