### ISSUE TITLE
[CRASH] Creating a new sequence preset crashes Olive

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#1538]
**Commit Hash**   
ce80fccd

**Platform**   
Ubuntu Groovy

**Summary**
Trying to save a new preset, even one that is just a copy of the default settings for a completely new sequence, leads to a crash.

**Steps to Reproduce**
Right-click in Project area → New → Sequence → Save Preset → [enter some name] → OK → OK

**Backtraces**

**Additional information**  
None. It truly is that simple to reproduce.

**Comment by baphomutt** [comment]
This kept happening to me as well yesterday. :( Gave up trying to save any presets.

ce80fcc
Manjaro 21.0
