### ISSUE TITLE
[PLAYBACK] No video in Footage Viewer on macOS 10.13

### ISSUE THREAD

**Issue by dag-odoo** [olive-editor/olive#1540]
**Commit Hash** Olive 0.2.0 ce80fccd 

**Platform**  Mac OS 10.13

**Summary**
Playback does not work on preview footage, only audio.
1. Import 1080p footage, 24fps, mp4, H264
2. Double click on footage
3. playback does not show any image in footage viewer

But if I drag and drop on a sequence, the sequence preview in the sequence viewer works like a charm (audio + video, no latency)

**Additional Information / Output**
Mac Pro 5.1, 96GB ram, 512 MB vram

**Comment by Simran-B** [comment]
Sounds like it could be related to #1524?

**Comment by dag-odoo** [comment]
Hello, maybe. But the issue #1524 is closed and works fine. I did re-install olive 0.2 after the fix and it work (no crash on import). And what is super weird is that the play-back for the sequence viewer works like a charm. It's only the preview viewer for video that does nothing (I can hear the audio, there is no image playing). I can only see one frame when on pause and when I click some where in the timeline.

**Comment by dag-odoo** [comment]
Hello, I just tested something. My mp4 file is opened and in the parameter Editor, the pixel aspect ratio is set to Anamorphic HD. I tried to open another footage from another source, when I open it, it is set to pixel aspect ratio Square and the playback runs smoothly.
For the first one (anamorphic), there is a huge lag when I change it to square (I guess it's caching).
So I think there is not really an issue, just parameter errors on my footages.

**Comment by itsmattkc** [comment]
That's not caching, that's some other kind of bug (the footage viewer doesn't cache by default).

**Comment by itsmattkc** [comment]
This appears to be fixed in recent commits, can you test it again @dag-odoo?

**Comment by dag-odoo** [comment]
@itsmattkc it works like a charm ! Thanks for the fix :)
