### ISSUE TITLE
[EXPORT] [CRASH]

### ISSUE THREAD

**Issue by LizardMan2765** [olive-editor/olive#1543]
**Commit Hash** 
#1472 

**Platform** 
Windows 10

**Summary**
whenever I export my video (which is not that long as its 30 min max and i have made a video that is an hour long with this, not to mention that i have tones of room on my laptop) the video will get to 68% and crash. i have changed all the settings i could to see if it was the quality or something but nothing worked. i have tried restarting my computer and that didn't work. I am not using anything i do not usually use in my videos... so what do i do?

**Additional Information / Output**

**Comment by LizardMan2765** [comment]
i just want to say that i started to export and it worked for some bizarre reason. but in case this happens again can someone please help?

**Comment by TheTechRobo** [comment]
@LizardMan2765 What was the back trace? Please fill out the issue template

**Comment by LizardMan2765** [comment]
> @LizardMan2765 What was the back trace? Please fill out the issue template, and what was the commit hash? YOu can find it where you downloaded Olive.

**Comment by LizardMan2765** [comment]
wdym? i did fill it out?

**Comment by LizardMan2765** [comment]
> @LizardMan2765 What was the back trace? Please fill out the issue template, and what was the commit hash? YOu can find it where you downloaded Olive.

wdym? i did fill it out

**Comment by TheTechRobo** [comment]
You filled it out, but it doesn't seem complete. You also linked to an issue instead of the commit hash.

Sorry if I have been sounding a bit rude, am overtired. 🤕

**Comment by elsandosgrande** [comment]
> You filled it out, but it doesn't seem complete. You also linked to an issue instead of the commit hash.
> 
> Sorry if I have been sounding a bit rude, am overtired. 🤕 

You're not overtired or rude, you're completely in the right.

**Comment by LizardMan2765** [comment]
> > @LizardMan2765 What was the back trace? Please fill out the issue template, and what was the commit hash? YOu can find it where you downloaded Olive.
> 
> wdym? i did fill it out


> You filled it out, but it doesn't seem complete. You also linked to an issue instead of the commit hash.
> 
> Sorry if I have been sounding a bit rude, am overtired. 🤕

sorry, i have no idea what i am doing, this is my first time on github

**Comment by TheTechRobo** [comment]
Yeah, it's fine. :) 

Please check your commit hash and add the proper fields in - backtrace (if possible), and the commit hash (find it where you downloaded Olive). :)
