### ISSUE TITLE
[UI] No samplerate on Audio tab, on settings

### ISSUE THREAD

**Issue by Inky1003** [olive-editor/olive#1546]
**Commit Hash** 
2f4e9809

**Platform** 
Manjaro Linux KDE Plasma

**Summary**
![image](https://user-images.githubusercontent.com/13457223/113449221-bd67a180-93d3-11eb-8f46-f2221faf7c71.png)
When I'm trying to select the audio samplerate there are no options. Instead there is nothing.

**Additional Information / Output**
I even cannot record the audio, but I think this is another issue.

**Comment by itsmattkc** [comment]
Yes, device sample rate and recording is incomplete at the moment.

Also note that this does not represent your _project's_ sample rate (which is set in sequence settings), but the sample rate your input/output devices use.

**Comment by Inky1003** [comment]
I mean, also the recording audio button does not work... Is It incomplete too?

**Comment by itsmattkc** [comment]
Yes, that's what I said. Device sample rate and recording.

**Comment by Inky1003** [comment]
oh, okay. Thanks!
