### ISSUE TITLE
Keyframes are not next to the desired attribute

### ISSUE THREAD

**Issue by Mennaruuk** [olive-editor/olive#1547]
**2f4e9809** 

**Platform**: Windows 10, Ubuntu 20.04 

**Summary**
Simply put, keyframes don't appear next to the desired attribute. Rather, they're showing at the top.

**Additional Information / Output**

Screen recording

https://user-images.githubusercontent.com/52135169/113495093-e1eb7880-94bc-11eb-9b30-6d9148aa943f.mp4

**Comment by itsmattkc** [comment]
Can you provide specific steps to recreate this? So far it appears to be working on my end.

**Comment by Mennaruuk** [comment]
Here's a demo from start to finish, reproduced on 72669761 on Windows 10 20H2:

https://user-images.githubusercontent.com/52135169/114271168-0e802280-99de-11eb-9c3d-a9ac8b8fce2a.mp4
