### ISSUE TITLE
[CRASH] Dropping MakeMKV DVD Rip into timeline crashes Olive.

### ISSUE THREAD

**Issue by Inky1003** [olive-editor/olive#1548]
**Commit Hash** 
2f49809

**Platform** 
Manjaro Linux KDE Plasma

**Summary**
I just drag my MKV DVD Rip file into the timeline and selected "Automatically detect" and then It crashes.

**Steps to Reproduce**

1. Open a file made with MakeMKV.
2. Drag into the timeline and select Automatic Footage Parameters detection.
3. It should crash.

<details><summary><strong>Backtrace</strong></summary><pre><code>

Starting program: /home/inky/Apps/olive/Olive-2f4e9809-Linux-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 125240]
process 125236 is executing new program: /tmp/.mount_Olive-BRVtaK/usr/bin/olive-editor
warning: Loadable section ".dynstr" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe76b3640 (LWP 125247)]
[Detaching after fork from child process 125248]
[WARNING] Node "org.olivevideoeditor.Olive.time" has no inputs ((null):0)
[DEBUG] Extracting default OCIO config to "/home/inky/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[New Thread 0x7fffe6e90640 (LWP 125252)]
[New Thread 0x7fffe668f640 (LWP 125253)]
[New Thread 0x7fffe5e8e640 (LWP 125254)]
[New Thread 0x7fffe568d640 (LWP 125255)]
[New Thread 0x7fffe4e8c640 (LWP 125256)]
[New Thread 0x7fffcffff640 (LWP 125257)]
[New Thread 0x7fffcf7fe640 (LWP 125258)]
[New Thread 0x7fffceffd640 (LWP 125259)]
[New Thread 0x7fffce7fc640 (LWP 125260)]
[New Thread 0x7fffcdffb640 (LWP 125261)]
[New Thread 0x7fffcd7fa640 (LWP 125262)]
[New Thread 0x7fffccff9640 (LWP 125263)]
[New Thread 0x7fffae0f5640 (LWP 125264)]
[INFO] Using Qt version: 5.15.2 ((null):0)
[New Thread 0x7fffacff3640 (LWP 125265)]
[New Thread 0x7fffa3fff640 (LWP 125266)]
[New Thread 0x7fffa37fe640 (LWP 125267)]
[New Thread 0x7fffa2ffd640 (LWP 125268)]
[DEBUG] Using graphics driver: NVIDIA Corporation ((null):0)
[New Thread 0x7fffa1f80640 (LWP 125269)]
[New Thread 0x7fff8ffff640 (LWP 125270)]
[INFO] Setting output audio device to "saida_som" ((null):0)
[WARNING] Failed to set name of parameter "track_in_0" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)
[WARNING] Failed to set name of parameter "track_in_1" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)
[WARNING] Failed to set name of parameter "track_in_2" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)

Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
olive::OpenGLRenderer::CreateNativeShader (this=this@entry=0x375a7b0, code=...) at ../app/render/opengl/openglrenderer.cpp:241
241     ../app/render/opengl/openglrenderer.cpp: Arquivo ou diretório inexistente.

</code></pre></details>

**Comment by itsmattkc** [comment]
Can you confirm if this only happens on one type of file and not all video files?

**Comment by Inky1003** [comment]
uhm... let's see...
Just dropped the same video cropped with Avidemux and edited with Olive 0.1.2, everything looks fine. Let's call that video the "droppable video"

Ironically I dropped on the timeline the other video which crashed Olive with the "droppable video" being first on there, and Olive does not want either to play or to cache the video.

**Comment by Inky1003** [comment]
Apparently the video is too big to cache, so Olive wants to fill something with cache on my pc and freeze It. Closing right now.

**Comment by itsmattkc** [comment]
This sounds related to #1519, but the expected outcome of that is not a crash.

Can you try with the latest AppImage? It should generate a crash report by itself without the need for GDB.

**Comment by Inky1003** [comment]
Yes, but I still can use GDB, don't worry. Just let me use the last AppImage as you said.

**Comment by Inky1003** [comment]
It seems now It works? But now there is another problem but with the audio. I'll open another issue. Thanks Matt!
