### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by notramo** [olive-editor/olive#155]
Please provide a tagged release because [Void Linux](https://voidlinux.org/) don't ship untagged releases.

**Comment by itsmattkc** [comment]
I would love to comply with this, but I'm not entirely sure what it means. How do I do this?

**Comment by notramo** [comment]
Simply create a Git tag and upload a release to Github.

**Comment by itsmattkc** [comment]
I've tagged the most recent commit, is this sufficient?
