### ISSUE TITLE
[EDIT] Crash when deleting clips while dragging them

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1556]
**Commit Hash** 
Any

**Platform** 
Any

**Summary**
While dragging clips, it is possible to delete them by pressing the delete key. Allowing this behavior is fine, however it should cancel the drag operation since the clips being dragged are no longer present. Instead the drag operation tries to continue and crashes.

**Comment by Simran-B** [comment]
Does it try to delete the ghost clip?

**Comment by itsmattkc** [comment]
Nah the deleting works correctly, but the drag isn't cancelled, so when it attempts to do the drop, it tries accessing clips that are no longer there.
