### ISSUE TITLE
[CACHE] Cache files are put into current working directory you are in on Linux

### ISSUE THREAD

**Issue by parona-source** [olive-editor/olive#1563]
**Commit Hash** 
c03c19741254f0fecfbf7dab2515a2da0a297ce7

**Platform** 
Ubuntu 20.10

**Summary**
Olive dumps cache files into the current working directory you are in on Linux, originally saw the behavior when it filled my home folder on Gentoo Linux.

For the sake of having a reproducible environment i tested this on Ubuntu 20.10 vm and latest appimage (as of  https://github.com/olive-editor/olive/commit/c03c19741254f0fecfbf7dab2515a2da0a297ce7) where it occurred also.

With the help git-bisect found the original source of the behavior to probably be https://github.com/olive-editor/olive/commit/6c30f8cf46497a1780d038205d52cb9aa0773ecf.

**Additional Information / Output**

**Comment by parona-source** [comment]
After testing https://github.com/olive-editor/olive/commit/7b4e7099f5a0e7cd76ab3fd7b8b94bd8df16c03d I see that behavior has changed in that the cache file isn't created when putting a video on the timeline, but cache files are still created in the current working directory when exporting.

**Comment by itsmattkc** [comment]
> After testing [7b4e709](https://github.com/olive-editor/olive/commit/7b4e7099f5a0e7cd76ab3fd7b8b94bd8df16c03d) I see that behavior has changed in that the cache file isn't created when putting a video on the timeline, but cache files are still created in the current working directory when exporting.

Fixed in 157da658a5323f4b61a19802c3303e44566fe5de
