### ISSUE TITLE
[EDIT] Moving clips while playing back freezes Olive

### ISSUE THREAD

**Issue by michaelharmonart** [olive-editor/olive#1564]
**Commit Hash** 
63c41146

**Platform** 
Kubuntu 20.10

**Summary**
Moving a clip while playing completely freezes Olive. This happens no matter how simple the project is, just import a video, press play, and try and move the clip forward and backward and Olive freezes.

**Additional Information / Output**
I'm using MKV files that were encoded in OBS with NVENC, I don't know much else about the crash/freeze but I'm happy to provide dumps/debug data if needed. (As long as someone lets me know how I might do that)

**Comment by itsmattkc** [comment]
Are you using the AppImage? The AppImage should provide a crash report that you can add to this issue.

**Comment by itsmattkc** [comment]
Confirmed when moving a clip with audio.
