### ISSUE TITLE
[UI] Left-Click + Drag on Timecode

### ISSUE THREAD

**Issue by krischan941** [olive-editor/olive#1565]
**Commit Hash** 
0.2.0-157da658

**Platform** 
Ubuntu 20.10

**Summary**
I remember on a previous version a while ago, when you left-clicked and dragged the timecode (on timeline or viewer) the mouse pointer vanished so one theoretically could scrubbed infinitely which I found quit handy. Now one is limited by screen borders when the mouse pointer reaches them. 
For node parameters I find it useful the way it now works. But for the timecode I'd prefer the previous way. What Do you think?

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Ultimately, after some deliberation, I think you're correct. Losing the "infinite dragging" was something I thought about a lot when implementing ladders (in fact I kept the old behavior accessible by disabling Preferences > Behavior > Use Slider Ladders for that reason). I figured that in most cases, the ladder itself allowing several multipliers would reduce the need for infinite dragging, however in situations where values are dragged and there is no ladder, the old behavior is probably preferable. As such, that has been implemented here: 51064f44f590e3fa5bdf20f4d83029a19731e292. If this behavior works, the "Use Slider Ladders" option may become unnecessary as this may cover all our bases.

**Comment by krischan941** [comment]
I think the behavior works great! Thank you.

Maybe a little minor cosmetic thing in this context you can find on the screenshot. The box doesn't match the underlying string and is a bit too narrow... if it is ok to mention here.
![slider](https://user-images.githubusercontent.com/23126549/114596595-1e269200-9c90-11eb-81da-b6e5d0c42a7f.png)
