### ISSUE TITLE
[CRASH] Olive freezing/crashing when I drag video into timeline 

### ISSUE THREAD

**Issue by Minelordsuniverse** [olive-editor/olive#1567]
**Commit Hash** 

**Platform**: Windows 10

**Summary**: Okay, so I drag(ged) a video from my file explorer into the sequence list/editor (bottom left || next to the timeline), works fine. But when I drag that clip from the sequence list/editor into the timeline list/editor (below the footage editor, etc.), the application just freezes/crashes. I'm in Windows 10 home using the latest version (as of now) of Olive.

**Steps to Reproduce**

1. (This is my first time committing an issue, so I don't think I know what to exactly include in these, sorry!)
2. 
3. 

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**

**Comment by Inky1003** [comment]
What is the latest version? Is that the ``51064f44`` version? Put that on the commit If you used the ``51064f44`` version.

You should add on your steps:
1. Drag a video from Windows Explorer into the Project List
2. Drag a video from the Project List to the Timeline
3. It should crash/It should freeze.
Specify If It's a freeze or a crash.

The backtrace is a output from your debugging application. @itsmattkc recommends gdb. [See this wiki page.](https://github.com/olive-editor/olive/wiki/Debugging-Olive)

I don't mean to be rude, but your bug report is incomplete. Have in mind that Olive is *not* stable and needs intensive testing. Use Olive If you know what you're doing, and not for production.

**Comment by itsmattkc** [comment]
Yes, please add your commit hash and steps to reproduce. The template explains where to find the commit hash:
```
**Commit Hash** <!-- 8 character string of letters/numbers in title bar or Help > About dialog (e.g. 3ea173c9) -->
```
As for backtrace, if you're using our official nightly, it should generate a crash report that you can either submit or paste here.
