### ISSUE TITLE
[PLAYBACK] MP3 audio file not playing

### ISSUE THREAD

**Issue by axiomgraph** [olive-editor/olive#1568]
**Commit Hash** 
Olive 429442c0

**Platform** 
linux 
**Summary**
in time line mp3 audio file not playing. play button does works but time line stuck.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
We had some audio issues a few commits ago but just fixed them, can you confirm if this is fixed on your end?

**Comment by axiomgraph** [comment]
problem still exists Olive-0d315d66
https://imgur.com/a/t25wji0

**Comment by itsmattkc** [comment]
Can you send that file? MP3s on my end don't cause issues.

**Comment by itsmattkc** [comment]
Can you delete the following folder and try again: `~/.local/share/olivevideoeditor.org/Olive/mediacache`

**Comment by axiomgraph** [comment]
thanks after deleting mediacache audio started playing.

**Comment by Simran-B** [comment]
Closing, as it was apparently caused by a bad disk cache.
