### ISSUE TITLE
[CRASH] Dragging an image on Timeline leads to consistent crashing

### ISSUE THREAD

**Issue by FirasH** [olive-editor/olive#1570]
**Commit Hash** 
Olive 0.2.0 6b7412af

**Platform** 
Windows 10

**Summary**

**Steps to Reproduce**

1. Start Olive
2. Import an image (like [this one](https://user-images.githubusercontent.com/6705690/114678642-bca40900-9d0b-11eb-8d06-a31e6e1bd04a.png)) using `File > Import...`
3. Drag the imported image on the `Timeline` and select `Automatically Detect Parameters From Footage`

Olive crashes consistently (happened also with older builds, tried with a build from a weeks ago).

Even if the `Sequence` is already created the crash is reproducible.

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
Using the github artifact, tested on different `.png` images

**Comment by itsmattkc** [comment]
Can you please provide the backtrace/crash report?

**Comment by ThomasWilshaw** [comment]
I'm not able to reproduce this (persoanl build on Windows 10)

**Comment by FirasH** [comment]
@ThomasWilshaw same here... Cannot reproduce with the AppImage on openSUSE.

**Comment by itsmattkc** [comment]
I've been able to reproduce this but only on an AMD laptop (Ryzen 5 CPU and Vega 9 GPU), this might be another AMD issue related to #1574?

**Comment by FirasH** [comment]
I have Windows 10 on a mac mini late 2015 with Intel i5-4278U cpu and Intel Iris 5100 graphics.

**Comment by itsmattkc** [comment]
That could also be affected, I've seen crash reports from Intel graphics drivers too, but they all appear to be older than the Intel GPU I have access to

**Comment by FirasH** [comment]
@itsmattkc I've checked the driver installed and it wasn't the latest.
Updated to the latest version but still crashing.

**Comment by Simran-B** [comment]
#1574 is resolved now, please test again @FirasH

**Comment by FirasH** [comment]
> #1574 is resolved now, please test again @FirasH

Sure! I don’t have access to the machine for a couple of days so I’ll report the test as soon as possible 👍

**Comment by FirasH** [comment]
This one is also fixed in 0cd40028.
Great work!
