### ISSUE TITLE
[CRASH] Applying any Rotation to clip Tranform crashes consistently

### ISSUE THREAD

**Issue by FirasH** [olive-editor/olive#1572]
**Commit Hash** 
Olive 0.2.0 6b7412af

**Platform** 
Windows 10

**Summary**

**Steps to Reproduce**

1. Start Olive
2. `File > Import...` and import a video (tested with `.MOV`)
3. Drag the imported video on the `Timeline` and select `Automatically Detect Parameters From Footage`
4. Select the imported clip and in the `Parameter Editor` set `Transform > Rotation` to `-90` (any value will work)

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
Using the github artifact, tested on different `.MOV` videos

**Comment by ThomasWilshaw** [comment]
I'm not able to reproduce this. Can you provide any sample footage or more details? Is there any console output or a backtrace?

**Comment by FirasH** [comment]
@ThomasWilshaw just recorded my screen here:
https://user-images.githubusercontent.com/6705690/114746343-ed0d9680-9d4f-11eb-909a-f0d5d517e258.mp4

**Comment by ThomasWilshaw** [comment]
Thanks, coud you possibly provide on of the  .mov files that does this? It's interesting there's no error report generated. Could you also provide some hardware specs, mainly CPU, GPU and GPU driver version.

**Comment by FirasH** [comment]
Doesn't happen with the AppImage on another openSUSE machine.
I'll report the hardware specs of the Windows 10 machine where the crash is happening.

**Comment by elsandosgrande** [comment]
I can also confirm that it doesn't happen with any of my builds on Ubuntu.

**Comment by itsmattkc** [comment]
Probably same root issue as #1570, which might be AMD-exclusive.

**Comment by ThomasWilshaw** [comment]
@FirasH Can you check if this is fixed with the latest master?

**Comment by FirasH** [comment]
> @FirasH Can you check if this is fixed with the latest master?

Sure, I’ll test it as soon as possible 👍

**Comment by FirasH** [comment]
I can confirm this is fixed in 0cd40028.
Thank you!
