### ISSUE TITLE
[COLOR] cant find an option to set opacity of solid or any other object in timeline

### ISSUE THREAD

**Issue by sherebiahtishbi** [olive-editor/olive#1580]
**Commit Hash** 
Olive 0.2.0-0d315d66

**Platform** 
Ubuntu 20.04

**Summary**
There is no way to adjust opacity of a solid

**Additional Information / Output**
![Screenshot from 2021-04-15 15-56-45](https://user-images.githubusercontent.com/7480055/114930619-38cd4800-9e03-11eb-9b4a-51cae82f5160.png)

**Comment by itsmattkc** [comment]
Multiply it

**Comment by sherebiahtishbi** [comment]
Appreciate the quick response.

**Comment by sherebiahtishbi** [comment]
Hi do you have docs somewhere to refer how to do it? I am not sure how to
do it. I tried using Math node and it didn’t go well.

**Comment by ThomasWilshaw** [comment]
https://github.com/olive-editor/olive/wiki/Olive-0.2.x-Quickstart

It's probably a bit out of date but should get you started.

**Comment by sherebiahtishbi** [comment]
Thank you so much. That helps....

**Comment by Simran-B** [comment]
Hm, not sure if it's possible to adjust the opacity yet without #1366. This node setup adjusts the brightness at least:

Solid -> Math -> Clip -> ...

It doesn't matter to which of the two Math node slots you connect the Solid to. Change the Method to Multiply and adjust the Value of the other slot within the range 0.0 - 1.0

![image](https://user-images.githubusercontent.com/7819991/115061347-5f65ae80-9ee9-11eb-9869-5c16c477e7e6.png)

**Comment by itsmattkc** [comment]
It depends if the source has an alpha channel, you're probably right that the solid doesn't (unless you pass it through a node that happens to give it one). That will definitely be more coherent once #1366 is implemented.

**Comment by sherebiahtishbi** [comment]
I was able to change opacity of solid over a image and use it as title
background....using math node

**Comment by kburchfiel** [comment]
I could change the opacity of a shape by adding in an Opacity object and connecting the Shape to its Texture component. I then merged these Shape and Opacity nodes (along with a Text node) to my image via a Merge node.

![image](https://github.com/olive-editor/olive/assets/32693822/0b0e664b-66da-4e8b-b0d9-d01f748655cb)
