### ISSUE TITLE
[CRASH] 

### ISSUE THREAD

**Issue by ItzXtra** [olive-editor/olive#1581]
**Commit Hash** 

**Platform** 

**Summary**

it isn't a crash but 0.2 when i download it says that it could harm my device
**Steps to Reproduce**

1. 
2. 
3. 

<details><summary><strong>Backtrace</strong></summary><pre><code>

</code></pre></details>

**Additional Information**

**Comment by Simran-B** [comment]
Probably a duplicate of #1288
