### ISSUE TITLE
when ripple deleting with subtitles on top layer, the upcoming subtitles are disabled[EDIT] 

### ISSUE THREAD

**Issue by orkunkumkale** [olive-editor/olive#1582]
**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**

**Comment by TheTechRobo** [comment]
You need to fill out the issue template. The commit hash can be found in the ABOUT menu, your platform is your OperatingSystem, the summary is a summary of the issue. We also need steps to reproduce.

**Comment by itsmattkc** [comment]
Closing until more information is provided
