### ISSUE TITLE
[ANIM] Curve editor keyframe handles not working properly

### ISSUE THREAD

**Issue by axiomgraph** [olive-editor/olive#1586]
**Commit Hash** 
74ad4110

**Platform** 
Linux 

**Summary**

**Additional Information / Output**

![image](https://user-images.githubusercontent.com/7819991/115745090-6847fb80-a393-11eb-98c5-03229a06d414.png)

**Comment by itsmattkc** [comment]
Please describe the issue you are having. The screenshot on its own isn't telling me much.

**Comment by itsmattkc** [comment]
Closing until more information is provided.
