### ISSUE TITLE
[PLAYBACK] Dragging Timecode on Footage Viewer to preview an Audio is too slow

### ISSUE THREAD

**Issue by krischan941** [olive-editor/olive#1592]
**Commit Hash** 
0.2.0 - 573597be

**Platform** 
Ubuntu 20.10

**Summary**
Preview an audio file by scrubbing it via timecode on Footage Viewer is too slow because it is scrubbing every single sample. Maybe It would be better if it was some thousand samples or so.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Please elaborate. Scrubbing means dragging your playhead, how can that be too slow?

**Comment by krischan941** [comment]
Ah ok. Then I used the word "scrubbing" in a wrong way, sorry. 
I meant if you you preview an audio file (by double click the audio item in project tab) and drag the timecode of the footage viewer, it plays back too slow if you compare it to by dragging the timecode of the sequence viewer when the audioclip is on an audio track.

**Comment by itsmattkc** [comment]
Okay I understand now. I think the solution is unlikely to be increasing the default drag interval by an arbitrary amount, I think it'll be more likely to use some sort of existing solution in Olive tweaked slightly (e.g. ladders or holding modifier keys, which makes the interval smaller but not larger).

**Comment by krischan941** [comment]
Personally I would like to retain infinity dragging on the footage viewer. So I would change the default drag interval for the "special case" audio. Something like: samplerate / 50 = x, where x is the drag interval dependent on the samplerate. This would be my suggestion.

**Comment by sobotka** [comment]
Try wraparound infinite scrubbing in this case?

**Comment by itsmattkc** [comment]
Okay I've made some changes to the keyboard modifiers, now Ctrl will make slider dragging slower (x 0.01) and Shift will make slider dragging faster (x 100). I think this will be our official solution to this issue.
