### ISSUE TITLE
[NODES] Video and/or audio breaks when reconnecting nodes

### ISSUE THREAD

**Issue by michaelharmonart** [olive-editor/olive#1593]
**Commit Hash** 
a0200f22

**Platform** 
Kubuntu 21.04

**Summary**
When reconnecting nodes by CTRL + Dragging to override a connection with another identical connection, or just deleting the node connect and making a new one, audio and/or video breaks (depending upon which connection you change). I'm talking specifically about the connection from the media node to the transform and or volume node. 
![image](https://user-images.githubusercontent.com/15620900/116165523-4ca56380-a6b9-11eb-89bd-a17c15d579ad.png)

Reconnecting from the volume or transform nodes to their respective clip nodes causes no issues.

Please let me know if you need more information, but I think this should be pretty reproducible for testing/debugging purposes.

**Comment by itsmattkc** [comment]
Known issue. Media nodes have multiple outputs for multiple streams but the UI doesn't allow connecting them yet.

**Comment by itsmattkc** [comment]
Merging into #1650
