### ISSUE TITLE
[NODES] No way of disconnecting nodes without selecting and deleting the connection

### ISSUE THREAD

**Issue by michaelharmonart** [olive-editor/olive#1594]
**Commit Hash** 
a0200f2

**Platform** 
Kubuntu 21.04

**Summary**
I may be missing something obvious so let me know if this is inaccurate. Currently in the olive node editor the only way to disconnect a node is by selecting the connection and deleting it. 
Most of the node-based software I've used (Fusion, Natron, Blender) will let you at least disconnect a node by dragging by its endpoint, and they often let you move that connection somewhere else as well. 

Here's what it looks like in Fusion
![resolve](https://user-images.githubusercontent.com/15620900/116168031-ca1fa280-a6be-11eb-9b5f-5de4196077df.gif)

I'd love something similar in Olive, but I understand that major bugs/crashes are the main focus right now.

**Comment by michaelharmonart** [comment]
Hey @itsmattkc  it looks like a7d7515 lets you drag node connections, but when you let go of the endpoint of a connection while it is disconnected it doesn't delete the connection, it just floats there connected to nothing.

I don't think that's intended behavior.

Here's a few other issues I ran into: 
![olive2](https://user-images.githubusercontent.com/15620900/116254492-9c724200-a72e-11eb-9574-75eff4a1578a.gif)
Namely
1. Dragging to a new node doesn't delete the old connection
2. Dragging to a node places the previous connection in the wrong place until that previous node is moved again.

**Comment by itsmattkc** [comment]
You're right, my mistake. Should be fixed in a8185aa13bbeb8e8e5ab742a38671dd929708806

**Comment by michaelharmonart** [comment]
Took a quick look, seems to work. Thanks for all your great work!
Hopefully soon I'll have the time and dedication to start learning qt and the olive code-base to begin helping contribute actual code.

**Comment by krischan941** [comment]
I like that behaviour too.
The only issue for this now: when you do a single left-click on the arrowhead it deletes the arrow.

**Comment by itsmattkc** [comment]
> I like that behaviour too.
> The only issue for this now: when you do a single left-click on the arrowhead it deletes the arrow.

Fixed in 502b5971f9ee0b360704f61d4bb52f33b71be044
