### ISSUE TITLE
[NODES] Allow to connect nodes without holding Ctrl/Cmd button down

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1596]
**Commit Hash** 
59952fdd

**Platform** 
macOS 10.14.6

**Summary**
Related with issue #1594, it would be nice to have no only a usable/easy way to disconnect a node with other but also to connect it. It's kind a "hidden" feature the need of drag the left mouse button while pressing CTRL/COMMAND in order to be able to connect a node with another one.
It would be nice that you can press a button in the node header and drag the mouse to "see the arrow". Some other softwares do this way and it's so useful:
<img width="494" alt="button" src="https://user-images.githubusercontent.com/5942369/116401215-459e6280-a82b-11eb-935f-39f623cccb62.png">

Thanks

**Additional Information / Output**

**Comment by michaelharmonart** [comment]
Recently Matt implemented a feature to let you easily disconnect nodes the same way you do in most composting software, by dragging the connection by its end.

**Comment by pgilfernandez** [comment]
> Recently Matt implemented a feature to let you easily disconnect nodes the same way you do in most composting software, by dragging the connection by its end.
> 
> (Since you mentioned to usability of disconnecting nodes I thought I'd let you know in case you hadn't found out yet)

Indeed, I mention that feature and it was the reason why I suggested this one =)

**Comment by itsmattkc** [comment]
If I'd be inclined to do anything, it would be to use Nuke's approach: https://learn.foundry.com/nuke/content/tutorials/written_tutorials/tutorial1/connection_tips.html

**Comment by sobotka** [comment]
There is a validity in transferring Nuke knowledge of models across here as well.

**Comment by itsmattkc** [comment]
Merging into #1650
