### ISSUE TITLE
[CACHE] Auto caching doesn't start if you press play too soon

### ISSUE THREAD

**Issue by ThomasWilshaw** [olive-editor/olive#1598]
**Commit Hash** 
59952fdd

**Platform** 
Windows 10

**Summary**
Drag some footage onto the timeline then add a blur node. Adjust the blur radius the hit play before the auto caching starts (there's always a small delay before auto caching starts, I'm not sure if that's meant to happen or not).  No caching will happen and the cache bar will stay red. Once playback is stopped, after 10/12 seconds Olive will start to cache again from where the cursor was originally.

**Additional Information / Output**
See atached video, I wait for the caching to start again so watch to the end. This appears to happen with the math node too, I've not tested others.

https://user-images.githubusercontent.com/7781683/116453741-23bad500-a857-11eb-8961-5301a945dd7f.mov

**Comment by itsmattkc** [comment]
Is this fixed in 27ba4899cad7576af2827819fa3f8d9c9e0a7716?

**Comment by ThomasWilshaw** [comment]
Sort of, caching now seems to happen as it should but I get a lot of `[WARNING] Playback queue failed to keep up ((null):0)` messages in the console and the fps seem to be very slow

https://user-images.githubusercontent.com/7781683/116557068-038e2300-a8f6-11eb-9cdc-f0e927294e8d.mov

**Comment by itsmattkc** [comment]
I've made a few more adjustments in b82e616124eb4b7f093aacbd4278db13abd632a4, let me know if that makes a difference.

**Comment by ThomasWilshaw** [comment]
That seems to have sorted it yes, what's happening now though is when I pause playback when ithe playhead is outside a cached area, caching stops. I'd expect it to start caching again from where the playhead is but could be wrong. Is that a seperate issue?

https://user-images.githubusercontent.com/7781683/116727974-33642600-a9dd-11eb-817e-1e43c1f25d8e.mov

**Comment by itsmattkc** [comment]
Try 0b259d3a630b377aca93a329d28f756dcd4d686d

**Comment by ThomasWilshaw** [comment]
That's better, it does keep caching. I suppose I'd expect the caching to jump straight to the playhead though, raher than keep caching from where it left off.

**Comment by itsmattkc** [comment]
That should depend on your "cache behind" setting.

**Comment by ThomasWilshaw** [comment]
My cache behindsetting is set to 0

**Comment by itsmattkc** [comment]
Try 964129bb0858339e4b63368db089cf2d91077b92

**Comment by itsmattkc** [comment]
I believe this has been fixed so I will close it.
