### ISSUE TITLE
[CODEC] Importing image sequence

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1602]
**Commit Hash** 
6d2eeb74

**Platform** 
macOS 10.14.16

**Summary**
Is it possible to import an image sequence in Olive v0.2? I tried yesterday and it didn't work... If it should work, it doesn't under macOS...

Thanks

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Yes, it's supposed to work. Please be more descriptive than "it doesn't work".

**Comment by ThomasWilshaw** [comment]
Any specific file formats? What exactly happens, is there a crash or an error in the console?

**Comment by pgilfernandez** [comment]
1) I open the "Import..." dialog and select all images (in my case they are PNGs) which are named "image.0001.png"
2) Olive doesn't ask me if they are part of a image sequence
3) they are imported as individual image (still) assets
4) even if I select them all in the project and place the into a sequence they are all placed one after the other but with the length of a normal still

Alternatively I have tried to import just the first numbered file in case Olive asks me then if it is part of a image sequence, but it doesn't.

**Comment by itsmattkc** [comment]
It's working on my end. Can you provide details about the full file path of these files?

**Comment by pgilfernandez** [comment]
Indeed:
`/Users/pablo/Google\ Drive\ Educarex/2020-2021\ Profesor/9\ Gestión\ TIC/Videotutoriales/0\ Entradilla\ Reino\ Aftasí/reino_aftasi_v05\ PNGs/reino.0001.png`
As you see, it contains folders with spaces, with accents and even the drive itself is a synchronized Google Drive drive...

As you suggest it might be related with path, I have tried too placing the files in just:
`/Users/pablo/Desktop/reino_aftasi_v05\ PNGs/reino.0001.png`
but it still doesn't work for me...

**Comment by ThomasWilshaw** [comment]
Could having two periods in the file name be causing issues?

**Comment by itsmattkc** [comment]
That is a possibility, all my files are formatted with an underscore

**Comment by ThomasWilshaw** [comment]
I get the following if I try to inport images named `image.xxxx.png` but it works fine if they are called `image_xxx.png`

![image](https://user-images.githubusercontent.com/7781683/116865933-781cd680-ac02-11eb-8ac4-aa5d0b7ee68c.png)

**Comment by ThomasWilshaw** [comment]
I suspect this issue is we use `completeSuffix()` which grabs everything after the first period, not the last.

https://doc.qt.io/qt-5/qfileinfo.html#completeSuffix
https://github.com/olive-editor/olive/blob/master/app/codec/oiio/oiiodecoder.cpp#L167

**Comment by ThomasWilshaw** [comment]
Hmm that allows the images to be loaded/read but the logic to detect a sequence will also need to be updated

**Comment by Simran-B** [comment]
Yeah, it works with underscores and the completeSuffix() method shouldn't be used because it returns everything from the first period on. The suffix should be fine for us. Should we need to support double extensions like .tar.gz then that should be based on the second to last period I guess? But I would rather suggest adding a dedicated import dialog where you can configure every detail including image sequences instead for such corner cases.

**Comment by itsmattkc** [comment]
> I suspect this issue is we use `completeSuffix()` which grabs everything after the first period, not the last.
> 
> https://doc.qt.io/qt-5/qfileinfo.html#completeSuffix
> https://github.com/olive-editor/olive/blob/master/app/codec/oiio/oiiodecoder.cpp#L167
> 
> Probably better to use:
> https://doc.qt.io/qt-5/qfileinfo.html#suffix

Hmm in this case that's probably true, I think I default to `completeSuffix` for things like `.tar.gz` but I don't think there's an image format where that would ever be case.

**Comment by ThomasWilshaw** [comment]
I couldn't think of one either. I'm trying to get the other bits of code to work with both types of sequence name.

**Comment by ThomasWilshaw** [comment]
I think I've got it, had to change `baseName()` to `completeBaseName()` in a few places as well. I'll open a PR now
