### ISSUE TITLE
[EDIT] Opacity/Transparency no available?

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1605]
**Commit Hash** 
32e11bb6

**Platform** 
macOS 10.16.14

**Summary**
Sorry to use the issue tracker for a question: is opacity/transparency available? I can't find a way to set it for a clip...

Thanks

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Multiply it

**Comment by pgilfernandez** [comment]
I promise I tried it before and it didn't work... I have tried again to confirm and it works, so, sorry about it and thank you very much.
=)
