### ISSUE TITLE
[NODES] Nodes View looks black after opening an existing project

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1608]
**Commit Hash** 
ee90d89e

**Platform** 
macOS 10.16.14

**Summary**
When you load a Recent project or just use the "Open project" dialog, when the project is loaded the Node View shows black. Only when you press in "New..." button from Project View then the Node View start working:

https://user-images.githubusercontent.com/5942369/117110758-e68aa180-ad86-11eb-9116-279a8e762ffc.mp4

Thanks

**Additional Information / Output**

**Comment by itsmattkc** [comment]
While this is certainly a UI papercut that was worth addressing, I think it's important to note that the NodeView responds to the project panel that's focused. So clicking new wasn't making the nodes appear, it was just focusing the project panel. If you had multiple projects open, the NodeView would switch depending on project panel active at any given time.

**Comment by pgilfernandez** [comment]
Indeed, it also happens when you create a new Project, till you don't focus the Project panel the Node view doesn't refresh.
