### ISSUE TITLE
Scrollable Viewer Playheads Zoom 

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#161]
Scrollable Viewers is a great idea, and they work really well. However current behaviour is that a user has to click on the playhead triangle to be able to zoom in with "+" and out "-" on keyboard.

It would be good if hovering the mouse over the viewer (either one) or sequence timeline would initiated the zoom "+" & "-" for each one respectively. When editing a user normally does not have time to think about clicking on each panel and activating it to initiate a zoom action.

Possibly having a scrollbar with two handles either end would simplify the adjustment of the zoom & range in a GUI way, (and incorporate "+" "-" in active, or moused over panel)

**Comment by itsmattkc** [comment]
In 467d271d5c4d6a5d31304526c54d6b4d100d2194 I added a setting to enable "hover focus", i.e. the focused panel that zoom keys will go to is the one with the mouse hovering over it.

Handles on the scroll bar is not a bad idea, however I don't think Qt provides this functionality out of the box. I believe it would require subclassing QScrollBar to hook into its mouse functions and add the ability to resize them manually. Probably wouldn't be too difficult but would require some research into the inner workings of QScrollBar.

**Comment by itsmattkc** [comment]
The branch `resizablebars` has a mockup of resizable scrollbars. For the most part it works, but I haven't figured out mathematically how to make the resizing perfect. Still, the concept is there.

**Comment by alcomposer** [comment]
Yes, I checked it out, and apart from the maths not working correctly, it's there.

One thing that would be nice would be to add a small visual cue on each end of the scrollbar. So that it is obvious that it is a handled scrollbar.

I was thinking to start with that this may be easier to implement as a custom QSlider, but it looks like this is ok.

**Comment by itsmattkc** [comment]
Despite no visual handles on the scrollbar, I'll consider this issue addressed now (the focus by hovering and resizable scrollbars being the main requests).
