### ISSUE TITLE
[RENDER] Waveform display breaks if transform is anything but neutral

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#1610]
**Commit Hash** 32e11bb6

**Platform** Manjaro Linux 64-bit

**Summary**

Waveform display becomes distorted when I alter scale, rotation or location in footage transform.

**Additional Information / Output**

Footage with a neutral transform:
![image](https://user-images.githubusercontent.com/491704/117365350-76cc0200-aebf-11eb-8bd4-9916d31bb345.png)

And after I nudge the scale, rotation or position in the Transform:

![image](https://user-images.githubusercontent.com/491704/117365404-86e3e180-aebf-11eb-940f-d0f07a7a1b51.png)

Then after I close and reopen Waveform display, it gets back on track:

![image](https://user-images.githubusercontent.com/491704/117365455-98c58480-aebf-11eb-8f21-1a8b6809aa0f.png)

And now I can alter the transform all I want and it's fine:

![image](https://user-images.githubusercontent.com/491704/117365529-b397f900-aebf-11eb-974d-069df305cecb.png)

Until I reset the transform back to neutral, and it's broken again:

![image](https://user-images.githubusercontent.com/491704/117365564-c27eab80-aebf-11eb-9df7-6c4fbcb7b8f5.png)

**Comment by ThomasWilshaw** [comment]
Can confirm this happens. As mentioned on Discord this is possiblythe fragment shader not getting an updated resolution.
