### ISSUE TITLE
[EDIT] Clip disappears just one frame after "cross dissolve" transition

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1617]
**Commit Hash** 
15556c64

**Platform** 
macOS 10.14.6

**Summary**
I have played with this issue and I can't find how to locate it so I just post a simple video and the project in case you can do it. I have tried clearing the cache, exporting the project to video and the frame after the "cross dissolve" transition always "disappears":

https://user-images.githubusercontent.com/5942369/117587397-0ff85400-b11e-11eb-962a-d002fc2b3144.mov

**Additional Information / Output**
Attaching the project:
[test.zip](https://github.com/olive-editor/olive/files/6448450/test.zip)

**Comment by itsmattkc** [comment]
This looks like it might be related to #1615, we still don't know what that issue is, but this looks like a very similar presentation
