### ISSUE TITLE
[UI] - NSIS - Enable multilanguage installer / use new component layout

### ISSUE THREAD

**Issue by bovirus** [olive-editor/olive#1619]
**Commit Hash** 

72ed87d9

**Platform** 

Windows 10

**Summary**

Multilanguage instalelr

**Additional Information / Output**
@itsmattkc 
@Simran-B 

Please enable multilanguage installer.
Please use for NSIS the new component layout window (v2)
Current component layout window (v1) is too short for text description (check screenshot)

![image](https://user-images.githubusercontent.com/1262554/117630302-5a5bee00-b17b-11eb-91fb-a4663c9fd7eb.png)

**Comment by itsmattkc** [comment]
I'm no NSIS expert, if you (or anyone else) have experience with it, I'd strongly encourage you to create a pull request so this is solved more timely than it would otherwise be. The NSIS file is located at `app/packaging/windows/nsis/olive.nsi` in the source repository.

**Comment by bovirus** [comment]
@itsmattkc 

I can do it.
When I will do it, I will ask you to create a temporary build to test it.

Pelase add also this info (instalelr script) in README about translation.

**Comment by Simran-B** [comment]
Just open a pull request with your code modifications, including CMake if necessary. Our CI will then automatically create builds.

**Comment by nesper8** [comment]
I think InnoSetup could be a better alternative to NSIS but hey its upto y'all

**Comment by itsmattkc** [comment]
If someone wants to PR a new installer, they can feel free.
