### ISSUE TITLE
[UI] - Languages - Update PR pending requests about language

### ISSUE THREAD

**Issue by bovirus** [olive-editor/olive#1621]
**Commit Hash** 

72ed87d9

**Platform** 
Windows 10

**Summary**

Update language files (for PR)

**Additional Information / Output**

@itsmattkc 
@Simran-B 

Could you please update language PR pending here

https://github.com/olive-editor/olive/pulls

Then I will make a general update about language files (alligned with master)

Thanks.

**Comment by Simran-B** [comment]
We will eventually check with the PR authors about the statuses and merge what is mergeable. Some are known to be on hold though.

Please refrain from opening reports like this, as this is not a bug (see #1175 for details).

**Comment by bovirus** [comment]
@Simran-B 

If you don't merge previous PR I cannot proced with otehr language.

I posted it via a new PR.

**Comment by bovirus** [comment]
@Simran-B 

Created a new PR

https://github.com/olive-editor/olive/pull/1622

The new NSIS installer script is quite ready.,

After you will apply this PR I can complete it.

Thanks.

**Comment by Simran-B** [comment]
I don't see the point of updating all .ts files without adding actual translations to all of them. If you want to contribute to the Italian translation then you should do that in a PR, but updates to other languages should be done separately. I fail to understand how the .ts files are related to the proposed installer changes. Hence, modifications to the installer should also be in its own PR.

**Comment by bovirus** [comment]
@Simran-B 

The big problem if someone want to update the language at 99% use an old language file with strings obsolete that he didn't need to edit.

I knwo that you wrote to update it manually but most of time the translator forget it.

Who develop this kind of project when made change a change to teh source apply automatically lupdate to cynchronize all project.

I will amke two differnt PR

One for Italian language
One for all languages expcept Italian and English.
