### ISSUE TITLE
[NODES] Allow "label" and "color" node properties accessible via Node View

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1624]
**Commit Hash** 
72d5b4af

**Platform** 
macOS 10.14.6

**Summary**
It would be great to be able to access the "label" and "color" node properties with the node system and making use of the Value node, this way it would be possible to automate the labeling and even custom node coloring. For instance:

<img width="1019" alt="labels" src="https://user-images.githubusercontent.com/5942369/117776820-3dd3ba80-b23c-11eb-9d0b-6fd02ad5dbaa.png">

Thanks

**Additional Information / Output**

**Comment by itsmattkc** [comment]
You _can_ access the label and color settings in the node view. I assume that's not what you're referring to?

**Comment by itsmattkc** [comment]
Yep I understand. I personally don't think this is a good idea.
