### ISSUE TITLE
[NODES] Center view to nodes

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1626]
**Commit Hash** 
72d5b4af

**Platform** 
macOS 10.14.6

**Summary**
Playing around with the Node View (panning and zooming) I sometimes "get lost" and don't know where the nodes are. It would be nice to have a menu option to "center view" so that the view pans and zoom to all your nodes. Something like "zoom to all" that all 2D-3D software have.

Thanks

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Merging into #1650
