### ISSUE TITLE
[NODES] Creating a New project doesn't resets pan/zoom Node View

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1627]
**Commit Hash** 
72d5b4af

**Platform** 
macOS 10.14.6

**Summary**
When you create a New Project, it gets the last used UI panel layout which is nice, but if you had a big node system and your "node view position/zoom" was very far away from the "node view origin", there is no way to recenter it and view your nodes.
It could be solved if it is added an option to "recenter nodes" as commented in #1626, but in this case I would say that the node view position would have to be reset to origin.

Thanks

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Merging into #1650
