### ISSUE TITLE
How full loading red buffer bar ? (twitter too)

### ISSUE THREAD

**Issue by Vedlem** [olive-editor/olive#1633]
Hey i have question! :) On 0.1 i have bug beginning of 2 files mkv have no sound (10 first second) so i go on 0.2 (bug dissapear). On 0.2 in timeline have buffer memory, how load all buffer without play and wait all green bar ? Thanks ;)

PS : I love Olive, my prefer of all

**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**

**Comment by TheTechRobo** [comment]
Please provide:

- the commit hash (go into the About dialog to see it)
- platform (Windows 10? Debian 9? macOS 12.69?)
- output (backtrace is preferred, if you can't do that just copy the terminal output)

**Comment by Simran-B** [comment]
Click on the _Sequence_ menu, then _Cache Entire Sequence_. That should start the caching of the entire sequence so that the cache indicator is all green.

![image](https://user-images.githubusercontent.com/7819991/118411841-f794b600-b696-11eb-8482-37a69f9964c4.png)

**Comment by Vedlem** [comment]
Oh yeah i test this but i test more options but i don't fing, i sure it's this now THANKS! You're reactive :DDD

**Comment by Vedlem** [comment]
Sorry for the criticism, probably my fault... 
![hdd](https://user-images.githubusercontent.com/32007933/118515309-9112a500-b735-11eb-98af-48afb22fa4d4.png)

**Comment by sobotka** [comment]
Fill out the damn report template or have the issue closed. Up to you. Do the work.
