### ISSUE TITLE
[EXPORT] Black video

### ISSUE THREAD

**Issue by dag-odoo** [olive-editor/olive#1637]
**Commit Hash** 4adaedb3

**Platform** Mac Os 10.13.6

**Summary**
I created a simple project with 2 tracks. Top track is a PNG with alpha channel. Bottom track is just a 4K video. I added som keyframes on position/rotation of the png track. Also added 3 audio tracks.
After export -> Media, the video is either fully black, either it's just the top track (png with black background) or 1 or 2 frames from the bottom track (4K). (export to mp4)
No Node were added.

The viewer works perfectly fine, Olive does not crash, there is no error message.

**Additional Information / Output**
Video is black, sound works, image is broken or black.

**Comment by itsmattkc** [comment]
What happens if you export the 4K video straight with nothing else on the timeline? Is it still black?

**Comment by itsmattkc** [comment]
It's worth noting that I have been unable to recreate this, so it's something specific to your setup. I won't be able to fix this without more information.

**Comment by dag-odoo** [comment]
Hello, sorry it took me a while to test it.
I've done two tests: one with the track  2 (top track) muted and a second test with track 2 deleted.
Here are the results. https://www.kradukman-production.com/File_transfert/olive/

**Comment by itsmattkc** [comment]
Hmm is there any console output? Would you be able to share the original footage?

**Comment by itsmattkc** [comment]
Also I'd be interested to see if there's any change with ae3393f03141ec0f179523670950e2483b8d5c33

**Comment by itsmattkc** [comment]
Merging into #1297, assuming it's the same issue
