### ISSUE TITLE
[UI] No text by checkboxes in context menu

### ISSUE THREAD

**Issue by andersmmg** [olive-editor/olive#1638]
**Commit Hash** 
4adaedb3

**Platform** 
Manjaro Linux KDE

**Summary**
When I right click on the parameter editor, the context menu has a list of checkboxes (seems to be one per parameter), but they have no labels so I have no idea what they are for.

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/16022203/119033567-97d62d80-b96a-11eb-8872-e9b80bc531b0.png)

**Comment by Simran-B** [comment]
@andersmmg Is this Wayland or X?

**Comment by andersmmg** [comment]
I'm on X11

**Comment by itsmattkc** [comment]
Pretty sure this is Qt's auto-generated menu for showing and hiding dock widgets. We don't really need or want this behavior, so if anything, I'd be inclined to just disable it.
