### ISSUE TITLE
[NODES] Video track elements don't get deleted when it's subitem is deleted

### ISSUE THREAD

**Issue by JellyOsaurus** [olive-editor/olive#1640]
**Build Number** 
09dc79f9

**Platform** 
Windows 10 64-bit

**Summary**
Same issue as #1639  but with the video track node. Deleting the subitems in the node editor will not delete the element itself, creating unneccesary build up in your project.

https://user-images.githubusercontent.com/22872180/119254605-10580c80-bb6c-11eb-9fd7-07d75d04e250.mp4

**Comment by itsmattkc** [comment]
Not a bug. Deleting in the Project Explorer is one thing, but anything done in the Node Editor assumes the user wants full manual control. When tracks can be deleted in the timeline (not implemented yet), then some degree of automation can be implemented similar to the Project Explorer.
