### ISSUE TITLE
[UI] Hotkey for video cropping

### ISSUE THREAD

**Issue by main-gi** [olive-editor/olive#165]
The Viewer now supports resizing videos visually through the Viewer, but there's no hotkeys for Shift, Ctrl, and Alt (or any hotkeys there?) as far as I know. I'd like the OBS-style change in specific, where if you hold Alt and resize the video, it crops instead of resizing.

**Comment by itsmattkc** [comment]
This may be difficult to implement as the on-screen controls are controlled by the effect and the default Transform effect has no crop parameters. The only way to implement this in the current design would be to merge the transform and crop effects together (which may not be a bad idea, I can certainly see the appeal of these sorts of keyboard shortcuts). The Shift for disabling "uniform scale" could be done without much difficulty though.
