### ISSUE TITLE
[UI] NodeView Enhancements

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1650]
This is a meta thread for the various NodeView enhancements planned. Feel free to comment for further suggestions.

Current TODO list:
- [x] Mini-map to improve navigation
- [x] Toolbar
- [ ] Allow pinning parts of edges to better organize
- [x] Allow access to array elements
- [x] #1752
- [x] Connect to nodes without Ctrl/Cmd
- [x] Reimplement block-based filtering
- [x] Improve arrow look and feel (#1682)

**Comment by mcDandy** [comment]
Do not allow connecting incompatible nodes/warn about it. For example Video to Trigonometry (Color[X,Y] -> double).

The data types are just my assumptions.

**Comment by sobotka** [comment]
> Do not allow connecting incompatible nodes/warn about it. For example Video to Trigonometry (Color[X,Y] -> double).
> 
> The data types are just my assumptions.

This seems suffocating.

Adding business logic near nodes seems like a Bad Idea. One can never know what someone is doing. Smart software is always stupid.

**Comment by itsmattkc** [comment]
This is pretty much all done. The only thing not implemented yet is the pinning of edges, but that can be done later.
