### ISSUE TITLE
[PLAYBACK] Crash when playing a freshly imported MP4

### ISSUE THREAD

**Issue by luukvanderduim** [olive-editor/olive#1652]
Pressing play after importing a MP4 video resulted in a crash.

OS: Xubuntu 21.04

Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 5.11.0-17-generic
System: Ubuntu 21.04 (ubuntu 21.04)

olive-editor(_ZN5olive13crash_handlerEi+0x116)[0x562e32e17d06]
/lib/x86_64-linux-gnu/libc.so.6(+0x41040)[0x7fea768d7040]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN7QString13toUtf8_helperERKS_+0xd)[0x7fea76f57f4d]
olive-editor(_ZNK5olive4Node4HashER18QCryptographicHashRKNS_8rationalE+0x4e2)[0x562e32e772d2]
olive-editor(_ZN5olive12RenderWorker8HashNodeEPKNS_4NodeERKNS_11VideoParamsERKNS_8rationalE+0x87)[0x562e32ea5c27]
olive-editor(_ZN5olive12RenderWorker14GetCachedFrameEPKNS_4NodeERKNS_8rationalE+0xcd)[0x562e32ea658d]
olive-editor(_ZN5olive13NodeTraverser16PostProcessTableEPKNS_4NodeERKNS_9TimeRangeERNS_14NodeValueTableE+0x134e)[0x562e32e7ef1e]
olive-editor(_ZN5olive13NodeTraverser13GenerateTableEPKNS_4NodeERKNS_9TimeRangeE+0xaf)[0x562e32e7f16f]
olive-editor(_ZN5olive13NodeTraverser12ProcessInputEPNS_9NodeInputERKNS_9TimeRangeE+0x131)[0x562e32e7f2f1]
olive-editor(_ZN5olive12RenderWorker11RenderFrameESt10shared_ptrINS_12RenderTicketEEPNS_12ViewerOutputERKNS_8rationalE+0x89)[0x562e32ea5df9]
Version: 
Signal: 11

**Comment by itsmattkc** [comment]
Is this consistently recreatable?

**Comment by luukvanderduim** [comment]
Unfortunately not. I tried it just now and it seems to work fine. I'll poke around some more and hope to find offending circumstances.

**Comment by itsmattkc** [comment]
Closing until more information can be provided
