### ISSUE TITLE
[CACHE] cache system was broken when moving clip on timeline

### ISSUE THREAD

**Issue by omida56** [olive-editor/olive#1654]
**Commit Hash** 
96bfff43

**Platform** 
Mint 20.1

**Summary**
Workflow:
importing mp4 file into the bin,cutting 3 part of it and dragging into Timeline playback seems OK. but problem came after I moved clips around,changing their place cos cache system completely broke
(playback screen was black and no audio for those clips which was relocated)

**Additional Information / Output**
(sorry for my bad English)

**Comment by itsmattkc** [comment]
Can you provide specific steps to reproduce this?
