### ISSUE TITLE
[BUILD] CMake error after introduction of subtitle support

### ISSUE THREAD

**Issue by mynameismuhl** [olive-editor/olive#1658]
**Commit Hash** 
08e2fa4d

**Platform** 
Linux Mint 20.1

**Summary**
After the introduction of cc21ed37 olive does not compile here anymore.
Tried with both gcc9 and clang12

I get a successful build if I rollback and checkout 4adaedb3
or
If I comment out all includes of subtitleparams.x in headers and cmakelists 
(and some subtitle related lines in ffmpegencoder.cpp)
then i can also compile at current head.

**Additional Information / Output**
```
[ 48%] Building CXX object app/CMakeFiles/libolive-editor.dir/render/subtitleparams.cpp.o
/home/xxx/olive/app/render/subtitleparams.cpp:83:24: error: no matching member function for call to 'arg'
  return kFormatHeader.arg(QCoreApplication::applicationName(),
         ~~~~~~~~~~~~~~^~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:1008:25: note: candidate function not viable: requires 9 arguments, but 16 were provided
inline QString QString::arg(const QString &a1, const QString &a2, const QString &a3,
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:1004:25: note: candidate function not viable: requires 8 arguments, but 16 were provided
inline QString QString::arg(const QString &a1, const QString &a2, const QString &a3,
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:1000:25: note: candidate function not viable: requires 7 arguments, but 16 were provided
inline QString QString::arg(const QString &a1, const QString &a2, const QString &a3,
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:997:25: note: candidate function not viable: requires 6 arguments, but 16 were provided
inline QString QString::arg(const QString &a1, const QString &a2, const QString &a3,
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:291:31: note: candidate function not viable: requires at most 5 arguments, but 16 were provided
    Q_REQUIRED_RESULT QString arg(double a, int fieldWidth = 0, char fmt = 'g', int prec = -1,
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:994:25: note: candidate function not viable: requires 5 arguments, but 16 were provided
inline QString QString::arg(const QString &a1, const QString &a2, const QString &a3,
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:275:31: note: candidate function not viable: requires at most 4 arguments, but 16 were provided
    Q_REQUIRED_RESULT QString arg(qlonglong a, int fieldwidth=0, int base=10,
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:277:31: note: candidate function not viable: requires at most 4 arguments, but 16 were provided
    Q_REQUIRED_RESULT QString arg(qulonglong a, int fieldwidth=0, int base=10,
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:979:25: note: candidate function not viable: requires at most 4 arguments, but 16 were provided
inline QString QString::arg(long a, int fieldWidth, int base, QChar fillChar) const
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:981:25: note: candidate function not viable: requires at most 4 arguments, but 16 were provided
inline QString QString::arg(ulong a, int fieldWidth, int base, QChar fillChar) const
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:975:25: note: candidate function not viable: requires at most 4 arguments, but 16 were provided
inline QString QString::arg(int a, int fieldWidth, int base, QChar fillChar) const
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:977:25: note: candidate function not viable: requires at most 4 arguments, but 16 were provided
inline QString QString::arg(uint a, int fieldWidth, int base, QChar fillChar) const
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:983:25: note: candidate function not viable: requires at most 4 arguments, but 16 were provided
inline QString QString::arg(short a, int fieldWidth, int base, QChar fillChar) const
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:985:25: note: candidate function not viable: requires at most 4 arguments, but 16 were provided
inline QString QString::arg(ushort a, int fieldWidth, int base, QChar fillChar) const
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:991:25: note: candidate function not viable: requires 4 arguments, but 16 were provided
inline QString QString::arg(const QString &a1, const QString &a2, const QString &a3,
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:293:31: note: candidate function not viable: requires at most 3 arguments, but 16 were provided
    Q_REQUIRED_RESULT QString arg(char a, int fieldWidth = 0,
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:295:31: note: candidate function not viable: requires at most 3 arguments, but 16 were provided
    Q_REQUIRED_RESULT QString arg(QChar a, int fieldWidth = 0,
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:298:31: note: candidate function not viable: requires at most 3 arguments, but 16 were provided
    Q_REQUIRED_RESULT QString arg(const QString &a, int fieldWidth = 0,
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:301:31: note: candidate function not viable: requires at most 3 arguments, but 16 were provided
    Q_REQUIRED_RESULT QString arg(QStringView a, int fieldWidth = 0,
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:303:31: note: candidate function not viable: requires at most 3 arguments, but 16 were provided
    Q_REQUIRED_RESULT QString arg(QLatin1String a, int fieldWidth = 0,
                              ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:989:25: note: candidate function not viable: requires 3 arguments, but 16 were provided
inline QString QString::arg(const QString &a1, const QString &a2, const QString &a3) const
                        ^
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:987:25: note: candidate function not viable: requires 2 arguments, but 16 were provided
inline QString QString::arg(const QString &a1, const QString &a2) const
                        ^
1 error generated.
make[2]: *** [app/CMakeFiles/libolive-editor.dir/build.make:2638: app/CMakeFiles/libolive-editor.dir/render/subtitleparams.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3468: app/CMakeFiles/libolive-editor.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by itsmattkc** [comment]
What version of Qt are you compiling with?

**Comment by mynameismuhl** [comment]
it is 5.12.8

**Comment by Simran-B** [comment]
Try 5.15.2 and see if that helps

**Comment by mynameismuhl** [comment]
Yes, that shortly opened a can of nightmare worms but it works with 5.15.2 now, thanks!
And sorry, should have tried that before posting, I didn't want this to turn into a help request.

The build instructions on your website are now outdated though.
5.12.8 is what ` apt install ` gives you on Ubuntu 20.04 based distros
and the dependencies list Qt 5.9+.

Anyway thanks again, closing this.

**Comment by Simran-B** [comment]
I guess this is the culprit method:

> `template <typename Args> QString QString::arg(Args &&... args) const`
> […]
> This function was introduced in Qt 5.14.

https://doc.qt.io/qt-5/qstring.html#arg-22

There was also some code for debugging that used a 5.15 method, but that was removed again I believe... We should make 5.15 the minimum required version I guess. Other dependencies also require versions that aren't available via distro package managers, so doing this for Qt as well shouldn't make it much more difficult.

**Comment by itsmattkc** [comment]
> We should make 5.15 the minimum required version I guess.

I'm in two minds about that. While we have a dependency system set up so we can more or less choose whatever version we want for official builds (and they all use 5.15 anyway), it would likely not be hard to change that code to use a different form of `QString::arg` too.

**Comment by Simran-B** [comment]
Is there any benefit to staying with a lower 5.x Qt other than availability in package managers though? An important drawback is that 5.9 may behave quite differently than 5.15, with the latter hopefully having less bugs. Any issues reported with another Qt version than what our official builds use will make it harder for us to support custom builds.

**Comment by itsmattkc** [comment]
No, no benefit outside of backwards compatibility/ease of compilation on certain Linux distros.

**Comment by elsandosgrande** [comment]
@Simran-B By “custom builds”, do you mean “local builds of Olive built by other people”? If so, wouldn't trying to see how far the Qt version can be pushed without any side-effects — possibly even seeing if some minor patches which do not affect Olive's behaviour with the latest version of Qt 5 might increase the usable minor version range — be a benefit? I mean, we could, after enough reports and/or research, actually say something like: “The minimum Qt version needed for compiling Olive without any unintended/unknown side-effects is 5.13”?

If this is completely missing the point, then I apologise in advance — I'm just now catching up to everything thanks to school commandeering most of my time 😅.

**Comment by mynameismuhl** [comment]
My thoughts on this regarding the Linux situation are:
If you use current Ubuntu LTS as an "is tested on..." which is what you somewhat suggest on the webpage,
stick to the version it comes with. That is likely until April 2022: v5.12.8.

While it is certainly not impossible to upgrade it, 
it is a little more involved than simply installing it on top and definitely makes a (first) build more complicated.
Plus if you are not careful you can mess up parts of your system and create broken dependencies elsewhere.
The other extras like OCIO don't necessarily run into that.

I never tried the Qt online installer you link to, whether it makes the process easier/safer,
but I saw it requires opening an account so I don't see a lot of Linux users using it ;-) .
