### ISSUE TITLE
[RENDER] Alpha issue with gap underneath EXR

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#1661]
**Commit Hash** 
08e2fa4d8ebfc2df9edcdb981a7e118b21a8c1c6

**Platform** 
Linux, probably others.

**Summary**
Alpha looks wrong when a gap is merged but looks fine when a black solid is merged. I don't know why.

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/34096995/124323946-f6c8be00-db36-11eb-836b-544347a9b335.png)
![image](https://user-images.githubusercontent.com/34096995/124323951-f92b1800-db36-11eb-83af-cb91b95dd993.png)

**Comment by Simran-B** [comment]
The semi-transparent areas appear to be affected?
I set View to Filmic Log Encoding Base in the Viewer because that happened to result in a good contrast between image and artifacts:

![image](https://user-images.githubusercontent.com/7819991/126519744-da52440a-41e6-42fb-ab16-4a37fe4649a3.png)

**Comment by itsmattkc** [comment]
I've investigated further into this and consulted with others since the original post and have determined it may not actually be a "bug" per se. It appears to be related to the alpha disassociation and reassociation done before and after a color transform. Disabling it results in an image that looks fine (however this breaks other test/example images).

I spoke to the lead developer of OpenImageIO, he confirmed that OIIO will produce the same result with this image if disassoc/reassoc is enabled, and that they ended up implementing a user setting to disable disassoc/reassoc because there just seem to be some images that break with it on (like this one) and some images that break without it.

Unless we find that both Olive and OIIO (or OCIO potentially) have botched their implementations in some way, it may simply be that Olive just needs a similar option to disable it.
