### ISSUE TITLE
[EXPORT] Export always gets stuck at 4%

### ISSUE THREAD

**Issue by amateureditor** [olive-editor/olive#1667]
**Commit Hash** 
1e3cf533

**Platform** 
Windows 10, 64 bit - version 10.0.19041

**Summary**
I have edited a complete video, but every time I try to export it, it gets stuck on 4%

**Additional Information / Output**
I have tried exporting as several different video formats but the problem persists

**Comment by Simran-B** [comment]
> > **Commit hash**
>
> I'm not a coder. I don't what this is.

Just follow the instructions:

`<!-- 8 character string of letters/numbers in title bar or Help > About dialog (e.g. 3ea173c9) -->`

**Comment by amateureditor** [comment]
Was looking in the wrong place. I found it now. 

1e3cf533

**Comment by Simran-B** [comment]
0.1.x is not supported anymore. You can try this 0.1.2 build for Windows 64-bit, however: https://drive.google.com/file/d/1Dns0rPHAySPqtp2ADo6BGLUIAkXOhH0c/view?usp=sharing

**Comment by amateureditor** [comment]
I know this now considered closed so I don't know if you're still willing to help, but: I've downloaded the files for the update. What do I do with them? Again I have no coding knowledge, and if there's not an .exe file, I don't know what to do.

I'm competent enough to follow instructions (despite the earlier mishap) but I'll be lost without any.
