### ISSUE TITLE
[EXPORT] Export always gets stuck at 4%

### ISSUE THREAD

**Issue by amateureditor** [olive-editor/olive#1668]
**Commit Hash** 

2c700ca2
**Platform** 
Windows 10 64 bit, version 10.0.19041

**Summary**

I submitted this same problem yesterday but had an old version of Olive. I was told support could not be provided but linked to the updated version. I have installed the updated version but the same problem persists. Every time I try to export my project, it gets stuck at 4% and the entire program freezes. I eventually have to close the export which in turn automatically closes Olive when I do. Then I get a message up on opening the next time that Olive didn't close properly.

**Additional Information / Output**

**Comment by elsandosgrande** [comment]
The version of Olive you're using, indicated by the commit hash you wrote, is deprecated — anything below 0.2 is deprecated:

![image](https://user-images.githubusercontent.com/40576902/125274478-4add5a80-e30e-11eb-9ddb-b877359dad1a.png)

If the pre-compiled Windows build of Olive 0.1.2 has not fixed the issue that you've been having, then you'll either have to ask around for a possible workaround in the subreddit or the Discord server, or have to try Olive 0.2.
