### ISSUE TITLE
[UI]  It doesn't change the language to Spanish

### ISSUE THREAD

**Issue by ndawebs** [olive-editor/olive#1672]
**Commit Hash** 

**Platform** 
Windows 11

**Summary**

**Additional Information / Output**

It doesn't change the language to Spanish, I'm using windows 11. It looks like an abandoned project. Is that right?

**Comment by itsmattkc** [comment]
It sounds like you're talking about 0.1, which never got a complete Spanish translation (despite there being a blank file for it).

Either way, this project is **not** abandoned. The next release has been a complete redesign/rewrite and has therefore taken a long time, but it is still being worked on almost every day.
