### ISSUE TITLE
[UI] All clips are visible on Node Editor

### ISSUE THREAD

**Issue by alex285** [olive-editor/olive#1673]
**Commit Hash:** 24b9756e3bfe2fc7acb650d1678068dc557decf9

**Platform:** Linux

**Summary:** Node editor displays all clips, and that makes hard to work on. Is that by design? 

### Reproduce 
1. Create a new sequence
2. Add two solids
3. Select one solid

**Result:** Node Editor will display nodes for both solids, even if we filter by "Selected Blocks" (if that relates)

**Expected:** Node Editor should display nodes only for the selected solid;

**Further:** There is same behavior even if we place solids on different channels (eg Video 1, Video 2)

### Assets

![olive2-nodes](https://user-images.githubusercontent.com/11244308/126028728-fe9e4d66-996d-48b0-8f8b-fb3310c86ea8.png)

**Comment by itsmattkc** [comment]
See #1650. Try the `nodeview-redux` branch to see progress on this.

**Comment by nicorikken** [comment]
Thanks @alex285 for leading me here and showing off this great project! Thank you Olive editor team for your work! https://www.youtube.com/watch?v=zEhSMi6k_BQ
