### ISSUE TITLE
[UI] Possible design flaw in node UI

### ISSUE THREAD

**Issue by samytichadou** [olive-editor/olive#1682]
**Commit Hash** 

**All Platform** 

**Summary**
The current design of node/noodle connection can be weird, when a node is connected to an "output noodle" going left or right, the node arrow (little triangle directly below the node) could be mistaken for the end of a directional arrow coming **from** the noodle itself. Here is a picture (quick n dirty, sorry) trying to show what i mean. 
Below the original image, a little mockup with some kind of "vertical start" margin for the out noodle, maybe fixing the problem

![arrow_design](https://user-images.githubusercontent.com/26276003/126335150-9bc262f7-8edb-4ff0-9fd4-a7878ed89883.png)

This could be confusing for people not used to node, giving this node window is opened by default in olive workspaces, it could be hard to read with a "crowded edit".

Cheers !

**Additional Information / Output**
None

**Comment by pgilfernandez** [comment]
Yes, I agree that the line should start just at the node output tip.

**Comment by itsmattkc** [comment]
Merging into #1650
