### ISSUE TITLE
[Blur] When clicking on keyframe for any of the nodes, it does not properly display the value set for the selected keyframe

### ISSUE THREAD

**Issue by rpatros1979** [olive-editor/olive#1688]
**Commit Hash** 
f13962da

**Platform** 
Arch Linux

**Summary**
It seems that when clicking on keyframe for any of the nodes, it does not properly display the value set for the selected keyframe.

1. Create a sequence and add a video clip to the video1
2. Create the following nodes attached in this sequence:

Text-->Stroke-->Transform-->Crop-->Blur-->\
                                                                            \___Merge
                                                                           /
                              Media file-->Transform-->/

3. Enable and create multiple keyframes either of the nodes (Transform or Crop) and set a unique value for the keyframe.
4. Then attempt to click on the keyframe with the value set and you will not see the value that was assigned to the keyframe. It seems that only the value will show is if you move the playhead.
5. Also addition bug shown in the attached video, is that when clicking on the keyframe button to move to the next keyframe, it did not seem to move to the last keyframe.

**Additional Information / Output**
https://user-images.githubusercontent.com/53153746/126905696-77858ae7-6369-4453-ba96-25970ec2e6bf.mp4

**Comment by itsmattkc** [comment]
Not a bug, the parameter view will show the value at that time, not the value for whatever keyframes are selected.

> Also addition bug shown in the attached video, is that when clicking on the keyframe button to move to the next keyframe, it did not seem to move to the last keyframe.

This is a bug, sort of. If a keyframe has been shifted to a point between two frames (even minutely), it will be considered "the next keyframe" and then rounded down to the frame boundary, causing what appears to be no change. It would seem the solution would be to allow the playhead to exist off the frame boundary in some situations.
