### ISSUE TITLE
[EDIT] Timeline and Footage Markers

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#1690]
**Commit Hash** f13962da

**Platform** Manjaro Linux KDE

**Summary**

Various issues related to Markers

- [x] It's not possible to select markers
- [x] Hence it's not possible to delete
- [x] Move markers
- [x] It's also not possible to rename markers
- [x] Marker names are not visible on the timeline ruler or anywhere else
- [x] Markers created in Media preview do not show up on clips in a sequence
- [x] There's no way to change marker color (always green)

**Comment by itsmattkc** [comment]
Some of this overlaps with #487, but this post is probably more complete. May merge that issue into this one.

**Comment by itsmattkc** [comment]
This has now been fully implemented
