### ISSUE TITLE
[EDIT] Add a hotkey to move selection to the current playhead position

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#1691]
In Ardour (open-source DAW) there's a hotkey "A" you can use to move your selection to they current position of your "edit point" (usually mouse or playhead).
I know Ctrl-X and Ctrl+V should do it, but somehow I really miss that hotkey in Olive.

**Comment by itsmattkc** [comment]
This has been implemented in the form of `[` and `]` keys.
