### ISSUE TITLE
[CRASH] 

### ISSUE THREAD

**Issue by DiegoDev-It** [olive-editor/olive#1693]
**Commit Hash**  

**Platform**  Ubuntu 21.04

**Summary** Olive crashed importing a 2160p@60 clip in project or timeline

**Steps to Reproduce**

1. Import 2160p@60 clip (MKV) on project's files or timeline
2. 
3. 

<details><summary><strong>Crash Report</strong></summary><pre><code>

Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 5.11.0-22-generic
System: Ubuntu 21.04 (ubuntu 21.04)
olive-editor(_ZN5olive13crash_handlerEi+0x116)[0x557986563d06]
/lib/x86_64-linux-gnu/libc.so.6(+0x41040)[0x7ff62ee56040]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZNK14QObjectPrivate20maybeSignalConnectedEj+0x21)[0x7ff62f665a91]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0x2f0149)[0x7ff62f673149]
olive-editor(_ZN5olive4Task15ProgressChangedEd+0x44)[0x557986511404]
olive-editor(_ZN5olive17ProjectImportTask6ImportEPNS_6FolderERK5QListI9QFileInfoERiP12QUndoCommand+0x21e)[0x5579866073fe]
olive-editor(_ZN5olive17ProjectImportTask3RunEv+0x5a)[0x557986607aca]
olive-editor(_ZN12QtConcurrent15RunFunctionTaskIbE3runEv+0x52)[0x557986590772]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0xd0792)[0x7ff62f453792]
/lib/x86_64-linux-gnu/libQt5Core.so.5(+0xcd341)[0x7ff62f450341]
Version: 
Signal: 11
</code></pre></details>

**Additional Information**

**Comment by Simran-B** [comment]
Version information missing and without sample footage it's virtually impossible to reproduce.
