### ISSUE TITLE
[PLAYBACK] Footage viewer slow or no video, scrubbing may crash

### ISSUE THREAD

**Issue by GUY-BBS** [olive-editor/olive#1694]
**Commit Hash** 5254be3f

**Platform** Win 10

**Summary**Video files slow to appear in Footage Viewer. When they do appear, unable to be played back. Red line under Footage Viewer window fails to disappear. I have tried two different (Win 10) computers with the same result.  

**Additional Information / Output** Repeatedly attempting to move playback head in Footage Viewer causes program to crash.
![Olive 2 Footage Viewer Frze](https://user-images.githubusercontent.com/49677111/127337883-7f255392-4a1d-4a36-abf1-b61ef95a3e81.jpg)

**Comment by itsmattkc** [comment]
Please provide the specs of your computer including the GPU and GPU drivers installed.

**Comment by GUY-BBS** [comment]
Hi Matt,

Error appears on two Win 10 PCs

PC 1
Intel i7 2.4 GHz   16GB RAM
GFX Geforce GTX 660M
Driver 425.31

PC2

Intel(R) Pentium(R) CPU 4415U @ 2.30GHz 2.30 GHz

Ram 4.00 GB Integral Intel GFX

Regards

GRC

**Comment by Simran-B** [comment]
What's the exact CPU model of PC 1? There are several i7 generations and processors with 2.4 GHz base clock.

**Comment by GUY-BBS** [comment]
Details of CPU

Intel® Core™ i7-3630QM Processor

6M Cache, up to 3.40 GHz


Memory Specifications

• Max Memory Size (dependent on memory type)32 GB

• Memory TypesDDR3/L/-RS 1333/1600

• Max # of Memory Channels2

• Max Memory Bandwidth25.6 GB/s

• ECC Memory Supported ‡No

Processor Graphics

• Processor Graphics ‡Intel® HD Graphics 4000

• Graphics Base Frequency650 MHz

• Graphics Max Dynamic Frequency1.15 GHz

• Graphics OutputeDP/DP/HDMI/SDVO/CRT

• Intel® Quick Sync VideoYes

• Intel® InTru™ 3D TechnologyYes

• Intel® Flexible Display Interface (Intel® FDI)Yes

• Intel® Clear Video HD TechnologyYes

• # of Displays Supported ‡3

• Device ID0x166


Regards

GRC

**Comment by Simran-B** [comment]
Thanks, so it's an Intel HD Graphics 610 (2017) and a 4000 (2012).

**Comment by GUY-BBS** [comment]
Downloaded Olive-930d8309 today and the problem seems resolved; however, the red line in the Footage Viewer remains.

**Comment by Simran-B** [comment]
The footage viewer does not cache by default so the line staying red is expected behavior.

Are you sure that the original problem is solved? I don't see any changes that involved the footage viewer between the two builds.

**Comment by GUY-BBS** [comment]
I have downloaded the latest build Olive-9f4470f5- and the problem has
returned?
GRC

**Comment by itsmattkc** [comment]
What you're probably finding has nothing to do with the versions and is instead that brand new footage imported into Olive requires "conforming" the audio, which will temporarily slow the renderer down. Once the audio has been conformed, it never has to be done again (unless you clear the disk cache), which means the issue will appear to be "fixed".

Please confirm if old footage appears "fixed" while new footage appears "broken". You can start off with a fresh disk cache (delete `%localappdata%/olivevideoeditor.org/Olive/mediacache` to test more reliably.

**Comment by GUY-BBS** [comment]
Hi Matt,
I have carried out several tests (on Computer 1).
With nothing in the Footage Viewer window, the timeline is fully responsive
with quite a complex sequence.
I have cleared the cache, and the timeline renders as one would expect and
is fully responsive.
Sending an MP3 music clip to the Footage Viewer, it responds instantly and
the playback response is instant. Timeline response normal.
Sending a PNG image to the Footage View and it takes 10 seconds to appear
in the window.. When it does appear Timeline response is normal.
Sending a video clip to the Footage Viewer, either new or old, pre-cached
or not, takes around five seconds to appear. and then the playback is
frozen or incredibly sluggish. The timeline is now frozen or incredibly
sluggish.
Happy to provide further information if you would like.
GRC

**Comment by GUY-BBS** [comment]
Installed Olive-5e7cb068 today and the Footage Viewer operation has improved. Placing any video in it no longer affects the timeline performance. Playback in the Footage Viewer is not fluid and scrolling takes a while to catch up.

**Comment by itsmattkc** [comment]
Let me know if this is fixed in 677277c16d51bcd9aa6073fc71fa8fe4bdbc720e

**Comment by GUY-BBS** [comment]
I tried 677277, but the first frame of a video clip appears in the Footage Viewer, and I am unable to play or scroll in this window. Returning the focus to the main timeline and this too had frozen. After about a minute the timeline unfroze. Returned to the Footage Viewer window and still frozen. Also, the timeline refroze.

**Comment by itsmattkc** [comment]
Works fine for me. Try clearing all your cache and settings and try again (delete folders `%appdata%\olivevideoeditor.org` and `%localappdata%\olivevideoeditor.org`).

**Comment by itsmattkc** [comment]
1ab13c3ab6be2d78f35f9adfbc91cffde567d5d5 may also help mitigate slowness/freezing (677277c was a stability thing not a performance thing).

**Comment by GUY-BBS** [comment]
I cleared the cache/settings as suggested and installed 1ab13c3 on both machines detailed above. The HP laptop (Computer two) worked well with fluid playback in the Footage Viewer and instant switching of focus to the timeline. The Clevo laptop (Computer one) still showed the exact same problem - unable to playback or scroll in the Footage Viewer window and inability to switch focus to the timeline without considerable delay- sometimes crashing. Installed 1ab13c3 on an older Clevo - i7 Q740 @ 1.73GHz and its performance was similar to Computer two. 
Can I help in any way to give you further information or assistance?

**Comment by itsmattkc** [comment]
So you're saying between three computers, it works perfectly fine on two of them?

**Comment by GUY-BBS** [comment]
Yes. It works on the HP laptop (Computer 2) and my old Clevo laptop but it does not work on my newer Clevo (Computer 1)

**Comment by itsmattkc** [comment]
> Yes. It works on the HP laptop (Computer 2) and my old Clevo laptop but it does not work on my newer Clevo (Computer 1)

Well, what's different about that computer? Does it not have an SSD? Does it only have integrated graphics?

**Comment by itsmattkc** [comment]
Also please try the latest commit @GUY-BBS

**Comment by GUY-BBS** [comment]
The laptop has an SSD C: drive and a regular D: drive (for media)
The GFX card is a Nvidia GTX 660M
I manually deleted the cache files and installed efcf0ed3 with the same result. Video clips freeze in the Footage Viewer and getting focus back to the timeline is delayed.
Since everything works fine now on the other two computers, this could be a weird one-off and not worth your time in pursuing.
If the problem goes away with a future commit or I find something odd with this computer, I will contact you.
This unit happily runs Premier CS6 and Resolve 16

**Comment by itsmattkc** [comment]
To be honest, yeah I'm not sure there's anywhere else that this issue can go. Seeing as I can't recreate it on any of my systems, and only one of yours exhibits this issue, and I'm not aware of any other user who is experiencing this, I'm not sure how to even begin diagnosing it let alone fixing it. My only suggestion is to try updating your graphics drivers, but otherwise I'm not sure much can be done on Olive's end. Therefore I think I will close this issue. And yes, feel free to comment on it if something happens.

**Comment by GUY-BBS** [comment]
Will do
