### ISSUE TITLE
Hue/Saturation/Brightness needs a limit

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#170]
Right now, it's possible to go set pretty much whatever value for both hue, saturation, and brightness. But 500 doesn't make sense for hue, because it's limited to 360° (honestly, I don't remember is the range is 0..360 or -180..180° in HSB, but you get the point) — it just keeps rotating. Similarly, one probably won't use 15000 for saturation or 7000 for brightness. So maybe there should be some sensible limits?

**Comment by itsmattkc** [comment]
This may sound silly but I don't really intend on limiting values like this. While it's true that 15000 saturation will seldom produce a usable result, I think it's up to the user (more so than me) to determine what qualifies as a usable result. But thanks for the suggestion :)
