### ISSUE TITLE
Incorrect 4k media scaling in render on 1040p Sequence with mixed-resolution videos.

### ISSUE THREAD

**Issue by 111ukasz111** [olive-editor/olive#1702]
**Commit Hash** 
132e637f

**Platform** 
Windows 10 Intelcore i7, Nvidia Geforce 920M

**Summary**
Incorrect 4k video scale after scale and position animation combined with 1040p video after rendering on sequence  with 1040p resolution.
PrtScFullScreenSequence preview: 
![PrtScSequence preview](https://user-images.githubusercontent.com/20667528/128604707-3822c5a7-e230-45df-a198-ae607da8099f.png)
RenderingOption:
![RenderingOptions](https://user-images.githubusercontent.com/20667528/128604967-88c48b4b-9f9e-4f60-8379-03b791074667.JPG)
PrtScRender:
 ![PrtScRender](https://user-images.githubusercontent.com/20667528/128604706-671a18bf-9551-47c7-b6d3-c191dbe56747.png)
![Zrzut ekranu (9)](https://user-images.githubusercontent.com/20667528/128606749-415d55b5-f58b-4473-9925-fd7981896824.png)

**Additional Information / Output**
Export the project and you will see:
[https://drive.google.com/file/d/1MvWmUpGmHIztpXSPMlGmSqMIyigfuaQj/view?usp=sharing](url)

**Comment by ThomasWilshaw** [comment]
Please provide the commit hash for your build and I'll re-open the issue. Also it would be helpful if you could provide a screen shot of your node setup, or even better the a sample project and footage for us to test. 

Thanks

**Comment by 111ukasz111** [comment]
Can you open it?

> Please provide the commit hash for your build and I'll re-open the issue. Also it would be helpful if you could provide a screen shot of your node setup, or even better the a sample project and footage for us to test.
> 
> Thanks

Can you open it?

**Comment by ThomasWilshaw** [comment]
Thanks that's much appreciated.

**Comment by Simran-B** [comment]
Closing in favor of https://github.com/olive-editor/olive/issues/1703

**Comment by 111ukasz111** [comment]
> Closing in favor of #1703

My was first.

**Comment by Simran-B** [comment]
Consider the other issue as meta ticket. There was another report of the same problem on Discord. Plus it's labeled more appropriately as export issue and Matt assigned a priority.
