### ISSUE TITLE
[EDIT] The curve editor view is scrolling by itself to the left side while moving the curve deforming circle to the left side.

### ISSUE THREAD

**Issue by 111ukasz111** [olive-editor/olive#1704]
**Commit Hash** 
132e637
**Platform** 
Windows 10 Intelcore i7, Nvidia Geforce 920M

**Summary**
Steps to reproduce.
1. Click and move the curve deforming circle in the curve editor view, the curve editor view is scrolling by itself to the left side.

**Additional Information / Output**
![Przechwytywanie](https://user-images.githubusercontent.com/20667528/128636952-8f467bee-3cf7-4a3c-8a08-1dfe46b0524e.JPG)

![OliveAudioBug](https://user-images.githubusercontent.com/20667528/128696570-acdbc3c9-93c0-4e0a-a350-2bc9b147863e.gif)

**Comment by ThomasWilshaw** [comment]
I'm not quite sure what the problem is here,  the viewer auto scrolls if you move the point to the edge of the view. Could you provide a screen recording of the problem?

**Comment by 111ukasz111** [comment]
> I'm not quite sure what the problem is here, the viewer auto scrolls if you move the point to the edge of the view. Could you
It scrolls to the left without moving the controller circle to the left.

**Comment by ThomasWilshaw** [comment]
I see what you mean now. The smallest movement of a bezier handle causes the viewer to scroll to the side. I can confirm this on Windows 10

**Comment by itsmattkc** [comment]
@111ukasz111 Just as a sidenote, you can upload regular videos to GitHub. Converting them to heavily compressed and low frame rate GIFs like this makes it much harder to understand what's going on.
