### ISSUE TITLE
[NODES] Subtitle node doesn’t allow an input connection

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1707]
**Commit Hash** 
a0db9b5

**Platform** 
macOS 10.14.6 (maybe all platforms)

**Summary**
When trying to connect, for instance, a Value Node set as text to the Subtitle Node it doesn't let you connect it to any parameter.

**Additional Information / Output**
The Subtitle node doesn't expand if you double click on it or try to press the "expand" button

**Comment by itsmattkc** [comment]
This is intentional. Connecting a node would open the possibility of the text changing before the subtitle itself has finished and this is not permissible in any subtitle standard.
