### ISSUE TITLE
[EDIT] Make subtitle section clearer when adding first subtitle clip

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1709]
**Commit Hash** 
a0db9b5

**Platform** 
All

**Summary**
When you activate for the first time the "add subtitle" tool, it's not obvious where actually you need to create the subtitle. After having a look you can guess it is below the audio track but it's not cristal clear.

I would suggest to create the Subtitle track just after selecting the "add subtitle button", this way the user would see the new track created with default label "subtitles 1" and then it would be obvious where to create it.
If the user finally switches tool without creating any subtitle then the track can be automatically deleted (if, of course, the track has no subtitle on it).

**Additional Information / Output**
The previous suggested behavior would only be desirable when in the Timeline View, not in the Nodes View where you can "manually" create your nodes and connections.

**Comment by itsmattkc** [comment]
It does open the subtitle "section" when you mouse over the timeline, but I suppose for some people it would be a little subtle.

**Comment by pgilfernandez** [comment]
I love it, now it's perfect
=)
