### ISSUE TITLE
[PROJECT] Opening the same project that is open does not open the project.

### ISSUE THREAD

**Issue by 111ukasz111** [olive-editor/olive#1710]
**Commit Hash** 
132e637f

**Platform** 
Windows 10 Intelcore i7, Nvidia Geforce 920M

**Summary**
Steps to reproduce:
1.  Open the project.
2. Make some changes.
3.  Open the same project again.

**Additional Information / Output**

**Comment by Simran-B** [comment]
I'm not quite following. What do you expect to happen? Another project tab so that the same project is open twice?

Multi project support is not fully implemented: https://github.com/olive-editor/olive/issues/1351

**Comment by 111ukasz111** [comment]
> I'm not quite following. What do you expect to happen? Another project tab so that the same project is open twice?
> 
> Multi project support is not fully implemented: #1351

Load the previous state from the save.

**Comment by itsmattkc** [comment]
It's pretty obviously intentional that you can't open the same project twice.

Are you looking for a "Revert" function?

**Comment by Simran-B** [comment]
Yeah, revert to the project state of the last save (what's on disk) by re-opening the project. A dedicated option for that in the File menu seems more intuitive to me, but opening an already open project could also trigger a revert. There should be a dialog to ask for confirmation before unsaved changes are discarded.
