### ISSUE TITLE
[EDIT] Olive is freezing forever, after animating in curve editor and moving marker on this media.

### ISSUE THREAD

**Issue by 111ukasz111** [olive-editor/olive#1712]
**Commit Hash** 
132e637f

**Platform** 
Windows 10 Intelcore i7, Nvidia Geforce 920M

**Summary**
Steps to reproduce:
1.Move the curve editing wheels, of several animatable parameters on the curve editor.
2 Move the timeline marker to wav with animated  parameters animated in the curve editor. Olive is freezing forever.

**Additional Information / Output**
![OliveAudioBugfre](https://user-images.githubusercontent.com/20667528/128705874-3f81fc33-0704-457e-873b-0e830a545386.gif)

**Comment by itsmattkc** [comment]
Is this fixed in 0a06fcf67e4311ebab2fc6e29555bb8b0288a4ab?

**Comment by 111ukasz111** [comment]
I don't know.

**Comment by itsmattkc** [comment]
If you can't recreate this, I will assume it's fixed.
