### ISSUE TITLE
[EDIT] Copy and paste keyframes doesn't work in a parameter editor.

### ISSUE THREAD

**Issue by 111ukasz111** [olive-editor/olive#1714]
**Commit Hash** 
132e637f

**Platform** 
Windows 10 Intelcore i7, Nvidia Geforce 920M
Steps to reproduce:
1. Create a keyframe.
2. Select and copy and paste to diferent place.

**Summary**

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
This is a known issue. See #1349 Thanks for the report though :)
