### ISSUE TITLE
Blur rendering broken on Intel 620 

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#172]
Any blur effect results in visual garbage both in preview and in the rendered video. I'm on the Intel 620 chipset.

![2018-12-20 14-27-51](https://user-images.githubusercontent.com/57467/50282646-81a7a880-0464-11e9-8b5e-b682a2a4a327.png)

**Comment by itsmattkc** [comment]
GLSL is notoriously inconsistent depending on the API version/type, driver, OS, etc. so this may be tough to track down. However, if you could send me the output (running from a terminal), that'd be great - it's likely Qt reported an error if it was unable to compile the shader correctly.

**Comment by feeef** [comment]
I have the same issue and the terminal doesn't say much more than : 
`libpng warning: iCCP: known incorrect sRGB profile`

It says that for all filters that I apply but the blur filters are the only ones that don't work as expected. Every other filters work perfectly (and pretty fast) .

I am using mp4 (H.264) rush files.
I have an Intel 520 GPU and I am running Debian testing (if it can help)

**Comment by itsmattkc** [comment]
Hmm from the sounds of it, something about the GLSL code in the blurs isn't sitting right with the particular Intel driver(s) that drive these cards. I'll try out Linux on my laptop to see if it's an issue in general with Intel cards on Linux.

**Comment by prokoudine** [comment]
Full make output: https://paste.gnome.org/pubdq4y6f

**Comment by itsmattkc** [comment]
@prokoudine Are you also getting no terminal output during runtime? (specifically when adding a blur effect) What about when you compile in debug mode?

**Comment by prokoudine** [comment]
> Are you also getting no terminal output during runtime?

Nothing at all

> What about when you compile in debug mode?

That's what I already do -- compile in debug mode :)

**Comment by itsmattkc** [comment]
Hmm alrighty, I'll have to look more into this

**Comment by itsmattkc** [comment]
I've been able to identify an issue with the blurs affecting Intel GPUs and fixed it in 74d343522d3b09864d76c66d88caec4afc25d66b. Let me know if this works for you!

**Comment by prokoudine** [comment]
Looks fixed to me, thanks!

**Comment by itsmattkc** [comment]
Awesome, this seems to be a global issue that Intel GPUs had with one of the things I did in the GLSL code as I was able to confirm it in Windows too. Glad it's fixed now!

**Comment by feeef** [comment]
It is working on my side too but it is pretty slow and sliding the values can completely freeze the UI... 
...but this should be part of another bug :)

**Comment by itsmattkc** [comment]
Yeah the blurs could very likely be optimized further (particularly gaussian), I don't think they're as fast as they could be yet.

As the blurs are done on the GPU, I'm not complete sure about whether they can be processed asynchronously (as to not hang the UI), but optimizing them will hopefully at least negate that a little bit in case they can't.
