### ISSUE TITLE
No audio playback on Ubuntu 18.10 with PulseAudio running

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#173]
Playback of audio doesn't seem to work on my Ubuntu 18.10 system.

There is no sound coming out of the application, the VU meter never lights up.

How can I help you investigate this?

**Comment by itsmattkc** [comment]
Hi, could you try running Olive from a terminal and send the output? It should print information about the audio devices found and the one it's choosing to use.

**Comment by itsmattkc** [comment]
Have you installed `libqt5multimedia5` and `libqt5multimedia5-plugins`? If not, install those and then run `qmake` and `make` again.

**Comment by prokoudine** [comment]
Indeed, libqt5multimedia5-plugins was missing, Adding it fixed the issue, thanks :)

**Comment by itsmattkc** [comment]
Awesome, I should probably have some compile instructions up somewhere to list all of Olive's required dependencies haha

**Comment by romansimakov** [comment]
It seems I have the same issue on Ubuntu 18.10. I've installed Olive from your PPA. I've installed both libqt5multimedia5 and libqt5multimedia5-plugins. In the same time some movies plays audio with the same codec. Can I do something to fix it or I need to build Qlive from sources?

**Comment by itsmattkc** [comment]
@romansimakov Check your selected audio devices - Tools > Preferences > Audio

**Comment by romansimakov** [comment]
It's Default. I also tried default, pusle, but without restart. There is no effect. Also I can see a ton of items in the list. Is there any way to define the right choose?
