### ISSUE TITLE
[EDIT] Keyframes slow everything down

### ISSUE THREAD

**Issue by morrolinux** [olive-editor/olive#1731]
**Commit Hash** 
2794730

**Platform** 
Arch Linux

**Summary**
I've set up a 60fps timeline and applied an input node with 1 keyframe per frame to the transform node of a clip. 
The UI hangs for several seconds each time I touch that clip.

To make sure the issue is the way keyframes are handled, I've done the same using a different approach (with no keyframes involved) and everything went smooth. 

See the demo gif for more details

![demo](https://user-images.githubusercontent.com/20294254/130596960-4e65892a-f167-4371-9dfa-eb77b386c038.gif)

**Additional Information / Output**
- timeline is 60fps 
- keyframes / datapoints are 3052 in both cases (only the first few hundreds are really used as applied 1:1 to the frames of the clip)
- CPU is an i5-8250U

**Comment by Simran-B** [comment]
Matt pushed a minor optimization that you can give a try: https://github.com/olive-editor/olive/commit/4484981d911a47ea250c61152a4cc1f32076f65b

**Comment by morrolinux** [comment]
Much, much better now. 
It still takes up to a second to select the clip but I think we're in "to be expected" territory, given how many frames there are in the node.
Thank you!

**Comment by itsmattkc** [comment]
I believe the remaining lag is from creating/destroying so many UI objects, there was a similar issue with the timeline with multiple clips and I'll probably solve it in a similar way.

**Comment by itsmattkc** [comment]
Largely mitigated as of 74d9c43ff5f301dbe8082046ae892710c857b755
