### ISSUE TITLE
[EDIT] Switching between sequences hangs the UI for up to 10 seconds

### ISSUE THREAD

**Issue by morrolinux** [olive-editor/olive#1733]
**Commit Hash** 
dc66c30

**Platform** 
Arch Linux

**Summary**
I've got two 1h 11m 1080@50p video+audio clips which I've split into five 14 minutes sequences for performance reasons (Olive 0.2 slows down too much to be usable past that length)
Now the problem is switching between those sequences hangs the UI for up to 10 seconds on my 32Gb RAM + Ryzen 9 3900X system.   
![out](https://user-images.githubusercontent.com/20294254/130808454-8176dc47-17bd-4080-bcce-1335d960fe4d.gif)

**Additional Information / Output**
- During the hang, only 1 core is stuck at 100%, the rest is idling.
- Opening a timeline for the first time via the left drawer is fine, only switching between open timelines freezes everything

**Comment by itsmattkc** [comment]
This should be significantly improved in 677277c16d51bcd9aa6073fc71fa8fe4bdbc720e. Can post back if not.
