### ISSUE TITLE
[EDIT] Editing is slow on a 15+ min timeline

### ISSUE THREAD

**Issue by morrolinux** [olive-editor/olive#1734]
**Commit Hash** 
dc66c30

**Platform** 
Arch Linux

**Summary**
When the timeline length is around 10 min, all editing operations start to slow down and it gets increasingly worse past 15 minutes.
Here's an example with a 15 minute timeline made of just one 1080@50 clip:
- If I try to split that clip, it gets done after 2 to 4 seconds
- During that time, one core is stuck at 100%, the rest is idling 
- The background renderer is not working since I'm positioning the playhead in the green zone
- Ripple delete takes about 5 seconds
- The longer the timeline, the worse it gets 
![out](https://user-images.githubusercontent.com/20294254/130812304-c62bef8d-1668-428c-a8b9-168590109165.gif)

**Additional Information / Output**

**Comment by morrolinux** [comment]
There's another variant of this issue which almost seem to happen on even odds, where it looks like the waveform is actually re-built after the cut and you can see all the cores maxed out at 100% for a few seconds until the waveform shows up.
Are you rebuilding the waveform after each cut?

**Comment by morrolinux** [comment]
> It is worth noting that [6bd7bc4](https://github.com/olive-editor/olive/commit/6bd7bc4cca7d2061e6fce334f25fec450f0b0f2b) has introduced a slowdown that can be triggered here

I don't know why 6bd7bc4 was necessary (?) but it does consistently freeze the UI for a couple of seconds each cut I make.
I don't know how slow it got on your end so I wanted to ask if you are planning to improve this in the short term.
Thank you

**Comment by itsmattkc** [comment]
> I don't know why 6bd7bc4 was necessary (?) 

It copies the waveform when a clip is duplicated (e.g. when splitting) so that the split isn't missing a waveform until the next audio render. The copy operation is necessary but ends up taking a substantial amount of time.

> I don't know how slow it got on your end so I wanted to ask if you are planning to improve this in the short term.

If I mention a slow point, then yes, I'm planning to fix it.

**Comment by itsmattkc** [comment]
The slowness from 6bd7bc4cca7d2061e6fce334f25fec450f0b0f2b should be largely addressed now, let me know if you can recreate that original slow down still.

**Comment by morrolinux** [comment]
Yep. Much much better.
 
It does still take 3 seconds to split a clip on the origial infamous project, but it doesn't happen on any new/other project, so that might be for a separate issue if I can figure out what's the deal with that project.

**Comment by itsmattkc** [comment]
Feel free to run `perf` on that slow down too, even if it only shows up in some situations, it's probably worth addressing
