### ISSUE TITLE
[BUILD] Re-enable 'continious' builds for speedup latest nightly downloads

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#1738]
**Commit Hash** 

5b7255b8

**Platform** 

Linux / Debian 10.x

**Summary**

Nightly downloads speed from `https://olivevideoeditor.org/dl/` is horrible: it is `<= 300 kbps`.

- https://olivevideoeditor.org/go.php?type=l64a&hash=5b7255b8

I tried few times with same result - in same time I has no any "download speed issues" with getting assets from GitHub.

I just recommend to re-enable uploading latest nightly builds as a `continuous` pre-release assets to speedup downloads & for mirroring purposes.

**Additional Information / Output**

![olive-dl_speed](https://user-images.githubusercontent.com/13188580/131244052-fa239e5f-bf6a-4409-9289-478e8b7b9f7e.png)

**Comment by itsmattkc** [comment]
GitHub Releases has no support for multiple commits and organizing them in the way we do. We can look into ways to speed up our web server but we have no intention of "re-enabling continuous builds".

**Comment by Symbian9** [comment]
> GitHub Releases has no support for multiple commits

JFTR, I just asks for host *latest* commit builds.

**Comment by itsmattkc** [comment]
It's a wholly inferior system. `uploadtool` has no awareness of whether what it's uploading is the "latest commit" or not. If there are two builds running at the same time and one happens to complete before the other, we have to write extra logic to ensure an old commit doesn't replace a new commit (not to mention `uploadtool` will delete *all* builds if the commit is not the same, often resulting in only one platform appearing).

Additionally, if a commit breaks a certain platform, having multiple commits means you can still access the last commit that did build for that platform. Only having access to the latest commit means if, for example, the Linux release failed to build, it's gone forever and there is no way to download Linux releases anymore.

Again, we have no intention of using GitHub Releases for nightly builds. That being said, I do think I can use GitHub hosting to speed up the downloads from the website, and I will post an update here when that's done.

**Comment by Symbian9** [comment]
> `uploadtool` has no awareness of whether what it's uploading is the "latest commit" or not.

JFTR, Its possible to add such info on each in release description, which also may be updated on each upload.

BTW, If you may speedup your server upload speed then it would be the best solution.

**Comment by itsmattkc** [comment]
The nightly page has been updated to use GitHub hosted packages so the speed should be vastly improved.

**Comment by Symbian9** [comment]
@istmattkc, one more note here: as GitHub Actions produces two variants of AppImage (`clang` and `gcc`) it would be good to show both variants download links on nightly page as next:

- **Linux**
  - Download (clang)
  - Download (gcc)

**Comment by Simran-B** [comment]
There's intentionally just a GCC build. Clang builds are only enabled to catch compile errors that don't occur with GCC. We don't know if there are any notable differences in the binaries produced.

**Comment by Symbian9** [comment]
> There's intentionally just a GCC build... We don't know if there are any notable differences in the binaries produced.

There is a notable difference in 30 Mbytes (more than in "quarter") between both AppImage artifacts: https://github.com/olive-editor/olive/runs/3510829279
  - GCC ~ 125 Mbytes
  - Clang ~ 92 Mbytes

**Comment by Simran-B** [comment]
If those few measly megabytes are a deal breaker then I don't know. It could just be different settings or handling of debug information. It's not notable to me unless there is proof of better performance (or stability, correctness, debuggability, or other metric that actually matters). As long as it's unclear whether Clang builds have any advantage over GCC builds, offering both would just confuse the majority of users.

**Comment by Symbian9** [comment]
> As long as it's unclear whether Clang builds have any advantage over GCC builds

Try to compare internal structure of both AppImages.

To unpack AppImage use command `$ ./*.AppImage --appimage-extract`
