### ISSUE TITLE
split screen video composition

### ISSUE THREAD

**Issue by JohnnyKetch** [olive-editor/olive#1739]
Is there a way to script the composition of multiple videos in split screen?

I'll give you an example. Upload 20 videos of the same resolution from a folder. The program automatically places them for me from left to right, from top to bottom to form a "chessboard".

I'd like to do this terminal thing if possible. I have a macro project and the videos in question could be 5000+

**Comment by itsmattkc** [comment]
There is no way to do this automatically at the moment, the hope is we'll have a Python or JavaScript scripting engine so you can script certain tasks at some point, but that's quite a bit down the line right now. The project files and copy/paste data is simple text (XML), so you can probably write your own script to generate what you want.
