### ISSUE TITLE
Copy/pasting effects stack

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#174]
It would be useful to be able to copy/paste an entire stack of effects or selected part of it from one clip to another. All keyframes' position would then be recounted from target clips' position (not necessarily the best approach). 

As for selecting FX, darktable has something like this: Ctrl+C copies everything, then Ctrl+V just pastes everything, but Ctrl+Shift+V allows selecting which effects will be transferred.

![2018-12-20 14-47-01](https://user-images.githubusercontent.com/57467/50283360-be749f00-0466-11e9-8bfd-113a54138e09.png)

Needless to say, it should be possible to paste into multiple selected clips. And quite possibly Olive should be smart enough to tell a user that pasting video effects to audio clips won't work.

**Comment by prokoudine** [comment]
Tried and can't seem to find a way to do this. Nothing similar in the Edit menu, nothing in the right-click menu for a clip, nothing in the right-click menu for an effect. How do I access it?

**Comment by itsmattkc** [comment]
You should be able to use the standard "Copy" and "Paste" for copying/pasting effects. It should copy effects if the effects panel is focused (I'm planning to make a visual cue for which panel is focused soon).

**Comment by prokoudine** [comment]
Yep, that works! Maybe something to consider: if Olive should overwrite existing applied filters or add new copies, the way it works now. Or just provide a way to merge several instances into one (another idea from darktable).

**Comment by itsmattkc** [comment]
Added the following dialog box in c62d4803fbdcdf05bad55ca3c5b38beabba65bb2:
![image](https://user-images.githubusercontent.com/34096995/50316721-fa157480-050b-11e9-82f9-d2de97db90e5.png)
