### ISSUE TITLE
[RENDER] Sequence Viewer doesn't render

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1741]
**Commit Hash** 
3fccfecd

**Platform** 
macOS 10.14.6

**Summary**
Sequence Viewer doesn't preview anything. It seems that if you add anything to the timeline it renders and caches it but it doesn't show up.

**Additional Information / Output**
Here is the log I get if I launch Olive with a terminal:
<img width="833" alt="opengl_error" src="https://user-images.githubusercontent.com/5942369/132188728-5e9abd2d-f06c-4ac4-8c0f-94e1a728dafa.png">

**Comment by pgilfernandez** [comment]
I can confirm it works again.

Thanks!!

**Comment by Symbian9** [comment]
>  it works again.

Does not works on my PC:

Here is `$ Olive-923b889f-Linux-x86_64.AppImage` - sequence preview does not show nothing non during playback, non when paused:

- ![Screenshot_2022-01-01_09-15-28](https://user-images.githubusercontent.com/13188580/147845887-3ca4180f-5e04-4662-8f93-6c36c1f3a3ad.png)


With software-gl (`$ LIBGL_ALWAYS_SOFTWARE=true ./Olive-923b889f-Linux-x86_64.AppImage`) it seems to show, BUT during playback it does not updates (preview updates only when paused):

- ![Screenshot_2022-01-01_09-17-03](https://user-images.githubusercontent.com/13188580/147845900-2b3cb2f0-f2fd-4087-8d7e-c448da402d3b.png)

System info: 

<details><summary><summary>

```Shell
System:    Host: <filter> Kernel: 4.19.0-18-amd64 x86_64 bits: 64 compiler: gcc v: 8.3.0 
           parameters: BOOT_IMAGE=/boot/vmlinuz-4.19.0-18-amd64 
           root=UUID=<filter> ro quiet splash 
           Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 
           Distro: MX-19.4_x64 patito feo March 31  2021 base: Debian GNU/Linux 10 (buster) 
CPU:       Topology: Dual Core model: Intel Pentium Dual T2330 bits: 64 type: MCP 
           arch: Core Merom family: 6 model-id: F (15) stepping: D (13) microcode: A4 
           L2 cache: 1024 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 bogomips: 6384 
           Speed: 1229 MHz min/max: 800/1600 MHz Core speeds (MHz): 1: 1229 2: 1163 
           Vulnerabilities: Type: itlb_multihit status: KVM: Vulnerable 
           Type: l1tf mitigation: PTE Inversion 
           Type: mds status: Vulnerable: Clear CPU buffers attempted, no microcode; SMT disabled 
           Type: meltdown mitigation: PTI 
           Type: spec_store_bypass status: Vulnerable 
           Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization 
           Type: spectre_v2 mitigation: Full generic retpoline, STIBP: disabled, RSB filling 
           Type: srbds status: Not affected 
           Type: tsx_async_abort status: Not affected 
Graphics:  Device-1: AMD RS600M [Radeon Xpress 1250] vendor: Samsung Co driver: radeon v: kernel 
           bus ID: 01:05.0 chip ID: 1002:7942 
           Display: x11 server: X.Org 1.20.10 driver: ati,radeon 
           unloaded: fbdev,modesetting,vesa resolution: 1280x800~60Hz 
           OpenGL: renderer: ATI RS600 v: 2.1 Mesa 18.3.6 direct render: Yes 
Audio:     Device-1: AMD SBx00 Azalia vendor: Samsung Co driver: snd_hda_intel v: kernel 
           bus ID: 00:14.2 chip ID: 1002:4383 
           Sound Server: ALSA v: k4.19.0-18-amd64 
Drives:    Local Storage: total: 111.79 GiB used: 31.00 GiB (27.7%) 
           ID-1: /dev/sda vendor: Toshiba model: MK1246GSX size: 111.79 GiB block size: 
           physical: 512 B logical: 512 B speed: 1.5 Gb/s serial: <filter> rev: 2A scheme: MBR 
Partition: ID-1: / raw size: 34.00 GiB size: 33.22 GiB (97.70%) used: 31.00 GiB (93.3%) fs: ext4 
           dev: /dev/sda1 
           ID-2: swap-1 size: 1.75 GiB used: 6.0 MiB (0.3%) fs: swap swappiness: 15 (default 60) 
           cache pressure: 100 (default) dev: /dev/sda5 
Info:      Processes: 178 Uptime: 57m Memory: 1.70 GiB used: 1.19 GiB (69.9%) Init: SysVinit 
           v: 2.93 runlevel: 5 default: 5 Compilers: gcc: 8.3.0 alt: 8 Shell: quick-system-in 
           running in: quick-system-in inxi: 3.0.36 
```

**Comment by itsmattkc** [comment]
Am I correct in understanding your GPU (Radeon Xpress 1250) is from 2006? I don't think you should expect 0.2 to run properly on that

**Comment by Symbian9** [comment]
>  I don't think you should expect 0.2 to run properly on that.

I may agree with this on use Olive without software gl.

But if launching `$ LIBGL_ALWAYS_SOFTWARE=true ./Olive-923b889f-Linux-x86_64.AppImage` preview should be rendered correct during playback, even by cost of high CPU usage.
