### ISSUE TITLE
[CRASH] Adding audio to math node crashes program

### ISSUE THREAD

**Issue by Quackdoc** [olive-editor/olive#1745]
**Commit Hash** 
9843fd47

**Platform** 
Windows 10, Arch linux latest

**Summary**
Olive will crash when adding audio in into a math or merge node.

**Steps to Reproduce**

1. Create a math or merge node
2. add audio track as input

<details><summary><strong>Crash Report</strong></summary><pre><code>

No crash report, Stack trace says no stack, program closed successfully despite program being unresponsive sometimes closing itself. sometimes full crashing.

</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
As far as I can tell, this is fixed now. But let me know if it persists.
