### ISSUE TITLE
[CACHE] preroll cache before current frame

### ISSUE THREAD

**Issue by samytichadou** [olive-editor/olive#1746]
**Commit Hash** 9843fd47

**Platform**  Windows 10

**Summary** hi, I had to edit some footage in full resolution, so cache was quite laggy (1080p60), and I Found that the cache order could be weird sometimes. 
For example, when I Move the playhead on an uncached frame, olive tried to cache some preroll before the current frame. This behavior leads to wait until the current frame is properly shown to the user. 
In my opinion, it is better to show the current frame first, let the user knows where he is in the edit, then cache some preroll frames. 

**Additional Information / Output**

**Comment by sobotka** [comment]
Please include the commit hash.

**Comment by samytichadou** [comment]
Hi, not really familiar with these sorry, where do i find the commit hash for this issue ?
Thanks

**Comment by Simran-B** [comment]
Read the issue template text:

`**Commit Hash** <!-- 8 character string of letters/numbers in title bar or Help > About dialog (e.g. 3ea173c9) -->`

**Comment by samytichadou** [comment]
oh yes, sorry my bad, just edited the first post ! Is it preferable to create a new issue ?

**Comment by Simran-B** [comment]
No, editing is fine. The issue is reopened now.

**Comment by itsmattkc** [comment]
You can change this yourself. In preferences, there's a setting for "cache behind" and "cache ahead". If you set "cache behind" to 0, it will just cache from the playhead onwards.

I should mention there are plans to revise the cache system so it will more "intelligently" cache the whole sequence in the background. But that's a little further down the line right now.

**Comment by samytichadou** [comment]
Great ! thanks for the information, didn't know about it !
And yeah new cache system with background caching would be awesome ! Cheers
