### ISSUE TITLE
[CACHE] "Auto Caching" sequence setting only affects video

### ISSUE THREAD

**Issue by morrolinux** [olive-editor/olive#1747]
**Commit Hash** 
6d576a3

**Platform** 
Arch Linux

**Summary**
In sequence settings you can turn off automatic disk caching. This setting however, only affects video caching and not both video and audio.

Currently there is no way to disable audio caching which is a considerable performance let down as mentioned in more detail in #1742 .

**Additional Information / Output**
Proposed solution:
Add an option in timeline settings to disable audio caching as well

**Comment by itsmattkc** [comment]
I don't think this is necessary. I think we can reach a one size fits all with audio.
