### ISSUE TITLE
[BUILD] Could not initialize GLX

### ISSUE THREAD

**Issue by Master811129** [olive-editor/olive#1748]
**Commit Hash** 

**Platform** Manjaro Linux

**Summary** I can't start the latest version of olive it does not open up (flatpak) :

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/37829730/134052402-08eede15-2565-4bc0-b3c0-219e83db2c38.png)

**Comment by Simran-B** [comment]
What version is that (commit hash)?
Hardware and graphic drivers?

Note that the AppImage nightlies are the only official means of distribution. Flatpaks are not maintained or supported by the team.

**Comment by Master811129** [comment]
@Simran-B

> What version is that (commit hash)?

I ran `flatpak run org.olivevideoeditor.Olive --version `
I think this is the hash version `Olive (April 2019 | Alpha | 2c700ca)`

>  Hardware and graphic drivers?

NVIDIA GTX 750ti
Intel core i5 6400

**Comment by Simran-B** [comment]
0.1.x from 2019 is not supported anymore. Try the latest 0.2 nightly build and check if that works.

**Comment by Master811129** [comment]
I downloaded the appimage and the app successfully opened
