### ISSUE TITLE
Clips do not get added to Olive in the correct order

### ISSUE THREAD

**Issue by kburchfiel** [olive-editor/olive#1749]
**Commit Hash** 

**Platform** 

**Summary**

I have 97 .mp4 clips that I wish to add to my project. I have the videos sorted by their modified date in the file list on the lower left of the editor. However, when I highlight all of them and drag them into the timeline, they show up in an unexpected order that appears jumbled/random. Is this a bug? If not, how can I import the clips so that they all show up in the order that they were modified (or alphabetically if needed)?

**Additional Information / Output**

**Comment by Simran-B** [comment]
See #1751

**Comment by kburchfiel** [comment]
I retried the file additions with the most recent version and found that they were now added in the order I expected. Thank you for the prompt fix!
