### ISSUE TITLE
Thumbnails in the Project pane

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#175]
It would be useful to have optional thumbnail view (next to the current list/table view) in the Project pane for when file names are not human-readable, and previewing each one is not the best option.

**Comment by itsmattkc** [comment]
Check out the `iconview` branch. It should be a fairly complete (right click Project panel > Icon View) but let me know if you have any suggestions. I also realized I could use the thumbnails in the standard Tree View too so I've also done that.

Let me know what you think!

**Comment by prokoudine** [comment]
```
project/sourcescommon.h: In constructor ‘SourcesCommon::SourcesCommon(Project*)’:
project/sourcescommon.h:34:14: warning: ‘SourcesCommon::project_parent’ will be initialized after [-Wreorder]
     Project* project_parent;
              ^~~~~~~~~~~~~~
project/sourcescommon.h:31:12: warning:   ‘Media* SourcesCommon::editing_item’ [-Wreorder]
     Media* editing_item;
            ^~~~~~~~~~~~
project/sourcescommon.cpp:19:1: warning:   when initialized here [-Wreorder]
 SourcesCommon::SourcesCommon(Project* parent) :
 ^~~~~~~~~~~~~
project/sourcescommon.cpp: In member function ‘void SourcesCommon::mouseDoubleClickEvent(QMouseEvent*, const QModelIndexList&)’:
project/sourcescommon.cpp:145:56: warning: unused parameter ‘e’ [-Wunused-parameter]
 void SourcesCommon::mouseDoubleClickEvent(QMouseEvent *e, const QModelIndexList& selected_items) {
                                           ~~~~~~~~~~~~~^
project/sourcescommon.cpp: In member function ‘void SourcesCommon::reveal_in_browser()’:
project/sourcescommon.cpp:258:5: error: ‘QDesktopServices’ has not been declared
     QDesktopServices::openUrl(QUrl::fromLocalFile(m->url.left(m->url.lastIndexOf('/'))));
     ^~~~~~~~~~~~~~~~
make: *** [Makefile:2161: sourcescommon.o] Error 1
```

What do I need to install? :)

**Comment by itsmattkc** [comment]
Huh... funnily enough I don't think you have to install anything, I think I just missed an include (interesting that it didn't cause any issues for me). Try the newest commit in `iconview` :)

**Comment by prokoudine** [comment]
Builds now, thanks! :)

So, a few ideas for the icon view mode...

1. Ellipsize long file names.
2. Always try to show multiple previews in a row (currently just one). Basically, the current preview size slider can control the amount of previews in a row (darktable does that), and their actual size will be computed from 1) width of the project panel, and 2) amount of preview per row. that way, there will be no weird blank spaces to the right of the last preview in the row, and everything will be wrapped around nicely. 
3. You can try to make the iconview more informative while not overloaded. E.g. show clip length next to file name. I think I can make a mockup for you there, if you wish.

**Comment by itsmattkc** [comment]
Yes, a mockup of 3 would be helpful I think. The other 2 should be fairly easy to achieve.

**Comment by prokoudine** [comment]
Here you are :) It's a quick one though

![project-bin-mockup](https://user-images.githubusercontent.com/57467/50407708-b6fa2080-07ed-11e9-926e-bb9cda108fe9.png)

**Comment by prokoudine** [comment]
There are some behavior considerations here though. E.g. what happens when the preview is too small, because there are too many previews in a row, or the project bin is not too wide? Should Olive figure out when to drop duration (and then file name)? I don't have an answer yet :)

**Comment by prokoudine** [comment]
Also, the detailed view in the mockup is probably information overload :)

**Comment by prokoudine** [comment]
Actually, now that I come to think of it, there might be uses for zoom controls in detailed view as well: e.g. show less details (in steps) and less top/bottom padding for wide frames (21:9), or show more details and less left/right padding for 4:3 frames.

**Comment by NathanSalapat** [comment]
Not sure if I should report this here or open a new issue.
![olive text clipping](https://user-images.githubusercontent.com/8930456/52184556-80df9180-27da-11e9-9f44-42be027a2b8a.png)
Currently, using the latest version available from the ppa on Linux Mint, when viewing icons in the project pool zooming past a certain point pushes the text under other items, or out of the rendered area.

**Comment by itsmattkc** [comment]
Implemented in 54518a5896efc9c9c4477a0e6ae4724d6e9e20fc

**Comment by kolaente** [comment]
Is this the way it should look like?

![image](https://github.com/olive-editor/olive/assets/13721712/62a068b1-5850-4c0f-9d03-762b44778673)

From reading this issue it seems like it should show a thumbnail for each of these clips? Or do I need to enable that somewhere?

**Comment by prokoudine** [comment]
> Is this the way it should look like?
> 
> ![image](https://user-images.githubusercontent.com/13721712/262464185-62a068b1-5850-4c0f-9d03-762b44778673.png)
> 
> From reading this issue it seems like it should show a thumbnail for each of these clips? Or do I need to enable that somewhere?

It's one of those unfinished things after one of the rewrites of the program.
