### ISSUE TITLE
Clips added to timeline out of order when I dragged and dropped them from file list

### ISSUE THREAD

**Issue by kburchfiel** [olive-editor/olive#1751]
**Commit Hash** 
**9843fd47**

**Platform** 
**Windows 10**
**Summary**

When I dragged and dropped a set of 97 .mp4 clips into my timeline from the file list on the bottom left of the default layout, I expected that they would be added either in the order that they were sorted or in alphabetical order. Instead, the clips were added in what appeared to be a jumbled order.

Is this a bug? If not, how does Olive determine the order that clips will appear in a timeline?

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Usually it's fairly frowned upon to make the same issue again if the first one gets closed.

That being said, this is now fixed in f78a4643f3433f85e0e5651c7aa00e7efa3102a9.

**Comment by kburchfiel** [comment]
Apologies--when I looked at my Issues list on GitHub, it was filtered to only show open issues, so I thought I had forgotten to post my initial issue. That was why I accidentally double-posted it. Thank you for the prompt response!
