### ISSUE TITLE
[NODES] VST plugins load but the UI does not appear and there is no way to use sidechains.

### ISSUE THREAD

**Issue by DAMO238** [olive-editor/olive#1753]
**Commit Hash** 
0ac9dd9

**Platform** 
Arch

**Summary**
Loading, for example, the vst2 version of lsp sidechain compressor (stereo) works fine. However, there is no way to direct the sidechain from one of the other audio tracks into the plugin, thus rendering it useless. Additionally, when clicking the button to show the interface, the UI does not load.

**Additional Information / Output**

**Comment by Simran-B** [comment]
0.1.x is not supported anymore. 0.2.x does not have support for VST plugins and everything in the direction of advanced audio processing is currently out of scope. This is better left to DAWs.

**Comment by DAMO238** [comment]
I am actually an idiot... I should have checked that rather than assuming I was up to date. Sorry for wasting your time.
