### ISSUE TITLE
[NODES] when importing a file with multiple audio tracks, only the 1st audio track is used in the timeline

### ISSUE THREAD

**Issue by brendaningram** [olive-editor/olive#1754]
**Commit Hash** 

42ce950e

**Platform** 

Debian 11

**Summary**

I use OBS to record videos. I record the desktop audio (e.g. from a DAW) into track 1, and voice over from my mic into track 2. After I have opened Olive, imported the clip, when I drag the clip into timeline, 2 tracks are (correctly) created, but both tracks will (incorrectly) play the first audio track.

**Additional Information / Output**

Kdenlive, Lightworks, VLC all show the files with correctly separate audio tracks.

The file output from OBS is an x264 MKV. I have attached a sample file to this issue.

The node editor correctly shows 2 audio nodes - there just seems to be no way to differentiate the audio clip nodes or to specify which audio track they belong to.

Thanks for your great work with Olive :)

[2021-09-30 11-45-29.mkv.gz](https://github.com/olive-editor/olive/files/7256091/2021-09-30.11-45-29.mkv.gz)

**Comment by itsmattkc** [comment]
Here's how to override, select the volume node, expand the "Connected to Media" section, and choose the other audio stream:
![image](https://user-images.githubusercontent.com/34096995/135392815-3e9cd21d-cb58-45d6-8b56-c65257eab9f5.png)

However the fact that this doesn't happen automatically is indeed a bug.
