### ISSUE TITLE
[BUILD] Olive 0.2 won't open on macOS 11.x Hackintosh

### ISSUE THREAD

**Issue by n8binus** [olive-editor/olive#1755]
**Commit Hash** 
I don't know what "commit hash" means. Is it this? : Version: 42ce950e (Sep 29 2021 11:23:01 AM}

**Platform** 

I'm on MacOS Big Sur 11.6 on an Intel Hackintosh.

**Summary**
Olive 0.2 won't open

**Additional Information / Output**
I downloaded Olive 0.2 and installed it in Applications.
I opened my security and privacy settings to allow it to open.
I clicked "open" when Apple's pop up about "cannot verify the developer" came up.
Nothing happened. I tried multiple times, restarting, etc.
??????????????????

**Comment by Simran-B** [comment]
macOS 10.15 is the minimum required operating system version for the latest Olive builds. You will need to upgrade to use the 0.2 nightlies. Or build Olive as well as all its dependencies yourself and set a lower deployment target version, however, I'm not sure if everything can be compiled for your old macOS version.

**Comment by pgilfernandez** [comment]
Big Sur 11.6 is the most modern version...
;)

**Comment by itsmattkc** [comment]
It was another library path issue (there always seems to be at least a few on macOS). I've added an automated loop to the CI that should permanently solve this as of 07b0f36d8e0ea110d7400561fd3480bbbc15666d

**Comment by n8binus** [comment]
It opens!  THANKS!
