### ISSUE TITLE
[UI] Color chooser: provide a way to input hex color notation and/or a color picker

### ISSUE THREAD

**Issue by morrolinux** [olive-editor/olive#1757]
**Commit Hash** 
7f36ac9f

**Platform** 
Any

**Summary**
Currently user can only choose color from a wheel or by inputting RGB values in a 0..1 interval, which makes it really cumbersome to input a color from an external program, pallette or color picker:

![image](https://user-images.githubusercontent.com/20294254/135581626-e6a9e8b8-0df6-463d-b1ce-71a8fd3f113a.png)

It would be nice to have a built in color picker and an input for hex color coding as well

**Additional Information / Output**

**Comment by elsandosgrande** [comment]
1. Could you elaborate on “color picker”? I mean, isn't that just the color wheel as seen in the screenshot?

2. While it is true that it's harder to share colors with most applications with the current system, the current system is the only one that's reliable and truly color accurate across all color spaces and bit depths. Given that color accuracy is one of the biggest selling points of Olive, I think that you'll just have to use some online converter for color sharing; they likely assume that you're dealing with sRGB colors, so it's not an amazing solution.

**Comment by morrolinux** [comment]
1. I mean a tool that allows me to pick a colour from any pixel on the screen. Like if I want to create a solid with a colour that matches the background of my video, I would be able to "pick" the colour I need with a mouse click on the image. If it's not a colour picker I don't know what it's called, but you can find it in basically any graphics related program.
2. Well I get your point but in the end if I'm working with more than just olive and I've got no other option but to convert an hex colour code to RGB 0..255 by myself and then manually divide each value of the triplet by 255 to get the only coding Olive can read and input each 0..1 value separately... The result is the same but I've only wasted a bunch of time.

**Comment by sobotka** [comment]
> I mean a tool that allows me to pick a colour from any pixel on the screen. Like if I want to create a solid with a colour that matches the background of my video, I would be able to "pick" the colour I need with a mouse click on the image. If it's not a colour picker I don't know what it's called, but you can find it in basically any graphics related program.

This already exists, and provides both internal light model values, as well as the nonlinearly encoded values.

> Well I get your point but in the end if I'm working with more than just olive and I've got no other option but to convert an hex colour code to RGB 0..255 by myself and then manually divide each value of the triplet by 255 to get the only coding Olive can read and input each 0..1 value separately... The result is the same but I've only wasted a bunch of time.

And that is wrong and doesn’t work and will not yield correct values, so why would you expect a piece of software to do something flatly incorrect that seeks to actually properly manage colourimetric information?

**Comment by morrolinux** [comment]
I'm attaching an example of what I meant by "colour picker"

https://user-images.githubusercontent.com/20294254/135650188-86413305-050f-4c90-b7d1-abe6120382d3.mov

**Comment by morrolinux** [comment]
> This already exists, and provides both internal light model values, as well as the nonlinearly encoded values.

Can you show me where to find it? 

> And that is wrong and doesn’t work and will not yield correct values, so why would you expect a piece of software to do something flatly incorrect that seeks to actually properly manage colourimetric information?

IDK I'm working with screen recordings an I just needed that. It worked perfectly but it was a huge waste of time.

**Comment by sobotka** [comment]
> It worked perfectly but it was a huge waste of time.

It doesn’t work perfectly and is flatly wrong with footage. For an assumed BT.709 signal to sRGB, it creates the illusion of working, but it doesn’t.

The approach is fundamentally problematic.

**Comment by morrolinux** [comment]
So what if I need to input an sRGB hex colourcode? 

And can you show me where is the screen colour picker you were talking about?

**Comment by sobotka** [comment]
It was in the picker tab at one point.

**Comment by morrolinux** [comment]
Yeah I remember that too, but now it's gone. That's why I've opened the issue.

BTW
![image](https://user-images.githubusercontent.com/20294254/135652168-a4db3754-e4eb-465b-9cde-3589d9a2dd47.png)

This is Davinci Resolve, a professional NLE with builtin accurate color grading capabilities. 
If I create a "solid" clip and open the color picker I can easily input an HTML sRGB color from another program. 
I don't know how they do it or if it's problematic to do so, but it's a useful feature every software has and I've never had a problem with it. Maybe it was just "good enough" so I never noticed any shifting.

**Comment by sobotka** [comment]
Resolve has a hard coded backbone, which makes it easier to deal with this. It’s also janky as fuck in points, and the “management” has some issues ever since they went consumer after the BM purchase.

**Comment by elsandosgrande** [comment]
> I'm attaching an example of what I meant by "colour picker"
> colour.picker.mov

Oh, that. I've always heard that being referred to as “the eyedropper” or “the dropper tool” 😅

Regarding the entire colour panel discussion, at the end of the day, even if support for hex and zero-through-two-fifty-five were desirable for the project and something worth pursuing, the foundation is still being laid down, which means that Olive is likely not in the best position to start pursuing this at present.

**Comment by morrolinux** [comment]
> Oh, that. I've always heard that being referred to as “the eyedropper” or “the dropper tool” sweat_smile

Yep, that's it! I always called it "color picker" even in my native language and only now I learn it's actually called another way ahah

> Regarding the entire colour panel discussion, at the end of the day, even if support for hex and zero-through-two-fifty-five were desirable for the project and something worth pursuing, the foundation is still being laid down, which means that Olive is likely not in the best position to start pursuing this at present.

Admittedly, I don't know what it takes to properly implement this feature on Olive, but If we can get the ..ehm.. `dropper tool` back it's probably not too much of a deal since one could simply pick the screen color and work around this. But then again, isn't that the opposite face of the same problem? I don't know.

**Comment by sobotka** [comment]
This is actually a much deeper rabbit hole. The stuff that comes out of your display needs to be heavily massaged to achieve different rendering intentions.

Display light back and forth to display light is much more direct, but still complex. Think about wider gamut display lights versus sRGB; the ratios of lights, like paint, need to change to match the same stimulus across displays.

Even with that complexity, for footage it’s a wholly different nightmare, as it is no longer display light, and rather a reconstruction of open domain stimulus light. Zero to surface of sun intensity.

It is really a tricky surface. Baby steps… get the sampler working properly…

**Comment by itsmattkc** [comment]
It is a bit of a rabbit hole.

Hex is, by definition, 8-bit and none of the color in Olive is 8-bit, hence why there isn't a hex. Though it may be possible to have a hex input in the UI and just convert it to float values (on the input tab only, since "input" colors aren't in reference space and I believe should only be 0.0-1.0). Users would have to be aware what color space this hex value is (likely sRGB) and make sure it's entered correctly, but they have to do that anyway when entering float 0.0-1.0 values on the input tab.

And yeah we don't have a picker yet. Implementing it on for the viewer would actually be dead simple because we already have functionality for the pixel sampler that can grab the RGB values in reference space, there's just no automated way of bringing them into the dialog yet. For any other part of your screen would be fairly challenging, but most (if not all) of the time they'd be picking from the viewer I think.

**Comment by morrolinux** [comment]
> For any other part of your screen would be fairly challenging, but most (if not all) of the time they'd be picking from the viewer I think

Indeed. It's probably not even essential to have a "whole screen" picker if you can input a hex value since an external program can be used for that :)

**Comment by sobotka** [comment]
> (on the input tab only, since "input" colors aren't in reference space and I believe should only be 0.0-1.0)

Folks also need to input emissions etc.

Getting pickers right is a massive challenge. Doable, but way, way more challenging than most folks erroneously believe.
