### ISSUE TITLE
[CACHE] "Sequence -> cache sequence in/out" doesn't work if "AutoCache" is disabled in sequence settings

### ISSUE THREAD

**Issue by morrolinux** [olive-editor/olive#1758]
**Commit Hash** 
7f36ac9f

**Platform** 
Arch Linux

**Summary**
At this current stage cache can't keep up with playback on my machine so I've disabled it.
Now the only issue is I sometimes need to cache specific portions of the timeline which otherwise would not render smoothly in real-time (like keyframe animations) and so I mark in and out points on the timeline, go to "Sequence -> cache sequence in/out" and expect the program to cache just that part, but this doesn't happen unless I re-enable "Auto Caching" in the sequence settings, let it render that part and then I need to manually disable "Auto Caching" once again.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Fixed in 4125f41d1f0479a686939302f96ef7b2e3c2cc9d
