### ISSUE TITLE
Long file names and file names with Cyrillics not supported

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#176]
As you can see on the screenshot below, Olive doesn't like files with long names (JPG file at the top) and files with Cyrillic letters in their names (PNG and WebM files at the bottom).

![2018-12-20 15-37-36](https://user-images.githubusercontent.com/57467/50285495-63927600-046d-11e9-9fa8-98249dbfeaed.png)

**Comment by itsmattkc** [comment]
ef3ff6f0c4333c9dfd01c62fa295105738066ba5 should fix the issues with Cyrillic. Not sure about the long filename one though, I wasn't able to recreate that. What's the error when you hover over the red X?

**Comment by prokoudine** [comment]
> What's the error when you hover over the red X?

Says "Could not open file - no such file or directory".

**Comment by itsmattkc** [comment]
Theoretically yes, it should work for all languages (I also tested with Chinese and Japanese but not Portuguese). What's the error when you hover over the X?

**Comment by manokara** [comment]
The same: "no such file or directory". The files are not corrupted or anything, I can load them in Kdenlive just fine. Very weird...

**Comment by itsmattkc** [comment]
Interesting, I also can't recreate the issue with a similar path (on Windows). I'll have to test this a little more.

**Comment by itsmattkc** [comment]
I also cannot recreate it with the same path on Linux. Are you sure you're on the `alpha` branch?

**Comment by manokara** [comment]
Oh, I was compiling on master. Didn't notice that the commit was on the alpha branch, sorry. It works fine now!

**Comment by itsmattkc** [comment]
Awesome, no worries glad it's fixed!
