### ISSUE TITLE
Blending mode has no effect once a filter is applied

### ISSUE THREAD

**Issue by feeef** [olive-editor/olive#177]
I am trying to do a Bleach Bypass effect by duplicating a clip, placing the duplicated clip on top of the original one in the timeline, setting its blending mode to overlay and making it black and white.

The overlay blending mode works OK until I add a filter that lets me lower the saturation to 0. The top clip is then fully visible and no blending mode is taken into account.

My timeline : 
![screenshot from 2018-12-21 10-46-11](https://user-images.githubusercontent.com/383399/50336256-fedb2800-050d-11e9-8c8f-6d2a44f41ea2.png)

Simple overlay (color is visible) : 
![screenshot from 2018-12-21 10-47-15](https://user-images.githubusercontent.com/383399/50336282-161a1580-050e-11e9-96d2-74547c712850.png)

Adding a filter (no more overlay) : 
![screenshot from 2018-12-21 10-47-31](https://user-images.githubusercontent.com/383399/50336312-2c27d600-050e-11e9-8213-49d96e46ea51.png)

**Comment by itsmattkc** [comment]
fb36c79eeadb987d3143d69dcdfcff7b9781268e should fix this (make sure you switch to the `alpha` branch)
