### ISSUE TITLE
[EDIT] Olive 0.2 nightly Linux version Timeline live video not accurately displaying

### ISSUE THREAD

**Issue by Rstation4** [olive-editor/olive#1784]
Linux Mint Cinnamon 20.2
Cinnamon Version : 5.0.6
Linux Kernel: 5.4.0-89-generic
RAM: 5.8 GiB
CPU: AMD Ryzen 3 

Olive: Nightly Build  0.2 version cf1bd65b (Oct 25 2021 4:31:08 PM)

The timeline live video does not display accurately when selecting frames. When I had first used this new nightly build it had crashed on me after some usage with a very short clip that I had trimmed.

**Comment by itsmattkc** [comment]
What?

**Comment by sobotka** [comment]
Feel free to provide an actual actionable case here.

**Comment by Rstation4** [comment]
If this is how you respond to an issue then you people can go fuck yourselves. Im not wasting my time with you fucking neckbeards.

**Comment by sobotka** [comment]
Re-read your post and try to deduce what is going on from what you’ve presented. If it isn’t actionable and clear, **how the fuck do you expect anyone to figure it out you stupid motherfucker**?

**Comment by Simran-B** [comment]
You aren't following the rules (fill out the issue template), still haven't provided a reasonably detailed description of the problem and steps to reproduce, and also insulted the people that work on the project for free. If someone is wasting time then it's you wasting our time.
