### ISSUE TITLE
[BUILD]  i just compiled olive in my phone 

### ISSUE THREAD

**Issue by b-aaz** [olive-editor/olive#1786]
**Commit Hash** ??!?wot??

**Platform** 
Aarch64 termux arch proot 

**Summary**

Hi 👋 so I managed to compile the normal version of olive on the aur 
In a aarch64 Platform and it's really enjoyable to to edit videos in your phone 😄 
The only thing that I did was to add aarch64 to the Platforms variable in the PKGBUILD file it took a eternity to compile and my phone was on fire but everything worked perfectly afterwards and there was no errors 
So I think it's OK to add aarch64 to the Platforms?
**Additional Information / Output**
The olive-git failed to compile

**Comment by elsandosgrande** [comment]
@b-aaz This kind of thing — suggesting new features or options and discussing Olive in general — is what the Discord server is for.

By the way, the few digits and letters next to the tick mark represent the hash of, in this case, the currently latest commit, also known as the commit hash:
![image](https://user-images.githubusercontent.com/40576902/140030442-fc078719-6d75-4de8-8ce8-4ad885aaed1f.png)

**Comment by itsmattkc** [comment]
We don't maintain the AUR package. Please talk to them instead of us.
