### ISSUE TITLE
[PROJECT] Import not working at all

### ISSUE THREAD

**Issue by arunkumaraqm** [olive-editor/olive#1787]
**Commit Hash** 
`cf1bd65b`

**Operating System** 
Ubuntu 20.04

**Summary**
I tried importing an mp4 file, an avi file, and an mkv file and receive an import error in each case.

**Additional Information / Output**
`The following files failed to import. Olive likely does not support their formats.`

**Comment by itsmattkc** [comment]
The error is fairly self-explanatory. Where did you get the build from? What codecs are your videos? Is your build compiled with the codecs you need?

I can confirm the latest AppImage will read libx264 videos in all the containers you mentioned.

**Comment by arunkumaraqm** [comment]
Fixed after a reboot of my computer. I was also experiecing issues with ffmpeg at the same time.
