### ISSUE TITLE
Image sequence loaded as missing clip

### ISSUE THREAD

**Issue by feeef** [olive-editor/olive#179]
I have imported a PNG image sequence in my project and everything worked fine. 

The path to my image sequence is : 

> seq/logo/logo_0001.png
> seq/logo/logo_0002.png
> ...

After closing my project and reopening it, the image sequence has not been loaded. 

The output says : 

> Could find no file with path 'seq/logo/logo_%04d.png' and index in the range 0-4

**Comment by itsmattkc** [comment]
Try switching to the `alpha` branch, this issue was addressed in 576d3f00984ad57d87c30daf6731d795f7262720

**Comment by feeef** [comment]
I confirm that it works on the alpha branch.

Thank you!

**Comment by feeef** [comment]
Although the bug is fixed on normal usage, I have been able to reproduce it after having a crash of the application and loading the recovered file.

On the recovered file, the png sequence was found as missing. Saving and reopening the file didn't help.

**Comment by feeef** [comment]
Thank you @itsmattkc !

**Comment by brendanhowell** [comment]
I'm the latest AppImage (2530608ca7935664874ebe86ca3531e026580b30) and I am getting the original bug when I try to import an image sequence.

**Comment by itsmattkc** [comment]
@brendanhowell The original issue was this error occurring after the project was saved and later re-loaded. Are you experiencing that issue, or getting the error when you actually import the image sequence initially?

**Comment by brendanhowell** [comment]
Ah yes indeed. It fails on the initial import. Sorry, I should have read closer. I can file a new issue if you like. The error message in the tooltip is 
`Filename: /home/mute/Pictures/dscf%04d.jpg `
`Could not open file - No such file or directory`

**Comment by itsmattkc** [comment]
What's the actual file name of the image you're trying to import?

**Comment by brendanhowell** [comment]
dscf2636.jpg

**Comment by brendanhowell** [comment]
The full path is `/home/mute/Pictures/2018/12/dscf2636.jpg`
I suspected it could be capitalization but I also tried in a path with all lower-case it has the same problems.

I also just had a look in the debug log and there were quite a few lines with:
`[WARNING] QFileInfo::absolutePath: Constructed with empty filename (:0, ) `
