### ISSUE TITLE
[PLAYBACK] Screen turns off during long playback

### ISSUE THREAD

**Issue by ThomasWilshaw** [olive-editor/olive#1791]
**Commit Hash** 
b02bc4c

**Platform** 
Windows (but probably effects other OSs)

**Summary**
On long playbacks the screen goes to sleep as there is no user intput.

**Possible Solution**
This will probably require a per OS fix. On Windows at least it looks like we can use `SetThreadExecutionState` ([see](https://stackoverflow.com/questions/3665332/how-do-i-prevent-screen-savers-and-sleeps-during-my-program-execution) for details). 

I think we want the screen to never sleep in fullscreen mode and to also never sleep during playback in normal mode.

**Comment by ThomasWilshaw** [comment]
For Mac see [this](https://stackoverflow.com/questions/8460033/what-is-the-correct-way-to-prevent-sleep-on-os-x) possibly

**Comment by itsmattkc** [comment]
Ah thanks for pointing this out. I can try to implement this on macOS (and also figure out why the CI is failing)

**Comment by ThomasWilshaw** [comment]
No problem, I had no idea where to start with Mac and Linux and can't test it anyway. Are you happy with the way I've done it in Windows?

**Comment by itsmattkc** [comment]
Yeah that seems to be the ideal way. Mac should be fairly straightforward too.

Linux will be a lot tougher because it's probably down to the DE/display server/distro. It'll probably be impossible to target them all (but I guess people can PR for whatever setup if they wish).

**Comment by ThomasWilshaw** [comment]
Cool, I'll merge it then.

Some possibly useful links:
https://stackoverflow.com/questions/31498114/how-to-programmatically-prevent-linux-computer-from-sleeping-or-turning-on-scree
https://marc.info/?l=mplayer-dev-eng&m=114468011701366&w=2

**Comment by itsmattkc** [comment]
Yeah those will probably work, but they're all X11 (or GNOME) based so that'll just be something we'll have to keep in mind.

**Comment by ThomasWilshaw** [comment]
Haha, I'll  not even pretend to understand Linux.
