### ISSUE TITLE
[CRASH]  Won't start on Windows 10

### ISSUE THREAD

**Issue by omeritzics** [olive-editor/olive#1794]
**Commit Hash** 0afbad6

**Platform**
Windows 10

**Summary**
Olive does not start up on Windows 10, when using version 0.2.

**Steps to Reproduce**

1. Download Olive 0.2 and install it on Windows 10
2. Try to open Olive

<details><summary><strong>Crash Report</strong></summary><pre><code>
Operating system: Windows NT
                  10.0.19041 1202
CPU: amd64
     family 6 model 140 stepping 1
     8 CPUs

Crash reason:  Unhandled C++ Exception
Crash address: 0x7ffccf544f99

Thread 0 (crashed)
 0  KERNELBASE.dll + 0x34f99
    rbx = 0x90923168   r12 = 0x00000000   r13 = 0x8f64b630   r14 = 0x8f64ba10
    r15 = 0x9337fe10   rip = 0xcf544f99   rsp = 0x38cff080   rbp = 0x38cff670
    Found by: given as instruction pointer in context
 1  OpenColorIO_2_1.dll + 0x313167
    rip = 0x90923168   rsp = 0x38cff090
    Found by: stack scanning
 2  KERNELBASE.dll + 0x34f98
    rip = 0xcf544f99   rsp = 0x38cff0b8
    Found by: stack scanning
 3  OpenColorIO_2_1.dll + 0x313167
    rip = 0x90923168   rsp = 0x38cff0d8
    Found by: stack scanning
 4  0x7ffc9060ffff
    rip = 0x90610000   rsp = 0x38cff0e0
    Found by: stack scanning
 5  ntdll.dll + 0x34a5e
    rip = 0xd1b44a5f   rsp = 0x38cff110
    Found by: stack scanning
 6  OpenColorIO_2_1.dll + 0x350fff
    rip = 0x90961000   rsp = 0x38cff138
    Found by: stack scanning
 7  0x7ffc9060ffff
    rip = 0x90610000   rsp = 0x38cff140
    Found by: stack scanning
 8  VCRUNTIME140.dll + 0x61bd
    rip = 0xb52061be   rsp = 0x38cff150
    Found by: stack scanning
 9  OpenColorIO_2_1.dll + 0x313167
    rip = 0x90923168   rsp = 0x38cff158
    Found by: stack scanning
10  VCRUNTIME140.dll + 0x647f
    rip = 0xb5206480   rsp = 0x38cff160
    Found by: stack scanning
11  OpenColorIO_2_1.dll + 0x4e4d3
    rip = 0x9065e4d4   rsp = 0x38cff180
    Found by: stack scanning
12  0x7ffc9060ffff
    rip = 0x90610000   rsp = 0x38cff188
    Found by: stack scanning
13  OpenColorIO_2_1.dll + 0x313167
    rip = 0x90923168   rsp = 0x38cff1a0
    Found by: stack scanning
14  0x7ffc9060ffff
    rip = 0x90610000   rsp = 0x38cff1a8
    Found by: stack scanning
15  OpenColorIO_2_1.dll + 0x23dd0
    rip = 0x90633dd1   rsp = 0x38cff1c0
    Found by: stack scanning
16  OpenColorIO_2_1.dll + 0x28313f
    rip = 0x90893140   rsp = 0x38cff1f8
    Found by: stack scanning
17  OpenColorIO_2_1.dll + 0x28016f
    rip = 0x90890170   rsp = 0x38cff218
    Found by: stack scanning
18  OpenColorIO_2_1.dll + 0x2800e7
    rip = 0x908900e8   rsp = 0x38cff228
    Found by: stack scanning
19  ucrtbase.dll + 0xef5cf
    rip = 0xcf8cf5d0   rsp = 0x38cff2b0
    Found by: stack scanning
20  OpenColorIO_2_1.dll + 0x280167
    rip = 0x90890168   rsp = 0x38cff2c8
    Found by: stack scanning
21  ucrtbase.dll + 0xfd1f
    rip = 0xcf7efd20   rsp = 0x38cff320
    Found by: stack scanning
22  OpenColorIO_2_1.dll + 0x27eb07
    rip = 0x9088eb08   rsp = 0x38cff328
    Found by: stack scanning
23  OpenColorIO_2_1.dll + 0x27e5ff
    rip = 0x9088e600   rsp = 0x38cff330
    Found by: stack scanning
24  OpenColorIO_2_1.dll + 0x27eaff
    rip = 0x9088eb00   rsp = 0x38cff3b0
    Found by: stack scanning
25  Qt5Core.dll + 0x7683
    rip = 0x6df27684   rsp = 0x38cff420
    Found by: stack scanning
26  olive-editor.exe!olive::ColorManager::CreateConfigFromFile(QString const &) [colormanager.cpp : 65 + 0x23]
    rip = 0x84b7c16b   rsp = 0x38cff450
    Found by: stack scanning
27  olive-editor.exe!olive::ColorManager::SetUpDefaultConfig() [colormanager.cpp : 103 + 0x46]
    rip = 0x84b7d6b5   rsp = 0x38cff480
    Found by: call frame info
28  olive-editor.exe!olive::Core::Start() [core.cpp : 138 + 0x4]
    rip = 0x84b0e5d6   rsp = 0x38cff570
    Found by: call frame info
29  olive-editor.exe!main [main.cpp : 259 + 0xb]
    rip = 0x84d25283   rsp = 0x38cff6c0
    Found by: call frame info
30  olive-editor.exe!static int __scrt_common_main_seh() [exe_common.inl : 288 + 0x21]
    rip = 0x84d2a00c   rsp = 0x38cffcf0
    Found by: call frame info
31  KERNEL32.DLL + 0x17033
    rip = 0xd1787034   rsp = 0x38cffd30
    Found by: call frame info
32  ntdll.dll + 0x52650
    rip = 0xd1b62651   rsp = 0x38cffd60
    Found by: stack scanning
33  KERNELBASE.dll + 0x10c15f
    rip = 0xcf61c160   rsp = 0x38cffdb0
    Found by: stack scanning

Thread 1
 0  ntdll.dll + 0xa07c4
    rbx = 0x8f5f8090   r12 = 0x00000000   r13 = 0x00000000   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bb07c4   rsp = 0x38dff5e8   rbp = 0x00000000
    Found by: given as instruction pointer in context
 1  ntdll.dll + 0x52dc6
    rip = 0xd1b62dc7   rsp = 0x38dff5f0
    Found by: stack scanning

Thread 2
 0  ntdll.dll + 0xa07c4
    rbx = 0x8f5fb690   r12 = 0x00000000   r13 = 0x00000000   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bb07c4   rsp = 0x38eff468   rbp = 0x00000000
    Found by: given as instruction pointer in context
 1  ntdll.dll + 0x52dc6
    rip = 0xd1b62dc7   rsp = 0x38eff470
    Found by: stack scanning

Thread 3
 0  ntdll.dll + 0xa07c4
    rbx = 0x8f5fcc50   r12 = 0x00000000   r13 = 0x00000000   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bb07c4   rsp = 0x38fff5e8   rbp = 0x00000000
    Found by: given as instruction pointer in context
 1  ntdll.dll + 0x52dc6
    rip = 0xd1b62dc7   rsp = 0x38fff5f0
    Found by: stack scanning

Thread 4
 0  ntdll.dll + 0xa07c4
    rbx = 0x8f5fc170   r12 = 0x00000000   r13 = 0x00000000   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bb07c4   rsp = 0x390ff998   rbp = 0x00000000
    Found by: given as instruction pointer in context
 1  ntdll.dll + 0x52dc6
    rip = 0xd1b62dc7   rsp = 0x390ff9a0
    Found by: stack scanning

Thread 5
 0  ntdll.dll + 0xa07c4
    rbx = 0x00000000   r12 = 0x00000000   r13 = 0x00000000   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bb07c4   rsp = 0x391ffad8   rbp = 0x00000000
    Found by: given as instruction pointer in context
 1  ntdll.dll + 0x52dc6
    rip = 0xd1b62dc7   rsp = 0x391ffae0
    Found by: stack scanning

Thread 6
 0  ntdll.dll + 0x9d8c4
    rbx = 0x00000003   r12 = 0xffffffff   r13 = 0x6a94a310   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bad8c4   rsp = 0x393ff608   rbp = 0x00000000
    Found by: given as instruction pointer in context
 1  KERNELBASE.dll + 0x4cb6f
    rip = 0xcf55cb70   rsp = 0x393ff610
    Found by: stack scanning
 2  USER32.dll + 0x293ce
    rip = 0xcfca93cf   rsp = 0x393ff620
    Found by: stack scanning
 3  KERNELBASE.dll + 0x631df
    rip = 0xcf5731e0   rsp = 0x393ff640
    Found by: stack scanning
 4  ig12icd64.dll + 0x102caf
    rip = 0x69b82cb0   rsp = 0x393ff648
    Found by: stack scanning

Thread 7
 0  ntdll.dll + 0x9dee4
    rbx = 0xccd62f00   r12 = 0xccd62ef8   r13 = 0x00000001   r14 = 0x00000038
    r15 = 0x80000009   rip = 0xd1badee4   rsp = 0x392ffb58   rbp = 0x948b5480
    Found by: given as instruction pointer in context
 1  dwmapi.dll + 0x3d79
    rip = 0xccd43d7a   rsp = 0x392ffb60
    Found by: stack scanning
 2  dwmapi.dll + 0x22eff
    rip = 0xccd62f00   rsp = 0x392ffb68
    Found by: stack scanning
 3  dwmapi.dll + 0x1ffff
    rip = 0xccd60000   rsp = 0x392ffb78
    Found by: stack scanning
 4  dwmapi.dll + 0x22edf
    rip = 0xccd62ee0   rsp = 0x392ffbd0
    Found by: stack scanning

Thread 8
 0  ntdll.dll + 0x9d8c4
    rbx = 0x00000001   r12 = 0xffffffff   r13 = 0x394ff420   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bad8c4   rsp = 0x394ff0d8   rbp = 0x000004bc
    Found by: given as instruction pointer in context
 1  KERNELBASE.dll + 0x4cb6f
    rip = 0xcf55cb70   rsp = 0x394ff0e0
    Found by: stack scanning
 2  MSCTF.dll + 0x4151f
    rip = 0xcfba1520   rsp = 0x394ff0e8
    Found by: stack scanning
 3  ntdll.dll + 0x17954
    rip = 0xd1b27955   rsp = 0x394ff0f0
    Found by: stack scanning
 4  ntdll.dll + 0x16a4cf
    rip = 0xd1c7a4d0   rsp = 0x394ff0f8
    Found by: stack scanning
 5  MSCTF.dll + 0x4151f
    rip = 0xcfba1520   rsp = 0x394ff110
    Found by: stack scanning
 6  ntdll.dll + 0x1791c
    rip = 0xd1b2791d   rsp = 0x394ff1b0
    Found by: stack scanning
 7  ntdll.dll + 0x1793c
    rip = 0xd1b2793d   rsp = 0x394ff1b8
    Found by: stack scanning
 8  ntdll.dll + 0x74f9c
    rip = 0xd1b84f9d   rsp = 0x394ff1d0
    Found by: stack scanning
 9  0x7ffcd1b0ffff
    rip = 0xd1b10000   rsp = 0x394ff268
    Found by: stack scanning
10  ntdll.dll + 0x74b62
    rip = 0xd1b84b63   rsp = 0x394ff270
    Found by: stack scanning
11  0x7ffcd1b0ffff
    rip = 0xd1b10000   rsp = 0x394ff280
    Found by: stack scanning
12  ntdll.dll + 0x74b17
    rip = 0xd1b84b18   rsp = 0x394ff2a0
    Found by: stack scanning
13  ntdll.dll + 0x507af
    rip = 0xd1b607b0   rsp = 0x394ff310
    Found by: stack scanning
14  ntdll.dll + 0x2df4b
    rip = 0xd1b3df4c   rsp = 0x394ff350
    Found by: stack scanning
15  KERNELBASE.dll + 0x645cf
    rip = 0xcf5745d0   rsp = 0x394ff360
    Found by: stack scanning
16  combase.dll + 0xcadaf
    rip = 0xd092adb0   rsp = 0x394ff378
    Found by: stack scanning
17  combase.dll + 0xcb1c5
    rip = 0xd092b1c6   rsp = 0x394ff3d0
    Found by: stack scanning
18  ntdll.dll + 0x2b86a
    rip = 0xd1b3b86b   rsp = 0x394ff4b0
    Found by: stack scanning
19  ntdll.dll + 0x2b3c6
    rip = 0xd1b3b3c7   rsp = 0x394ff570
    Found by: stack scanning
20  ntdll.dll + 0x507af
    rip = 0xd1b607b0   rsp = 0x394ff580
    Found by: stack scanning
21  ntdll.dll + 0x2b44c
    rip = 0xd1b3b44d   rsp = 0x394ff5a0
    Found by: stack scanning
22  KERNELBASE.dll + 0x33399
    rip = 0xcf54339a   rsp = 0x394ff5d0
    Found by: stack scanning
23  combase.dll + 0xcb03f
    rip = 0xd092b040   rsp = 0x394ff660
    Found by: stack scanning
24  combase.dll + 0x658e4
    rip = 0xd08c58e5   rsp = 0x394ff680
    Found by: stack scanning
25  combase.dll + 0xcae4f
    rip = 0xd092ae50   rsp = 0x394ff6b0
    Found by: stack scanning
26  combase.dll + 0xcb245
    rip = 0xd092b246   rsp = 0x394ff6e0
    Found by: stack scanning
27  combase.dll + 0xcadd8
    rip = 0xd092add9   rsp = 0x394ff710
    Found by: stack scanning
28  KERNEL32.DLL + 0x17033
    rip = 0xd1787034   rsp = 0x394ff740
    Found by: stack scanning
29  ntdll.dll + 0x52650
    rip = 0xd1b62651   rsp = 0x394ff770
    Found by: stack scanning

Thread 9
 0  ntdll.dll + 0xa07c4
    rbx = 0x8f5fc510   r12 = 0x00000000   r13 = 0x00000000   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bb07c4   rsp = 0x395ff938   rbp = 0x00000000
    Found by: given as instruction pointer in context
 1  ntdll.dll + 0x52dc6
    rip = 0xd1b62dc7   rsp = 0x395ff940
    Found by: stack scanning

Thread 10
 0  ntdll.dll + 0xa07c4
    rbx = 0x00000000   r12 = 0x00000000   r13 = 0x00000000   r14 = 0x00000000
    r15 = 0x00000000   rip = 0xd1bb07c4   rsp = 0x396ff6c8   rbp = 0x00000000
    Found by: given as instruction pointer in context
 1  ntdll.dll + 0x52dc6
    rip = 0xd1b62dc7   rsp = 0x396ff6d0
    Found by: stack scanning

Loaded modules:
0x1758f920000 - 0x17591478fff  icudt69.dll  69.1.0.0  (main)
0x7ff784aa0000 - 0x7ff7854f8fff  olive-editor.exe  1.0.0.0
0x7ffc69a80000 - 0x7ffc6aa01fff  ig12icd64.dll  27.20.100.8853
0x7ffc6aa10000 - 0x7ffc6c20cfff  avcodec-58.dll  0.0.0.0
0x7ffc6c210000 - 0x7ffc6d027fff  OpenImageIO.dll  0.0.0.0
0x7ffc6da20000 - 0x7ffc6df10fff  libx265.dll  0.0.0.0
0x7ffc6df20000 - 0x7ffc6e405fff  Qt5Core.dll  5.15.2.0
0x7ffc75270000 - 0x7ffc7567afff  igdml64.dll  27.20.100.8853
0x7ffc7b830000 - 0x7ffc7be62fff  Qt5Gui.dll  5.15.2.0
0x7ffc80220000 - 0x7ffc80769fff  Qt5Widgets.dll  5.15.2.0
0x7ffc809a0000 - 0x7ffc80c85fff  libx264-163.dll  0.163.0.0
0x7ffc817b0000 - 0x7ffc81c63fff  avfilter-7.dll  0.0.0.0
0x7ffc82170000 - 0x7ffc82464fff  avformat-58.dll  0.0.0.0
0x7ffc8d030000 - 0x7ffc8d36cfff  avutil-56.dll  0.0.0.0
0x7ffc8faa0000 - 0x7ffc8fd17fff  icuin69.dll  69.1.0.0
0x7ffc90610000 - 0x7ffc9097bfff  OpenColorIO_2_1.dll  0.0.0.0
0x7ffc911c0000 - 0x7ffc9145dfff  IlmImf-2_5.dll  0.0.0.0
0x7ffc94730000 - 0x7ffc9476dfff  dataexchange.dll  10.0.19041.1151
0x7ffc975a0000 - 0x7ffc975cbfff  GLU32.dll  10.0.19041.1081
0x7ffc97610000 - 0x7ffc97734fff  OPENGL32.dll  10.0.19041.1081
0x7ffc9bd90000 - 0x7ffc9be5cfff  qwindows.dll  5.15.2.0
0x7ffc9be60000 - 0x7ffc9bf08fff  freetype.dll  2.11.0.0
0x7ffc9c580000 - 0x7ffc9c723fff  icuuc69.dll  69.1.0.0
0x7ffc9e640000 - 0x7ffc9e70cfff  zstd.dll  1.5.0.0
0x7ffc9f0b0000 - 0x7ffc9f17ffff  harfbuzz.dll  0.0.0.0
0x7ffc9f750000 - 0x7ffc9f775fff  qwindowsvistastyle.dll  5.15.2.0
0x7ffc9f780000 - 0x7ffc9f858fff  modplug.dll  0.0.0.0
0x7ffc9f940000 - 0x7ffc9f9c3fff  libde265.dll  0.0.0.0
0x7ffc9fb60000 - 0x7ffc9fb86fff  brotlicommon.dll  0.0.0.0
0x7ffc9fb90000 - 0x7ffc9fbb0fff  fribidi-0.dll  0.0.0.0
0x7ffc9fbc0000 - 0x7ffc9fcb2fff  OpenImageIO_Util.dll  0.0.0.0
0x7ffc9fd10000 - 0x7ffc9fdd2fff  swscale-5.dll  0.0.0.0
0x7ffca01b0000 - 0x7ffca01d9fff  lzma.dll  5.2.5.0
0x7ffca01e0000 - 0x7ffca025efff  pcre2-16.dll  0.0.0.0
0x7ffca0400000 - 0x7ffca0430fff  ass.dll  0.0.0.0
0x7ffca0440000 - 0x7ffca04b0fff  tiff.dll  0.0.0.0
0x7ffca0c00000 - 0x7ffca0c41fff  yaml-cpp.dll  0.0.0.0
0x7ffca0da0000 - 0x7ffca0dcdfff  VCOMP140.DLL  14.28.29913.0
0x7ffca0dd0000 - 0x7ffca0e59fff  jpeg62.dll  0.0.0.0
0x7ffca0f70000 - 0x7ffca0fc5fff  Imath-3_1.dll  0.0.0.0
0x7ffca1100000 - 0x7ffca1121fff  boost_filesystem-vc142-mt-x64-1_77.dll  0.0.0.0
0x7ffca1130000 - 0x7ffca1164fff  libpng16.dll  0.0.0.0
0x7ffca2130000 - 0x7ffca219dfff  heif.dll  0.0.0.0
0x7ffca2260000 - 0x7ffca22a8fff  Half-2_5.dll  0.0.0.0
0x7ffca70f0000 - 0x7ffca7118fff  libexpat.dll  0.0.0.0
0x7ffca7120000 - 0x7ffca71a7fff  opentimelineio.dll  0.0.0.0
0x7ffca7220000 - 0x7ffca724dfff  portaudio.dll  0.0.0.0
0x7ffca7760000 - 0x7ffca777cfff  MPR.dll  10.0.19041.546
0x7ffca79e0000 - 0x7ffca7a12fff  swresample-3.dll  0.0.0.0
0x7ffca90a0000 - 0x7ffca90abfff  Secur32.dll  10.0.19041.546
0x7ffcaea90000 - 0x7ffcaeaa7fff  bz2.dll  0.0.0.0
0x7ffcb4ff0000 - 0x7ffcb507cfff  MSVCP140.dll  14.29.30133.0
0x7ffcb51a0000 - 0x7ffcb51b7fff  NETAPI32.dll  10.0.19041.546
0x7ffcb5200000 - 0x7ffcb521afff  VCRUNTIME140.dll  14.29.30133.0
0x7ffcb5a40000 - 0x7ffcb5a57fff  boost_thread-vc142-mt-x64-1_77.dll  0.0.0.0
0x7ffcb5a60000 - 0x7ffcb5a9bfff  Iex-2_5.dll  0.0.0.0
0x7ffcb5aa0000 - 0x7ffcb5aabfff  VCRUNTIME140_1.dll  14.29.30133.0
0x7ffcb90b0000 - 0x7ffcb9163fff  dbgmodel.dll  10.0.19041.1266
0x7ffcb9170000 - 0x7ffcb97f0fff  dbgeng.dll  10.0.19041.1266
0x7ffcbad60000 - 0x7ffcbad79fff  Imath-2_5.dll  0.0.0.0
0x7ffcbae90000 - 0x7ffcbdaa8fff  igc64.dll  27.20.100.8853
0x7ffcbeef0000 - 0x7ffcbf0bdfff  d3d9.dll  10.0.19041.928
0x7ffcbf310000 - 0x7ffcbf31ffff  brotlidec.dll  0.0.0.0
0x7ffcc0330000 - 0x7ffcc0586fff  igdgmm64.dll  27.20.100.8853
0x7ffcc0ba0000 - 0x7ffcc0bb0fff  squish.dll  0.0.0.0
0x7ffcc4430000 - 0x7ffcc4457fff  SRVCLI.DLL  10.0.19041.546
0x7ffcc4660000 - 0x7ffcc4668fff  MSVCP140_1.dll  14.29.30133.0
0x7ffcc7070000 - 0x7ffcc7270fff  twinapi.appcore.dll  10.0.19041.964
0x7ffcc72c0000 - 0x7ffcc72c9fff  VERSION.dll  10.0.19041.546
0x7ffcc8a00000 - 0x7ffcc8a35fff  XmlLite.dll  10.0.19041.546
0x7ffcc8b90000 - 0x7ffcc8bbffff  RTWorkQ.DLL  10.0.19041.1288
0x7ffcc8da0000 - 0x7ffcc8f5bfff  MFPlat.DLL  10.0.19041.746
0x7ffcc90a0000 - 0x7ffcc9198fff  AppXDeploymentClient.dll  10.0.19041.1288
0x7ffcc9420000 - 0x7ffcc9439fff  zlib1.dll  1.2.11.0
0x7ffcc9fa0000 - 0x7ffcc9fadfff  IlmThread-2_5.dll  0.0.0.0
0x7ffccafa0000 - 0x7ffccb203fff  d3d11.dll  10.0.19041.1202
0x7ffccb7d0000 - 0x7ffccb9b4fff  dcomp.dll  10.0.19041.1266
0x7ffccc2e0000 - 0x7ffccc36ffff  apphelp.dll  10.0.19041.928
0x7ffccc3e0000 - 0x7ffccc47dfff  UxTheme.dll  10.0.19041.1266
0x7ffccc720000 - 0x7ffccc903fff  dbghelp.dll  10.0.19041.867
0x7ffccc940000 - 0x7ffccc953fff  WTSAPI32.dll  10.0.19041.546
0x7ffccc960000 - 0x7ffccc986fff  WINMM.dll  10.0.19041.546
0x7ffcccd40000 - 0x7ffcccd6efff  dwmapi.dll  10.0.19041.746
0x7ffccd180000 - 0x7ffccd191fff  kernel.appcore.dll  10.0.19041.546
0x7ffccd330000 - 0x7ffccdabffff  windows.storage.dll  10.0.19041.1266
0x7ffccdb20000 - 0x7ffccdc13fff  dxgi.dll  10.0.19041.1266
0x7ffccdf20000 - 0x7ffccdf52fff  ntmarta.dll  10.0.19041.546
0x7ffcce660000 - 0x7ffcce671fff  UMPDC.dll  0.0.0.0
0x7ffcce7e0000 - 0x7ffcce7ebfff  NETUTILS.DLL  10.0.19041.546
0x7ffcce7f0000 - 0x7ffcce83afff  powrprof.dll  10.0.19041.546
0x7ffccebf0000 - 0x7ffccebfbfff  CRYPTBASE.DLL  10.0.19041.546
0x7ffccec80000 - 0x7ffccecabfff  Wldp.dll  10.0.19041.662
0x7ffccf0f0000 - 0x7ffccf11dfff  USERENV.dll  10.0.19041.572
0x7ffccf120000 - 0x7ffccf150fff  SSPICLI.DLL  10.0.19041.1266
0x7ffccf170000 - 0x7ffccf18efff  profapi.dll  10.0.19041.844
0x7ffccf230000 - 0x7ffccf256fff  bcrypt.dll  10.0.19041.1023
0x7ffccf310000 - 0x7ffccf41afff  gdi32full.dll  10.0.19041.1110
0x7ffccf480000 - 0x7ffccf502fff  bcryptPrimitives.dll  10.0.19041.1202
0x7ffccf510000 - 0x7ffccf7d8fff  KERNELBASE.dll  10.0.19041.1202
0x7ffccf7e0000 - 0x7ffccf8dffff  ucrtbase.dll  10.0.19041.789
0x7ffccf8e0000 - 0x7ffccf92dfff  cfgmgr32.dll  10.0.19041.1151
0x7ffccf930000 - 0x7ffccf9ccfff  msvcp_win.dll  10.0.19041.789
0x7ffccfb30000 - 0x7ffccfb51fff  win32u.dll  10.0.19041.1288
0x7ffccfb60000 - 0x7ffccfc74fff  MSCTF.dll  10.0.19041.1202
0x7ffccfc80000 - 0x7ffccfe20fff  USER32.dll  10.0.19041.1202
0x7ffccfe30000 - 0x7ffccfe84fff  SHLWAPI.dll  10.0.19041.1023
0x7ffccfef0000 - 0x7ffcd062efff  SHELL32.dll  10.0.19041.1266
0x7ffcd0630000 - 0x7ffcd069afff  WS2_32.dll  10.0.19041.546
0x7ffcd06a0000 - 0x7ffcd07c9fff  ole32.dll  10.0.19041.1202
0x7ffcd0860000 - 0x7ffcd0bb4fff  combase.dll  10.0.19041.1288
0x7ffcd0ca0000 - 0x7ffcd0ccafff  GDI32.dll  10.0.19041.1202
0x7ffcd0cd0000 - 0x7ffcd0d7bfff  ADVAPI32.dll  10.0.19041.1052
0x7ffcd0da0000 - 0x7ffcd0e3afff  sechost.dll  10.0.19041.906
0x7ffcd0e40000 - 0x7ffcd0f0cfff  OLEAUT32.dll  10.0.19041.985
0x7ffcd1060000 - 0x7ffcd14d1fff  SETUPAPI.dll  10.0.19041.1237
0x7ffcd14e0000 - 0x7ffcd157dfff  msvcrt.dll  7.0.19041.546
0x7ffcd1580000 - 0x7ffcd16a9fff  RPCRT4.dll  10.0.19041.1288
0x7ffcd16b0000 - 0x7ffcd1758fff  clbcatq.dll  2001.12.10941.16384
0x7ffcd1770000 - 0x7ffcd182dfff  KERNEL32.DLL  10.0.19041.1202
0x7ffcd1830000 - 0x7ffcd18dcfff  shcore.dll  10.0.19041.1266
0x7ffcd18e0000 - 0x7ffcd190ffff  IMM32.DLL  10.0.19041.546
0x7ffcd1b10000 - 0x7ffcd1d04fff  ntdll.dll  10.0.19041.1288
</code></pre></details>

**Comment by ThomasWilshaw** [comment]
Have you tried the portable (zipped) version?

**Comment by omeritzics** [comment]
Yes, I did; Olive crashes on both installable and portable versions.

**Comment by itsmattkc** [comment]
Known issue. Occurs if your Windows username has any non-ANSI (Unicode) characters in the name. It's an OpenColorIO issue that I fixed (AcademySoftwareFoundation/OpenColorIO#1363), it's been merged into their codebase, but they haven't made a stable release since merging so it's still not available from most package managers. I may patch our dependency system to manually install the PR but we'll see how long it takes for their next release to come out.
