### ISSUE TITLE
[EXPORT] Error when i try to export

### ISSUE THREAD

**Issue by EggsToMe** [olive-editor/olive#1795]
**Commit Hash** 

**Platform** 
Windows 7

**Summary**
I cant export my videos with Olive

**Additional Information / Output**
The error: 
https://dl.dropboxusercontent.com/s/rpj51lj7pet5qzc/lrUJm8lR1d.mp4
(Click on the link to see the video of the error)

**Comment by Simran-B** [comment]
What exact the version? Please share the commit hash.

**Comment by EggsToMe** [comment]
Where i see the version

And do you mean 0.1 or 0.2?

if yes is 0.2

**Comment by EggsToMe** [comment]
Or is this:Olive-55e87bae-Windows-x86_64

**Comment by EggsToMe** [comment]
Please respond me

**Comment by itsmattkc** [comment]
55e87bae is about a month old. Try the latest build and see if there's any difference.

**Comment by EggsToMe** [comment]
Ok

**Comment by EggsToMe** [comment]
0afbad6c This is the latest version?

**Comment by EggsToMe** [comment]
THANK YOU IT WORKS

**Comment by EggsToMe** [comment]
Uhhh How do i close this?

**Comment by EggsToMe** [comment]
Ah
