### ISSUE TITLE
images 0 frames

### ISSUE THREAD

**Issue by autoteelar** [olive-editor/olive#1798]
when i add an image its 0 frames and no matter what i do i cant change anything about it, changing the duration does nothing, dragging it to try and make it longer does nothing, how am i supposed to add images to my video if i cant even make it more than 0 frames?

![image](https://user-images.githubusercontent.com/76745649/143925947-bb81a66f-354a-4751-8d18-c426b78754b0.png)
![image](https://user-images.githubusercontent.com/76745649/143925972-7fe90a76-f73e-4e15-903f-e64e5b4ee954.png)
all the same result
![image](https://user-images.githubusercontent.com/76745649/143925993-35247c69-f38b-408f-875e-d0eab72ca1a1.png)

**Comment by Simran-B** [comment]
Fill out the issue template
