### ISSUE TITLE
[CODEC] Olive random freezing when working with mp3 audio 

### ISSUE THREAD

**Issue by omida56** [olive-editor/olive#1799]
**Commit Hash** 
ab8d9e14

**Platform** 
Linux mint

**Summary**
the video i worked on is : video codec H.264 (libx264) ,  audio codec  mp3  (libmp3lame).
i have got random freezing,  then i convert the audio codec to AAC and problem is gone. 

**Additional Information / Output**

**Comment by itsmattkc** [comment]
I haven't been able to recreate this. Can you provide sample files that exhibit this problem?

**Comment by omida56** [comment]
I have mostly used  videos,  recorded by a  screen recorder name (Vokoscreen) . 
I blame it  for the problem.

Recently  tried diffident file  and  Olive seems fine, I am going to test more and will let you know if this problem occurs again.Thanks

**Comment by itsmattkc** [comment]
Okay I will close this issue until it can be confirmed
