### ISSUE TITLE
Selecting many clips on the timeline and trying to move them results in a long freeze with high CPU usage

### ISSUE THREAD

**Issue by philiplb** [olive-editor/olive#1807]
**Commit Hash**  e902507e

**Platform** Windows 10

**Summary**

When I select many clips (20 or so) on the timeline and try to move them all at once, Olive freezes and the CPU usage spikes. Eventually it will not succeed but crash.

**Additional Information / Output**

The computer here should offer enough performance:
-  i7-8750H
- 32 GB RAM
- Geforce 1070 MaxQ (Wheras I think Olive uses the integrated Intel UHD Graphics 630, not sure)
- Samsung EVO 970 Pro

This is the behaviour:

![performanceOnManySelect](https://user-images.githubusercontent.com/1672238/147158188-04a92167-25e4-4adb-8f0d-b0970ee8df0f.gif)

**Comment by omida56** [comment]
@itsmattkc  I think maybe separating Editing and Composing  functionality in tow tabs like Dancing Resolve’s Implementation (Editing tab and fusion tab)  can reduce overhead.

**Comment by itsmattkc** [comment]
@omida56 Actually, most of the lag in selecting multiple clips comes from the parameter editor, not the node view, so separating off nodes wouldn't make any difference.

**Comment by JoseOlin** [comment]
I confirm the same behaviour in 76831a2b, but in addition to high consumption it hangs from time to time, when there are many cuts in the Timeline.

Is there a way to increase the verbosity of messages in terminal? For this specific problem there are no messages that give any idea of what is causing the problem.

**Comment by JoseOlin** [comment]
By the way, is there any way to group multiple clips belonging to the same or different tracks? 

Thanks in advance.

**Comment by itsmattkc** [comment]
Significantly improved in 5afd3226441de242065f6199826f4acfd7337704. More optimizations can probably be made, but I think this is workable enough to close this issue.
