### ISSUE TITLE
Moving a clip along with its dissolve doesn't move the dissolve

### ISSUE THREAD

**Issue by philiplb** [olive-editor/olive#1809]
**Commit Hash**  e902507e

**Platform** Windows 10

**Summary**

I added a cross dissolve at the end of a video clip in order to fade it out. Then I select the clip as well as the dissolve and try to move everything. The dissolve just stays where it is.

**Additional Information / Output**

Here is a recording of this behaviour:
![crossDissolveNotMoving](https://user-images.githubusercontent.com/1672238/147161179-5f6d1944-62b9-44b8-baa8-fabbae80e3c9.gif)

**Comment by itsmattkc** [comment]
Merging into #1842
