### ISSUE TITLE
Bug in using ALT+L/R Arrow Key to move clip

### ISSUE THREAD

**Issue by GUY-BBS** [olive-editor/olive#1811]
**e902507e**

**Windows 10** 

**Only the right-hand clip on a timeline (C) can be moved freely using Alt + L/R Arrow Keys. Other clips to the left of Clip C (A&B) can only be moved one frame. This is true for video clips or sound clips or linked clips. Oddly, if clip A starts at frame 0, it can be moved right 2 frames?**

**Additional Information / Output**
![Olive Bug](https://user-images.githubusercontent.com/49677111/147266293-f81ac579-569f-4d13-b0ec-7136a982ef99.jpg)

**Comment by GUY-BBS** [comment]
Thanks, I will test it when Windows version available.
Any chance of implementing the nesting of folders as with Olive 1 or is
this more than a simple fix?

**Comment by itsmattkc** [comment]
Nesting of folders?

**Comment by GUY-BBS** [comment]
Commit  eab3148d for Windows has the Alt + L/R arrow key working perfectly.
Many thanks.

As to my query as to nested folders, perhaps my UK terminology is unclear.
I have uploaded an image showing what I call nested folders in the Olive 1
project window - something that is not possible in Olive 2
Guy

**Comment by itsmattkc** [comment]
Sorry I don't see a photo. If you attached it to an email reply it doesn't seem to have worked, you might need to reply with it directly on GitHub

**Comment by GUY-BBS** [comment]
I hope this explains what I mean.
Guy
![Olive 1 Nested  Folders](https://user-images.githubusercontent.com/49677111/147779792-ee17d3de-3ab0-4d27-92bd-47505fd4b09a.png)

**Comment by itsmattkc** [comment]
To be honest I had no idea that wasn't possible anymore. Definitely a bug, it's fixed now in 923b889f1c95e074afae275dab47f920e7122dff

**Comment by GUY-BBS** [comment]
Many thanks and a Happy New Year
