### ISSUE TITLE
Keyframes "Dots" not shown on parameter editor, but working [UI] 

### ISSUE THREAD

**Issue by DamianoBenedetti** [olive-editor/olive#1820]
**Commit Hash** 
d3ffeaa3

**Platform** 
Ubuntu 20.04.3 LTS - 64-bit

**Summary**
Key-frames "Dots" not shown on parameter editor, but correctly working

**Additional Information / Output**
The key-frames "Dots" are not shown on parameter editor but the key-frames function itself works correctly (both for audio or position / scale). The problem is experienced for clips AFTER the 1st clip where you insert the key-frames. Off-course without the dots you can't move them and if you need to delete one, you need to use arrows buttons to select the "invisible" dot --> right click --> delete (the canc. button is not working) and reinsert it.

Thank you

![00_1st_keyframe_selected](https://user-images.githubusercontent.com/96338335/148235133-84b9c000-b441-4186-b298-0aa9dc8236e8.png)

![01_after_1st_keyframe](https://user-images.githubusercontent.com/96338335/148235189-dab3cb88-6d7e-4445-bf5c-743e697bd11d.png)

![02_2nd_keyframe_selected](https://user-images.githubusercontent.com/96338335/148235221-6b8b4a6d-44d1-405a-b7b3-f546acc0e4f7.png)

**Comment by itsmattkc** [comment]
Can you be more specific about steps to reproduce this? I've been able to get all keyframes to appear on my end

**Comment by itsmattkc** [comment]
Never mind, I have been able to recreate and fix this in 2831f6508bcf5fd9024a41f35977a8adaab63366

**Comment by DamianoBenedetti** [comment]
ok thank you :-)
