### ISSUE TITLE
[UI] Collapsing/expanding panels in Parameter Editor doesn't work until the titlebar is double clicked (Qt bug)

### ISSUE THREAD

**Issue by GUY-BBS** [olive-editor/olive#1829]
**d8ccc62d** 

**Windows 10** 

The behaviour of the arrowheads on the headings in the parameter editor seems illogical.  
Initially clicking on the arrowhead with either a single or double mouse-click does nothing.
Double-clicking to the right of the title closes the window.
Subsequently, a single click on the arrowhead opens or closes the window.
Yet a double click is still required to open or close the window if you point to the right of the title.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
We're aware of this, it's a Qt bug. Not sure what to do about it yet.

**Comment by GUY-BBS** [comment]
Thanks Matt
