### ISSUE TITLE
Where did the snap installation go

### ISSUE THREAD

**Issue by guyluz11** [olive-editor/olive#1830]
Template for **other** type does not exist.

I saw in some issue talk about the snap version of this software but I cant find it in the snap store.

![image](https://user-images.githubusercontent.com/9304740/149362577-be68ec42-b504-4b74-af29-867f4f5d7d5f.png)

Did it got removed?.

**Comment by elsandosgrande** [comment]
Anything other than the AppImages present on the Olive website is unofficial and thus the burden of support does not lie on us. Try looking into who packaged Olive as a Snap and ask them about it.
