### ISSUE TITLE
Using VCPKG as package manager on Windows

### ISSUE THREAD

**Issue by Cambloid** [olive-editor/olive#184]
Using the Microsoft VCPKG package manager to provide libraries like ffmpeg on Windows?

**Comment by itsmattkc** [comment]
I apologize for my ignorance in advance (I don't know how vcpkg works) but what does this require of Olive? Are the libraries installed from vcpkg not available system-wide?

**Comment by Cambloid** [comment]
I made a fork of olive where I tested vcpkg with olive (only on windows) 
All i did was I installed ffmpeg through vcpkg and then linked the lib files in a separate
.pri file and then copied the dll files to the executable directory. 
The good thing about vcpkg is that it is portable and does not pollute your system.

**Comment by itsmattkc** [comment]
I'm glad you were able to successfully make that work, but I'm still not certain what you want from Olive. If you wish to, perhaps you could package your suggestions into a PR so I can better understand your suggestion.

**Comment by Cambloid** [comment]
For olive it would be an advantage to use a package manager like VCPKG when it comes to add more dependencies in future since its a young project. Because I've seen a lot of opensource projects like blender which handle their dependencies manually.  Which is additional maintainance work.

**Comment by Cambloid** [comment]
Hi, sorry for not writing back. Happy Christmas btw. 
Yes it is a suggestion because VCPKG is very easy to use under Windows.
