### ISSUE TITLE
[EDIT] Ripple delete only deletes now

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#1841]
**Commit Hash** 

8f8d43f6

**Platform**

Ubuntu 22.04

**Summary**

**Shift + Del** or 'Edit > Ripple Delete' stopped making a shift to the left to fill the gap after deletion, it only deletes now.

**Comment by itsmattkc** [comment]
Can you share a video? Very basic testing on my end still seems to work as expected and no known changes have been made to rippling recently.

**Comment by prokoudine** [comment]
Here it is.

https://user-images.githubusercontent.com/57467/150672547-5b3d4f3d-52c7-4cdf-b949-96ea29868047.mp4

**Comment by itsmattkc** [comment]
I think the long audio clip is confusing it. The ripple code is probably worth revising anyway, last time I looked at it, it was pretty convoluted.
