### ISSUE TITLE
[EDIT] There should be an easy way to clean up unused tracks

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#1843]
Olive automatically creates new video and audio tracks when the need arises. However there is no way to delete unused tracks, and it's not easy to figure out to how to clean that up in a text editor. Perhaps, the should be a right-click menu for tracks with a Delete option?

**Comment by prokoudine** [comment]
Dunno if you go as far as "Remove all empty tracks" but the newly added "Delete track" option works well, thanks! Unsure if non-empty tracks need user confirmation before removal. What do you think?

**Comment by itsmattkc** [comment]
I'd say "delete track" doesn't need confirmation because it can be undone, but if there's a "delete all empty" option, it might be nice for a confirmation listing which tracks will be removed in the operation.
