### ISSUE TITLE
[UI] Config file to change default UI

### ISSUE THREAD

**Issue by gnolooo** [olive-editor/olive#1846]
**Commit Hash** 

**Platform** 
Arch Linux
Olive AppImage

**Summary**
This is more of a question than a real issue. Is there a way to store a custom UI configuration in a .config file and use it in any new project? Using Olive AppImage, which by design is portable like any other AppImage, I've seen there isn't this option, but I noticed it's missing in Windows too (tested both portable and installed version) so I think this is just a lacking feature. Could you confirm that?
(Please note I'm not asking for it to be added, I mean it would be really cool but I understand you guys have much more important things to do right now so I'm only asking if this is already present or not).

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Not yet. Follow #1231 and #587 for that.
