### ISSUE TITLE
[BUILD] macOS builds are .zip.zip

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1849]
**Commit Hash** 
6152e854

**Platform** 
macOS 12.0.1

**Summary**
Dev builds are twice ZIP compressed with no sense as the second compression doesn't reduce the file size. It also force the user to unzip it twice:
<img width="380" alt="zipzip" src="https://user-images.githubusercontent.com/5942369/150978160-e01d708d-4313-433e-bc94-c2519f15e278.png">

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Known issue, it's a GitHub Actions bug (actions/upload-artifact#39) that's out of our control. The only alternative seems to be to host files elsewhere, and right now this is the most convenient and cost-effective means of hosting the files.
