### ISSUE TITLE
[UI] Linux .02 Build asking for Program to use AppImage

### ISSUE THREAD

**Issue by Asian-Liberty** [olive-editor/olive#1854]
**Commit Hash** 

**Platform**  Linux Mint 20.3

**Summary** 0.2 Build keeps asking for a program to run the appimage.  I am currently using 0.1 and have no issues with this.  I'm sorry if this has already been submitted but I didn't see it in the issues reports threads.

**Additional Information / Output**

**Comment by Simran-B** [comment]
What are the file permissions? Does `ls -l Olive*.AppImage` show an `x` for user to execute it?

Run `chmod +x Olive*.AppImage` or set the execution permission in another way, then try running it again.

**Comment by itsmattkc** [comment]
AppImages must be set to execute permission. Indeed, as @Simran-B says `chmod +x <appimage>` or some DEs have a setting in "properties":

![image](https://user-images.githubusercontent.com/34096995/152203729-1a86b779-319c-44b5-b82e-b84394300aff.png)
