### ISSUE TITLE
[EDITING] Link/Unlink function doesn't work

### ISSUE THREAD

**Issue by LK-parrot** [olive-editor/olive#1855]
**Commit Hash** 

**Platform** <Ubuntu 20.04>

**Summary**

When I try to unlink audio track from video track (**either pressing ctrl + L or under "edit" menu**) it doesn't work and both audio and video tracks stay linked. I also tried to **select audio or video first**, but the result doesn't change. (tried on ubuntu 20 and 21 on another computer).

**Additional Information / Output**

**Comment by itsmattkc** [comment]
The clips are unlinking correctly in your video (as indicated by the underlines disappearing). They're still moving together because they're still both selected.
