### ISSUE TITLE
[UI] The parameter editor doesnt update when i remove a node from the clip.

### ISSUE THREAD

**Issue by scorpium959** [olive-editor/olive#1858]
**Commit Hash** 
The parameter editor isn't updating when i a clip doesnt have a node, like, i have this clip with transform and opacity to the output node, when i delete the opacity node and reconnect the transform node with the output one and go to the parameters editor, the opacity parameters still there.

**Platform** 
Arch Linux (AppImage)

**Summary**

**Additional Information / Output**
![Captura de pantalla de 2022-02-08 01-51-46](https://user-images.githubusercontent.com/64052400/152920593-c12040a3-5eb5-4592-aa73-798b8aae81f1.png)
![Captura de pantalla de 2022-02-08 01-52-32](https://user-images.githubusercontent.com/64052400/152920628-25a82857-4709-47de-a8ad-13898c507b6d.png)
![Captura de pantalla de 2022-02-08 01-52-02](https://user-images.githubusercontent.com/64052400/152920640-693dba4d-f08a-4615-8cb9-8f8d77546e80.png)
![Captura de pantalla de 2022-02-08 01-52-26](https://user-images.githubusercontent.com/64052400/152920646-149a0e70-e972-4526-a006-ae6f02f84708.png)
![Captura de pantalla de 2022-02-08 01-51-55](https://user-images.githubusercontent.com/64052400/152920672-36bf4ad5-937b-45b5-b4e0-e0e7ef279b7c.png)

**Comment by itsmattkc** [comment]
Known issue. We're working on it.

**Comment by itsmattkc** [comment]
Fixed in 1448f641e5c3da32cd822721d14ff3091c0cd0ae
