### ISSUE TITLE
[CACHE] 

### ISSUE THREAD

**Issue by techcountless** [olive-editor/olive#1859]
**Commit Hash** 

Olive 2.0 Cache is not effective

**Platform** 

Windows 11 

**Summary**
I want to tell you that When we generate disk cache olive cache the whole timeline and when we move any clip it again caches so this way we unnecessary caching so many stuff and also it is not that effective.
Instead of that, you need to provide a proxy feature that generates a lower version of that footage.

**Additional Information / Output**

**Comment by Simran-B** [comment]
You can define a preview resolution in the sequence settings, superseding proxies. Certain operations could be optimized to reduce the need for recaching but these limitations are well known by the team.
