### ISSUE TITLE
[CRASH] 

### ISSUE THREAD

**Issue by Usertyu** [olive-editor/olive#1860]
**Commit Hash**  2c700ca

**Platform**  Linux

**Summary**
My olive keeps freezing then just crashes when it hits 23 percent

**Steps to Reproduce**

1. Open olive
2. Open project
3. Export then it crashes

<details><summary><strong>Crash Report</strong></summary><pre><code>

  i did not get a crash report or I’m just looking in the wrong place

</code></pre></details>

**Additional Information**

**Comment by TheTechRobo** [comment]
Olive 0.1 is not supported and often has that issue. It might not happen on different platforms, but it might.

**Comment by Usertyu** [comment]
So there is No way to fix it

**Comment by TheTechRobo** [comment]
Other than updating to 0.2 or switching platforms, none that I know of.

**Comment by elsandosgrande** [comment]
Closing as deprecated.

**Comment by Usertyu** [comment]
Last question can I download 0.2 and just export already made project from there I tried 0.2 I just don’t like the node based editor

**Comment by elsandosgrande** [comment]
There is currently no official project conversion tool.
