### ISSUE TITLE
[BUILD] No nightly build since version: 7d52dc19 (Feb 4 2022 2:44:08 AM)

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#1861]
**Commit Hash** 
When you visit https://www.olivevideoeditor.org/download.php you can read that the last available version of Olive 0.2 is from February 4th. Should be more recent. Could you please look for it?

**Platform** 
Windows / Mac / Linux

**Summary**

**Additional Information / Output**

**Comment by Cuperino** [comment]
Hello @Suk-RAM, the last commit on the main branch was @[7d52dc19](https://github.com/olive-editor/olive/commit/7d52dc19e3bd5e48a066e95669525cb9387afae4), performed on February 4. The build system shouldn't create a new package until there are new commits to update with.

Perhaps the developers haven't pushed their more recent commits, maybe they're dealing with a large complex feature, or perhaps they've had a busy couple weeks limiting their time to work on the project. It does little good to make commits of incomplete code unless it is something that is to be accomplished through stages, following some kind of plan.

Give them a little time, and feel free to look for other issues to report in the meantime, always checking first they haven't already been reported. If the issue has been reported, read the discussion to see if there's some additional details you could add from your experience. Once a commit gets made to the main branch, the build system should create a new daily build as scheduled.

**Comment by Simran-B** [comment]
Thanks @Cuperino, your answer pretty much sums it up. There's nothing new to build at the moment as the core developer is currently busy with his main job.

The term "nightly builds" is a bit misleading, there are no scheduled builds once a day. A build is triggered immediately on every git push to the main branch (continuous Integration). That means there can be multiple builds a day.
