### ISSUE TITLE
[EDIT] Box selecting and moving leaves transitions behind

### ISSUE THREAD

**Issue by bziur** [olive-editor/olive#1863]
**Commit Hash** 

c2dd7da7238afcf8a6ffe6700dacf97daa97fda0

**Platform** 

Linux 5.15.21-1-MANJARO

**Summary**

Box selecting on timeline properly marks transitions as selected (are darker in colour), however moving the selected items in timeline, leaves transitions behind.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
#1842
