### ISSUE TITLE
[CACHE] 

### ISSUE THREAD

**Issue by Funtime60** [olive-editor/olive#1868]
41a49c48 

Windows 10 

The disk cache doesn't seem to be working for me. I have examined the folder it resides in and there are files of variable size, however a file called index is pretty much empty, maybe has 6 characters which look to be NULL characters. Moving the cache folder did not change anything. The files including the empty index were now there.

While I don't know how exactly it works, I suspect that a write error is causing a read failure.

I'm sorry if this some error on my part, but I hope this can be resolved quickly and relatively painlessly.

**Additional Information / Output**

**Comment by Funtime60** [comment]
Shoot, forgot to set the name, I don't think I can fix that can I?

**Comment by Funtime60** [comment]
Update: manually choosing "cache entire sequence" does function. There are now many folders and also an index file that is in the MB range instead of the byte range.

**Comment by Funtime60** [comment]
My apologies, I was not aware that it was possible to disable caching automatically. I will now enable auto caching and hopefully figure out how to save that to the global default.

**Comment by TheTechRobo** [comment]
For reference, there should be an "Edit" button beside the title; click it to edit it.
