### ISSUE TITLE
Unable to paste Opacity node[NODES] 

### ISSUE THREAD

**Issue by GUY-BBS** [olive-editor/olive#1872]
**78034288** 

**Win 10** 

**Copying and pasting video clip does not copy the Opacity node or its connections, yet the node configuration in the pasted clip still works**

**Additional Information / Output**

https://user-images.githubusercontent.com/49677111/157077964-795f521d-2027-4a8d-b679-20328135023d.mp4

**Comment by itsmattkc** [comment]
Fixed as of e0bfbf12b23cf5d4b9f44cc3230e0a046773ddb6
