### ISSUE TITLE
[NODES] Opacity node outputs black opaque image when at 0%

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1874]
**Commit Hash** 
3e12fb1f

**Platform** 
macOS 12.2.1

**Summary**
I understand that an opacity node should end up with a totally transparent output if set to 0%, that is, if you have something like the following:
<img width="1680" alt="trans" src="https://user-images.githubusercontent.com/5942369/157093548-071a7942-ba38-4c67-97fd-c0b117c01f10.png">

You expect and "merged" or combined output showing the lower "layer" or video track, in this case it has a solid clip set to default red color.

Is it a bug or I am using incorrectly the node hierarchy?

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
Due to current limitations the opacity node doesn't add an alpha channel yet if a clip doesn't already have it. This should be fixed soonish

**Comment by pgilfernandez** [comment]
Thanks for the answer and explanation.
I will stay tuned =)
