### ISSUE TITLE
[CRASH] when trying to preview images  

### ISSUE THREAD

**Issue by teklife** [olive-editor/olive#1878]
**Commit Hash** 

**Platform** <Ubuntu Studio 21.10>

**Summary**

**Steps to Reproduce**

1. add images to project window
2. 2x click an image
3. crash. happens every time on my machine with 0.2.0

<details><summary><strong>Crash Report</strong></summary><pre><code>

</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
You're missing several parts of the template. Please fill out the "Commit Hash" and try to acquire a "Crash Report". Closing until this is remedied.
