### ISSUE TITLE
Olive crashes on launch on some Macs

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#188]
Some Mac users report Olive crashing on launch (therefore being unable to use it entirely). Strangely, on the other hand, some Mac users seem to have no issue at all running it, including myself. Since I've never been able to recreate it (even across several macOS versions and a couple of different machines), I've never been able to track it down and address it.

A user has provided the following crash report which I interpreted as an issue with `libglib-2.0.0.dylib`, but I honestly have no idea:
[OLIVE_MACOS_CRASH.txt](https://github.com/olive-editor/olive/files/2705652/OLIVE_MACOS_CRASH.txt)

Perhaps it's an issue with the particular libs packaged by `macdeployqt`? Or something about the way the FFmpeg libs are compiled? If someone has this issue and is able to compile on Mac, I'd greatly appreciate help.

**Comment by pgilfernandez** [comment]
Mine is working fine and when compiling it doesn't through any important error (just some warnings...)
May be it's a good idea to ask them to try to compile it by themselves

**Comment by koma2305** [comment]
I have no clue how to compile myself. Here is my crash report. I hope it helps:

[OLIVE_MACOS_10_9_CRASH.txt](https://github.com/olive-editor/olive/files/2717471/OLIVE_MACOS_10_9_CRASH.txt)

**Comment by itsmattkc** [comment]
It looks like the solution to this has been found - since I compile the FFmpeg libs for Mac myself, FFmpeg's been compiling with AVX2 extensions which are only available in CPUs after 2015 or so. Recompiling FFmpeg without AVX2 extensions appears to have solved the problem, I'll update the binary on the website soon.

**Comment by itsmattkc** [comment]
Anyone with this problem can try this test build and see if it fixes things: https://drive.google.com/open?id=1xK-k3UDxWtraGn8zYE-5JrJBVT5OnqdG

**Comment by pgilfernandez** [comment]
For me it works flawlessly.
This build lacks the "viewer zoom options" but bug https://github.com/olive-editor/olive/issues/187 is not present which makes it usable and cool

Keep on this way, it's almost my favourite opensource NLE by now =)
Thanks!

**Comment by itsmattkc** [comment]
Thank you!
