### ISSUE TITLE
[UI] Interface is not displayed etc. (Windows 10 21Р2)

### ISSUE THREAD

**Issue by Andrei-graiv** [olive-editor/olive#1891]
**Commit Hash** 

**Platform** 

**Summary**
не отображается интерфейс  и т.д. 

**Additional Information / Output**

**Comment by mcDandy** [comment]
Can you please fill in template?

 What version you are using? 

Does the program start at all and do you see Black window for a split second?

If so is there any text?

Can you be more specific?

**Comment by Andrei-graiv** [comment]
Версия программы 0.2
Текст появляется только при нажатии ![IMG_20220406_121508.jpg](https://user-images.githubusercontent.com/67795509/161940965-6c261da6-7603-4a22-9e08-9f940361f063.jpg)

**Comment by Simran-B** [comment]
Please always provide the exact version number including the commit hash when you report bugs. I was able to identify it as 0.2.0 e0bfbf12 using the screenshot, which is the lastest test build.

Can you please start Olive from a command prompt and post what is printed there?

**Comment by Andrei-graiv** [comment]
Запуск без изменений

**Comment by Simran-B** [comment]
Don't get me wrong, it won't change anything about the problem but we need to know what is printed to the terminal. And it would be helpful to know what GPU you have. It might not meet the minimum requirements.

**Comment by itsmattkc** [comment]
I'm betting this is a GPU Issue, probably too old for OpenGL 3.2.
