### ISSUE TITLE
Can't render to external drive on windows

### ISSUE THREAD

**Issue by JonFStr** [olive-editor/olive#1893]
**Commit Hash** 
e0bfbf12

**Platform** 
Windows 10 portable (on NTFS-drive)

**Summary**
When trying to render to an external drive, Olive fails to start the rendering process with the message
`The intended output directory doesn't exist and Olive couldn't create it. Please choose a different filename.`

**Additional Information / Output**
Screenshot of error:
![grafik](https://user-images.githubusercontent.com/49946813/162222509-7268e531-7b61-4ea7-9557-3929d30a0342.png)

**Comment by itsmattkc** [comment]
Fixed as of 20f74919a3cf4e934db5039de61111bf427a742c
