### ISSUE TITLE
[NODES] Inserting a node connects it to "enabled"

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1906]
**Commit Hash** 
827dd98

**Platform** 
macOS 12.3

**Summary**
When inserting a new node (for instance: a "blur" node in between a "text" and the "output" ones) the "text" output connects to "enabled" parameter instead of "input" parameter.

<img width="617" alt="Captura de Pantalla 2022-04-28 a las 9 50 52" src="https://user-images.githubusercontent.com/5942369/165704959-564f3c5c-eb6c-43e0-beb2-ba91bccba06b.png">

**Additional Information / Output**
I guess this bug has been introduced after adding the ability to enable/disable nodes...

**Comment by itsmattkc** [comment]
Fixed in 7825d0e16d38c04188b021e160fea609da3cf7d0
