### ISSUE TITLE
[PLAYBACK] Laggy playback with multiple video-streams in MKV

### ISSUE THREAD

**Issue by JonFStr** [olive-editor/olive#1908]
**Commit Hash** 
827dd98d

**Platform** 
Manjaro Linux GNOME, X11, NVIDIA 1050Ti, Kernel 5.15

**Summary**
When using an MKV with multiple video-streams embedded in it (e.g. a video with the thumbnail embedded via `yt-dlp --embed-thumbnail`), the playback doesn't play any video, and the audio is only audible for the first few seconds.

I have the thumbnail-stream disabled in the properties of the media (right-click on clip in project-frame -> properties)

**Additional Information / Output**
The same video as mp4 with only the actual video stream (remuxed via `ffmpeg -i video.mkv -c copy -o video.mp4`) works flawlessly, so the problem should be happening because of the second stream.

**Comment by ThomasWilshaw** [comment]
Can you provide some sample footage that demonstrates the problem?

**Comment by itsmattkc** [comment]
I was able to generate a file like the one he's talking about (with `yt-dlp --embed-thumbnail`), but couldn't see any difference on my end. It might be that this is just general render slowdown rather than anything specific to this setup, and that the solution is just general render optimization (which will be coming)

**Comment by itsmattkc** [comment]
@JonFStr The latest commit has a bunch of optimizations, could you test and see if this issue is resolved now?

**Comment by itsmattkc** [comment]
Closing for now

**Comment by JonFStr** [comment]
Sorry for not responding, I was quite busy.
Anyways, the problem seems to be gone. Thank You!
