### ISSUE TITLE
[EXPORT] Unable to export audio

### ISSUE THREAD

**Issue by Funtime60** [olive-editor/olive#1911]
5351e634 

Win10 Pro x64 

When exporting with audio, I get the error:
"Failed to open file: Failed to open encoder: Invalid argument -22"

Unchecking "Export Audio" allows it to export, but then my clip is obviously silent.

![image](https://user-images.githubusercontent.com/24595923/166500732-f2be61f6-808b-4bec-ad09-4b2148792e64.png)

**Comment by pgilfernandez** [comment]
Same error here under macOS 12.3.
And sometimes even unchecking "export audio" it continues poping up an error.

**Comment by pgilfernandez** [comment]
> Same error here under macOS 12.3. And sometimes even unchecking "export audio" it continues poping up an error.

This is the other error:
<img width="427" alt="Captura de Pantalla 2022-05-03 a las 23 26 14" src="https://user-images.githubusercontent.com/5942369/166569262-2305bb9d-b1e7-4839-9d46-327b821812a6.png">

After it Olive goes so choppy, like it it where working in the background or had a memory leak...

**Comment by itsmattkc** [comment]
Fixed as of b290c4d00709838153a913e7007cb3c6bec308c3
