### ISSUE TITLE
[UI] [Enhancement] Node and Parameter editor synchronization

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1912]
**Commit Hash** 
a3c52ca

**Platform** 
all

**Summary**
It would be nice to have a synchronization between the selected or focused element between Nodes and Parameter editor, that is, when a node is selected in the Node Editor, the Parameter editor would focus on that exact node and viceversa.

I have seen that if you click in Parameter editor links (for instance "node connected to...") the node is focused in the Node editor but no in the Parameter one. This behavior is so nice, I think it would be great that the Parameter editor works the same way as well and that both editors get synchronized when selecting a node.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Coincidentally I was actually planning on implementing this today
