### ISSUE TITLE
recording audio failed on macOS 10.13.6

### ISSUE THREAD

**Issue by dolarfred** [olive-editor/olive#1916]
**Commit Hash** 

**Platform** 

**Summary**
Olive build ef515579-macOS-x86_64 was OK for recording Audio with macOS 10.13 (french)
after this build it doesn't work with more recent build

**Additional Information / Output**
The message is : "failed to start audio recording"

**Comment by itsmattkc** [comment]
Can you check your audio recording settings, ensure the devices are correct and format is valid, click OK, and try again?

**Comment by dolarfred** [comment]
Hi !

The audio recording settings was correctly set in preferences system, but not in olive preferences !!!
so, nows it runs

Thank you
