### ISSUE TITLE
[UI] "Edit with editor" option at Text node

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1918]
**Commit Hash** 
102ce9a

**Platform** 
macOS 12.3 (all)

**Summary**
It would be nice to have a button at the "Text node" to open the new "visual text editor" as right now it's a little hidden as the only way to open it is double clicking the text box in the Sequence Viewer, which is so handy but not obvious...
<img width="309" alt="edit_text" src="https://user-images.githubusercontent.com/5942369/166895490-1542ff6b-117d-416e-9fb0-6acd93d1b2d3.png">

The actual button with the beam icon would permit edit the text source code while the proposed new button with the pencil icon would focus and open the "visual text editor" in the Sequence viewer.

**Additional Information / Output**
I have [made a PR](https://github.com/olive-editor/olive/pull/1917) with the icon needed in case you feel like to implement this option.

**Comment by itsmattkc** [comment]
While I agree that the viewer text gizmo lacks discoverability right now (at least, after years of never having such a thing), I'm not sure this is the best solution. I've considered hiding the HTML/text input (since our HTML implementation is limited anyway) to better prompt users that text needs to be edited somewhere else.

**Comment by pgilfernandez** [comment]
That's right.
No matter what solution you finally choose, you have a new icon ;p

Cheers

**Comment by GUY-BBS** [comment]
If the HTML/text input gets hidden in a new iteration, can I ask for a slight modification? The text from certain types of captions, eg crawler or roller captions, is generally pasted in from another source. Currently, if you paste into the text window, the format defaults to minuscule-sized text. Consequently, I paste the text into the appropriate place in the HTML code. Could the behaviour when pasting into the text window be changed to retain the existing font parameters?

**Comment by itsmattkc** [comment]
Okay I've gone ahead and replaced the entire HTML editor in the parameter panel with an "edit in viewer" button in 501564fb2228b3d6d263dbf0a9cd6603625f8ac5. Text pasting should also retain the existing style as @GUY-BBS pointed out. I think this should solve this issue.
