### ISSUE TITLE
[CRASH] Importing footage with auto parameters causes crash

### ISSUE THREAD

**Issue by aeroc7** [olive-editor/olive#1919]
**Commit Hash** 
0e3d6ef

**Platform** 
Fedora 35 (though should be applicable to any platform)

**Summary**
Dereference happens right [here](https://github.com/olive-editor/olive/blob/0e3d6ef37429c6ab9cd3f29b906bd581a7e5f92a/app/node/traverser.cpp#L376). Specifically, the job from `SampleJob job = v.value<SampleJob>();` is a valid variant, but `job.samples()` is a `nullptr`, so when the dereference happens `job.samples()->audio_params()`, it crashes.

**Steps to Reproduce**

1. Import video clip
2. Drag to timeline
3. Select 'detect parameters automatically'

<details><summary><strong>Crash Report</strong></summary><pre><code>

#0  0x00000000008ee5c6 in olive::NodeTraverser::ResolveJobs(olive::NodeValue&, olive::TimeRange const&) (this=0x7fffae992e70, val=..., range=...)
    at /home/user/dev/olive/app/node/traverser.cpp:381
#1  0x00000000008eeef2 in olive::NodeTraverser::PreProcessRow(olive::TimeRange const&, QHash<QString, olive::NodeValue>&) (this=0x7fffae992e70, range=..., row=...)
    at /home/user/dev/olive/app/node/traverser.cpp:399
#2  0x00000000008e9b7d in olive::NodeTraverser::GenerateRow(olive::NodeValueDatabase*, olive::Node const*, olive::TimeRange const&)
    (this=0x7fffae992e70, database=0x7fffae991c00, node=0x61400013fc40, range=...) at /home/user/dev/olive/app/node/traverser.cpp:60
#3  0x00000000008ec71a in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::Node::ValueHint const&, olive::TimeRange const&)
    (this=0x7fffae992e70, n=0x61400013fc40, hint=..., range=...) at /home/user/dev/olive/app/node/traverser.cpp:267
#4  0x00000000009c9edf in olive::RenderProcessor::GenerateBlockTable(olive::Track const*, olive::TimeRange const&) (this=0x7fffae992e70, track=0x612000192ac0, range=...)
    at /home/user/dev/olive/app/render/renderprocessor.cpp:290
#5  0x00000000008ec562 in olive::NodeTraverser::GenerateTable(olive::Node const*, olive::Node::ValueHint const&, olive::TimeRange const&)
    (this=0x7fffae992e70, n=0x612000192ac0, hint=..., range=...) at /home/user/dev/olive/app/node/traverser.cpp:249
#6  0x00000000009c78e4 in olive::RenderProcessor::Run() (this=0x7fffae992e70) at /home/user/dev/olive/app/render/renderprocessor.cpp:191
#7  0x00000000009c948d in olive::RenderProcessor::Process(std::shared_ptr<olive::RenderTicket>, olive::Renderer*, olive::RenderCache<olive::Decoder::CodecStream, olive::DecoderPair>*, olive::RenderCache<QString, QVariant>*, QVariant)
    (ticket=std::shared_ptr<olive::RenderTicket> (use count 5, weak count 0) = {...}, render_ctx=0x606000164840, decoder_cache=0x60200007eb90, shader_cache=0x60200007eb70, default_shader=...) at /home/user/dev/olive/app/render/renderprocessor.cpp:262
#8  0x00000000009c1b02 in olive::RenderManager::RunTicket(std::shared_ptr<olive::RenderTicket>) const
    (this=0x60e00031cec0, ticket=std::shared_ptr<olive::RenderTicket> (use count 5, weak count 0) = {...}) at /home/user/dev/olive/app/render/rendermanager.cpp:228
#9  0x0000000000a10d5a in olive::ThreadPoolThread::run() (this=0x6070000be590) at /home/user/dev/olive/app/threading/threadpool.cpp:140
#10 0x00007ffff30ab4c6 in QThreadPrivate::start(void*) (arg=0x6070000be590) at thread/qthread_unix.cpp:329
#11 0x00007ffff2b4480a in start_thread () at /lib64/libc.so.6
#12 0x00007ffff2ae4430 in clone3 () at /lib64/libc.so.6

</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
Is this fixed in ef046d5ed6b8d32ba347e1e7addf8774a80c9ff1?

**Comment by aeroc7** [comment]
Yes, no issue anymore.
