### ISSUE TITLE
Compiling wiki for macOS

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#192]
Hi,

As we cannot pull request for the Wiki, here you have the instructions I followed to compile it under macOS. It may be not perfect (I'm not an experienced programmer) but it seems to work. Of course, if anyone could improve it it would be cool for everybody:

Open up **Terminal** and use the following instructions to build Olive from source.

Install Xcode Command Line Tools:

`xcode-select --install`

Install Homebrew:

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

Install Qt 5:

`brew install qt5`

Install FFmpeg:

`brew install ffmpeg`

By this point, all dependencies should be installed. Grab a copy of the source code with:

`git clone https://github.com/olive-editor/olive.git`

Enter the Olive folder:

`cd olive`

Generate a Makefile:

`qmake`

**If `qmake` doesn't work** you could try these options:

1) Force the link of the just installed Qt5:

`brew link qt5 --forces`

2) if the previous one doesn't work try:
`brew info qt`
`echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile`
`export LDFLAGS="-L/usr/local/opt/qt/lib"`
`export CPPFLAGS="-I/usr/local/opt/qt/include"`
`export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"`
`. ~/.bash_profile`

And finally run `make` to compile Olive:

`make`

Once `make` is complete Olive should be ready to run, so open the folder with Finder and launch the new .app file.

Enjoy!

**Comment by itsmattkc** [comment]
Looks good! I'll make a couple slight adjustments and put it up

**Comment by pgilfernandez** [comment]
Of course, improve it as you wish

**Comment by itsmattkc** [comment]
I moved the compile page to the official website, but I've added your instructions with a few minor tweaks. Thanks for the help!
