### ISSUE TITLE
[NODES] [UX enhancement] Default text node box size

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1923]
**Commit Hash** 
6613ff3

**Platform** 
All

**Summary**
This is a UX suggestion as I always have to resize the text box and I guess almost everybody has to do it as well in their projects: it would be nice that the default text box size is calculated when inserted in a sequence using the sequence dimensions minus the save margins.

Now, the default size is like this:
<img width="747" alt="Captura de Pantalla 2022-05-12 a las 10 05 05" src="https://user-images.githubusercontent.com/5942369/168023398-53f2881a-d1d8-4fa3-b74d-5479a40903be.png">

While with the suggested improvement it would be like the following:
<img width="744" alt="Captura de Pantalla 2022-05-12 a las 10 05 31" src="https://user-images.githubusercontent.com/5942369/168023504-b33dd5e2-34e0-4ce8-b8ec-d440f696756c.png">

**Additional Information / Output**
It might be also nice to have a simple calculation that sets the text default font size to something balanced with the sequence dimensions (not too big, not too small)

Cheers

**Comment by itsmattkc** [comment]
I don't know if you'll consider this a solution, but I've just added something I've wanted to implement for a while:

https://user-images.githubusercontent.com/34096995/168165389-4f09dc73-0b88-485a-9fbb-e64491a530b2.mp4

Allowing you to create titles and shapes directly in the viewer to whatever size you want.

**Comment by pgilfernandez** [comment]
Yeah, looks very nice.
Anyway, in what moment are you prompt to create this text box? I guess you first still have to create the text clip in the timeline and then go to the sequence viewer to create the box, right?
