### ISSUE TITLE
Problem with Keyframe audio

### ISSUE THREAD

**Issue by dolarfred** [olive-editor/olive#1924]
[EDIT] 
**Commit Hash** 
Audio keyframes PB

**Platform** 
macOS 10.13

**Summary**
Trying audio keyframes, it doesn't work. On precedent other builds it did. 
(Olive-13aedfa2-macOS-x86_64) 
see video joined file

https://user-images.githubusercontent.com/104966909/168024936-c15a82ae-a954-4516-a96c-61de11f1123e.mp4

**Additional Information / Output**

**Comment by sobotka** [comment]
Please follow the issue template and include the hash. Without this, it makes triaging more challenging.
