### ISSUE TITLE
[EDIT] Add clip marker from timeline and display it's name

### ISSUE THREAD

**Issue by ApplePie420** [olive-editor/olive#1925]
Hey, would it be possible to add/edit clip markers from timeline? Even when I select clip and add marker, it always adds it to the timeline, not to a clip. It would be handy if the clip is selected, it will add the marker to that clip, and if not, add it to timeline. So far the only way I was able to do it is if I open the clip in source monitor and add markers there. But that's pretty obnoxious since the playheads are not in sync.
Also another welcome feature would be a small little tag next to the marker with it's name, similar to what kdenlive has. 
Thanks :)

**Comment by sobotka** [comment]
Fill out the template as requested please. This also doesn’t appear to be a bug report, and more value would come from discussing in the Discord or other places likely.
