### ISSUE TITLE
[EDIT] Subtitles are exported with a comma symbol prepended

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1927]
**Commit Hash** 
8e642c8

**Platform** 
macOS 12.3

**Summary**
Testing the old and new subtitles features I have detected that when you export a SRT file, it's added a comma "," before the subtitle itself:
<img width="1243" alt="Captura de Pantalla 2022-05-13 a las 17 29 13" src="https://user-images.githubusercontent.com/5942369/168317035-eda0989d-f7ab-4573-abfa-4f3524f22dda.png">

This simple test exports this SRT:
```
1
00:00:01,000 --> 00:00:02,000
,first

2
00:00:03,000 --> 00:00:04,000
,second
```

**Additional Information / Output**
As expected, if you import it with the new subtitles import feature, the subtitles (and clip titles) include the "ghost" comma:
<img width="1242" alt="Captura de Pantalla 2022-05-13 a las 17 32 18" src="https://user-images.githubusercontent.com/5942369/168317423-9a5ef1d4-bebc-457b-9bea-f84e9eac80c4.png">

**Comment by itsmattkc** [comment]
Damn, this appears to be a recent issue introduced by FFmpeg 5.0. I tested a build with FFmpeg 4.4 (the last version pre-5.0 and what the export subtitles feature was initially written for) and it works as expected, but indeed as of the latest version, a comma is prepended.

FFmpeg's own SRT generation with its CLI app seems to work fine in the latest version, so we might just be using the API wrong on our end in a way that worked on 4.x but doesn't on 5.x. Either way, this will take further investigation.
