### ISSUE TITLE
Hardware-accelerated export

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#193]
I come from the land of weak CPUs.

Shotcut can export projects in the h264_qsv and h264_vaapi codecs through FFmpeg. Is this possible in Olive? I hope this is not a #26 duplicate

**Comment by itsmattkc** [comment]
I'm afraid it is a #26 duplicate, however it does look like VAAPI encoding will be fairly easy to implement. Stay tuned for an update very soon!
