### ISSUE TITLE
[UI] The "Add default transition" is not working

### ISSUE THREAD

**Issue by rpatros1979** [olive-editor/olive#1939]
**Commit Hash** <f4af8353>

**Platform** <Archlinux>

**Summary**
Current it seems that when right clicking on a video in the timeline, we have the option for "Add Default Transition" and this function does not seem to work as it does not add any transition. I would expect the default transition to be fade in and fade out on any clip in the timeline.

**Additional Information / Output**

**Comment by ringeringeraja** [comment]
I'm experiencing the same in Olive 0.2.0-bdb917c5.
