### ISSUE TITLE
[CRASH] Appending a video to a video track where the track has a title in the beginning with cross fade transitions

### ISSUE THREAD

**Issue by rpatros1979** [olive-editor/olive#1940]
**Commit Hash** <f4af8353>

**Platform** <Archlinux>

**Summary**
Adding a mp4 clip to the timeline with an existing by appending the video where the video clips start with a text that has cross fades and then appended the video after it

**Steps to Reproduce**

I could not reproduce it when I tried it again. Also the crash report from olive is not able to send the report successfully.

1. 
2. 
3. 

<details><summary><strong>Crash Report</strong></summary><pre><code>

[crash-f4af8353.txt](https://github.com/olive-editor/olive/files/8733608/crash-f4af8353.txt)

</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
I have a feeling this was a crash fixed in the latest commit. Sadly I can't confirm, but if you encounter it again, the crash reporting is fixed now.
