### ISSUE TITLE
[BUILD] 

### ISSUE THREAD

**Issue by Lehmeiers** [olive-editor/olive#1941]
**Commit Hash** 

Unfortunately, I could not access the number because the compilation process was aborted.

**Platform** 

Linux Manjaro

**Summary**

Good day!
I wanted to try Olive ( 0.1.2-2 ) , but it broke off during compilation. 

The last part of the message can be seen below.

**Additional Information / Output**

...

[ 13%] Building CXX object CMakeFiles/olive-editor.dir/olive-editor_autogen/mocs_compilation.cpp.o
[ 14%] Building CXX object CMakeFiles/olive-editor.dir/dialogs/aboutdialog.cpp.o
[ 15%] Building CXX object CMakeFiles/olive-editor.dir/dialogs/actionsearch.cpp.o
[ 15%] Building CXX object CMakeFiles/olive-editor.dir/dialogs/advancedvideodialog.cpp.o
[ 16%] Building CXX object CMakeFiles/olive-editor.dir/dialogs/autocutsilencedialog.cpp.o
/var/tmp/pamac-build-ralf/olive/src/olive-0.1.2/dialogs/advancedvideodialog.cpp: In Konstruktor »AdvancedVideoDialog::AdvancedVideoDialog(QWidget*, AVCodecID, VideoCodecParams&)«:
/var/tmp/pamac-build-ralf/olive/src/olive-0.1.2/dialogs/advancedvideodialog.cpp:47:45: Fehler: ungültige Umwandlung von »const AVCodec*« in »AVCodec*« [-fpermissive]
   47 |   AVCodec* codec_info = avcodec_find_encoder(static_cast<AVCodecID>(encoding_codec));
      |                         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             const AVCodec*
make[2]: *** [CMakeFiles/olive-editor.dir/build.make:264: CMakeFiles/olive-editor.dir/dialogs/advancedvideodialog.cpp.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/olive-editor.dir/all] Fehler 2
make: *** [Makefile:136: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...

**Comment by ThomasWilshaw** [comment]
It looks like you're trying to compile Olive 0.1 which is no longer supported. Please try 0,2

**Comment by Simran-B** [comment]
Using a newer FFmpeg or compiler than what the code was originally written for makes it more likely to run into problems. You might be able to bypass some issues by downgrading errors to warnings and by not failing the compilation on warnings, but I don't know how to set the respective flags by heart. It might be easier to adjust the code to make the data types match.
