### ISSUE TITLE
[UI] Dysfunctional numerical inputs on all dialogue boxes

### ISSUE THREAD

**Issue by Beamer4U** [olive-editor/olive#1945]
**Commit Hash** 
44d81f6b

**Platform** 
Linux Mint 19.1 Tessa 64-bit Mate 1.20.1

**Summary**
Numerical inputs on all dialogue boxes with a left mouse click are dysfunctional - I'm not able to change between 1, 0.1 and 10 etc., I can't logically slide change the numbers, and not able to manually enter numbers. If I manually L/C many times - I might (just about) enter the manual numerical box. Otherwise, this is a superb application and I'm looking forward to its' development.

**Additional Information / Output**
Memory: 7.7 GiB. Processor: Intel® Core™ i5-4590 CPU @ 3.30GHz × 4. Available Disc Space: 146.4 GiB

**Comment by Simran-B** [comment]
Can you share a screen recording demonstrating the issues?

**Comment by Beamer4U** [comment]
Hi Simran
Thank you for your response, I'm a complete novice at GitHub, but I'll give
it a go :)

**Comment by Beamer4U** [comment]
Mate Terminal - upon powering Olive up:
micky@OurPC-ThinkCentre-M93p:~$ sudo ./Olive-44d81f6b-Linux-x86_64.AppImage
[sudo] password for micky:       
[WARNING] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root' ((null):0)
[DEBUG] Extracting default OCIO config to "/home/micky/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.15.2 ((null):0)
ALSA lib pcm_dsnoop.c:618:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[INFO] Setting output audio device to default ((null):0)
[INFO] Setting input audio device to default ((null):0)
[DEBUG] Using graphics driver: Intel Open Source Technology Center ((null):0)
[WARNING] libpng warning: iCCP: known incorrect sRGB profile ((null):0)

Mate Terminal added text - upon Olive running:
[DEBUG] olive::ProjectLoadTask(0x5842bc0) took 18 ((null):0)
[WARNING] QWidget::setWindowModified: The window title does not contain a '[*]' placeholder ((null):0)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f5ea8502440] st: 1 edit list: 1 Missing key frame while searching for timestamp: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f5ea8502440] st: 1 edit list 1 Cannot find an index entry before timestamp: 0.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f5e90848dc0] st: 1 edit list: 1 Missing key frame while searching for timestamp: 0
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f5e90848dc0] st: 1 edit list 1 Cannot find an index entry before timestamp: 0.
[DEBUG] Selected node: olive::TextGeneratorV3(0x7f5ea008e8d0) ((null):0)
[DEBUG] olive::ProjectSaveTask(0x5db00e0) took 9 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654514661.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x64ab1b0) took 10 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654514721.ove" ((null):0)
[WARNING] QObject::startTimer: Timers can only be used with threads started with QThread ((null):0)
[DEBUG] olive::ProjectSaveTask(0x642f850) took 11 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654514781.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x65e5950) took 8 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654514841.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x593b9c0) took 8 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654514901.ove" ((null):0)
[DEBUG] olive::ProjectLoadTask(0x7f5ecc00ba30) took 11 ((null):0)
[DEBUG] Selected node: olive::TransformDistortNode(0x7f5ea0049bd0) ((null):0)
[DEBUG] Selected node: olive::TextGeneratorV3(0x7f5ea008e8d0) ((null):0)
[DEBUG] olive::ProjectSaveTask(0x58dfec0) took 12 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515021.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x7f5ecc011690) took 8 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515081.ove" ((null):0)
[DEBUG] Selected node: olive::TextGeneratorV3(0x7f5ea008e8d0) ((null):0)
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
[DEBUG] olive::ProjectSaveTask(0x643a940) took 4 ((null):0)
[DEBUG] olive::ProjectSaveTask(0x59487e0) took 9 ((null):0)
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
[DEBUG] olive::ProjectSaveTask(0x64a10e0) took 3 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515321.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x65d6bc0) took 4 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515561.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x65277c0) took 4 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515621.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x66550a0) took 3 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515681.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x6908120) took 11 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515741.ove" ((null):0)

Mate Terminal added text - upon turning Olive off:
[DEBUG] olive::ProjectSaveTask(0x7f5ecc011690) took 8 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515081.ove" ((null):0)
[DEBUG] Selected node: olive::TextGeneratorV3(0x7f5ea008e8d0) ((null):0)
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
[DEBUG] olive::ProjectSaveTask(0x643a940) took 4 ((null):0)
[DEBUG] olive::ProjectSaveTask(0x59487e0) took 9 ((null):0)
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
[DEBUG] olive::ProjectSaveTask(0x64a10e0) took 3 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515321.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x65d6bc0) took 4 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515561.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x65277c0) took 4 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515621.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x66550a0) took 3 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515681.ove" ((null):0)
[DEBUG] olive::ProjectSaveTask(0x6908120) took 11 ((null):0)
[DEBUG] Saved auto-recovery to: "/home/micky/.local/share/olivevideoeditor.org/Olive/autorecovery/{374eea22-8ba9-46ac-b1aa-674a9f4b1852}/1654515741.ove" ((null):0)
micky@OurPC-ThinkCentre-M93p:~$

Now my issue video with Olive 0.2.0:
https://user-images.githubusercontent.com/106935778/172162222-b93b9594-fb0b-428f-bdd9-0a8f461a8b6c.mp4

I hope this helps you, to help us :)

**Comment by sobotka** [comment]
Please fill out the template properly.

**Comment by Beamer4U** [comment]
Many apologies - I hope I've got it right this time?

**Comment by sobotka** [comment]
Add the hash please.

**Comment by Simran-B** [comment]
The hash is 44d81f6b.

Thanks for the video. It looks like the active ladder element doesn't change when you hover over one, at least most of the time. Starting at 1:03, it does change a few times for some reason. It seems to coincide with the cursor moving to the left of the ladder widget, sometimes even touching the border?

You appear to be able to click the numeric properties to type in a value, again, most of the time. At 1:30, it looks like the ladder appears and immediately vanishes even though it should remain visible? Did you click the left mouse button a single time, with no keys held down?

**Comment by Beamer4U** [comment]
Blimey, I'm impressed at how quickly you respond, thank you. I've added the
Hash, hopefully, it's all OK now - I'm learning on the job :)
Q: "It looks like the active ladder element doesn't change when you hover
over one etc".
A: If I mouse hoover with no buttons pressed - no ladder option will
display. If I left click and hold - the ladder will display and numbers can
then go up and down (to a fixed number) by swiping whilst still holding LC
down.
Q: "It seems to coincide with the cursor moving to the left etc".
A: Occasionally I get the same impression, but it's much more miss than
hit, I've even operated this very sloooowly - still can't determine?
Q: "You appear to be able to click the numeric properties to type in a
value etc".
A: It's a real struggle - more miss than hit.
Q: "Did you click the left mouse button a single time etc".
A: I'm hovering over the number value and left-clicking - the ladder
disappears when I click, and no other buttons are pressed. I've tried
fast/slow clicking, middle button and RH clicking. I see the value box
appear about every say, 15 LH clicks.

Thank you for your continued thoughts.

**Comment by Beamer4U** [comment]
Hi itsmattkc
Disabling the slider ladder did the trick it's now functioning superbly,
thank you. By the way, for all my rodent clicking and probing around Olive
- not one crash :) And I'm almost tempted to do my next video on it - at my
own risk, I know :)
