### ISSUE TITLE
Adding font face tags to subtitle text crashes Olive

### ISSUE THREAD

**Issue by brettvachon** [olive-editor/olive#1947]
**Commit Hash** 
0.2.0-5ef56c80

**Platform** 
Windows 8.1

**Summary**
I have imported an SRT file into my project and added it to the timeline.
In the subtitle track parameter editor, in the text editor I have attempted to change the font of the line of text by adding 

    <font face="Capriola">My subtitle text.

This format is supported in SRT and in other editors such as Kdenlive.
Unfortunately this crashes Olive editor

**Additional Information / Output**
Olive becomes not responding after adding `<font face="Capriola">` into subtitle text editor.

**Comment by itsmattkc** [comment]
Can you post a crash report? I can't recreate this on any of my setups.

**Comment by Simran-B** [comment]
Is there something akin to an official specification for the SRT format? The pages I found state that you can't set font faces:

> you can use the font tag only to change color

https://srt-subtitles.com/
