### ISSUE TITLE
debug error:abort() has been called

### ISSUE THREAD

**Issue by yourengod** [olive-editor/olive#1949]
When importing an image in the project window and then double-clicking the image or dragging the image into the Timeline window, the error "abort() has been called" is reported
![1655377679520](https://user-images.githubusercontent.com/6347733/174057428-d464632c-9d51-4919-a66a-28c4cae8840a.png)
what do I do?

**Comment by sobotka** [comment]
Please follow the template.

**Comment by yourengod** [comment]
The debug mode will report this error whether it is qt creator or vs2019, I don't know the reason

**Comment by yourengod** [comment]
@elsandosgrande 
1. Both Qt6 and qt5 will have the same error。
![image](https://user-images.githubusercontent.com/6347733/174539702-abc057a8-60ce-4dec-8cdd-8e0d223b1f22.png)

2. I am using the master branch source code, debug has this problem, but realse does not have this problem。I can't find a solution
