### ISSUE TITLE
[UI] Title text function seems to be broken in this nightly build 

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#1951]
**Commit Hash** 
5ef56c80

**Platform** 
Windows 10

**Summary**
The title text function seems to be broken in this nightly build. While I could adjust the position and the size of the title text box via mouse running build 44d81f6b it is not possible in this build anymore. But instead you can open the text properties dialog more than once (in my case I had it four times open). This shouldn't be possible. Could you please look what's wrong?

If you need a screen shot let me know. Currently I have the older build running.

**Additional Information / Output**

**Comment by Suk-RAM** [comment]
Now I can move and resized the title text box again, thank you, but I cannot write any text in the title text box. Can you pleace make this also possible again?

**Comment by Simran-B** [comment]
New issue tracked by #1953
