### ISSUE TITLE
[CRASH] Exporting audio only causes a crash

### ISSUE THREAD

**Issue by robybeen** [olive-editor/olive#1952]
**Commit Hash** 
240bbdc5

**Platform** 
Windows 10

**Summary**
Can't export a audio track (only audio in the sequence) as an audio media (mp3, wav, mp4 audio, ogg...)

**Steps to Reproduce**
Not sure if other footages create the same effect
1. Use an audio track without any other tracks
2. Export->Media-> choose any audio only format
3. Start

<details><summary><strong>Crash Report</strong></summary><pre><code>
https://pastebin.com/FRR6xR0W
password: mzjZ0RNPD8

</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
I can't recreate this on any of my systems, however based on your crash report, e69436a27d23cd70846e23d1d5d3370b18e34476 should fix it.
