### ISSUE TITLE
[UI] Title text box does not accept any text from keyboard.

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#1953]
**Commit Hash** 
d32a0527

**Platform** 
Windows 10

**Summary**
The title text box does not accept any text from keyboard. You can again resize and move the title text box, but you cannot insert text.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Yeah I'm working on it. It's hard to test because this issue only happens on Windows, which is not my main development setup.

**Comment by itsmattkc** [comment]
Fixed in 7bfe5f563e48af2c6d28fd209981a6af14cb575b

**Comment by Suk-RAM** [comment]
Thanks for fixing the problem! The title text box now works fine again on windows.
