### ISSUE TITLE
[CRASH] debug error:abort() has been called

### ISSUE THREAD

**Issue by yourengod** [olive-editor/olive#1956]
**Commit Hash** 
[7bfe5f5](https://github.com/olive-editor/olive/commit/7bfe5f563e48af2c6d28fd209981a6af14cb575b)

**Platform** 
Windows 10

**Summary**

- When importing an image in the project window and then double-clicking the image or dragging the image into the Timeline window, the error "abort() has been called" is reported

![image](https://user-images.githubusercontent.com/6347733/174541651-b407871d-319c-4770-a746-c0a349856908.png)
![image](https://user-images.githubusercontent.com/6347733/174541715-3d9c96cc-0940-461e-bad4-6ee3748abdd3.png)

- I am using the master branch source code, debug has this problem, but realse does not have this problem。I can't find a solution

**Steps to Reproduce**

1. 
2. 
3. 

<details><summary><strong>Crash Report</strong></summary><pre><code>
1127, FromFilemap
[WARNING] QWindowsWindow::setGeometry: Unable to set geometry 120x30+2737+479 (frame: 136x69+2729+448) on QWidgetWindow/"olive::TaskDialogClassWindow" on "\\.\DISPLAY2". Resulting geometry: 286x104+2737+479 (frame: 302x143+2729+448) margins: 8, 31, 8, 8 minimum size: 286x104 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=302,143 maxtrack=0,0) (void __cdecl QWindowsWindow::setGeometry(const class QRect &):1891)
[DEBUG] olive::ProjectImportTask(0x2b15d19f190) took 36 (bool __cdecl olive::Task::Start(void):100)
[WARNING] QWindowsWindow::setGeometry: Unable to set geometry 100x30+2614+483 (frame: 116x69+2606+452) on QWidgetWindow/"QMessageBoxClassWindow" on "\\.\DISPLAY2". Resulting geometry: 532x96+2614+483 (frame: 548x135+2606+452) margins: 8, 31, 8, 8 minimum size: 532x96 maximum size: 532x96 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=548,135 maxtrack=548,135) (void __cdecl QWindowsWindow::setGeometry(const class QRect &):1891)
[WARNING] Tried to allocate sample buffer with zero sample count (void __cdecl olive::SampleBuffer::allocate(void):89)
[WARNING] Tried to fill an unallocated sample buffer (void __cdecl olive::SampleBuffer::silence_bytes(int,int):214)
1127, FromFilemap

</code></pre></details>

**Additional Information**

**Comment by elsandosgrande** [comment]
What are the properties of the image in question? Does it happen with any old image, or only specific images?

**Comment by yourengod** [comment]
any picture。
But，I just tried this image and reported the following problem
![Lenna](https://user-images.githubusercontent.com/6347733/174551062-6a1cac01-38d5-4f66-9c31-b1beefc77d8f.png)


1127, FromFilemap
[WARNING] QWindowsWindow::setGeometry: Unable to set geometry 120x30+817+479 (frame: 136x69+809+448) on QWidgetWindow/"olive::TaskDialogClassWindow" on "\\.\DISPLAY1". Resulting geometry: 286x104+817+479 (frame: 302x143+809+448) margins: 8, 31, 8, 8 minimum size: 286x104 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=302,143 maxtrack=0,0) (void __cdecl QWindowsWindow::setGeometry(const class QRect &):1891)
