### ISSUE TITLE
[RENDER] Playing video sequence in preview window causes flickering, missing frames or missplaced frames.

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#1964]
**Commit Hash** 
3963797d

**Platform** 
Windows 10, 64 Bit

**Summary**
Playing video sequence in preview window causes flickering, missing frames or missplaced frames.

**Additional Information / Output**
In my setup I use several video tracks. The lowest track contains a picture that is used as background, all other tracks above show either rotated text or downscaled and rotated pictures above the background picture. All pictures are stills encoded in png-files.

When I run the sequence in the preview window I get nondeterministic results. It could happen that the sequence runs fine as expected and another time the outpout flickers, pictures are constantly missing or pictures are missplaced. If this happens it could help to clear the disk cache or to restart olive and reload the project again, but sometimes not.

I only run the sequence when the whole sequence was cached before (indicated by a completely green timeline).

The size of the pictures doesn't seem to matter, because when I use natively sized pictures as they come from my photo camera my computer shows the same workload (less than 20%) as when I use downscaled pictures with 2k size.

I don't experience the issue while working solely with video footage instead of stills. 

While using a former nightly build I experienced that the exported video file could also be affected by fickering, missing frames or missplaced frames, but this isn't true anymore. At least I cannot reproduce it.

Do you have an idea what causes the issue? And if so, how could it be avoided? Thanks in advance.

**Comment by itsmattkc** [comment]
Should be fixed in a6d1ec99a896c7f6b77cb0b12416a7ff95bc58f3
