### ISSUE TITLE
[EXPORT] First frame isn't in 0:00

### ISSUE THREAD

**Issue by Shoghy** [olive-editor/olive#1965]
**Commit Hash:** 15d6f407

**Platform:** Windows 10

**Summary:**
English is not my first language.

[English]
I edited some videos with this editor and then exported them to Unity. Unity in the console gives me an alert message that tells me that the first frame of the video is not in **0s** (0 seconds) but in **0.0666666...s** (2/30s). This does not prevent me from using it as an asset in my project, but during 1 frame where the video should be displayed, the screen turns completely black.

[Español]
Edité unos vídeos con este editor y luego los exporté a Unity. Unity en la consola me da un mensaje de alerta que me avisa que el primer frame del vídeo no se encuentra en **0s** (0 segundos) sino en **0.0666666...s** (2/30s). Esto no me impide utilizarlo como asset en mi proyecto, pero durante 1 frame donde se debe mostrar el vídeo, la pantalla se vuelve completamente negra.

**Comment by Shoghy** [comment]
https://user-images.githubusercontent.com/54950187/180103009-38628024-858f-4670-bc41-6bff5bcf4275.mp4

**Comment by itsmattkc** [comment]
I'm afraid I can't confirm this is an Olive issue rather than a Unity issue. According to `ffprobe -show_frames`, the first frame _does_ start at 0:

```
[FRAME]
media_type=video
stream_index=0
key_frame=1
pts=0
pts_time=0.000000
pkt_dts=0
pkt_dts_time=0.000000
best_effort_timestamp=0
best_effort_timestamp_time=0.000000
pkt_duration=1500
pkt_duration_time=0.016667
pkt_pos=48
pkt_size=3502
width=1080
height=1920
pix_fmt=yuv420p
sample_aspect_ratio=1:1
pict_type=I
coded_picture_number=0
display_picture_number=0
interlaced_frame=0
top_field_first=0
repeat_pict=0
color_range=unknown
color_space=unknown
color_primaries=unknown
color_transfer=unknown
chroma_location=left
[SIDE_DATA]
side_data_type=H.26[45] User Data Unregistered SEI message
[/SIDE_DATA]
[/FRAME]
```

Is there any other software that exhibits what you're describing? Also perhaps try uploading as a zip or to a formal file sharing website, in case GitHub transcoded the video and is making it undetectable on my side.

**Comment by Shoghy** [comment]
[Entrada de Seleccion Isaac.zip](https://github.com/olive-editor/olive/files/9163536/Entrada.de.Seleccion.Isaac.zip)
I have not tried to import the video to other programs just Unity

**Comment by itsmattkc** [comment]
I'm afraid it shows the same thing, as far as I can tell the first frame is 0.

Have you tried different containers like QuickTime/MOV?

**Comment by Shoghy** [comment]
Nope
