### ISSUE TITLE
[EXPORT]  export the video with default setting + 0 in compression method slider, produce weird result.

### ISSUE THREAD

**Issue by JaydeepGo** [olive-editor/olive#1967]
**Commit Hash** 
13a0da53

**Platform** 
Manjaro 5.18.7.1 

**Summary**
When I export the video with default setting + 0 in compression method slider.
It produces a weird end result. 

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/29326238/178367577-c59c7a2a-a4aa-4c11-94a9-0e1e4c5107ce.png)

**Comment by itsmattkc** [comment]
Don't use a CRF of 0. Stick to 17-18.
