### ISSUE TITLE
[UI]  Can't resize the import window explorer columns.

### ISSUE THREAD

**Issue by JaydeepGo** [olive-editor/olive#1968]
**Commit Hash** 
13a0da5

**Platform** 
Manjaro 5.18.7.1

**Summary**
Can't resize the import window explorer columns.

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/29326238/178367933-8b8e556b-f83d-4979-ab24-3fe8fd62d227.png)

**Comment by itsmattkc** [comment]
Blame Qt.
