### ISSUE TITLE
[PLAYBACK] Playback is slow and laggy.

### ISSUE THREAD

**Issue by 111ukasz111** [olive-editor/olive#1969]
**Commit Hash** 

**Platform** 
windows 10 geforce 920m intel core i7

**Summary**

**Additional Information / Output**

**Comment by sobotka** [comment]
If you do not have the willingness to fill out the template, and have the ability to delete the template, you might want to consider if it is worth placing an issue in the tracker for a developer to look at.

Do your part. Don’t be lazy.
