### ISSUE TITLE
Change target from "Olive" to "olive-editor"

### ISSUE THREAD

**Issue by itsmattkc** [olive-editor/olive#197]
I'm considering changing the Qt target from "Olive" to "olive-editor" to better confirm to Unix naming style and allow for better consistency (it's less likely "olive-editor" will be already taken compared to "olive", though the capital O does help differentiate it at the moment).

This will of course affect anyone maintaining a package of Olive, which luckily at the moment is only a handful of people, but also why I think it'd be good to do this sooner rather than later. What are peoples thoughts on this?

**Comment by alexmyczko** [comment]
I am all for it!

**Comment by eszlari** [comment]
This change would affect classic Linux packaging (deb, rpm etc.), but is almost completely irrelevant for the new packaging methods (flatpak, snap, appimage), because they are mostly self-contained / isolated from the host system.

**Comment by itsmattkc** [comment]
Done in d2654f99806be0403f5dc5512ffb3d5389e07801
