### ISSUE TITLE
[CRASH] Olive doesn't run under ArcoLinux

### ISSUE THREAD

**Issue by rempas** [olive-editor/olive#1973]
**Commit Hash** a6d1ec99

**Platform** ArcoLinux

**Summary**
I have downloaded the latest nightly Appimage for Linux and when I try to execute it, I'm getting the following error message:

```
/tmp/.mount_Olive-gFSNWY/usr/bin/olive-editor: /usr/lib/liblzma.so.5: version `XZ_5.1.2alpha' not found (required by /tmp/.mount_Olive-gFSNWY/usr/bin/../lib/libboost_iostreams.so.1.76.0)
/tmp/.mount_Olive-gFSNWY/usr/bin/olive-editor: /usr/lib/liblzma.so.5: version `XZ_5.2.2' not found (required by /tmp/.mount_Olive-gFSNWY/usr/bin/../lib/libboost_iostreams.so.1.76.0)
```

**Steps to Reproduce**

1. Make the Appimage executable
2. Execute it
3. Prints the error message and automatically closes after some seconds

<details><summary><strong>Crash Report</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
I have no crash report as the app doesn't even open...

**Comment by itsmattkc** [comment]
Merging into #1487
