### ISSUE TITLE
[NODES] Crash when editing polygon/mask points

### ISSUE THREAD

**Issue by bunnywaffle** [olive-editor/olive#1975]
**Commit Hash** 

Crash when editing polygon/mask points

**Platform** 
Windows 11

**Summary**

I was making an animated title and I needed a mask, but when I edited the points in the mask node, Olive crashed, and I am using the latest nightly build. And it is happening again and again.

![image](https://user-images.githubusercontent.com/100540808/179626000-f46677e0-1fbf-49f3-945d-0c0eba18fa18.png)

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Can you provide a crash report?

**Comment by bunnywaffle** [comment]
The crash report is completely blank.

![image](https://user-images.githubusercontent.com/100540808/179723216-c201ffc8-7009-478c-8fb1-e2b0dd2cb470.png)
