### ISSUE TITLE
[EXPORT] While exporting, the app crashes or the exportation simply stops before reaching the end.

### ISSUE THREAD

**Issue by benflute** [olive-editor/olive#1977]
**Commit Hash** 

**Platform** 

**Summary** <!-- I was exporting a video (1440:810, 60 fps), the length of which was roughly 3 hours and a half. Unfortunately, before even reaching 50% of the process, Olive crashed and the exported file was obviously damaged. This time, I had selected the option "target bit rate" and chosen 2 pass encoding, because when I previously attempted to export by choosing "constant bit rate" (18), the exportation stopped before reaching the end and failed even so, although I had previously managed to successfully export another project (of the same resolution and fps and roughly of the same length) with the same settings. I very much need this problem to be fixed and hope that it will as soon as possible. Thank you in advance.**

**Comment by itsmattkc** [comment]
Please fill in the issue template, just saying "it crashes during my export" isn't much for us to go on. Please fill in the commit hash, platform, and provide a crash report if you can.

**Comment by itsmattkc** [comment]
Closing until more information is provided
