### ISSUE TITLE
[EXPORT] Scrubbing video preview makes preview to disappear

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1978]
**Commit Hash** 
f2e604c2

**Platform** 
macOS 12.3

**Summary**
When in the export window, if I scrub the video preview then the preview image disappears. Pressing Play button or resizing the window fix the issue and the image goes back.
<img width="803" alt="export_popup" src="https://user-images.githubusercontent.com/5942369/180609187-09f27f92-8a7c-4a7e-bf3c-feaf9916097b.png">

**Additional Information / Output**

**Comment by itsmattkc** [comment]
I'm afraid I can't recreate this, even on macOS:

https://user-images.githubusercontent.com/34096995/180617194-040bc76c-067b-4bad-9cdb-cc00e4d06ae3.mp4

**Comment by pgilfernandez** [comment]
In the last build, d7748c4a, it is gone so you can close the issue.

Thanks!
