### ISSUE TITLE
[EDIT] After changing marker color it shifts or follows mouse

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1981]
**Commit Hash** 
f2e604c2

**Platform** 
macOS 12.3

**Summary**
When you want to change a marker color, you press right mouse button and in the dropdown you select the color you want. After doing that, the marker follows the mouse as if you wanted to change its position in the timeline. You can very easily check the behavior in the following video:
![marker_shift](https://user-images.githubusercontent.com/5942369/180610358-0ed2de9b-7c39-48fc-8a70-f56f686d3c8e.gif)

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
I'm unable to repolicate this on Windows 10 so it's possible a OS specific bug. The linked PR might fix it though, could you try it?

**Comment by pgilfernandez** [comment]
It works fine now

Thanks!
