### ISSUE TITLE
[CACHE] Shouldn't the timeline turn into red as a whole when clearing the disk cash?

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#1986]
**Commit Hash** 
1fa171e5

**Platform** 
Windows 10

**Summary**
When I clear the disk cash I would expect that the whole timeline turns from green into red. It does but only the visible part of it. When I scroll to make a hidden part visible - just after clearing the disk cash - the timeline is already colored green.

**Additional Information / Output**
When running a sequence in the preview window it seems to me that it performs less smooth and uses more cpu power than former nightlies did, even pre-cashed parts of a sequence.

**Comment by itsmattkc** [comment]
The cache is currently being rewritten in a separate branch. Things like this will be resolved there.

**Comment by Suk-RAM** [comment]
Thanks for the information. But what about the performance issue? I have just compared the behaviour of the most recent nightly 1fa171e with the older nightly 46be693b. While i cannot work with the newest one, the older performs very well. Would that also be addressed when the cash gets rewritten? Thanks in advance.

**Comment by itsmattkc** [comment]
That has nothing to do with it. I am not aware of any performance changes between those two versions.
