### ISSUE TITLE
[UI] Better video transformation handling

### ISSUE THREAD

**Issue by nesper8** [olive-editor/olive#1989]
**Commit Hash** 
ed744802

**Platform** 
Windows 10

**Summary** 
Right now Olive's video transformation handling in the sequence viewer is kinda barebones 
and is something which can be better improved to meet more modern standards.

Current Implementation
https://user-images.githubusercontent.com/57890520/181499092-784ea2d6-1457-47fa-96ec-311d700d1a7b.mp4

Proposing Implementation
https://user-images.githubusercontent.com/57890520/181500204-fcb45cd9-2520-49e5-9277-32966bf14aca.mp4

**Comment by itsmattkc** [comment]
All you're showing is resizing that isn't anchored to the center?

**Comment by nesper8** [comment]
sorry i have this problem of being unable to convey what i want to say

so uh the resize handles of videos in the sequence viewer are always anchored to the center right?
instead can you implement a way for the resize handles to be anchored to the opposite handle like i shown on adobe photoshop
