### ISSUE TITLE
[PROJECT] Can't save the project, nothing happens

### ISSUE THREAD

**Issue by NicKoehler** [olive-editor/olive#1991]
**Commit Hash**
5a067f5

**Platform**
Arch Linux
kernel: 5.18.14-zen1-1-zen
DE: Gnome

**Summary**
When I try to save the project nothing happens, no dialog or error.
This actually doesn't happens using the nightly appimage, but it happens only with the binary I compiled.

**Additional Information / Output**
Compiled with:
`cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr -DOTIO_DEPS_INCLUDE_DIR=/usr/include/opentimelineio`

**Comment by itsmattkc** [comment]
We don't support custom builds. If it works in the AppImage, just use the AppImage.
