### ISSUE TITLE
[EDIT] Animating a text node position makes text track inconsistency

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1994]
**Commit Hash** 
10bc448c

**Platform** 
macOS 12.3

**Summary**
When animating the Position value of a Text node, that is, making a text move along time and the canvas, turns into a weird "text tracking inconsistency" undesired effect:
![choppy3](https://user-images.githubusercontent.com/5942369/182018752-eef6fa53-317d-4d7f-a28e-be297965ea13.gif)

If you add a Transform node after the Text node, the weird effect is gone. In the previous video you can see both clips working together to see the difference:
- choppy: just animating the Position value of a Text node
- soft: animating a Transform node after the Text one

**Additional Information / Output**
The "problem" looks to be related with Sequence preview resolution as if you preview it in full resolution (or render a final video) this issue is not present, that is, it only affects the editor preview. Anyway it is annoying and may confuse users that would look at this particular issue as an Olive bug.

[choppy_text.ove.zip](https://github.com/olive-editor/olive/files/9228537/choppy_text.ove.zip)

**Comment by itsmattkc** [comment]
This is a limitation of Qt's text renderer. I don't think there's much we can do, and in the future I think we may be defaulting to full resolution anyway.

**Comment by pgilfernandez** [comment]
And what about making the Text node be a "group node" created by a Text and a Transform node and where all the exposed parameters come from the Text node but the Position that comes from the Transform one?

**Comment by itsmattkc** [comment]
I mean users can do that if they want, but they're not actually the same thing. Try creating scrolling credits and you'll see what I mean.
