### ISSUE TITLE
[UI] Olive is not saving a custom window layout

### ISSUE THREAD

**Issue by porrarafaelmano** [olive-editor/olive#2002]
**Commit Hash** 
45bn8520

**Platform**
Debian 11 [stable]

**Summary**
When I open Olive, the first thing I do is to customize the entire layout, but when I close the software and open it again, Olive doesn't save my custom layout. It only works when I save a project, but then, I must have a "default" project for always open my favorite layout.

Same for shortcuts.

**Comment by itsmattkc** [comment]
Duplicate of #1231
