### ISSUE TITLE
[CRASH] Clicking a video can cause a crash by 'rare' chance.

### ISSUE THREAD

**Issue by EditaNEmilis** [olive-editor/olive#2003]
**Commit Hash** 
02f40ad

**Platform** 
Windows 10

**Summary**
I was making a video of Perry's Cafe, I got my recorded OBS part to put in for some part.
But when I click one of my recorded video part... Crashed, unexpected.

<details><summary><strong>Crash Report</strong></summary><pre><code>

Can't send due to Github body limit, had to send a WeTransfer link.
https://we.tl/t-4QxGtfow7R
</code></pre></details>

**Additional Information**
Had copied the crash log from my notepad and saved it. So I won't forget.

**Comment by itsmattkc** [comment]
Can you provide steps to reproduce?

**Comment by EditaNEmilis** [comment]
Well I can, but trying to get that crash again might take too long. Oops.

**Comment by itsmattkc** [comment]
Closing until steps to reproduce are provided.
