### ISSUE TITLE
[UI] Change "color picker" button position at Select Color popup

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#2005]
**Commit Hash** 
409f24be

**Platform** 
macOS 12.3 (all)

**Summary**
When using the (great) Select Color popup window I find really confusing the placement of the screen color picker (the one with "Pick" label):
<img width="986" alt="color_window0" src="https://user-images.githubusercontent.com/5942369/184089469-123784d6-f362-4734-8cc7-163caadbaad9.png">

- as being so close to the "Preview" box
- because the focused button is that one (in blue)
- and even because you can think that the "Pick" button means "I want to pick or choose the color you are showing in the preview box"

All of that confuses me and think that it is the "Ok" button...
I would suggest to move it to the lower left corner as it is a non important button:
<img width="986" alt="color_window1" src="https://user-images.githubusercontent.com/5942369/184089501-b1d07eca-92ca-48e1-a65f-312ed423493f.png">

**Additional Information / Output**
Additionally I would change the "Pick" label for an icon (I'll be glad to design it) and I would make the "Ok" button to be the default highlighted one in this popup window:
<img width="986" alt="color_window3" src="https://user-images.githubusercontent.com/5942369/184090730-96cf0124-bccf-43e5-9f95-df953261b2e0.png">

Let me know if you like the changes and I design and PR the icon (the one I used it's just a mockup from the internet).

Cheers

**Comment by itsmattkc** [comment]
I think that the icon is good, but I don't like the placement in the lower left. It's in the middle of nowhere there and looks really out of place. I actually think it's sensible for the pick button to be next to the preview box, and that having an icon should dispel any confusion. I can also ensure the OK button is the highlighted/default button to further make it clear.

**Comment by pgilfernandez** [comment]
OK, I agree that just using the icon could make it not confusing anymore.
I'll PR it.
