### ISSUE TITLE
[UI] Vertical alignment text is shifted

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#2007]
**Commit Hash** 
409f24be

**Platform** 
macOS 12.3

**Summary**
When using "Middle" or "Bottom" text vertical alignment, the rendered text goes correctly into place but the actual line for selecting individual letters, words, etc. are still in their "default position" (Top):
<img width="633" alt="alignment" src="https://user-images.githubusercontent.com/5942369/184093659-36d1926c-c66d-46d7-9813-b87fc9183250.png">
_In the previous screenshot I have selected the word "text"._

It makes unnatural and hard to select the real part of the text that you want to edit...

Thanks

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Known issue.
