### ISSUE TITLE
[UI] The User Interface looks distorted

### ISSUE THREAD

**Issue by liammcsh2008** [olive-editor/olive#2010]
**Commit Hash** 
409f24be 

**Platform** 
Windows 11

**Summary**
I downloaded Olive 0.2 and opened it up, and I found out that the Ui is distorted and making it unusable, which means I can't edit my videos

**Additional Information / Output**
![2022-08-11 (1)](https://user-images.githubusercontent.com/71038452/184168061-03e71974-40bd-4abf-8a85-40e56dc2927f.png)

**Comment by itsmattkc** [comment]
- Is this a new issue? Were you able to use earlier versions of 0.2?
- What GPU do you have?
- Is your graphics driver up to date?

**Comment by liammcsh2008** [comment]
My Graphics driver is up to date, I have a Nvidia GPU, and this program is running on Visual C++, tried re-installing it using portable version, but still didn't work, I was able to use early versions of 0.2

**Comment by itsmattkc** [comment]
Can you try recent commits cc7893e7 and 30b64d9b?

**Comment by liammcsh2008** [comment]
How do I get those commits?

**Comment by itsmattkc** [comment]
You can either use `git checkout` if you're self-compiling or download the binaries here: https://olivevideoeditor.org/nightly.php

**Comment by liammcsh2008** [comment]
I found out that this is the only computer that has this issue, I tried other computers and the ui is fine

**Comment by itsmattkc** [comment]
Do you consider the issue resolved then or are you still going to try those commits?

**Comment by liammcsh2008** [comment]
I will try those commits and see

**Comment by liammcsh2008** [comment]
It didn't work, still got the distorted ui
