### ISSUE TITLE
[UI] Turkish Menu

### ISSUE THREAD

**Issue by DrVektor** [olive-editor/olive#2011]
File ==> Dışa aktar is wrong, it must be İçe aktar. Dışa is : to out /export. İçe aktar is : import please fix this. 
![yanlış foto](https://user-images.githubusercontent.com/105983978/184182907-7059dd64-28ed-4fc3-a80e-662aa5b1314c.png)
please look to picture for understanding for clear. Ctrl+I is import but in turkish is wrong. It has been translated in english export in turkish dışa aktar in old turkish ihraç. i hope everything is clear. Have fun byee
**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**

**Comment by itsmattkc** [comment]
No one on our team speaks Turkish so we must rely on community contributions for translations. If you see something wrong, feel free to contribute a correction with the following guide: https://github.com/olive-editor/olive/wiki/Translations
