### ISSUE TITLE
[CRASH] Moving clips with the keyboard

### ISSUE THREAD

**Issue by porrarafaelmano** [olive-editor/olive#2012]
**Commit Hash** 
a88hjklc

**Platform** 
Ubuntu Studio 22.04.1 LTS

**Summary**
I tried to move two clips (with no space between them) by using a shortcut (Alt + Right Arrow).

**Steps to Reproduce**

1. Import a clip for your timeline and duplicate it;
2. Remove the space between these clips; 
4. Select these two clips (or create a group) and move them with Alt + Right Arrow;

The first clip will override the second clip, and then Olive will crash. 

<details><summary><strong>Crash Report</strong></summary>
<pre><code>
Operating system: Linux
5.15.0 -46-lowlatency #49-Ubuntu SMP PREEMPT Thu Aug 4 18:56:09 UTC 2022 x86_64
CPU: amd64
family 23 model 8 stepping 2
12 CPUs

GPU: UNKNOWN

Crash reason: SIGSEGV /SEGV_MAPERR
Crash address: 0x90
Process uptime: 9 seconds

Thread 0 (crashed)
0 olive-editor!olive::Node::ConnectEdge(olive::Node*, olive::NodeInput const&) [vector.tcc : 112 + 0x0]
rax = 0x0000000000000002 rdx = 0x0000000006b12b20
rcx = 0x0000000000000000 rbx = 0x0000000000000002
rsi = 0x0000000004c29780 rdi = 0x0000000006b12b20
rbp = 0x0000000000000000 rsp = 0x00007ffc3a2a6450
r8 = 0x000000000671e860 r9 = 0x0000000000795480
r10 = 0x0000000000000007 r11 = 0x0000000000000007
r12 = 0x00007ffc3a2a64a0 r13 = 0x0000000004d4a980
r14 = 0x0000000000000000 r15 = 0x0000000006b36510
rip = 0x00000000005d620e
Found by: given as instruction pointer in context
1 olive-editor!olive::PreviewAutoCacher::AddEdge(olive::Node*, olive::NodeInput const&) [previewautocacher.cpp : 304 + 0x8]
rbx = 0x0000000000000002 rbp = 0x0000000000000000
rsp = 0x00007ffc3a2a64a0 r12 = 0x0000000004d4a980
r13 = 0x0000000004d4a980 r14 = 0x0000000000000000
r15 = 0x0000000006b36510 rip = 0x0000000000611666
Found by: call frame info
2 olive-editor!olive::PreviewAutoCacher::ProcessUpdateQueue() [previewautocacher.cpp : 243 + 0x8]
rbx = 0x000000000079d9f0 rbp = 0x0000000000000000
rsp = 0x00007ffc3a2a64d0 r12 = 0x0000000004d4a980
r13 = 0x0000000004d4a980 r14 = 0x0000000004d4aa10
r15 = 0x0000000006b36510 rip = 0x0000000000611212
Found by: call frame info
3 olive-editor!olive::PreviewAutoCacher::TryRender() [previewautocacher.cpp : 546 + 0x8]
rbx = 0x00000000069c8190 rbp = 0x0000000000000000
rsp = 0x00007ffc3a2a6530 r12 = 0x00007f59e80148d0
r13 = 0x0000000004d4a980 r14 = 0x0000000004d4a980
r15 = 0x0000000004d4aaa8 rip = 0x000000000060f06b
Found by: call frame info
4 olive-editor!olive::PreviewAutoCacher::VideoRendered() [previewautocacher.cpp : 225 + 0x8]
rbx = 0x00000000069c8190 rbp = 0x0000000000000000
rsp = 0x00007ffc3a2a6650 r12 = 0x00007f59e80148d0
r13 = 0x0000000000000003 r14 = 0x0000000004d4a980
r15 = 0x0000000004d4aaa8 rip = 0x0000000000610d90
Found by: call frame info
5 libQt5Core.so.5 + 0x2d9e33
rbx = 0x0000000006cd8910 rbp = 0x00007ffc3a2a67a0
rsp = 0x00007ffc3a2a66e0 r12 = 0x00000000068605e0
r13 = 0x0000000000000003 r14 = 0x0000000006ced700
r15 = 0x0000000006860610 rip = 0x00007f5a6d4f4e33
Found by: call frame info
6 olive-editor!olive::RenderTicketWatcher::Finished(olive::RenderTicketWatcher*) [moc_renderticket.cpp : 265 + 0x13]
rbp = 0x00007ffc3a2a6840 rsp = 0x00007ffc3a2a67b0
rip = 0x000000000049bb3f
Found by: previous frame's frame pointer
7 libQt5Core.so.5 + 0x2d1179
rbp = 0x00007ffc3a2a6840 rsp = 0x00007ffc3a2a67e0
rip = 0x00007f5a6d4ec179
Found by: call frame info
8 olive-editor!_fini + 0x84d28c
rbp = 0x00007ffc3a2a6840 rsp = 0x00007ffc3a2a67f8
rip = 0x0000000000fac730
Found by: stack scanning
9 libQt5Core.so.5 + 0x2a571b
rbp = 0x00007ffc3a2a6840 rsp = 0x00007ffc3a2a6800
rip = 0x00007f5a6d4c071b
Found by: stack scanning
10 libQt5Widgets.so.5 + 0x1646ef
rsp = 0x00007ffc3a2a6850 rip = 0x00007f5a6e0566ef
Found by: stack scanning
11 libQt5Widgets.so.5 + 0x16cec8
rsp = 0x00007ffc3a2a6880 rip = 0x00007f5a6e05eec8
Found by: stack scanning
12 libQt5Core.so.5 + 0x2ba910
rsp = 0x00007ffc3a2a68c0 rip = 0x00007f5a6d4d5910
Found by: stack scanning
13 libQt5Core.so.5 + 0x604890
rsp = 0x00007ffc3a2a68f0 rip = 0x00007f5a6d81f890
Found by: stack scanning
14 libc.so.6 + 0xa54d3
rsp = 0x00007ffc3a2a6970 rip = 0x00007f5a6ce4c4d3
Found by: stack scanning
15 libQt5Core.so.5 + 0xcb626
rsp = 0x00007ffc3a2a6990 rip = 0x00007f5a6d2e6626
Found by: stack scanning
16 libQt5Core.so.5 + 0x6027a8
rsp = 0x00007ffc3a2a69b8 rip = 0x00007f5a6d81d7a8
Found by: stack scanning
17 libQt5Core.so.5 + 0x2a599a
rsp = 0x00007ffc3a2a69d0 rip = 0x00007f5a6d4c099a
Found by: stack scanning
18 libc.so.6 + 0xa54d3
rsp = 0x00007ffc3a2a6a10 rip = 0x00007f5a6ce4c4d3
Found by: stack scanning
19 libQt5Core.so.5 + 0x2a80f1
rsp = 0x00007ffc3a2a6a40 rip = 0x00007f5a6d4c30f1
Found by: stack scanning
20 libQt5Gui.so.5 + 0x105940
rsp = 0x00007ffc3a2a6a58 rip = 0x00007f5a6d925940
Found by: stack scanning
21 libglib-2.0.so.0 + 0x54185
rsp = 0x00007ffc3a2a6a90 rip = 0x00007f5a6691a185
Found by: stack scanning
22 libQt5Core.so.5 + 0x2fc110
rsp = 0x00007ffc3a2a6ac0 rip = 0x00007f5a6d517110
Found by: stack scanning
23 libQt5Core.so.5 + 0x2fc123
rsp = 0x00007ffc3a2a6ad0 rip = 0x00007f5a6d517123
Found by: stack scanning
24 libglib-2.0.so.0 + 0x55d1b
rsp = 0x00007ffc3a2a6ae0 rip = 0x00007f5a6691bd1b
Found by: stack scanning
25 libglib-2.0.so.0 + 0xaa6f8
rsp = 0x00007ffc3a2a6b60 rip = 0x00007f5a669706f8
Found by: stack scanning
26 libglib-2.0.so.0 + 0x533c3
rsp = 0x00007ffc3a2a6bc0 rip = 0x00007f5a669193c3
Found by: stack scanning
27 libQt5Core.so.5 + 0x2fb7ee
rsp = 0x00007ffc3a2a6be0 rip = 0x00007f5a6d5167ee
Found by: stack scanning
28 libQt5Core.so.5 + 0x2a470b
rsp = 0x00007ffc3a2a6c30 rip = 0x00007f5a6d4bf70b
Found by: stack scanning
29 libQt5Core.so.5 + 0x2a42bb
rsp = 0x00007ffc3a2a6c60 rip = 0x00007f5a6d4bf2bb
Found by: stack scanning
30 libQt5Core.so.5 + 0x6027a8
rsp = 0x00007ffc3a2a6c70 rip = 0x00007f5a6d81d7a8
Found by: stack scanning
31 libQt5Core.so.5 + 0x3d2370
rsp = 0x00007ffc3a2a6c80 rip = 0x00007f5a6d5ed370
Found by: stack scanning
32 libQt5Core.so.5 + 0x2ac1cc
rsp = 0x00007ffc3a2a6ca0 rip = 0x00007f5a6d4c71cc
Found by: stack scanning
33 libQt5Core.so.5 + 0x5fd188
rsp = 0x00007ffc3a2a6ca8 rip = 0x00007f5a6d818188
Found by: stack scanning
34 libQt5Core.so.5 + 0x3d2370
rsp = 0x00007ffc3a2a6cc8 rip = 0x00007f5a6d5ed370
Found by: stack scanning
35 libQt5Core.so.5 + 0x3d2370
rsp = 0x00007ffc3a2a6ce0 rip = 0x00007f5a6d5ed370
Found by: stack scanning
36 olive-editor!main [main.cpp : 276 + 0x5]
rsp = 0x00007ffc3a2a6cf0 rip = 0x0000000000744861
Found by: stack scanning
37 libc.so.6 + 0x29d90
rbx = 0x0000000000000000 rbp = 0x0000000000000002
rsp = 0x00007ffc3a2a6e80 r12 = 0x00007ffc3a2a6f88
r13 = 0x00000000007424d0 r14 = 0x0000000000000000
r15 = 0x00007f5a71cac040 rip = 0x00007f5a6cdd0d90
Found by: call frame info
38 libc.so.6 + 0x21aee8
rsp = 0x00007ffc3a2a6e88 rip = 0x00007f5a6cfc1ee8
Found by: stack scanning
39 ld-linux-x86-64.so.2 + 0x3a040
rsp = 0x00007ffc3a2a6ed0 rip = 0x00007f5a71cac040
Found by: stack scanning
40 libc.so.6 + 0x29e40
rsp = 0x00007ffc3a2a6f20 rip = 0x00007f5a6cdd0e40
Found by: stack scanning
41 olive-editor!_GLOBAL__sub_I_system_error48.cc + 0x3c
rsp = 0x00007ffc3a2a6f50 rip = 0x000000000048c3fc
Found by: stack scanning
42 0x7ffc3a2a6f80
rsp = 0x00007ffc3a2a6f58 rip = 0x00007ffc3a2a6f80
Found by: call frame info
43 olive-editor!_start + 0x29
rsp = 0x00007ffc3a2a6f70 rip = 0x000000000048c425
Found by: stack scanning
44 0x7ffc3a2a6f78
rsp = 0x00007ffc3a2a6f78 rip = 0x00007ffc3a2a6f78
Found by: call frame info

**_#Unfortunately, I couldn't paste the entire code because it's too big_**

</code>

**Comment by itsmattkc** [comment]
I'm a little confused by your steps to reproduce. Can you record a video of this happening?

**Comment by porrarafaelmano** [comment]
https://user-images.githubusercontent.com/110862268/184994865-f581b95c-6c30-4b77-8322-409de8fd2b37.mp4
