### ISSUE TITLE
[CRASH] Clicking the video/audio each time fast can cause a crash by chances.

### ISSUE THREAD

**Issue by EditaNEmilis** [olive-editor/olive#2015]
**Commit Hash** 
b169ad92

**Platform** 
Windows 10

**Summary**
I was going to make a little joke intro, using a video I have downloaded. By making the video audio to 8 KBPS (low and crisp audio) and pressing to hear it. All good.
Then I import the video to Olive and selecting the video and then, crashed..

Probably because I have clicked it too fast or not..

<details><summary><strong>Crash Report</strong></summary><pre><code>

Comment is too long due to GitHub characters limit. Had to use it as .txt
[OliveErrorReport2.txt](https://github.com/olive-editor/olive/files/9377822/OliveErrorReport2.txt)

</code></pre></details>

**Additional Information**
Little bit of note, this video I have _downloaded_.
https://youtu.be/1CKxtZYgzfc

**Comment by itsmattkc** [comment]
Can you show a video of this happening or provide consistent steps to reproduce?

**Comment by EditaNEmilis** [comment]
Well I do have the crash proof with this video, and oh. Downsampling the audio was Audacity by exporting and making it 8 Kbps.
https://user-images.githubusercontent.com/107065286/185760797-8ace9648-4a13-46e5-9cc4-c3b39e5cdef7.mp4

**Comment by itsmattkc** [comment]
Should be fixed in b361ba8c51dc79640e77358951b7d4e8f55807f1
