### ISSUE TITLE
[EDIT] Problems dragging an intermediate clip.

### ISSUE THREAD

**Issue by JoseOlin** [olive-editor/olive#2017]
**Commit Hash** 
10bc448c

**Platform** 
Linux Mint 20.3 Cinnamon. Linux Core 5.15.0

**Summary**
It is not possible to accurately drag an intermediate clip.

If I try to drag the last clip on the timeline it does so without any problems, it only happens with intermediate clips.

Occurs regardless of whether Snapping is on or off.

**Additional Information / Output**

I add gif of the behavior.

![toggle-snapping-issue-olive](https://user-images.githubusercontent.com/6277774/185774347-9b4e9c71-0e24-415d-8bed-dac98eaf0fb4.gif)

Is this a configurable behaviour or an issue?

Thanks in advance.

**Comment by itsmattkc** [comment]
Your Olive release is over 3 weeks old. Please update it.

**Comment by JoseOlin** [comment]
Corrected in b361ba8c. 

Thanks!
