### ISSUE TITLE
[Feature Request] More keyframe interpolation options

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#202]
Blender's VSE is the only open-source NLE with keyframe interpolation outside of the usual **_smooth_** and **_linear_**. However, Blender's VSE does not have hardware-accelerated GLSL effects 😉

Here's a screenshot of available keyframe interpolations in the Blender 2.8 beta:
![image](https://user-images.githubusercontent.com/40442071/50430944-43572280-0884-11e9-8681-73f3d3dac8d5.png)

[openFrameworks has the **ofxAnimatable** C++ add-on dedicated to this](https://github.com/armadillu/ofxAnimatable)
![16217582178_4e5789e8cb_o 2](https://user-images.githubusercontent.com/40442071/50430370-af378c00-0880-11e9-9b5f-38dbf5f286ba.png)

Natron also allows keyframe easing with their [Shadertoy GLSL plugins](https://github.com/NatronGitHub/natron-plugins/tree/master/Shadertoy). Not asking for a robust animation system, just more options for smoother transitions and effects.

**Comment by alcomposer** [comment]
There are two parts to this:

* Having either different easing modes or cubic-bezier interpolation controls

* Having a GUI to control the easing. Currently the editor panel incorporates a dope sheet style editor. To allow more control a graph editor would be ideal.

**Comment by itsmattkc** [comment]
My intention is to have cubic bezier interpolation, I was researching it for one of the effects and I think it'd be fairly easy to implement. The graph editor UI would probably take the longest.

But yes, this is absolutely on the radar, thanks for reminding me :)

**Comment by itsmattkc** [comment]
Added to master in 69a33c756cb5bdc5683dc899bb40137cff042e29
