### ISSUE TITLE
[CRASH] Olive freezes irrecoverably now and then when working in the timeline

### ISSUE THREAD

**Issue by JoseOlin** [olive-editor/olive#2022]
**Commit Hash** b361ba8c 

**Platform** 
Linux Mint 20.3 Cinnamon
Intel Core i7
Graphics: Intel Corporation UHD Graphics 620 (Whiskey Lake)

**Summary**
Olive freezes now and then when working in the timeline. May be is related specifically to Text edit function.

Program doesn't close and show the crash dialog, just freezes and doesn't allow further editing on the timeline, or any other interaction with the program other than closing. 

When closing the OS it indicates that the program is not responding and offers to force the closing. 

**Additional Information**

These are the last lines on the terminal.
```
[DEBUG] Selected node: olive::TextGeneratorV3(0x6f0df90) ((null):0)
[DEBUG] olive::ProjectSaveTask(0x60adaa0) took 7 ((null):0)
[DEBUG] Selected node: olive::TextGeneratorV3(0x6f0df90) ((null):0)
```

We're running the AppImage from terminal in the hope to get some information about the reason of the freeze but the output looks just normal. Any way to enable a more verbose mode in the AppImage?

**Comment by AGI-THB** [comment]
Read This:

[Debugging with GDB](https://github.com/olive-editor/olive/wiki/Debugging-Olive)

**Comment by JoseOlin** [comment]
That was fast. Thanks!

Running in debug mode...

I let you know the output the next time that freeze happens.

**Comment by itsmattkc** [comment]
Yeah I'm afraid there's not much we can do with this information. If you can provide steps to reproduce, that would be helpful. Using GDB to generate a backtrace during the freeze should also help a lot.

Closing until more information is provided.
