### ISSUE TITLE
[CRASH] 

### ISSUE THREAD

**Issue by BipedalDonkey** [olive-editor/olive#2024]
1e3cf533 

Windows10 

Crash occurred when searching for specific video name in a folder

**Steps to Reproduce**

1. I created a folder for videos in the media area
2.  Possibly a factor, possibly not, but for this particular project I have a lot of videos in this particular folder
3. Searched for a specific title in the "Search media, markers, etc." bit at the top.
4. Instant crash

<details><summary><strong>Crash Report</strong></summary><pre><code>

 idk where I would find that sorry

</code></pre></details>

**Additional Information**

**Comment by AGI-THB** [comment]
Your version of Olive is over 3 years old.

**Comment by itsmattkc** [comment]
0.1 is no longer supported.
