### ISSUE TITLE
[EDIT] Volume keyframes on splited audio

### ISSUE THREAD

**Issue by Papou008** [olive-editor/olive#2031]
**Commit Hash** 
cce44e40

**Platform** 
Windows 7

**Summary**
When audio is splited and don't start from the begining, volume keyframes are shifted.

**How to reproduce**
- Add an audio media in library
- Add this audio in timeline
- Split this audio in 2 blocks (Ctrl + K)
- Add volume Key on the second block
=> There is an offset between volume keyframes positions au the hearing audio

**Example**
- Audio is splited at 4s (and we edit the second part of this sound)
- A first keyframe "-99db" is added at 6s in the global sequence (locally at 2s in the block)
- A second keyframe "0db" is added at 8s in the global sequence (locally at 4s in the block)
=> We can hear the volume growing from 10s (= 4 + 6) to 12s (= 4 + 8)
=> We should hear the volume growing from 6s to 8s

**Comment by elsandosgrande** [comment]
Which commit hash are you using and on which platform? The commit hash can be found both in the titlebar and in the About window.

**Comment by Papou008** [comment]
Sorry, I'm on Windows with the cce44e40 portable version
