### ISSUE TITLE
the CODE execution canot proceed because MSCVCP140.dll was not found

### ISSUE THREAD

**Issue by editorman64ca** [olive-editor/olive#2033]
**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**

**Comment by itsmattkc** [comment]
If you downloaded the portable build, run `vc_redist.x64.exe`.

If you download the installer, this should automatically happen, but obviously can't for the portable release.

**Comment by editorman64ca** [comment]
sorry, somewhat vague, please ellaborate, { in red below } also i clicked alot of links on your site an am not shure wich link you mension would be can you send me download link in the past i just downloaded the win10 - 64 bit it would install with the new an impresived win10 its not as easy as it was b4

**Comment by editorman64ca** [comment]
[ https://github.com/olive-editor/olive | https://github.com/olive-editor/olive ]

**Comment by Simran-B** [comment]
Install the Visual C++ v16 runtime. If you can't find it in the download, try this link:
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by editorman64ca** [comment]
ty for sending this but i used the old posted link to get this same software i noticed there was alot of postings that asked: itsmattkc for help to get this software could to do something so all the people who need this can get it? the utsmattkc is a stubborn sort an refuses to be helpful "that really stinks!!" jeff ***@***.*** "hey" if version .02 comes out please send me a link,... ty 

hello, to whom this may concern: i recently reinstalled: Olive-7a1e1cdb-windows-x86_64 when i clicked the desktop icon to open olive i got the following error message: { the CODE execution canot proceed because MSCVCP140.dll was not found Issue #2033} then i had to look a long time to find: ITSMATTKC on github to tell him about this olive install prob he sent this back to me: { if you downloaded the portable build, run vc_redist.x64.exe. If you download the installer, this should automatically happen, but obviously can't for the portable release.} after 5 days no more word from him so sept 23 today i began more looking at posted stuff on github an saw he deemed this prob ended. looking all over the gitub i happened to come across a posting i clicked the link he posted: Simran-B commented on Nov 10, 2020 Do not remove the issue template and fill it out. https://aka.ms/vs/16/release/vc_redist.x64.exe should solve it. 
then downloaded an got the needed file my {lastest version of win10} comuter needed to install an sucessfully run the win7-10 unsupported version of: Olive-1e3cf53-windows-x86_64 the interface looks as it should but if you have the .02 version please let me know ill use it instead
