### ISSUE TITLE
[EXPORT] background process does not lock exported sequence

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#2037]
**Commit Hash**  
658fe9da

**Platform**
Linux

**Summary** 
If we export with background task, then continue to edit the exporting sequence, the exporting process will change. 

For example:
* Add red colour matte to empty project
* Export project in background
* Change colour of matte to blue
* Exported video will start red, then change to blue depending on how far along the export process it is when the change occurs in the project file.

**Discussion**
While changing a project after export has started is not the best practice, this is still an issue if for example a user wanted to export a project at a current version, then continue working on that project, or there are nested sequences that are being updated while exporting.

Olive should make an internal copy of the current sequence (including children) that is being exported. And only reference that while exporting. 

Possibly when background export is finished, and Olive detects there have been changes to the sequence, Olive should ask if the users wants to save that older version as well. (<Sequence>_backup)??

Alternatively Olive could lock all sequences that are exporting, (including nested sequences) however that feels wrong as the whole point of background export is to be able to continue work in Olive. However this solution would still enable a user to continue work on other non-linked sequences, and add more sequences to the render queue. So that may also be very useful, and reduce complexity of multiple exported versions building up.

**Comment by itsmattkc** [comment]
Hmm it's absolutely _supposed_ to make an internal copy for exactly the reason you specify. Something may have regressed since this was implemented, or the initial implementation may be flawed.
