### ISSUE TITLE
[EXPORT] 

### ISSUE THREAD

**Issue by CheeseWheelLord** [olive-editor/olive#2040]
Issue with exporting

platform - Windows 10

Hello, Im having an issue with exporting a video, when I press "export" it just brings me back to the main olive editor screen. When i look for the file it just shows a video file that I cant open any help is appreciated greatly.

No additional info, but im happy to give anything specific if you need

**Comment by AGI-THB** [comment]
Fill out the issue template.

**Comment by CheeseWheelLord** [comment]
Is that better? Sorry ive not use Github before and I cant find any fixes for my issue online anywhere

**Comment by AGI-THB** [comment]
Software Version?
Hardware?

Steps to reproduce?

**Comment by CheeseWheelLord** [comment]
Alpha 1e3cf533 Version
I dont have steps to reproduce All i did was export how I usually do. Ive used the editor for about two years now and ive never had this issue. 
Hardware is - 48 gb ram, 1650 ti graphics card. i7 8th gen cpu

**Comment by AGI-THB** [comment]
That version is old and unsupported.

Download version 0.2 on the homepage.

**Comment by CheeseWheelLord** [comment]
Can I move my video that ive edited over from this version to the new one?

**Comment by AGI-THB** [comment]
I don't know.

I don't think so.

**Comment by CheeseWheelLord** [comment]
ive spent a really long time on this and I cant lose it. Damn this is sad

**Comment by CheeseWheelLord** [comment]
Thank you for the help although im not sure why all of a sudden it doesnt want to export videos

**Comment by CheeseWheelLord** [comment]
Oh I just checked it works fine on other projects just not this one

**Comment by CheeseWheelLord** [comment]
![image](https://user-images.githubusercontent.com/114359218/192160710-480fe5cc-10af-4fef-ac7b-fa72f84c3487.png)
This is my settings for the export

**Comment by CheeseWheelLord** [comment]
OH YES its working now for some reason I just changed the range to "entire sequence" Sorry for wasting your time. Thank you for the very fast responce. Have a nice day again sorry for wasting your time
