### ISSUE TITLE
[NODES] [PLAYBACK] Very Poor Playback Performance while Clip with keyframes are selected.

### ISSUE THREAD

**Issue by Logos-Coder** [olive-editor/olive#2042]
**Commit Hash**
7a1e1cdb through 9d54e24d

**Platform**
Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-9-amd64
AppImages from the Olive website.

**Summary**

While I have a clip selected in the timeline with keyframes the whole interface slows to a crawl. In this state playback is impossible to use.
If you do not have any clip selected everything appears to be normal, and runs smoothly. So from my point of view it is a bug within the Parameter Editor.

**I do not believe** you will see this on a new project, but with the editing setup I am employing.

**Additional Information / Output**

This project that I am working in which is having these performance issues employs the tactic of having nested sequences. In a sense, I am using a layered approach toward how I am editing this video, which is relevant to this bug I believe.

Here is How the project is currently set up:

### Seq 0:

Contains main video/audio clip with two color grading nodes applied to it. Which the one first in the node tree has several keyframes.

### Seq 1:

Contains `Seq 0` that has been cut up. Along with one, short, new audio clip. (AKA This is the rough cut of the video)

### Seq 2:

This is the Final layer which Contains `Seq 1`. This is where I am encountering these problems. I have not had the same problem on either of the other two Sequences, though I did select the main clip from `Seq 0` and while it was still selected, switched to `Seq 1`, and while the selected clip was still in the Parameter Editor, and I ran into the same performance issues I am seeing on `Seq 2`.

**Seq 2** also has a few images, other video clips, as well as, a clip that contains a few text nodes, and a shape node.

**Any clip that I select in `Seq 2` that contains keyframes reduces the framerate of the interface to an unusable sate.**

**Comment by Logos-Coder** [comment]
I am not able to provide the project file at this time.

**Comment by itsmattkc** [comment]
I haven't been able to recreate with the instructions you provided. Would you be open to allowing me remote access to your system where I can properly debug the problem?

**Comment by Logos-Coder** [comment]
Sure, I would be willing to do that. what would be the best way?

**Comment by itsmattkc** [comment]
I'll send you a message on Discord
