### ISSUE TITLE
[CRASH] Ripple deleting the cross dissolve will crash.

### ISSUE THREAD

**Issue by EditaNEmilis** [olive-editor/olive#2043]
**Commit Hash** 
af6cb35c

**Platform** 
Windows 10

**Summary**
I was editing my video, decide to change the still frame video with the thumbnail I have made, decide to ripple delete the still frame and cross dissolve.
But when I ripple deleted.. It crashed.

**Steps to Reproduce**

1. Make a empty or any still frame video.
2. Add cross dissolve at left, right or middle.
3. Ripple delete it.

<details><summary><strong>Crash Report</strong></summary><pre><code>

Too big due to characters limit. Link there for the full crash report.
https://we.tl/t-HS03LgMNh8

</code></pre></details>

**Additional Information**
Video proof of this crash...

https://user-images.githubusercontent.com/107065286/192822258-167302ef-9902-4245-b1ba-94a0090cc263.mp4

**Comment by EditaNEmilis** [comment]
Oh right. Thanks.

**Comment by EditaNEmilis** [comment]
Oh wait, nevermind.
It still crash when I updated it to recent build.

**Comment by AGI-THB** [comment]
Sorry, we have to wait for a future update then.

#1842
