### ISSUE TITLE
[CRASH] Razor cutting the audio will crash by chances.

### ISSUE THREAD

**Issue by EditaNEmilis** [olive-editor/olive#2048]
**Commit Hash** 
fe159bdd

**Platform** 
Windows 10

**Summary**
Was editing a video, I was going to razor cut the audio for the video ending.
But when I razor cutted it, it crashed. Getting it a "EXCEPTION_INT_DIVID_BY_ZERO" crash reason...

<details><summary><strong>Crash Report</strong></summary><pre><code>

Too big due to Github characters limit. Here is the download text link.
[OliveErrorReport.txt](https://github.com/olive-editor/olive/files/9691260/OliveErrorReport.txt)

</code></pre></details>

**Comment by itsmattkc** [comment]
I'm pretty sure this is fixed in the `multicam` branch that will be merged today.

**Comment by itsmattkc** [comment]
`multicam` has been merged which should address this. Let me know if it occurs again in the latest commit.
