### ISSUE TITLE
[PLAYBACK] Stops for less of a second every second and a half

### ISSUE THREAD

**Issue by CloneHeroUruguay** [olive-editor/olive#2053]
**Commit Hash** I̵ ̵d̵i̵d̵n̵'̵t̵ ̵u̵n̵d̵e̵r̵s̵t̵a̵n̵d̵ ̵w̵h̵a̵t̵ ̵t̵h̵i̵s̵ ̵i̵s̵ ̵f̵o̵r̵

Olive 0.2.0-b28495c7

**Platform**

Edition	Windows 10 Home
Version	21H2
OS build	19044.2006

Processor	AMD Ryzen 3 PRO 2200G with Radeon Vega Graphics   3.50 GHz
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor

**Summary**

I used 0.1 with no problems on other machine, but in this one I installed 0.2 and run into this problem the first time I used it.

1. I opened a .webm vp8 file.
2. I let the program automatically sets the parameters
3. I run into this issue while using the "sequence viewer"

**Additional Information / Output**

The video is too big to upload here. I can upload it on google drive if it's necessary.

**Comment by elsandosgrande** [comment]
Could you elaborate? What parameters are automatically set?

---

The commit hash is the string of seemingly random letters and numbers that you can see both in the titlebar and in the About window.

**Comment by CloneHeroUruguay** [comment]
> What parameters are automatically set?

I don't know. I just move the file from the project box to the timeline and then a window titled "No Active Sequence" appears, and I have three options there:

1. Automatically detect parameters from footage
2. Set parameters manually
3. Cancel

I choose the first one. After that I try to play the video on the sequence viewer and happens what I already mentioned.

Where can I check those parameters to share them here?

**Comment by itsmattkc** [comment]
According to your commit hash, your version is from two weeks ago. Can you try to reproduce in the latest commit?

If it still occurs, please send this footage.

**Comment by CloneHeroUruguay** [comment]
Yup, tried latest version and same result.

I guess by "this footage" you mean the video I'm having problems with: https://drive.google.com/file/d/1kuVHUBRbSj9JA-rkn7WdTP8XLYHKXIP_/view?usp=sharing

**Comment by itsmattkc** [comment]
Video plays fine on my end.

Try to interpret your original message, it sounds like the backend renderer might be failing to keep up. Can you post a screen recording of the issue to confirm?

**Comment by CloneHeroUruguay** [comment]
https://user-images.githubusercontent.com/110006088/195192768-03d552b5-12df-46af-a029-0e2005b71719.mp4

There, I think.

**Comment by itsmattkc** [comment]
Please try the latest commit

**Comment by itsmattkc** [comment]
Closing until further information is provided

**Comment by CloneHeroUruguay** [comment]
Latest version solved it. Thanks!
