### ISSUE TITLE
[EDIT] Crop Error

### ISSUE THREAD

**Issue by MrWolfeXD** [olive-editor/olive#2057]
**Commit Hash** 

**Windows 11** 

**Normally when a video is cropped and moved around you can see the part of the video that was not cropped out. However in Olive Video Editor 0.2 when I crop a video and move it, it shows the area that was cropped. For instance, I cropped a video to just show a person and when I try to move the video to the left, the person moves to the left and goes out of view and only the wall they were in front of is in view. 0.2 crops an area, not the video. Please fix this problem.**

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Not true. If you move a crop, it moves the crop. This is intended behavior. If you want to move the cropped result, put a transform node after it.
