### ISSUE TITLE
[UI] [AUDIO] Audio monitor no longer works during playback

### ISSUE THREAD

**Issue by psemiletov** [olive-editor/olive#2059]
**Commit Hash** 
1765b8ab

**Platform** 
ArchLinux

**Summary**
The Audio Monitor sometimes does not show the audio meter. If it works, the panning settings does not affect on the meter, i.e. if I pan (the stereo signal) to the left, I can hear this panning, bur the audio meter shows the non-panned levels, as the source signal.

**Additional Information / Output**

**Comment by Logos-Coder** [comment]
The audio meter in olive follows the baked waveform given to an audio track. I do think this is an issue, and the audio meter should dynamically follow the audio being produced on the output. Personally I don't think this is a game breaker, but it would be nice to see this get changed.

**Comment by psemiletov** [comment]
As far I can understand, the Audio Meter (as the "master bus") must show the mixed signals from all audio tracks.

**Comment by itsmattkc** [comment]
Merging into #2199
