### ISSUE TITLE
[UI] Unable to zoom in and out in top area of timeline.

### ISSUE THREAD

**Issue by Logos-Coder** [olive-editor/olive#2060]
**Commit Hash** 

Olive 0.2.0-cae71f011d5339bff33e146516985a4cfa06ab77

**Platform** 

EndeavourOS (Arch Linux with easy installer)
5.19.13-arch1-1
Ryzen 2600
AMD RX580

**Summary**
I should be able to use ctrl+scrollwheel on this area of the timeline and be able to zoom in

![Olive-can't-zoom-area](https://user-images.githubusercontent.com/47828239/195015034-3299373d-ea9e-4712-9cf8-a3f3e2f58630.jpg)

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
I can confirm this happens and I agree it would be good to be able to scroll there
