### ISSUE TITLE
[UI] There is no good way to select multiple markers at once.

### ISSUE THREAD

**Issue by Logos-Coder** [olive-editor/olive#2061]
**Commit Hash** 

Olive 0.2.0-cae71f011d5339bff33e146516985a4cfa06ab77

**Platform** 

EndeavourOS (Arch Linux with easy installer)
5.19.13-arch1-1
Ryzen 2600
AMD RX580

**Summary**

Anywhere where you are able to select markers, (Timeline, parameter editor, etc.) there is no good way to select multiple markers at once.

**Additional Information / Output**

You should be able to drag select markers on timeline, and/or click one marker and shift click on a later one to select a range of markers. Then ctrl+click should do what shift clicking on markers currently do. What I have suggested here is basically how every other program out there handles selecting multiple items in a list.

**Comment by itsmattkc** [comment]
I don't see this as a particularly winnable scenario. You can't drag click in the time ruler because that will already drag the playhead, and as far as shift vs click, that's pretty subjective per platform and Olive is pretty consistent about it internally. Changing it here would make it inconsistent with the rest of the program.

**Comment by Logos-Coder** [comment]
I'll have to think about how to do this in a good way. I'll get back to you.

**Comment by Logos-Coder** [comment]
> Olive is pretty consistent about it internally. Changing it here would make it inconsistent with the rest of the program.

This is a fair point. I for some reason didn't notice this was the behavior for clips. Probably because I mainly select them by dragging.

**Comment by unfa** [comment]
Would it make sense to use the same tools as for manipulating strips?
There is a range selection tool, maybe that could be used for click&drag selecting markers too?

**Comment by Simran-B** [comment]
What's the actual use case here? In what situations do you want to move multiple markers at once?
Is the purpose e.g. to insert or delete something from the timeline and then adjust all markers after it accordingly, to maintain the relative position?

**Comment by ThomasWilshaw** [comment]
I'm possibly missunderstanding you here but you can move, edit and delete multiple markers at a time, just shift select them.

Also if you add markers in the footage viewer, they are tied to the clip and will apear in the timeline.

**Comment by Logos-Coder** [comment]
> I'm possibly missunderstanding you here but you can move, edit and delete multiple markers at a time, just shift select them.

I am not sure where you got that I could do these things, but no I can't. that is why I opened this issue. You can manipulate multiple at one time, **but I am unable to select them all in one single action.**

Shift selecting does not work, because Olive does not use shift select to select a range of items. Shift select in Olive is what most other programs use as ctrl select. Drag selecting is how Olive selects more then one item in one action, which is currently impossible to do with markers.

> Also if you add markers in the footage viewer, they are tied to the clip and will apear in the timeline.

I didn't know this, that is good to know! But you still can't select many markers at once, and personally this method feels a little clunky at first glance. Maybe if I used it more I would think otherwise.

You can do the same thing with sequences, if you create two sequences in your project, you can drag one of the sequences into the other. Then if you open up that second sequence and add markers to it, if you return to the first sequence that contains the second sequence as a clip, Olive shows you the markers for the second sequence inside the clip of that sequence, which is placed in the first sequence.

**Comment by Logos-Coder** [comment]
you could also use a modifier key like ctrl to allow you to make a selection box in that top area on the timeline.

**Comment by itsmattkc** [comment]
Is the main issue here that the markers don't move along with the timeline? I've noticed that in other editors the markers will shift with certain operations (e.g. ripple deletes/inserts). That'd probably be a good idea to implement, would that make this issue largely solved?
