### ISSUE TITLE
[UI] Add ability to zoom X and Y axis's independently from each other in the curve editor.

### ISSUE THREAD

**Issue by Logos-Coder** [olive-editor/olive#2062]
**Commit Hash** 

Olive 0.2.0-cae71f011d5339bff33e146516985a4cfa06ab77

**Platform** 

EndeavourOS (Arch Linux with easy installer)
5.19.13-arch1-1
Ryzen 2600
AMD RX580

**Summary**

Adding the ability to zoom X and Y axis's independently from each other in the curve editor, would be a vary useful feature to have. It would allow you to zoom into a section of time without zooming all of your keyframes off screen.

**Additional Information / Output**

I would look at Blender's implementation of this feature in their graph editor. They call it 2D Zoom. by default it is bond to ctrl+middleclick in the graph editor I believe.

**Comment by itsmattkc** [comment]
You can already do this by holding Ctrl+Shift while scrolling, and then using Alt to switch axes.

**Comment by Logos-Coder** [comment]
This is good to know Sorry for the issue spam. I was not aware the feature was added.

**Comment by Simran-B** [comment]
I suppose it should be made more discoverable that this is possible?

**Comment by itsmattkc** [comment]
I think that's probably one for documentation.
