### ISSUE TITLE
[UI] Parameter Editor Does Not Remeber Node Order and Size.

### ISSUE THREAD

**Issue by Logos-Coder** [olive-editor/olive#2063]
**Commit Hash** 

Olive 0.2.0-7791dde9543cf28249d126b99b0fba8b748bebcd

**Platform** 

5.19.13-arch1-1
Ryzen 2600
AMD RX580

**Summary**

This is the default order that olive puts my nodes in:

![olive-param1](https://user-images.githubusercontent.com/47828239/195157785-3a40f090-a18f-40fc-8c61-0e4dffd40e17.jpg)

This is the order I would like them in:

![olive-param2](https://user-images.githubusercontent.com/47828239/195157792-e69cae9b-a2e1-451c-983b-6043c92a3ad5.jpg)

Olive does not remember this order if I move off that clip. It also does not remember that I have shaded all of the nodes.

![olive-param3](https://user-images.githubusercontent.com/47828239/195161691-bba7887f-b325-4145-a1dd-6caad50b3e27.jpg)

these should be persistent across saves.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
I think this is unlikely to be implemented as you describe. The order is intended to correspond with the order of the nodes, and shifting them around is intended to (eventually) change the order of the nodes too.

**Comment by Logos-Coder** [comment]
@itsmattkc I see. That is understandable, but the one problem with that, is that node trees are not always linear. I am sure you know that though, so maybe you have a solution to that.

I do at least want to see the ability to have the node remember their shaded state.
