### ISSUE TITLE
[EXPORT] Olive consumes all system RAM and SWAP during export leading to OOM killing

### ISSUE THREAD

**Issue by daynashaw** [olive-editor/olive#2070]
ca8a257a

Fedora Silverblue 36

Hello. I am attempting to export my project, but Olive will consume my complete RAM and SWAP (42GB) in about 60 seconds leading to my system automatically OOM killing it.

I am working on a video with multiple source files. Each file is around 4gig and I have three of them in the project right now. In Olive I have maybe 95% of the content of these videos cut out. The original files have a collective runtime of 1h30m and my project currently runs for 2m. I'm not using any effects, transitions, or nodes (besides what are automatically provisioned). The only thing other than the source videos themselves are title frames and additional audio clips.

I have tried using the default export settings and my own custom settings. I have tried to export the video in half res (from 1440p to 720p), with different encoder settings, and with different container formats. Unfortunately Olive's RAM use presents the same way on my system regardless. 

**Additional Information / Output**
I'm not getting results back from GDB when Olive closes. I think it could be because it's my system OOM killing the process. Here's the closest thing to a GDB log that I know how to give you at the moment.

> (gdb) exec-file ./Olive-ca8a257a-Linux-x86_64.AppImage 
> (gdb) run
> Starting program: /var/home/shaw/appimage/Olive-ca8a257a-Linux-x86_64.AppImage 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> [Detaching after fork from child process 4401]
> process 4400 is executing new program: /usr/bin/env
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> process 4400 is executing new program: /usr/bin/bash
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> [Detaching after fork from child process 4407]
> [Detaching after fork from child process 4409]
> [INFO] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. ((null):0)
> [DEBUG] Extracting default OCIO config to "/var/home/shaw/.cache/olivevideoeditor.org/Olive/ocioconf" ((null):0)
> [INFO] Using Qt version: 5.15.2 ((null):0)
> ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
> ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
> ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
> ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
> ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
> ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
> ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
> ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
> ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
> ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
> ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
> ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
> ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
> [INFO] Setting output audio device to default ((null):0)
> [INFO] Setting input audio device to default ((null):0)
> [DEBUG] Using graphics driver: AMD ((null):0)
> [DEBUG] olive::ProjectLoadTask(0x7fffd0009520) took 50 ((null):0)
> [mp3 @ 0x7fff54007200] Estimating duration from bitrate, this may be inaccurate
> x265 [info]: HEVC encoder version 3.5
> x265 [info]: build info [Linux][GCC 9.3.1][64 bit] 8bit
> x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
> x265 [info]: Main profile, Level-5 (Main tier)
> x265 [info]: Thread pool created using 12 threads
> x265 [info]: Slices                              : 1
> x265 [info]: frame threads / pool features       : 3 / wpp(23 rows)
> x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
> x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
> x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 3
> x265 [info]: Keyframe min / max / scenecut / bias  : 25 / 250 / 40 / 5.00 
> x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
> x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
> x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
> x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 32 / 1
> x265 [info]: Rate Control / qCompress            : CRF-23.0 / 0.60
> x265 [info]: tools: rd=3 psy-rd=2.00 early-skip rskip mode=1 signhide tmvp
> x265 [info]: tools: b-intra strong-intra-smoothing lslices=8 deblock sao
> Output #0, mp4, to '/var/home/shaw/Videos/Olive_Project_Files/Death from Above.tmp1.mp4':
>   Stream #0:0: Video: hevc, yuv420p(tv, bt709), 2560x1440 [SAR 1:1 DAR 16:9], q=2-31, 60 fps
>   Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 320 kb/s
> /tmp/.mount_Olive-y9UQKM/AppRun: line 8:  4409 Killed                  "$APPDIR/usr/bin/olive-editor" "$@"
> [Detaching after fork from child process 4714]
> [Detaching after fork from child process 4715]
> [Inferior 1 (process 4400) exited normally]
> (gdb) bt
> No stack.
> (gdb) exit

**Comment by daynashaw** [comment]
I will create a project with a smaller source file and attempt to export that.

**Comment by daynashaw** [comment]
When working with a 785MB source file and making no changes I was able to successfully export using default settings. I noticed that Olive was consuming 2.4GB of RAM during the process. If I do a little math, and if Olive indeed has the same RAM behavior on my other project, does that imply that I would need 36GB of RAM to process 12GB of files? Does Olive fully load all assets to RAM in a decompressed state during the export process?

I will continue testing larger total source sizes until it fails and then I will report back. Thank you for working on this project.

**Comment by NorbiPeti** [comment]
Does this happen if you export the video without audio? I experienced the same and #2072 seemed to be about the same issue.

**Comment by cy11100** [comment]
I'm getting the same symptoms on Win10, agree with @NorbiPeti that #2072 is probably the same bug. It's not fixed in the latest commit.

**Comment by daynashaw** [comment]
This error does not occur when I export without audio.

**Comment by itsmattkc** [comment]
None of my test systems exhibit this issue (or any high memory usage at all), which makes it virtually impossible for me to diagnose. Is someone here willing to let me remote into their system so I can debug it firsthand?

**Comment by cy11100** [comment]
> None of my test systems exhibit this issue (or any high memory usage at all), which makes it virtually impossible for me to diagnose. Is someone here willing to let me remote into their system so I can debug it firsthand?

This minimal reproducible case works for my case on my Win10 setup: 

1. Download a random large video. I used yt-dlp to grab a random 30 min one, https://www.youtube.com/watch?v=_sQ_BlnGBIE was used for the test.
2. Randomly cut the video in ~50 locations. I made these cuts in the first minute. 
3. Crash with out of memory.

**Comment by daynashaw** [comment]
You may remote into my system for testing.
