### ISSUE TITLE
[CRASH] Often crashes when video editing.

### ISSUE THREAD

**Issue by EditaNEmilis** [olive-editor/olive#2071]
**Commit Hash** 
ca8a257

**Platform** 
Windows 10

**Summary**
Sometimes or often, when I tried editing video. Like a long one, they might be a small chance of crashing the program, because I do have a low end PC.
Because I do keep getting **EXCEPTION_ACCESS_VIOLATION_READ** or any crash reason...

<details><summary><strong>Crash Report</strong></summary><pre><code>

Too big due to GitHub characters limit.
WeTransfer link here.
https://we.tl/t-KGMcqY3J36

</code></pre></details>

**Comment by TheTechRobo** [comment]
[The crash report reuploaded on GitHub](https://github.com/olive-editor/olive/files/9833596/OliveErrorReport.txt)
