### ISSUE TITLE
Cache doesn't seem to be working and green cache bar is not appearing

### ISSUE THREAD

**Issue by kburchfiel** [olive-editor/olive#2073]
**Commit Hash** 
6ce80f44

**Platform** 
Windows 10

**Summary**
I just downloaded 0.2.0-6ce80f44 and am using it to view an older project (created using 2a80b858, which I believe came out last December). I was able to open the project successfully, but when I right click on a clip and select Cache --> Cache All, I don't see any indication that a cache is taking place (other than some CPU/disk usage). 

With 2a80b858, I would see a status bar at the bottom of the window showing what percentage of the cache task was complete, along with green/red bars on the timeline that showed what components of the project were cached. I'm not seeing any of that right now.

The project that I'm trying to cache is pretty large (44 minutes of 8K video), but these issues also occurred when attempting to cache a smaller component of the video.

Could the issue be that the project was originally created in an older version of Olive? I think the cache settings did work when I created a new project and imported some clips into it, but I'd love to get the cache to work with this older project also.

**Comment by itsmattkc** [comment]
If it works with newer projects, then it may indeed be the project's age. Would you be able to send the project file? (you shouldn't have to send the footage)

**Comment by kburchfiel** [comment]
Interestingly, when I opened up a new project and copied and pasted one of the clips from the old project into it, I was suddenly able to cache the video clips. (This might have just been coincidental, but caching is working now so I'm satisfied!)

One thing I'm finding, though, is that right clicking on a clip and selecting "Cache all" caches _only_ that clip. I can schedule multiple clip cache operations by selecting multiple clips and **then** pressing 'Cache all,' but it would be great to be able to right-click on one clip and then cache **all** the clips via the 'Cache all' operation. (I had previously had trouble getting Cache in/out to work, but I can try that again now that the cache feature is working.)

Thanks for all your work on Olive--it has been hugely helpful and does things (e.g. 8K video rendering) that my old proprietary video editor couldn't do.

**Comment by itsmattkc** [comment]
Yeah "all" in this scenario means the whole clip, as opposed to just a portion of it. There should be ways to affect all clips in the near future so stay tuned!

**Comment by kburchfiel** [comment]
That sounds great, thanks!
