### ISSUE TITLE
Strange error message on first start

### ISSUE THREAD

**Issue by JosephM101** [olive-editor/olive#2075]
**Commit Hash** 
3d90dc4e

**Platform** 
Windows 10

**Summary**
On first startup (I started Olive from the installer), I got this strange error message. I figured I should mention it, since I'm not sure if it's just a fluke, or a problem with a module/setup.

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/28277730/197560546-3b297df8-11cf-45ce-abea-6c62d610ecac.png)

**Comment by itsmattkc** [comment]
I believe this is probably just a fluke. From what I can tell it's an isolated incident and as long as it's not affecting further usage, I think it's nothing to worry about.

**Comment by Simran-B** [comment]
Possibly caused by ASCII text being interpreted as UTF16. 
https://devblogs.microsoft.com/oldnewthing/20140930-00/?p=43953

If it only occured once, then there was a memory corruption perhaps?

**Comment by mcDandy** [comment]
It allso happens to me whenever I install new version of olive.

**Comment by itsmattkc** [comment]
I could believe it's a Unicode issue (which would explain why it doesn't occur on my English setups), however it's probably an issue with NSIS or more specifically the "run as user" plugin we're using rather than Olive itself, considering it only occurs when running Olive from the installer.
