### ISSUE TITLE
[EDIT] Olive/FFmpeg fails to correctly detect MXF duration

### ISSUE THREAD

**Issue by ThomasWilshaw** [olive-editor/olive#2076]
**Commit Hash** 
[3d90dc4](https://github.com/olive-editor/olive/commit/3d90dc4ecd61ee67d3e52024695b99c0898256cd)

**Platform** 
Windows 10

**Summary**
Olive fails to properly detect the duration of Arri Alexa 35 sample clips. For example [this](https://webgate.io/directlink/bdb5241a98e21e39/folder/680418) clip is 10 seconds and 13 frames long but Olive interprets it as being about 34 minutes. 

**Additional Information / Output**
As far as I can tell this is actually a problem with ffmpeg incorrectly decoding the file but I'm wondering if we can find some way to confirm the duration of a clip. The fall back method that is already in the code does produce the correct results but is not used in this case as Olive thinks it has correctly decoded the file. Always calling the fallback method would be bad as it can be very slow on long clips so it would be good to find some way of only callin this when needed. 

Iterestingly MediaInfo reports the duration correctly so it is possible.

**Comment by itsmattkc** [comment]
I have some awareness of this, and AFAIK it only affects MXF files so I will change the title to reflect that.

Secondly as you mention this is technically an FFmpeg issue that we're inheriting. I can see two potential solutions:

- We could use the fallback for MXF files all of the time. This is easy but slightly hacky, and I don't know if this affects _all_ MXF files or only some of them.
- I've seen FFmpeg print a console message saying something like "estimated duration based on bit rate may be inaccurate" with these files. I'm assuming that's relevant here. If we could programmatically detect when such an "estimation" has occurred, we could fallback to manual length detection then. This would be a better solution, but I don't know whether/how FFmpeg provides that information.

**Comment by ThomasWilshaw** [comment]
Yes I was also getting those FFmpeg errors in the console although it only seemed to be for the audio streams. We might be able to use (this)[https://ffmpeg.org/doxygen/2.8/structAVFormatContext.html#a95035552afae17c1b7cd701ad72e67b5] to get the estimation method

**Comment by ThomasWilshaw** [comment]
The fix I've added in the linked PR seems to work fine for my test MXF files and doesn't effect any other common inputs I tried. It would be nice ot add some kind of visual feedback for the user if a file is being loaded by the slow method so they don't think it has crashed but I couldn't see a simple way
