### ISSUE TITLE
[EXPORT] olive is taking too long to export video,and I want to use GPU encoder when export

### ISSUE THREAD

**Issue by xiaoranyinpin** [olive-editor/olive#2079]
**Commit Hash** 

I've been using olive for video production for a while now, and it always takes longer to export video than other apps. I checked my Explorer usage and found that it wasn't fully occupied in either CPU or GPU usage, with a lot of free space. In addition, in windows, can GPU hardware coding be used for export?

Like NVIDIA's NVDEC, and CUDA acceleration,

AMF hardware acceleration of AMD home, may I ask if you can add these codes to use in Windows system when exporting?

 

**Platform**  Windows 10 64 Bit Intel 8400 B360-N

**Comment by AGI-THB** [comment]
#26

**Comment by itsmattkc** [comment]
Encoding will significantly improve if you use "Target Bit Rate" over "Constant Rate Factor", however the latter will always provide the best quality for the file size, which is Olive's primary goal.
