### ISSUE TITLE
compiling latest build on ubuntu

### ISSUE THREAD

**Issue by dacorsa** [olive-editor/olive#2081]
Before the latest mod at the code, compiling was OK, but now not, do you will fix it?

**Commit Hash** 
During compiling i see the red error:

/app/olive/app/dialog/task/task.cpp:59:46: error: no matching function for call to ‘run(bool (olive::Task::*)(), olive::Task*&)’
   59 |     task_watcher->setFuture(QtConcurrent::run(&Task::Start, task_));
      |                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~

**Platform** 
ubuntu 22.10

**Summary**

**Additional Information / Output**
[ 30%] Building CXX object app/CMakeFiles/libolive-editor.dir/node/distort/crop/cropdistortnode.cpp.o
cd /app/olive/build/app && /usr/bin/c++ -DPA_HAS_JACK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -I/app/olive/build/app -I/app/olive/app -I/app/olive/build/app/libolive-editor_autogen/include -I/app/olive/ext -isystem /usr/include/OpenEXR -isystem /usr/include/Imath -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -O2 -g -DNDEBUG -Wuninitialized -pedantic-errors -Wall -Wextra -Wno-unused-parameter -Wshadow -fPIC -std=c++17 -MD -MT app/CMakeFiles/libolive-editor.dir/node/distort/crop/cropdistortnode.cpp.o -MF CMakeFiles/libolive-editor.dir/node/distort/crop/cropdistortnode.cpp.o.d -o CMakeFiles/libolive-editor.dir/node/distort/crop/cropdistortnode.cpp.o -c /app/olive/app/node/distort/crop/cropdistortnode.cpp
[ 30%] Building CXX object app/CMakeFiles/libolive-editor.dir/node/distort/flip/flipdistortnode.cpp.o
cd /app/olive/build/app && /usr/bin/c++ -DPA_HAS_JACK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -I/app/olive/build/app -I/app/olive/app -I/app/olive/build/app/libolive-editor_autogen/include -I/app/olive/ext -isystem /usr/include/OpenEXR -isystem /usr/include/Imath -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/x86_64-linux-gnu/qt5/QtDBus -O2 -g -DNDEBUG -Wuninitialized -pedantic-errors -Wall -Wextra -Wno-unused-parameter -Wshadow -fPIC -std=c++17 -MD -MT app/CMakeFiles/libolive-editor.dir/node/distort/flip/flipdistortnode.cpp.o -MF CMakeFiles/libolive-editor.dir/node/distort/flip/flipdistortnode.cpp.o.d -o CMakeFiles/libolive-editor.dir/node/distort/flip/flipdistortnode.cpp.o -c /app/olive/app/node/distort/flip/flipdistortnode.cpp
/app/olive/app/dialog/task/task.cpp: In member function ‘virtual void olive::TaskDialog::showEvent(QShowEvent*)’:
/app/olive/app/dialog/task/task.cpp:59:46: error: no matching function for call to ‘run(bool (olive::Task::*)(), olive::Task*&)’
   59 |     task_watcher->setFuture(QtConcurrent::run(&Task::Start, task_));
      |                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtConcurrent/QtConcurrent:16,
                 from /app/olive/app/dialog/task/task.cpp:23:
/usr/include/x86_64-linux-gnu/qt5/QtConcurrent/qtconcurrentrun.h:72:12: note: candidate: ‘template<class T> QFuture<T> QtConcurrent::run(T (*)())’
   72 | QFuture<T> run(T (*functionPointer)())
      |            ^~~
/usr/include/x86_64-linux-gnu/qt5/QtConcurrent/qtconcurrentrun.h:72:12: note:   template argument deduction/substitution failed:
/app/olive/app/dialog/task/task.cpp:59:46: note:   mismatched types ‘T (*)()’ and ‘bool (olive::Task::*)()’
   59 |     task_watcher->setFuture(QtConcurrent::run(&Task::Start, task_));
      |                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtConcurrent/qtconcurrentrun.h:77:12: note: candidate: ‘template<class T, class Param1, class Arg1> QFuture<T> QtConcurrent::run(T (*)(Param1), const Arg1&)’
   77 | QFuture<T> run(T (*functionPointer)(Param1), const Arg1 &arg1)

**Comment by TheTechRobo** [comment]
CI is broken too. For now use the latest commit with the green checkmark i.e. https://github.com/olive-editor/olive/commit/2a595cb4c72ebd22db1f821f7f2a40b55aa6eb29

**Comment by dacorsa** [comment]
can you tell me how do it?

git checkout 2a595cb?

Thanks

**Comment by dacorsa** [comment]
Yes thanks, now works :)

best regards

**Comment by p9malino26** [comment]
This also happens on mine. I also get errors due to QMouseEvent::position being called, which is only available in QT6. Might be because the code uses QT6-exclusive stuff, but Olive is meant to depend on QT5.

**Comment by ThomasWilshaw** [comment]
Latest commits are trialing upgrading to QT6 so things might be broken for a little while until the CI gets updated to. If you're able to, you should be able to compile against QT6 yourself
