### ISSUE TITLE
[CACHE] No disk cache apparently

### ISSUE THREAD

**Issue by UltraBlackLinux** [olive-editor/olive#2083]
**Commit Hash**  c5a86af1

**Platform** Linux

**Summary** There does not appear to be any disk cache working, the bar is missing at least. The preview sounds horrible and slowed down, pretty much the same as if you were to hold the space bar on a youtube video. The audio waveforms are about four seconds early.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
If you have multiple issues, make multiple issues. Don't mention several in one paragraph.

To cache a clip, right click it and navigate to "cache".

I haven't encountered any such audio issues. You'll need to be more specific.

**Comment by UltraBlackLinux** [comment]
> If you have multiple issues, make multiple issues. Don't mention several in one paragraph.
> 
> To cache a clip, right click it and navigate to "cache".
> 
> I haven't encountered any such audio issues. You'll need to be more specific.

I assumed these problems all had the same culprit. That's why I put them into one paragraph instead of multiple issues
