### ISSUE TITLE
[PLAYBACK] Frame-stepping backward is buggy

### ISSUE THREAD

**Issue by dexeonify** [olive-editor/olive#2090]
**Commit Hash** 
c06d17cf 

**Platform** 
Windows 11

**Summary**
Play a video or step forward a few frames using the right arrow key. Then, step back using the left arrow key.
If you attempt to step forward, the preview window seems to be stuck in a previous frame and becomes completely misleading.
Seeking doesn't update the preview, nor does clearing the cache helps. The only way to correct the preview is play the video again.

**Additional Information / Output**
This is on a freshly installed Olive. No logs are printed during the playback.

The video only showcases the bug with a simple shape, but it affects videos too. This bug makes perfect frame cutting highly impossible.

https://user-images.githubusercontent.com/72267349/200111972-e0d1713e-278a-4542-9b0a-eaa62a846291.mp4

**Comment by itsmattkc** [comment]
I've tested on two setups (Windows and Linux) and not encountered this.

Can you update to the latest version (1c4149a0fdae80a39d0799aaa7d9eef16737a225 or later), then enable "Use glFinish" in Preferences > Behavior > OpenGL and see if that makes a difference?

**Comment by dexeonify** [comment]
Amazing, that fixed it!

In case you require more hardware information:
CPU: Intel i7-9700
GPU: Intel UHD Graphics 630 (4.5.0 - Build 31.0.101.2114)
RAM: 8GB @ 2666 MHz
