### ISSUE TITLE
[EDIT] no Sound waveform after extending a clip in timeline

### ISSUE THREAD

**Issue by omida56** [olive-editor/olive#2092]
**Commit Hash**c06d17cf

**Platform** linux mint

**Summary**
importing part of a video to timeline everyting seems ok then extending the clip , there is no sound waveform in extended part.

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
Can confirm on Windows 10 too. To clarify, audio does work but the waveform in the timline is not drawn.

**Comment by itsmattkc** [comment]
Merging into #2199
