### ISSUE TITLE
[CODEC](H.265) no sound in footage viewer while timeline is OK

### ISSUE THREAD

**Issue by omida56** [olive-editor/olive#2093]
**Commit Hash** c06d17cf

**Platform** linux mint

**Summary**
the video format : MOV ,  codec: H.265 (no problim with H.264 footage) , sound codec: AAC 

**Additional Information / Output**
importing video in Olive then hit to see it in viewer window   (the blue progress bar that normaly shown at this time is absent)  and there is no sound in viewer window  then draging video to timeline ,  sound is available here.

**Comment by itsmattkc** [comment]
It's not going to be because the video stream was encoded in H.265. You're going to need to share the file you're working with.

**Comment by omida56** [comment]
https://user-images.githubusercontent.com/85232693/200143344-b302a75c-6e1b-425a-9e90-43b0b0edf7ae.MOV

**Comment by omida56** [comment]
My experiance : take look at the bottom bar while playing

https://user-images.githubusercontent.com/85232693/200143622-86db7161-3b90-4d8c-b00a-0445b66e991b.mp4

**Comment by ThomasWilshaw** [comment]
I can conform that with the suppplied clip we have audio in the timeline but not in the footage viewer. AUdio is encoded as AAC LC according to MediaInfo
