### ISSUE TITLE
[WEBSITE] STOP USING PHP

### ISSUE THREAD

**Issue by SelfhostedPro** [olive-editor/olive#2094]
**Commit Hash** latest (macos 12.5)

**Platform** All (Macos 12.5 & latest firefox)

**Summary**
Please consider using a language/framework that uses typescript/javascript as the current php site is non-functional on the latest firefox/macos. No matter what I click on I'm unable to download olive. If you need help I'm happy to be of assistance in order to convert to a usable language.

**Additional Information / Output**

**Comment by Simran-B** [comment]
You have to provide more details than this, like the exact browser version and the developer console output.
