### ISSUE TITLE
[CRASH] arm built crashes on launch

### ISSUE THREAD

**Issue by dolarfred** [olive-editor/olive#2095]
**Commit Hash** 

**Platform** 
macOS 12.6

**Summary**
Olive-435971c6-macOS-arm64 and Olive-2aaa2fb8-macOS-arm64 craches on launch, for the same build versions on intel builds there is no problem

**Steps to Reproduce**

1. 
2. 
3. 

<details><summary><strong>Crash Report</strong></summary><pre><code>
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Olive [26994]
Path:                  /Users/USER/Desktop/Olive.app/Contents/MacOS/Olive
Identifier:            org.olivevideoeditor.Olive
Version:               0.2.0 (0.2.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-11-10 08:34:33.3137 +0100
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Anonymous UUID:        23B07F34-3CD3-CD33-1598-8E1F05F653A3

Sleep/Wake UUID:       9B5B94C6-A9D9-4DAC-B379-A5FC5FA82774

Time Awake Since Boot: 150000 seconds
Time Since Wake:       1924 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 4 Symbol missing
Symbol not found: (__ZN7Imf_3_114TypedAttributeIN9Imath_3_13BoxINS1_4Vec2IfEEEEEC1ERKS5_)
Referenced from: '/Users/USER/Desktop/Olive.app/Contents/Frameworks/libOpenImageIO.2.3.19.dylib'
Expected in: '/Users/USER/Desktop/Olive.app/Contents/Frameworks/libOpenEXR-3_1.30.5.1.dylib'
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x10343fe98 __abort_with_payload + 8
1   dyld                          	       0x103447024 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x103447058 abort_with_payload + 16
3   dyld                          	       0x1033fea28 dyld4::halt(char const*) + 580
4   dyld                          	       0x1033f9fb8 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3644
5   dyld                          	       0x1033f906c start + 488

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016daee098   x3: 0x00000000000000f8
    x4: 0x000000016daedc98   x5: 0x0000000000000000   x6: 0x000000016daeca10   x7: 0x000000016daed710
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x000000016daedd66  x11: 0x000000000000011c
   x12: 0x0000000000000000  x13: 0x0000000000000032  x14: 0x00000001042d86ab  x15: 0x000000016daed268
   x16: 0x0000000000000209  x17: 0x00000001033f714c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016daedc98  x21: 0x00000000000000f8  x22: 0x000000016daee098  x23: 0x0000000000000004
   x24: 0x0000000000000006  x25: 0x000000016daedc98  x26: 0x0000000000000400  x27: 0x0000000000000400
   x28: 0x00000000000000ce   fp: 0x000000016daedc60   lr: 0x0000000103447024
    sp: 0x000000016daedc20   pc: 0x000000010343fe98 cpsr: 0x00001000
   far: 0x00000001032b4000  esr: 0x56000080  Address size fault

Binary Images:
       0x1033f4000 -        0x103453fff dyld (*) <38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=835.6M resident=0K(0%) swapped_out_or_unallocated=835.6M(100%)
Writable regions: Total=18.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=18.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__AUTH                            1678K      114 
__AUTH_CONST                      8146K      247 
__DATA                            18.9M      283 
__DATA_CONST                      11.2M      283 
__DATA_DIRTY                       544K       87 
__FONT_DATA                          4K        1 
__LINKEDIT                       594.3M       40 
__OBJC_CONST                      1066K       92 
__OBJC_RO                         83.0M        1 
__OBJC_RW                         3168K        1 
__TEXT                           241.3M      298 
__UNICODE                          592K        1 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                              1.0G     1452 

-----------
Full Report
-----------

{"app_name":"Olive","timestamp":"2022-11-10 08:34:33.00 +0100","app_version":"0.2.0","slice_uuid":"2e38341c-4b36-3cdc-bf6b-c0cc2ff05925","build_version":"0.2.0","platform":1,"bundleID":"org.olivevideoeditor.Olive","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"179D7D24-5E41-4AF4-BC12-5156A11D30B5","name":"Olive"}
{
  "uptime" : 150000,
  "procLaunch" : "2022-11-10 08:34:31.4169 +0100",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,7",
  "procStartAbsTime" : 3788127135258,
  "coalitionID" : 20974,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-11-10 08:34:33.3137 +0100",
  "incident" : "179D7D24-5E41-4AF4-BC12-5156A11D30B5",
  "bug_type" : "309",
  "pid" : 26994,
  "procExitAbsTime" : 3788172651346,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "Olive",
  "procPath" : "\/Users\/USER\/Desktop\/Olive.app\/Contents\/MacOS\/Olive",
  "bundleInfo" : {"CFBundleShortVersionString":"0.2.0","CFBundleVersion":"0.2.0","CFBundleIdentifier":"org.olivevideoeditor.Olive"},
  "storeInfo" : {"deviceIdentifierForVendor":"4AA5D946-95BA-5CD7-B22D-00C86E004D15","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.olivevideoeditor.Olive",
  "crashReporterKey" : "23B07F34-3CD3-CD33-1598-8E1F05F653A3",
  "wakeTime" : 1924,
  "sleepWakeUUID" : "9B5B94C6-A9D9-4DAC-B379-A5FC5FA82774",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":4,"flags":518,"namespace":"DYLD","indicator":"Symbol missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Symbol not found: (__ZN7Imf_3_114TypedAttributeIN9Imath_3_13BoxINS1_4Vec2IfEEEEEC1ERKS5_)","Referenced from: '\/Users\/USER\/Desktop\/Olive.app\/Contents\/Frameworks\/libOpenImageIO.2.3.19.dylib'","Expected in: '\/Users\/USER\/Desktop\/Olive.app\/Contents\/Frameworks\/libOpenEXR-3_1.30.5.1.dylib'"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1267313,"threadState":{"x":[{"value":6},{"value":4},{"value":6135144600},{"value":248},{"value":6135143576},{"value":0},{"value":6135138832},{"value":6135142160},{"value":32},{"value":9},{"value":6135143782},{"value":284},{"value":0},{"value":50},{"value":4365059755},{"value":6135140968},{"value":521},{"value":4349456716,"symbolLocation":392,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6135143576},{"value":248},{"value":6135144600},{"value":4},{"value":6},{"value":6135143576},{"value":1024},{"value":1024},{"value":206}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4349784100},"cpsr":{"value":4096},"fp":{"value":6135143520},"sp":{"value":6135143456},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4349755032,"matchesCrashFrame":1},"far":{"value":4348133376}},"frames":[{"imageOffset":310936,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":0},{"imageOffset":340004,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":0},{"imageOffset":340056,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":0},{"imageOffset":43560,"symbol":"dyld4::halt(char const*)","symbolLocation":580,"imageIndex":0},{"imageOffset":24504,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3644,"imageIndex":0},{"imageOffset":20588,"symbol":"start","symbolLocation":488,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4349444096,
    "size" : 393216,
    "uuid" : "38ee9fe9-b66d-3066-8c5c-6ddf0d6944c6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7200178176,
  "size" : 3144744960,
  "uuid" : "049b583e-d4dc-3b2b-88da-e52d6e18313d"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=835.6M resident=0K(0%) swapped_out_or_unallocated=835.6M(100%)\nWritable regions: Total=18.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=18.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__AUTH                            1678K      114 \n__AUTH_CONST                      8146K      247 \n__DATA                            18.9M      283 \n__DATA_CONST                      11.2M      283 \n__DATA_DIRTY                       544K       87 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       594.3M       40 \n__OBJC_CONST                      1066K       92 \n__OBJC_RO                         83.0M        1 \n__OBJC_RW                         3168K        1 \n__TEXT                           241.3M      298 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                              1.0G     1452 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "634710168e8be655c1316aaa"
      },
      "deploymentId" : 240000229
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000026
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,7, BootROM 7459.141.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5
AirPort: Wi-Fi, wl0: Mar 23 2022 20:47:07 version 18.60.27.0.7.8.129 FWID 01-bfc059c1
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
Fixed as of de8d50ea
