### ISSUE TITLE
[UI] Replacing footage file does not change file name in project window.

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#2098]
**Commit Hash** 
3302c363

**Platform** 
Windows 10

**Summary**
Olive shows already imported footage files in the project window. When you right click on one of those footage files a context menue appears. Then you have the option to click on "replace footage". If you do so you can search for a different footage file in your file system. If you chose a new file the new footage gets recognized by Olive, but Olive does not change the file name in the project window. Could you please fix this behaviour?

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
I'm not sure this is a bug, the feature is mainly for relinking media if for example you've been using proxies or move the location of a file. If you want to replace the media entierly why not delete it and add a new piece?

**Comment by Suk-RAM** [comment]
Well, when the feature is intended to relink footage files only, why is it called "replace footage"? And why does the file dialog allow to choose new footage from a new file whose name differ from the file name of the current footage? I think when the feature recognize new footage from a new file, it should also recognize the new file name.
By the way, the feature is a smart one. Why? Imagine you have arranged a presentation with stills and you find that some pictures need to be replaced by better ones having the same size you could do this with minimal effort using the feature "replace footage".

**Comment by Suk-RAM** [comment]
Now file names in the project window get updated.. Thank you. Could you please let the file name of a footage placed in a track along the timeline change, too?
