### ISSUE TITLE
Olive significant performance loss when you stack multiple clips of the same imported footage

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#21]
Dragging in a second copy of your imported footage into the timeline and having them play over each other (on separate video layers) results in at least 50% performance loss to playback. This can be repeated, further decreasing performance. 

Workaround: Importing the same footage twice (having 2 references to the same footage in the import panel) and dragging each reference into the timeline allows for intended playback performance.

**Comment by itsmattkc** [comment]
This will likely be fixed by opening multiple input streams of each file depending on how many simultaneous clips are playing. Ideal solution would be for Olive to open and close these streams transparently to the user based on what's playing to economize memory usage. Additionally #4 requires this issue to be resolved.

**Comment by itsmattkc** [comment]
About to rewrite a large chunk of Olive's file handling to fix this issue once and for all.

**Comment by itsmattkc** [comment]
Issue is fixed, but solution is complete and will lead to memory leaks down the road. Leaving this open until those problems are fixed.

**Comment by itsmattkc** [comment]
Merging #24 with this. Future steps for this issue are:

- Dynamically open/close inputs on Stream with Timeline depending on what needs playing
- Make app multithreaded so it can do these things outside of the main event loop

**Comment by itsmattkc** [comment]
This issue is fixed and the aforementioned steps have been completed.
