### ISSUE TITLE
[EDIT] Clip thumbnails not showing

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#2105]
**Commit Hash** 
3302c363

**Platform** 
macOS 12.6.1

**Summary**
I thought it wasn't implemented yet but I have seen it in some other users screenshots... I haven't found any way to activate them.
This way is how it is seen under macOS:
<img width="691" alt="thumbnails" src="https://user-images.githubusercontent.com/5942369/202725286-b9786253-4970-4209-941d-d39600e20881.png">

Cheers

**Additional Information / Output**

**Comment by itsmattkc** [comment]
Check your thumbnail setting by right clicking an empty part of the timeline and opening the "Show Thumbnails" menu.

It's true they are a little intermittent at the moment, but that should improve soon.

**Comment by pgilfernandez** [comment]
Oh, it feels like the feature is little bit hidden... 
By the way, it doesn't work for me (it was already active and didn't work):
<img width="634" alt="thumbnails2" src="https://user-images.githubusercontent.com/5942369/202841351-23cdb74b-815a-42d7-9f34-c634f648dfe2.png">

I'll wait for those future changes as it is not an important feature for me, but at least I wanted to let you know how it behaves under macOS.

Thanks

**Comment by itsmattkc** [comment]
> Oh, it feels like the feature is little bit hidden...

It should be on by default. I'm only asking you to check because you're saying it isn't working.

I'm already working on improvements so I'll close this for now. Thanks for the information.
