### ISSUE TITLE
[CRASH] Appimage won't launch if there's a space at the file name

### ISSUE THREAD

**Issue by myghi63** [olive-editor/olive#2107]
**Commit Hash** 
5fce683e

**Platform** 
Arch Linux, kernel 6.0.8-zen1-1-zen

**Summary**
With default name (that contains no spaces at all) it works just fine, but after renaming the file (putting a simple space in it) it trows a error and just won't launch.

**Steps to Reproduce**

1. Download the latest olive appimage build and extract the .zip
2. Rename the file (put a random space)
3. Try to run it

<details><summary><strong>Crash Report</strong></summary><pre><code>

[myghi63@myghistation Área de trabalho]$ ./Olive\ 5fce683e-Linux-x86_64.AppImage
/tmp/.mount_Olive nqmOV8/AppRun: line 8: /tmp/.mount_Olive
/home/myghi63/Área de trabalho/nqmOV8/usr/bin/olive-editor: No such file or directory

</code></pre></details>

**Additional Information**

**Comment by itsmattkc** [comment]
This seems to be a limitation of AppImages in general, they have an issue for it there: AppImage/AppImageKit#678
