### ISSUE TITLE
Unusual Behaviour[PLAYBACK] 

### ISSUE THREAD

**Issue by MadCoding208** [olive-editor/olive#2115]
**Commit Hash** 

**Platform** <Windows 10>

**I crated two tracks one is shape and the other is title track. I put the shape in the video track 0 and the title track above it. but in the preview window when maneuver the title track on the top of the shape it starts to flicker and some time the whole preview window gets black.**

**Additional Information / Output**

https://user-images.githubusercontent.com/43301199/204437681-4e46fbc1-9216-46b6-9297-4135403b560c.mp4

**Comment by sobotka** [comment]
Please fill out the issue template fully. Commit hash.
