### ISSUE TITLE
[EXPORT] Setting In Point other then first frame crashes on video export

### ISSUE THREAD

**Issue by ChildLearningClub** [olive-editor/olive#2119]
**Commit Hash** 
af76fbf0

**Platform** 
Windows 11

**Summary**
Exporting video using in out points will crash if the in point is anything other then the first frame. 

**Additional Information / Output**
video will export fine using entire project and if the in out points are set with the in point at the beginning of the video, but the output will hang and then crash with the in point set to anything other then the very beginning

**Comment by itsmattkc** [comment]
I'm fairly certain what you're running into is not what you think. I've been made aware of a bug where if the in point is set at a time that isn't a frame boundary (i.e. the in point is somewhere between two frames), the export will fail. I'm pretty sure that's what you're running into. If you move your in point to a frame, it should work.

This is a known issue and will be resolved eventually.

**Comment by ChildLearningClub** [comment]
@itsmattkc thank you, that is good to know, I was able to get it to work today, but was not certain what had changed, your comment explains it.
