### ISSUE TITLE
The window is black

### ISSUE THREAD

**Issue by Nintendelta** [olive-editor/olive#2121]
**af76fbf0** 

**Windows 7** 

**The screen shows up completely black, I can still interact with elements, but can't see them**

**This may be a graphics card issue, I have an Intel HD 3000**

**Comment by TheTechRobo** [comment]
How is there no commit hash? Please elaborate.

**Comment by Nintendelta** [comment]
> 

Oops, thought it meant the code sent by the program. What am I supposed to put there?

**Comment by TheTechRobo** [comment]
If you got it from the download page, it probably shows there in addition to the program, unless you got 0.1, which is unsupported.

**Comment by Nintendelta** [comment]
> If you got it from the download page, it probably shows there in addition to the program, unless you got 0.1, which is unsupported.

I see, editing the original comment now

**Comment by itsmattkc** [comment]
I'm afraid the Intel HD 3000 is too old to run Olive 0.2. I apologize for any inconvenience.

**Comment by TheTechRobo** [comment]
Could you add a better error message for that? (Maybe a separate issue, but even if it was just an alert box that said something along the lines of "This graphics card might be too old to run Olive. You will likely run into issues."
