### ISSUE TITLE
[EDIT]Having Problems with Title tool 

### ISSUE THREAD

**Issue by MadCoding208** [olive-editor/olive#2122]
**Commit Hash** af76fbf0

**Platform**  Windows 10

**Summary**
There so many issues with the title tool
1. Sometimes the parameter editor is not showing 
2. After deleting the sample text the text size automatically reduced to 0.1
3. The resizing cursor is not showing while hovering over the corner of the text box. I think the text is not vector based that's why once while I resize the text box the text size did not increased.
4. While selecting text the highlight is not being displayed.

**Additional Information / Output**

**Comment by brokenarrowgarage** [comment]
I also have experienced this. Even overlapping text while editing. I've been able to work around the bugginess. However if I do a few titles in a row olive crashes. So after I do a couple titles I will save and close olive manually and reopen to ensure I do not lose any unsaved progress like I did the first couple times experiencing the issue.

**Comment by MadCoding208** [comment]
> 
we have to be patient. As currently this is the only video editor that comes up with node based compositing.

**Comment by itsmattkc** [comment]
All of these should be resolved as of c8908587bbea52f085e7dd597da03b15c7e63d29
