### ISSUE TITLE
[PROJECT] Unable to import folders via drag&drop from "Import..." window

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#2123]
**Commit Hash** af76fbf0

**Platform** Linux (Debian 11, Xfce4)

**Summary**

Importing folders with media by drag&drop from *"Import..."* window into *"Project"* dock does not work — when trying to move action shown as not permitted.

In same time, importing folders with media into *"Project"* dock by  drag&drop from external file manager window (i.e. from *Thunar*) works normally.

**Additional Information / Output**

In legacy *Olive* `v0.1` (f81df00) drag&drop of folders from *"Import..."* window into *"Project"* dock works normally.

**Comment by ThomasWilshaw** [comment]
TBH I would say this is expected behaviour, once you are in the import window why would you need to drag and drop? Do you have a use case where this would be required?
