### ISSUE TITLE
[EDIT] Cannot change font face consistently

### ISSUE THREAD

**Issue by murb144** [olive-editor/olive#2124]
**** 

**Linux Mint** 

**I can't change the font name, I can make font bigger or smaller, change the color, but after I choose another font name from the list, text stays the same. I removed the program and re-installed it several times and problem stays. It works randomly for a while that I can pick another font but then stays same again. **

**Additional Information / Output**

**Comment by AGI-THB** [comment]
Fill out the issue template.

**Comment by murb144** [comment]
> Fill out the issue template.

I don't get this system here and technical terminology.

**Comment by TheTechRobo** [comment]
> I don't know what is Commit Hash

It's in the Help > About dialog in the program, like the description showed. Alternatively, you can find it on the download page.

**Comment by Simran-B** [comment]
When you create an issue, the input box already has some text, to ask for specific information that is required for an actionable issue report.

The text starts with `<!-- ⚠ Do not delete this issue template! ⚠ -->`. The `this` should make clear what the issue template is - the text you are looking at when filing an issue.

`**Commit Hash** <!-- 8 character string of letters/numbers in title bar or Help > About dialog (e.g. 3ea173c9) -->` explains what the commit hash looks like and where you can find it. In case you don't understand, here are some screenshots:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/7819991/207926797-2a369bd6-1a92-4c13-bef3-1e318975c214.png">

<img width="294" alt="image" src="https://user-images.githubusercontent.com/7819991/207926948-7769ad23-87ce-4feb-8477-1a81c7a42781.png">

The commit hash is `af76fbf0` in the example.
