### ISSUE TITLE
[NODES] Swap "Base" and "Blend" parameters

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#2126]
**Commit Hash** 
f234deb9

**Platform** 
macOS 12.6.1 (all)

**Summary**
I would like to suggest to swap the order of "base" and "blend" parameters in the Merge node as "base" usually is considered to be placed "underneath" anything else. In (I would say all) graphic design software that makes use of the concept of layers, they are stacked from bottom to top, that is, the base layer sits below the others.
As you see this issue it's not a bug, it's just a suggestion to place things more logically in order to improve UX and Olive experience:
<img width="1525" alt="merge_node" src="https://user-images.githubusercontent.com/5942369/208072436-bdb6aa9b-8faf-4e96-bb4e-652de89e3c19.png">

What do you think?

Thanks

**Additional Information / Output**

**Comment by itsmattkc** [comment]
I've thought about this and researched what other node compositors do, and have found for the most part they do what Olive does - the "base" is the first input and the "blend" is the second. As such I think we will keep it as-is, though I do understand your thought process.
