### ISSUE TITLE
[EXPORT] When I export the video is grainy. There seems to be no quality option like on v1?

### ISSUE THREAD

**Issue by brokenarrowgarage** [olive-editor/olive#2129]
**Commit Hash** 

**Platform** 
Windows 11

**Summary**
Online there are many videos that show on v1 you can choose a quality for the video, lower the number meaning better the quality. However this is missing on v2. I edited a video about 12 min long my first time and it came out great and was 2GB. Second video looks awful. It's 38 min long and only 3.5GB. Obviously confirming quality was lowered. I did not change the settings. I notice under codec in the export setting there is a slide bar that is automatically set at 18, I thought this maybe the CRF setting. However according to what I've read it's auto set to 36(on v1). I changed the setting to 8 hoping it might help with my issue. However I believe this is not the setting I was looking for as it did not help. There seems to be no tutorials on using v2 so I'm just running in circles trying to find a quality option while exporting. Any insight?

**Additional Information / Output**

**Comment by brokenarrowgarage** [comment]
scratch that, rebooting and re-exporting at 8 instead of the auto 18 yielded a high quality video. 15gb worth. took 3 hours instead of 4 hours, so it came out better quality and took a shorter amount of time at 8. go figure.

**Comment by ThomasWilshaw** [comment]
Closing as you seemed to have resolved this yourself. Feel free to re open if there is still an issue.
