### ISSUE TITLE
[EDIT] When editing a video with 3 audio tracks only 2 waveform show up

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#2130]
**Commit Hash**  af76fbf0

**Platform**  Windows 11

**Summary** Only first 2 tracks show waveform instead of all

**Additional Information / Output**
![obrazek](https://user-images.githubusercontent.com/18588943/209228749-5ae29bd1-e03c-418d-9e76-45a985fedc59.png)

Olive console shows: [WARNING] Unknown parameter: "Files\\Olive"

ffmpeg output

'''

Input #0, matroska,webm, from '.\OBS_2022-12-12 10-57-48.mkv':
  Metadata:
    ENCODER         : Lavf59.16.100
  Duration: 01:42:52.75, start: 0.000000, bitrate: 2935 kb/s
  Stream #0:0: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 60 fps, 60 tbr, 1k tbn
    Metadata:
      DURATION        : 01:42:52.750000000
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : Track1
      DURATION        : 01:42:52.736000000
  Stream #0:2: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : Track2
      DURATION        : 01:42:52.736000000
  Stream #0:3: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : Track3
      DURATION        : 01:42:52.736000000

'''

**Comment by mcDandy** [comment]
Or just one can show up.

**Comment by itsmattkc** [comment]
Merging into #2199
