### ISSUE TITLE
[PLAYBACK] No sound is playing

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#2131]
**Commit Hash** af76fbf0

**Platform** Windows 11 (22623.1037)

**Summary**
I cannot hear any sound comming from playback. Sound is exported correctly

**Additional Information / Output**
I have like 200MB left on my main drive (thank you windows)

1. Open Olive
2. add an file with audio to timeline
3. play (no sound heared)

https://user-images.githubusercontent.com/18588943/209235569-c5c2319f-59b4-44e8-ae53-1a1a6602d4b0.mp4

**Comment by mcDandy** [comment]
Windows muted olive...

**Comment by mcDandy** [comment]
It is happening again. I am sure, that app is not muted. Happened maybe becouse of hibernation when I ran out or battery after accidental unplug in the middle of 12h rendering.

**Comment by itsmattkc** [comment]
Check Olive's audio settings. Try different audio APIs, etc. It seems to be specific to your setup so there's not much we can do about it.
