### ISSUE TITLE
[EDIT] Footage viewer not working anymore after removing and adding it back

### ISSUE THREAD

**Issue by radiotoz** [olive-editor/olive#2136]
**af76fbf0** 

**Windows 11** 

**After accidently removing the footage viewer, I added it back and my footage would not show up again, making editing the project virtually impossible as there isnt a way to look at what you are producing, or even to play the video. I realize that you can reveal in footage viewer, however you cannot do this with anything but audio and video (no titles). Im sure this is just my error and I cant figure out how to make it work again, but I cant see any clear way to view my footage after I did this.**

**Might be a bug, might be my error and I just cant figure it out.**

**Comment by Simran-B** [comment]
Does Window > Reset to Default Layout in the menu help?
