### ISSUE TITLE
[EDIT] Auto scrolling in Parameter Timeline.

### ISSUE THREAD

**Issue by EditaNEmilis** [olive-editor/olive#2138]
**Commit Hash** 
f234deb9

**Platform** 
Windows 10

**Summary**
Started editing my video and decide to do a quick zoom to the parts.. Then the Timeline scroll is just scrolling, not using the mouse wheel.
And yet, it happens every time for like 20 to 30 minutes..

**Additional Information / Output**

https://user-images.githubusercontent.com/107065286/210257379-e70c6f6f-206d-4cd7-94c6-02add08a4109.mp4

**Comment by itsmattkc** [comment]
Can you provide steps to reproduce?
