### ISSUE TITLE
[CRASH] Trying to cancel audio export

### ISSUE THREAD

**Issue by mcDandy** [olive-editor/olive#2140]
**Commit Hash**  af76fbf0

**Platform**  Windows 11

**Summary**
Crash when clicking X on cancelled sound rendering

**Steps to Reproduce**

1. Import sound file (used: 10s; 32bit float; 44.1kHz; mono; waw)
2. put file on timeline and automatically detect parameters
3. connect time to volume node
4.  export as waw on default settings (16bit; singed; mono; 44.1kHz)
5. Exporting hung on 0% (0:00:00 out of 0:00:00); Click cancel
6. Cancel button disables itself and nothing else happens; click X
7. crash

<details><summary><strong>Crash Report</strong></summary><pre><code>

Crshpad is empty. I hope stack trace will be sufficient.

olive-editor.exe!olive::RenderProcessor::ProcessSamples(olive::SampleBuffer & destination, const olive::Node * node, const olive::TimeRange & range, const olive::SampleJob & job) Řádek 495
	v umístění D:\a\olive\olive\app\render\renderprocessor.cpp(495)
olive-editor.exe!olive::NodeTraverser::ResolveJobs(olive::NodeValue & val) Řádek 460
	v umístění D:\a\olive\olive\app\node\traverser.cpp(460)
olive-editor.exe!olive::NodeTraverser::GenerateRow(olive::NodeValueDatabase * database, const olive::Node * node, const olive::TimeRange & range) Řádek 71
	v umístění D:\a\olive\olive\app\node\traverser.cpp(71)
olive-editor.exe!olive::NodeTraverser::GenerateTable(const olive::Node * n, const olive::TimeRange & range, const olive::Node * next_node) Řádek 301
	v umístění D:\a\olive\olive\app\node\traverser.cpp(301)
olive-editor.exe!olive::NodeTraverser::ProcessInputElement(std::map<int,olive::NodeValueTable,std::less<int>,std::allocator<std::pair<int const ,olive::NodeValueTable>>> & array_tbl, const olive::Node * node, const QString & input, int element, const olive::TimeRange & range) Řádek 247
	v umístění D:\a\olive\olive\app\node\traverser.cpp(247)
olive-editor.exe!olive::NodeTraverser::ProcessInput(const olive::Node * node, const QString & input, const olive::TimeRange & range) Řádek 217
	v umístění D:\a\olive\olive\app\node\traverser.cpp(217)
olive-editor.exe!olive::NodeTraverser::GenerateDatabase(const olive::Node * node, const olive::TimeRange & range) Řádek 51
	v umístění D:\a\olive\olive\app\node\traverser.cpp(51)
olive-editor.exe!olive::RenderProcessor::GenerateDatabase(const olive::Node * node, const olive::TimeRange & range) Řádek 316
	v umístění D:\a\olive\olive\app\render\renderprocessor.cpp(316)
olive-editor.exe!olive::NodeTraverser::GenerateTable(const olive::Node * n, const olive::TimeRange & range, const olive::Node * next_node) Řádek 287
	v umístění D:\a\olive\olive\app\node\traverser.cpp(287)
olive-editor.exe!olive::RenderProcessor::Run() Řádek 224
	v umístění D:\a\olive\olive\app\render\renderprocessor.cpp(224)
olive-editor.exe!olive::RenderProcessor::Process(std::shared_ptr<olive::RenderTicket> ticket, olive::Renderer * render_ctx, olive::RenderCache<olive::Decoder::CodecStream,olive::DecoderPair> * decoder_cache, olive::RenderCache<QString,QVariant> * shader_cache) Řádek 322
	v umístění D:\a\olive\olive\app\render\renderprocessor.cpp(322)
olive-editor.exe!olive::RenderThread::run() Řádek 267
	v umístění D:\a\olive\olive\app\render\rendermanager.cpp(267)
[Externí kód]

</code></pre></details>

**Additional Information**

**Comment by ThomasWilshaw** [comment]
I'm not quite sure what you mean in step 3. Can you provide a screenshot of your node setup? If you don't do step 3, does Olive still crash?

**Comment by mcDandy** [comment]
By step 3 I ment this: ![image](https://user-images.githubusercontent.com/18588943/213782711-530a5e43-7d47-4db9-96d5-82a774df2852.png)

Without time node it exports instantly. However the moment you connect the time node you will be stuck with this: 
![image](https://user-images.githubusercontent.com/18588943/213783397-c1272f7d-1478-4bb9-8b8a-1202d89dab20.png)

It will not crash unless you press cancel and then the X button which should close the dialogue box.
