### ISSUE TITLE
[UI] Sequence Viewer Trackpad Zoom Sensitivity Too High

### ISSUE THREAD

**Issue by nudefireninja** [olive-editor/olive#2143]
**Commit Hash** af76fbf0 

**Platform** macOS 13 

**Summary** Zooming in the sequence viewer by holding ⌘ and swiping up/down with two fingers on the trackpad changes the zoom level too fast. I suggest decreasing the sensitivity and adding a way to set the zoom level more precisely to e.g. 200%, 300%, etc.

**Additional Information / Output**

**Comment by itsmattkc** [comment]
This is addressed as of 060c3b088304a20b92b49824cb174316890167de, though for the record, you *can* set the zoom level more precisely. Just right click on the viewer for a menu.
