### ISSUE TITLE
[NODES] Adding Bool value type to Value node (and new invert node)

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#2145]
**Commit Hash** 
e7982239

**Platform** 
all

**Summary**
I'm missing a boolean value type (true / false) in order to connect it to, as instance, to any node with an "enable" parameter.

**Additional Information / Output**
It would be nice as well to have another simple node that inverts that bool signal in order to build more complex node setups.

Thanks

**Comment by mcDandy** [comment]
What invert do you mean?
1-value (logic, works correctly only in interval <0;1>)
Or 
-value (additive)
Or
1/value (multiplicative)

**Comment by pgilfernandez** [comment]
I would say logic, that is, if my value is set to TRUE, the invert node would turn it into FALSE and the contrary.

I haven't say it but what the "bool" type should do is to be compatible with any parameter with a "check".

Thanks

**Comment by pgilfernandez** [comment]
@itsmattkc did you add the node to invert the bool signal?
The value works like a charm but I miss this other option...

Thanks
