### ISSUE TITLE
[UI] Replacing footage file does not change file name in timeline window.

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#2147]
**Commit Hash** 
e7982239

**Platform** 
Windows 10

**Summary**
This issue continues the already closed issue #2118 which solves the problem only partly. Please read issue #2118 first.

_What is solved so far?_
Olive now changes the file name of an IMAGE, a VIDEO and an AUDIO file in the project window when the file was replaced by using the function "replace footage". So a) and b) of issue #2118 are solved.

_What is not solved so far?_
Not solved is c) of issue #2118. Olive does still not change a file name in the track bar of the timeline window when the file gets replaced in the project window by function "replace footage".  

**Additional Information / Output**
Some questions ...
- Can I reopen a ticket that I wrote and that was closed by someone else (typically a developer)? I had two times the joy to write a new ticket because I was not able to reopen an older ticket which was not fully solved.
- Does a developer who has closed a ticket recognize when I write a comment to that closed ticket?

**Comment by itsmattkc** [comment]
Should be implemented as of 49fd809db76494ae2f19ac13083d23de5b15734b
