### ISSUE TITLE
[CRASH] Timeline smooth scrolling crash on freshly opened file

### ISSUE THREAD

**Issue by Katzenwerfer** [olive-editor/olive#2156]
**Commit Hash** 
e7982239

**Platform** 
Windows 10 IoT Enterprise LTSC
Version 21H2 (19044.2486)

**Summary**
Using the `smooth scrolling` auto-scroll method causes a crash whenever a file that has objects in the timeline is opened.

**Steps to Reproduce**

1. Create a fresh project
2. Add some files and drop them in the timeline
3. Set the Auto-Scroll Method setting to Smooth Scrolling
4. Close the program
5. Reopen the program and open the test project.
6. Attempt to start playback

<details><summary><strong>Crash Report</strong></summary><pre><code>

The report was too big, so I had to upload it to a gist
https://gist.githubusercontent.com/Katzenwerfer/1417f4e2722201dce5254780fac7e36d/raw/6b7b5e38d2167bb34c4a308f056557f4ee4f7074/Olive%2520Crash%2520Report.txt

</code></pre></details>

**Additional Information**
I can't think of any other useful information I could provide, but do tell me if some data in particular is needed.

**Comment by ThomasWilshaw** [comment]
Can confirm on Windows 10

**Comment by ThomasWilshaw** [comment]
It seems to be to do with the call to `GetConnectedNode()` on line 501 of `timebasedwidget.cpp`, it seems like the conencted node is not getting set. I notice that if I select/focus the timeline and then play back the crash does not occur
