### ISSUE TITLE
[CRASH] Crash when copying a special video in timeline

### ISSUE THREAD

**Issue by WelkinHere** [olive-editor/olive#2157]
**Commit Hash** 
e7982239

**Platform** 
Windows 11 21H2 (22000.1455)

**Summary**
Copying a video in timeline and it crashed.

**Steps to Reproduce**

1. Open an existed / fresh new project
2. Added 2 video and lots Title in there
3. Copy the 1st video with the title
4. Copy the 2nd video
5. crosh

<details><summary><strong>Crash Report</strong></summary><pre><code>

The Crash report is too long and can't pasted at there.
</code></pre></details>
[So I uploaded at pastebin.](https://pastebin.com/QVQMMHLk)

**Additional Information**
i dont know this issue is only can appear on my computer because this is happend at one of my projects.

**Comment by WelkinHere** [comment]
Additional Info:

I recorded that crash but idk that would help

here is the [LINK](https://www.youtube.com/watch?v=sd2H6vmy56s)

**Comment by itsmattkc** [comment]
Copy and paste has been reworked. See if this still occurs. If so, reply back and I'll re-open.
