### ISSUE TITLE
[UI] Please make more tools shortcut-mappable

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#2158]
It would be really useful to have more tools available through keyboard shortcuts. I'm thinking primarily of Title, Solid, and Subtitle. Speaking from my own experience, most of the time, I can deal with Title and Solid not being mappable, but Subtitle is a whole different story. Here is why.

I make scripted YT videos. So I copy an entire sentence from the script, see into how many parts I want to split it so that it would be convenient to read off the screen, then draw the subtitle boxes, split the copied text between them, and finally tweak the position of the boxes. Then I repeat it for the next sentence. The latest video I did has 70 sentences, and it's a relatively short one. This means I had to switch from the Select tool to the Subtitle tool by expanding the tool group button ca. 70 times. I would really rather setup a keyboard shortcut and use it instead :)

**Comment by itsmattkc** [comment]
All addable items have been moved to the main menu so they integrate with the existing keyboard shortcut infrastructure. Thanks for the suggestion!
