### ISSUE TITLE
[UI] Colour Picker spam

### ISSUE THREAD

**Issue by Disaster2life** [olive-editor/olive#2161]
**Commit Hash** bf049f98

**Platform** Fedora 37

**Summary**
Using the colour prompt in the parameter editor for any of the nodes allows the user to open multiple windows for the colour dialogue, I assume the normal behaviour in this situation is to limit the amount the user can open, and refocus the open window?
**Additional Information / Output**
![image](https://user-images.githubusercontent.com/19931889/218164274-bed3036d-e034-4e4a-aae2-88f7c679ab96.png)

**Comment by ThomasWilshaw** [comment]
Can confirm this on Windows 10 too.
