### ISSUE TITLE
[EDIT] Editing in the timeline has become unbearably slow. Moving clips takes 2-10 seconds.

### ISSUE THREAD

**Issue by oliveman521** [olive-editor/olive#2167]
**Commit Hash** 
e7982239

**Platform** 
Windows 10

**Summary**
I've been working on a project for a few days. It's about 20 minutes long and has a lot of cuts. At first, it only slowed down when I moved chunks of clips, but now even single clip movements are very sluggish. 

Most footage is only 1080p 30 fps. So is the Sequence

I have a decent processor, and while the usage gets pretty high during playback, the playback is plenty smooth, but the usage doesn't get all that high when moving clips.
Processor	AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx, 2300 Mhz, 4 Core(s), 8 Logical Processor(s)
I was able to edit larger projects in premiere without significant issue, so I don't think it's just an issue of "get a better computer"

**Additional Information / Output**
Video of the issue with task manager monitoring
https://user-images.githubusercontent.com/53627220/218829409-4659238d-0abc-4215-aca1-156d8b5df30f.mp4

**Comment by itsmattkc** [comment]
This is a known issue. I'm working on it.

**Comment by oliveman521** [comment]
To follow up, do you have more information on what is causing it? Will bundling my project into shorter sequences band-aid the problem? Or is it at the project level?
Thanks again

**Comment by itsmattkc** [comment]
This should be resolved as of 43f1be9c06805284fa4630ddacde8de3b78205ae
