### ISSUE TITLE
[BUILD] "portaudio_x64.dll" is missing.

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#2168]
**Commit Hash** 
9a87b197

**Platform** 
Windows 10

**Summary**
It doesn't matter if you run Olive Portable or Olive Installer, both stop with the message that "portaudio_x64.dll" is missing and thus the code cannot be executed any further. 

**Additional Information / Output**

**Comment by itsmattkc** [comment]
I know.

**Comment by Suk-RAM** [comment]
The dll is now no longer missing. Thank you.
