### ISSUE TITLE
[EDIT] Olive does not work with former Olive projects.

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#2169]
**Commit Hash** 
68959763

**Platform** 
Windows 10

**Summary**
Whenever I try to load a project file that I made with a former Olive version, Olive shows me only content in the project window, but nothing in the timeline, nothing in the node graph window, nothing in the parameter editor and so forth.

**Additional Information / Output**
Is it possible for you to make some basic tests on a Windows platform before you upload code to git?

**Comment by itsmattkc** [comment]
Just open the sequence by double clicking it. It's not hard.

**Comment by itsmattkc** [comment]
> Is it possible for you to make some basic tests on a Windows platform before you upload code to git?

What do you think a "nightly" build is? What do you think "alpha" software is? What do you think a git repository is?

**Comment by Suk-RAM** [comment]
Calm down. I'm not your enemy. I know that mainly you (but also others) develop Olive in their short times. And I like to use Olive and therefore I am willing to test it and this way help to improve it. But I think it would make much more sense when people like me focus on identifiing bugs that are well hidden instead of those that are obvious. And that's why in my opinion a nightly build should meet some basic quality standards.

Saying that I hope that Olive will learn again to open sequences by default. Thanks in advance.
