### ISSUE TITLE
[UI][EDIT] Olive crashes when a cross dissolve transition covers every single frame of a snippet.

### ISSUE THREAD

**Issue by Suk-RAM** [olive-editor/olive#2171]
**Commit Hash** 
d09e2575

**Platform** 
Windows 10

**Summary**
*What's the issue?*
Assume you put a snippet of a video, an audio or even an image into a track of the timeline. And you want the snippet as far as possible to be covered by a cross dissolve transition. So you start either at the left end of the snippet or at it's right end and then you pull the transition all over the snippet - over every single frame. As soon as you then release the mouse key Olive crashes.

*What's the reason for the crash?*
I think Olive crashes because it does not prevent a snippet to be fully covered by a transition. At least one frame of a snippet should  stay uncovered.

*Why do I think that's the reason?*
There's a slightly different way to cover a snippet by a transition which I think shows why. Again you start either at the left or at the right end of a snippet and then pull the transition over the snippet, but this time only partly. Next release the mouse key. After that try to extend the transition to the full length of the snippet. You see that the extension process stops just one frame before the whole snippet is covered. When you finally release the mouse key Olive stays alive.
 
**Additional Information / Output**

**Comment by Suk-RAM** [comment]
The topic is related to this already closed issued: #1450.

**Comment by itsmattkc** [comment]
It was closed because it was merged into #1842, as this will be
