### ISSUE TITLE
[BUILD] Distribute an installer for Linux instead of a standalone executable

### ISSUE THREAD

**Issue by IoIxD** [olive-editor/olive#2174]
**Commit Hash** 

3bc53cef

**Platform** 

Any Linux

**Summary**

Every time I have installed Olive to a Linux install (which has been around 3-4 times at this point) I've just renamed the file to `olive` and moved it to my `/usr/bin`, and then made my own `.desktop` file. Given how simple it is and how it's worked almost every time, I suggest the AppImage that's distributed through the site be replaced with an AppImage that installs the AppImage to `/usr/bin` and makes said .desktop file.

I will volunteer to do this in a PR at some point soon.

**Comment by parona-source** [comment]
Have you looked at appimage integration projects like https://github.com/TheAssassin/AppImageLauncher ? Like this project exists to make "installing" appimages easier with desktop entries etc.

**Comment by itsmattkc** [comment]
I'm not sure about this, it runs counter to how almost all AppImages I've seen work. I think installing should probably be kept to each distro's native package manager, however they want to handle it. Though I do acknowledge that AppImages in general aren't the most convenient thing in the world; we may look into reinstating Flatpak support at some point.

**Comment by IoIxD** [comment]
The way I see it, AppImages are already different from how most FOSS people and companies distribute their software. If it already eviates from the norm as far as it does, it could at least deviate further.

Relying on package managers is better but that invovles relying on it being in the distro's repos. If theres an alternative to this solution to be done, it should be Flatpaks yes.

Although personally I also don't like working with two package managers at once, and suggest that the Flatpakked version has a prompt for auto updates; it's unusual for Linux software, but its better then the user forgetting they installed the program through Flatpak and never seeing it update.

**Comment by itsmattkc** [comment]
> The way I see it, AppImages are already different from how most FOSS people and companies distribute their software. If it already eviates from the norm as far as it does, it could at least deviate further.

I don't really agree with this. While there is an argument that AppImages deviate from "standard Linux packaging", it is a standard in itself, and we conform to that standard. AppImages should behave how people expect AppImages to behave.

> Relying on package managers is better but that invovles relying on it being in the distro's repos. If theres an alternative to this solution to be done, it should be Flatpaks yes.

Indeed Olive isn't in most package managers now, but it's also in alpha so we wouldn't really expect it to be. I expect that to happen naturally further down the line.

Depends on your distro too. It is in some "bleeding edge" repos like the AUR which Arch users are pretty accustomed to using, and we may be able to re-deploy an Ubuntu PPA some day, but again it's alpha so widespread deployment still isn't a high priority. AppImages require the lowest maintenance for the time being.

**Comment by Simran-B** [comment]
Regarding updates: What you absolutely don't want with the nightly builds is automatic updates because they can render your project files unusable. It will be a different story once there's a stable version.

**Comment by this-is-just-con-tribute** [comment]
> Regarding updates: What you absolutely don't want with the nightly builds is automatic updates because they can render your project files unusable. It will be a different story once there's a stable version.

Have you guys considered getting in contact with linux creators to promote it, or even just channels that talk about video editing in general? I feel like noboby talks about you guys, and that's a shame. I wish I was made of money so I could just give a million dollars to the project.

**Comment by Simran-B** [comment]
Promoting Olive has largely been avoided due to it being alpha software with bugs and missing features.

**Comment by RafaelLinux** [comment]
I think this thread is already closed and the latest posts do not refer to the subject of it. Please use another thread. In any case, I consider the AppImage distribution to be the best option the developer has chosen. Download and go.
