### ISSUE TITLE
How do you move imported media files over to the timeline?

### ISSUE THREAD

**Issue by techristian** [olive-editor/olive#2175]
**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**
How do you move imported media files over to the timeline? I'm using v  .2 on Mint Linux 22....instructions anywhere?

Dan Laskowski

**Comment by techristian** [comment]
I guess you have to create a project first...even after importing media. I have a long video to edit though, over an hour and it seemed to choke after it got to 50% (when sliding into the timeline)

Dan

**Comment by itsmattkc** [comment]
I'm not really sure what you're saying. To add media to the timeline, you just drag it over from the Project Explorer.

**Comment by ThomasWilshaw** [comment]
> I guess you have to create a project first...even after importing media. I have a long video to edit though, over an hour and it seemed to choke after it got to 50% (when sliding into the timeline)
> 
> Dan

I'm just curious, what format is the video?

**Comment by techristian** [comment]
it is from a Nikon camera *.mov format 
When I tried to re-open this project from a few hours ago , I got the following error.

Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 5.15.0-60-generic
System: Linux Mint 21.1 (linuxmint 21.1)

olive-editor(_ZN5olive13crash_handlerEi+0x117)[0x559c7f744547]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f2107aa4520]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(+0xf14ea)[0x7f210860b4ea]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN21QPaintEngineExPrivateC1Ev+0xb3)[0x7f2108909bd3]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN18QRasterPaintEngineC2EP12QPaintDevice+0x23)[0x7f2108916b83]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZNK6QImage11paintEngineEv+0x82)[0x7f21086a4812]
/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPoint6QFlagsINS_14DrawWidgetFlagEEP8QPainterP21QWidgetRepaintManager+0x542)[0x7f2108da19d2]
/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x17d9f5)[0x7f2108d779f5]
/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x17e1f3)[0x7f2108d781f3]
/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1cc26c)[0x7f2108dc626c]

**Comment by techristian** [comment]
I think that is the end of my exploring for today. I'll jump back to the WIn10 side of this machine, back to Vegas 16

I may try this again on my next video.
Dan
