### ISSUE TITLE
[CRASH] at open .ove project  if the folder have accents letters (á é ã)

### ISSUE THREAD

**Issue by eliramalho** [olive-editor/olive#2178]
**Commit Hash** 
 Alpha | 1e3cf533

**Platform** 
Windows 11

**Summary**
In my Windows 11, in my language, portuguese, has by default the default folder for the desktop with the words ("área de trabalho").
I noticed that whenever my project it is in a folder with accents letters (á é ã ...) , the program does not open, crashes and closes immediately.

**Steps to Reproduce**

1. open the file
2. crash
3. close

<details><summary><strong>Crash Report</strong></summary><pre><code>

</code></pre></details>

**Additional Information**
THANK YOU SO MUCH FOR DELIVERING A GREAT LIGHTWEIGHT SOFTWARE - all my students love it !

**Comment by ThomasWilshaw** [comment]
It looks like you're using Olive 0.1 which is no longer supported. Please try upgrading to 0.2 (available on the website or GitHub actions)

**Comment by ThomasWilshaw** [comment]
The latest 0.2 should be pretty stable, if you do get any crashes or bugs you can report them here. Users have been successfully creating largish complex edits in 0.2 without any issues.

As I said 0.1 is unfortunately no longer supported
