### ISSUE TITLE
Overlay blend mode is incorrect

### ISSUE THREAD

**Issue by feeef** [olive-editor/olive#218]
When applying an overlay blending mode of a clip on top of a duplicate of the same clip (basically to do a bleach bypass effect) the result of the overlay blending mode is incorrect.

This is the original shot : 

![screenshot from 2018-12-29 11-38-13](https://user-images.githubusercontent.com/383399/50537386-1f832d80-0b5f-11e9-8476-a6daef3da115.png)

When overlaying on top of itself with Gimp or another program, I get the following result : 

![screenshot from 2018-12-29 11-38-38](https://user-images.githubusercontent.com/383399/50537401-4d687200-0b5f-11e9-81c1-d3cf961dde2b.png)

When overlaying on top of itself with Olive, I get the following result : 

![screenshot from 2018-12-29 11-38-56](https://user-images.githubusercontent.com/383399/50537411-6cff9a80-0b5f-11e9-9348-0d3727d63c15.png)

**Comment by itsmattkc** [comment]
I've been somewhat aware of this for some time, but haven't had the time to address it. It seems that most of these blending modes cannot be correctly recreated with `glBlendFunc` and the only way to produce the correct result is with a shader. I'll try to get around to that soon.

**Comment by itsmattkc** [comment]
This should be fixed in 6e1e342c1692501a954ecca996469c92a28bfbf4
