### ISSUE TITLE
[BUILD] Building with OTIO 0.10 its Impossible  

### ISSUE THREAD

**Issue by anomalocaris452** [olive-editor/olive#2196]
Host: Arch/Manjaro
OTIO 0.15
Branch Master

Logs
[97/468] Building CXX object app/CMakeFiles/libolive-editor.dir/core.cpp.o
FAILED: app/CMakeFiles/libolive-editor.dir/core.cpp.o 
/usr/bin/c++ -DKDDOCKWIDGETS_STATICLIB -DPA_HAS_JACK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DUSE_OTIO -I/home/senpai/funstuff/olive-git/src/olive/build/app -I/home/senpai/funstuff/olive-git/src/olive/app -I/home/senpai/funstuff/olive-git/src/olive/build/app/libolive-editor_autogen/include -I/home/senpai/funstuff/olive-git/src/olive/ext/core/include -I/usr/include/opentimelineio -I/home/senpai/funstuff/olive-git/src/olive/ext -I/home/senpai/funstuff/olive-git/src/olive/ext/KDDockWidgets/src/fwd_headers -isystem /usr/include/ffmpeg4.4 -isystem /usr/include/OpenEXR -isystem /usr/include/Imath -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtOpenGL -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtDBus -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -O2 -g -DNDEBUG -Wuninitialized -pedantic-errors -Wall -Wextra -Wno-unused-parameter -Wshadow -fPIC -std=c++17 -MD -MT app/CMakeFiles/libolive-editor.dir/core.cpp.o -MF app/CMakeFiles/libolive-editor.dir/core.cpp.o.d -o app/CMakeFiles/libolive-editor.dir/core.cpp.o -c /home/senpai/funstuff/olive-git/src/olive/app/core.cpp
In file included from /usr/include/opentimelineio/anyDictionary.h:6,
                 from /usr/include/opentimelineio/serializableObject.h:9,
                 from /usr/include/opentimelineio/serializableObjectWithMetadata.h:6,
                 from /usr/include/opentimelineio/timeline.h:6,
                 from /home/senpai/funstuff/olive-git/src/olive/app/dialog/otioproperties/otiopropertiesdialog.h:9,
                 from /home/senpai/funstuff/olive-git/src/olive/app/core.cpp:48:
/usr/include/opentimelineio/any.h:6:10: fatal error: any/any.hpp: No such file or directory
    6 | #include "any/any.hpp"
      |          ^~~~~~~~~~~~~
compilation terminated.
[98/468] Building CXX object app/CMakeFiles/libolive-editor.dir/libolive-editor_autogen/mocs_compilation.cpp.o
FAILED: app/CMakeFiles/libolive-editor.dir/libolive-editor_autogen/mocs_compilation.cpp.o 
/usr/bin/c++ -DKDDOCKWIDGETS_STATICLIB -DPA_HAS_JACK -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DUSE_OTIO -I/home/senpai/funstuff/olive-git/src/olive/build/app -I/home/senpai/funstuff/olive-git/src/olive/app -I/home/senpai/funstuff/olive-git/src/olive/build/app/libolive-editor_autogen/include -I/home/senpai/funstuff/olive-git/src/olive/ext/core/include -I/usr/include/opentimelineio -I/home/senpai/funstuff/olive-git/src/olive/ext -I/home/senpai/funstuff/olive-git/src/olive/ext/KDDockWidgets/src/fwd_headers -isystem /usr/include/ffmpeg4.4 -isystem /usr/include/OpenEXR -isystem /usr/include/Imath -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtOpenGL -isystem /usr/include/qt/QtConcurrent -isystem /usr/include/qt/QtX11Extras -isystem /usr/include/qt/QtDBus -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -O2 -g -DNDEBUG -Wuninitialized -pedantic-errors -Wall -Wextra -Wno-unused-parameter -Wshadow -fPIC -std=c++17 -MD -MT app/CMakeFiles/libolive-editor.dir/libolive-editor_autogen/mocs_compilation.cpp.o -MF app/CMakeFiles/libolive-editor.dir/libolive-editor_autogen/mocs_compilation.cpp.o.d -o app/CMakeFiles/libolive-editor.dir/libolive-editor_autogen/mocs_compilation.cpp.o -c /home/senpai/funstuff/olive-git/src/olive/build/app/libolive-editor_autogen/mocs_compilation.cpp
In file included from /usr/include/opentimelineio/anyDictionary.h:6,
                 from /usr/include/opentimelineio/serializableObject.h:9,
                 from /usr/include/opentimelineio/serializableObjectWithMetadata.h:6,
                 from /usr/include/opentimelineio/timeline.h:6,
                 from /home/senpai/funstuff/olive-git/src/olive/build/app/libolive-editor_autogen/AH4O2BKEHD/../../../../app/dialog/otioproperties/otiopropertiesdialog.h:9,
                 from /home/senpai/funstuff/olive-git/src/olive/build/app/libolive-editor_autogen/AH4O2BKEHD/moc_otiopropertiesdialog.cpp:10,
                 from /home/senpai/funstuff/olive-git/src/olive/build/app/libolive-editor_autogen/mocs_compilation.cpp:41:
/usr/include/opentimelineio/any.h:6:10: fatal error: any/any.hpp: No such file or directory
    6 | #include "any/any.hpp"
      |          ^~~~~~~~~~~~~
compilation terminated.

**Comment by Simran-B** [comment]
You seem to be missing dependencies. Anyway, the only  distro we target is CentOS 7.
