### ISSUE TITLE
[BUILD] KDDockWidgets submodule ID belongs to the olive fork of the repository

### ISSUE THREAD

**Issue by wferi** [olive-editor/olive#2203]
**Commit Hash** 
8ca16723613517c41304de318169d27c571b90af

**Platform** 
Debian unstable (but not relevant)

**Summary**
The `ext/KDDockWidgets` submodule points to commit 8d2d0a5764f8393cc148a2296d511276a8ffe559, which belongs to the https://github.com/olive-editor/KDDockWidgets fork, not to the official https://github.com/KDAB/KDDockWidgets repo, which is referenced by olive-editor's `.git/config` file. This breaks checking out the current source. Please fix the remote address or the commit ID as appropriate. Thanks.

**Comment by itsmattkc** [comment]
f1f2da9300fee26797e6afdaeafb3871c6fa5505
