### ISSUE TITLE
[EXPORT] GIF not supported

### ISSUE THREAD

**Issue by lines-of-codes** [olive-editor/olive#2204]
**Commit Hash** 
f1f2da93

**Platform** 
Windows 11 22H2 (OS Build 22621.1413)

**Summary**
This is really not an issue, but a feature request. Basically:

The GIF format is not supported in Olive 0.2

**Additional Information / Output**
It used to be supported in Olive 0.1 but it seems like it is removed in Olive 0.2

**Comment by AGI-THB** [comment]
MattKC wrote on 03/01/2023:

"0.2 does not export GIF and is unlikely to ever. It's an obsolete format and has too much complexity/too many variables to get high quality results that it's not really worth implementing. I recommend using a dedicated tool for the job like Photoshop or FFmpeg."
