### ISSUE TITLE
[UI] No drag and drop

### ISSUE THREAD

**Issue by ralosch** [olive-editor/olive#2207]
**Commit Hash** 

**Platform** 
openSuse tumbleweed latest Gnome

**Summary**
Hello
Drag and drop does not work in opensuse tumbleweed.
Olive starts normally. Import also works, but I can't drag any content to the timeline. When I click on it, a prohibition symbol appears on the mouse.

**Additional Information / Output**
AppImageLauncher:12437): GdkPixbuf-CRITICAL **: 09:07:26.850: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
[INFO] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[DEBUG] Extracting default OCIO config to "/home/robert/.cache/olivevideoeditor.org/Olive/ocioconf"
[INFO] Using Qt version: 5.15.2
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
[INFO] Setting output audio device to default
[INFO] Setting input audio device to default
[DEBUG] Using graphics driver: AMD

**Comment by ralosch** [comment]
Same with shotcut appimage.
Maybe an tumbleweed bug.

**Comment by quazar-omega** [comment]
@ralosch Did you manage to get it working then?  
I'm having the same issue both under GNOME Wayland and GNOME Xorg with this output in the latter:
```
$ ./Olive-7fa69ea5-Linux-x86_64.AppImage 
[DEBUG] Extracting default OCIO config to "/var/home/user/.cache/olivevideoeditor.org/Olive/ocioconf"
[INFO] Using Qt version: 5.15.2
ALSA lib pcm_dsnoop.c:566:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
[INFO] Setting output audio device to default
[INFO] Setting input audio device to default
[DEBUG] Using graphics driver: Intel
[WARNING] libpng warning: iCCP: known incorrect sRGB profile
```
