### ISSUE TITLE
AppImage does not start, fribidi_get_par_embedding_levels_ex

### ISSUE THREAD

**Issue by probonopd** [olive-editor/olive#221]
An user on Twitter reports:

`./Olive-5e81565-x86_64.AppImage ./Olive-5e81565-x86_64.AppImage: symbol lookup error: /lib64/libpango-1.0.so.0: undefined symbol: fribidi_get_par_embedding_levels_ex tnks`

Details requested.

I cannot reproduce this on `xubuntu-18.04-desktop-amd64.iso`.

**Comment by probonopd** [comment]
According to https://github.com/knapsu/plex-media-player-appimage/issues/14#issuecomment-408940087, not bundling `libfribidi.so.0` may solve this. Can it be taken for granted to be there on each target system?

**Comment by itsmattkc** [comment]
I haven't seen this before either. Clearly some kind of dependency discrepancy of some kind, but without being able to recreate it, it'd be tough to figure out the root cause.

**Comment by probonopd** [comment]
The user reports this happens on Fedora, unspecified version.

**Comment by itsmattkc** [comment]
Confirmed, this issue occurs on the latest version of Fedora.

**Comment by probonopd** [comment]
So the only question left is whether we can blacklist Fribidi and assume it is "there" on all target systems (distributions). I am not sure on this one yet.

**Comment by itsmattkc** [comment]
Doing the above solution on Ubuntu (18.04) and Mint (19.1) have no effect on Olive running, so it's looking like we should be able to, but not 100% on other distros/older versions yet.

**Comment by Chaz6** [comment]
I have the same issue on CentOS 7.6.1810.

**Comment by probonopd** [comment]
@Chaz6 does the workaround work for you, too?

**Comment by probonopd** [comment]
I have added `libfribidi.so.0` to the [excludelist](https://github.com/AppImage/pkg2appimage/blob/master/excludelist) for now, please let me know if this causes issues going forward.

**Comment by itsmattkc** [comment]
The AppImage now runs as expected on Fedora (and presumably CentOS too). I guess we'll re-open this if anything else related to this comes up.

**Comment by Chaz6** [comment]
I can confirm the latest release runs correctly on CentOS. Thank you.
