### ISSUE TITLE
[UI] File==>Import Wrogn in turkish

### ISSUE THREAD

**Issue by DrVektor** [olive-editor/olive#2217]
**Commit Hash** 

**Platform** < Windows 10 -->

**Menu turkish language import = Dışaaktar is wrong should be içeaktar. "iç" is "in", "aktar" is "transfer" in-transfer logical. Forexample intransfer in turkish içe-aktar or merged içeaktar revesed dışa-aktar outtransfer , alternative of dışaaktar "yolla" like send in english. 
![olivegithub](https://user-images.githubusercontent.com/105983978/234430674-7c99cb8f-c66f-4ab2-8338-47973828188d.png)
**

**Additional Information / Output**

**Comment by itsmattkc** [comment]
All translations are community contributed. We have no translators on staff. If you wish to issue a correction, please make it yourself. Instructions can be found here: https://github.com/olive-editor/olive/wiki/Translations
