### ISSUE TITLE
[PROJECT] Editor crashed and can't locate resources anymore

### ISSUE THREAD

**Issue by Notplayingallday383** [olive-editor/olive#2220]
**Commit Hash** 
cce44e40

**Platform** 
Windows 11 Version 22H2 (OS Build 22621.1555)

**Summary**
So today I was working on a new youtube video in Olive Video Editor and then it randomly crashed and when I reopened it and loaded the project file it said that all the video resources weren't found even though the file names were never changed and when I click the chose button to select where its located it says that the file name doesn't exist even though the file isn't there.

**Additional Information / Output**
![image](https://user-images.githubusercontent.com/72810050/235312530-7d3fda91-4792-4e94-9ed4-2313a1145456.png)
![image](https://user-images.githubusercontent.com/72810050/235312579-1ce5d004-5e71-4b9c-965e-29357f0367b5.png)

**Comment by itsmattkc** [comment]
What do you mean it's the same file? In the screenshot, they have very clearly different filenames.

**Comment by Notplayingallday383** [comment]
> What do you mean it's the same file? In the screenshot, they have very clearly different filenames.

The thing is the file **USED** to be the same but idk if olive or windows for some reason changed the file name because it is not being recognized

**Comment by Notplayingallday383** [comment]
oh wait I found the issue turns out I selected the wrong video directory my bad
