### ISSUE TITLE
[UI] 

### ISSUE THREAD

**Issue by bruhmanshit** [olive-editor/olive#2224]
**Commit Hash** Olive 0.2.0 starts without a interface.

**Platform**  Windows 10

**Summary**
![изображение_2023-05-07_121443067](https://user-images.githubusercontent.com/132813566/236668722-eaefb24f-67fc-419c-ade8-8d1bea86bab7.png) I can press on the interface but cant see it. I can create a new project etc. How do i fix this?

**Additional Information / Output**

**Comment by Quackdoc** [comment]
not able to replicate, can you

A) try and redownload the latest version?
B) post specs and system info?

**Comment by bruhmanshit** [comment]
A) same thing
B)Windows 10 64x, Intel(R) Celeron(R) CPU B815 @ 1.60hz
RAM - 8 GB
Video card: 512 MB

**Comment by Quackdoc** [comment]
it's possible that the specs are simply too low to run olive. olive has a minimum req of OGL 3.2 and I believe sandybridge doesn't support all of the features so it's possible that your igpu doesn't support olive. even if it didn't though, olive has no hardware accelerated video encoding or decoding at the moment, so chances are olive wouldn't be very usable regardless.

**Comment by itsmattkc** [comment]
Yeah this is almost certainly a GPU that doesn't support OpenGL 3.2. Olive 0.2 cannot run on your system, sorry.

**Comment by Simran-B** [comment]
Especially the first generations of Intel HD graphics are known to not support the minimum required OpenGL version, e.g. the Intel HD graphics 2000 and 3000. The Celeron B800 doesn't, for example:

https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html
