### ISSUE TITLE
[UNSUPPORTED] 

### ISSUE THREAD

**Issue by marcosdebrito** [olive-editor/olive#2231]
Build Environment: x86_64 (x86_64-little_endian-lp64)
Run Environment: x86_64
Kernel: linux 5.10.0-23-amd64
System: Debian GNU/Linux 11 (bullseye) (debian 11)

olive-editor(_ZN5olive13crash_handlerEi+0x112)[0x55744bfb0942]
/lib/x86_64-linux-gnu/libc.so.6(+0x38d60)[0x7f6f45df5d60]
/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZNK18QThreadStorageData3getEv+0x3b)[0x7f6f4638de9b]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN14QOpenGLContext14currentContextEv+0x28)[0x7f6f46985ea8]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN19QOpenGLContextGroup19currentContextGroupEv+0x9)[0x7f6f46986e79]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN13QOpenGLBuffer4bindEv+0x29)[0x7f6f46cd70e9]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN21QOpenGLTextureBlitter4bindEj+0x4f)[0x7f6f46cfb3ff]
/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN21QPlatformBackingStore15composeAndFlushEP7QWindowRK7QRegionRK6QPointP20QPlatformTextureListb+0x1af)[0x7f6f46c7d76f]
/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x60767)[0x7f6f32480767]
/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x16fd23)[0x7f6f4703ad23]
Version: 
Signal: 11

**Comment by elsandosgrande** [comment]
Whilst local builds of Olive aren't generally supported, it would make it likelier that your report would be looked at if you provided proper information regarding your issue. 

What were you doing when your local build crashed? Have you tried reproducing the issue with an AppImage? What compiler did you use, version included, and with which compiler flags did you build Olive?
