### ISSUE TITLE
[EXPORT] my olive does not export the videos because the files are "non-existent"

### ISSUE THREAD

**Issue by cabriote** [olive-editor/olive#2237]
**not found** 

**WINDOWS 10** 

**MEU OLIVE NÃO ESTÁ EXPORTANDO OS VÍDEOS PORQUE OS ARQUIVOS ESTÃO SUPOSTAMENTE INEXISTENTES**

![imagem_2023-06-13_124649696](https://github.com/olive-editor/olive/assets/136492132/d7bb8430-6fc6-45da-8a76-f32382199805)

**nothing**

**Comment by itsmattkc** [comment]
There's probably something wrong with the path, like the directory you're trying to save to doesn't exist (Olive will not create directories for you)

**Comment by cabriote** [comment]
> There's probably something wrong with the path, like the directory you're trying to save to doesn't exist (Olive will not create directories for you)

how to create a directory?
