### ISSUE TITLE
Audio/Video tracks separator position isn't saved in the project [UI] 

### ISSUE THREAD

**Issue by Triffen** [olive-editor/olive#2243]
**Commit Hash** 
Olive 0.2.0-70690c5b

**Platform** 
Manjaro Linux, X, KDE

**Summary**
After reopening a saved project, Audio/Video track separator returns to its default place in the centre, while I keep it near the bottom in my projects. I'd like this position to be saved and restored.

**Additional Information / Output**
![image](https://github.com/olive-editor/olive/assets/4696816/e2b0be23-6c7a-4fd6-a91c-fa1e61b9a46e)

**Comment by ThomasWilshaw** [comment]
A lot of UI layout is not saved at the moment and isn't a priority right now (see #1231 )
