### ISSUE TITLE
[COLOR] Transparent .MOV's transparency doesn't work/GIFs no longer work

### ISSUE THREAD

**Issue by Awesomeplayer98** [olive-editor/olive#2244]
**1687a721**

**Windows 10**

**I wanted to put a meme in my video and found the following:**
**1. Gifs don't work anymore and it tried to put in a million images stacked on top of each other for me to edit frame by frame,**
**2. Movs with transparent backgrounds don't have transparency in Olive.**

**This isn't a big deal and I am not mad. I know it's kind of a new feature sort of thing for the mov, so you can take your time! Now I have the frame-by-frame of that gif saved so I can copy and paste it! Thank you!**

**Comment by ThomasWilshaw** [comment]
Can you provide exmaple footage of a transaprent .mov file?

Olive 0.2 doesnt support GIFs

**Comment by Wert688** [comment]
Why doesn't Olive 0.2 support GIFs, when 0.1 did? It's very inconvenient.

**Comment by Awesomeplayer98** [comment]
I also miss rotatable text

**Comment by Woynert** [comment]
As a workaround use ffmpeg to convert the **transparent** GIF to a WEBM replacing the transparent color with GREEN so it can be Chroma Keyed.

```sh
INPUT=binding-of.gif;
DURATION=$(ffprobe -v error -select_streams v:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 $INPUT);
ffmpeg -i $INPUT -f lavfi -i color=0x00FF00 -filter_complex "[1:v]trim=duration=$DURATION[bg]; [bg][0:v]scale2ref[bg][gif]; [bg][gif]overlay=shortest=1:format=auto" green.webm
```

[Screencast.](https://www.youtube.com/watch?v=61bo_kdgWUU)

**Comment by Awesomeplayer98** [comment]
Yeah tbh I stopped using Olive. It's a great free option and impressive that a bunch of college students made it, but I realized I get Premiere Pro for free with my school account so...

**Comment by Awesomeplayer98** [comment]
Close with comment
