### ISSUE TITLE
[UI] Proxy generation option missing?

### ISSUE THREAD

**Issue by ericswpark** [olive-editor/olive#2252]
**Commit Hash** 

1687a721

**Platform** 

Windows 11 21H2

**Summary**

The proxy generation option seems to be missing in the project subwindow. I've seen tutorials on YouTube that mention this button -- is it just not implemented in 0.2.x?

**Additional Information / Output**

Here's what I get when I right-click on a clip in the "Project" subwindow:

![image](https://github.com/olive-editor/olive/assets/13326074/065ce7f5-3dba-4457-b6c7-d359c0f21cea)

**Comment by Quackdoc** [comment]
pre-cache is more or less the current implementation of a proxy, but if you need something more flexible you can use the replace footage function for now. this is what I Personally do.
