### ISSUE TITLE
[UI] Volume reduction reduces visual waveform on clip (bad UX)

### ISSUE THREAD

**Issue by Avispa** [olive-editor/olive#2257]
### System
**Commit Hash** Olive 0.2.0-7fa69ea5
**Platform** Windows 10

### Currently
Reducing the  volume of an audio clip also reduces the drawn waveform in the timeline clip hence reducing/destroying the benefit of having a graphical waveform in the first place. (Similarly for increasing the volume of course.)

### Expecting
1. Using maximum real estate of my display/UI by leaving scale of waveform untouched!
2. If wished, different graphical indicator like a horizontal line on the clip/waveform or maybe to different colours on the waveform top/bottom part (similar to a line just visual less distructive -- since a line would potentially cover important parts)

### Easy solution/suggestion for the moment
Almost any other effect is also not visualized on the timeline clip so I would suggest to disable this "feature" for the moment till an overall UI-solution is found to bring back the value of the graphical waveform.

**Comment by ThomasWilshaw** [comment]
Seeing as this is a feature request rather than a bug I'm closing for now. We'll hopefully eb able to look at this sort of thing when live is further along and more stable.
