### ISSUE TITLE
Auto-Resize proxy imported clips in "replace clips using this media" option?

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#226]
First time posting the issue for the open-source video editor and I am aware of the Auto-Scaling Issue that was resolved but this is somewhat different.

I was testing out importing footage into Olive such as the highest resolution 4K UHDtv resolution, and I do love how Olive gives the option to "Replace Clips Using this Media" option, this makes the use of editing with Proxy Videos (Small-Sized videos for smooth playback) possible, however, upon replacing clips:

![image](https://user-images.githubusercontent.com/5027750/50569863-9fa7bf80-0d26-11e9-832a-7ee7fac6c8fe.png)
Using Blender's generated colorgrid as an example.

I thought that the "fit" option wasn't working until I realize its because the sequencer's properties settings that doesn't allow the proxy videos to fit/fill the viewing canvas completely, and the anchor point hasn't changed.

I was thinking if possible that in the "Replace Clips Using this Media" option, could there be an option to recenter the anchor point at the center of the _proxy_ footage then re-size the proxy to the same size the sequencer's _resolution size_ was in the sequencer properties?

**Comment by itsmattkc** [comment]
Auto-centering anchor point added to 69a33c756cb5bdc5683dc899bb40137cff042e29
