### ISSUE TITLE
[PACKAGING] AppImage autoupdate

### ISSUE THREAD

**Issue by RafaelLinux** [olive-editor/olive#2267]
**Commit Hash** 
1687a721

**Platform** 
Linux

**Summary**
As an AppImage (Linux) user, I find more and more AppImages that auto-update itself (Upscayl, Ossia and others). As Olive is updated often (always to get a better application) would be very useful for AppImage users to have an auto-update AppImage of Olive.

**Comment by ThomasWilshaw** [comment]
Given Olive is still not stable this is outside the scope of what we're looking at just now so I'm going ot close this issue. Hopefully once Olive is stable we can look at features like this.
