### ISSUE TITLE
[UI] [EDIT]Feature requests: Allow multiple videos to be editted at once after a right click hold and drag

### ISSUE THREAD

**Issue by metapea** [olive-editor/olive#2270]
**Commit Hash**
1687a721

**Platform** 
Win7

**Summary**
After a left click hold and drag in timeline, it would nice to use the video nodes gui to change scale, rotation and the other options to the selected videos all at once. 

**Additional Information / Output**

**Comment by ThomasWilshaw** [comment]
The tracker is for bugs/issues not feature requests so I'm closing this for now. You can view multiple clips at once and copy/paste transforms etc. between them
