### ISSUE TITLE
[RENDER] Scopes have transparent backgrounds, and histogram is in bottom left quadrant 

### ISSUE THREAD

**Issue by Quackdoc** [olive-editor/olive#2275]
**Commit Hash** 
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794 (ts-timeline plus my own commit to get it building again)

**Platform** 
Wayland arch

**Summary**
 The scopes define *_scale = 0.80f which makes the fragment shader scale the entire texture down, and I presume QT is treating that as alpha = 1 causing the transparent background again. 

as for this histogram being in the bottom left quadrant, I have not investigated

**Comment by ThomasWilshaw** [comment]
I'm going to close this as the issue tracker is really for `master` branch commits only. Please feel free to tass this to the `ts-timeline` PR if it's still an issue. Thanks
