### ISSUE TITLE
Random Highlight selections in Export Window

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#228]
I noticed when I was pressing tab to go to the next option space in Export Window, the highlight would go to a next option, out-of-order. Say I'm at "Width" and pressing tab sends me to "Height". That didn't happen, but what occurred next was that the highlight is now at Quality. Pressing tab again sends highlight to Framerate, Audio checkbox... Kept repeating before highlight was now at Width.

The tab queue in the Export Window is out of order. Just a heads up.

**Comment by itsmattkc** [comment]
This was recently broken by a fairly large refactoring of the UI backend. Fixed in f4715fdf99971747ba303281b64f5c84d16cb68c
