### ISSUE TITLE
[UI] Native styling is gone?

### ISSUE THREAD

**Issue by omentic** [olive-editor/olive#2288]
**Commit Hash** 55eedbfc

**Platform** Arch Linux 6.5.7

**Summary**

After updating from a quite old Olive version, the native styling is gone. Only Olive Dark and Olive Light are available in the menu. I can't seem to find a native option. Is this a regression, or were the settings moved, or were the settings removed?

**Additional Information / Output**

**Comment by AngeloFrancabandiera** [comment]
FWIW, looking the source code, I can confirm that "Dark" and "Light" are the only available style. Don't know the reason of this choice.

**Comment by Simran-B** [comment]
Some 0.1.x version apparently had an option for using native styling:
https://github.com/olive-editor/olive/issues/625#issuecomment-473518483

In 0.2.x, this is no longer the case. I can't find the comment right now but Matt stated that Olive opts for a consistent style across OSes. Another reason might be that supporting native styling is a chore.

**Comment by omentic** [comment]
I strongly implore you to reconsider :slightly_frowning_face: 

It's very unusual for Qt apps to not support native styling, and sucks for users.

**Comment by omentic** [comment]
I strongly implore you to reconsider 🙁

It's very unusual for Qt apps to not support native styling and sucks for users. Everything else on my computer (except Audacity) follows a consistent theme.
