### ISSUE TITLE
[PROJECT] Monero (XMR) Donations

### ISSUE THREAD

**Issue by Killercat103** [olive-editor/olive#2289]
**Commit Hash** 

**Platform** Web

**Summary** Please add the possibilty to contribute to the project to Monero.

**Additional Information / Output** I and possibly many other would be interested to be able to donate to the project while maintaining a level of privacy and using foss software. I personally am not interested in ever signing up for Patreon as it collides with my personal values.

**Comment by Simran-B** [comment]
You can also use PayPal, see https://olivevideoeditor.org/donate

There are currently no plans to add other options.
