### ISSUE TITLE
MKV file format corrupts exported video

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#229]
This was discovered while dealing with issue #227, when I exported a video in the MKV format through the Export Window, I opened up the video in VLC to find that the video is unplayable, just a black screen. Then I played the video in Windows Media Player to find that the frames go very fast than the original timeline limit, and the picture becomes glitched/corrupted.

When selecting MKV as a file format, it simply corrupts the exported video after rendering.

**Comment by feeef** [comment]
I had the same issue with WebM export (both VP8 and VP9).

**Comment by itsmattkc** [comment]
This should be fixed in fcaed728657c75e38cef98df723346059b698c89 (both MKV and WebM, and any others affected by this). Test it out and let me know!

**Comment by Corruptinator** [comment]
I'll let you know how the export goes soon.

**Comment by itsmattkc** [comment]
Do you need an updated exe for testing?

**Comment by Corruptinator** [comment]
sure.

**Comment by Corruptinator** [comment]
Sorry for non response, computer was acting up.

**Comment by Corruptinator** [comment]
Looks like its working, thanks!
