### ISSUE TITLE
Clicking "OK" in the Sequencer Properties crashes Olive

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#230]
Olive crashes whenever I attempt to click ok in the sequencer properties (Right clicking any sequencer project item, before clicking "properties") menu after making a few adjustments. The software completely freezes for a moment, then the program completely terminates itself and leaves me at the computer's desktop.

**Comment by itsmattkc** [comment]
Just to be clear, you're talking about this dialog?
![image](https://user-images.githubusercontent.com/34096995/50593520-c3b4fd80-0eec-11e9-8c11-935ff2b2baf0.png)
If so, I haven't been able to recreate any crash from it. Is this the same build I sent for #227?

**Comment by Corruptinator** [comment]
Yup. Same build.

**Comment by Corruptinator** [comment]
It does, this new build works.

**Comment by itsmattkc** [comment]
Awesome, thanks for the bug report
