### ISSUE TITLE
[BUILD] Compilation instructions cannot be opened.

### ISSUE THREAD

**Issue by 406114033** [olive-editor/olive#2305]
**Commit Hash** 

**Platform** 
 I want to compile and run under windows.

**Summary**

**Additional Information / Output**

**Comment by AngeloFrancabandiera** [comment]
You can file build instruction at https://olivevideoeditor.org/compile
Not quite clear what you "cannot open".

**Comment by 406114033** [comment]
Yes, that's it. It didn't open before.https://olivevideoeditor.org/compile.
Thank You.
