### ISSUE TITLE
[Feature request] Icons on project pane

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#231]
Hi,

I would find a great UI improvement and, so that, a way to speed up the work, to add some icons to the Project panel.
<img width="396" alt="buttons" src="https://user-images.githubusercontent.com/5942369/50601126-94ce6580-0eb3-11e9-8d63-6564ab0d9a57.png">
Right click button is not very handy for this kind of tasks. So, I would suggest to create buttons for:
- tree view and icon view
- new, open and save Project
- Import (anyway the double click into anywhere of the panel works perfectly)
- new sequence
- new folder
- undo/redo

Thanks

**Comment by itsmattkc** [comment]
I don't have icons for them yet, but I've added an optional toolbar with most of the functionality you list in 7857b064ff4e1183e586ab5d84960b7642c16d3c

**Comment by pgilfernandez** [comment]
If you agree I could collaborate the project by creating a full set of icons, I’m designer, it would be a pleasure.

**Comment by itsmattkc** [comment]
Sure, that sounds great to me.
