### ISSUE TITLE
[Feature request] Dropdown button for "new tittle, solid color, bars, etc..." in Project pane

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#232]
Hi,

I think it would be more consistent to have the "new title, solid color, bars,... etc" (plus icon button now on Timeline toolbar) in the Project pane. Also, when one of these objects are created they became listed in the hierarchy, that way, they would be **reusable and easy to find and modify**.

Thanks!

**Comment by DaniSeeh** [comment]
I definitely agree. I actually am having trouble understanding how titles work presently to be honest haha.

**Comment by itsmattkc** [comment]
This will be addressed in the node rewrite.
