### ISSUE TITLE
AppImage does not support Wayland

### ISSUE THREAD

**Issue by gnolooo** [olive-editor/olive#2320]
**Commit Hash** 
10ce5fb, but also many previous versions.

**Platform** 
Arch Linux

**Summary**
Basically, when I use Olive AppImage, it opens with XWayland even though I've set the correct environment variable needed by Qt on Wayland (`env QT_QPA_PLATFORM=wayland`, with which I successfully launch almost every other Qt application).
I know that building from source does work, but I can no longer build it (I've not managed a single successful build in months - different issue, check #2319).

**Comment by Simran-B** [comment]
Yes, the AppImage does not support Wayland. In fact, the Qt build created by the ASWF that is used in the CI does not include the qtwayland module, so there isn't any Wayland library for Qt to begin with (whether the AppImage bundling would pick it up is another question). It doesn't seem to be possible to build the Qt Wayland module separately, or there is at least some problem that makes the qmake configuration fail to detect Qt Wayland Client/Compositor and wayland-egl, even though the dependencies seem to be installed. So, there is no Wayland support (also see #1630) and there are no plans to support it in the current code base.

**Comment by Simran-B** [comment]
I think the most reasonable move with this code base would be to migrate to Qt 6 as that comes with a much further developed and actually maintained Wayland module. With the obsolete Qt 5, problems are to be expected. I'm not sure how much knowhow is needed with a framework like Qt to make it work in the end, as it should take care of most of the things. Anyway, this code base is essentially unmaintained and therefore there are also no plans to work on Wayland support. A video editor is a huge undertaking and too big for the currently available resources. There is a chance of a restart (narrower scoped and rolling less custom lower level things) with a different technical base without Qt and a framework that potentially supports Wayland out of the box and might make AppImages unnecessary.

**Comment by gnolooo** [comment]
I used to build it from source exactly because of doing so, I could use it on Wayland without any problem. Now, I cannot build it (mentioned the issue above) and so I can't use it on Wayland.

**Comment by FlyingSaturn** [comment]
I can try to help you all, but an important question: are you all active?

The thing is, it has been proposed that Fedora 43 GNOME will totally eliminate the support of X11 and will go on with Wayland. Here's the discussion: https://discussion.fedoraproject.org/t/f43-change-proposal-wayland-only-gnome-self-contained/150261/5

**Comment by RafaelLinux** [comment]
> I can try to help you all, but an important question: are you all active?
> 
> The thing is, it has been proposed that Fedora 43 GNOME will totally eliminate the support of X11 and will go on with Wayland. Here's the discussion: https://discussion.fedoraproject.org/t/f43-change-proposal-wayland-only-gnome-self-contained/150261/5

But I'm using Olive booting openSUSE in Wayland, and can execute and use Olive w/o issues.
