### ISSUE TITLE
[REQ] fix GH license file

### ISSUE THREAD

**Issue by forart** [olive-editor/olive#2328]
**Commit Hash** 

**Platform** 

**Summary**

**Additional Information / Output**

---
(PREAMBLE: Sorry, dunno how to fit this issue in template...)

Hi there, 1st of all an heartfelt thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://forart.it/HyMPS) (under the [VIDEO category](https://github.com/forart/HyMPS#-1) \ [Editors page](https://github.com/forart/HyMPS/blob/main/Video/Editors.md#--) \ [Non-Linear Editors subsection](https://github.com/forart/HyMPS/blob/main/Video/Editors.md#non-linear-editors-)), can you please fix the license file for it ?

Although it may sounds like a minor aspect, license file uncompliance causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/olive-editor/olive/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/olive-editor/olive/?label=LICENSE)

Anyway you can easily set a compliant one through the GH's license wizard tool.

Last but not least, let us know - in your opinion - how we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by Simran-B** [comment]
This was apparently caused by minor differences in the GPL license text, namely URLs (HTTPS instead of HTTP, one updated link)

**Comment by forart** [comment]
Works now, thanks !
