### ISSUE TITLE
[EDIT] Will the set to frame size feature come?

### ISSUE THREAD

**Issue by ahmetcanisik** [olive-editor/olive#2338]
**Commit Hash** 
0.2.0-f7e1bff0

**Platform** 
Windows 11

**Summary**
Hello, I wanted to ask if the set to frame size feature in Premiere Pro can also come to Olive Editor. The reason for this request is to eliminate unnecessary efforts. I say unnecessary effort because first adding the crop and then adjusting the size with transform > scale does not work exactly and it is a bit annoying to do it every time. If it comes, the use of olive will be even better. Thank you for reading.

**Additional Information / Output**
My Windows 11 pro build version: 10.0.2631 Build 22631

**Comment by itsmattkc** [comment]
Set "auto-scale" in the transform node to "fit" or "fill".

**Comment by ahmetcanisik** [comment]
It's a screenshot from the node editor, but I couldn't find any fit or fill option under auto-scale.
![Ekran görüntüsü 2024-07-17 222744](https://github.com/user-attachments/assets/5732006e-3a63-41f0-9178-7713fd1ee0ae)
