### ISSUE TITLE
[BUILD] Olive AppImage not running

### ISSUE THREAD

**Issue by SamuraiDestroy** [olive-editor/olive#2339]
**Commit Hash** f7e1bff0 and 10ce5fbd

**Platform** Ubuntu 24.04

**Summary**
Attempting to run the AppImage installed from the .zip file results in nothing happening.

**Additional Information / Output**
Not sure if this is the correct issue category, also could affect more versions, haven't tested though.

**Comment by Simran-B** [comment]
Did you set the file execute permission for the AppImage with `chmod +x`?

**Comment by RafaelLinux** [comment]
I tried it when released (may 2024 was the last) and worked.

**Comment by SamuraiDestroy** [comment]
> Did you set the file execute permission for the AppImage with `chmod +x`?

I set executable to true in the properties, are those the same?

**Comment by RafaelLinux** [comment]
> > Did you set the file execute permission for the AppImage with `chmod +x`?
> 
> I set executable to true in the properties, are those the same?

Yes, it's exactly same result doing from console or from properties window.

**Comment by SamuraiDestroy** [comment]
Update: Turns out I needed to install a library to install AppImages.

**Comment by RafaelLinux** [comment]
You must take into account AppImages are simply "executables", they are no installed. What libraries were they? It will help other users with same issue, don't forget it!!!
