### ISSUE TITLE
Screenshot on website

### ISSUE THREAD

**Issue by eszlari** [olive-editor/olive#234]
It would be nice to have a screenshot on the website that could be referenced in the appdata file:
https://github.com/olive-editor/olive/blob/master/packaging/linux/org.olivevideoeditor.Olive.appdata.xml

**Comment by itsmattkc** [comment]
Added at
https://olivevideoeditor.org/img/screenshot.png
https://olivevideoeditor.org/img/screenshot.jpg

In quarter resolution:
https://olivevideoeditor.org/img/screenshot.small.png
https://olivevideoeditor.org/img/screenshot.small.jpg

**Comment by eszlari** [comment]
Since the screenshot on https://flathub.org/apps/details/org.olivevideoeditor.Olive has not been updated yet, there seems to be a problem. I think the screenshot is too large:
```
$ appstream-util validate org.olivevideoeditor.Olive.appdata.xml

• attribute-invalid     : <screenshot> width too large [https://olivevideoeditor.org/img/screenshot.jpg] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [https://olivevideoeditor.org/img/screenshot.jpg] maximum is 900px
```
So could you please, upload a screenshot with a size of 1600x900?

**Comment by itsmattkc** [comment]
Sorry about the delay:
https://olivevideoeditor.org/img/screenshot.1600.png
https://olivevideoeditor.org/img/screenshot.1600.jpg
