### ISSUE TITLE
If a title, solid bar, etc. is used in the project when quitting the app it crashes

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#240]
Hi,

If your project has added a title, solid bar, etc. when you quit the app it crashes. It's not a big problem if you have saved your work but any preferences modified are not saved due to this crash...
Tried on macOS

Thanks

**Comment by itsmattkc** [comment]
A possible fix for this was merged into `master` in 69a33c756cb5bdc5683dc899bb40137cff042e29. Test it out and see if it still affects you.

**Comment by pgilfernandez** [comment]
Yes, it seems to work fine now =)

Thanks!
