### ISSUE TITLE
[Feature Request] Be able to change framerate of a clip by editing properties

### ISSUE THREAD

**Issue by PostPollux** [olive-editor/olive#241]
It would be awesome if we could change the framerate of an imported clip when we edit the porperties of that clip.
I tried to import an image sequence which worked well, but it was imported with 25 fps while I need it to be 60. Unfortunately I didn't find a way to change that. So I guess it's not yet implemented.

Specs:
Olive b828171, Linux Manjaro, Intel I7 8550U, UHD620

**Comment by itsmattkc** [comment]
Technically, the way to do this now is to put it into a sequence and use speed/duration to change the frame rate. But for image sequences specifically, perhaps it'd be neater to be able to change the source frame rate specifically.

**Comment by alcomposer** [comment]
frame-rate conform eg: 50p played at 24p is also a good function for both image sequence and media.

**Comment by PostPollux** [comment]
Yes, I think especially for image sequences it would be neater if we could somewhere define the fps of the sequence before putting it into the timeline. It feels wrong to me that I can't have the "correct" fps for my image sequence in the project view and that I would have to adjust it each time I throw it into the timeline.
I think the "properties..." dialog from the context menu of the project view would be the best fit for it.

**Comment by alcomposer** [comment]
I think it would also be good to be able to redefine the conformed / speed value as well. 

But remember: conform is not speedchange. We are asking the software to play back a FPS at another frame-rate. So 50p turns into 25p but half speed. 

These functions are all connected with retiming, so I think that they belong together.

**Comment by itsmattkc** [comment]
Should be fully functional in 90ee9ecb4ec5b2d1fc91bcfa9a807e8ef61f1a01

**Comment by PostPollux** [comment]
Wow! Now that was quick! I just tested it. Works flawlessly! Thank you very much. You are the man!

**Comment by itsmattkc** [comment]
Awesome, glad to hear!
