### ISSUE TITLE
A request for a real-time marker mode

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#244]
The current marker process:

1. Press **M**
2. Pop-up window for name placement
3. Marker inserted

Theoretical optional mode for instant markers
1. Press **M**
2. Marker inserted

This option would be useful for the people who make fast montages or the ones too lazy to name their markers

**Comment by itsmattkc** [comment]
Added in cdd01db9abd651bb09ec89e1bc8f6258d8321762 in Tools > "Ask For Name When Setting Marker"
