### ISSUE TITLE
Cannot export video

### ISSUE THREAD

**Issue by MelanX** [olive-editor/olive#246]
If I want to export my video there is an error after a few seconds:
`Export failed - failed to send frame to encoder (-542398533)`

Details:
- 4K .MOV file
- just imported and instant go to export (because I don't know how to edit a video :D)

If more information needed, just ask :)

**Comment by itsmattkc** [comment]
Hi, this sounds like the same issue as #227, are you also using the Windows build from the website?

**Comment by MelanX** [comment]
Yes I downloaded the build from the website for Windows a few days ago.

**Comment by itsmattkc** [comment]
I believe it's the same issue. Since it affects so many people, I've updated the Windows build on the website to fix this bug. Try that one and it should be fixed.
