### ISSUE TITLE
Video after export async

### ISSUE THREAD

**Issue by MelanX** [olive-editor/olive#249]
Maybe I'm exporting wrong but every video I export isn't sync. I import a .MOV in UHD with 60 FPS (footage by iPhone 8) and exporting is the default settings:
Format: MPEG-4 Video
Range: Entire Sequence
Video
Codec: libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
Width: 3840
Height: 2160
Frame Rate: 60,00
Compression Type: Quality-based (Constant Rate Factor)
Quality (CRF): 36,00

Audio
Codec: AAC (Advanced Audio Coding)
Sampling Rate: 44100
Bitrate (Kbps/CBR): 256

computer:
CPU: AMD FX 7350
GPU: GeForce GTX 950
RAM: 16 GB DDR3

**Comment by itsmattkc** [comment]
Hi which version of Olive is this? Which platform and is this a build from the website or did you compile from source?

**Comment by itsmattkc** [comment]
I recently revamped the export timings for #229, let me know if that solves this issue (just replace the exe with this one)
[olive-editor.zip](https://github.com/olive-editor/olive/files/2729982/olive-editor.zip)

**Comment by MelanX** [comment]
That fixed the problem, thank you :)
