### ISSUE TITLE
Windows installer creates dead shortcuts

### ISSUE THREAD

**Issue by mordwina** [olive-editor/olive#256]
The Windows 64 installer creates shortcuts to `Olive.exe` on the desktop and launch menu, but that target doesn't exist. A side effect is that the shortcut has no icon. The executable filename is `olive-editor.exe` .
**Fix:** edit shortcut to `olive-editor.exe`, for example `c:\Program Files\Olive\olive-editor.exe`.

**Comment by itsmattkc** [comment]
I forgot to update the installer script when I changed the target exe name. I've just updated the installers to fix that.
