### ISSUE TITLE
[Feature request] Show version

### ISSUE THREAD

**Issue by MelanX** [olive-editor/olive#257]
It would be nice if you could add a version number in the "About" section in "Help". And maybe a version number one the homepage. Maybe with a small changelog. Or just a changelog for bigger updates. Would be pretty helpful :)

**Comment by itsmattkc** [comment]
I've been in the process of writing a small qmake function that'll put the git commit hash in the title bar (I can also put it in about). That way it can easily be cross-referenced to the GitHub commit history for a changelog. Do you think that would be sufficient?

**Comment by itsmattkc** [comment]
The commit hash function seems to work from what I've tested, so I've merged it into `master`. I think this will provide a very usable version identifier especially as development is so rapid right now.
