### ISSUE TITLE
Add search field to "Preferences - Keyboard"

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#259]
### Current  behaviors

- https://news.ycombinator.com/item?id=18840198

> I wish all programs that rely heavily in shortcuts also had a search bar for users still not proficient with the program.

### Expected behaviors

Add "Search" field to "Keyboard" tab on "Preferences" dialog for easy navigating in shortcuts descriptions and assigned keys.

### Mockup(s)

- "Search: `(empty)`"

![pic.1](https://i.imgur.com/8pxORAv.png)

- "Search: `Ctrl+N`" 

![pic.2](https://i.imgur.com/Mq62hyG.png)

- "Search: `Open Project`"

![pic.3](https://i.imgur.com/9kebkg0.png)

### REFERENCE

- «Olive, a new non-linear video editor | Hacker News» (discussion) — https://news.ycombinator.com/item?id=18838227

**Comment by itsmattkc** [comment]
Added to d46252b823fb40e317e0857c9d88b9bf63df2c54
