### ISSUE TITLE
Some actions has no option for add any shortcut

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#264]
For example:

- "Action: `Open Recent`"

![pic.1](https://i.imgur.com/rs6omQU.png)

**Comment by Symbian9** [comment]
Maybe, then  show menu labels in parentheses: "Action: `[Open Recent]`"

Or using **bold** text style.

**Comment by itsmattkc** [comment]
As of c36f2ac6fa7b9278e8a45818d8827496d5eaa440, it will always show the > triangle indicator for menus to make it clearer.
