### ISSUE TITLE
Add pop-up menu for quick access to all actions (similar to "Operator Search" in Blender)

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#265]
This pop-up menu should be similar to current "Keyboard" (with "Search action" field) tab in "Preferences" dialog, but would be used directly for apply selected action by double-click on it or by `Enter` (aka `Return`) key after select needed action.

Here is *Blender*'s "Operator Search" pop-up menu description:

> A pop-up menu with access to all Blender tools is available by pressing `Spacebar`. Simply start typing the name of the tool you want to refine the list. When the list is sufficiently narrowed, `LMB` on the desired tool or navigate with `Down` and `Up`, activate it by pressing `Return`.
> 
> ![pic.1](https://docs.blender.org/manual/en/latest/_images/interface_controls_templates_operator-search_pop-up.png)

Also, it would be useful add shortcut (`Spacebar` or other key by default; could be customized) for it and menu sub-entry into "Help" menu:

- "Help"
  - "Action Search"
  - "About..."

### REFERENCE

- https://docs.blender.org/manual/en/latest/interface/controls/templates/operator_search.html

**Comment by Symbian9** [comment]
*NOTE*: For prevent recursive opening of this pop-up menu, "Action Search" action entry should be not shown inside "Action Search" pop-up menu!

**Comment by itsmattkc** [comment]
Done in 952c67972b9e19f5f47236a03dd5a1dae61230a8

**Comment by probonopd** [comment]
# :+1: 

This is awesome.

Could it be made show up as a search box in the menu, like on the Mac?

![1 dk1vkzbbebhgjdgh064vkq](https://user-images.githubusercontent.com/2480569/51429178-f3aa1380-1c03-11e9-90c4-9ee48ed99136.png)

**Comment by itsmattkc** [comment]
@probonopd Hey I'm glad you like it, I'm not sure about menus though, especially as far as Linux goes as doing something like that probably differs immensely between desktop environments.

As for a plugin, it's certainly possible! it's definitely not in any plugin shape at the moment, but perhaps I could put work towards that.

**Comment by probonopd** [comment]
> As for a plugin, it's certainly possible! it's definitely not in any plugin shape at the moment, but perhaps I could put work towards that.

That would be _awesome_!

**Comment by probonopd** [comment]
> MATE HUD

Seems to be dead?
https://bitbucket.org/ubuntu-mate/mate-hud redirects to https://github.com/ubuntu-mate/mute-hud which gives 404.

**Comment by probonopd** [comment]
Check out https://github.com/aoloe/scribus-plugin-actionSearch
