### ISSUE TITLE
Separate Audio Track from Video Track?

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#267]
Would it be possible for Olive be able to separate the video's audio track from itself so then the audio track can be freely modified for purposes of audio sync timing and or replacing the audio track with a remixed (enhanced) audio track?

**Comment by Corruptinator** [comment]
Ah, I didn't know this. Thanks!

**Comment by Corruptinator** [comment]
Oh, actually I noticed as I try out the Link/Unlink, clicking the audio clip still selects both the Video and the Audio tracks, but clicking the video track only will select only the video track and keep it separate. its a BUG.

**Comment by itsmattkc** [comment]
Does d43cb42f02f966fdaf2dfddda70153b133f7df5a fix this?

**Comment by Corruptinator** [comment]
It works.
