### ISSUE TITLE
Auto-scrolling not work in "Action Search" if input field is active

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#269]
### Current behavior

If open "Action Search" pop-up menu and try navigate in the long list of actions using `Up`/`Down` keys, selected item could not be visible if it far away from top of the list.

![pic.1](https://i.imgur.com/yYtnF4t.png)

But if firstly make list area active (by switching using `Tab` key) all work as should be.

![pic.2](https://i.imgur.com/AItSa4t.png)

Seems, like auto-scrolling not working while search input field is active.

### Expected behavior

Selected item should be always in focus in the "Action Search" pop-menu visible area, so auto-scrolling should work always.

**Comment by itsmattkc** [comment]
Weird, I could have sworn I wrote this in but it was missing. Maybe I did in another branch and forgot to merge. Either way, d51ce537aeb066c247bfcd3ec84bb3ea4183bef9 should fix this
