### ISSUE TITLE
Navigating on sequence timeline using Left/Right arrow keys in backward direction keep more time than navigating in forward direction

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#270]
Navigating into forward direction by `Right arrow` key much faster (work better) than navigating into backward direction using `Left arrow` key.

**Comment by itsmattkc** [comment]
Do you mean advancing a frame is usually faster than stepping backwards a frame?

**Comment by Symbian9** [comment]
Yes, and system load increased if step backwards

**Comment by itsmattkc** [comment]
This is _sort of_ a design decision in that Olive purposefully doesn't keep any frames in memory that are prior to the playhead (optimizing memory space for playback). It's also a reality that getting specific frames can be expensive, particularly with codecs like H.264.

Olive _could_ keep frames prior to the playhead in memory, but the question then is how many frames and how much memory are users willing for Olive to take up. I believe the user should be in control of this, so in 5f8db6b3beceb3dcda5b9ebacca43911da30ac28 I've added controls for how many frames the user wants to keep in memory (both upcoming frames and previous frames). I believe this will solve this issue.
