### ISSUE TITLE
Effects Keyframe Playhead & Playline disconnect

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#274]
If a user drags the edge of the Effects Keyframe slider, the playhead & playbar become disconnected.

![disconnected_play_arrow](https://user-images.githubusercontent.com/12004932/50831358-817f3680-139a-11e9-9892-6b0356e62c87.png)

**Comment by itsmattkc** [comment]
Good pickup, fixed in 607d36115a86265f8bf934250a79aeaa0795733c
