### ISSUE TITLE
[Feature request] Filling empty stereo channel with audio from the other channel

### ISSUE THREAD

**Issue by goldenbait** [olive-editor/olive#277]
This is a common situation, you've recorded audio with a mono microphone onto a stereo track. This only fills one of the two stereo channels, commonly the left channel.

In Premiere Pro this issue is resolved by using the "Fill left with right"/"Fill right with left" effects.

I've always felt this was an ineffective way to do it, but it works. Maybe consolidating it to one audio effect with two options (Fill right with left/Fill left with right) in a drop-down would be a better way?

**Comment by goldenbait** [comment]
I've worked with a ton of beginners teaching them Premiere Pro, and this is always confusing until they've been told that it is in fact an issue and how to fix it.

Maybe auto-detecting stereo tracks with an empty channel and fixing it on import could be a solution? Or, if this might break some niche use prompt the user for an auto-fix when putting the clip on the timeline?

A prompt could say: "This clip contains an empty stereo channel. (Fill empty channel) (Always fill empty channels) (Cancel)"

**Comment by itsmattkc** [comment]
Fill Left/Right effect added in 6b1bb620c1549dea825b7875363e607207653c50

Auto-detecting is a slippery slope, as you say if there's low level noise, it won't be truly "silent", so there would have to be some sort of minimum threshold. It would also take time to process, which could be done in the background like the waveform generation (and would probably hook into the same loop), but that means the user wouldn't get a prompt until several seconds (or even minutes) after importing which could get confusing or even annoying from a user experience standpoint.

I do think putting a stop to the epidemic of one-ear audio through some sort of automation would be nice, but I'd have to think further on the best way to do it.

Anyway, this feature has been added so I'll close this issue for now.

**Comment by IcedQuinn** [comment]
This should probably be re-opened. 0.2 does not have this node and I just ran in to an issue where I had to drop Olive due to being unable to fix a botched stereo track with it.
