### ISSUE TITLE
Add more CLI options  (--help, --version, etc.) and arguments (such as path to project, media file that should be imported)

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#280]
Add CLI options that could be executed in terminal

- `--help` (`-h`) — show all available CLI options; (**without launch GUI**)
- `--version` (`-v`) — info about current *Olive* build; (**without launch GUI**)
- `--fullscreen` (`-f`) — launch *Olive* in fullscreen. (with GUI)
- `--test` — quick test & show availability of all needed functions (system requirements) before normal launch *Olive* on particular PC/OS; (**without launch GUI**)
- other options.

Example:

```
$ ./Olive-*.AppImage -v
Olive (January 2019 | Alpha | a16993b )
```

**Comment by alcomposer** [comment]
I think this would be very powerful.
There could also be a command to render Olive projects, or inspect olive projects. Paired with the terminal a user could generate automation scrips for preprocessing clips for editing in Olive GUI

**Comment by itsmattkc** [comment]
Added `--help`, `--version`, `--fullscreen` in d798edfd059ecf52558d6f2dc1b55eb2feaacbae. Command line (no GUI) rendering (with the ability to select in/out points) would be especially interesting, could technically make something like a video editing render farm with that.

**Comment by itsmattkc** [comment]
Folding into #820.
