### ISSUE TITLE
Add "Help > Log console"

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#283]
Vector editor *sK1 2.0* has nice feature: "Log console"

- https://github.com/sk1project/sk1-wx

![pic.1](https://i.imgur.com/yxHk9Tp.png)

![pic.2](https://i.imgur.com/d2xajSV.png)

Application log should be stored in `~/.config/Olive*/Olive.log

**Comment by itsmattkc** [comment]
Should be fully implemented as of 317d278fc5222c27096ce31f12cd494c309da348
