### ISSUE TITLE
Change shortcuts for "Delete" and "Edit"

### ISSUE THREAD

**Issue by goldenbait** [olive-editor/olive#286]
This is opinionated, but for a faster workflow delete should be remapped to "X" (while keeping delete as an alternate if possible), and edit could be moved to the available "E".

**Comment by itsmattkc** [comment]
All keyboard shortcuts can be changed in the Preferences (unless that's not what you're talking about?)

**Comment by goldenbait** [comment]
Yes of course. I mean it might be a better default. It's as said just my opinion, feel free to close this if you feel the default is fine as is :)

**Comment by pgilfernandez** [comment]
I also find it a better default shortcuts, but, as _itsmattkc_ said it just a matter of changing them as you prefer.

PS - I also find more obvious to export with command+E, hehehe

**Comment by goldenbait** [comment]
@pgilfernandez Ctrl-m stems from Premiere Pro, so converts might like this one :) It's not bad as is, but in the end good defaults matter.

**Comment by Symbian9** [comment]
The easiest way to solve this issue:

1. add  "Reset selected to Default";
2. rename "Reset to Default" → "Reset all to Default".

![pic.1](https://i.imgur.com/XbTjmCh.png)

**Comment by itsmattkc** [comment]
I was thinking of a "Reset All" button, I'll probably add that soon.

Almost all of the shortcuts do stem from Premiere simply because that's what I'm most familiar with so I don't really want to change them. Adding presets for people familiar with other editors (e.g. Blender) is not a bad idea though.

**Comment by Symbian9** [comment]
> I was thinking of a "Reset All" button, I'll probably add that soon added

Thanks! ;-)

When I reread this issue thread found that this issue title should be ~~*Edit and delete shortcut rearrangement*~~ *Change default shortcuts for "Delete" and "Edit"*.

> Adding presets for people familiar with other editors (e.g. Blender) is not a bad idea though.

As now *Olive* has an option for import shortcut preset from file, think different/additional presets should be placed into separate repo:

- https://github.com/olive-editor/olive-assets

Later `olive-assets` could be used for collect themes, shortcut presets, etc.

Think, it's bad idea for bundle presets named as other proprietary software directly into *Olive* (also it could be some violating on trademarks™, registered marks ® and copyrights ©), so better separate assets from main source repo.

**Comment by goldenbait** [comment]
Not changing them is fine, that's why they're configurable.

Not sure if naming shortcut presets based on brand names would violate that trademark. Darktable has named all of it's base curves on camera brand names "Canon EOS like" etc. Davinci Resolve has this shortcut preset scheme on first startup and in the preferences, would doubt Adobe would allow it from a competitor if it could be stopped. Better safe than sorry though. And Blender like shortcuts alone would be nice.

**Comment by itsmattkc** [comment]
I think presets should definitely be available, but I agree they should probably be separate from the application itself. This was a good discussion however, and something to think about in the future.
