### ISSUE TITLE
Playback region stop/start and loop

### ISSUE THREAD

**Issue by ion12** [olive-editor/olive#288]
First of all thank you so much for creating and sharing this project!

Regarding the playback region stop/start behaviour:

- Adding a button/hotkey toggle for looping playback would be very useful.
- When the playhead reaches the last frame/out point it stops. When you press 'play' again, I'd like it to 'auto-rewind' and restart playback from the first frame/in point. 
Right now it will just continue playing forward indefinitely!
- Obviously the playhead should stop at the last frame, but I'm not so sure about how useful it is that it also stops at the 'Out Point' when there's no looping. Premiere Pro, for example, has separate functions for 'Play' and 'Play In to Out'. When looping is enabled in Premiere 'Play' will also be restricted to looping the In/Out points, when looping is disabled 'Play' will disregard the In/Out points for playback behaviour. This quick shifting between looping the In/Out region and unrestricted playback is very useful for fine adjustments of an edit.
Other options that could be useful in this regard would be : 
     - add the option to 'Clear In Point' (i.e. reset it to last frame) and 'Clear Out Point' (i.e. reset it to first frame) independently
     - add the option to 'Disable' the In and Out Points (i.e. ignore them temporarily during playback without being forced to completely 'Clear' them)
     - make a distinction between 'Go to In/Out Point' functions and 'Go to Start/End' functions.

I hacked the code to enable a rudimentary auto-rewind and loop toggle for my own local compile. It is usable and useful for me as a starting point. I am not an experienced programmer, so I'm not offering this as a pull request, but for what it's worth here are my initial crude patches for [auto-rewind](https://github.com/ion12/olive/commit/9a14ca5abc36758468c46c6fd6cb502821454d24) and [loop](https://github.com/ion12/olive/commit/260979e4db9390b7497bcb05d562436a20c23390)

**Comment by itsmattkc** [comment]
Added options for looping (and stopping at the last frame, both on by default) in 0318ad4965a35ad317609dc9d3a648cbbd5216b4
Separated go to in/out from go to start/end in e0f628060719deb3c5dd2aa7dd92bdbd3174eab4

**Comment by ion12** [comment]
Thanks so much!  
Sorry for not having time to respond yesterday before you closed the issue. Is it still ok to follow up this up?

IMO 'Loop' belongs in the 'Playback' menu not the 'Tools' menu, and should also get a dedicated button next to the other playback buttons. (I can open as separate issue if it's easier)

You use 'Out Point' and 'last frame' interchangeably, can we differentiate between 'Out Point' and 'End Point' (literally the last frame of the sequence) behaviour?

IMO creating the "auto-rewind" effect by combining enabling 'Loop' and 'Pause at Out Point' at the same time is confusing.  
When 'Loop' is ON, playback should literally loop (between In/Out points if they're active, or between Start/End points otherwise) *regardless* of any other setting - otherwise it's counter-intuitive.

When 'Loop' is OFF :  
I would follow the logic of Premiere, Resolve, etc. and ignore the 'In/Out Points' for playback, and add a dedicated 'Play In to Out' function (shift+space hotkey?) instead.  
So 'Pause at Out Point' should be 'Pause at End' and not affect the 'Out Point'.  
'Restart Playback from Beginning if at End' (or whatever name is most appropriate to describe "auto-rewind") should be a separate option. Both 'Pause' and 'Auto-rewind' options should be enabled by default.  
When 'Pause' is enabled and 'Auto-rewind' is disabled, pressing play at 'End Point' just does nothing, playhead remains paused.

**Comment by ion12** [comment]
Thanks for the loop menu re-positioning.
Do the rest of my comments make sense to you? I'm trying to describe playback behaviors that are typical for professional NLEs, and which are IMO extremely intuitive and helpful for a fluent editing workflow.

**Comment by itsmattkc** [comment]
Yes I understand them, I just haven't gotten around to implementing them yet. I should be able to soon!

**Comment by itsmattkc** [comment]
cb3098e89d2a789d9bc9784a9b6962c74baaae06 should behave how you've described.
