### ISSUE TITLE
Add option "Seeking also selects"

### ISSUE THREAD

**Issue by goldenbait** [olive-editor/olive#297]
Opens up a whole new world of keyboard based workflows! This is called "Select follows playhead" in Premiere I think.

Side note, editing 1080p on a 200$ notebook. Everything is smooth as butter. You're creating something really special here.

**Comment by goldenbait** [comment]
Yes. This would be most useful in a rough cut, you can for example quickly delete the clip you are currently watching, then ripple delete.

Could also be useful for color correcting footage, switching between clips with up and down keys, and having the effects panel automatically update to the current clip.

**Comment by itsmattkc** [comment]
Let me know if what I've added in 5bb256156edd5d1666d706ca3b9e4e492d42e7e3 is what you wanted.

(P.S. forgot to say thanks for the kind words, that sort of thing is what's driving this whole project :) )

**Comment by goldenbait** [comment]
It works excellent! Great stuff.

It would be even more functional if it kept selecting during playback. Wherever the play head goes, it selects.

(P.S. you deserve it man.)

**Comment by itsmattkc** [comment]
Selects on playback too in 731300539a820ddca391163835c299442675fd32
