### ISSUE TITLE
Replace text input field with "Edit Text" button & text input window for "Text" effect

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#299]
### Actual behavior

Currently 3-line еуче input field located directly on "Effects Controls" widget and little affect it

![pic.1](https://i.imgur.com/lamJasj.png)

### Expected behavior

Lets separate text input to the separated "Edit Text" window

![pic.2](https://i.imgur.com/99rECxM.png)

**Comment by goldenbait** [comment]
Any clarification on why you would want this? You would lose being able to see your text at a glance, and it would add another click to your workflow. I think it should stay the way it is.

Is it because it is so small? Then manually being able to expand the input window would be way better.

**Comment by Symbian9** [comment]
> Any clarification on why you would want this?

As it's effects *string* in connection with node editor, it would be better keep on string per each effect option.

**Comment by itsmattkc** [comment]
I think having the text in the panel itself is useful, but I can see the argument for it being too small in some cases. I believe it should be a compromise - I've added a resizable text dialog in e8f632940c20026ea294d1340fad5d666aab0e9f if you want more room to edit (right click on text field > Edit Text)

**Comment by Symbian9** [comment]
> I believe this should solve this issue.

Partially, yes, but height of text in panel height should be **1 line**:

![pic.1](https://i.imgur.com/daWSdcU.png)
