### ISSUE TITLE
Improve widgets "Footage Viewer", "Sequence Viewer" and "Effects Controls" title and header

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#305]
### Actual behavior

- If un-tabbed

![pic.1](https://i.imgur.com/ovB456H.png)

- If tabbed

![pic.2](https://i.imgur.com/8hzpv1A.png)

### Expected behavior

- If un-tabbed

![pic.3](https://i.imgur.com/k4XNmYv.png)

- If tabbed

![pic.4](https://i.imgur.com/p0QCZbk.png)

### Naming improvements

Also, as for me, need fix:

- ~~"Effect Controls"~~ → "Effects Controls"

And rename:

- ~~"Footage Viewer"~~ → "Media Preview"

**Comment by goldenbait** [comment]
This is a discussion about clutter vs. information. One mans trash is another mans gold! I like having that information there. But I see why you would want a neater setup for yourself.

**Comment by itsmattkc** [comment]
Added naming for "Media Viewer" and "Sequence Viewer" in 5776387eb0ae92edd8d204501b135c248e0a06c4
