### ISSUE TITLE
Add hardcoded "Sequences" and "Media" folders into "Project" navigator

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#307]
Add two hardcoded folders in "Project" navigator:

- "Media" (or "Media files") — where all imported media files should be placed automatically;
- "Sequences" — where all sequences should placed automatically.

![pic.1](https://i.imgur.com/Q9CPbqZ.png)

- Those folders should be non-strippable!
- In those folders creating sub-folders (that could be deleted) should be allowed!
- Sequences cannot be moved into "Media" folder!
- Media files cannot be moved into "Sequences" folder!

**Comment by ion12** [comment]
Forcing a workflow style on the user is always a problematic idea IMO. I wouldn't want my projects organized that way personally.

**Comment by pgilfernandez** [comment]
Maybe a Preference option to force Media or Sequences to be created into a folder with the option to customize their name. If they are uncheck all the media and sequences go to the main hierarchy as happens now.

**Comment by Symbian9** [comment]
@pgilfernandez, something like that

Or, maybe, there should be just context option "Hide sequences" for temporary hide all sequences on the "Project" widget.

![pic.1](https://i.imgur.com/UKTR969.png)

**Comment by itsmattkc** [comment]
Added option to hide sequences in 016a94f656331fb439a7f4e91dc8a4ada74526b5
