### ISSUE TITLE
Surround Sound Support?

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#312]
I noticed that even though you can import 5.1 or 7.1 surround channel sound files, olive only downmixes the multi channel to the Left and Right Stereo channels through final exporting to video. Can Olive have the option to export with surround sound to 5.1, 7.1 or up to 32 channels?

[Surround_Test.zip](https://github.com/olive-editor/olive/files/2752767/Surround_Test.zip)

I made the surround sound clip above in Cakewalk to test the Olive sound export, it exports in stereo only.

**Comment by itsmattkc** [comment]
Olive currently only supports stereo audio. Surround support will likely be added later.

**Comment by Corruptinator** [comment]
Understood.

**Comment by frink** [comment]
The actual mixing of 5.1, 7.1 11.2 etc is almost always done by external programs in professional workflow. NLEs are not DAWs and should not be thought of as replacement for the art of audio engineering. The panning, phasing and normalizing of audio is enough to make most visual sequence editors pull their hair out. You need someone who is focused on only the audio. If you're doing something on YouTube you don't need anything more than stereo most of the time. If you're doing a feature movie you probably know better than trying to do your audio editing in the NLE...

**Comment by Corruptinator** [comment]
That's very much true @frink, most Digital Audio Workstations does get the job done, I know this from experience by taking a university class of Sound Design using Pro Tools. There are also other software tools that can be used to great extent, the one I prefer is Cakewalk (Sonar) by Bandlab, not because that it is free for download, but a nifty software that can do great results in any type of mixing, including surround sound.

In other cases however, mostly when any sound mixer is done mixing sound effects, they're mostly put alongside with video files to mix them together as a final render, either through FFMPEG, MakeMKV, or video editors; henceforth, this feature request I previously suggested as a means of ease-of-access alternative of final audio mixing to the exported/rendered video.

**Comment by frink** [comment]
So the request is more not the editing features of surround sound but rather avoiding down-mixing higher channel counts... is that it?

**Comment by Corruptinator** [comment]
More or less. Although you could take advantage of exporting with surround sound or down-mix to Stereo, just options.

**Comment by frink** [comment]
I'd agree with that sort of thinking. We should be destroying the surround formats if we can help it...

In the end though, we should really be thinking more about the interoperability between DAW and NLE. While I understand the Prosumer concept of trying to bring everything into one tool like HitFilms and Davinci Resolve try to do, I think it is better to have great file exchange potential with better version control and administrative workflow between the programs...

Finding a solution for distributed work is probably the biggest thing in terms of large scale projects. If Olive focuses on multi-person workflows that are generic and configurable then we will have a pro-grade editor that every studio and small shop will use. (which means more support for the project overall...) This is why I'm stressing workflow and interoperability...

**Comment by Corruptinator** [comment]
In the end, you're right about one thing, Olive doesn't need to edit surround sound; instead, it should simply just be able to drag and drop surround sound files into the project. That is where the DAW software comes in, let one software do all the hard work while Olive does the simplicity of editing videos. Heck, this is where one professional freeware software (Cakewalk by Bandlab) comes into play. That software can make surround sound on the go, afterwards I can take the exported surround sound and drag it into Olive.

**Comment by frink** [comment]
Absolutely.

But there is still no easy workflow between DAW or NLE unless you use a suite like Adobe or Avid. Even then it's tough to have an easy streamlined workflow.
