### ISSUE TITLE
Incorrect Windows version, audio issues, and suggestions

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#313]
_**The Versioning Issue**_

The [downloads page](https://www.olivevideoeditor.org/download.php) says it provides December 2018 binaries. However, the site provides the unreleased January 2019 build.

_**Audio Issues (January 2019 build for Windows)**_

**Note:** None of these issues affect video files with audio tracks. These issues affect individual audio files with no video track whatsoever.

1. Wave-forms do not render
2. The green audio strip is not properly inserted into the timeline.  No matter where you scrub, the audio strip plays back wherever it was left off.

_**Feature Requests/Improvements**_

1. The ability to link/un-link and "un-nest" strips through the context-menu. No more #267
2. Nested strips from multiple sequences should form one strip, similar to [Blender's meta-strip function](https://easyblend.org/html/editors/sequencer/strips/meta.html). This should reduce clutter.
3. Currently, the transform effect's uniform-scale inserts **both** X and Y-axis keyframes into the graph-editor. In uniform-scale, the user should only insert X-axis keyframes. The Y-Axis (green) is redundant for uniform scaling.

![image](https://user-images.githubusercontent.com/40442071/51096080-ed84e480-1776-11e9-942a-0a4432d0fbf2.png)

4. Markers and the time-line scrubber need to separate. The issue affect the timeline, graph editor, and node editor. Here is an example of a common conflict:

![conflict](https://user-images.githubusercontent.com/40442071/51095149-cecf1f80-176f-11e9-83ef-f63ed1a40516.png)

This makes it difficult to interact with the marker or scrubber. My idea is that the marker should mirror the scrubber like this:

![proposed](https://user-images.githubusercontent.com/40442071/51095165-ed351b00-176f-11e9-955d-ff2b0e66f63e.png)

I also hope the issues from #300 were considered. The OP did many works on his fork and I don't want this project to die out :v

**Comment by itsmattkc** [comment]
> 1. Wave-forms do not render
> 2. The green audio strip is not properly inserted into the timeline.  No matter where you scrub, the audio strip plays back wherever it was left off.
You may need to send a sample of this audio file - this doesn't occur for me and sounds like perhaps there's a codec incompatibility of some kind.

> 1. The ability to link/un-link and "un-nest" strips through the context-menu. No more #267
So adding Link/Unlink to the context menu? That should be easy. Olive doesn't yet have an "un-nest" feature.

> 2. Nested strips from multiple sequences should form one strip, similar to [Blender's meta-strip function](https://easyblend.org/html/editors/sequencer/strips/meta.html). This should reduce clutter.

Does nesting clips not squash them into one sequence for you? You may need to clarify what you mean by this.

**Comment by Symbian9** [comment]
Please, split this multitask issue into separate issues per each task (it would be useful for prevent creating duplicates)

**Comment by BrimsonBhin** [comment]
@itsmattkc 

1. Okay, here are some examples I got from [here](https://nobleoak.bandcamp.com/track/random-hits)

[Ogg and AAC versions](https://github.com/olive-editor/olive/files/2770268/Samples.zip)

This is how it looks on the January Alpha (Windows x64)

![image](https://user-images.githubusercontent.com/40442071/51343307-5f994a00-1a53-11e9-93ac-323b7d2d2d52.png)

It still happens even when I re-encode the audio samples with FFmpeg

3. The current nested sequence is like this, with two stips. 

![image](https://user-images.githubusercontent.com/40442071/51343552-e9e1ae00-1a53-11e9-8cdc-3d8fa910a9b1.png)

I thought it would be a sound idea to remove the bottom strip because you can't alter it. Recently, I realized the sequence divides the video on top and the audio on the bottom. I am scrapping this idea altogether.

@Symbian9 I'll do it next time, as the developer already responded to this issue. Thanks for the reminder 👍

**Comment by itsmattkc** [comment]
I'm not able to recreate your audio missing waveforms bug. I've updated the website builds so could you try those and see if they solve the audio issue?

**Comment by BrimsonBhin** [comment]
@itsmattkc 

The issues are still there when I tried Alpha `b2ff4db`. I have discovered that the issues I am experiencing on my end also affects audio recordings as well.

**Comment by itsmattkc** [comment]
@BrimsonBhin They're still working on my end. Can you check Help > Debug Log for any error messages surrounding the importing and inserting of said audio files?

**Comment by BrimsonBhin** [comment]
@itsmattkc Okay, debug now works in `1d85c42`, here is what I get whenever I scrub/play the audio

![image](https://user-images.githubusercontent.com/40442071/51576921-358dc080-1e75-11e9-90a3-d76cb2a55d38.png)

**Comment by itsmattkc** [comment]
I believe 32479b1b8395004e06d46e5289b19632fed8a6d5 should fix this, let me know if it does!

**Comment by BrimsonBhin** [comment]
It works! thank you :)
