### ISSUE TITLE
Add AppImage builds for 32-bit (x86; i386)

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#314]
Add task to Travis CI for build 32-bit AppImage & upload it as asset to `continuous` release

Naming: `Olive-{git}-x86.AppImage`

Cast @probonopd

**Comment by probonopd** [comment]
Uh, I don't know how to do this, but @TheAssassin might know.

**Comment by TheAssassin** [comment]
Just install all of your dependencies as 32-bit versions, then cross-build for 32-bit.

**Comment by probonopd** [comment]
> install all of your dependencies as 32-bit versions

Probably along the lines of 

```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get -y install bash:i386 
```

>  then cross-build for 32-bit

How?

**Comment by TheAssassin** [comment]
Not really. See https://github.com/linuxdeploy/linuxdeploy/blob/master/.travis.yml#L16-L28 and https://github.com/linuxdeploy/linuxdeploy/blob/master/cmake/toolchains/i386-linux-gnu.cmake.

**Comment by probonopd** [comment]
Thanks for the hints.

**Comment by itsmattkc** [comment]
I seem to have it correctly building for 32-bit, but the resulting AppImage doesn't run on 32-bit systems. Is the container AppImage still 64-bit code or have I done something wrong?

**Comment by TheAssassin** [comment]
You need to build with the i386 version of appimagetool.

**Comment by itsmattkc** [comment]
How would I do that considering it's set up to use linuxdeployqt? Would I need to compile linuxdeployqt manually?

**Comment by probonopd** [comment]
> linuxdeployqt is so limited...

Blocked by https://github.com/AppImage/AppImageKit/issues/304, rather.

**Comment by itsmattkc** [comment]
Done in 229d01a400f3a7c65ca6e3d07b8f3f0c6d94f757
