### ISSUE TITLE
Screencast video (from Android) imported with 90000FPS

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#315]
![pic.1](https://i.imgur.com/IncF4P5.png)

Here is this screencast video (file size ~ 6 MB; direct link valid until 2019/01/30)

- https://transfer.sh/get/WqSiS/20190109_075302.mp4

**Comment by Corruptinator** [comment]
Huh, that's weird. Not sure what to give on the verdict of the issue but just in case, one way of fixing it is to interpolate the frames to either 60 fps or 24 fps. What I am thinking is that whatever you used to record has no definite Frame-rate Cap limit in the video's metadata and that the capture was set to the highest it could go to ensure a seamless playback. Therefore, the video is going to need to be re-encoded or re-rendered with the proper fps count. I recommend using _Virtualdub2_ (formally virtualdubmod) with the **Interpolate Filter** that blends the framerate to the intended framerate for the video. Figure I share a helpful advice.

**Comment by Symbian9** [comment]
> Figure I share a helpful advice.

Did you try do all the above by yourself with linked file?

**Comment by Corruptinator** [comment]
Well after changing it to 30 FPS through VirtualDub2's Interpolation Filter, Seems to work:

![image](https://user-images.githubusercontent.com/5027750/51220780-7cb30900-18eb-11e9-83c2-8fe6dd0791a4.png)

**Comment by Corruptinator** [comment]
Probably a lesson learned through this is always to make sure the framerate is at a fixed output. Not all capture devices will record the equal amount Especially for any devices such as a mobile phone, Xbox, etc with their built in DVR game capture software.

**Comment by Symbian9** [comment]
> According to the results the average framerate your video has is **29.136 FPS**. So it could explain the 90000 FPS in Olive, it doesn't give a specific FPS count depending on what video is uploaded. Had a similar situation when I was trying to import Xbox One video captures from the console to Olive itself. Every game capture had a different output of FPS assigned as there were no absolute capture limit.

Seems like a bug of Olive, right?

**Comment by Corruptinator** [comment]
Well technically Olive shouldn't (in theory) need an interpolation filter. From my understanding based on how long I have been experimenting with the Olive software, the video editor itself was designed to be professionally usable in the most simple way possible. That said the framerate issue is something that needs to be resolved outside of Olive before importing them into the project. That is only my opinion though and I can't say that it is not the right idea either. Bug or not I think what could help is that perhaps _Olive have the correct FPS output number displayed_ so then video editors will have a better idea on what framerate every sequence property should have.

**Comment by Symbian9** [comment]
> framerate issue is something that needs to be resolved outside of Olive before importing them into the project

... or during importing them into the project

**Comment by Corruptinator** [comment]
Perhaps. I have no idea honestly.
