### ISSUE TITLE
Show only 1-line input field for "Text" on effects panel

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#316]
### Actual behavior

Text input field on effects panel (preview) is **3-line tall**

![pic.1](https://i.imgur.com/daWSdcU.png)

### Expected behavior

Text input field on effects panel should be **1-line  tall** (for multiline edit control click RMB on text field and choose "*Edit Text*" in context menu, see https://github.com/olive-editor/olive/issues/299 )

![pic.2](https://i.imgur.com/Qix0qYC.png)

Here is similar solution coming to video sequencer in *Blender 2.80*

- https://twitter.com/_rachinskiy/status/1084982263341875200

![pic.3](https://pbs.twimg.com/media/Dw6gv67XcAAIbvQ.jpg:orig)

**Comment by itsmattkc** [comment]
I don't really see this is an improvement. I guess it saves screen real estate but I'd prefer to have 3 lines than 1 in the effect controls.

**Comment by Symbian9** [comment]
As half-way solution, can you add an option in "Preferences" dialog where user could set how many lines should be shown in text input field?

**Comment by itsmattkc** [comment]
> As half-way solution, can you add an option in "Preferences" dialog where user could set how many lines should be shown in text input field?

Added in 9143561bb476a8a4093ded9ea42742166fed0993, you'll have to restart Olive for changes to take effect.

**Comment by Symbian9** [comment]
> Added in (...), you'll have to restart Olive for changes to take effect.

Thanks! Just few notes:

If set height as **1-line** then input field look little broken:

![pic.1](https://i.imgur.com/oVJIKsw.png)

But if set height as **2-line** seems much better!

- if text inside text input field is single line it look

![pic.2](https://i.imgur.com/Y6zoMSv.png)

- if text inside text input field is multiline vertical scrolling buttons start indicate that

![pic.3](https://i.imgur.com/dlnczRN.png)

### Conclusion

So, 2-line effect textbox seems like best option here.

Finally, @itsmattkc, I propose *set effect textbox height to 2-line (as hardcoded)* and remove "Effect Textbox Lines:" option from *Olive* preferences.

**Comment by itsmattkc** [comment]
The textbox margins should be fixed in d0c9b0ba0734f2d3f520093cc7293ec1234feefa
