### ISSUE TITLE
Corner Pin fails on AMD GCN 3 (other GL effects work)

### ISSUE THREAD

**Issue by oc1024** [olive-editor/olive#321]
My laptop is:

> Arch Linux, last updated Jan 13.
> Olive compiled within the last 4 hours, with `git pull; qmake; make`
> A10-8700P (AMD Carrizo, GCN 3)

The only other similar issue I could find was #284 but I soon ruled it out. Every other effect I know is GL based works (I tested Text with shadows, box blur, gaussian blur, directional blur, radial blur, ripple, toonify, fisheye, volumetric light and even all of them at the same time).

When I add the corner pin effect, the video or image turns into an opaque area with the color of the top left pixel of the image. [Using this stock footage video](https://www.youtube.com/watch?v=vWGg0iPmI8k), I get a sky-colored box. With a white image with lone black pixel at the top left, I get a black area.

I consistently get this error message:
```QOpenGLShader::compile(Vertex): 0:2(12): warning: extension `GL_EXT_gpu_shader4' unsupported in vertex shader
0:34(6): error: `gl_VertexID' undeclared
0:34(6): error: operands of `==' must have the same type
0:36(13): error: `gl_VertexID' undeclared
0:36(13): error: operands of `==' must have the same type
0:38(13): error: `gl_VertexID' undeclared
0:38(13): error: operands of `==' must have the same type
0:52(6): error: `gl_VertexID' undeclared
0:52(6): error: operands of `==' must have the same type
0:54(13): error: `gl_VertexID' undeclared
0:54(13): error: operands of `==' must have the same type
0:56(13): error: `gl_VertexID' undeclared
0:56(13): error: operands of `==' must have the same type
0:58(13): error: `gl_VertexID' undeclared
0:58(13): error: operands of `==' must have the same type

*** Problematic Vertex shader source code ***
#version 110
#define lowp
#define mediump
#define highp
#line 1
#extension GL_EXT_gpu_shader4 : enable

uniform bool perspective;
uniform vec2 p0;
uniform vec2 p1;
uniform vec2 p2;
uniform vec2 p3;

varying vec2 q;
varying vec2 b1;
varying vec2 b2;
varying vec2 b3;
varying vec2 vTexCoord;

void main() {
    gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;

    if (perspective) {
        float m1 = (p3.y - p0.y)/(p3.x - p0.x);
        float c1 = p0.y - m1 * p0.x;
        float m2 = (p1.y - p2.y)/(p1.x - p2.x);
        float c2 = p2.y - m2 * p2.x;
        float mid_x = (c2 - c1) / (m1 - m2);
        float mid_y = m1 * mid_x + c1;

        float d0 = length(vec2(mid_x - p0.x, mid_y - p0.y));
        float d1 = length(vec2(p1.x - mid_x, mid_y - p1.y));
        float d2 = length(vec2(p3.x - mid_x, p3.y - mid_y));
        float d3 = length(vec2(mid_x - p2.x, p2.y - mid_y));

        float q;

        if (gl_VertexID == 0) {
            q = (d1+d3)/d3;
        } else if (gl_VertexID == 1) {
            q = (d0+d2)/d2;
        } else if (gl_VertexID == 2) {
            q = (d3+d1)/d1;
        } else {
            q = (d2+d0)/d0;
        }

        gl_Position[0] *= q;
        gl_Position[1] *= q;
        gl_Position[3] = q;

        vTexCoord = gl_MultiTexCoord0.xy;
    } else {
        vec2 pos;
        
        if (gl_VertexID == 0) { // top left
            pos = p2;
        } else if (gl_VertexID == 1) { // top right
            pos = p3;
        } else if (gl_VertexID == 2) { // bottom right
            pos = p1;
        } else if (gl_VertexID == 3) { // bottom left
            pos = p0;
        }

        q = pos - p0;
        b1 = p1 - p0;
        b2 = p2 - p0;
        b3 = p0 - p1 - p2 + p3;
    }
}
***```

**Comment by oc1024** [comment]
It now works, though the video darkens a bit.

**Comment by itsmattkc** [comment]
It seems GPUs are less likely to support `GL_EXT_gpu_shader4` than they are to support GLSL 1.30 (which contains the functionality of `GL_EXT_gpu_shader4`). I'll change the shader to use that instead.

Darkens eh? Can you provide a side by side example of this?

**Comment by oc1024** [comment]
I vividly remember having the issue, but after a reboot it went away. The effect works properly.

**Comment by itsmattkc** [comment]
Huh, just one of those things I guess? Let me know if it returns
