### ISSUE TITLE
How to position windows in a video editor, 1st draft

### ISSUE THREAD

**Issue by brontosaurusrex** [olive-editor/olive#322]
Nothing specifically to do with Olive, but you got me tinkering and since I'am more than 20 years now in this video-editing business I think I may have some more or less useful ideas (on how to waste screen space 'correctly').

https://brontosaurusrex.github.io/2019/01/17/how-to-position-windows-in-a-video-editor/

Comments are welcome, but keep in mind that this is the 1st draft and I may change and or expand it further.

**Comment by itsmattkc** [comment]
Definitely good points, and I hope to address layout concerns with #587. Thank for the input!
