### ISSUE TITLE
[Feature request] Viewport panning

### ISSUE THREAD

**Issue by Cambloid** [olive-editor/olive#324]
It would be nice to have the ability to pan the video viewport like dragging and zooming.

**Comment by Symbian9** [comment]
> It would be nice to have the ability to pan the video viewport 

You mean this?

![pic.1](https://i.imgur.com/g6zzpW9.png)

If, so, you could already use mouse actions:

- for panning: grab and drag with `LMB`
- for scaling: pull corners with `LMB`

**Comment by Cambloid** [comment]
No, I ment the whole viewport with the clips inside

**Comment by itsmattkc** [comment]
Zooming can be accomplished with right click > Zoom
Panning can be accomplished by switching to the Hand tool or dragging with middle click

**Comment by Cambloid** [comment]
You probably ment the timeline, I was talking about the viewer (video viewport)

<img width="640" alt="68747470733a2f2f692e696d6775722e636f6d2f67367a7a7057392e706e67" src="https://user-images.githubusercontent.com/12214553/51318195-eea96080-1a59-11e9-9b7c-9d6cbe2da8fd.png">

**Comment by itsmattkc** [comment]
I do not mean the timeline.

![image](https://user-images.githubusercontent.com/34096995/51318266-f0047880-1aad-11e9-817d-68954b5954c7.png)

**Comment by Symbian9** [comment]
> Panning can be accomplished by switching to the Hand tool or dragging with middle click

Also, for vertical panning it's possible to use roll mouse wheel, and for horizontal panning could be used mouse wheel left/right clicks (if mouse support it) too ;-)
