### ISSUE TITLE
Handling system-wide shortcuts

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#326]
What you think, would it be useful for *Olive* implement `qxtglobalshortcut`?

- https://github.com/hluk/qxtglobalshortcut

**Comment by itsmattkc** [comment]
I'm not sure what global system-wide shortcuts could be useful in Olive. If you have ideas, feel free to let me know.

**Comment by Symbian9** [comment]
@hluk, what you think, would be it useful add handling system-wide shortcuts into non-linear video editor?

**Comment by hluk** [comment]
> @hluk, what you think, would be it useful add handling system-wide shortcuts into non-linear video editor?

Not sure why I get a vote in this, but I don't see how a video editor would benefit from having system-wide shortcuts.
