### ISSUE TITLE
Feature Request: Clip Markers

### ISSUE THREAD

**Issue by greaterfool** [olive-editor/olive#333]
I know that you can put in and out markers on clips, but it would be really nice if you could put markers on individual clips, video and audio. Specifically for use cases where you might want to mark a specific section of a video for a specific purpose, and another section for another purpose, if that makes sense.

Thanks!

**Comment by goldenbait** [comment]
This would make logging large amount footage in Olive a breeze. A must for documentary work.
Add a search bar that searches for both clip names and marker names and you're all set.
On my wishlist as well!
