### ISSUE TITLE
Shrunken Window upon Initialization

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#334]
For some strange reason whenever I open up Olive (January 2019 | b2ff4db) the window isn't at fullscreen:

![image](https://user-images.githubusercontent.com/5027750/51387463-f230fc00-1ada-11e9-9511-581285070c27.png)

(Cropped from desktop snapshot, scale not at 1:1)

It starts up as a square.

**Comment by itsmattkc** [comment]
This appears to be a likely Qt bug that mostly affects Windows HiDPI users. I've added a workaround in 61f5e13 that should address this.

**Comment by Symbian9** [comment]
Strange, but something similar happen on Linux, but unlike @Corruptinator, I has NO such issue with *Olive* `b2ff4db`

![pic.1](https://i.imgur.com/xVdZXtA.png)

BUT *Olive* `61f5e13` and `20f4b8d` on start **try be "square" too**

![pic.2](https://i.imgur.com/Fuuecsg.png)

![pic.3](https://i.imgur.com/xfk7bU9.png)

**Comment by itsmattkc** [comment]
Hmm I may have to find a different workaround and/or limit it to Windows which it seems to be exclusive to.

**Comment by itsmattkc** [comment]
Tracked down the offending line in the panel construction and this issue should be fixed in 722c2cde3b38952f2b4db9805f502ac419e2af06
