### ISSUE TITLE
the program freezes during video export

### ISSUE THREAD

**Issue by welon68** [olive-editor/olive#343]
I made a short movie, 30min. The program freezes during video export. its possible to fix it ?

**Comment by jonno85uk** [comment]
I too have noticed this issue. The CPU usage is low so it doesn't seem to be an infinite loop somewhere but does indicate the encoding has stopped.

However, I only get this issue when exporting to an mp4, file not mkv, although that may have been a coincidence.

**Comment by jonno85uk** [comment]
> 
> 
> I made a short movie, 30min. The program freezes during video export. its possible to fix it ?

Had you used any speed adjustments of clips?

**Comment by oc1024** [comment]
@jonno85uk Yes, both.

**Comment by welon68** [comment]
latest version. I added a repository to my kubuntu. I think is fresh.

**Comment by welon68** [comment]
olive-editor -v
Olive (January 2019 | Alpha | )

**Comment by technicaljayendra** [comment]
This same happen to me i can't export my video. I made 5 youtube videos and saved them in olive project file please fix thiis issue as soon as possible because i want my videos to export now :(
