### ISSUE TITLE
Add to vertical separator on "Effects" same behaviour as horizontal separator on "Timeline" has

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#346]
![pic.1](https://i.imgur.com/3UsNGa2.png)

**Comment by itsmattkc** [comment]
I'm not sure what this means, is the behavior not the same?

**Comment by Symbian9** [comment]
Not the same, because I can't fully hide left or right sub-widget on "Effects controls" widget.

On "Timeline" I could hide top (videos, images, titles) or bottom (audio tracks) sub-widgets.

**Comment by itsmattkc** [comment]
That's technically a mistake, you're not supposed to be able to do that in the timeline

**Comment by Symbian9** [comment]
Anyway, "Effects controls" need such thing.

I will add more mockaps about what I mean

**Comment by itsmattkc** [comment]
What I'm saying is I'm more inclined to remove that function from the timeline than to add it to the effect controls.

**Comment by Symbian9** [comment]
Well, then I close this issue about "collapsing" sub-widgets.
