### ISSUE TITLE
Request for a "tiles" shader effect

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#347]
I love the optimized sphere effect. It is amazing how I could play 1,000,000 copies of my video in real-time without demolishing my computer. I think there should be a "tiles" effect, like sphere without the distortion

In the proposed "tiles" shader effect, I would like to have the option for the tiles to clamp/mirror the edges of the source video, like this:

![image](https://user-images.githubusercontent.com/40442071/51491520-cc6e5600-1d6b-11e9-980b-a82aaf161117.png)

My reason for a tiles effect is that there are motion-based transitions that I want to make that needs tiled video.

**Comment by BrimsonBhin** [comment]
@itsmattkc that looks really nice! Can't wait to try out the next build

**Comment by itsmattkc** [comment]
Ahh if you're on Windows, you can download the `tile.frag` and `tile.xml` and place them in Olive's effects folder - no compiling necessary. However I'll also update the website builds later today.

**Comment by BrimsonBhin** [comment]
> 
> 
> Does the tile effect in [b4b1b8f](https://github.com/olive-editor/olive/commit/b4b1b8f95c9d14e98b9b813c53894ef4f80a8117) satisfy this?

It does. However, will it be possible for the effect to have a "center" mode where the source is at the center and tiles generate **around** the center of the video, like sphere's _scale_ parameter? Also, it would also be cool to allow like sphere's _center_ parameter.

Basically, like sphere.frag without the distortion and the ability to mirror tiles

**Comment by itsmattkc** [comment]
Try the tile effect in 86464b76e4966afb858c2302559d68cd431bdbfe, it should be much closer to what you're talking about.

**Comment by BrimsonBhin** [comment]
That's just what I needed @itsmattkc , thank you!
