### ISSUE TITLE
Black / Transparent frame in between all clips meant to be a cut

### ISSUE THREAD

**Issue by DaniSeeh** [olive-editor/olive#348]
I am on Alpha 46feccf on Linux Mint 19.1, and when I have two PNGs meet on the timeline so that one is supposed to disappear simultaneous to another appearing, there is a one frame gap where nothing is displayed. This was true both in the preview and in the final render. I attached a little video demoing what I mean as best I can. It can be fixed by putting the image intended to replace one layer above the other and making them overlap by a single frame.
[Demo of Bug.mp4.zip](https://github.com/olive-editor/olive/files/2780503/Demo.of.Bug.mp4.zip)

As I was making that demo of the bug, I realized it does it with video too. It leaves a single black/transparent frame in between the two clips that are supposed to be a cut.

**Comment by itsmattkc** [comment]
Should be fixed in d4d654203dec1712f48a010dcfb999cd397f54f4
