### ISSUE TITLE
Seeking past nested sequences crashes Olive

### ISSUE THREAD

**Issue by oc1024** [olive-editor/olive#351]
I set up a simple sequence consisting a short clip with a GIF image over it. Then tried nesting it under another sequence as the first clip, and as soon as playback stops or when going past the end of the nested sequence seeking with Right key, the following error log is printed:

`[ERROR] Failed to retrieve frame from buffersink. -11 ((null):0, (null))`
`[WARNING] Texture is not valid in the current context.`
`Texture has not been destroyed ((null):0, (null))`
`double free or corruption (out)`
`Aborted (core dumped)`

And Olive closes.

**Comment by itsmattkc** [comment]
584b8670c0535e67366b407a4a6b9098a241a176 should fix this

**Comment by oc1024** [comment]
Now nested sequences have audio, seeking past them does not segfault, but they don't display any video.

**Comment by oc1024** [comment]
I reverted back to commit 584b867 and both issues are fixed. Somewhere between it and the current commit this bug was introduced.
