### ISSUE TITLE
Windows 1.0.0.0 portable builds incomplete

### ISSUE THREAD

**Issue by FredThompsonII** [olive-editor/olive#352]
unzip olive-w64p.zip and try to run it.

You'll get messages these are missing:

libgcc_s_seh-1.dll
libcairo_2.dll

olive-w32p.zip does properly start on a Win64 system.

**Comment by FredThompsonII** [comment]
... also needs libstdc++-6.dll ...

**Comment by itsmattkc** [comment]
Looks like the new frei0r effects needed more DLLs than I was aware of. Should be fixed now.
