### ISSUE TITLE
[Feature Request] Copying All Effect Parameters from One Clip to Another

### ISSUE THREAD

**Issue by DaniSeeh** [olive-editor/olive#355]
It would be awesome to be able to copy all the parameters of effects (e.g. Transform has Position, Scale, Uniform Scale, Rotation, Anchor Point, Opacity and Blend Mode) from one clip to another by either pushing Ctrl + C or right clicking and copying the effect. This is useful for everything from copying and pasting basic color adjustments quickly, to positioning PIP things in the same place over and over again.

**Comment by itsmattkc** [comment]
Olive actually already does this, if you select effects from one clip, use Ctrl+C or Edit > Copy, and then paste them on another clip it'll ask if you want to replace the existing effects (allowing you to just paste the values). However adding "Copy" to the right click menu is probably a good idea to make this clearer.

**Comment by itsmattkc** [comment]
Copy/paste effect menu items added for clarity in 0e3250fb59cef6361b36225af7633113c17cd3d0
