### ISSUE TITLE
[Feature Request] Extra keying effects

### ISSUE THREAD

**Issue by oc1024** [olive-editor/olive#356]
For now, Chroma key is the only keying effect available in Olive.

In addition to it, some more I'd like to see implemented:

- Luma key/using the clip itself as a mask is a common feature of other video editors, and would make many amateur special effects often used by YouTubers and other prosumers possible.
- Another keying effect I think would be interesting is a color threshold i.e. imposing a range for a certain component (HSL, RGB, YCbCr) and making other colors transparent. This would allow for custom bloom (by restricting luminance to the highest values and blurring the filtered image) and much more.

Some more I've thought of, but are guaranteed to become obsolete when masking is implemented:
- Filters for masks with simple shape (rectangles, ellipses, stars) - like Kdenlive's Alpha Shapes, maybe being superseded by something like Render > Shape when masking is done.
- Filter that takes an image mask, offset and scale as input - basically a limited version of full mask support.

**Comment by goldenbait** [comment]
I would also suggest Difference matte - compare the pixels of two clips and remove everything that is static. Lets you isolate a moving character or object easily.

**Comment by oc1024** [comment]
Implemented luminance key and selecting for color in #358 . For the simple shape masks, I don't have the skills necessary to implement them with anti-aliased rotation.

For image masks and difference mattes, I'd need documentation on how to write transitions (Kdenlive effects involving multiple images often hijack the transitions system like masks and blending modes). And they would be easily replaced by proper masking either way.

**Comment by itsmattkc** [comment]
Much of this will be addressed in the node rewrite.
