### ISSUE TITLE
Export video doesn't export transforms / animations

### ISSUE THREAD

**Issue by therealrobster** [olive-editor/olive#361]
I've a video that I've zoomed into, panned, added easing etc on the keyframes (nice system by the way.  Who's the animator on board who knows their stuff?)

When I export though, it simply exports the original video with no transforms.

Ubuntu 18.04

Great work in general, hope the bug report helps

**Comment by itsmattkc** [comment]
Hey, I'm glad you like the keyframing in Olive!

As for your issue, could you provide more information about what you're doing or perhaps provide a video? I've done some tests and the videos I've exported seem to animate correctly.

**Comment by therealrobster** [comment]
OK you can close this.  I just did up a killer demo project to show the problem... and it exported the transforms properly. I'm sorry to waste your time. Must have been a one off thing.  If you can export GIF you've got a loyal user.  It's the only thing I need but for now, I can always export to another format then convert with another tool.  Great work to you all.

**Comment by itsmattkc** [comment]
Haha don't be sorry, it's curious even if it was a one off. I'll close for now but feel free to let me know if you run into it again
