### ISSUE TITLE
Olive tutorials

### ISSUE THREAD

**Issue by RezaSh13** [olive-editor/olive#366]
Hi, when will come olive tutorials?

**Comment by Symbian9** [comment]
Here is one by *'MustardPig'*

- "How I Use Olive to Make the Pokemon Crystal Clear Videos"
  - https://www.youtube.com/watch?v=HqHGA2FdL3Q

**Comment by itsmattkc** [comment]
I haven't had time to produce any, but my other concern is Olive is still changing so rapidly that a tutorial made now could be out of date next week.

**Comment by alcomposer** [comment]
@Symbian9 'MustardPig's' version of Olive is already quite old. I agree with @itsmattkc. However I also think more-is-more, so it can't hurt. Tutorials simply need to stress the changing nature of the software (which is almost any software).
It much easier now that Olive shows the version number bottom left.

**Comment by RezaSh13** [comment]
> Here is one by _'MustardPig'_
> 
>     * "How I Use Olive to Make the Pokemon Crystal Clear Videos"
>       
>       * https://www.youtube.com/watch?v=HqHGA2FdL3Q



> I haven't had time to produce any, but my other concern is Olive is still changing so rapidly that a tutorial made now could be out of date next week.

thanks Symbian9 :)

good for us, itsmattkc; The Olive is very gooooooooood

**Comment by itsmattkc** [comment]
>good for us, itsmattkc; The Olive is very gooooooooood

Thank you! It is definitely my intention to have tutorials readily available (as you can tell from the website), it'll probably just have to wait until Olive is more "feature complete".

**Comment by NathanLovato** [comment]
Hey! I'm a tutor working in Free Software.

Editing with Blender now (as with Python, we could write our own extension to edit our videos really quickly) but I find your project both inspiring and impressive. I'd gladly create a tutorial or two under a copyleft license if you want. I'll just need a few tips to make the most of the available features as we have a completely different workflow compared to the traditional editing experience in Blender. E.g. in Olive I mostly work with JKL/arrows/Ctrl K and Q.

I'm in the middle of a crowdfunding campaign now but please ping me when you need a video tutorial 🙂

Here are two tuts we made for the Blender VSE for ref:
1. Getting started editing in Blender https://www.youtube.com/watch?v=Zcj4onvP06w
2. Color grading in Blender https://www.youtube.com/watch?v=55Jov3VgivY

**Comment by itsmattkc** [comment]
@NathanLovato Hi, that would certainly be appreciated! I do think perhaps it should wait a bit because we're on the brink of quite a few big features, but I can certainly keep you posted when a good time for tutorials would be.

**Comment by NathanLovato** [comment]
@itsmattkc All good, just ping me when you're ready 🙂
I'm in the middle of a Kickstarter anyway, got a lot to do right now 😄

**Comment by Symbian9** [comment]
«Olive Editor - cross dissolve» by *welon68*

- http://www.youtube.com/watch?v=4Vldl_tn4uE

«Olive Video Editor (alpha)» by *Popescu Sorin*

- http://www.tonvid.com/info.php?video_id=l00GbFPm7FM

**Comment by mdmayfield** [comment]
Replying to this thread to get updates - I'm also interested in helping to contribute by producing tutorials.

Are there any sections of Olive that are less likely to change (radically) that might make more sense to cover in a tutorial in the short term?

**Comment by itsmattkc** [comment]
@mdmayfield Sorry about the late response. It's hard to say at the moment, I guess the Timeline behavior is likely to not change significantly any time in the near future.

**Comment by itsmattkc** [comment]
I've created a Wiki page for collecting video tutorials. Feel free to produce and list them there for now: https://github.com/olive-editor/olive/wiki/Video-Tutorials

**Comment by enzogian** [comment]
Hi everybody, talking about tutorials and tips on OLIVE Video Editor, I have opened a fb page and a group in order to share and gather followers and supporters (hope it helps to spread the word on this wonderful software and how to use it ;)
https://www.facebook.com/groups/412394822845471/
