### ISSUE TITLE
Latest 64-bit AppImage build not uploaded to GitHub

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#372]
32-bit uploaded, but 64-bit not uploaded

- https://travis-ci.org/olive-editor/olive/builds/485372058/

**Comment by itsmattkc** [comment]
Seems to have been a one time thing, the latest build has AppImages for both architectures.

**Comment by Symbian9** [comment]
This happen again

- https://travis-ci.org/olive-editor/olive/jobs/487425985

**Comment by itsmattkc** [comment]
I don't know why this happens, but it always gets fixed on the next commit.
