### ISSUE TITLE
Huge effects menu + Effect duplication

### ISSUE THREAD

**Issue by oc1024** [olive-editor/olive#382]
OS: Arch Linux (last updated Jan 19)

When building the latest Olive ( 13b4c22 ), I get the following effects menu:
![image](https://user-images.githubusercontent.com/7990860/51991406-ceca6180-2489-11e9-9041-d170e1d11639.png)

i.e. Submenus are duplicated inside menus.

Not only that, clicking any item applies the effect twice, not once.

This issue was reproducible both on my compilation and on the AppImage.

**Comment by itsmattkc** [comment]
Should be corrected in c69952d2ca79e48fdbbffa1390231d28d43555ee
