### ISSUE TITLE
 window menu missing (Ubuntu 16.04 / olive-editor snap)

### ISSUE THREAD

**Issue by pixelr0** [olive-editor/olive#383]
window menu missing (Ubuntu 16.04 / olive-editor snap)
olive-editor 
Failed to register window menu, reason: org.freedesktop.DBus.Error.AccessDenied ("An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.434" (uid=1000 pid=22404 comm="/snap/olive-editor/1/bin/Olive ") interface="com.canonical.AppMenu.Registrar" member="RegisterWindow" error name="(unset)" requested_reply="0" destination="com.canonical.AppMenu.Registrar" (uid=1000 pid=4179 comm="/usr/lib/x86_64-linux-gnu/unity/unity-panel-servic")")
Failed to unregister window menu, reason: org.freedesktop.DBus.Error.AccessDenied ("An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.434" (uid=1000 pid=22404 comm="/snap/olive-editor/1/bin/Olive ") interface="com.canonical.AppMenu.Registrar" member="UnregisterWindow" error name="(unset)" requested_reply="0" destination="com.canonical.AppMenu.Registrar" (uid=1000 pid=4179 comm="/usr/lib/x86_64-linux-gnu/unity/unity-panel-servic")")
Failed to register window menu, reason: org.freedesktop.DBus.Error.AccessDenied ("An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.434" (uid=1000 pid=22404 comm="/snap/olive-editor/1/bin/Olive ") interface="com.canonical.AppMenu.Registrar" member="RegisterWindow" error name="(unset)" requested_reply="0" destination="com.canonical.AppMenu.Registrar" (uid=1000 pid=4179 comm="/usr/lib/x86_64-linux-gnu/unity/unity-panel-servic")")
libpng warning: iCCP: known incorrect sRGB profile

~$ snap info olive-editor
name:      olive-editor
summary:   Professional open-source NLE video editor
publisher: MattKC (itsmattkc)
license:   unset
description: |
  Olive is a non-linear video editor for Windows, macOS, and Linux.
snap-id: TA1somyaZMIyltyX9y0LtDfpbjVcMdDD
channels:
  stable:    –                            
  candidate: –                            
  beta:      –                            
  edge:      60e53d7 2018-12-22 (1) 129MB -

![menu](https://user-images.githubusercontent.com/333589/51997808-27b4ec80-24c0-11e9-874d-deedf4edcfb7.png)

**Comment by itsmattkc** [comment]
Admittedly, the snap hasn't been updated in some time. I'll try to fix and update tomorrow, but for now see if you get the same issue with the AppImage.

**Comment by itsmattkc** [comment]
I've updated the Snap to the newest build. Please try again with that.

**Comment by pixelr0** [comment]
still nope on Ubuntu 16.04

~$ olive-editor 
[WARNING] libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
[INFO] Initializing effects... ((null):0, (null))
[INFO] Finished initializing effects ((null):0, (null))
[WARNING] Failed to register window menu, reason: org.freedesktop.DBus.Error.AccessDenied ("An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.180" (uid=1000 pid=9052 comm="/snap/olive-editor/2/bin/olive-editor ") interface="com.canonical.AppMenu.Registrar" member="RegisterWindow" error name="(unset)" requested_reply="0" destination="com.canonical.AppMenu.Registrar" (uid=1000 pid=4947 comm="/usr/lib/x86_64-linux-gnu/unity/unity-panel-servic")") ((null):0, (null))
ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
[WARNING] Failed to unregister window menu, reason: org.freedesktop.DBus.Error.AccessDenied ("An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.180" (uid=1000 pid=9052 comm="/snap/olive-editor/2/bin/olive-editor ") interface="com.canonical.AppMenu.Registrar" member="UnregisterWindow" error name="(unset)" requested_reply="0" destination="com.canonical.AppMenu.Registrar" (uid=1000 pid=4947 comm="/usr/lib/x86_64-linux-gnu/unity/unity-panel-servic")") ((null):0, (null))
[WARNING] Failed to register window menu, reason: org.freedesktop.DBus.Error.AccessDenied ("An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.180" (uid=1000 pid=9052 comm="/snap/olive-editor/2/bin/olive-editor ") interface="com.canonical.AppMenu.Registrar" member="RegisterWindow" error name="(unset)" requested_reply="0" destination="com.canonical.AppMenu.Registrar" (uid=1000 pid=4947 comm="/usr/lib/x86_64-linux-gnu/unity/unity-panel-servic")") ((null):0, (null))
[WARNING] QLayout: Attempting to add QLayout "" to DemoNotice "", which already has a layout ((null):0, (null))
[WARNING] libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
[WARNING] QObject::connect: No such signal DemoNotice::finished() ((null):0, (null))


also tested on 19.04 and there the menu is fine https://www.youtube.com/watch?v=l00GbFPm7FM

**Comment by oc1024** [comment]
As far as I know, it's necessary to add `unity7` to the plugs section in the `snapcraft.yaml` file:

https://docs.snapcraft.io/the-unity7-interface/7786

Otherwise the app will not be able to perform the necessary IPC with the desktop environment to show the global menu.

**Comment by pixelr0** [comment]
^^ yeah, something like this 
plugs:
    - desktop
    - desktop-legacy
    - wayland
    - unity7

https://github.com/olive-editor/olive/blob/master/snap/snapcraft.yaml

**Comment by itsmattkc** [comment]
Ahh okay thanks for the heads up, testing now...

**Comment by itsmattkc** [comment]
That seems to have done it, the newest snap should have menus on 16.04.
