### ISSUE TITLE
Shortkey for showing project preview in fullscreen

### ISSUE THREAD

**Issue by ahangarha** [olive-editor/olive#387]
Though there is option for playing the preview in full-screen mode, but there is no option to assign short-key to it.

I am so addicted in using backtick for this particular purpose. I hope to see this feature soon in this amazing software.

**Comment by ahangarha** [comment]
I use backtick: `

It is used to maximizing the active tab/windows/pannel/... in Premiere and because of that, I use it to directly watch the video preview in full-screen mode.

**Comment by itsmattkc** [comment]
Ahh, yes I know that function, though that's slightly different from what you're describing. I assume having said maximizing panel functionality would be preferable since it would be functionality that works on all panels.

**Comment by ahangarha** [comment]
forget about maximizing panel. I just mentioned that to say why backtick is relevant shortkey for this purpose. I think if it be used to make video preview fullscreen, it is enough.

**Comment by itsmattkc** [comment]
To be honest, I've wanted that maximize panel functionality for a while anyway. I've gone ahead and added both in 0513749b9d606d085d0752c192788d9e68f796f1, backtick to maximize panel, and a function to make the focused viewer full screen (which can be given whatever keyboard shortcut you wish in the Preferences).

**Comment by ahangarha** [comment]
This feature is available on Windows version but not for GNU/Linux! (even on snap!) any issue?

**Comment by oc1024** [comment]
Snap is actually the most outdated version. Please download 0.1.0 from the Releases page.

**Comment by ahangarha** [comment]
This is what I get from Snap:
```
➜  ~ snap info olive-editor
name:      olive-editor
summary:   Professional open-source NLE video editor
publisher: MattKC (itsmattkc)
license:   unset
description: |
  Olive is a non-linear video editor for Windows, macOS, and Linux.
commands:
  - olive-editor
snap-id:      TA1somyaZMIyltyX9y0LtDfpbjVcMdDD
tracking:     edge
refresh-date: 2019-01-31
channels:
  stable:    –                            
  candidate: –                            
  beta:      –                            
  edge:      c8aec60 2019-01-31 (2) 173MB -
installed:   c8aec60            (2) 173MB -
```
I can use ` on windows but not on my Olive installed via snap on Kubuntu 19.04
