### ISSUE TITLE
Blocky Soundwaves Preview

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#388]
I haven't tried out the new recent Olive Alpha build yet but while the sound works the preview isn't cooperating:

From `229d01a`:

![image](https://user-images.githubusercontent.com/5027750/52091889-c564f600-256a-11e9-83fd-dc3a76b63685.png)

The audio preview looks heavily blocked, even the timeline preview is affected. Just heads up.

**Comment by Corruptinator** [comment]
Ah, I see. Time to make space in the hard drive I guess. Only got 2Gb of space left.

**Comment by itsmattkc** [comment]
Haha it'll probably be okay, Olive's waveforms are admittedly conservative, and some sort of simple compression on them might be good in the future.

**Comment by itsmattkc** [comment]
Added control over waveform (and thumbnail) resolution in 3b276fea40268c608d2d9a19542279a75ad218bb. The waveforms can now be as detailed or as blocky as the user's heart desires!
