### ISSUE TITLE
Project search field needs a quick reset button

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#389]
Searching in the project bin is great, but would do with a button that would quickly remove all text in the search field. Typically, it's located at the right edge of the field and has 'X' for caption.

**Comment by itsmattkc** [comment]
I had thought of this but wasn't aware if Qt had built-in functionality for this or if it would require a custom solution. Turns out Qt provides this functionality, so I've enabled it in 61d58d0f40e48c91c0bb3b70a1bc85e39a88c76f
