### ISSUE TITLE
Problems with the mouse pointer

### ISSUE THREAD

**Issue by RafaMartorell** [olive-editor/olive#396]
I just downloaded the latest version "Olive-d5df44c-x86_64.AppImage" and I notice that clicking the right mouse button on a numeric value in the video effect panel leaves an option to paste, but the mouse pointer disappears and I I am forced to close the application. In the "Olive-6270b99-x86_64.AppImage" version this did not happen. I even liked this version "6270b99" because the window was resized alone and the values were better adjusted taking better advantage of the space on the screen.
I tested it on three different distributions, Linux Mint 18.3 Cinnamon, Linux Mint 19 Xfce and Lubuntu 18.04 and in all three I had the same error.
I also wanted to mention that I would like to translate this magnificent application into Spanish and when a stable version of the application is finished I will make a series of tutorials on Olive Video Editor, I had originally thought only in Spanish.
**I think it's an excellent job, I like it a lot.**

**Comment by oc1024** [comment]
I think you and I are facing the same bug. Sometimes a right click on the wrong objects makes my mouse cursor disappear and I have to restart the program. Maybe you managed to find the cause.
