### ISSUE TITLE
Spanish translation and tutorials in this language

### ISSUE THREAD

**Issue by RafaMartorell** [olive-editor/olive#397]
When I have time I write tutorials on multimedia applications in GNU / Linux, Olive I liked it a lot, so I offer to translate the app into Spanish and translate it or not if I intend to do tutorials on Olive when a stable version is released. I do not rule out doing them also in English but not being a native I feel insecure because of my bad pronunciation. Currently I only do the tutorials in Spanish.

**Comment by oc1024** [comment]
@pgifernandez is working on this, I think. You might want to work with him.

**Comment by itsmattkc** [comment]
Translations are definitely appreciated and the infrastructure has been mostly implemented now (see #276), but yes @pgilfernandez has mentioned working on a Spanish translation so I recommend discussing with him.

**Comment by itsmattkc** [comment]
I think this issue should be folded into #276 just for containment, but I very much look forward to updates on a Spanish translation.

**Comment by pgilfernandez** [comment]
I’m on it, it’s still not finish though...
Probably next week I will PR it.

From that v1.0 @RafaMartorell can help to review and improve it =)

**Comment by RafaMartorell** [comment]
@pgilfernandez It will be a pleasure to help you. I can review and contribute to what you tell me. Consider me an assistant.

**Comment by RafaMartorell** [comment]
The translation into Spanish is 100% completed using the git wizard "Qt Linguist".
Not being an expert on Github, I do not know if I followed the correct steps to upload the finished ts file. So I've hosted it in my Google Drive account for download and that you can put it in the project so that Spanish-speaking people can enjoy the application in this language.
The file for download is at: https://drive.google.com/open?id=1fMWHvA2iA6Yr-fKfRknYBMNyDTGEwOkU

I have also attached the file here
[olive-es_ts-file.zip](https://github.com/olive-editor/olive/files/3342691/olive-es_ts-file.zip)

Thank you and forgive my little experience in Github

**Comment by RafaMartorell** [comment]
### **Spanish translation completed 100%**

**Comment by RafaMartorell** [comment]
@pgilfernandez I put here the .qm file in case you want to try it, so you can do it by starting the application referring to the file with the following line from the terminal:
"olive-editor --translation <qm-file>"
Or replacing this file in the flatpak installation folder:
"/var/lib/flatpak/app/org.olivevideoeditor.Olive/current/3494f8dd1b9c6356de07984d140a418b2a27701f58accda99e53338b36dfdf13/files/share/olive-editor/ts"
It is in case you want to try it and in case you have any objection, thank you and do not feel obligated to do so, if you can, and if you can not too.
[olive_es.qm.zip](https://github.com/olive-editor/olive/files/3345619/olive_es.qm.zip)
