### ISSUE TITLE
Only English available in the list of translations

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#407]
It's currently impossible to switch to a different supported language: English is the only option in the drop-down list.

**Comment by itsmattkc** [comment]
I should be able to add a couple lines to the Qt project file that will deploy the language files correctly (which should in turn correctly update most packaging methods - AppImage, apt, snap, etc. - to do so too)

**Comment by itsmattkc** [comment]
Fixed on most platforms in 749c4d8ff8d0a07a3d35a80df9b940318f55a395
