### ISSUE TITLE
Proxy generation crashes Olive when using MP4

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#409]
I generated an MP4 file with Olive, and imported it back into Olive, then started conversion of it into a Proxy.

Olive crashes with error:
[mp4 @ 0x7f2ab0007f00] Could not find tag for codec prores in stream #0, codec not currently supported in container

**Comment by itsmattkc** [comment]
Does 5f89e6dca93ffbcb0119ffde49369cff024005a6 fix this?

**Comment by alcomposer** [comment]
Yes.
