### ISSUE TITLE
Sliced audio clips play the wrong part of audio

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#41]
Sliced audio clips always play the audio from the beginning of the source video, regardless of where you cut it from. 

maybe this is a [feature](https://drive.google.com/open?id=10eRI-oEHgVEVbM0qTj0KMBk9z9JNuVYB)

MICHAEL CAINE MICHAEL CAINE MICHAEL CAINE MICHAEL CAINE MICHAEL CAINE 

*EDIT: video meta data, if h264 is part of the issue

Double Jump\Arkham City LP\Ep 1\Ep1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2013-03-23T11:22:27.000000Z
  Duration: 00:05:23.31, start: 0.000000, bitrate: 3156 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 1280x                                                         720 [SAR 1:1 DAR 16:9], 2993 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2013-03-23T11:22:27.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, flt                                                         p, 157 kb/s (default)
    Metadata:
      creation_time   : 2013-03-23T11:22:27.000000Z
      handler_name    : Mainconcept MP4 Sound Media Handler
[INFO] Clip opened on track 1
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'E:\Users\David\My Documents\Film Stuff\                                                         Double Jump\Arkham City LP\Ep 1\Ep1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2013-03-23T11:22:27.000000Z
  Duration: 00:05:23.31, start: 0.000000, bitrate: 3156 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 1280x                                                         720 [SAR 1:1 DAR 16:9], 2993 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2013-03-23T11:22:27.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, flt                                                         p, 157 kb/s (default)

**Comment by itsmattkc** [comment]
Fixed
