### ISSUE TITLE
[FR] Olive Background Process Manager

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#410]
As Olive is growing, there are increasingly more background tasks happening. 

Having a status window, (and/or throber) would allow the user to see what is happening, what is taking too long, and ability to pause, or cancel the jobs.

Example viewable tasks:
* Preview gen
* Waveform gen
* Proxy gen
* Optimised media gen
* Rendering (timeline and output)
* Analysis
* Import conversion

**Comment by naj59** [comment]
@oc1024 You mean something like [this](http://doc.qt.io/qt-5/qtwinextras-musicplayer-example.html)?

**Comment by oc1024** [comment]
@naj59 Yes, that's what I meant by Taskbar progress.

**Comment by naj59** [comment]
@oc1024 This also wouldn‘t be bad while exporting. I think notifications would be too much for this point. Premiere, Resolve and other pro NLEs doesnt offer this too.

**Comment by oc1024** [comment]
I'm used to Kdenlive (currently the major prosumer NLE for Linux) and it has only two notifications: for "ready to render", "render finished". I don't think this is overkill and it's especially useful to the prosumer market Olive also targets (and has the most success with at the moment), since they'll be using their machine for other stuff while video renders on the background.

**Comment by naj59** [comment]
@oc1024 for those two that would be fine (not too much notifications was my point). The problem is that every platform has an own notification system, and Qt does not offer a solution to that (what I have explored).

**Comment by naj59** [comment]
Also I suggest to add a simple tone when exporting has finished just as FL Studio does this. It does not distract and if you can recognize the sound as one of Olive‘s its just like as a notification.

**Comment by oc1024** [comment]
> Also I suggest to add a simple tone when exporting has finished just as FL Studio does this. It does not distract and if you can recognize the sound as one of Olive‘s its just like as a notification.

That seems to be an elegant cross-platform solution that won't add dependencies.

**Comment by prokoudine** [comment]
Does https://doc.qt.io/QtApplicationManager/qml-qtapplicationmanager-notification.html work on Linux only?

**Comment by naj59** [comment]
@prokoudine This is QML.

**Comment by oc1024** [comment]
I found an easy way to implement this on Linux. `libnotify`, despite its name, is an external executable that can send notifications on behalf of something else. For example, a terminal command can be sent in this format:

`notify-send 'top text' 'bottom text' -i icon`
![image](https://user-images.githubusercontent.com/7990860/52168397-b9af3600-2708-11e9-91ee-da4fa7632a47.png)
 
By replacing text and icons, we get
![image](https://user-images.githubusercontent.com/7990860/52168436-34785100-2709-11e9-8120-935872621dc4.png)

SnoreNotify from KDE has a subproject called SnoreToast which is basically `libnotify` for Windows, although it needs the parent application to have a start menu shortcut with extra metadata (SnoreToast provides a `--install` mode that does that) so Windows actually identifies the notification as coming from it:

https://github.com/KDE/snoretoast
https://docs.microsoft.com/windows/desktop/shell/appids

**Comment by naj59** [comment]
The point is, does it make sense to add up dependencies for such a small thing? Otherwise we could implement or own Qt based cross platform solution.

**Comment by oc1024** [comment]
They could be made optional though. There's nothing wrong with a `notify_user()` routine that checks if libnotify or Snoretoast are available and uses them if yes or falls back to a standard dialog box if not.
