### ISSUE TITLE
[Feature request] Colour correction with curves

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#415]
I really love your project, but in my opinion it's missing an essential feature:
colour correction with curves!
Please consider adding it to make colour correction much faster!
Premiere Pro, Davinci Resolve and LWKS have it and I use it in my own workflow!
Thank you in advance and keep up the gread work!

Gimp:
![curves-dialog-original](https://user-images.githubusercontent.com/45124869/52170152-77f0b080-2745-11e9-8733-9c061156f547.png)

**Comment by itsmattkc** [comment]
This has been planned for quite some time, I'll hopefully be implementing a fuller suite of color correction tools within the near future.

**Comment by libalis** [comment]
Thant would be great!
Thank you!

**Comment by libalis** [comment]
[CLOSE ISSUE] Reason: Duplicate of Issue #452

**Comment by ChameleonScales** [comment]
Sorry I'm a little confused. This issue was closed as duplicate of #452 but then this other one was closed for not being specific enough, yet I still don't see RGB curves in the latest build. Am I missing it or should we reopen this issue ?
