### ISSUE TITLE
Add ability to save custom effects

### ISSUE THREAD

**Issue by NathanSalapat** [olive-editor/olive#418]
Maybe this already exists but I couldn't find it.

It would be nice if we could save keyframes from a specific effect and add that effect+keyframes to other clips.

If you are using a the same effect on many clips, and they all need to be animated it would save a lot of time to not need to do the animation on every clip.

**Comment by NathanSalapat** [comment]
I saw that, and it works when the effect is in the same project, but when you have many projects that you want to use the same effect in you need to recreate it in each project.
KDenLive has an option to save a custom effect which basically saves the effect and keyframes and lets you use them in other projects.
I can always make a template file and do the copying and pasting method for projects too.

**Comment by itsmattkc** [comment]
So you mean more like saving a preset into a file that can be reloaded into other projects? This would actually be fairly easy to implement with the current infrastructure.

**Comment by NathanSalapat** [comment]
First thanks for getting this implemented!
On Linux when saving the effect settings it doesn't give the file an extension automatically. When loading an effect it only will show files with the .xml extension, so I had to manually add the extension to the file, but outside of that it's working perfectly.

**Comment by itsmattkc** [comment]
4812a45cf47617f8fbe8591b8049fd4239c39e35 should fix that
