### ISSUE TITLE
Can't add effects to a split clip

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#42]
Also if the transform effect is changed from default, the split clip will not inherit the transformation. In addition, the split clip's position is offset with all effects removed and no way to add effects to it.

**Comment by itsmattkc** [comment]
This was actually a combination of two bugs:

1. When clips split into two, the second of those clips would not inherit any of the effects of the first.
2. The "Add Effect" button had no real function.

Both of these have now been fixed.
