### ISSUE TITLE
Plural forms

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#422]
The way some of the user-visible messages are formed in the source code is not plural forms friendly for translators.

While English has two plural forms, other languages have 3, 4, and possibly more.

English:

1 frame, 22 frames, 38 frames — two forms

Russian:

1 кадр, 22 кадра, 38 кадров — three forms

So far, I've only stumbled upon this:

project/media.cpp:

```
						} else {
							tooltip += QCoreApplication::translate("Media", "%1 fields (%2 frames)").arg(
										QString::number(f->video_tracks.at(i).video_frame_rate * f->speed * 2),
										QString::number(f->video_tracks.at(i).video_frame_rate * f->speed)
									);
```

Both '%1 fields' and '%2 frames' should be translated separately from each other and with support for plural forms.

Please see e.g. http://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals for more technical info.

**Comment by itsmattkc** [comment]
I've changed these two examples to what I believe should work. Let me know how it goes or if you find any more examples!
