### ISSUE TITLE
[Feature request] Save ui elements scaling

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#424]
If you e.g. make the Project: Name column wider it doen't save that setting!
It would be nice if it would save the ui elements scaling in the .ove file or in olive itself!
Thank you in advance and keep up the great work!

**Comment by DaniSeeh** [comment]
Oh yeah this would make life much more convenient. I find myself resizing all the panels every time I open Olive haha

**Comment by oc1024** [comment]
Like Blender files?

**Comment by naj59** [comment]
Would be more specific to any project. First option would be to save it in ``.ove`` files, second option would be to create something like "Workspaces" for each situation.

**Comment by libalis** [comment]
someone has to alert him to this problem because he either ignored it or just missed it

**Comment by naj59** [comment]
@libalis Hey hey. This is a feature request and we‘re currenly in alpha. This „problem“ shouldn‘t be a priority. First he is going to fix the current issues that are appearing, this is a much bigger „problem“ than that, although it would be nice to have.

**Comment by libalis** [comment]
yes I understand and apologize! I just have the fear that he did not notice this topic, because he always answers otherwise!

**Comment by itsmattkc** [comment]
Sorry for not getting back to this issue sooner, Olive does have a small amount of layout saving, e.g. if you place a panel somewhere else, it should be in the same general area the next time Olive loads. Unfortunately I haven't managed to wrangle them into more specific saving/restoring just yet, but this can be done eventually I'm sure.

**Comment by libalis** [comment]
That would be nice!

**Comment by itsmattkc** [comment]
Done in eb4c2fdad382a16bf39fce4f25b2828bd088f972
