### ISSUE TITLE
[Feature request] Audio Noise Reduction and EQ

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#428]
Is it possible to "fork" the genius Audacity Noise Reduction feature over to Olives audio settings?
And is it planned to ad an audio EQ?
That would be so nice!
Thank you in advance and keep up the great work!

**Comment by itsmattkc** [comment]
Currently, extra audio effects are a low priority since Olive supports VST 2 on all platforms. For now, I recommend searching for VST plugins that will accomplish what you wish.

**Comment by DaniSeeh** [comment]
@itsmattkc want me to write up an FAQ? I feel like some of these questions you have to answer a dozen times haha. Just so people have a place to check first.

**Comment by itsmattkc** [comment]
@DaniSeeh That may be good, I can make it a page on the Wiki.

I do see value in having more internal effects, but since Olive already has access to almost all VST plugins out there (and hopefully LV2 soon), I think there are higher priorities.

**Comment by dimitarsp** [comment]
I would like to second the fact of having some very basic audio effects - EQ & Normalize included. I tried the VST mentioned above - Fablifter, and when I loaded it, Olive crashed. For non-advanced audio editing it would be really useful to know that doing a slight adjustment of audio would not create issues that would crash Olive.

**Comment by Simran-B** [comment]
The VST host does not handle all events, which could well be the reason why the plugins crash.

Maybe a third-party plugin host like https://github.com/falkTX/Carla could be integrated?

**Comment by dimitarsp** [comment]
Just to report further. I have tried a series of VST EQ plugins, and with all of them Olive Editor Crashed. Do you guys have some that you can recommend that you have gotten to work with Olive Editor?

**Comment by Simran-B** [comment]
Some worked for on Windows: https://github.com/olive-editor/olive/issues/890#issuecomment-488632672

**Comment by dimitarsp** [comment]
> Some worked for on Windows: [#890 (comment)](https://github.com/olive-editor/olive/issues/890#issuecomment-488632672)

Thanks. Finally found an eq plugin that works on windows - https://sonimus.com/products/soneq/
