### ISSUE TITLE
[UI] Optional display of marker names

### ISSUE THREAD

**Issue by prokoudine** [olive-editor/olive#433]
For quicker navigation, it could be useful to have an optional display of markers' names, similar to what Ardour does, for both timeline markers and clip markers:

![image](https://user-images.githubusercontent.com/57467/52193231-3bb17300-285f-11e9-8efe-07e3f34360a0.png)

When labels overlap, they could be ellipsized.

**Comment by itsmattkc** [comment]
Merging into #1690
