### ISSUE TITLE
Impossible activate timeline tools via menu "Tools"

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#435]

**Comment by itsmattkc** [comment]
You may have to clarify what this means.

**Comment by Symbian9** [comment]
Can't switch timeline tools via menu — impossible activate items shown in the yellow box on screenshot

![pic.1](https://i.imgur.com/HTwuFu7.png)

**Comment by itsmattkc** [comment]
Also should be fixed in 05e431ef6ef6d2241c70ed36f40581d45dbe2210
