### ISSUE TITLE
"Graph Editor" window not shown in context menu

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#436]
While it not opened via menu "Window > Graph Editor" for the first time

**Comment by itsmattkc** [comment]
You may have to clarify what this means.

**Comment by Symbian9** [comment]
Screenshots

![pic.1](https://i.imgur.com/gLX1nD8.png)

![pic.2](https://i.imgur.com/rVHEFy3.png)

**Comment by itsmattkc** [comment]
I'll be honest, I'd never seen this context menu before these screenshots. It appears to be a convenience menu provided by Qt and I don't really control its contents. I'd be more inclined to find a way to disable it than to "fix" this, as I already provide access to this functionality through the Window menu.

**Comment by Symbian9** [comment]
> I'll be honest, I'd never seen this context menu before these screenshots

This is standart Qt context menu always opened if mouse-right-click on menu string or any widget/window title area.

**Comment by itsmattkc** [comment]
I guess there's no real harm in having it.
