### ISSUE TITLE
Long clip names breaks titles of tabbed windows

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#441]
It breaks not only background tabs labels, but breaks current active tab label too.

![pic.1](https://i.imgur.com/0poQ0Lx.png)

**Comment by itsmattkc** [comment]
Sorry, what's broken? They just look ellipsized.

**Comment by Symbian9** [comment]
> what's broken?

I said: titles of other tabbed windows broken (not only titles of other inactive tabs, but title of current tab too).

**Comment by itsmattkc** [comment]
I haven't (intentionally) set anything as far as that goes, could it just be Qt trying to compensate for the long name?

**Comment by Symbian9** [comment]
### Expected behavior

Here is possible solution

![pic.1](https://i.imgur.com/DAC17zk.png)

**Comment by itsmattkc** [comment]
I honestly don't really think this is much of a problem. I'd prefer to keep information in the tabs so one has a chance of seeing what's in them without having to switch to them (would be especially useful at a time when multiple Timeline panel instances could be opened for multiple sequences so the user doesn't have to click through each one to figure out what it is. If anything I'd rather remove the subtitle bar, but there isn't yet a way to close/undock the panels without it.

**Comment by Symbian9** [comment]
> I honestly don't really think this is much of a problem

Then there should be an option in preferences dialog (enabled by default)

- [x] "Show extra details in titles of tabbed windows"
