### ISSUE TITLE
Improve/Change tools buttons order on "Timeline" window

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#442]
> **NOTE**: It would be cool if user could setup buttons order on toolbars manually.

### Actual behavior

![pic.1](https://i.imgur.com/sX9d9ww.png)

**Comment by Symbian9** [comment]
### Expected behavior (little fixed)

![pic.1](https://i.imgur.com/ln05rMB.png)

**Comment by alcomposer** [comment]
Just for an example of this concept done correctly, check out Krita. The tool bars on the left are able to reflow based on groups. Krita is also developed in Qt.

**Comment by alcomposer** [comment]
I worked on this, allows tool re-flow groups:
https://github.com/alcomposer/olive/commit/75aa92b2a41febe4258dd0831a4f5f7ed040b1e1

Small issue with bottom [+][-] getting too low & currently no ability to re-arrange.

**Comment by alcomposer** [comment]
I just noticed that the master branch also has the issue of tools getting cut off on bottom. I don't know exactly what that is.  Attached current Master branch cut off issue:
![issue](https://user-images.githubusercontent.com/12004932/52520344-7c264c00-2cb8-11e9-901e-fd5fa40518fe.png)

**Comment by itsmattkc** [comment]
This feels pretty inconsequential. Maybe this can be revisited if more buttons are added later on.
