### ISSUE TITLE
Area of zoomed views look broken

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#443]
> **NOTE**: "Media Viewer" window is tabbed; "Sequence Viewer" window is un-tabbed.

### First example (windows not fully filled if fit views)

- Views fit to windows

![pic.1](https://i.imgur.com/sbDzDNW.png)

- Views zoomed: media to 400%; sequence to 150%

![pic.2](https://i.imgur.com/DhDsPy9.png)

### Second example (windows resized to be fully filled if fit views)

- Views fit to windows

![pic.3](https://i.imgur.com/z8VOs1Z.png)

- Views zoomed: media to 400%; sequence to 150%

![pic.4](https://i.imgur.com/LSZMWnE.png)

**Comment by Symbian9** [comment]
This issue not fixed (incompletely fixed) in `fc96ad7`!

P.S.: I will add more details and screenshot later.

**Comment by itsmattkc** [comment]
Oh, are you talking about the viewer maintaining the same aspect ratio as the source when zoomed in?

**Comment by Symbian9** [comment]
> Oh, are you talking about the viewer maintaining the same aspect ratio as the source when zoomed in?

Something like that

![pic.1](https://i.imgur.com/F9Grre4.png)
