### ISSUE TITLE
[Feature Request] Video effect parameters could be synced with audio amplitude

### ISSUE THREAD

**Issue by danielfernandzz** [olive-editor/olive#450]
Would be great if you could provide an option to sync effect parameters to the audio amplitude. This will make Olive a great option for making music visualizers (as most music visualizer softwares are expensive). 

Like whenever the music becomes louder (like at the instance when the kick drum hits), the value of certain video parameter could be increased (say the "scale" parameter of the transform effect). We could have the option to link any audio clip with any parameter. 

Also, you guys are doing an amazing job, can't wait to see Olive becoming the best video editor of all time! :)

**Comment by elsandosgrande** [comment]
Second that!

**Comment by itsmattkc** [comment]
This will be addressed in the node rewrite.
