### ISSUE TITLE
[Issue] Frei0r shows B G R as effects

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#453]
Frei0r uses letters to split the effect into "groups", but these letters like B are shown as effects in Olive which confused me a lot!
Would be nice if you could fix that!
Thank you in advance and keep up the great work!

**Comment by itsmattkc** [comment]
B, G and R are actually effects that isolate the blue, green, and red channels respectively - I'm not sure showing them is a flaw.

Hovering the mouse over effects will provide descriptions of each.

**Comment by alcomposer** [comment]
I think it may make more sense if the Frei0r menu was ordered in a type way, not alphabetical. That way R, G, B would be next to each other? 
Categories like: Color, Distort, Scopes, Analysis, Generators etc.

I'm sure that there already are effects category metadata in Frei0r

**Comment by itsmattkc** [comment]
Frei0r does *not* have effect categories unfortunately or else I would have implemented them. See https://frei0r.dyne.org/codedoc/html/structf0r__plugin__info.html

**Comment by alcomposer** [comment]
Sorry @itsmattkc, I haven't looked into the spec, but having used other plugin formats, metadata tends to be very important. 
I don't think `plugin_type` will be useful, as it only has 4 enums.

**Comment by itsmattkc** [comment]
Haha don't worry, I was surprised myself that there was no category-like field. I even limit the "plugin type" to filters since the others didn't really make sense in context of an NLE.

**Comment by itsmattkc** [comment]
Haha don't worry, I was surprised myself that there was no category-like field. I even limit the "plugin type" to filters since the others didn't really make sense in context of an NLE.

**Comment by alcomposer** [comment]
I wonder if it's worth discussing this on https://github.com/dyne/frei0r.

**Comment by naj59** [comment]
Extending the struct would be an idea or creating another ``plugin_category``.

@alcomposer
Think this would be more a topic over there, the problem is, how many people are updating their plugins to include. If you say the „host add more functonality“ we could make something like a list were plugins are sorted after category which is then used by Olive to implement categories. 

Or atleast give the user the ability to sort them in groups just like in FL Studio. I can create own groups for example my „favorite“ or „most used“ plugins/effects.

**Comment by itsmattkc** [comment]
Potentially this is a discussion topic for there, but yeah as it says it's intentionally very minimal. Some form of grouping or categories would be nice, but even if the spec was updated to include them, there's no guarantee any existing plugins would be updated to comply.

For Olive the best (possibly only) solution to that would be as @naj59 says, letting the users sort/group them manually.
