### ISSUE TITLE
OpenFX Support

### ISSUE THREAD

**Issue by 1div0** [olive-editor/olive#456]
Please consider support for the [OpenFX](http://openeffects.org/) image processing plug-in standard.

**Comment by naj59** [comment]
Isn't this more for compositing/VFX like [Natron](https://github.com/MrKepzie/Natron)?

**Comment by 1div0** [comment]
It depends. The OpenFX is well suited for compositing as well as editing.

**Comment by naj59** [comment]
@1div0 Ah, I see. Sony Vegas is also integrating it. I am wondering why Premiere and FCPX does not integrate them. Could be an outstanding feature for Olive.

**Comment by alcomposer** [comment]
FCPX has it's own proprietary plugin system: FXPlug. However I believe there exist wrappers for PP...

**Comment by itsmattkc** [comment]
I have heard of OpenFX. I haven't properly looked into it, but it does seem powerful.

@alcomposer Hmm I wonder if that would require reverse-engineering (and I assume it's Mac-exclusive). There's obviously documentation for writing FxPlug plugins but it's less clear about hosts (perhaps it provides enough information to write a host either way).

**Comment by alcomposer** [comment]
@itsmattkc I have used FxPlug for GLSL effects. The developers at www.vuo.org have released an OpenFX wrapper for their real-time software Vuo. Very cool. But I believe it was quite allot of work.

I don't think FxPlug will give Olive anything that it doesn't have already. OpenFX however is very exciting, as there are already many fantastic professional plugins.

Neat Video comes to mind: https://www.neatvideo.com/features/version-history/nv4ofx
Which is already Linux compatible!

**Comment by BrimsonBhin** [comment]
Closing this to make #335 the main thread for APIs
