### ISSUE TITLE
Olive for Android (mobile, tablet)

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#459]
As Qt5 apps could be compiled for Android, it would be cool create *Olive* for Android devices (as long term task)

**Comment by naj59** [comment]
Please no. Editing on any mobile device is a nightmare. The only "tablets" were such type of small editing is useful is on iPad Pro and Microsoft Surface. No android phone and tablet could ever handle the performance needed by a full features professional NLE. Thats why Adobe for ex. is pushing out no "real" Premiere onto these platforms.

**Comment by Symbian9** [comment]
> Please no

DON'T PANIC!

Adroid version would be just as additional port of Olive, and NOT as replacement for Olive desktop version.

**Comment by Symbian9** [comment]
> No android phone and tablet could ever handle the performance needed by a full features professional NLE.

My actual PC, that used now for testing *Olive*, has less performance than my actual Android phone.

**Comment by naj59** [comment]
@Symbian9 Why add extra work for something which is probably unmaintainable?

> My actual PC, that used now for testing Olive, has less performance than my actual Android phone.

Yes. But probably then you will also get problem on both problems if Olive reaches 1.0 stable.
I don't give something about that octa-core 8GB ram advertising promise, even though you should never compare desktop with mobile technology. Any PC having just a dual-core with 8GB ram could run down that "octa-core" thing. Rendering performance on these platforms is complete inacceptable (I've coming from this sector, building 2d and 3d games for Android). 

Imagine exporting a 4K 60fps movie... also the "battery" bottleneck jumps in there.

**Comment by itsmattkc** [comment]
Yeah pretty much what @naj59 said, while I like platform agnosticism as much as anyone, an Android port is harder than it may look and has a lot of potential for going wrong. Still, I encourage anyone whose willing to give it a shot, it would definitely be interesting to see. But I doubt I'd support it officially any time soon, Windows+Mac+Linux is already quite a handful

**Comment by Symbian9** [comment]
> I encourage anyone whose willing to give it a shot, it would definitely be interesting to see.

In first comment to this issue I noted that this feature request is *long term task* ;-)

**Comment by alcomposer** [comment]
Mobile will always be a moving target. Considering that currently the major focus of Olive is to incorporate external libraries, such as: Colour management, OpenCV, Cineform codec to name a few (which are still being evaluated). These libraries would also need to be compatible with Android. 

Possibly it would be more interesting to have an external controller (jog wheel, controller) for Olive on an Android device. :-)

**Comment by naj59** [comment]
@alcomposer A controller would be a great idea! I love to work with my iPad and FL Studio together, this is something which I would really appreciate.

**Comment by alcomposer** [comment]
Its an idea. IIRC there are already a few NLE jog controllers available. But even a dedicated Olive controller would be fantastic. Protocols such as OSC make this an interesting target.

**Comment by Symbian9** [comment]
> Plus @itsmattkc may be able to monetise the controller on the ~~Android store~~ Google Play. (~~Many FLOSS projects have a proprietary mobile product~~).

... and keep it free on F-Droid, like *Simple Tools* dev did.

**Comment by alcomposer** [comment]
Its completely up to @itsmattkc, and it was only an idea... Argyll is a fantastic, FLOSS software that is payware on Google Play: http://www.argyllcms.com/pro/

**Comment by DaniSeeh** [comment]
I'm certainly no expert, but imagine porting to ARM processors would be a real nightmare. Olive only runs on x86 and AMD64 right now I think, so I imagine it would be a whole other beast to tackle porting to ARM.

And even once you got past that, UI changes would have to be nearly comprehensive. The only future I could see this being particularly useful in is one where docking phones and using them with a mouse and keyboard is way more common, and even then it might not be worth the work since NLEs are just so damn resource intensive and performance would still be limited.

**Comment by elsandosgrande** [comment]
> I'm certainly no expert, but I imagine porting to ARM processors would be a real nightmare. Olive only > The only future I could see this being particularly useful in is one where docking phones and using them with a mouse and keyboard is way more common, and even then it might not be worth the work since NLEs are just so damn resource intensive and performance would still be limited.

Well, the Note 9 is not a slouch and the iPad Pro has pro image software the last I heard, so I don't think it's far-fetched that the tech would be able to handle it in the future (and don't forget that there are some Snapdragon SoCs being built and targeted at the laptop/possibly desktop market, not a Raspberry Pi).

**Comment by naj59** [comment]
> and don't forget that there are some Snapdragon SoCs being built and targeted at the laptop/possibly desktop market

And a lot of reviews showed us that they are complete crap.

**Comment by Symbian9** [comment]
Please, use this issue only for discuss how to port Olive for Android.

> NOTE: Do not spam here, please!

**Comment by itsmattkc** [comment]
Having no experience in Qt on Android, I have no idea how much of the current base is portable to Android, i.e. will the current UI just port over? Even then, as @DaniSeeh says, the current UI probably _shouldn't_ just be ported over as Android generally emphasizes touch controls and small screens.

The other concern is Olive already doesn't compile on ARM (#247), but this is actually more to do with the apparent availability of OpenGL libraries on ARM-based Linux than differences in the architecture (i.e. it seems only OpenGL ES 2.0 is available and Olive is not 100% compliant with that standard). It's probably the same for Android.

**Comment by naj59** [comment]
> just port

Never. Ever. 
This is impossible, I think even the ui needs a QML rewrite (what I‘ve experienced with).

**Comment by itsmattkc** [comment]
@naj59 I figured, in which case there's I'd say there's strong chance of a hypothetical Android port lagging significantly behind the standard version as far as functionality goes.

**Comment by alcomposer** [comment]
Olive is a complex piece of software, and only going to get more complex. If looking at other Libre/GPL software there are hardly any that have an Android port. If such software as Blender, GIMP, Krita are not able to initiate an Android port I would suggest this isn't something that is realistic.

I accept that the Android hardware is very powerful, however remember that even if Android uses the Linux kernel, this does not mean that it is GNU/Linux. Android is a locked down, proprietary system. And is very much a moving target for development. 

It is so much more important to get Olive performant, first class color, effects, and professional editing capabilities.

**Comment by Symbian9** [comment]
> If looking at other Libre/GPL software there are hardly any that have an Android port. If such software as Blender, GIMP, Krita are not able to initiate an Android port I would suggest this isn't something that is realistic

There are many FLOSS desktop software already ported to Android

- VLC
- OpenOrienteering Mapper
- mpv
- QGIS
- Cool Reader
- and many other

> NOTE: Blender, GIMP not ported due to limitation of its toolkits.

**Comment by Symbian9** [comment]
> It is so much more important to get Olive performant, first class color, effects, and professional editing capabilities.

This issue is *long-term* ***feature request***!

Stop discuss here other Olive issues and requests, not related to Android port development!

**Comment by naj59** [comment]
> Stop discuss here other Olive issues and requests, not related to Android port development!
We‘re discussing exactly about that. 

I think most of the people ignore the fact that Olive does not try to be something like iMovie.

**Comment by elsandosgrande** [comment]
> Android is a locked down, proprietary system.

Have you heard of the AOSP? Sure, it has proprietary things (**ahem**Play Store**ahem**), but the core is open-source.

**Comment by goldenbait** [comment]
This is off topic in regards to Android, but on topic when talking about mobile. If Purism's Librem 5 project is a success a mobile interface could be interesting. This is pure GNU/Linux with convergence in mind, not locked down Google mobile.

I can picture a future where at least viewing and tweaking an edit on a mobile device would be possible. I'm not a developer and somewhat ignorant on this, but from what I understand running on this particular device would at least require ARM-support and an adaptable interface that reads like a mobile app when scaled small enough.

**Comment by oc1024** [comment]
Apparently Olive is portable enough for ARM. However, one needs drivers with support for desktop OpenGL, which is often not the case for common phones.

If Librem (or some Ubuntu Phone) offers this, though, this might be the first mobile platform Olive hits, requiring only a UI rearrangement (compared to Android, which requires a full UI rewrite in QML)

**Comment by Symbian9** [comment]
> This is off topic in regards to Android, but on topic when talking about mobile.

This feature request consist of two subtasks

1. Design Mobile/Tablet UI (sets of `*.ui` layouts via QtDesigner)
2. Compile Olive for Android or any other mobile or tablet OS that Qt5 already support.

First task is fully platform-independent.

As start point, look on *OpenOrienteering Mapper* that is also Qt5/C++ app for desktop and mobile platforms (its possible run it on desktop with mobile UI layout too).

- http://github.com/OpenOrienteering/Mapper

**Comment by itsmattkc** [comment]
Well it's been a nice discussion, but I really don't see this happening, at least on an official basis. I still encourage anyone who wants to make it happen, but I think it would be a massive undertaking and I don't think a pro-centric video editor will find much of a userbase on Android. Generally mobile video editor are way stripped down GUI-wise by necessity, so I think the closest thing would be a fork of Olive's backend with a completely new frontend. But even that would be a whole other project separate from development here. Sorry to anyone who was interested in this happening.
