### ISSUE TITLE
[Feature request] Having built-in updates

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#461]
Since the AUR package was still stuck in the year prior (at least it was two days ago when I last checked), I thought it would be beneficial to others if there were some way of supporting automatic updates, something along the lines of Firefox Nightly and Thunderbird Daily (either that, or get someone to update the AUR package/get them in charge of it). I realize that it might not be really practical, or even feasible right now, but I do think this should be implemented in some way in the future. 
Actually, it's still not been updated [(pakku -Si olive.txt)](https://github.com/olive-editor/olive/files/2847256/pakku.-Si.olive.txt).
I also realize that someone may write this off with "Oh, just use a Flatpak or AppImage!", but not everyone wants to use containers.

I thank thee in advance!

**Comment by Symbian9** [comment]
AppImage packages also support delta-updating.

@probonopd could help setup it to `Olive-*.AppImage`

**Comment by itsmattkc** [comment]
I actually don't know who maintains the AUR package (I didn't even know Olive had one before this lol), but my assumption is it _does_ pull directly from the Git, but only pulls tagged commits in an attempt to maintain package stability. I haven't tagged a commit in some time because my priority has been adding features, which usually works against making a "stable" build.

If it could be set up to pull all commits from the repo that'd probably be preferable, but otherwise I could just try tagging an upcoming commit - a new unstable commit is probably better than an old slightly less unstable commit.

**Comment by probonopd** [comment]
I think delta binary updates are already working for Olive using [AppImageUpdate](https://github.com/AppImage/AppImageUpdate).

If the Olive authors would like to have updates without the need for the external AppImageUpdate tool, they could use something like libappimageupdate or [AppImageUpdaterBridgePlugin](https://github.com/antony-jr/AppImageUpdaterBridge/issues/7#issuecomment-438256103), which is a Qt plugin (= should work without changes in the application's source code, by merely bundling it inside the AppImage).

**Comment by elsandosgrande** [comment]
You know what's funny? I had some weird glitch where the editor would crash if I moved the pointer around too much (I use KDE Wayland) while having the File, Edit, ... menus open, which was solved by parsing QT_QPA_PLATFORM=xcb, but the AppImage (just tried it) doesn't have that issue. Furthermore, Olive's AppImage actually opened, while FreeCAD's crashed right away.

Anyway, I was initially thinking of Firefox's way of updating Nightly (you know, folders in /opt), but this is even better! Now to go and figure out how to set that tool up until it gets integrated into Olive somewhere down the line/the AUR package gets going again.

**Comment by Symbian9** [comment]
> I just noticed that the AppImage
doesn't use the native file manager, but a Windows look-alike instead

As for me, I like that Olive has internal file manager that not depend on my ugly native file manager.

BTW, if this is issue, then as possible solution could be adding option "Use system default file manager" .

**Comment by elsandosgrande** [comment]
> BTW, if this is issue, then as possible solution could be adding option "Use system default file manager" 

Perfect! Slowly, this thing's becoming better than KDEnlive with each passing minute.

**Comment by itsmattkc** [comment]
I'm not really sure why that happens, I'm using QFileDialog which defaults to a native dialog when possible, so for whatever reason it can't find a native dialog in the AppImage. Maybe because the AppImage is Trusty-based?

**Comment by probonopd** [comment]
“Native” as in? KDE? Let’s open a separate issue for that. Please ping me there.

**Comment by itsmattkc** [comment]
@probonopd It's not exclusive to KDE, the AppImage doesn't pick up a native dialog on GNOME either. I _believe_ Qt might use `zenity` on Linux usually, but I'm not 100% sure.

**Comment by elsandosgrande** [comment]
> “Native” as in? KDE? Let’s open a separate issue for that. Please ping me there.

Gotcha!

**Comment by itsmattkc** [comment]
Thankfully the primary cause of this issue has been solved, AUR now has an Olive version that stays up to date: https://aur.archlinux.org/packages/olive-git/

**Comment by elsandosgrande** [comment]
And I'm compiling Gentoo as we speak. Our timings are misaligned.

**Comment by DGMurdockIII** [comment]
For windows please

**Comment by oc1024** [comment]
Windows'd need a separate executable for that.
