### ISSUE TITLE
"Linear Fade" applied to audio & video

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#462]
If enable it via menu "Edit > Add Default Transition"; for video should be applied "Cross Dissolve".

Also there are few other issues with "Linear Fade"

- Effects option name "Length::" (with double ":")

![pic.1](https://i.imgur.com/PgVMQRp.png)

- Effects not switched if select clip and only then select applied transition ("Linear Fade"; etc.)

![pic.5](https://i.imgur.com/7PtCewX.png)

**Comment by itsmattkc** [comment]
Fixed in 6ee7153f4a1d9ff7fcc672e43c379fe1f0425acc
