### ISSUE TITLE
Audio gain/volume adjustment in dB

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#464]
Loving this application so far! I'm testing on latest Git version compiled from source on Ubuntu MATE 18.10, and so far have not encountered any crashes. Even in its (pre-)alpha state, I'm finding this to be the most performant and well-thought-out open source video editor available.

I'd like to request the ability to make audio level adjustments in dB instead of what seems to be a percentage unit. As per standard audio convention, the Volume or Gain effect would work like this:

+/- 0.0 dB = audio passes through unchanged
+6.0 dB = double the volume (literally; at +6.02 dB, i.e. +(20 * log(2)) dB, each sample is multiplied by 2)
-96.0 dB = useful minimum volume before snapping to...
-infinity = mute

That way, anyone familiar with audio engineering will be fluent in how much adjustment is needed, and any keyframes with linear connections would automatically be the correct (exponential, i.e. dB-linear) fade.

This also makes volume adjustments more practical - for example, adding 12dB requires going up to "400%" but subtracting 12dB means dropping down to "25%."

**Comment by itsmattkc** [comment]
Done in ca4e39449b0222f3e6194e50ce3e2d7433fd0b62
