### ISSUE TITLE
black screen then open file

### ISSUE THREAD

**Issue by dma3000** [olive-editor/olive#470]
I have black screen then open file created in previously version Olive.
![olive_black](https://user-images.githubusercontent.com/36135809/52530445-e8d03380-2d16-11e9-96c4-4c44f070c710.png)

In terminal I have:
```
$ /settings/programs/Olive-ca4e394-x86_64.AppImage                       (02-10 09:31)
[INFO] Initializing effects... ((null):0, (null))
[INFO] Finished initializing effects ((null):0, (null))
[INFO] Failed to match "../224.mp4" to file ((null):0, (null))
[INFO] Matched "001.ove Audio/Recording 1.wav" relative to project's current directory ((null):0, (null))
[INFO] Matched "001.ove Audio/Recording 2.wav" relative to project's current directory ((null):0, (null))
[INFO] Matched "001.ove Audio/Recording 4.wav" relative to project's current directory ((null):0, (null))
Input #0, wav, from '/work/RecVideo/Olive_test/001.ove Audio/Recording 2.wav':
  Duration: 00:00:11.27, bitrate: 1536 kb/s
Input #0, wav, from '/work/RecVideo/Olive_test/001.ove Audio/Recording 4.wav':
  Duration: 00:00:03.72, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
Input #0, wav, from '/work/RecVideo/Olive_test/001.ove Audio/Recording 1.wav':
  Duration: 00:00:06.75, bitrate: 1536 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 2 channels, s16, 1536 kb/s
$ 
```

**Comment by itsmattkc** [comment]
I'll need more information to address this, you say all of Olive turns black after loading a project file? What's your platform and GPU?

**Comment by naj59** [comment]
@itsmattkc (off-topic) While seeing yet another issue, wouldn‘t it be nice to add an issue template so that we have more informations directly?

**Comment by dma3000** [comment]
Linux 4.20.6-arch1-1-ARCH (x86_64), xfce4 + kwin_11

Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
8034 Мб
Render OpenGL : Mesa DRI Intel(R) Ivybridge Mobile

**Comment by dma3000** [comment]
My olive file. Rename [001.txt](https://github.com/olive-editor/olive/files/2849847/001.txt) to 001.ove 
In GIT not allowed to attach *.ove file.

**Comment by dma3000** [comment]
> @itsmattkc (off-topic) While seeing yet another issue, wouldn‘t it be nice to add an issue template so that we have more informations directly?

My olive file. Rename [001.txt](https://github.com/olive-editor/olive/files/2849847/001.txt) to 001.ove
In GIT not allowed to attach *.ove file.

**Comment by itsmattkc** [comment]
@naj59 That would probably be a good idea, yes.

@dma3000 Does this only occur with this project? And the entire window goes black like this?

**Comment by dma3000** [comment]
I open Olive, and create new sequence. I have black window.
I saved screencast, link to view it https://radikal.ru/video/fQbCbGMfMOi

**Comment by dma3000** [comment]
I open Olive, and create new sequence. I have black window.
I saved screencast, link to view it https://radikal.ru/video/fQbCbGMfMOi

**Comment by dma3000** [comment]
> @naj59 That would probably be a good idea, yes.
> 
> @dma3000 Does this only occur with this project? And the entire window goes black like this?

I open Olive, and create new sequence. I have black window.
I saved screencast, link to view it https://radikal.ru/video/fQbCbGMfMOi

**Comment by itsmattkc** [comment]
Seems like something is breaking when OpenGL is initialized. Try running Olive with the environment variable `LIBGL_ALWAYS_SOFTWARE=1` to confirm:

```
LIBGL_ALWAYS_SOFTWARE=1 ./Olive-*.AppImage
```
It will likely be too slow to be usable running in software mode, but this will at least help narrow things down.

**Comment by dma3000** [comment]
It very slow to be usage for Olive-5d41b90-x86_64.AppImage

`$ LIBGL_ALWAYS_SOFTWARE=1 ./Olive-5d41b90-x86_64.AppImage                                   (02-13 08:45)
[INFO] Initializing effects... ((null):0, (null))
[INFO] Finished initializing effects ((null):0, (null))
Input #0, mp3, from '/work/Music/Iz_filmov/HOME_CD/03. Home Part 3 [my-hit.org].mp3':
  Metadata:
    title           : Home Part 3
    album           : Home
    genre           : SoundTrack
    date            : 2009
    track           : 3
    artist          : Armand Amar
    ENSEMBLE        : Armand Amar
  Duration: 00:01:34.30, start: 0.025057, bitrate: 320 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
    Metadata:
      encoder         : LAME3.98r
[mp3 @ 0x7fbf380078c0] Could not update timestamps for skipped samples.
[mp3 @ 0x7fbf380078c0] Could not update timestamps for discarded samples.
Input #0, png_pipe, from '/work/RecVideo/Изменение территории/Карта_2010_05_14_google.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 1160x675 [SAR 2835:2835 DAR 232:135], 25 tbr, 25 tbn, 25 tbc
Input #0, png_pipe, from '/work/RecVideo/Изменение территории/Карта_2008_02_04_google.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 1160x675 [SAR 2835:2835 DAR 232:135], 25 tbr, 25 tbn, 25 tbc
Input #0, png_pipe, from '/work/RecVideo/Изменение территории/Карта_2014_09_05_google.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 1160x675 [SAR 2835:2835 DAR 232:135], 25 tbr, 25 tbn, 25 tbc
[swscaler @ 0x7fbf34280440] Warning: data is not aligned! This can lead to a speed loss
[swscaler @ 0x7fbf2c279840] Warning: data is not aligned! This can lead to a speed loss
[swscaler @ 0x7fbf30279c40] Warning: data is not aligned! This can lead to a speed loss
[WARNING] QFileInfo::absolutePath: Constructed with empty filename ((null):0, (null))
[INFO] Auto-recovery project saved ((null):0, (null))
[WARNING] Tried to display clip 0 but it's closed ((null):0, (null))
Input #0, mp3, from '/work/Music/Iz_filmov/HOME_CD/03. Home Part 3 [my-hit.org].mp3':
  Metadata:
    title           : Home Part 3
    album           : Home
    genre           : SoundTrack
    date            : 2009
    track           : 3
    artist          : Armand Amar
    ENSEMBLE        : Armand Amar
  Duration: 00:01:34.30, start: 0.025057, bitrate: 320 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s
    Metadata:
      encoder         : LAME3.98r
[INFO] Clip opened on track 0 ((null):0, (null))
[WARNING] Tried to display clip 0 but it's closed ((null):0, (null))
[WARNING] Tried to display clip 0 but it's closed ((null):0, (null))
Input #0, png_pipe, from '/work/RecVideo/Изменение территории/Карта_2008_02_04_google.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 1160x675 [SAR 2835:2835 DAR 232:135], 25 tbr, 25 tbn, 25 tbc
[INFO] Clip opened on track -1 ((null):0, (null))
[INFO] Frame queue couldn't keep up - either the user seeked or the system is overloaded (queue size: 0 ) ((null):0, (null))
[ERROR] Failed to retrieve frame from buffersink. -11 ((null):0, (null))
Input #0, png_pipe, from '/work/RecVideo/Изменение территории/Карта_2010_05_14_google.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 1160x675 [SAR 2835:2835 DAR 232:135], 25 tbr, 25 tbn, 25 tbc
[INFO] Clip opened on track -2 ((null):0, (null))
[INFO] Frame queue couldn't keep up - either the user seeked or the system is overloaded (queue size: 0 ) ((null):0, (null))
[ERROR] Failed to retrieve frame from buffersink. -11 ((null):0, (null))
[mp3 @ 0x7fbf30009f40] Could not update timestamps for skipped samples.
Input #0, png_pipe, from '/work/RecVideo/Изменение территории/Карта_2014_09_05_google.png':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, rgb24(pc), 1160x675 [SAR 2835:2835 DAR 232:135], 25 tbr, 25 tbn, 25 tbc
[WARNING] Tried to display clip 1 but it's closed ((null):0, (null))
[INFO] Clip opened on track -1 ((null):0, (null))
[INFO] Frame queue couldn't keep up - either the user seeked or the system is overloaded (queue size: 0 ) ((null):0, (null))
[ERROR] Failed to retrieve frame from buffersink. -11 ((null):0, (null))
[INFO] Clip closed on track -1 ((null):0, (null))
[INFO] Clip closed on track -2 ((null):0, (null))
[INFO] Clip closed on track 0 ((null):0, (null))
[INFO] Clip closed on track -1 ((null):0, (null))
$  
`
New version Olive-73ac2d5-x86_64.AppImage work perfectly. 
Bug close?

**Comment by itsmattkc** [comment]
> New version Olive-73ac2d5-x86_64.AppImage work perfectly.
> Bug close?

Odd, I hadn't really touched the drawing code to my knowledge. If it's not affecting you anymore, may as well close for now and re-open if it returns.
