### ISSUE TITLE
White Balance with dropper + levels + few things

### ISSUE THREAD

**Issue by PatLabGit** [olive-editor/olive#473]
A "White Balance" filter/effect would be very useful with a dropper to chose what is white or gray in the sequence viewer, as well as a levels tool (like GIMP in Colors/Levels... to adjust colors level, mid tones and more)
IMHO those are the basics in editing, especially when we have underwater videos or videos were shot in a different location like inside a corridor than in a stadium than in a studio all with different types of lights.

I just discover Olive today, so my first thoughts: Adding some effects is not easy, I mean not user-friendly at all, the tab says "(none)", ok i did not add effect, i can understand that, but i have no access to a list of effects.
I found a way to make them appear in the tab "Effects" and have access at all the effects' list by grabbing AND moving around the video in the sequence viewer... other than that how can I access the list of effects?

When I drop from a directory a video directly in the Timeline, the application just shut down, (just to let you know).

I am using the Appimage on Ubuntu-MATE 16.04.5

Overall first impression, Wooww, very nice! it's quite stable for an Alpha!
 I will continue to study it and report ASAP bugs and suggestions,
Thanks a lot for this software.

**Comment by itsmattkc** [comment]
The list of effects is here.

![image](https://user-images.githubusercontent.com/34096995/52534201-80bc2600-2cf3-11e9-88cd-ad2eecba1789.png)

As for a white balance plugin, install Frei0r (it's supposed to be packaged in the AppImage but for some reason isn't so you can install them with `sudo apt-get install frei0r-plugins`). I believe you will find a white balance effect like you describe in there.

Otherwise, thank you for trying out Olive.

**Comment by itsmattkc** [comment]
On this topic, @probonopd sorry if this is a dumb question but how would I get Frei0r effects into the AppImage? They're not linked at compile time so I guess `linuxdeployqt` doesn't pick them up. They're loaded at runtime and need to be in a specific location (see https://frei0r.dyne.org/codedoc/html/group__pluglocations.html), but also have dependencies of their own. What would be the best way to accomplish this?
