### ISSUE TITLE
Export Video is so weird

### ISSUE THREAD

**Issue by ggomagundan** [olive-editor/olive#474]
I downloaded from DMG file and installed my laptop.

And I tested exporting video project like follow

<img width="1748" alt="2019-02-10 11 10 45" src="https://user-images.githubusercontent.com/1453712/52534805-777d9880-2d89-11e9-8231-578247d1e0f2.png">

And  I exported MP4 format

<img width="533" alt="2019-02-10 11 13 45" src="https://user-images.githubusercontent.com/1453712/52534813-8b28ff00-2d89-11e9-8787-5211eb4617ca.png">

But export result is so weired...

<img width="526" alt="2019-02-10 11 11 06" src="https://user-images.githubusercontent.com/1453712/52534822-9e3bcf00-2d89-11e9-9454-07f88b009cc6.png">

Why exporting result like that?.. fix please.

It running on `mojave 10.14.1`

**Comment by itsmattkc** [comment]
This was fixed with #447, sorry the website build for Mac hasn't been updated yet.

If it helps, it happens when your export width is **not** a multiple of 16. If you export at a width of 512 instead of 510, that's a workaround until the website build gets updated.

**Comment by itsmattkc** [comment]
I'm setting up automated builds for Mac, try out the latest build here: https://github.com/olive-editor/olive/releases

**Comment by DevAbanoub** [comment]
I have the same issue on Ubuntu 18.04 LTS and here is an image of  the exported video.
![Screenshot-20190413001216-1191x703](https://user-images.githubusercontent.com/27523369/56069016-51707680-5d81-11e9-9565-ae24444b23a1.png)
THANKS FOR OLIVE!

**Comment by itsmattkc** [comment]
As I said, this was fixed quite some time ago. Which version of Olive are you using?

**Comment by DevAbanoub** [comment]
My version is `Olive (January 2019 | Alpha | c8aec60)`

**Comment by itsmattkc** [comment]
That's _extremely_ old. Please update to the latest build and this issue should disappear.

**Comment by DevAbanoub** [comment]
Thanks for your reply!
