### ISSUE TITLE
Feature request: ability to type in specified length of a still image clip

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#475]
To show the issue/question:

1) Import a still image, put it in a sequence
2) Note that dragging edges allows changing duration without altering speed
3) Right-click, Speed/Duration, enter a duration in numbers
4) Note that the Speed changes

Not sure if this is the intended behavior or not, and what ramifications there would be on keyframe timing, but it would be nice to have a way of typing in, say, exactly 5 seconds to set the length of a still (the same as dragging an edge) without altering its speed.

**Comment by itsmattkc** [comment]
This is intended behavior, the duration in Speed/Duration sets the speed in order to reach a duration (e.g. if the user wants a 1 sec clip to be 2 secs, the speed adjustment will be 50%).

Olive has no way of editing a clip length/duration manually like that yet.

**Comment by mdmayfield** [comment]
OK, thank you! Then I suppose what this really is is a feature request for the ability to type in a duration for a still image clip (wherever is convenient and fits in with the larger plan for the UI). Will edit the issue title accordingly...

**Comment by itsmattkc** [comment]
Added in 1685fa3a5dfc2a57e9802a084a578abd4f5af066
