### ISSUE TITLE
Builds Still Say January 2019

### ISSUE THREAD

**Issue by DaniSeeh** [olive-editor/olive#476]
I know this doesn't matter at all, but I figured it was worth noting that new builds are still saying January instead of February.

**Comment by naj59** [comment]
And it is correct. 
https://github.com/olive-editor/olive/blob/5d41b9005f28658a69a3d470a09f8e76fb104d1f/main.cpp#L14

**Comment by itsmattkc** [comment]
Indeed it should be updated, 32dec87575732a0df1479874242e67ac1d68631f should do it
