### ISSUE TITLE
If possible please add chinese support, thanks.

### ISSUE THREAD

**Issue by wallena3** [olive-editor/olive#478]
Chinese linux community is very concerned about this software, if the energy allows, please try to add Chinese support, thank you

**Comment by itsmattkc** [comment]
Hi, thank you for your support.

I would love a Chinese translation, but as someone who is not fluent in Chinese it would probably need to be provided by someone from the community (all current translations have been community-supplied).

**Comment by naj59** [comment]
Hey @wallena3. Don‘t know how much time you have, but translating Olive is very very easy. Just fork and clone the repo, download [Qt](http://download.qt.io) or just the [Qt Linguist](https://github.com/thurask/Qt-Linguist/releases) and open up the file ``olive_zh.ts`` in linguist. The rest is done over there with no programming interaction. 

@itsmattkc adding chinese would also resist in the problem to use a font which can display chinese characters.

**Comment by itsmattkc** [comment]
I've written a tutorial for anyone interested in providing a Chinese translation https://github.com/olive-editor/olive/wiki/Translations

**Comment by wallena3** [comment]
Thanks all for reply. In spare time I will do my effort. Thanks itsmattkc for tutorial.

**Comment by elsandosgrande** [comment]
> Thanks all for reply. In spare time I will do my effort.

Good luck and have a nice day!

**Comment by itsmattkc** [comment]
I'll close this issue since none of the current developers can really address this, but I very much hope a Chinese translation from someone soon.

**Comment by elsandosgrande** [comment]
Yeah, let's hope somebody gets around to it before I learn Mandarin myself.

**Comment by ka1i** [comment]
I want to do a simple translation job,but I saw that the code snippet contains a section like "Save Project &As" , I don't know what "&" means,or I can change it for  "Save Project As" or "& Save Project As" ?

**Comment by alcomposer** [comment]
`save project &as` means that Qt will underline and make the `a` in `as` a key shortcut while pressing `alt`:
![save_as](https://user-images.githubusercontent.com/12004932/56845852-a2967380-6906-11e9-9623-9a7b1189b509.png)
To enter the menu, a user will first need to press `ctl + f` (to enter file menu). 
Then when the menu is open, press any of the underlined keys associated with what you are interested in using. So to save a project as, simply press `a`.  At any time escape will clear your selection, and you can choose again.

**Comment by ka1i** [comment]
thank you @alcomposer .

**Comment by lostmypillow** [comment]
Would love it if any contributors doing translation would keep Simplified and Traditional apart, if you're doing simplified, make it zh-CN, and let someone (like me) do the zh-TW part.

**Comment by ka1i** [comment]
I try to do zh_CN part.and the translation is not particularly good.I am just taking the first step.thank you everone.I am try my best.

**Comment by Eiffi** [comment]
> Thanks all for reply. In spare time I will do my effort. Thanks itsmattkc for tutorial.

现在能下载到中文包吗？看不懂
