### ISSUE TITLE
Remove 1024x1024 icon

### ISSUE THREAD

**Issue by eszlari** [olive-editor/olive#479]
https://github.com/flatpak/flatpak/pull/2696

> The biggest icon size supported by the hicolor theme definition is 512x512. Putting larger icons there is not going to make desktops pick them up, if they follow the icon theme spec.

**Comment by itsmattkc** [comment]
Some platforms (notably macOS) require a 1024x1024 icon, and I'm sure it'll become necessary within the next 5 years. I don't think it's really an issue to have it.

**Comment by eszlari** [comment]
But this icon isn't used on macOS?
https://github.com/olive-editor/olive/blob/master/packaging/linux/icons/1024x1024/org.olivevideoeditor.Olive.png

>  I don't think it's really an issue to have it.

It causes flatpak icon validation to fail and in turn prevents a successful flatpak build.
And for other Linux packages it wastes space.

**Comment by itsmattkc** [comment]
You took my statement too literally, I was saying for any platforms that do accept or require a 1024x1024 icon, having one available seems like a good thing. I suppose we can always have a copy of all the icon sizes elsewhere and remove the 1024x1024 one from /packaging/linux for the time being.
