### ISSUE TITLE
[Translation] Bosnian

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#480]
So, I would like to be able to add Bosnian translations in the future when I have time (school is a pain), or even now a bit at a time during the weekends and whatnot, but I have no idea where to start or what to use to achieve that. Also, I am still in the web development sphere as far as coding goes, so finer-grain instructions would be much appreciated.

Thank you in advance and I hope I can also pitch in with what I can do!

**Comment by itsmattkc** [comment]
I've written a tutorial that should help once you get time to write a translation: https://github.com/olive-editor/olive/wiki/Translations

If you can provide one, it'll be very much appreciated!

**Comment by elsandosgrande** [comment]
Thank you and you're welcome!

**Comment by itsmattkc** [comment]
According to the Arch Wiki, it looks like Qt Linguist is packaged with `qt5-tools`. See https://wiki.archlinux.org/index.php/qt#Tools

**Comment by elsandosgrande** [comment]
@itsmattkc I meant to say that I thought it would be good to add that is not standalone on Arch, but part of the tools package.

**Comment by itsmattkc** [comment]
@elsandosgrande I've provided a revision with some links for different platforms.

**Comment by elsandosgrande** [comment]
Lovely! Also, @itsmattkc , here's my [progress tracker](https://github.com/elsandosgrande/olive/projects/1) for the translation work.

**Comment by itsmattkc** [comment]
Excellent, thank you for your work so far.

**Comment by itsmattkc** [comment]
I shall close this for now since you've started working on it. If you have any issues, you can feel free to comment more here.

**Comment by elsandosgrande** [comment]
Alright.

**Comment by naj59** [comment]
@elsandosgrande CI builds are uploaded after every commit. When committing, CI runs and after finished its uploaded to github.

**Comment by elsandosgrande** [comment]
Oooh, OK, so I don't have to be on a schedule. Hooray!

**Comment by elsandosgrande** [comment]
One more question. Is there anywhere where the progress-tracking link could be put for those interested to monitor (I don't think many people go through the closed issues in general, let alone for looking into the progress of a translation)?

**Comment by itsmattkc** [comment]
I've been considering making a Wiki page to show the status of all the translations (something like https://github.com/OpenOrienteering/mapper/wiki/Translation). I'm not exactly sure how to set this up to work automatically, but I'm sure it's possible.

**Comment by elsandosgrande** [comment]
Actually, you should also add the symbols reference (it took me a while to figure out that & designates an alt combo key and that %1 is a placeholder) and other relevant info from that site (for now, you could just add my link to that page and note which languages those are, at least until you get to the automated progress tracker, since I keep updating the project with notes as I work on the translations, as I have the project open in a tab in an adjacent virtual desktop/workspace).
