### ISSUE TITLE
[Issue] Unclear translation wiki page instructions

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#485]
The page is not clear on the generation of a new file for editing. I have tried just `lupdate olive.pro`, but it spits this out: `Info: creating stash file /opt/Olive-translating/olive/.qmake.stash
/opt/Olive-translating/olive/panels/viewer.cpp:207: Unexpected character in meta string
Updating 'ts/olive_de.ts'...
    Found 632 source text(s) (0 new and 632 already existing)
Updating 'ts/olive_es.ts'...
    Found 632 source text(s) (0 new and 632 already existing)
Updating 'ts/olive_fr.ts'...
    Found 632 source text(s) (0 new and 632 already existing)
Updating 'ts/olive_it.ts'...
    Found 632 source text(s) (0 new and 632 already existing)
Updating 'ts/olive_cs.ts'...
    Found 632 source text(s) (0 new and 632 already existing)
Updating 'ts/olive_ar.ts'...
    Found 632 source text(s) (0 new and 632 already existing)
Updating 'ts/olive_ru.ts'...
    Found 632 source text(s) (0 new and 632 already existing)`, while trying `lupdate olive.pro olive_bs.ts` gave me `lupdate error: File 'olive_bs.ts' does not exist.`. I'll try working from a copy of the German file until I figure this out.

**Comment by naj59** [comment]
You‘ll need to add ``olive_bs.ts`` to ``olive.pro`` or run, as stated in wiki, ``lupdate olive.pro olive_bs.ts``.

**Comment by elsandosgrande** [comment]
> You‘ll need to add `olive_bs.ts` to `olive.pro` or run, as stated in wiki, `lupdate olive.pro olive_bs.ts`.

I tried running that, it gave me what it gave me (see my full message). So, how do I add it to `olive.pro`?

**Comment by naj59** [comment]
To the ``TRANSLATIONS +=`` part of it.

**Comment by elsandosgrande** [comment]
So, it's a text file? OK then.

**Comment by elsandosgrande** [comment]
Yeah, someone add that to the wiki page. Thanks @naj59 !

**Comment by itsmattkc** [comment]
I apologize, the command is supposed to be `lupdate olive.pro -ts <ts-file>`. I left out the `-ts` part by accident.

**Comment by elsandosgrande** [comment]
I knew something was off! Also, I would suggest adding the "edit olive.pro" method in the wiki, since some might prefer that over the `lupdate olive.pro -ts <ts-file>` command (especially if they want to do multiple translations) and it doesn't hurt (list it under "Alternative method" I guess).
