### ISSUE TITLE
[UI] Ability to edit clip markers

### ISSUE THREAD

**Issue by brimson** [olive-editor/olive#487]
Right now, these clip markers cannot be moved or deleted from the main sequence. [prokoudine](/prokoudine) had the same issue in #333

![image](https://user-images.githubusercontent.com/40442071/52668160-01d01480-2ed0-11e9-9107-8ff75edaed96.png)

Will it be possible to edit such markers by Double-Clicking them in the future? Thank you for your work on this project.

**Comment by itsmattkc** [comment]
The footage markers can be edited if you open the footage in the Footage Viewer (double click it in the Project panel). Not ideal in all situations, I know, but that's a way to do this for now.

**Comment by frink** [comment]
Would a context menu option may suffice for this use case?

**Comment by itsmattkc** [comment]
Merging into #1690 which is more relavent to the current codebase.
