### ISSUE TITLE
[Feature Request] Solo, or Disable Clip in timeline

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#491]
When editing, it is super important to be able to disable either the selected clip, or all other clips.
I would suggest that the disabled clip/s would have to be either a different color, or filled with lines (similar but not the same as to missing media).

**Comment by itsmattkc** [comment]
You can disable clips by selecting them and using Edit > Enable/Disable (Shift+E)

**Comment by alcomposer** [comment]
@itsmattkc I didn't notice this! Great. What would be good is to have this in the right click clip menu.

**Comment by itsmattkc** [comment]
Very true, I've added it in 4890650466459fb9aefa8b7e49f378332068c0e6, I assume this addresses this so I'll close.
