### ISSUE TITLE
Unable to open any media files

### ISSUE THREAD

**Issue by NathanSalapat** [olive-editor/olive#492]
I am unable to add any media, everything reports an error about invalid data. I checked one of my previous projects and all the media fails to load from that project.

![media-bin](https://user-images.githubusercontent.com/8930456/52685537-ad4c8980-2f0f-11e9-986b-6b8704e0f109.png)

```
[DEBUG] using qt5ct plugin ((null):0, (null))
[WARNING] libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
[INFO] Initializing custom cursors ((null):0, (null))
[INFO] Finished initializing custom cursors ((null):0, (null))
[INFO] Initializing effects... ((null):0, (null))
[DEBUG] D-Bus global menu: no ((null):0, (null))
[INFO] Finished initializing effects ((null):0, (null))
[DEBUG] palette support is disabled ((null):0, (null))
[WARNING] libpng warning: iCCP: known incorrect sRGB profile ((null):0, (null))
```

**Comment by alcomposer** [comment]
@itsmattkc I wonder if this has anything to do with the new FFmpeg 4?
I am on Antergos, fully updated, and I am not seeing this issue.

**Comment by itsmattkc** [comment]
This is definitely an FFmpeg issue of some kind (i.e. that error is generated by FFmpeg), usually indicating a file is corrupt or something. Strange that it would be happening for all files. You'll probably need to provide your Linux version and package (e.g. AppImage, apt, etc) to narrow this down.

**Comment by dma3000** [comment]
> @itsmattkc I wonder if this has anything to do with the new FFmpeg 4?
> I am on Antergos, fully updated, and I am not seeing this issue.

I had this error today when opening the project in Olive-73ac2d5-x86_64.AppImage
Having closed the program and opening the project, the error was no longer there, the project opened normally.

Linux arch 4.20.7-arch1-1-ARCH

**Comment by elsandosgrande** [comment]
So, I downloaded the new AppImage and am not seeing any issues in that regard. I'm on Antergos with 20.8-zen.

**Comment by itsmattkc** [comment]
It's actually very possible this is the result of the upgrade to FFmpeg 4. Some dependencies are still in the FFmpeg 3 repo and I noticed in one of the buildlogs that it was still installing FFmpeg 3 for some things, so perhaps for some people/some builds Olive ends up linking with the wrong FFmpeg.

FFmpeg 4 deprecates one of the initiating functions (`av_register_all()`) and does it automatically so I removed it, but this missing function could possibly lead to the error on all files mentioned in the OP.

**Comment by NathanSalapat** [comment]
Sorry, I forgot to include OS in OP.
Linux Mint 19.1
Latest build available from the PPA, not sure if there is a version number anywhere, so I can't give you that.

**Comment by itsmattkc** [comment]
Ahh, I was _sort of_ correct. It has nothing to do with conflicting libs since it's not the AppImage, but does have everything to do with removing the initiating functions (Mint 19/18.04 is stuck on FFmpeg 3).

I've restored them in bd5b2cf036d4c168aa1a965fa88f4567bda093d6, the PPA should update in a few hours. This should fix this issue.

**Comment by NathanSalapat** [comment]
Thanks.
