### ISSUE TITLE
About version numbering

### ISSUE THREAD

**Issue by dma3000** [olive-editor/olive#493]
Is it possible to do version numbering in order? The current version numbering only confuses. It is not clear what the previous one, and what the next one.

**Comment by elsandosgrande** [comment]
I second that!

**Comment by naj59** [comment]
I am completely on the side of how its currently done. Every month a new "release", we're in such an early stadium were version numbers do not make real sense for me. The Git hash is a good thing to start also because you can look up whats done in that time (better for issue fixing etc.).

**Comment by elsandosgrande** [comment]
Can't the be a version increment for each hash?

**Comment by itsmattkc** [comment]
I agree with @naj59 , I know Git hashes are less intuitive since they don't increase monotonically, but as Git is the VCS and keeps track of all the code/changes, I think it's more helpful at the moment to refer directly to points in the Git repo rather than adding a layer of abstraction.

**Comment by elsandosgrande** [comment]
@itsmattkc I was thinking that there could be an automatically increment version number alongside each hash, not instead of. That might even get the AUR package updating again.

**Comment by oc1024** [comment]
@elsandosgrande Aren't `epoch=`, `pkgrel=` and `function pkgver` better options? They'd even allow an `olive-git` package.

**Comment by elsandosgrande** [comment]
I'm not sure what those are, but if they get the AUR back in action, great!
