### ISSUE TITLE
[Discussion] Having a group of issue "moderators"

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#494]
Well, what I mean by this is having some people that would primarily be looking into issues. Those people would probably be like me, I don't know how to code things for Olive yet, but am contributing translations and am still looking into issues as they are created. 

I do understand that this role may be unnecessary right now, but I just thought it would be nice to have a group of people that could respond at greater notice than those that do more coding (not to mention different time zones and labels).

**Comment by itsmattkc** [comment]
Probably a good idea, there are already a few people familiar with Olive who respond to issues before I do which is always appreciated. Naturally it would have to be a volunteer thing, but I'm sure there is a way I could give trusted people a moderator role.

**Comment by elsandosgrande** [comment]
I think it would be best for you to still retain seldom right for appointment, but maybe we could have two tiers (at least at some point down the line), moderators and assistants. Moderators would be seldom appointed by you and a few other contributors you trust (I would advise to keep that trust within the circle of those who contribute substantial amounts of code, just to be safe) and, well, could moderate, while assistants could be appointed by moderators and those higher-up and would be able to label issues and not much else in comparison to regular contributors. 

To be honest, I might be stuck a bit too much in Discord space, as I'm not even sure that this plan could be executed in any way on GitHub, sooo, food for thought I guess?

**Comment by naj59** [comment]
Thats for what github organizations are. Take a look [here](https://help.github.com/articles/repository-permission-levels-for-an-organization/).

@itsmattkc would need to send an invitation to those people and set a permission level.

**Comment by elsandosgrande** [comment]
Well great, I don't have the money to pay. Does that mean that this chapter has come to and end or?

**Comment by naj59** [comment]
@elsandosgrande No no no. I think you missunderstood. He just needs to invite us. These are the regular permissions. Github Orgs are free and olive is already one „https://github.com/olive-editor“.

**Comment by naj59** [comment]
Further reading of how its done
https://help.github.com/articles/managing-an-individual-s-access-to-an-organization-repository/

**Comment by elsandosgrande** [comment]
Ooooh, so it's already an organization. In that case, we're waiting good Sir (I don't mind helping in any way possible if it will accelerate the process).

**Comment by elsandosgrande** [comment]
Thanks @naj59 !

**Comment by itsmattkc** [comment]
I think we mostly have this now in the form of regulars to the tracker and the Discord. I may nominate moderators over time as the issue tracker grows, but for now I really appreciate people who take the time to comment and post about issues.
