### ISSUE TITLE
Meda viewer

### ISSUE THREAD

**Issue by dma3000** [olive-editor/olive#495]
What is it needed for Meda viewer? 
It shows nothing.
![2019-02-13 15-48-08](https://user-images.githubusercontent.com/36135809/52712820-ce13ee00-2fa6-11e9-9a19-c0e3e5e9b70c.png)

**Comment by Symbian9** [comment]
> ~~Meda~~ Mediam viewer

*Media Viewer* is player used for preview imported files.

Just import any media file and double-click on any file in "Project" window.

**Comment by itsmattkc** [comment]
What @Symbian9 said.
