### ISSUE TITLE
Threads of processor

### ISSUE THREAD

**Issue by dma3000** [olive-editor/olive#496]
Exporting file and working Olive used only one thread one core of multi core processor. Can Olive use multi core and multi threads?

**Comment by elsandosgrande** [comment]
Considering KDEnlive deems multi to be experimental (they're quite stable and have been at it for a long time by the way), I wouldn't say that's it's something easily doable (if doable at all) in alpha.

**Comment by itsmattkc** [comment]
Olive exporting has been multithreaded for a very long time. What codec are you trying to export with?

**Comment by dma3000** [comment]
Not actually for current version (Olive-0ac9dd9-x86_64), its work.
Export in mkv with libx264

**Comment by itsmattkc** [comment]
@dma3000 Sorry I don't understand, are you saying it is working or it isn't working?

**Comment by elsandosgrande** [comment]
> Olive exporting has been multithreaded for a very long time. What codec are you trying to export with?

KDEnlive is a disappointment.

**Comment by itsmattkc** [comment]
Try the newest build, the new playback backend should take even better advantage of multiple threads. Also ensure the FFmpeg build you have was compiled with multithreading support.

**Comment by itsmattkc** [comment]
I believe the threads setting addresses this. If not, I suggest making an issue with FFmpeg and giving them details about your setup.
