### ISSUE TITLE
Occasional crashes under heavy load

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#498]
It seems that when working with very large source footage files, and reaching the limits of the workstation's CPU/GPU, Olive can occasionally crash.

So far I'm not able to 100% reliably reproduce this with specific steps. I will continue to experiment to try to trigger it consistently.

System:
- Dell XPS 15 9550
- 8GB RAM
- Core i5-6300HQ
- Intel i915 graphics (has GeForce GTX 960 but disabled for this test)
- Ubuntu MATE 18.10
- Olive compiled from Git 2019-02-12 (commit 2ebea97)
- Using a fairly slow spinning hard drive for media files, not an SSD

Project:
- Minimal effects, mainly cutting 1080p60 and 1080p30 video
- Source files are very large (one is over 10 GB)
- Using frequent cuts from disparate spots in source footage
- A few minimal dissolves, speed changes, transform pan/zoom

Symptoms:
- Seeking is sluggish (especially compared to MPV on the same files, even with Olive in Fast Seeking mode)
- Occasionally a color-distorted view of a different clip will show and freeze
- Video sometimes doesn't move after playback starts
- Over time in a session, the problem tends to get worse
- Lots of RAM usage observed in top when performance is slower (nearly or over 8GB, on a computer with 8GB of physical RAM)
- Eventually the session may freeze and crash
- Unsure of exact steps to reproduce, but seems worse when clips have Speed and transitions etc. simultaneously (higher resource usage)
- In terminal, see some messages like `[WARNING] Tried to display clip 0 but it's closed ((null):0, (null))` and lots (i.e. hundreds) of messages like `[INFO] Frame queue couldn't keep up - either the user seeked or the system is overloaded (queue size: 4 ) ((null):0, (null))`
- Those messages are often shown with this large project even when the application does not crash

**Comment by mdmayfield** [comment]
Seeing a lot of segfault crashes when hitting J to play in reverse.

Is there debug logging or anything I can turn on to make a crash report more useful?

**Comment by oc1024** [comment]
The terminal output is the debug log. You can copy and paste it.

**Comment by mdmayfield** [comment]
@oc1024 Thanks for the response. I'm a "know enough to be dangerous" almost-developer so I might not have the whole picture, but from what I could tell, I wasn't seeing anything in the terminal output that looked like it could provide useful clues to track down a potential memory leak, or a reason for the segfaults.

I was wondering if there was a way to provide something like a stack trace from the crash; I'm not too familiar with debuggers - only used gdb once or twice - but if you can point me in the direction of one that would work well with Olive I can give it a try.

Either way, I will attach the terminal output next time I'm working on the project and it occurs. It's verbose but extremely repetitive (hundreds of those messages I paraphrased in the issue).

**Comment by oc1024** [comment]
> I was wondering if there was a way to provide something like a stack trace from the crash; I'm not too familiar with debuggers - only used gdb once or twice - but if you can point me in the direction of one that would work well with Olive I can give it a try.

`gdb ./olive_editor`

Issue `run` to start debug, when program crashes issue `bt` to get backtrace.
Then Ctrl+D to quit.

Since you have the source code, you get function names. That will help @itsmattkc to find out the source of the crash.

**Comment by itsmattkc** [comment]
Try the latest commit and see if you can still get it to crash. As @oc1024 says, as much `gdb` output/backtraces as possible would be very much appreciated (if you're compiling from source make sure you have `qmake` set to produce debug symbols).

**Comment by itsmattkc** [comment]
If this is still an issue, try again with the newest build (39d62fe39486526ecaca7ace3006407107c270df) and see if it's better. The playback engine has received an overhaul that should be more robust than the previous version.

**Comment by AGI-THB** [comment]
@mdmayfield  is your problem solved?

**Comment by mdmayfield** [comment]
@AGI-THB I haven't been seeing crashes from this lately, but also I've been focusing on UI details and not working on an actual editing project lately. It seems likely that the updates to the rendering have resolved this. Unless you are seeing the same thing with the latest version, I'm inclined to close this issue (for now at least).
