### ISSUE TITLE
[Feature Request] Locking panels and hiding their names. 

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#500]
It is good to add the ability to look panels and hiding their names while they are locked.

**Comment by DaniSeeh** [comment]
Haha, I was actually recording a tutorial for Olive where I had to start over because I kept grabbing and moving panels on accident

**Comment by itsmattkc** [comment]
Added in c3373524b17d0e4134cd51955fa5482f7cfb8c99
