### ISSUE TITLE
[Feature Request] Separate horizontal / vertical zoom in graph graph editor. 

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#501]
Separate horizontal / vertical zoom in graph editor is needed.

**Comment by BrimsonBhin** [comment]
Yup. Blender has this function and would be **very useful** where keyframes have extreme values

**Comment by itsmattkc** [comment]
In c810f27c474441ad56319dda01fcb7626ee05eaf, hold Ctrl to scroll only one axis. Hold Alt to swap between the vertical axis and horizontal axis.
