### ISSUE TITLE
[Feature Request] No need for default effects (transform, volume, pan, etc. ) 

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#502]
I found the default effects for video/audio tracks annoying and it is better to add them manually by the user.

**Comment by elsandosgrande** [comment]
I completely agree! I don't even know how to use them (noob here), so manual would be the best.

**Comment by BrimsonBhin** [comment]
I also agree, I thought that _transform_ effect is for the auto-scaling function.

**Comment by main-gi** [comment]
I don't agree at all! I'd hate to have a large project and have to add basic effects every time.

**Comment by malnaanah** [comment]
Well, personal preferences are different for different people. So, maybe an option could be added to set which effects should be applied automatically.

**Comment by itsmattkc** [comment]
I agree with @main-gi , I really don't think there is "no need" for default effects. However, I'm fine with adding a setting to disable adding them for those who don't want them added by default.

**Comment by elsandosgrande** [comment]
> I agree with @main-gi , I really don't think there is "no need" for default effects. However, I'm fine with adding a setting to disable adding them for those who don't want them added by default.

Yes, yes, YES!

**Comment by malnaanah** [comment]
I agree too, so YES YES YES  for adding an option for disabling (or better choosing) the default effects.

Another YES YES YES for choosing whether  A/V tracks should be splitted by default or not.

**Comment by elsandosgrande** [comment]
> splitted

Sorry to be that guy, but it's split, not splitted.

**Comment by DaniSeeh** [comment]
Oh thank GOD you didn't remove the defaults. I didn't see this til now and I would have begged for them back if you had removed them haha
