### ISSUE TITLE
[Feature Request] Timeline snap to the frame after the  end of the video 

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#503]
The timeline head snaps not to the last frame in the video but to the frame after it, which is very annoying. Also, if two video clips are adjacent, the head should snap the end of the first one then to the start of the second one, not only the start of the second on.

**Comment by elsandosgrande** [comment]
Timeline head?

**Comment by malnaanah** [comment]
I mean by "timeline head" the cursor that is used to change and track current frame in the timeline. I am not sure what it is called.

**Comment by elsandosgrande** [comment]
Oooh. I haven't noticed anything like that when using it. How did you achieve that exactly? I put a video after one that was already present and the timeline cursor (the red thing used for seeking) did not move at all and it always starts at the beginning of the sequence, so yeah, I don't quite understand the circumstances of your issue.

**Comment by malnaanah** [comment]
When you seek to the end of a video in the time line, the red cursor will snap to the frame just after the end of the video and it should snap the last frame in the video.

If there is a video after the video you are seeking to its end, the red cursor will snap the first frame in the second video, I think it is better if it snaps to the last frame in the first video then, with further seeking, it snaps to the first frame of the second video.

**Comment by elsandosgrande** [comment]
Well, that's the same as KDEnlive, do I didn't notice. Good luck!

**Comment by malnaanah** [comment]
Well, I just pointed out what logical behavior the timeline cursor should have when snapping, regardless if it exists in other editors or not.
I think that  the cursor should snap to the last frame in the video not the frame after.

**Comment by itsmattkc** [comment]
I don't really agree. The playhead snaps to any in/out points, this is fairly clear in the usage of it. I think it would be far more confusing if the playhead suddenly snapped to one frame before the end.

**Comment by malnaanah** [comment]
Is the out point part of the video, if yes then the last frame should be seen when playhead snap to the end of the video, but it is not shown.

In other words, just as the playhead snap to the first frame at the start, it should snap to the last frame at the end.

**Comment by itsmattkc** [comment]
I think you misunderstand the way snapping works in Olive. It does not snap to the first frame of the sequence, nor does it snap to the last. It snaps to the edit points (e.g. in/out points) of clips.
