### ISSUE TITLE
[Feature request] Better default column widths in Project pane

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#511]
By default, the Project pane attributes the most width to the rightmost column, like so:
![image](https://user-images.githubusercontent.com/26154258/52800840-35cb4700-3042-11e9-8441-2c63a4826b5d.png)

It would be more helpful to default to giving a sufficient amount of horizontal space to Duration and Rate, then giving all remaining available space to Name:
![image](https://user-images.githubusercontent.com/26154258/52800982-8478e100-3042-11e9-9e5e-04839cebf514.png)

**Comment by elsandosgrande** [comment]
I second that!

**Comment by itsmattkc** [comment]
Same issue alluded to in #424. Unfortunately Qt doesn't seem to have direct functionality for making the first column the priority in width so it'll have to be done manually. I've added a simple "hack" to just resize the first column width to be larger, which should solve this and eventually will lead into #424.
