### ISSUE TITLE
[Feature request] Auto-restart when settings changes require it

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#512]
For example, changing the language requires one to close and reopen Olive manually, while KDEnlive auto-restarts when a change requires it (exempli gratia, when enabling the Movit library).

**Comment by Symbian9** [comment]
> For example, changing the language

Language change should be switched without restart (as many other Qt-based apps did; for example, FreeCAD).

**Comment by elsandosgrande** [comment]
![olive chnages require restart](https://user-images.githubusercontent.com/40576902/52813289-be290680-3099-11e9-9792-8071f4269ee7.png)
@Symbian9 
As you can see, changing the language shows this box (I had it in Serbian/српски and then switched it to Russian and back to Serbian again; the items did not change a bit).

**Comment by Symbian9** [comment]
> As you can see, changing the language

I mean that for language switch redesign I will create separate issue.

According other options that now requer restart, option "Restart app if needed" should be added as optional and user would toggle it in "Preferences > Behavior".

**Comment by elsandosgrande** [comment]
Acceptable.

**Comment by itsmattkc** [comment]
I think forcing a restart would be a really bad idea. At best I'd write a Yes/No dialog if the user wants to restart now after changing settings.

**Comment by elsandosgrande** [comment]
> I think forcing a restart would be a really bad idea. At best I'd write a Yes/No dialog if the user wants to restart now after changing settings.

That's what KDEnlive does (if you decline, the settings are reset, the ones that summoned the dialog that is).

**Comment by elsandosgrande** [comment]
Thank you very much good Sir!
