### ISSUE TITLE
Switch language without restart

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#514]
There are many other Qt5-based apps that could switch language immediatly

- Scribus;
- FreeCAD;
- ...

**Comment by itsmattkc** [comment]
Mentioned in #454. Qt doesn't require a restart to install a new translator. The only reason Olive does is because it doesn't have functions to remake the strings yet upon changing the translator so restarting is a stopgap until that's implemented.

**Comment by itsmattkc** [comment]
Implemented in 47d0065effc36e4306a6464cb256315f37ad07dd

**Comment by qubodup** [comment]
This is awesome, thanks! Better than PP in this regard now! :D
