### ISSUE TITLE
Add Topics to Olive's Repository

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#516]
Hello,

I believe that adding topics would help people notice this project more, perhaps bring in more patrons.

[helio-workstation](https://github.com/helio-fm/helio-workstation) is another c++, [one-man personal hobby project](https://helio.fm/) like this one that also uses topics.

Some topics I would suggest: 

- cpp
- cross-platform
- glsl
- opengl
- qt
- video-editor
- vst

I suggested glsl, vst, opengl because those are Olive's **unique** differences from other open-source NLEs. Hardware acceleration, custom GLSL shaders, and VST plugin support. It would suck to loose potential users/contributors because they assumed Olive is "just another open-source NLE" at first sight.

**Comment by itsmattkc** [comment]
Done, thanks for the suggestion
