### ISSUE TITLE
Some content for the Wiki

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#517]
Hello,

I spent the last few days dissecting documenting Olive's functionalities and wrote a series of .md articles about them. These articles I wrote were inspired by [Blender's VSE Manual](https://docs.blender.org/manual/en/latest/editors/vse/index.html).  It should be an easy copy & paste since I tested the markdown documents' formatting with GitHub's preview function.

It's bare-bones and does not have images (due to GitHub's file size cap), but it gives people a chance to understand and take a glimpse at Olive's features and functionalities before using it.

Because GitHub does not allow me to directly push the edits, I decided to compress them into a .zip file. [Olive Wiki Stuff.zip](https://github.com/olive-editor/olive/files/2871577/Olive.Wiki.Stuff.zip). Everything was written with [Zettlr](https://github.com/Zettlr/Zettlr).

**Comment by BrimsonBhin** [comment]
Nevermind, I made [my own information stash](https://github.com/BrimsonBhin/Olive-Wiki/wiki) about Olive if anyone else is interested in documenting Olive.

Sadly, Olive's official wiki is only accessible to collaborators. [The OBS project's wiki is available for the public to edit](https://github.com/obsproject/obs-studio), so I do not see a reason why this one should stay private.

**Comment by naj59** [comment]
@itsmattkc it‘s an addition to #494
We need _the team_ ❤️

**Comment by itsmattkc** [comment]
Hi, sorry about the radio silence, I've been busier than usual recently. I think having the wiki public is probably a good idea and have made it so. Feel free to add the information in now

**Comment by BrimsonBhin** [comment]
Thank you both for your responses. I think this issue is no more

**Comment by elsandosgrande** [comment]
I believe that this will aid in translation efforts as well (not exactly an experienced user here), so you have my gratitude as well!
