### ISSUE TITLE
[Wiki request] Manual build instructions

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#520]
So, I think that it will aid in newcomers getting their feet wet (trying out their code locally before doing anything on GitHub if they have never compiled from git manually and are just learning to code, not to mention that I fall in that category myself). I've seen that there are different methods used with different projects, but I'm not sure what would be the best course of action for building Olive.

**Comment by oc1024** [comment]
There are instructions on the website (which also seems to use Markdown). It's only a matter of copy-pasting.

**Comment by elsandosgrande** [comment]
Oooh. But, if I go with those, I'll end up with the binary in the local repo, so I wouldn't be able to push it to my fork and later upstream via pull request. Is there any way to get the makefile and binary to be in a separate directory?

**Comment by itsmattkc** [comment]
`qmake` functions the same way as `cmake` where you can run it from a different directory and point it to the source code and it'll put the build files in that different directory. e.g.

```
mkdir olive-build
cd olive-build
qmake path/to/olive/src
make
```

All build files will be made in `olive-build` instead of `path/to/olive/src`

**Comment by elsandosgrande** [comment]
Oooh. Thanks! Again, that might be something good to add to the instructions for newcomers (sort of like me).
