### ISSUE TITLE
[Discussion] Custom cursors

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#522]
Hi,

In collaboration with @alcomposer we are developing a set of custom cursors.
This thread is just opened to discuss what tools need a custom cursor, design, implementation, etc.
By now they are being developed under [this branch](https://github.com/pgilfernandez/olive/tree/custom_cursors), if you help like helping us start by sharing a words with us here.

Here you have a preview of the first cursors designed:
![cursors](https://user-images.githubusercontent.com/5942369/52910503-b6838080-3298-11e9-8525-33c918e13ecb.png)

I hope this feature is soon pulled to master but in the meantime it's a good solution to have this thread as a hub for opinions, conversation, etc.

**Comment by alcomposer** [comment]
I wonder if it's a good idea for the razor tool to have a downward arrow? What are peoples thoughts on that? Would the razer tools horizontal alignment (the way it is) be center, or to the left?

**Comment by pgilfernandez** [comment]
Good point!
Actually I included it because I usually find this icon in other editors to be confusing, I mean, it’s not clear where is the cutting point...
I would suggest to add something that makes it clear like the arrow, a simple line, point (or colored)...

**Comment by elsandosgrande** [comment]
KDEnlive uses scissors for the icon and has a red line on the timeline item to indicate where it's cutting.

**Comment by pgilfernandez** [comment]
I have added a new option for the "razor tool" cursor, now we have:

![5_64](https://user-images.githubusercontent.com/5942369/52915005-26146280-32cf-11e9-97fd-f691433090d5.png) or ![5b_64](https://user-images.githubusercontent.com/5942369/52915011-2f053400-32cf-11e9-9fbf-da427002fa49.png)

Opinions?

**Comment by alcomposer** [comment]
Currently there is a line that is drawn onto the currently active clip when using the razor tool in the timeline.

I think that it is clearer, (at least for me) to have the razor tool offset, like Premier, Resolve & FCPX do. I really like the razor cursor without the arrow, or red line.

**Premier Pro razor tool example**
![](https://www.4kshooters.net/wp-content/uploads/2016/03/Essential_Editing_Tools_In_Premiere_Pro_CC_Square-300x300.jpg)

**Comment by pgilfernandez** [comment]
Oh, that's a good point.
I have just uploaded a third option without any arrow or line, it seems the best option so far.
>
>It may also be interesting to have different states for the icons. For example the tool icon can turn red when activated?

Yes, I have also thought about that but with the "hand tool": an open hand when moving the pointer around and a closed hand when moving.
> 
> I really like the slip & drag tool designs.

Thanks!

**Comment by alcomposer** [comment]
The one good thing about having the razor tool at an angle, (like PP above) is that a user can clearly see where the edit point is, (even more so than having the tool offset and straight).

However, one of the main reasons to have consistent icons/cursors is so they *are* consistent. So whatever the razor tool looks, it should be the same look and feel of the tool icon.

**Comment by itsmattkc** [comment]
Hey these are pretty good. As far as the razor tool goes, I agree that a Premiere-like angle with the line on the left side might be good. I think that might be clearer than having a line in the middle.

**Comment by alcomposer** [comment]
Here is a super quick setup for your new tools. I have had to resize them in the loader to 24pix, if anyone wants to play with that, simply comment out the beginning of the line with `//`.

https://github.com/alcomposer/olive/tree/my_custom_cursors

Please note, that the branch is called my_custom_cursors only because I was working on it on my machine, I'm not saying they are *my" cursors.  :-)

Also just noticed that currently olive doesn't have a **Roll** edit. This tool I think should be in the default set (with pointer, left trim, right trim) and be activated when a user positions their mouse over a connected edit point. (From what I can see, Resolve cheats and simply changes the cursor to **Roll** edit tool whenever the mouse gets too close to any edit point - connected or not) I don't see an issue with this behaviour.

**Comment by itsmattkc** [comment]
There used to be a rolling edit tool (there are still artifacts of it in the code), but I realized the pointer tool does more or less the same thing being able to overwrite other clips. I'm okay with "cheating" by doing the same behavior but showing a different cursor if that improves clarity for the user.

**Comment by alcomposer** [comment]
I made a new request for Roll edit here #529

**Comment by alcomposer** [comment]
@itsmattkc as per the size of the pointer, what is a good way to take into account HiDPI screens?

**Comment by itsmattkc** [comment]
@alcomposer The most platform-independent way I've found is to multiply by `QApplication::desktop()->devicePixelRatio()`.

**Comment by itsmattkc** [comment]
Are these ready to be merged? I'm happy to start implementing them if so.

**Comment by alcomposer** [comment]
@itsmattkc:
> Hey these are pretty good. As far as the razor tool goes, I agree that a Premiere-like angle with the line on the left side might be good. I think that might be clearer than having a line in the middle.

Currently the center razor cursor is implemented? Should this not be the edge razor? (as left aligned)
