### ISSUE TITLE
Most of effects not presented (not bundled?) in latest nightly AppImage

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#524]
*If you are requesting a feature, you can remove the following content. If not, it would help get a faster feedback on your issue.*

__Olive version:__  `Olive-3d0a65c-x86_64.AppImage`
__Source:__ *AppImage*
__Operating system:__ *Debian 64-bit*  
__CPU:__ *no matter*  
__GPU:__ *no matter*

### Detailed Description

In latest nightly build only few effects available.

### Steps to reproduce

1. Launch Olive;  
2. Add any video clip;
3. Look in available effects list;

### Output log

There no any abnormal mesages in debug log

**Comment by itsmattkc** [comment]
Should be fixed in d15d6303779742c33f3f89265230bb027a4fa3b3
