### ISSUE TITLE
[Issue] Can't compile Olive anymore!

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#531]
I used Olive for two week now (continuously updating), but as i tried to update my compiled version yesterday it gave me a crash report!

Klone nach '/home/robert/.olive' ...
remote: Enumerating objects: 1487, done.
remote: Counting objects: 100% (1487/1487), done.
remote: Compressing objects: 100% (434/434), done.
remote: Total 13370 (delta 1168), reused 1259 (delta 1053), pack-reused 11883
Empfange Objekte: 100% (13370/13370), 7.46 MiB | 7.89 MiB/s, Fertig.
Löse Unterschiede auf: 100% (10628/10628), Fertig.
In file included from ./project/media.h:28,
                 from ./project/projectelements.h:25,
                 from project/undo.h:24,
                 from oliveglobal.h:24,
                 from main.cpp:26:
./project/marker.h:30:26: Fehler: »shared_ptr« in Namensraum »std« bezeichnet keinen Templatetyp
 using SequencePtr = std::shared_ptr<Sequence>;
                          ^~~~~~~~~~
./project/marker.h:30:21: Anmerkung: »std::shared_ptr« ist im Header »<memory>« definiert; haben Sie vergessen, »#include <memory>« zu schreiben?
./project/marker.h:28:1:
+#include <memory>
 
./project/marker.h:30:21:
 using SequencePtr = std::shared_ptr<Sequence>;
                     ^~~
./project/marker.h:39:26: Fehler: Variable oder Feld »set_marker_internal« als »void« deklariert
 void set_marker_internal(SequencePtr seq, const QVector<int>& clips);
                          ^~~~~~~~~~~
./project/marker.h:39:26: Fehler: »SequencePtr« wurde in diesem Gültigkeitsbereich nicht definiert
./project/marker.h:39:26: Anmerkung: empfohlene Alternative: »Sequence«
 void set_marker_internal(SequencePtr seq, const QVector<int>& clips);
                          ^~~~~~~~~~~
                          Sequence
./project/marker.h:39:43: Fehler: expected primary-expression before »const«
 void set_marker_internal(SequencePtr seq, const QVector<int>& clips);
                                           ^~~~~
./project/marker.h:40:26: Fehler: Variable oder Feld »set_marker_internal« als »void« deklariert
 void set_marker_internal(SequencePtr seq);
                          ^~~~~~~~~~~
./project/marker.h:40:26: Fehler: »SequencePtr« wurde in diesem Gültigkeitsbereich nicht definiert
./project/marker.h:40:26: Anmerkung: empfohlene Alternative: »Sequence«
 void set_marker_internal(SequencePtr seq);
                          ^~~~~~~~~~~
                          Sequence
In file included from ./project/media.h:29,
                 from ./project/projectelements.h:25,
                 from project/undo.h:24,
                 from oliveglobal.h:24,
                 from main.cpp:26:
./project/footage.h:103:25: Fehler: »shared_ptr« in Namensraum »std« bezeichnet keinen Templatetyp
 using FootagePtr = std::shared_ptr<Footage>;
                         ^~~~~~~~~~
./project/footage.h:103:20: Anmerkung: »std::shared_ptr« ist im Header »<memory>« definiert; haben Sie vergessen, »#include <memory>« zu schreiben?
./project/footage.h:31:1:
+#include <memory>
 
./project/footage.h:103:20:
 using FootagePtr = std::shared_ptr<Footage>;
                    ^~~
In file included from ./project/projectelements.h:25,
                 from project/undo.h:24,
                 from oliveglobal.h:24,
                 from main.cpp:26:
./project/media.h:38:26: Fehler: »shared_ptr« in Namensraum »std« bezeichnet keinen Templatetyp
 using SequencePtr = std::shared_ptr<Sequence>;
                          ^~~~~~~~~~
./project/media.h:38:21: Anmerkung: »std::shared_ptr« ist im Header »<memory>« definiert; haben Sie vergessen, »#include <memory>« zu schreiben?
./project/media.h:30:1:
+#include <memory>
 
./project/media.h:38:21:
 using SequencePtr = std::shared_ptr<Sequence>;
                     ^~~
./project/media.h:40:22: Fehler: »shared_ptr« in Namensraum »std« bezeichnet keinen Templatetyp
 using VoidPtr = std::shared_ptr<void>;
                      ^~~~~~~~~~
./project/media.h:40:17: Anmerkung: »std::shared_ptr« ist im Header »<memory>« definiert; haben Sie vergessen, »#include <memory>« zu schreiben?
 using VoidPtr = std::shared_ptr<void>;
                 ^~~
./project/media.h:47:5: Fehler: »FootagePtr« bezeichnet keinen Typ; meinten Sie »Footage«?
     FootagePtr to_footage();
     ^~~~~~~~~~
     Footage
./project/media.h:48:5: Fehler: »SequencePtr« bezeichnet keinen Typ; meinten Sie »Sequence«?
     SequencePtr to_sequence();
     ^~~~~~~~~~~
     Sequence
./project/media.h:49:22: Fehler: »FootagePtr« wurde nicht deklariert
     void set_footage(FootagePtr f);
                      ^~~~~~~~~~
./project/media.h:50:23: Fehler: »SequencePtr« wurde nicht deklariert
     void set_sequence(SequencePtr s);
                       ^~~~~~~~~~~
./project/media.h:55:5: Fehler: »VoidPtr« bezeichnet keinen Typ
     VoidPtr to_object();
     ^~~~~~~
./project/media.h:82:5: Fehler: »VoidPtr« bezeichnet keinen Typ
     VoidPtr object;
     ^~~~~~~
make: *** [Makefile:1922: main.o] Fehler 1

**Comment by alcomposer** [comment]
Adding: `#include <memory>` in **marker.h** fixes this issue. (quite nice the compiler lets us know it was forgotten...)

**Comment by elsandosgrande** [comment]
Guess I'll hold onto the AppImage I have then. I can't imagine where someone would begin here, but good luck with it anyway!

**Comment by itsmattkc** [comment]
Huh, yeah it looks like GCC needs some extra includes. 83ad41d9fdf7db1bc23cac38ce2343b349a80c85 should work (AppImages are compiling properly now too)
