### ISSUE TITLE
[PR] Emboss effect

### ISSUE THREAD

**Issue by oc1024** [olive-editor/olive#532]
I've written an Emboss effect. I also tried writing a drop shadow effect, but I - Olive now has text drop shadow angles, so the major application for it is moot; II - I just couldn't implement it efficiently.

Since the main branch of my fork is already loaded with a hackish Mask Thru Blending implementation and I just don't know how to set up a branch with undone commits, I'll just drop the shader here.

[Emboss.zip](https://github.com/olive-editor/olive/files/2882791/Emboss.zip)

**Comment by BrimsonBhin** [comment]
Nice. It works on the `87df07e` Windows build

Since there is already a corner-pin shader, I wonder if a 3D-rotation shader is also possible

**Comment by itsmattkc** [comment]
Hey I'll check this out momentarily, yes I'm in the process of moving the drop shadow from the text effect as it's own separate effect.

**Comment by itsmattkc** [comment]
Merged in as of 47d0065effc36e4306a6464cb256315f37ad07dd
