### ISSUE TITLE
[Feature request] Option to center objects

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#535]
It would be so great if you could center an object horizontally and / or vertically in the Transform Tool with the help of e.g. two button!
Thank you in advance and keep up the great work!

**Comment by elsandosgrande** [comment]
That would be great! Now if only video editors had a clue of what an array is (my AutoCAD usage might be spilling over a bit here).

**Comment by itsmattkc** [comment]
Technically the way to do this is alt+click the position fields to set them back to their defaults since Olive will default to centering clips.

**Comment by libalis** [comment]
Yes, but it would be so great if you could add 2 buttons for seperate horizontal and vertical centering!

**Comment by itsmattkc** [comment]
I mean that _is_ how that works, as in alt+clicking the horizontal position will center it horizontally and alt+clicking the vertical position will center it vertically. I'm not sure what you're requesting here.

**Comment by elsandosgrande** [comment]
@itsmattkc I think he wants those to be wrapped up in buttons labeled as such.

**Comment by itsmattkc** [comment]
I think the fact they're centered by default and also have a method of returning them to the center kind of negates this (extra buttons might add to visual clutter too). However, I've also added a reset menu item in the right click context menu in b2d632598159d4ea26ab7ef2d1552c13279064a8 for better discovery if that helps.
