### ISSUE TITLE
Add .clang-format

### ISSUE THREAD

**Issue by eszlari** [olive-editor/olive#539]
Maybe this could be a small contribution for helping to improve the development process (https://github.com/olive-editor/olive/issues/518).

**Comment by itsmattkc** [comment]
Forgive my ignorance, what programs use this file? I've begun adopting the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) in recent changes (with a 120 character limit), is there an existing one for that style that can be used?

**Comment by eszlari** [comment]
> Forgive my ignorance, what programs use this file?

Don't you use Qt Creator for development? https://doc.qt.io/qtcreator/creator-beautifier.html

The next version (4.9) will have native support: http://code.qt.io/cgit/qt-creator/qt-creator.git/tree/src/plugins/clangformat?h=4.9

> I've begun adopting the Google C++ Style Guide in recent changes (with a 120 character limit), is there an existing one for that style that can be used?

https://clang.llvm.org/docs/ClangFormatStyleOptions.html

`BasedOnStyle: Google`

**Comment by itsmattkc** [comment]
Added in 224d804c0272890380b8c51ca4b0b441dc6bb8c0
