### ISSUE TITLE
All functions & tabs should be inactive if sequence is empty

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#540]
*If you are requesting a feature, you can remove the following content. If not, it would help get a faster feedback on your issue.*

__Olive version:__ `e0b2cf3`
__Source:__ AppImage

### Detailed Description

Olive try play empty sequence (al playbackl buttons & shortcuts active if sequence empty)

![pic.1](https://i.imgur.com/nPhM91d.png)

### Steps to reproduce

1. Create empty sequence;
2. Play it.

**Comment by itsmattkc** [comment]
The play button won't try to play in an empty sequence as of 47d0065effc36e4306a6464cb256315f37ad07dd
