### ISSUE TITLE
[EXPORT] Allow rendering in background

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#542]
It would be great to have project export (rendering) in background, and being able to continue work on other projects. As long as Olive is open. If a user were to want to quit Olive while rendering- there would be a warning.

**Comment by oc1024** [comment]
If this gets implemented, I'd be interested in setting the priority of the background render thread. This would free up CPU (especially useful on non-CK and non-Zen Linux kernels, which tend to prioritize intensive tasks too much).

**Comment by alcomposer** [comment]
@oc1024 yes, this would be a background task. However its also good to be able to do something with Olive, as opposed to nothing. But yes, background task.

**Comment by frink** [comment]
Until you have background task management with some indication of what background tasks are doing what, you probably don't want background rendering. Background tasks if not managed properly can result in crashes that are hard to diagnose. Until we have great background process management and visibility I would recommend we avoid adding the most time consuming and mission critical process to the background stack...
