### ISSUE TITLE
Discord/IRC group

### ISSUE THREAD

**Issue by naj59** [olive-editor/olive#543]
In addition to #494, would it be nice to have something like a discord or IRC we're we can chat all together, talk about dev topics and help new users.

@elsandosgrande I am not so into Discord (you've said you are coming from this world), is it easy and free to set up a server?

Also, what would be the better way to do?

**Comment by BrimsonBhin** [comment]
I think because of the liberating nature of Olive (being open-source and all-that), I think a matrix room is a viable solution

Riot.im 1.0 just released, and people can create rooms/communities free of charge

**Comment by Corruptinator** [comment]
Interesting, so Riot is sorta like an open-source alternative to Discord? You never know what open-source projects are out in the wild. The more you know...   :)

**Comment by elsandosgrande** [comment]
@naj59 It is free to set a server up. You can have bots, different roles with different permissions, ... I can't remember everything off of the of my head, but it's quite easy. I don't know how to set bots up, but it shouldn't be hard either. 

@BrimsonBhin Well, we could use Telegram then (TuxDigital and Destination Linux use it).

**Comment by elsandosgrande** [comment]
@naj59 What do you think of you, @itsmattkc and me being owners of the server together?

Also, 
 > in to 

is `into`.

**Comment by naj59** [comment]
@elsandosgrande Fine, no problem :-) I have no idea how to do this, but talking about mainstream dev (and random off-topic things) would be very interesting because we don‘t have an opportunity to chat ob gh (except issues). 

I would also go for matrix like @BrimsonBhin. Looks like a cool alternative and have looked up something about it yesterday.

**Comment by DaniSeeh** [comment]
Wow, Riot completely parroted Discord's UI. Once this is set up I would love to join!

**Comment by elsandosgrande** [comment]
@DaniSeeh Can't we just use Discord?

**Comment by alcomposer** [comment]
Personally I think an IRC channel would be great. I know its very old technology, but it works well, and is used for many FLOSS projects.

**Comment by elsandosgrande** [comment]
@alcomposer Yeah, but I've never had good luck with them (it's like there's nobody there most of the time, and that's talking about Mozilla's server).

You know what, after this week, I'm setting the Discord server up (we have exams this week, but Friday is Bosnian Independence day, so I'll be able to then).

**Comment by main-gi** [comment]
And Discord's UI comes much from Slack. :P  

@itsmattkc already has his own personal server which has an #olive subchannel, but as far as I know there is no dedicated Olive Discord. I don't know if he ultimately wants to direct people there though, so I won't post it for now.

**Comment by elsandosgrande** [comment]
Ooooh, that's something I didn't know. Well, I guess we will have to wait for our good Sir to chime in on this topic then.

**Comment by itsmattkc** [comment]
I think a chat server for discussion would be good, I haven't tried Riot before but would be happy to give it a shot if people would like to use it. Otherwise I'm set up for IRC or Discord too.

@main-gi I wouldn't, that was set up much earlier in development and would be way too small I think.

**Comment by giacomoalbe** [comment]
Hi all!

It's my first post here on this project, I found it one week ago while doing totally unrelated stuff, and I'm very happy about that since I have been looking for a decent NLE in Linux since I remember, and Olive looks very very promising! 

Regarding the topic, I'd like to add up to the discussion that it is possible and fairly easy to create one (or multiple) gitter channels. 

Gitter is a very lightweight chat application developed by Gitlab, its very simple and minimal, and it has been done to enhance IRC and help code communities to meet. 

And what about a Discourse forum? I think that having a forum might be of interest for user assistance, problem solving in general and all the social "stuff".

**Comment by DaniSeeh** [comment]
@elsandosgrande I'm totally down for Discord. I use it daily.

**Comment by BrimsonBhin** [comment]
@giacomoalbe Wow, Gitter looks promising. Though it's disadvantage is the pervasive logging (go I gotta watch what I say).

**Comment by elsandosgrande** [comment]
@BrimsonBhin Discord (not Discourse) does not require any money, period (there is Nitro for perks like animated profile pics, but that neither here nor there).

**Comment by Corruptinator** [comment]
I'm down for discord. Pretty much a lot of users use Discord for various purposes.

**Comment by Corruptinator** [comment]
Maybe someday there could also be a Discord Video Edit Collab project. Who knows?

**Comment by elsandosgrande** [comment]
So, I still have things left to set up, but here we are my comrades: https://discord.gg/rvJMEYQ

@itsmattkc Do message me so that I can add you as an owner.

**Comment by itsmattkc** [comment]
Awesome, thanks for setting this up. I've joined, this should solve this issue now.

**Comment by elsandosgrande** [comment]
Should we (I, most likely) make a wiki page to give some helping tips with regards to the server?

**Comment by oc1024** [comment]
Apparently Discord hates my country's phone numbers. Hooray.

**Comment by elsandosgrande** [comment]
@oc1024 How so?

**Comment by oc1024** [comment]
The confirmation screen hangs when I click Next after inputting my phone number.

**Comment by elsandosgrande** [comment]
Umm, try again? Well, I'll look into it once I'm done with my homework for the week (sorry that I can't sooner).

**Comment by BrimsonBhin** [comment]
Hello, is it possible to access the discord without a phone #? Discord does not allow my carrier's numbers to be used. :/

**Comment by elsandosgrande** [comment]
I set it to the highest level of moderation, so... Also, aren't you already in the server @BrimsonBhin?

**Comment by main-gi** [comment]
Yeah I have this issue too. Well, I'm currently busy with other projects so I probably wouldn't be able to respond a lot anyway, but you *can* join the server and read messages without phone verification. I just can't send any messages. No other server I'm in needs phone verification and it's kind of strange that it's necessary unless the server gets so big there's a lot of spammers or something?

**Comment by BrimsonBhin** [comment]
I am in the server @elsandosgrande . However, I need a phone number to send messages.

**Comment by naj59** [comment]
What happens when trying to enter the phone number? @BrimsonBhin

**Comment by elsandosgrande** [comment]
I was trying to future-proof it. If it proves to be too much, I'll revise my strategy.

**Comment by BrimsonBhin** [comment]
@naj59 It shows as an invalid number. I do not think Discord whitelists FreedomPop numbers.

**Comment by elsandosgrande** [comment]
Well, made it be a ten-minute timeout. Mind you, there might be a need to raise it to this verification again in the future, so I'd suggest getting an additional number that is A-OK to Discord.
