### ISSUE TITLE
[Feature request] Layout/Look and feel options

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#545]
I know that you're working with the Premiere look, but it might be good to add different layout tweaks as options to acommodate users of other video editors who might be switching to Olive (not major changes, but mostly in the way that you add effects and transitions, like a button that then has a right-click-looking menu versus a list of effect and transition categories like in KDEnlive, or having the option to add those same effects and transitions from a right click on a clip in the timeline like in KDEnlive, or being able to choose to do keyframing like in KDEnlive, having a mini seek bar in the panel for the effect for easier keyframe manipulation and being able to overlay the graph on the clip in the timeline; sorry for only giving KDEnlive examples, but I have not known any other software for a long time).

**Comment by naj59** [comment]
When we talk about look and feel I would find it nice when the menu bar would have the platforms style. On Windows this would look way more professional than using fusion everywhere. Could tweak that with something like

```cpp
#if defined(Q_OS_WIN32) || ...
menuBar->setStyle(QStyleFactory::create(„windowsvista“));
#endif
```

**Comment by BrimsonBhin** [comment]
I think another layout option is the ability to "lock" the current panel layout

Sometimes when I edit, I find myself accidentally moving the graph editor into separate window.

**Comment by elsandosgrande** [comment]
I am getting the feeling that this ticket will be diverging from my original request more and more over time.

**Comment by BrimsonBhin** [comment]
Sorry if I made you feel that way, @elsandosgrande , I thought this thread could be a collective of requests regarding layout/look and feel options.

Back to the main topic, you mean something like this? (with the bezier handles of course).

![keyframeable-effects](https://user-images.githubusercontent.com/40442071/53291172-395e7c80-376c-11e9-9f71-d01b837db304.png)

**Comment by DaniSeeh** [comment]
Oooh, I love that mockup

**Comment by BrimsonBhin** [comment]
@DaniSeeh fortunately it is not a mockup, it is from [KdenLive's feature section](https://kdenlive.org/en/features/)

**Comment by DaniSeeh** [comment]
Ahhh, cool. Kdenlive would be so great if the preview performance wasn't absolute crap. Olive has such better performance.

**Comment by malnaanah** [comment]
I believe that olive keyframing capabilities are more powerful than kdenlive, however the graph editor needs more enhancements, such as:
1- Adding more icons that are used to pan or zoom in the vertical or horizontal direction
2- Relating the graph editor horizontal limits to the clip limits, so you can relate the position of the keys to the clip duration. 
3- Viewing the keys of the active property on the clip in the time line as in Kdenlive, and if not, then the curve editor should provide equivelant view.

**Comment by elsandosgrande** [comment]
@BrimsonBhin Well, you've hit the mail right on the head! Considering that our good Sir has issues implementing pixel scrolling (or whatever it's called, just look my two-finger scrolling ticket up), I cannot easily navigate the graph editor (honestly, I'm not sure how to use it with mouse-like behavior either, using actual left and right clicks like on a mouse that is), so having this added would be nice (I think it could also server as an easy overview at a glance once you get used to it). Also, he should add sliders alongside the number fields for effect parameters, like in KDEnlive (dragging those numbers doesn't work out for me in either Olive or KDEnlive).

**Comment by elsandosgrande** [comment]
@DaniSeeh Actually, KDEnlive has become pretty good on that point, at least on my laptop running Antergos KDE, so much so that it's not significantly different from Olive without effects applied (haven't tried those out in Olive, but images with transparency/text made in GIMP slows the preview down by a lot, do alpha is an issue I guess?), so I'm sort of in it for the potentially superior GPU acceleration (using Movit is like playing a game of Russian roulette on my system) and superior effects.

**Comment by DaniSeeh** [comment]
@elsandosgrande Whenever I used Kdenlive, it froze up like Canada in wintertime any time I did literally anything.

I pretty much exclusively use images (educational YouTuber) and I edit in 4K60. Kdenlive simply wasn't up to even the simplest task in my workflow, where Olive only has trouble with the craziest animations that I do. Kdenlive also doesn't have subsequences which is practically criminal for my workflow.

I really only need:

1. Decent preview performance at 4K (preferably 60fps)
2. Subsequences
3. Keyframeable masks
4. Exporting RGBA
5. Keyframeable Effects

Olive now has everything but Keyframeable effects masks so it is pretty much up to every task I throw at it less one.

Kdenlive (for me) has abysmal performance (it actually often freezes my entire PC), no subsequences, and because it is MLT based I don't see the preview performance improving for me anytime soon.

I am glad it works for you though!

**Comment by elsandosgrande** [comment]
@DaniSeeh Ummm, what's a subsequence?

OK, I can't believe it crashes on Ryzen+decent Nvidia, yet it doesn't on dual-core APU+similar-level AMD dGPU.

**Comment by DaniSeeh** [comment]
@elsandosgrande A timeline within the main timeline.

**Comment by elsandosgrande** [comment]
@DaniSeeh And how does that work? How do you even trigger the creation of one?

**Comment by DaniSeeh** [comment]
@elsandosgrande

Two ways, if you want to Nest something you already have inside a new sequence on the main timeline, select all the clips you want and right click then hit nest.

If you want a new empty sequence, right click the project pane and click new sequence or use Ctrl + Shift + N

**Comment by elsandosgrande** [comment]
So, I checked it out and I don't think it would really help me in my editing (maybe only slow me down by a bit really, as I would just be going in and out of them like there's no tomorrow). Lovely that it works out for you though!

**Comment by DaniSeeh** [comment]
I imagine subsequences main purpose would be to neatly separate scenes, but I use them to do animated composites and to separate elements I am animating cleanly and move them around easily.

**Comment by elsandosgrande** [comment]
Well, wouldn't grouping work just as well (barring the vertical space, which can be expanded as far as I know in KDEnlive at least) for ease of maneuvering?

**Comment by DaniSeeh** [comment]
Not if you need to apply effects on top of everything under the subsequence and not to each individual clip

**Comment by elsandosgrande** [comment]
@DaniSeeh Well, you got me there.

**Comment by itsmattkc** [comment]
This is kind of a difficult thread to unpack as it doesn't point to any single issue or request, but rather a very loose definition of making the interface more similar to other editors. Without spending a significant amount of time in each editor, it'd be impossible to "replicate" it to the point of making familiar. I also don't think replicating another piece of software for the sake of replicating it is necessarily a good idea.

There are some good ideas in this thread, but I think it'd be easier to request them individually (like #606). That way each idea can be discussed and it can be determined if/how they'll fit into Olive.
