### ISSUE TITLE
[Compiling] Failure to find: debug/resources_res.o and release/resources_res.o

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#546]
I've pretty much followed instructions on how to compile Olive on Windows and at the end of the instructions, I've ran into this compiling error after typing and entering "qmake":

```
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
WARNING: Failure to find: debug/resources_res.o
WARNING: Failure to find: release/resources_res.o
```

I theorize it may have something to do with the Username. Username has a space before Corruptinator: "The Corruptinator"

Any idea on how this can be fixed or resolved. Would love to test out the new builds through compiling.

**Comment by elsandosgrande** [comment]
I find that you can put a backslash before a space to escape it in filenames in bash. Exempli gratia, `pakku\ -Qq.txt`.

 Another way would be `'pakku -Qq.txt'`, but I don't like it, so I don't use it.

**Comment by BrimsonBhin** [comment]
I also have this issue with MSYS2

I think what is missing from the compilation instructions is the requirement to install `gcc`. GCC does not come with MSYS2 by default.

**Comment by itsmattkc** [comment]
I think this means your git version is old, try running `pacman -Syu` and see if that fixes it (MSYS2 doesn't update itself when it's first installed).

**Comment by Corruptinator** [comment]
Doing `pacman -Syu`, and looks like its updating. This could take a couple of minutes to fully update. I'll report back to see if anything is changed.

**Comment by Corruptinator** [comment]
Done updating, ran `qmake`, still got same error:

```
$ qmake
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
WARNING: Failure to find: debug/resources_res.o
WARNING: Failure to find: release/resources_res.o
```

**Comment by itsmattkc** [comment]
What's your Git version? `git --version`?

**Comment by Corruptinator** [comment]
```
$ git --version
git version 2.20.1
```

**Comment by itsmattkc** [comment]
If you replace the following line in `olive.pro` (around line 32)
```
GITHASHVAR = $$system(git --git-dir $$PWD/.git --work-tree $$PWD log -1 --format=%h)
```
with this:
```
GITHASHVAR = $$system(git --git-dir=$$PWD/.git --work-tree=$$PWD log -1 --format=%h)
```
does that fix it?

**Comment by Corruptinator** [comment]
One moment. Testing...

**Comment by Corruptinator** [comment]
Still the same error, however there were new files created in the olive source code folder:
![image](https://user-images.githubusercontent.com/5027750/53308419-e6f98a80-3855-11e9-9d33-4e8e6ae47763.png)

Do you need those files to take a look?

**Comment by itsmattkc** [comment]
If you have the Makefile (and Makefile.Debug/Makefile.Release) you should be able to just compile. It may not have a Git hash in the title bar but it should compile and run regardless.

**Comment by Corruptinator** [comment]
I'll try it out.

**Comment by Corruptinator** [comment]
For some reason `make` isn't a command. strange:

![image](https://user-images.githubusercontent.com/5027750/53308490-9f273300-3856-11e9-9c67-287a2c7dec68.png)

I don't know if I'm missing something. I'm pretty sure I've read the instructions.

**Comment by itsmattkc** [comment]
I think the Windows instructions are more incomplete than I realized. Also install the following:

`pacman -S make mingw-w64-x86_64-toolchain`

**Comment by Corruptinator** [comment]
Will do.

**Comment by Corruptinator** [comment]
There we go. something is happening after using `make`.

**Comment by Corruptinator** [comment]
I do believe it may be compiling.

**Comment by Corruptinator** [comment]
Ran into a compiling error:

![image](https://user-images.githubusercontent.com/5027750/53308707-448ed680-3858-11e9-879c-b4387c190756.png)

Maybe it was after adding an '=' around line 32 in `olive.pro`?

**Comment by Corruptinator** [comment]
I'm going to revert the line in olive.pro back to it was originally and try again.

**Comment by Corruptinator** [comment]
Interesting, I ran `qmake` again, and the missing debug is now gone. release is the only one that is still missing:

```
$ qmake
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
WARNING: Failure to find: release/resources_res.o

```

**Comment by itsmattkc** [comment]
That's really weird... that's an error in the Qt header, not any Olive code... As it says maybe you'll need to send a bug report to MSYS2 themselves.

For Olive though, it doesn't actually use that crc32.cpp/crc32.h. Remove the lines referencing them in olive.pro and see if you have better luck compiling then.

**Comment by Corruptinator** [comment]
remove line 169 `io/crc32.h \` and line 79 `io/crc32.cpp \`?

**Comment by itsmattkc** [comment]
Indeed

**Comment by Corruptinator** [comment]
Alright, done. Recompiling...

**Comment by Corruptinator** [comment]
I'm starting to think this is on the MSYS2 side of compiling:

![image](https://user-images.githubusercontent.com/5027750/53309069-84ef5400-385a-11e9-8864-5f0f8d896b9b.png)

Cause that error showed up after removing those two lines.

**Comment by itsmattkc** [comment]
It's a different error, but more importantly a very old version of Olive - Olive's used an internal VST header for some time now. When did you last pull/clone?

**Comment by Corruptinator** [comment]
I'm pretty sure I've just pulled it since yesterday. Is there any way to check the git source version?

**Comment by itsmattkc** [comment]
`git log -1` will tell you about the most recent commit it's aware of

**Comment by Corruptinator** [comment]
hmm... Maybe I should redownload the source:

```
$ git log -1
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by Corruptinator** [comment]
I'm going to delete the source code and try to redownload them.

**Comment by Corruptinator** [comment]
Redownloaded source code, and now the error is different after running `qmake`. Do you think it has something to do having an empty space for the username? Unix/Linux kernel and or terminals are known to be finicky over spaces:

![image](https://user-images.githubusercontent.com/5027750/53309307-05fb1b00-385c-11e9-9804-e911a6356cfd.png)

**Comment by itsmattkc** [comment]
Ahh that must be it, yeah. Try taking that line from before and putting quotes around the paths:

```
GITHASHVAR = $$system(git --git-dir="$$GITPATH/.git" --work-tree="$$GITPATH" log -1 --format=%h)
```

**Comment by Corruptinator** [comment]
Ok, replacing line 32 in olive.pro again.

**Comment by Corruptinator** [comment]
Well it fixes the kernel spacing problem, but brought forth the same error again:

```
$ qmake
/usr/bin/git
fatal: not a git repository: '/.git'
sh: C:/msys64/home/The: No such file or directory
/usr/bin/git
fatal: not a git repository: '/.git'
sh: C:/msys64/home/The: No such file or directory
/usr/bin/git
fatal: not a git repository: '/.git'
sh: C:/msys64/home/The: No such file or directory
WARNING: Failure to find: debug/resources_res.o
WARNING: Failure to find: release/resources_res.o
```

However, the five new files `Makefile`, `Makefile.Debug`, `Makefile.Release`, `object_script.olive-editor.Debug`, and `object_script.olive-editor.Release` were generated in the Olive Source Code folder.

**Comment by itsmattkc** [comment]
If you're downloading the zip from GitHub (rather than using `git clone`) I'm pretty sure it strips out the .git folder anyway so that's expected. See what happens if you compile at this point.

**Comment by Corruptinator** [comment]
Alright. Compiling...

**Comment by Corruptinator** [comment]
Still compiling. No errors so far. Thats a good sign.

**Comment by Corruptinator** [comment]
Nevermind, now its at MSYS2 compile error:

![image](https://user-images.githubusercontent.com/5027750/53309905-4019ec00-385f-11e9-9413-57d9da8d2789.png)

**Comment by itsmattkc** [comment]
Very weird, same compiler error on the Qt header as before... Unfortunately I'm not sure what to do about that apart from file an issue with them.

**Comment by Corruptinator** [comment]
I forgot to remove line 169 `io/crc32.h \` and line 79 `io/crc32.cpp \`. I'm going to do that and see if there is any difference. If not then I'll definitely file a bug report.

**Comment by Corruptinator** [comment]
NVM, didnt work. I'm wondering how I am going to file out this bug?

**Comment by naj59** [comment]
The spacing problem is back. 
```
fatal: not a git repository: '/.git'
sh: C:/msys64/home/The: No such file or directory
/usr/bin/git
```
Although it is very strange to me. Isn‘t there a possibility to use just the Qt Creator for that completely ignorning msys? I just run the 5.9.7 LTS MinGW on my Windows. There must be a simpler way to do this...

**Comment by Corruptinator** [comment]
Oh you're right, I just realized that the Spacing isn't fixed at all WHOOPS.  XP

**Comment by elsandosgrande** [comment]
@Corruptinator Yeah. Could you possibly try to use escape characters, something that I suggested in the first reply? If you could, then great!

**Comment by Corruptinator** [comment]
How am I going to get it to work with backslash on qmake and make?

**Comment by elsandosgrande** [comment]
> How am I going to get it to work with backslash on qmake and make?

Sadly, I haven't the slightest clue.

**Comment by itsmattkc** [comment]
I can try to update the website build soon, for now I'll close this as it doesn't seem to be an Olive issue (and I've implemented those spacing fixes into `master`). Thanks for letting me know I should update the website tutorial as well.

**Comment by Corruptinator** [comment]
Figure I give an update, turns out I'm not the only one who had suffered this internal bug:
https://github.com/msys2/MINGW-packages/issues/5006
There are a few others just reporting in as well. Perhaps a fix will soon make headway.

**Comment by Corruptinator** [comment]
Interestingly, one of the users suggested downgrading GCC to 8.2:
"Downgrading to 8.2.0 solves the problem..."
I'll need to find a way to downgrade to 8.2 and see if that fixes the problem.

**Comment by itsmattkc** [comment]
@Corruptinator Interesting, from what I remember there's no way to downgrade with pacman, but you can browse the MSYS2 archives on Sourceforge for old versions and install them from a package file. I'll test this out.

**Comment by naj59** [comment]
Possibly [this](https://mingw-w64.org/doku.php/download) could help? Take a look at Msys2, they have the 8.2.0 version.
