### ISSUE TITLE
Appimage on Manjaro: No effects are showing up.

### ISSUE THREAD

**Issue by bvz2000** [olive-editor/olive#548]
*If you are requesting a feature, you can remove the following content. If not, it would help get a faster feedback on your issue.*

__Olive version:__  f4668e3
__Source:__ Appimage
__Operating system:__ Manjaro (latest)
__CPU:__ *Intel i7 (Dell XPS15 9560)*  
__GPU:__ VGA compatible controller: Intel Corporation Device 591b (rev 04)

### Detailed Description
No matter which version of Olive I am using (I have also tried 0ad58a6) the effects window is completely empty.  Perhaps I do not understand where the list of effects should live, but all of my research seems to indicate that it should just be a list inside of this window.  Note: when the appImage asks to integrate into my system, I always say "run once", and do not do the integration.

Also, I don't know if this matters, but here is the full installation path I am using for Olive:

/opt/apps/olive/olive/2-24-2019/app/Olive-f4668e3-x86_64.AppImage

*your issue description here*

### Steps to reproduce

1.  
2.  
3.  
4.  
...

### Output log

```
please paste it here for better reading
```

**Comment by itsmattkc** [comment]
When you select a clip, the effects on that clip will show in Effect Controls.

![image](https://user-images.githubusercontent.com/34096995/53305984-b48f6380-383c-11e9-8734-0f5532040e02.png)

Clicking one of the buttons will bring up a menu for adding effects.

![image](https://user-images.githubusercontent.com/34096995/53306014-fb7d5900-383c-11e9-9683-a361a0e7a13d.png)

**Comment by bvz2000** [comment]
Aha. Thank you. Sorry to not have figured that out myself.

**Comment by itsmattkc** [comment]
No worries, hopefully soon there will be tutorials to assist new users in navigating Olive's interface.

**Comment by elsandosgrande** [comment]
This is why I opened that feature request.
