### ISSUE TITLE
[Feature Request] Ctrl-wheel for zoom instead of Shift-wheel

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#549]
It's more common (in my experience with Web browsers, image viewers, file managers, and other software) for Ctrl-mousewheel to be used for zoom, and Shift-mousewheel to be used to swap scrolling axes (horizontal/vertical).

For consistency with other applications, please consider making Ctrl the zoom modifier and Shift the axis modifier.

**Comment by elsandosgrande** [comment]
One, I agree completely on the ctrl note. Two, it uses SHIFT to zoom? Three, you use SHIFT with a mouse wheel to scroll horizontally?

**Comment by mdmayfield** [comment]
This is a complex situation that will need some judgment calls. There are several competing considerations:

- Some users have a mouse with only one wheel. Others have a touchpad with multi-axis scrolling.
- The most strongly expected behavior from a scroll wheel is vertical scroll.
- Most applications and graphical toolkits, across OSes (to my knowledge) scroll horizontally on Shift-scroll wheel.
- Some users know about Shift-scrollwheel to scroll horizontally; many don't.
- Many, but probably not a majority of, applications that have a primarily horizontal workspace (i.e. timeline-based editors) use the unmodified scroll wheel to scroll *horizontally* instead of vertically as "generally" expected.
- Olive currently does this (vert scrollwheel --> horiz scroll)

If it were up to me alone, here is what I would choose for scrollwheel behavior:

- Timeline: unmodified scroll = vertical scroll. Shift-scroll = swap axes. Ctrl-scroll = horizontal zoom.
  - Prioritizes "usual behavior" and is convenient for touchpad users
  - Slight disadvantage to mouse users
  - To mitigate that, tooltips or similar to raise awareness of Shift-scrollwheel

- Graph Editor: exactly the same behavior as the Timeline, same modifiers

When swapping axes, I would make the wheel motion that normally scrolls a webpage _down_ scroll the timeline to the _right_. (Same motion = "later" in the document/project, whether vertical or horizontal)

**Comment by elsandosgrande** [comment]
@mdmayfield @itsmattkc still hasn't gotten the touchpad scrolling to work properly (#505), so it's there is no difference on that note at this time. Oh, and the vertical-gives-horizontal scrolling thing is also mentioned in the issue. 

My suggestion would be that vertical scrolling with a touchpad zooms (something that even KDEnlive doesn't do) without ctrl by default (modifiable in Settings) and horizontal scrolling scrolls, while the behavior would be different with a regular mouse (I presume that the device used can be detected). Basically, conditional behavior.

**Comment by itsmattkc** [comment]
Alt+Scroll to switch axes is Qt's default behavior, I'm not sure how easy it'd be to override that. Switching Shift to Ctrl would be fine as I don't think Ctrl+Scroll does anything in most places in Olive.

**Comment by mdmayfield** [comment]
I was looking into this some more and it does seem like Qt has Alt as a hard(ish)-coded swap of axes... Actually not precisely a swap, as it seems to ignore horizontal scrolling on a touchpad and only map vertical --> horizontal.

This leads to an issue where, if you hold Alt and scroll *horizontally* on a touchpad, both left and right scroll only to the right. It seems to be somewhere in the logic of `TimelineWidget::wheelEvent`. I will take a look and open a pull request to resolve that, as well as make Ctrl as the modifier for zoom.

There are several aspects of the way Qt deals with scrolling that I'm not happy with... For example, touchpad two-finger scroll seems to count even a single device pixel as a whole scrollwheel "click", making scrolling much too fast in many cases (switching between tabs in a window, for instance). Ah well, can't please everybody.

**Comment by itsmattkc** [comment]
Admittedly, I do seem to remember `TimelineWidget::wheelEvent` being weirdly written when I was looking into #505, I think I wrote it with a mouse in mind and not really thinking about trackpads.

**Comment by elsandosgrande** [comment]
Maybe soon, maybe soon...

**Comment by mdmayfield** [comment]
Just found yet another odd case with horizontal scrolling and touchpads - I have some thoughts on how to approach this and have a laptop handy to test. If it's OK with you I'll try putting something together today.

**Comment by mdmayfield** [comment]
If it's not too much trouble, when you have some time would you be willing to correct the author data that I messed up on commit 9cb8f7 ? According to https://stackoverflow.com/a/28845565 it can be done with these steps:

```
git checkout 9cb8f7a62812de0213a33615f1296644a8d58c0f
git commit --amend --author "Matt Mayfield <mdmayfield@users.noreply.github.com>"
# Note new commit hash
git checkout master
# git replace 9cb8f7a62812de0213a33615f1296644a8d58c0f ##new-hash##
git filter-branch -- --all
git replace -d 9cb8f7a62812de0213a33615f1296644a8d58c0f
git push --force-with-lease
```

On my own branch, the new commit's hash became ff655633a917ddb266ef921a7a32fb66556cb62b.

If that's too much bother, no biggie. Thank you!

Matt

**Comment by mdmayfield** [comment]
Original issue (Ctrl for zoom) resolved & merged into master
