### ISSUE TITLE
Crashes when copy effect

### ISSUE THREAD

**Issue by ererbe** [olive-editor/olive#551]
*If you are requesting a feature, you can remove the following content. If not, it would help get a faster feedback on your issue.*

__Olive version:__  *January 2019*
__Source:__ *Website*
__Operating system:__ *Windows 7 64-bit* 
__CPU:__ *AMD A8-6600K*
__GPU:__ *8GB Sapphire Radeon RX 570 Nitro+*
Also tried internal: Radeon HD 8570D

### Detailed Description

The Program crashes when I try to copy an effect (tested with Text/Title or Bars)
Windows just say: no response.
(known stuff ->) When I try to copy the effects with ctrl+c it copy just basic stuff like the time length, position, also the animation, but not the settings like font, shadow, outline etc...

### Steps to reproduce

1.  Create an effect with some Settings
2.  Right Click
3.  Copy
And
(known stuff ->) 2.  May also try the Ctrl+C variant, and then paste it.
...

### Output log

Cant find any, sorry.

**Comment by itsmattkc** [comment]
The website build for Windows is quite old at this point (see #482) and I believe this issue has been fixed in recent commits. I'll try to update the online build as soon as possible and update this when I can.

**Comment by itsmattkc** [comment]
The website builds are now auto-updating and this should fix this issue. Feel free to let me know if not.
