### ISSUE TITLE
Reduce size of commits

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#554]
While I love how fast this project is progressing, it would be great to get smaller commits.
With a giant commit it is hard to see the parts of the code that have changed, and how they have changed.

I don't mind if the commits are pushed all at once, as long as they are not squashed when really really large.

**Comment by itsmattkc** [comment]
This most recent one was certainly an unusually large commit, I'll try to keep them smaller and un-squashed in the future.

**Comment by alcomposer** [comment]
Thanks @itsmattkc! Sorry for the request, gitg finds it hard to show mega-commits. :-( And online on GitHub it just doesn't show the larger diffs.

**Comment by itsmattkc** [comment]
No worries, I'll try to accommodate for that in the future
