### ISSUE TITLE
Low CPU load on *.MXF to *.MPG convertion 

### ISSUE THREAD

**Issue by kwiwtov** [olive-editor/olive#556]
*If you are requesting a feature, you can remove the following content. If not, it would help get a faster feedback on your issue.*

__Olive version:__  *february 2019 aplha f4668e3*
__Source:__ *repository for Ubuntu or website for Win version*  
__Operating system:__ *Ubuntu 18.04 64-bit or Windows 10 64-bit*  
__CPU:__ *any*  
__GPU:__ *any*

### Detailed Description

*Exporting sequence of x.MXF files to a MPEG-2 x.mpg file. Everything works fine, but CPU load is only 30-50% per any core of processor.
The same picture on a windows and ubuntu systems. On a different hardware.*

### Steps to reproduce

1.  
2.  
3.  
4.  
...

### Output log

```
please paste it here for better reading
```

**Comment by naj59** [comment]
Is that a problem? :smile:
Does it take longer than what you would expect?

**Comment by kwiwtov** [comment]
> Does it take longer than what you would expect?

The current job take 2.5 hours... If it could use all of CPU resources, it could take a maybe 2 times shorter period?

**Comment by naj59** [comment]
@kwiwtov

Ok then you are right, I am currently not looking into Olive but could a preference be the problem (something line use x amount of load, just like in Premiere)?

**Comment by kwiwtov** [comment]
> Ok then you are right, I am currently not looking into Olive but could a preference be the problem (something line use x amount of load, just like in Premiere)?

There is no load settings in the app. No thread settings, or something else even close. If you are using x264 codec - the load is 100%. So, I think this is the problem of mpeg-2 coding inside the Olive or not (my other editors did not support .MXF formats).

**Comment by naj59** [comment]
Probably this problem relies more on the ffmpeg side. Currently on mobile, sorry. 

You can also check up the discord in meantime..

**Comment by elsandosgrande** [comment]
Here's Discord (https://discord.gg/rvJMEYQ).

**Comment by itsmattkc** [comment]
This one's tough, we're certainly at the mercy of FFmpeg when it comes to the encoding, but to try and provide more control I've added a new option in c82ef62b13309f7a26e74f48a65f9c064d54b8a6 in Export > Advanced to allow users to specify the amount of threads to use. It's set to "auto" by default, but in case FFmpeg can't determine the correct amount, this should help.

**Comment by itsmattkc** [comment]
I believe the threads setting addresses this. If not, I suggest making an issue with FFmpeg and giving them details about your setup.
