### ISSUE TITLE
[Discussion] What features will be included in the first release

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#557]
First, I would like to express my gratitude  for the developer of Olive that he listens to our feature requests and implements them as quickly as he can. Big thanks.

Second, I would like to ask what features will be implemented in the first release and if there is a road map for the future additions to Olive.

So far, even if Olive is in alpha release, it has great design principles and I am sure it will dominate other editors as long as new features are added and the developers listen to the end users and implements their requests.

Regards,

**Comment by elsandosgrande** [comment]
My guess would be that it's too early to tell at this point.

**Comment by BrimsonBhin** [comment]
My speculation is that there will be
- Complete OCIO/OpenCV implementation
- Ton more shader effects (perhaps the ShaderToy folks can have fun with Olive)
- Further hardware acceleration (if this is possible)

I predict that a first proper stable release would be in a couple of years. You bring up a good point though, I hope the Olive Team has some sort of organized to-do list with what they are doing. Hope all goes well :)

**Comment by malnaanah** [comment]
I think wipe transitions should be given a priority too.

**Comment by DaniSeeh** [comment]
@malnaanah I think Wipe transitions should be lower priority than Masking since you could just animate your own wipes if you had Masking. I mean, you already kinda could do that but it would be really difficult as opposed to a few second process.

If Masking also is animate-able with the Graph Editor you would have pretty fine-toothed control over the wipes too

**Comment by malnaanah** [comment]
I totally agree, masking is more needed and could be used to create wipes. I wonder how long it might take before it get implemented.

**Comment by itsmattkc** [comment]
Pretty much what @BrimsonBhin said with a handful of others people have mentioned (e.g. masking, transitions, etc.), but I'm leaning heavily towards a rolling release strategy meaning there won't really be a "first release" per se. It's probable there'll be a point where stable/dev branches are separated, which I suppose you could call a "first release", but I don't really see it as working towards a "1.0" as much as I see it as perpetually improving with certain priorities.

**Comment by itsmattkc** [comment]
Any further discussion of this nature can happen in the Discord I think.
