### ISSUE TITLE
Olive won't display any effects if more than one clip is selected, including a linked audio/video pair

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#56]

**Comment by itsmattkc** [comment]
Implementing this will require a mild rewrite of the effects UI code. But it will be rewritten with this and #69 in mind.

**Comment by itsmattkc** [comment]
Olive can now display effects of linked pairs. It would be nice if Olive could display effects from an arbitrary amount of clips at a time, but that'll be a separate enhancement for later. For now, this is fixed.
