### ISSUE TITLE
Reversing certain footage floods "no PTS value" warnings, never finishes rendering

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#570]
__Olive version:__  Git as of 2019-02-28
__Source:__ Yes please!  
__Operating system:__ reproduced on Ubuntu MATE 18.10 and Windows 10
__CPU:__ i7-3770 or i5-6300HQ
__GPU:__ Intel i915 or NVidia Quadro FX 380

### Detailed Description

With certain media clips, reversing the footage causes two symptoms:
1) Attempting to render the project results in endless looping of errors similar to
```
2019-02-28T09:47:36 [WARNING] "VID_20180815_223825.mp4" frame had no PTS value
2019-02-28T09:47:36 [ERROR] Failed to retrieve frame for clip "VID_20180815_223825.mp4"
2019-02-28T09:47:36 [WARNING] Failed to create texture
```
Rendering never progresses beyond 0%.

2) When the playhead is at the start of the reversed clip, video is black and repeated errors similar to 1) above are shown.

**Workaround:** Step frame-by-frame from the start of the reversed footage to find the first frame that displays an image and stops the errors. Trim the start of the reversed footage to this point. Then exports work, and errors are not displayed in stdout.

### Steps to reproduce

1) Open attached project, [Backwards-issue.zip](https://github.com/olive-editor/olive/files/2915806/Backwards-issue.zip)
2) Right-click clip in Timeline, Speed/Duration, click Reverse, OK
3) Press **Home** to go to start of timeline
- Observe continuous errors in terminal output:
  - `[WARNING] "VID_20180815_223825.mp4" frame had no PTS value`
  - `[ERROR] Failed to retrieve frame for clip "VID_20180815_223825.mp4"`
  - `[WARNING] Failed to create texture`
4) **File** -> **Export** and attempt to export with default settings
- Observe similar continuous errors
- Export progress never continues beyond 0%
5) Cancel export
6) With Timeline in keyboard focus and playhead at start of project, tap **Right** key three times
- Note that image appears
- Errors stop
7) Trim the left side of the clips to the playhead
8) **File** -> **Export** and attempt to export with default settings again
- Export succeeds

### Output log

See above

**Comment by itsmattkc** [comment]
cab3c93004cf5486d2b7cebd4550071cc455d558 should fix this

**Comment by mdmayfield** [comment]
Exported successfully, and only gives a single "no PTS value" warning, once per access of a problematic frame (not repeated). Thanks!
