### ISSUE TITLE
TIF image sequence loads up as a sound file

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#578]
__Olive version:87df07e__  
__Source:__ *Main Website, Download*  
__Operating system:__ *Windows 10 Pro 64 Bit*  

### Detailed Description

Not sure why but whenever I try to load in an image sequence as a TIF:
![image](https://user-images.githubusercontent.com/5027750/53626949-f2351900-3bbb-11e9-81e8-91f2c8029227.png)

Olive assumes that it is a sound file. I'm pretty sure it isn't.

### Steps to reproduce

1.  Create an image sequence under the .tif format
2.  import the image sequence into olive.

**Comment by Symbian9** [comment]
What OS you use?

What extention this image has (including letters case): `*.tif`, `*.tiff`, `*.TIF`, `*.TIFF`?

**Comment by Corruptinator** [comment]
OS as in Operating System, is at the above post. (Windows)

and the image sequence used is a (.tif)

**Comment by elsandosgrande** [comment]
That's actually visible in the screenshot and in his post @Symbian9 .

**Comment by Symbian9** [comment]
I just tested import `tif`/`TIF`/`tiff`/`TIFF` in latest *Olive* build -- all seems work for me.

Olive version: `48497dd`

OS: *Linux*

**Comment by Corruptinator** [comment]
I was using the downloaded build from the website page. Tried to compile the latest build but currently there is a serious internal compiler error within MSYS2. For now i have no way of testing it out.

**Comment by itsmattkc** [comment]
TIF sequences are also working as expected for me.

@Corruptinator In your case, I'd recommend downloading Qt directly from the website for now. You can install it for MSVC or MinGW and it should work for both (MSVC requires Visual Studio but I think it comes with its own MinGW environment so you won't get compile errors)

**Comment by itsmattkc** [comment]
@Corruptinator Any better now that you can compile the latest Git?

**Comment by Corruptinator** [comment]
I'll need to check.

**Comment by Corruptinator** [comment]
Been busy but in experimentation, the tif is still reading as a sound file:

![image](https://user-images.githubusercontent.com/5027750/53939501-15524380-4068-11e9-9603-08de29f6bf79.png)

**Comment by itsmattkc** [comment]
You may have to send this TIFF sequence, looks like it's something specific to it

**Comment by Corruptinator** [comment]
[tif image sequence.zip](https://github.com/olive-editor/olive/files/2944273/tif.image.sequence.zip)

In that case, here are the image sequence. By the way, it was rendered using MAYA 2018.5 on this setting:

(The compression used to make the sequence)
![image](https://user-images.githubusercontent.com/5027750/54005740-68330600-410f-11e9-885a-e65462fdbcc3.png)

There are other dropdown menu selections as well: perhaps one of them could be subject to making the tif image sequence become sound files in the Olive Project Menu:

![image](https://user-images.githubusercontent.com/5027750/54005812-b6e0a000-410f-11e9-86aa-7c215cff73ee.png)

![image](https://user-images.githubusercontent.com/5027750/54005815-bf38db00-410f-11e9-9b94-299fd34acb8d.png)

![image](https://user-images.githubusercontent.com/5027750/54005788-987aa480-410f-11e9-9365-b4d593d7ece7.png)

**Comment by itsmattkc** [comment]
Ahh indeed, it looks like FFmpeg doesn't support float TIFF files yet. Olive shouldn't be presenting them as audio, but unfortunately the correct behavior is not accepting them at all.

See https://trac.ffmpeg.org/ticket/5303 for more details.

**Comment by Corruptinator** [comment]
It just seems that I keep discovering external bugs outside Olive don't I?    :P

**Comment by itsmattkc** [comment]
Haha it does seem that way, but hey it's helpful information. d4df41152692f66717d3b6b9d369afa2380ce3ad will display an actual error, which addresses this issue as much as I can, sorry you won't be able to import these kinds of image sequences for now though.

**Comment by Corruptinator** [comment]
Kinda wonder what other image formats with floats that FFMPEG doesn't support as well?

**Comment by itsmattkc** [comment]
The implication from that FFmpeg ticket ([and the one it depends on](https://trac.ffmpeg.org/ticket/3657)) is that it's basically all of them. FFmpeg supports a lot of pixel formats but no float-based ones it seems.

**Comment by Corruptinator** [comment]
DANG.
