### ISSUE TITLE
In Linux compile instructions, need to add libqt5svg5-dev as a dependency

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#579]
Compilation on Linux since some of the SVG changes now requires the `libqt5svg5-dev` package (on Ubuntu; other distros may call it something else).

Without that installed, `qmake` will return error `Project ERROR: Unknown module(s) in QT: svg`.

**Comment by elsandosgrande** [comment]
In that case, I already have it installed.

So, I just checked in the Arch repositories and it seems to be called `qt5-svg`.
Description: `Classes for displaying the contents of SVG files`

**Comment by itsmattkc** [comment]
Indeed, many Qt installations install QtSvg by default. The AppImage was one that didn't (#569, #567), so it is probably best to make it an official dependency.

**Comment by itsmattkc** [comment]
Added to the compile instructions now
