### ISSUE TITLE
Double click timeline, the software exits the interface -Windows10

### ISSUE THREAD

**Issue by Delmurat** [olive-editor/olive#580]
https://youtu.be/4qAviQxEniU

**Comment by BrimsonBhin** [comment]
I also tested. I can confirm this is happening on Windows 10 `Build 17763.316` as well.

This happens **only** on the timeline window. Double-clicking any other window besides the timeline does not cause the crash.

**Comment by itsmattkc** [comment]
This was fixed a few weeks ago, but the Windows build hasn't been updated in some time since I've been away from my regular setup. There _should_ be automatic builds for Windows as there are for Mac+Linux, but issues with Travis CI prevent them from working (#482).
