### ISSUE TITLE
First seconds fail to render

### ISSUE THREAD

**Issue by miltonics** [olive-editor/olive#581]
*If you are requesting a feature, you can remove the following content. If not, it would help get a faster feedback on your issue.*

__Olive version:__  
__Source:__ *(AppImage, Website etc.)*  
__Operating system:__ *(Ubuntu 18.04 64-bit)*  
__CPU:__ *Intel i5-4300U*  
__GPU:__ *NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx)*

### Detailed Description

Render as mp4, first seconds are cut off.

### Steps to reproduce

1.  Audio intro and title slide then video.
2.  Export with default features
3.  First seconds cut off of intro song.  

Workaround by starting music at 00:00:00;21

...

### Output log

```
please paste it here for better reading
```

**Comment by itsmattkc** [comment]
You may have to elaborate on "cut off". Do you mean the first few seconds are missing entirely or just that the audio is silent for the first few seconds?

**Comment by miltonics** [comment]
The first half second or so is missing.

**Comment by itsmattkc** [comment]
Would you be able to create a quick video showing this happening?

**Comment by miltonics** [comment]
[short start.mp4.tar.gz](https://github.com/olive-editor/olive/files/2921378/short.start.mp4.tar.gz)

**Comment by itsmattkc** [comment]
Sorry, I meant more like a video of you using Olive and reproducing this issue.

**Comment by miltonics** [comment]
Just found your reply in spam :(

Attempting to recreate today was unsuccessful. Not sure what's changed but if it happens again I will make a video of my actions.
