### ISSUE TITLE
Transform->Position dragging in viewer window doesn't always allow full movement

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#583]
1) Select media on Timeline
2) Go to Effects
3) Drag image in Sequence Viewer to set Position

Under certain conditions, the drag switches from an image position drag to an OS drag-and-drop action prematurely. That is, after moving only a dozen pixels or so, the cursor turns into "Prohibited" sign, image stops moving, OS takes over, and if dragged into a text editor, the letter "h" is dropped as per https://github.com/olive-editor/olive/blob/master/ui/viewerwidget.cpp#L353

This may have to do with the Scale parameter; still narrowing down the exact conditions.

Guessing the cause is somewhere in `ViewerWidget::get_gizmo_from_mouse` https://github.com/olive-editor/olive/blob/master/ui/viewerwidget.cpp#L262 - looking into this now.

**Comment by mdmayfield** [comment]
This is a regression - I remember this didn't happen on builds from last week. Hard to pinpoint exactly where it happened because many revisions do not compile.

`git bisect` reports:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 47d0065effc36e4306a6464cb256315f37ad07dd
> a1455ce9c7560d2b48073ce82013e3c0f71263c5
> c3373524b17d0e4134cd51955fa5482f7cfb8c99
> b9d7efa0bcc3b47bdf78f5988ca988bc52d5bd5d
> da2f51ee6e6d808891a1370bfd2b6c54769e8caa
> 110b75a04dc4d9db7f395760ef9133c7e99b30bb
> 39d62fe39486526ecaca7ace3006407107c270df
> 3233c0d0f96210b973e485911c4bc84103c593ed
> We cannot bisect more!

**Comment by itsmattkc** [comment]
Funnily enough another rendering backend regression. Try 2e400c7c552b5ecd4fb24cd586dd1394a0bc43da

**Comment by mdmayfield** [comment]
Thank you, that fixes it! That was a subtler root cause than I thought.
