### ISSUE TITLE
[Feature Request] GLSL Transition Editor

### ISSUE THREAD

**Issue by frink** [olive-editor/olive#586]
Olive already uses GLSL so it makes sense to expose something like a GLSL for complex transitions.

See reference:
https://gl-transitions.com/

**Comment by BrimsonBhin** [comment]
Those transitions are amazing. Nice find 🥇

![image](https://user-images.githubusercontent.com/40442071/53704576-fdb25b00-3dda-11e9-8924-b007678b8bd6.png)

If the configuration scheme is like this, I am think means the transitions right now have to be treated as a different strip in the graph editor (to properly configure the time).

**Comment by frink** [comment]
That may be true. This site is amazing and really shows the power of GLSL when used properly.

**Comment by frink** [comment]
I'm a big fan of adding scripting into things. Lua's addition into Ardour and OSB has been a huge boon. I like the frame context sensitivity that these transitions have. And the language overall is very well thought out. Reminds me of Faust in the audio domain...

**Comment by cgvirus** [comment]
This would help to create complex effects like even optical flare as well... I can port my whole GLSL shaders here if it can be implemented.

**Comment by BrimsonBhin** [comment]
@cgvirus I would wait until `furtherocio` is complete. That branch standardizes around OpenGL ES 3.0 and has changes in Olive's pipeline

**Comment by cgvirus** [comment]
Awesome...It seems we can already port a huge library of effects frag with xml..
I am very much hopeful with Olive. Have only started exploring and already mind is blown. Olive will be a game changer. @BrimsonBhin

**Comment by cgvirus** [comment]
Just made a pull request for some glitch effect. Let's see how things go! I love this app.

**Comment by frink** [comment]
Excited to see your enthusiasm @cgvirus!!

**Comment by unfa** [comment]
@cgvirus  - I've used one of your effects in my latest video in the final text sequence:
https://youtu.be/jWJHl25hxWI?t=461

**Comment by frink** [comment]
Nice glitch. I wouldn't have chosen that font to pair with the effect. But it seemed to work well.

**Comment by enzogian** [comment]
Hi, I am new using OLIVE but I wonder if there would be some more transition effects available in future versions ? (at the moment I just can see the "dissolve" one but not sure where to find others ? I suppose is still early to have more alternatives but hope stable release could come with some more options (?)
Thanks and congrats for such a robust and stable software so far !!!

**Comment by oc1024** [comment]
Currently, new features are less of a priority due to a thorough code review process. However, if/when @frink 's suggested library gets accepted, there'll be quite a few new transitions from the get-go.

**Comment by Symbian9** [comment]
> See reference:
> 
> https://gl-transitions.com/

Here is its GitHub repo:

- https://github.com/gl-transitions/gl-transitions

**Comment by enzogian** [comment]
> Currently, new features are less of a priority due to a thorough code review process. However, if/when @frink 's suggested library gets accepted, there'll be quite a few new transitions from the get-go.

wonderful to hear that, it would be great I am sure.
Thanks a lot.

**Comment by enzogian** [comment]
> > See reference:
> > https://gl-transitions.com/
> 
> Here is its GitHub repo:
> 
> * https://github.com/gl-transitions/gl-transitions

I don't have idea on how to implement these transitions when using olive, I have posted a request in our fb group to see if some users could make a video tutorial of some example on how to use it (?)
Thanks a lot and regards ;)

**Comment by cgvirus** [comment]
Thanks for the source. I will look into it and will add some in this repo:
https://github.com/cgvirus/Olive-Editor-Community-Effects
