### ISSUE TITLE
Feature Request: Sub-Projects as Timeline Elements

### ISSUE THREAD

**Issue by frink** [olive-editor/olive#588]
In larger projects like Feature Films including the entire thing in one timeline is asking for disaster. One of the reason that proponents of Lightworks love it so much is the concept of sub-timelines that can be includes allowing for more focused editing.

Basically, the idea is to edit one scene as a project and then have a master project to stitch those scenes together. This is also helpful when different moods are present in those different scenes to divide up the movie into smaller segments for create the stark emotional contrast. Since these sub-project timelines have separate versioning due to the sub-project files saving the edits to allow different editors to focus on these different scenes for better distribution of workload.

If our goal is to produce an editor for the professional market this is one of the biggest things besides proxy files which can set us apart from the other open source editors. Unlike most prosumer editors, a professional workhorse needs to be useable by a team of editors who may be distributed geographically. It is not only the edit experience that must be managed but the version control and approval processes.

This feature starts down the road by allowing pieces to be stitched together. Once that is in place version control and management procedures can easily be bolted on to the editing process to allow a full professional workflow...

**Comment by oc1024** [comment]
I was thinking of opening an issue with "Allow Importing of .OVE files".

This includes that, plus a valid justification.

**Comment by itsmattkc** [comment]
Importing Olive projects into others had been planned for a while. It's now implemented in a16d8a4fe177cf629912af4013ca8cee0b7bc057. With nested sequences already supported, I believe that solves this issue.

**Comment by frink** [comment]
That is perfect.

One of the only remaining issues with this is how to navigate into the sub-project from the imported clip on the timeline. Assuming that this can be done via some sort of context menu, I'd say that you can consider this as completely fulfill!!

**Comment by itsmattkc** [comment]
You mean navigating from the main sequence into one of the nested ones? I believe double clicking the clip on the timeline should do that. Perhaps an extra context menu can be added later too for flexibility.

**Comment by frink** [comment]
Double-clicking should work...

What happens in that case?
- Do we then have two windows that each have different projects? Or does the nested project replace the parent project?
- Also, what happens when significant changes are made to the nested project? Are those immediately reflected in the parent or does a reload/refresh have to take place to get the newest edits?

As mentioned here and elsewhere, the main thing I'm concerned with is how to manage a distributed team working on different pieces of the project. Also trying to figure out how to do version control and editorial approval of both projects... (definitely beyond the scope of this ticket...)

**Comment by alcomposer** [comment]
when entering a nested sequence, it takes over the project, and the viewer. any changes are reflected immediately in any project that contains the sub-clip.

**Comment by frink** [comment]
How does one traverse back to the parent project then to continue working at that level?

**Comment by alcomposer** [comment]
@frink (currently) double click the parent project in the `project viewer`.

**Comment by oc1024** [comment]
One thing to add, once we fix #597: is it possible to get each imported project to have its own folder?

Like, when one imports "ActionScene3.ove", a folder named "ActionScene3" is made and stuff is dropped there.

**Comment by frink** [comment]
@alcomposer - That sounds great.

@oc1024 - I like where your head is at. The question behind the question is: "How do we organize and manage larger projects?" - I think this is one of the biggest questions that has been swept under the rub by most open source solutions.

I'm very thankful for Next Gen because it has forced Blender to think through more of the resource management questions that production houses face. I think Kdenlive + Krita could do with a reality check their too. But ultimately, you need an editor that is flexible to allow any workflow that a production house may throw at it...

We may want to allow a configuration switch that allows opening Sub-Projects in a new window VS current window so that one can jump between two Sub-Projects to compare something or possibly share the clipboard...

I think we're headed in the right direction here.

**Comment by itsmattkc** [comment]
@frink I think I misunderstood your request initially, the current behavior is simply importing a project into another, essentially merging them into one so the initially open project can use the imported project's assets. At this point, no changes will ripple back to the original project as they're essentially just one project now. It seems like you're requesting more having two projects open at the same time so they can be worked on in parallel and included within each other. Is that more correct?

**Comment by frink** [comment]
Yes. Simple importing is not quite enough for my use case...

Think about git submodules and how important they are to our workflow as software developers. I'm essentially suggesting a similar paradigm for sub-projects here. There needs to be a way to transverse  sub-projects and selective import changes like the way pinning submodules works in git.

Let's say that a director can't decide the order of scenes or perhaps a specific cut of the same scene inside the larger context of the story. Every new scene written and shot has the potential to change what was cut the previous day. If we look at the editing as a timeline of timelines then we are closer to how a director or screenwriter is likely to think about things.

Blender starts to try to get into this territory a little with some of its more recent workflow changes but Lightworks is the one that really has this theory fleshed out. Ultimately, we need way to switch between "snapshots" (Ardours word for versioning) of our sub-project timeline inside our parent timeline to view different versions of scenes in the context of the greater story.

This is something that most editors do poorly. But if you chop things in small pieces it works better for everyone. This also starts to build a practical framework for some of the background rendering ideas that have been floating around in a few tickets...
