### ISSUE TITLE
Add empty clips

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#592]
Add two actions/tools for adding empty clips to sequence:

- Add empty video clip;
- Add empty audio clip;

This tools should be available in context menu for "Timeline" window.

**Comment by itsmattkc** [comment]
What would the purpose of an empty clip be?

**Comment by oc1024** [comment]
Using Render/Tone Generator effects on them, I guess.

**Comment by Symbian9** [comment]
> What would the purpose of an empty clip be?

Containers for video or audio effects.

Also those two actions should has shortcuts & be available throw menu "Tools" and "Action Search".

**Comment by Symbian9** [comment]
> Using Render/Tone Generator effects on them, I guess.

This is one of reasons.

As we has "+" button on instrument panel of "Timeline" that are presets, but it would be better if just limit it to "Add > Empty Video clip" and "Add > Empty Audio clip". And then user ahould choose needed effect throw "Effects" window.

**Comment by frink** [comment]
I still don't understand why empty audio clips are useful...

Video could be if you do effects. But what effects are we rendering in the audio clip? Are you gonna use a VSTi and MIDI to make a soundtrack or what?

**Comment by AGI-THB** [comment]
Do other programs have that functionality?

**Comment by Symbian9** [comment]
> But what effects are we rendering in the audio clip?

User should apply audio effects in "Effects" window of added empty audio clip. Same for video effects adding to empty video clip.

**Comment by BrimsonBhin** [comment]
This is already possible in Olive.

It's just that empty strips come with preconfigured effects when you add them (color for video, noise for audio).
