### ISSUE TITLE
[Feature request] x265 support for export

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#593]
It would be so nice if I could export my 4k Video in a more space friendly codec like x265!
For this purpose you could add an libx265 dropdown menu entry in "Codec" under "MPEG-4 Video"!
Thank you so much in advance and keep up the great work!

**Comment by itsmattkc** [comment]
I'm actually surprised, I could have sworn the H.265 tags were already in there. Ah well, they are now in 5d879128442026b0bd4bc1a981c045d6e184659d
