### ISSUE TITLE
[Feature Request] Multiple Bézier handle modes

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#594]
Olive's Bézier handles are epic and I enjoy them a lot. Pretty comical that Olive got this feature down while other open-source NLE's with more developers lack it. Oh well..

I would like to request for an addition Bézier handle mode: **Free**.

With **free** Bézier handles, the user can alter the handle on one side without interfering with the other. Multiple handle modes allow more sophisticated animation without inserting more key-frames, (complicating a project more than it needs to).

Here's an example in Blender. The **Free** Bézier handles is the bottom-most one in black.

![image](https://user-images.githubusercontent.com/40442071/53705052-deb5c800-3dde-11e9-9314-970fe6ec2cd8.png)

**Comment by itsmattkc** [comment]
If I understand this request correctly, it already exists. You can hold Ctrl while moving the bezier handles to only move one side at a time.

**Comment by BrimsonBhin** [comment]
@itsmattkc It does! Lol I did not know that. Thanks for the response.
