### ISSUE TITLE
Sequences in Folders inaccessible on re-open of project

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#597]
Observed in Linux and Windows versions of Olive, latest Git as of this writing.

To reproduce, open attached [seq-in-folder.zip](https://github.com/olive-editor/olive/files/2928408/seq-in-folder.zip) or:
1) New Project
2) Create two new sequences, and one folder
3) Move Sequence 01 into the folder
4) Save project and re-open

Expected behavior: both Sequences are visible, Sequence 02 in the root level and Sequence 01 in the folder.
![image](https://user-images.githubusercontent.com/26154258/53766828-94455180-3e99-11e9-9fca-d432016fff85.png)

Actual behavior: Sequence 02 is visible in the root level, but the folder appears empty and Sequence 01 is inaccessible.
![image](https://user-images.githubusercontent.com/26154258/53766810-855e9f00-3e99-11e9-9379-243d23fbf49b.png)

- If Sequence 01 was active at the time the project was saved, it is still active upon re-open
- In the XML, it is observed that Sequence 01 still exists and should be inside the folder
```
        <sequence id="2" folder="1" name="Sequence 01" width="1920" height="1080" framerate="29.9700000000" afreq="48000" alayout="3" workarea="0" workareaIn="0" workareaOut="0"/>
```
- On creation of a Sequence 03 in the project in the "hidden sequence" state, Sequence 01 will again become visible.

**Comment by oc1024** [comment]
I was able to reproduce this bug.

However, switching to icon view (right click) and double clicking the folder makes it accessible again, and, as you noticed, adding something to the project (importing media, new folder, new sequence) causes it to appear again.

It might be just an oversight in the function that populates the tree-view.
