### ISSUE TITLE
Compiling: System Error Cause of Missing Files

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#600]
__Olive version: *3233c0d fixed segmentation fault on release builds*__  
__Source:__ *Git Download (Master)*  
__Operating system:__ *Windows 10 Pro*  
__CPU:__ *Intel i7-5777U*  
__RAM:__ *16GB*  

### Detailed Description

I ran into a problem while finally figuring out a way to compile Olive:

Sincere apologies if this might count as a duplicate or a continuation of a previous issue I had under compiling Olive and for the fact this is a rather long wall of text:
https://github.com/olive-editor/olive/issues/546
Fortunately though, with help from others I found an alternative way, turns out that GCC 8.3 had a serious compiling error and that the only way to fix it was to downgrade GCC to 8.2. Many would say that downgrading GCC is hard, but it is doable:

First I downloaded the necessary packages 8.2 from the msys2 package repository:
(http://repo.msys2.org/mingw/x86_64/) These files are required:

```
mingw-w64-x86_64-gcc-objc-8.2.0-3-any.pkg.tar.xz
mingw-w64-x86_64-gcc-libs-8.2.0-3-any.pkg.tar.xz
mingw-w64-x86_64-gcc-libgfortran-8.2.0-3-any.pkg.tar.xz
mingw-w64-x86_64-gcc-fortran-8.2.0-3-any.pkg.tar.xz
mingw-w64-x86_64-gcc-ada-8.2.0-3-any.pkg.tar.xz
mingw-w64-x86_64-gcc-8.2.0-3-any.pkg.tar.xz

```

Next I copied those files into where msys would hold the packages (This is Msys64 [64-Bit]):
`C:\msys64\var\cache\pacman\pkg`

From there, using the MSYS terminal, we can now downgrade GCC:
```
cd /var/cache/pacman/pkg
pacman -U mingw-w64-x86_64-gcc-objc-8.2.0-3-any.pkg.tar.xz mingw-w64-x86_64-gcc-libs-8.2.0-3-any.pkg.tar.xz mingw-w64-x86_64-gcc-libgfortran-8.2.0-3-any.pkg.tar.xz mingw-w64-x86_64-gcc-fortran-8.2.0-3-any.pkg.tar.xz mingw-w64-x86_64-gcc-ada-8.2.0-3-any.pkg.tar.xz mingw-w64-x86_64-gcc-8.2.0-3-any.pkg.tar.xz
```

At this point you need to use Git command to download Olive from the master branch, but instead of the default location where you would use git I had to move my folder location to where it would not be under a folder name with spaces between words due to Linux/Unix's kernal syntax:

```
cd /c/
mkdir git
cd git/
mkdir Olive
cd Olive/
```
Just make a folder on the `C:/` Drive on Windows.
From there, following the compiling instructions: https://olivevideoeditor.org/compile.php
The compile actually works!

```
git clone https://github.com/olive-editor/olive.git
qmake
make
```

![image](https://user-images.githubusercontent.com/5027750/53781397-915c5800-3ebd-11e9-987c-c2083136e8fd.png)

You'll find the compiled files under the `debug` folder, that is where I found the olive-editor.exe, but when I started it that is where the issue comes in. I got these SYSTEM ERRORS due to Missing Files:

![image](https://user-images.githubusercontent.com/5027750/53781223-c9af6680-3ebc-11e9-8fd9-faa7b5d6831e.png)
![image](https://user-images.githubusercontent.com/5027750/53781229-d16f0b00-3ebc-11e9-95e3-91abefff1784.png)
![image](https://user-images.githubusercontent.com/5027750/53781232-d633bf00-3ebc-11e9-873c-fa57190fde94.png)
![image](https://user-images.githubusercontent.com/5027750/53781236-daf87300-3ebc-11e9-8ba2-05447c63f432.png)

I was that close to actually being able to open up the compiled Olive program, if not for the missing files of `avcodec-58.dll, avfilter-7.dll, avformat-58.dll, and avutil-56.dll`. So any ideas on where to go to next?

This is somewhat of a continuation but I wanted to point out the new issue after finding an alternate way to get the GCC to work.

**Comment by BrimsonBhin** [comment]
Have you tried using the `Shared` DLL files from [zeranoe](https://ffmpeg.zeranoe.com/builds/)? I want to see if this would work

**Comment by itsmattkc** [comment]
Yeah the missing files are FFmpeg's libraries and they should have come with installing `mingw-w64-x86_64-ffmpeg`... If not, the link @BrimsonBhin posted is definitely the best place to get precompiled ones for Windows. I'll have to double check and update the tutorial if that doesn't work.

**Comment by Corruptinator** [comment]
I think I know what the problem was, this is where the default folder location comes to play since the compiling instructions said to install the prerequisites at the main folder

```
The Corruptinator@Corrupt MINGW64 ~/olive
$ qmake
Info: creating stash file C:\msys64\home\The Corruptinator\olive\.qmake.stash
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
sh: C:/msys64/home/The: No such file or directory
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
sh: C:/msys64/home/The: No such file or directory
/usr/bin/git
git: 'Corruptinator/olive/.git' is not a git command. See 'git --help'.
sh: C:/msys64/home/The: No such file or directory
WARNING: Failure to find: debug/resources_res.o
WARNING: Failure to find: release/resources_res.o

The Corruptinator@Corrupt MINGW64 ~/olive
$
```

Problem now is that since MSYS is based on Linux/Unix kernel it does not like filenames with spaces in between.

**Comment by Corruptinator** [comment]
Turns out that you need to run the olive-editor.exe from command:
$ ./olive-editor
