### ISSUE TITLE
.txt file crashes Olive

### ISSUE THREAD

**Issue by NathanSalapat** [olive-editor/olive#601]
__Olive version:__  27d77ab
__Source:__ PPA
__Operating system:__ Linux Mint 19.1 64-bit
__CPU:__ Intel i7-8700K
__RAM:__ 32GB
__GPU:__ NVIDIA Geforce GTX 1060 6GB (Driver ver 390.77)

### Detailed Description

I can drag a .txt file into the media bin, and it appears to be accepted. I can pull up the properties and see a resolution, frame rate, and even a tiny sample of the contents of the text file. Once I add the file to the sequence and try to view the single frame it displays on Olive will crash. I'm not sure if I should even be able to add a .txt file to the media pool, but I can. I can add other formats as well, such as .log, .db, and even appimages but those can't be added to the sequence.

### Steps to reproduce

1.  create a txt file
2.  add .txt file to sequence.
3.  try to view frame the text file is on.
4.  watch the crash
...

### Output log

```
Input #0, tty, from '/home/nathan/dev site login.txt':
  Duration: 00:00:00.04, bitrate: 12 kb/s
    Stream #0:0: Video: ansi, pal8, 640x400, 25 fps, 25 tbr, 25 tbn, 25 tbc
[swscaler @ 0x7fe80006b620] Warning: data is not aligned! This can lead to a speed loss
2019-03-05T09:31:54 [INFO] Clip closed on track -1
Input #0, tty, from '/home/nathan/dev site login.txt':
  Duration: 00:00:00.04, bitrate: 12 kb/s
    Stream #0:0: Video: ansi, pal8, 640x400, 25 fps, 25 tbr, 25 tbn, 25 tbc
2019-03-05T09:31:54 [INFO] Clip opened on track -6 (took 7 ms)

2019-03-05T09:31:54 [WARNING] "dev site login.txt" frame had no PTS value
Segmentation fault (core dumped)
```

**Comment by oc1024** [comment]
This is what happens when I add a txt file:
![image](https://user-images.githubusercontent.com/7990860/53823271-2f98fe00-3f50-11e9-8ceb-f0388ed7816f.png)

We both have:
`Stream #0:0: Video: ansi, pal8, 640x400, 25 fps, 25 tbr, 25 tbn, 25 tbc`

When I type `ffmpeg -codecs 2>1 | grep ansi` on a terminal, I get:
```
 D.V.L. ansi                 ASCII/ANSI art
 D.A.L. mace3                MACE (Macintosh Audio Compression/Expansion) 3:1
 D.A.L. mace6                MACE (Macintosh Audio Compression/Expansion) 6:1
```
i.e. my ffmpeg has an ASCII art codec.

**Comment by itsmattkc** [comment]
Yep this is coming from FFmpeg's ASCII decoder as @oc1024 says. The crash has been fixed in f9e7c3a3dd3d11aad045e52665bde56c88a46f0f, but generally you can consider importing text behavior as undefined. Using it to import a title may be interesting in the future.

**Comment by alcomposer** [comment]
> Using it to import a title may be interesting in the future.

Possibly also subtitle files?

**Comment by NathanSalapat** [comment]
I didn't expect anybody would ever try to import a txt file. I was just fooling around for a little review project I'm working on and wondered what would happen if I tried using files that weren't images, audio, or video.
