### ISSUE TITLE
Sequence viewer frozen on first frame

### ISSUE THREAD

**Issue by bradleypariah** [olive-editor/olive#602]
[ConX.ove.zip](https://github.com/olive-editor/olive/files/2932465/ConX.ove.zip)

__Olive version: I don't know (?)  I went to Help > About, and the window no longer says, but I just installed the latest update today.
__Source: ppa:olive-editor/olive-editor
__Operating system: Ubuntu Studio 18.04 64-bit
__CPU: i5-6500K  
__RAM: 32GB  
__GPU: gtx960

I have a project that I created a week or two ago, and when I open it now, the project seems to load just fine, and I see the first frame of the session in the Sequence Viewer, but if I hit play, the Sequence Viewer stays on the first frame.  I hear the audio as the cursor moves through the session, and I can scrub audio as well.
If I right-click the sequence in the Project list, then choose Preview in Media Viewer, it just plays a black screen.

### Output log
[WARNING] QXcbConnection: XCB error: 3 (BadWindow), sequence: 4261, resource id: 8589217, major code: 40 (TranslateCoords), minor code: 0 (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Clip opened on track 0 (took 34 ms) (:0, )
[INFO] Clip closed on track 1 (:0, )
[INFO] Clip opened on track -5 (took 146 ms) (:0, )
[INFO] Clip opened on track -1 (took 18 ms) (:0, )
[INFO] Clip opened on track -2 (took 15 ms) (:0, )
[INFO] Clip opened on track -6 (took 4 ms) (:0, )
[INFO] Clip opened on track 1 (took 11 ms) (:0, )
[INFO] Clip closed on track 1 (:0, )
[INFO] Clip closed on track -4 (:0, )
[INFO] Clip closed on track -5 (:0, )
[INFO] Clip closed on track -1 (:0, )
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1327 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1320 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1315 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1304 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1281 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1245 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1236 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1230 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1225 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1220 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1208 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1197 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1187 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1180 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1172 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1166 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1163 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1158 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1139 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1129 
[INFO] Clip opened on track 1 (took 22 ms) (:0, )
[INFO] Clip closed on track 1 (:0, )
[INFO] Clip opened on track 1 (took 26 ms) (:0, )
[INFO] Clip closed on track 2 (:0, )
[INFO] Clip opened on track -5 (took 165 ms) (:0, )
[INFO] Clip opened on track -1 (took 28 ms) (:0, )
[INFO] Clip opened on track -3 (took 31 ms) (:0, )
[INFO] Clip opened on track 2 (took 39 ms) (:0, )
[INFO] Clip opened on track -4 (took 17 ms) (:0, )
[INFO] Clip closed on track -9 (:0, )
[INFO] Clip closed on track -7 (:0, )
[INFO] Clip closed on track -6 (:0, )
[INFO] Clip closed on track -8 (:0, )
[INFO] Shader program linked successfully (:0, )
[INFO] Fragment shader added successfully (:0, )
[INFO] Vertex shader added successfully (:0, )
[INFO] Clip opened on track -7 (took 28 ms) (:0, )
[INFO] Clip opened on track -6 (took 26 ms) (:0, )
[INFO] Clip opened on track -8 (took 20 ms) (:0, )
[INFO] Shader program linked successfully (:0, )
[INFO] Fragment shader added successfully (:0, )
[INFO] Vertex shader added successfully (:0, )
[INFO] Clip opened on track -9 (took 211 ms) (:0, )
[INFO] Shader program linked successfully (:0, )
[INFO] Fragment shader added successfully (:0, )
[INFO] Vertex shader added successfully (:0, )
[WARNING] QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) (:0, )
[INFO] Matched "Images/101 blur.png" relative to project's current directory (:0, )
[INFO] Matched "Audio/201_full_corporate-tech-logo_0013.wav" relative to project's current directory (:0, )
[INFO] Matched "Video/Ultra Launch Sequence.mp4" relative to project's current directory (:0, )
[INFO] Matched "Images/Title.png" relative to project's current directory (:0, )
[INFO] Matched "Video/Outro.mp4.mp4" relative to project's current directory (:0, )
[INFO] Matched "Video/Intro Green Screen x2.mp4" relative to project's current directory (:0, )
[INFO] Matched "Video/2019-02-20_08-38-28.mp4" relative to project's current directory (:0, )
[INFO] Matched "Video/2019-02-20_08-24-41.mp4" relative to project's current directory (:0, )
[INFO] Matched "Images/White Background.png" relative to project's current directory (:0, )
[INFO] Matched "Images/New Hand.png" relative to project's current directory (:0, )
[INFO] Matched "Images/Mondopad_Ultra_Glass.png" relative to project's current directory (:0, )
[INFO] Matched "Images/Mark up tools Err.png" relative to project's current directory (:0, )
[INFO] Matched "Images/Mark up tools Cirque.png" relative to project's current directory (:0, )
[INFO] Matched "Images/InFocus-white-logo.png" relative to project's current directory (:0, )
[INFO] Matched "Images/Blue Background.png" relative to project's current directory (:0, )
[INFO] Matched "Images/black bg.png" relative to project's current directory (:0, )
[INFO] Matched "Images/101.png" relative to project's current directory (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Finished initializing effects (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Deleted 1 autorecovery file that was older than 7 days (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing custom cursors (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[WARNING] QApplication: invalid style override passed, ignoring it. (:0, )

**Comment by itsmattkc** [comment]
The version should be in the window title, but I've added a version identifier to the about dialog to make things clearer.

As for the issue itself, is it only this project or does it occur with new projects too? Additionally does it occur with any media or just the media that this project starts with?

**Comment by bradleypariah** [comment]
Olive version: February 2019 | Alpha | 464ce74

I tried to re-built the session from scratch, and the assets seemed to be acting okay.  I saved my work as "ConX-2", then opened the session file "ConX", attached in my previous post, and the session played fine for about three seconds, then the sequence viewer froze.  
I closed the frozen session, the re-opened the "ConX-2" session that was previously working, and it is now corrupted.  Froze on the first frame of the session.  When I hit play, only the audio works correctly.

**Comment by bradleypariah** [comment]
Downloaded update, now on 3b2990b

I can't do anything with the software at all now.  If I drag any file of any kind into the Project window, then attempt to drag that file into the Timeline window, absolutely nothing happens whatsoever.  The UI does not change.  It remains all blank gray boxes.  If I hit play, I can hear audio, if the file had audio to begin with.

**Comment by itsmattkc** [comment]
You mean the entire app window is just gray with no UI objects? That's strange. Can you send any of these footage files? Also try with [the latest AppImage](https://github.com/olive-editor/olive/releases) and see if that's any different.

**Comment by bradleypariah** [comment]
No, the entire window looks like it does when there's no files.  All the UI elements are simply empty, not "broken."  Regardless, I downloaded the AppImage, 662219a, and now I'm back to the original problem in the OP.  The Sequence Viewer refuses to change.  It's stuck on a single frame.  What's even more odd, I just started up a brand new session, and imported a completely unrelated video file, hit play, and the Sequence Viewer was still stuck on the first frame of the previous session.
Check out the attached video. 
[2019-03-08 06-23-57.mp4.zip](https://github.com/olive-editor/olive/files/2946436/2019-03-08.06-23-57.mp4.zip)

**Comment by itsmattkc** [comment]
It may in fact be a good idea to zip that entire folder and send it through, it looks like the rendering backend is getting stuck on a frame for some reason and isn't able to recover, so I think I'll need to take a look at the media you're using to see what's causing that.

**Comment by bradleypariah** [comment]
Here it is: https://www.dropbox.com/s/1pemx9x7u10iksa/ConX.zip?dl=0

**Comment by bradleypariah** [comment]
I'm not positive, but I think this may be an ffmpeg issue.  One of the files in the above session, called "Ultra launch sequence," seems to lock up the session.  I tried to convert the file to repair it, and I'm getting the error: 
"Too many packets buffered for output stream 0:1.
[aac @ 0x5647ce296960] Qavg: 65033.195
[aac @ 0x5647ce296960] 2 frames left in the queue on closing
Conversion failed!"

**Comment by itsmattkc** [comment]
From taking a look at your project, it seems "Ultra Launch Sequence.mp4" is a very strangely encoded file. FFmpeg was failing to get the correct timestamp and it seems to be missing a lot of early frames too. Regardless, Olive should be resilient to this so 2f86888a8db7e9c4b70af1ff93195c4c0e10a491 should address this, let me know if it does!

**Comment by bradleypariah** [comment]
It was made by OBS.  I wonder what happened?  I guess I might need to re-think my settings.  I'll look into it during my next capture.   Thank you!  :)  

I just checked the /releases page, and it looks like the 64-bit AppImages aren't up yet.  I tried to launch the 386 image just for kicks, but it won't open.  I'll check back later.

**Comment by itsmattkc** [comment]
I'm not sure either, OBS videos are usually fine afaik.

Also looks like there was a compile issue delaying the 64-bit AppImage, but it's up now.

**Comment by bradleypariah** [comment]
Got it.  It works great!  Thank you so much!

**Comment by itsmattkc** [comment]
Excellent, glad to help!
