### ISSUE TITLE
Making the menubar look more professional on Windows

### ISSUE THREAD

**Issue by naj59** [olive-editor/olive#606]
So as I stated in https://github.com/olive-editor/olive/issues/545#issuecomment-466642704, on Windows it would look way more professional to let the menu bar use the systems style (just like as Premiere does). Fusion is great, I like it really much, but using it anywhere gives the application in my opinion (on windows) a more clumsy look.

I wrote a sample application and set it up in theming just like Olive.

```cpp
    qApp->setStyle(QStyleFactory::create("Fusion"));

    QPalette darkPalette;
    darkPalette.setColor(QPalette::Window, QColor(53,53,53));
    darkPalette.setColor(QPalette::WindowText, Qt::white);
    darkPalette.setColor(QPalette::Base, QColor(25,25,25));
    darkPalette.setColor(QPalette::AlternateBase, QColor(53,53,53));
    darkPalette.setColor(QPalette::ToolTipBase, QColor(25,25,25));
    darkPalette.setColor(QPalette::ToolTipText, Qt::white);
    darkPalette.setColor(QPalette::Text, Qt::white);
    darkPalette.setColor(QPalette::Button, QColor(53,53,53));
    darkPalette.setColor(QPalette::ButtonText, Qt::white);    
    darkPalette.setColor(QPalette::BrightText, Qt::red);
    darkPalette.setColor(QPalette::Disabled, QPalette::ButtonText, QColor(128, 128, 128));
    darkPalette.setColor(QPalette::Link, QColor(42, 130, 218));
    darkPalette.setColor(QPalette::Highlight, QColor(42, 130, 218));
    darkPalette.setColor(QPalette::HighlightedText, Qt::black);

    qApp->setPalette(darkPalette);
    QMenuBar *menuBar = new QMenuBar(this);
    menuBar->setStyle(QStyleFactory::create("windowsvista"));
    menuBar->setStyleSheet("color: black;");

    QList<QMenu*> menuList;

    fileMenu = menuBar->addMenu("File");
    helpMenu = menuBar->addMenu("Edit");

    menuList.append(fileMenu);
    menuList.append(helpMenu);

    Q_FOREACH(QMenu *m, menuList) {
        m->setStyle(QStyleFactory::create("windowsvista"));
    }

    this->setMenuBar(menuBar);
```
What I achieve is this: ![imgur](https://i.imgur.com/1Ucp5gAl.png)

The problem is as you can see I currently set the colors of the menubar manually using the ``setStyleSheet`` option. Any ideas about that? Shouldn't be an option to do this using this way. Even though this should also be done in the ``Q_FOREACH`` because the QPalette is also overriding the actual color of the menu bar's items.

Also is this a way to go? I would like it much more with that style on that platform...

**Comment by itsmattkc** [comment]
"More professional" is very subjective, but I can appreciate the appeal of getting a more native experience. I did actually briefly experiment with this a while back and found the same thing you did - it requires "un-setting" the style on all QMenu objects individually. There may be a trick to make it simpler (e.g. subclassing `QMenu` to always set itself to `windowsvista` on Windows), but unfortunately I don't think there's anything as clean as setting a style on just the whole class or something.

**Comment by naj59** [comment]
Atleast give the user the ability to set a checkbox in preferences for that (if we're on windows). I'll test around a little bit in the next days...

**Comment by itsmattkc** [comment]
Indeed, if this can be implemented cleanly, I'll make it default on Windows probably with an option somewhere to revert to full Fusion.

**Comment by itsmattkc** [comment]
Added in 791bc0c9b8a264d33fe46fe40485e3d504a6f092, can be disabled in Preferences.
