### ISSUE TITLE
Crash when moving the red pointer

### ISSUE THREAD

**Issue by MichaelObvious** [olive-editor/olive#612]
__Olive version:__  f07dd69
__Source:__ *(AppImage, Website etc.)*  
__Operating system:__ (Ubuntu 18.10 64-bit*  
__CPU:__ *Intel® Xeon(R) CPU E5-2670 0 @ 2.60GHz × 16 *
__RAM:__ *8GB*  
__GPU:__ *NV126*

### Detailed Description

When moving the red pointer the program gets stuck and
 after a few seconds crashes.

### Steps to reproduce

1.  Create a project an then a new sequence (30 fps, 1980x1920, 48000kHz).
2.  move the red pointer a bit

### Output log
I opened the debug log and i saw this:
```
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Finished initializing effects (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing custom cursors (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
```
![olive_crash](https://user-images.githubusercontent.com/40719297/53976194-d45d3c00-4106-11e9-808e-04a0fba64147.gif)

**Comment by AGI-THB** [comment]
Your Version is old.
The latest build is 3b2990

Try a recent build and see if the problem is still there.

**Comment by MichaelObvious** [comment]
In the newest build (3b2990b) the bug is still there.

**Comment by MichaelObvious** [comment]
In the latest build (3b2990b) the bug is still there.

**Comment by MichaelObvious** [comment]
This is the output when i run the program from the terminal.
```
2019-03-07T21:10:54 [WARNING] libpng warning: iCCP: known incorrect sRGB profile
2019-03-07T21:10:54 [INFO] Initializing custom cursors
2019-03-07T21:10:54 [INFO] Finished initializing custom cursors
2019-03-07T21:10:55 [INFO] Initializing effects...
2019-03-07T21:10:55 [INFO] Finished initializing effects
2019-03-07T21:10:56 [WARNING] libpng warning: iCCP: known incorrect sRGB profile
Segmentation fault (core dumped)

```

**Comment by itsmattkc** [comment]
Are you using the Nouveau graphics driver by any chance?

**Comment by MichaelObvious** [comment]
no, i only have the nvidia drivers.

**Comment by itsmattkc** [comment]
So you specifically installed the proprietary NVIDIA drivers? Can you provide a GDB backtrace for the crash?

**Comment by MichaelObvious** [comment]
this is what I get with gdb:
```
Starting program: /usr/bin/olive-editor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe1a0c700 (LWP 31481)]
[New Thread 0x7fffdbdfc700 (LWP 31482)]
[New Thread 0x7fffdb5fb700 (LWP 31483)]
[New Thread 0x7fffdad38700 (LWP 31484)]
[New Thread 0x7fffd8b87700 (LWP 31486)]
_IceTransSocketUNIXConnect: Cannot connect to non-local host obvious-HP-Compaq-Elite-8300-CMT
_IceTransSocketUNIXConnect: Cannot connect to non-local host obvious-HP-Compaq-Elite-8300-CMT
2019-03-09T12:56:27 [WARNING] Qt: Session management error: Could not open network socket
2019-03-09T12:56:27 [WARNING] libpng warning: iCCP: known incorrect sRGB profile
2019-03-09T12:56:27 [INFO] Initializing custom cursors
2019-03-09T12:56:27 [INFO] Finished initializing custom cursors
[New Thread 0x7fffc3fff700 (LWP 31487)]
[New Thread 0x7fffc37fe700 (LWP 31488)]
[New Thread 0x7fffc2fab700 (LWP 31489)]
2019-03-09T12:56:27 [INFO] Initializing effects...
2019-03-09T12:56:28 [INFO] Finished initializing effects
[Thread 0x7fffc2fab700 (LWP 31489) exited]
[New Thread 0x7fffc2fab700 (LWP 31490)]
[New Thread 0x7fffc1eca700 (LWP 31491)]
[New Thread 0x7fffc16c9700 (LWP 31492)]
2019-03-09T12:56:31 [WARNING] libpng warning: iCCP: known incorrect sRGB profile

Thread 1 "olive-editor" received signal SIGSEGV, Segmentation fault.
0x00007fffd98ca6ec in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so

```

**Comment by itsmattkc** [comment]
It seems your debug log indicates your computer _is_ using the Nouveau driver (at least, Nouveau is what's causing the segfault). How did you install the NVIDIA proprietary driver?

**Comment by alcomposer** [comment]
@MichaelObvious run `inxi -G` to get a detailed report of your graphics drivers and hardware.

**Comment by MichaelObvious** [comment]
I am Sorry, my computer is actually using the Nouveau driver

**Comment by itsmattkc** [comment]
All due respect to Nouveau, but there are a lot of things that don't play nicely with it, Olive included. Perhaps this will improve with better GLES support (#247), but for now I recommend you use the proprietary NVIDIA drivers when using Olive.
