### ISSUE TITLE
AppImage builds not uploaded to GitHub?

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#613]
Nightly builds not shown in latest nightly build

- https://github.com/olive-editor/olive/releases/tag/continuous

But as I can see in logs builds uploaded

- `Olive-27cb7c8-x86_64.AppImage` - https://api.travis-ci.org/v3/job/503511075/log.txt

**Comment by itsmattkc** [comment]
This has been brought up a few times. Should be solved soon.

**Comment by itsmattkc** [comment]
Mac and Linux builds shouldn't collide anymore.
