### ISSUE TITLE
Windows Update

### ISSUE THREAD

**Issue by GlennWilk** [olive-editor/olive#614]
I really love Olive Editing Software and have used Premiere for years.  I am teaching High School students film studies and we don't have a budget for expensive software.  I looked through the issues and was just wondering if there would be a windows build update in the next little while?  I realize the software is only in Alpha stage, and that app image updates come out regularly, but I am unsure of how to test these out - sorry if that sounds unintelligent or confused.  I know it has been requested but ability to add LUTS as effects would be fantastic.  Great piece of software!

**Comment by BrimsonBhin** [comment]
According to #482 , the Windows build is not updated due to Travis CI problems with Windows

I think there should be a statement on the readme regarding why the main Windows build is outdated

**Comment by itsmattkc** [comment]
As a matter of fact, I've just started putting something together for this. Expect something very soon.

**Comment by itsmattkc** [comment]
Windows builds are now part of the CI utilizing AppVeyor instead of Travis.

**Comment by Symbian9** [comment]
@itsmattkc, please, add also 32-bit builds for Windows.

**Comment by GlennWilk** [comment]
I truly thank you for this wonderful piece of software. The students I
teach really have very little and to have access to this software really
will make a huge difference.
