### ISSUE TITLE
Adding/removing other effects reset "Solid > Color" preview

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#618]
[The following template is primarily for bugs, you can remove it if you're requesting a feature.]

**Olive version:**  [Git hash from window title or Help > About]
**Source:** [AppImage, Website etc.]
**Operating system:** [Ubuntu 18.04 64-bit]
**CPU:** [Intel i5-4300U]
**RAM:** [8GB]
**GPU:** [NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx)]

### Detailed Description

Of video clip has effect "Solid > Color", adding or removing other effects reset preview of  "Solid > Color"

### Steps to reproduce

1. Add video clip with solid color effect (by default it is red color);
2. Change color to any other;
3. Add any other effect to this clip; as result, color preview reset to red;
4. Change solid color again;
5. Remove other effect.
6. As result — color preview reset to red again.

**Comment by BrimsonBhin** [comment]
Happening on `Windows 10` as well.

**Comment by itsmattkc** [comment]
Fixed with merge of `fxrestructure`.
