### ISSUE TITLE
Missing file name and some icon

### ISSUE THREAD

**Issue by saileshkush95** [olive-editor/olive#621]
As you can see in the screenshot, there is missing file name 
![DeepinScreenshot_select-area_20190311200852](https://user-images.githubusercontent.com/28560875/54131269-10abd780-443a-11e9-886a-e6b8014bb11c.png)

And also please add icon for adding in point and out point in media viewer

![DeepinScreenshot_select-area_20190311200940](https://user-images.githubusercontent.com/28560875/54131507-962f8780-443a-11e9-8e08-5f0cb5d54dae.png)

**Comment by AGI-THB** [comment]
Fill out the [Issue Template](https://github.com/olive-editor/olive/blob/master/ISSUE_TEMPLATE.md)

**Comment by NathanSalapat** [comment]
This happens to me every once in a while, I've found that changing the zoom level usually fixes the problem of the name not showing.

**Comment by itsmattkc** [comment]
54518a5896efc9c9c4477a0e6ae4724d6e9e20fc should fix this, see #676 for details
