### ISSUE TITLE
make failed - QMainWindow: No such file or directory

### ISSUE THREAD

**Issue by wiwi936** [olive-editor/olive#623]
Hi, 
Just cloned repository and followed compiling instructions.
Error seems too big to be true.
trying on Linux Mint 19 - Tara

~/apps/olive : make
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -DGITHASH=\"0f3d91b\" -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtMultimedia -I/usr/include/qt4 -I/usr/include/x86_64-linux-gnu -I/usr/X11R6/include -I. -o main.o main.cpp
In file included from main.cpp:21:
mainwindow.h:24:10: fatal error: QMainWindow: No such file or directory
 #include <QMainWindow>
          ^~~~~~~~~~~~~
compilation terminated.
Makefile:1346: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by itsmattkc** [comment]
For some reason your Makefile is set up to use Qt4 libs when Olive requires Qt5. Make sure the `qmake` you're running is the one from Qt5.

**Comment by wiwi936** [comment]
works well right now.
thanks
