### ISSUE TITLE
Show radio-buttons as "radio-button"

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#624]
### Actual behavior

Currently all "checkbox" and "radio-button" menu/option items shown in *Olive* as "checkbox".

### Expected behavior

Show "radio-button" as is:

- ⊙ active "radio-button"
- ◯ inactive "radio-button"

**Comment by itsmattkc** [comment]
Which checkboxes are you referring to?

**Comment by Symbian9** [comment]
For example, in "Tools" menu.

P.S.: Will try add screenshots later today

**Comment by Symbian9** [comment]
Here are right "radio-buttons" (as expected)

![pic.1](https://i.imgur.com/VOlJA1Y.png)

And here are radio-buttons shown as "checkbox" (wrong)

![pic.2](https://i.imgur.com/MWuqqjg.png)

![pic.3](https://i.imgur.com/ZDw9eSn.png)

**Comment by frink** [comment]
A simpler approach may be to remove checkbox backgrounds from the checkmarks on the menu. They aren't really expected to work like radio groups or checkboxes, but showing which are and aren't currently selected is a nice feature. If you don't have the background then they will be perceived as selections instead of radio buttons or checkboxes...

A lot of this really has to do with perception by the users...

**Comment by Symbian9** [comment]
> A simpler approach may be to remove checkbox backgrounds from the checkmarks on the menu.

NO!

Checkboxes in menu indicate what option enabled or desabled.

Radio-buttons in menu indicate which option variant is active (in the list of abailable option variants)

FTR, here is one more example where need show radio-buttons:

![pic.1](https://i.imgur.com/d3pDUoi.png)

**Comment by frink** [comment]
I've definitely never seen checkmarks and radios both used in one menu before. Usually there aren't even any indicators like this. I guess I'm sitting here scratching my head on what problem this really solves. I don't understand why the indicator shape MUST be different. But you seem extremely infatic about this...

To me the indicators are such common sense the way they are. I wouldn't want different symbols confusing me in the menu. Id rather not have the indicators than have both checks and radios. What's to stop a Qstyle from making things even more confusing with their funny marks? To me simple is better.

How come it is so imperative to show an check one place and a circle another?

I guess I don't understand.

**Comment by Symbian9** [comment]
> I've definitely never seen checkmarks and radios both used in one menu before.

For example, here is *OpenOrienteering Mapper*

- http://github.com/openorienteering/mapper

![pic.1](https://i.imgur.com/0fXzwZP.png)

**Comment by itsmattkc** [comment]
I definitely don't think anyone is truly confused by this, the only benefit is _slight_ UI polish.

But I do like UI polish and luckily for this issue, Qt makes this very quick to do so now it's done.
