### ISSUE TITLE
bash script to simplify source build of Olive

### ISSUE THREAD

**Issue by cyborgspiders** [olive-editor/olive#626]
### System Information

**Olive version:**  [Alpha ed05ced]
**Source:** [https://github.com/olive-editor/olive]
**Operating system:** [e.g. Ubuntu 18.04 64-bit]
**CPU:** [e.g. Intel i5-4300U]
**RAM:** [e.g. 8GB]
**GPU:** [e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx)]

### Detailed Description

I summarized the steps to perform a source build of the Olive video editor into a bash script on Ubuntu 18.04 64 bit by summarizing the well documented source build instructions from your webpage. Perhaps this will save one developer a moment. 

<a href="https://github.com/installerz/install.olive/blob/master/install.olive">install.olive</a>
[https://github.com/installerz/install.olive/blob/master/install.olive](url)

![Screenshot at 2019-03-13 00-03-44](https://user-images.githubusercontent.com/24215963/54259580-850e7580-4523-11e9-9230-5950385a9786.png)
Keep up the good work.

**Comment by itsmattkc** [comment]
Hey thanks, feel free to add this to the wiki (it's open to the public), that feels like the best place for it.
