### ISSUE TITLE
Olive Video Editor not recognizing image sequence in latest Build (both futherocio and master)

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#631]
**Olive version:(Furtherocio Branch) [afa89ff] Alpha**
**Source: Github**
**Operating system: Windows 10 Pro 64-Bit**
**CPU: Intel Core i7-5557U**
**RAM: 16 GB**
**GPU: Intel Iris Grpahics 6100**

### Detailed Description

This commit version isn't recognizing the image sequence imported into Olive, resulting in only one frame imported:

![image](https://user-images.githubusercontent.com/5027750/54363491-431b2780-4628-11e9-9ab5-cdb794d1fb2b.png)

### Steps to reproduce

Using (furtherocio) branch, try to import an image sequence

**Comment by Corruptinator** [comment]
Just tested it from the latest Master and learned that Olive still fails to load image sequence. So I decided to revert the commit back to the January 2019 | 87df07e Version and the image sequence import works. Did the source code somehow disable importing image sequence?

![image](https://user-images.githubusercontent.com/5027750/54395018-cca01900-466b-11e9-8404-58d46b395558.png)

**Comment by itsmattkc** [comment]
Looks like there was a bug in `furtherocio`'s preferences dialog that cleared the value in Preferences > General > Image Sequence Formats. You'll need to re-add the default value:
```
jpg|jpeg|bmp|tiff|tif|psd|png|tga|jp2|gif
```
0b7906f0998483baaaad7cf1a0db678d2861dcb9 should prevent this from occurring in the future.

**Comment by Corruptinator** [comment]
Thanks!
