### ISSUE TITLE
[Feature Request] Add CMake Support

### ISSUE THREAD

**Issue by DeveloperPaul123** [olive-editor/olive#632]
Given that this project is cross platform, I'd like to propose that CMake support be added to this project. I appreciate that `cmake` and `qmake` are similar in form/function but on Windows, it's very convenient to use cmake with Visual Studio and IMO Visual Studio is nicer to use for C++ development than Qt Creator. 

I just wanted to post this here to open up a discussion on adding this feature. If this is something that is desired by the developers/community I can do it and then file a PR.

**Comment by eszlari** [comment]
I just opened a PR: https://github.com/olive-editor/olive/pull/630

**Comment by itsmattkc** [comment]
Indeed, there's a PR for this already. I think further discussion should go there.
