### ISSUE TITLE
Does Olive perform compositing on the GPU?

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#633]
I am sorry to be asking a question in the form of an issue, but I couldn't find a better way to do it.

I've been making YouTube videos  for many years, first with Blender VSE and now with Kdenlive.

One problem with both of these is that saturating my CPU for rendering is very hard, and GPU is not used at all.

I have a Ryzen 7 1700 CPU with 8 cores / 16 threads and a GTX 1060 with 6 GB or VRAM and unless I hack together a parallell-rendering script I can't saturate any of that when rendering from Kdenlive or Blender.

The irony is that OBS does all compositing on the GPU and hence - can do it in real-time with multiple FullHD-resolution sources at 60 FPS - so the tech and it's sources are there, while all open-source video editors I know do all compositing in a single thread on the CPU, like it's 1999 (Kdenlive supposedly render in parallell, unless you use any frei0r video effects - which I nearly always do).

Because of that, a 45-minute video with a Luma key, an alpha blur effect, and some transformations to compositing a face into a screen capture, and then add a PNG-sequence of an animation in the corner would render for 12 hours straight on the aforementioned hardware, which is bizarre. And you better pray it won't crash at 90%, because I had that happenjng too.

I've yet changed my format to videos under 15 minutes, but still - not utilising the GPU power and multiple CPU cores is a notorious thing in libre NLAs. I can't get anything more than a single FullHD source to play in real-time from Kdenlive. Any compositing drops the FPS by a factor of three, while my CPU and GPU are both  90% idle.

So if Olive is doing it's thing better - that'd be a first libre NLA to break the ice AFAIK.

Is it?

**Comment by alcomposer** [comment]
Currently Olive uses GLSL shaders to blend video layers together, and there are lots of GLSL effects (with the cool ability to add your own effects if you know GLSL).

Even though Olive is in very much Alpha state, I think if you are editing together OBS footage & Talking Head, it should be enough currently to achieve what you want.

Olive should easily be able to render your videos in less than 12 hours.  Why not try with your workflow, and see how it goes?

**Comment by unfa** [comment]
I will definitely try it, as it could save me a lot of time. Moving from Blender VSE to Kdenlive was already a great improvement, but MLT is not using GPU at all, and I don't see it fixing that.

+1 for autosave and automatic crash recovery - this software makes me really thing you know what you're doing. I've seen so many barely passable NLAs... I have nearly lost all faith, but this... this is a new hope!

Also - I love that the timeline has full width of the screen by default - I can't change this in Kdenlive and it's frustrating me a bit. I am really looking forward to LV2 audio effect support - I am a music producer, and I ma currently adding audio effects to my videos in Ardour - Olive could really simplify my workflow, if I can apply the same audio effects without leaving it.

I am absolutely blown away by your work - after 30 minutes of testing I've decided to support you on Patreon, even though I haven't done that before.

**Comment by alcomposer** [comment]
All credit to @itsmattkc, this is his project.

**Comment by BrimsonBhin** [comment]
Yes, Olive's compositing depends on OpenGL. I believe the Frei0r and audio effects are the only CPU-based effects. The encoding right now is CPU-based.

Mentioned above, the rest of the effects [rely on GLSL](https://github.com/olive-editor/olive/tree/master/effects). Effects like `bloom` have not been written in GLSL and integrated into Olive yet. I believe such an effect would not require much lines of code.

What I like about Olive right now is that external effects are _modular_. You do not need compiler knowledge if you want to add a new effect or modify existing ones. If you want to add a new effect, just do the following..
- Properly code a .frag shader file. [`colorsel`](https://github.com/olive-editor/olive/blob/master/effects/colorsel.frag) for example
- Make an .xml configuration for said effect
- Drag the files into the Olive's `effect` folder in the app directory

**Comment by unfa** [comment]
I have just finished my first video in Olive.
I had a blast. And now it's rendering on all 16 threads on my CPU!
I had some minor issues, but for software that's in alpha stage - this is unbelievably good.

**Comment by itsmattkc** [comment]
As people have said, Olive's compositing/rendering pipeline is 100% OpenGL. Ideally we'll have decoding and encoding on the GPU too (#26) but this is tougher since it relies heavily on different GPU vendors, drivers, platforms, and codecs. One day though...

Thanks for the kind words and patron support too! Feel free to open other issues for any that you have :)

**Comment by foxisok** [comment]
Help please,
Windows 7 pro 64 bit sp1
Olive (March 2019 | Alpha | 6264123b)
Why I get the sequence Viewer black ?

![bbb](https://user-images.githubusercontent.com/49990098/56749573-ad2bfe00-678a-11e9-8d24-dd8950996ad8.png)

**Comment by itsmattkc** [comment]
@foxisok Are your graphics driver's installed and up to date?

**Comment by foxisok** [comment]
@itsmattkc Thank you very much. I installed new graphics driver's, and now it's okay.
