### ISSUE TITLE
Environment variables 

### ISSUE THREAD

**Issue by muziker** [olive-editor/olive#636]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:**  [e.g. Git hash from window title or Help > About]
Olive march 2019, alpha, 76b3cf5
from continuous
git commit hash 76b3cf589bc8eda79384342b3267a54d54c46c7d
**Source:** [e.g. AppImage, Website etc.]
github,com
### Detailed Description
The environment variables do not seem to be working
OLIVE_EFFECTS_PATH & FREI0R_PATH 
Even when specified, the paths don't affect whether the application loads the plugins, there is nothing in the effects control window. 

### Steps to reproduce
export OLIVE_EFFECTS_PATH=`pwd`/effects ; export FREI0R_PATH=/usr/lib/frei0r-1 ; ./olive-editor

There are no crashes, just the qgetenv doesn't propogate the path changes

**Comment by itsmattkc** [comment]
I've been able to confirm them working. What do you mean by "there is nothing in the effects control window"?

**Comment by muziker** [comment]
I do this : 
OLIVE_EFFECTS_PATH=`pwd`/effects/ FREI0R_PATH=/usr/lib/frei0r-1 ./olive-editor --no-debug
And olive starts, but in the effects panel, there is nothing to be seen there

**Comment by itsmattkc** [comment]
@muziker There won't be anything in the Effects panel unless you have a Clip selected. Is that what you mean?

**Comment by muziker** [comment]
Yes i did that. I imported 2 clips into the project. Pulled them into the timeline editor. And clicked on the effects editor tab to inspect. There was no effects in the pane.

**Comment by muziker** [comment]
Ok i see what you mean. I highlighted a clip in the timeline editor and the effects panel turned on.

**Comment by muziker** [comment]
It would be an improvement, if effects could be placed on the timeline, where it will affect all clips within that region,  rather than be attached to clips.

**Comment by itsmattkc** [comment]
It's coming, see #13
