### ISSUE TITLE
Playing reverse makes image jitter

### ISSUE THREAD

**Issue by tin2tin** [olive-editor/olive#641]
Playing this clip uploaded to Wetransfer in reverse(hotkey: j) makes the image jitter/jump between frames: https://we.tl/t-WygjPBv0C8

Olive version: March Build
Operating system: Windows 8

**Comment by itsmattkc** [comment]
You'll probably have to be more specific about what you mean by jitter. Do you mean it doesn't play perfectly smoothly?

**Comment by tin2tin** [comment]
It looks like it is "shuffling" frames. Like it is randomly showing the start frame in-between the reverse-playing frames.

**Comment by itsmattkc** [comment]
Can you make a video of this happening?

**Comment by tin2tin** [comment]
Now this clip crashes Olive when just playing it, so I can't even make a video of it.
Here's a link again: https://we.tl/t-WygjPBv0C8  It's ca. 21 MB.

**Comment by BrimsonBhin** [comment]
Happening on the `54c03ef` build. How to replicate

1. Place input in the timeline (mpeg2 or h264, does not matter)
2. Playback the video
3. Press `j`
4. You should see the reverse playback of the video having that "jittering" issue
