### ISSUE TITLE
Full screen show damaged image for a few sec

### ISSUE THREAD

**Issue by tin2tin** [olive-editor/olive#642]
Making player full screen makes image look like this for a few sec. 
![image](https://user-images.githubusercontent.com/1322593/54611797-ed93b000-4a57-11e9-88af-afe90e56bb6a.png)

Using this as footage:
https://we.tl/t-WygjPBv0C8

Olive version: March Build
Operating system: Windows 8

**Comment by itsmattkc** [comment]
Known issue, fixed in the `furtherocio` branch.

**Comment by tin2tin** [comment]
Oh, cool. Thank you.
