### ISSUE TITLE
[FR] Improve Audio FX: "Fill Left/Right"

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#645]
The Fill Left/Right effect is a very simplified audio channel switcher operating in two modes:

**LR --> LL**

or 

**LR -> RR**

I guess  renaming it to "**Channel Switcher**" would be a good thing, as (as an audio guy) I deem that to be a more technically correct name.

There could be also other useful operation possible like:

**LR -> MS
MS -> LR**

With this - the Balance effect could be used to make the stereo separation wider or narrower.

However then the effect could be better named "Stereo Tool".

The inspiration comes fro ma popular open-source plug-in called "Calf Stereo Tools":
https://calf-studio-gear.org/doc/Stereo%20Tools.html

**Comment by itsmattkc** [comment]
I'm folding this into #575, I think the long-term solution is an actual channel route setting (not an effect) so that you can "connect" say LL -> LR or LR -> RL or as you say LR -> MS.

**Comment by artmarvin** [comment]
It would be awesome to have also a sidechain compression fx to auto-duck the audio in background
