### ISSUE TITLE
[furtherocio] Crash when changing FPS on Sequence View with pre-recorded footage already in

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#647]
**Olive version: Git [47532a4]**
**Source: Git source download [furtherocio] branch**
**Operating system: Windows 10 Pro 64-bit**

Testing out the new overwriting color management options in the latest _furtherocio_ branch, I was attempting to change the FPS of the Sequence Clip in the properties window to fit the FPS of the imported footage to match it up, but upon doing that the software freezes for a second then it crashes, I have no means of recording crash messages but it was running using MSYS MINGW and it generated this message upon crash:

`2019-03-19T22:46:33 [FATAL] ASSERT: "d->size == asize" in file ../../include/QtCore/../../src/corelib/tools/qvector.h, line 654`

I have no idea what it means but assuming "FATAL" is in there, maybe there was a fault in the code? Once again, it crashed after attempting to change the FPS in the properties window.

### Steps to reproduce

1. import any footage
2. place them into a sequence timeline.
3. right click the sequence and click properties.
4. try to change the FPS, hit ok.

Thats where it crashes.

**Comment by itsmattkc** [comment]
I'm not able to recreate this. If you're using MSYS, you can install GDB and produce a GDB backtrace as described in https://github.com/olive-editor/olive/wiki/How-to-get-output-logs-if-the-program-crashes-and-use-GDB-LLDB-for-more-detailed-logs (use `pacman -S mingw-w64-x86_64-gdb`)

**Comment by Corruptinator** [comment]
I'll give that a try.

**Comment by Corruptinator** [comment]
Weird, its not crashing anymore. Closing...
