### ISSUE TITLE
Crash when opening clip in source player 

### ISSUE THREAD

**Issue by tin2tin** [olive-editor/olive#648]
Olive version: The latest beta
Operating system: Win 8

In a freshly opened Olive, import a clip, double click it to open it in the source player, press play in the source player, makes Olive crash. 

NB. this doesn't happen if you ex. first drag the clip into the timeline or in the program player.

Watch the gif to see what I did:
![Olive_file_crash](https://user-images.githubusercontent.com/1322593/54673347-5e8ba400-4afa-11e9-92c8-22463555a3ad.gif)

**Comment by itsmattkc** [comment]
Does this still occur on the latest build? If so, I might need to send you a debug build for a more verbose debug log

**Comment by tin2tin** [comment]
In the latest build 'play' works, but not when doing the same procedure, but instead of hitting play, when I hit "j" for reverse playing in the source monitor is now crashing Olive. 

Is the log saved somewhere, because the log window doesn't write anything before the crash?

**Comment by itsmattkc** [comment]
I likely won't be able to diagnose this without a GDB backtrace.

**Comment by itsmattkc** [comment]
I'll close this for now, later on once the codepaths are merged you can see if this issue still affects you.
