### ISSUE TITLE
Feautres

### ISSUE THREAD

**Issue by GlennWilk** [olive-editor/olive#649]
Hello... Is there anyway of bringing some of the effects that were present in earlier versions - they were under Frei0r.  I teach media students and some of the surreal effects that were here helped shaped the look of their short films.
Thanks

**Comment by itsmattkc** [comment]
@GlennWilk Which platform are you on? Frei0r support still exists in the master branch.

**Comment by GlennWilk** [comment]
I am using the portable version of Windows.
Thanks

**Comment by Symbian9** [comment]
@GlennWilk , please, change title of this issue to "Frei0r effect not exists in effects list"

**Comment by itsmattkc** [comment]
@GlennWilk If you extract the following ZIP and copy the files into Olive's "effects" folder, the Frei0r effects should return:

https://drive.google.com/open?id=1bsCz_b498MDa9ZPAXP7qER1sfl0wPjtG

**Comment by GlennWilk** [comment]
Thanks so much for the quick response.

Glenn

**Comment by GlennWilk** [comment]
Hi... Tried what you suggested and still no Frei0r?
Thanks

**Comment by itsmattkc** [comment]
@GlennWilk Try the latest build from here: https://ci.appveyor.com/project/itsmattkc/olive/build/artifacts (GitHub release page will have it next commit)

**Comment by Symbian9** [comment]
@itsmattkc I just found that Frei0r effects also not shown in latest AppImage's too

**Comment by AGI-THB** [comment]
Latest Build is 773882222b42ccc4ee38a4db69ce838d2322d693

Frei0r Effects are there for me.
Must be a Problem with your system. 
I use Linux Mint.

**Comment by itsmattkc** [comment]
@Symbian9 The AppImages never had Frei0r effects included, but will pick up on them if they're installed on your system.

**Comment by Symbian9** [comment]
> The AppImages never had Frei0r effects included

But I remember, that few days ago I sew "Frei0r" in effects list in nightly AppImage build.
