### ISSUE TITLE
Add "Insert as..." dialog for sequences and media with video and audio content

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#650]
Add dialog ***"Insert as..."*** (window title) for ask user how insert dragged media or other sequence (if inserted media or sequence has both video and audio content) into current sequence timeline with next buttons:

- Video + Audio clips;
- Only Video clip;
- Only Audio clip;
- Cancel (cancel inserting).

**Comment by itsmattkc** [comment]
I think a dialog on every insert would get annoying. Besides, Olive already has a means of inserting only video or only audio from a source:

![image](https://user-images.githubusercontent.com/34096995/54683954-1ce51280-4b67-11e9-84cd-23f20fb7106c.png)

**Comment by Symbian9** [comment]
> I think a dialog on every insert would get annoying.

Then there should be an option ***"Always ask how insert clips"*** in *"Preferences > Behaviour"*

> Olive already has a means of inserting only video or only audio from a source:

This not work for sequence inserting in other seqeunce

**Comment by itsmattkc** [comment]
I've added these drag buttons that I think will accomplish what you're requesting and be less intrusive than a dialog. They will work for Sequences too.

![image](https://user-images.githubusercontent.com/34096995/54827760-d8907880-4d06-11e9-86c8-139030d7624d.png)
