### ISSUE TITLE
Add "Auto-Scroll Speed"

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#652]
Currently "Auto-Scroll" in "Rich Text" effect depend on its clip length only.

**Comment by oc1024** [comment]
I find this reasonable. Setting the start and endpoints should be enough to know the speed.

**Comment by itsmattkc** [comment]
I'm inclined to recommend you just use the Title on a separate clip (easier now that "Rich Text" is the default Title effect). You get more powerful editing that way too having the start/end points settable on the timeline.

**Comment by Symbian9** [comment]
> I'm inclined to recommend you just use the Title on a separate clip

@itsmattkc I already use it, but there NO any numeric representation of "Auto-Scroll" speed (pixels per second, etc.)

So, if I want create two separate different titles that should has same "Auto-Scroll" speed **how should I tune their speed to same numeric value?**
