### ISSUE TITLE
Choppy animation in export

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#653]
Currently I see some glitches on exported videos in places where *Olive* need more memory/CPU usage (when there are few effects rendered in same time, etc.)

Is it possible optionaly decrease export speed?

Let it use more time for processing, but quality of rendering output would be better.

**Comment by DaniSeeh** [comment]
By glitches, do you mean like, higher compression or visual errors?

**Comment by Symbian9** [comment]
> do you mean

I mean speed of moving object not stable, and sometime this object twitch.

**Comment by itsmattkc** [comment]
The premise of this question is faulty - Olive doesn't sacrifice output quality for export speed. If something is exporting incorrectly, it's a **bug**, not a result of Olive not spending enough time on it.

That being said, can you explain in more detail what's not exporting correctly?

**Comment by alcomposer** [comment]
@Symbian9 can you post a screenshot of the problem?

**Comment by Symbian9** [comment]
> can you post a screenshot of the problem?

It not visible on static image. I will upload exported video later today.

**Comment by Symbian9** [comment]
Here is ZIP with project file & exported MP4 video

- https://transfer.sh/get/husiQ/test-rich-text.zip

Take a look on how Rich Text 'twitch' when moving on this video

**Comment by itsmattkc** [comment]
Is this still present in the latest commit?

**Comment by Symbian9** [comment]
> Is this still present in the latest commit?

I will take a look tomorrow

**Comment by Symbian9** [comment]
> Is this still present in the latest commit?

Here is export output from *Olive*

- https://transfer.sh/get/15DIxT/test-rich-text-2.zip

Moving little better, but what happen with export quality? It is much worst than it was previously.

Here is export profile (I use same for previous export)

![pic.1](https://i.imgur.com/Q3bIHyu.png)

For example, I use in this project as background "Solid Color" + "Vignete" effect

Here is what I see in *Olive* (full screen "Sequence Viewer")

![pic.2](https://i.imgur.com/vGJBH7E.png)

Here is what I seen previously in export output ( https://transfer.sh/get/husiQ/test-rich-text.zip )

![pic.3](https://i.imgur.com/x7zoFcX.png)

And here is what I see in current export output

![pic.4](https://i.imgur.com/mTMqYq4.png)

As You can see, last export has many artifacts, especially on "Vignete" edges

FTR, here is exported frame from "Sequence Viewer" — it has NO such artifacts, but in same time it has transparency that replace "Solid Color" (look like a bug)

![pic.5](https://i.imgur.com/ZLlUnHD.png)

**Comment by itsmattkc** [comment]
Use a higher quality (CRF) value. There was a bug earlier that passed frames incorrectly to the encoder causing encoding to be inefficient. I may raise the default quality to compensate for this.

**Comment by Symbian9** [comment]
> Use a higher quality (CRF) value

When I use higher value, for example `42` (default is `36`), then I got video with too heavy visual compression artifacts.

When I set *CRF* = `0` (no compression), then video quality is very well, BUT ***scrolling text still "twitch" on exported video*** (tested using *Olive* https://github.com/olive-editor/olive/commit/675ea942f1cb18261637e30f17eeca814a6501d3 )

- https://0x0.st/zKwt.zip

**Comment by itsmattkc** [comment]
Is the stuttering limited to the rich text's autoscroll? e.g. does the issue still occur if you keyframe an object to move at a similar speed?

**Comment by Symbian9** [comment]
> does the issue still occur if you keyframe an object to move at a similar speed?

How? I don't understud.

Can you show it on screenshot or edit `test-rich-text.ove` and upload modified OVE-file?

**Comment by AGI-THB** [comment]
Use keyframes to move an Object across the screen and tell us if they twitch too.

Transform -> Position
Set a keyframe
then move the red line to another point on the timeline
set another keyframe 
render (export) the scene
see if text / object is making laggy movements too

**Comment by Symbian9** [comment]
> Transform

@itsmattkc I just tried use "Transform" keyframes instead of "Auto-Scroll"

1. "Transform" cut long test to frame size, so it could not be used as replacement for "Auto-Scroll";
2. When export as MP4+AAC, then output has less "twitch" lags than if export to MP4+MP2;
3. In same time if used "Auto-Scroll", then both exported (MP4+AAC and MP4+MP2) has near similar visulally recognizible "twitch" lags of scrolled text.

Here is ZIP with project file and two export results with "Transform" keyframes:

- https://transfer.sh/get/UV7wi/test-rich-text-4.zip

**Comment by itsmattkc** [comment]
>"Transform" cut long text to frame size, so it could not be used as replacement for "Auto-Scroll";

I know - I wasn't suggesting you use it instead, I was asking if the issues are restricted to the auto-scroll feature or if they occur in other places too.

What does the export look like if you export video only (untick audio in Export)?

**Comment by Symbian9** [comment]
> What does the export look like if you export video only (untick audio in Export)?

Auto-scroll text still "twitch"  on exported video if untick audio

**Comment by cgvirus** [comment]
@AGI-THB ` Use keyframes to move an Object across the screen and tell us if they twitch too.`
Yes transform has this frame dropping as well. tested with a footage+transform effect
