### ISSUE TITLE
Keep wraped panels in "Effects" window

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#654]
All effects panels unwraped if add or delete any other effects, move or resize clip.

**Comment by itsmattkc** [comment]
Can you explain what you mean by "wrapped panels"?

**Comment by AGI-THB** [comment]
He means you can fold effect tabs (or how you wanna call it) of effects you dont need or of which you dont want to see the effect properties.

if you add additional effects ( or delete effects) all hidden properties will unfold, taking up space again

**Comment by AGI-THB** [comment]
Another word for this could be "collapse".
You have a table, but you dont want to see the entries of this table, just the headline.
I hope you understand what is meant.
