### ISSUE TITLE
Create separate repo for Olive themes

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#658]
Please, create separate repo for CSS themes:

- https://github.com/olive-editor/olive-themes

- Add `olive-dark.css`, `olive-light.css`, `native.css` and `native-light.css` into this repo (based on bundled themes);
- Collect custom CSS themes for Olive created by other users;

**Comment by BrimsonBhin** [comment]
Those four themes in current are embedded in Qt itself. They are not separate `.css` presets.

But a separate repository seems like a good idea for community-made themes and effects.

**Comment by itsmattkc** [comment]
Indeed those styles in Olive are not CSS, they're just QStyles with palettes. Perhaps once people start producing custom CSS themes for Olive, a repo can be set up.

**Comment by Symbian9** [comment]
> Perhaps once people start producing custom CSS themes for Olive, a repo can be set up.

But there NO any CSS templates for *Olive* themes, so creating such repo with bundled themes in CSS format would be starting point for theme makers

**Comment by BrimsonBhin** [comment]
@Symbian9 

Oh, I see what you mean. Like a template for making a theme for Olive?

**Comment by Symbian9** [comment]
> Like a template for making a theme for Olive? Basically the default themes, but in .css/.qss format for users to customize?

YES.

**Comment by itsmattkc** [comment]
Olive doesn't really do anything special as far as CSS goes, any Qt/QSS template you find on the internet should work.

**Comment by Symbian9** [comment]
> any Qt/QSS template you find on the internet should work.

But where get `olive-dark.css`, `olive-light.css`, `native.css` and `native-light.css`?

**Comment by itsmattkc** [comment]
They don't exist. Those are just Qt's built-in styles with some palette tweaking - they don't use the CSS paradigm at all (especially in the case of the native styles).

**Comment by Symbian9** [comment]
> They don't exist.

Then need create such CSS and place them in separate repo. That is main idea of current issue/feature request.

**Comment by itsmattkc** [comment]
They don't exist because that's not how they work. The choice between "Native" (your system's style) and "Fusion" (Qt's cross platform style and Olive's default), and the choice between light icons or dark icons are all programmatic and can't be achieved in CSS. The only thing Olive does from there is slight palette tweaking (when there's no CSS set up), which _could_ be CSS, but isn't.

Think of them more as the base (i.e. Olive Dark for a dark style and Olive Light for a light style), and as I said, start with any generic Qt stylesheet and work from there.

**Comment by Symbian9** [comment]
> the choice between light icons or dark icons are all programmatic and can't be achieved in CSS

As we has all icons in SVG format, then it is possible ;-)

- https://stackoverflow.com/questions/15123544/change-the-color-of-an-svg-in-qt
- https://github.com/filamentgroup/grunticon/issues/235

**Comment by itsmattkc** [comment]
Just because you can edit the CSS on the SVG file programmatically does not mean that functionality is exposed through loading a Qt stylesheet - you'll notice the example provided primarily uses C++ code to manipulate the CSS.
