### ISSUE TITLE
[Bug] Cannot drag media files from desktop to project window 

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#660]
### System Information

**Olive version:**  `1da4a31`
**Source:** Github Continuous
**Operating system:** [Windows 10 64-bit]

### Detailed Description

Dragging media files to the project window does not add to the project's input collection. However, it is still possible to directly drag media from the desktop into the timeline window (which can still adds to the project collection). Using `import media..` still works as it should.

### Steps to reproduce

1. Enable project window
2. Try to drag media directly from the desktop into the project window
3. Olive does not consume dragged media files

**Comment by alcomposer** [comment]
I can confirm this issue: Antergos Linux, Gnome 3.32
