### ISSUE TITLE
Crash adding effects frei0r

### ISSUE THREAD

**Issue by GlennWilk** [olive-editor/olive#662]
### System Information

**Olive version:**  1da4a31
**Source:** [Windows Portable]
**Operating system:** [Windows 10 64-bit]
**CPU:** [e.g. Intel i5-4300U]
**RAM:** [e.g. 8GB]
**GPU:** [e.g. NVIDIA Geforce GT 705

### Detailed Description

When I take my source clips and convert to proxy 1/8 resolution, works fine.  Can edit in timeline add crossdisolves etc.  When I add effects, especially anything from frei0r it crashes.  Have tested with other effects and works fine.

### Output Log
[INFO] Clip opened on track -1 (took 5 ms) (:0, )
[INFO] Clip opened on track 0 (took 4 ms) (:0, )
[WARNING] QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) (:0, )
[INFO] Matched "20180129_152312.mp4" relative to project's current directory (:0, )
[INFO] Matched "20180129_152302.mp4" relative to project's current directory (:0, )
[INFO] Matched "20180129_152251.mp4" relative to project's current directory (:0, )
[INFO] Matched "20180129_152235.mp4" relative to project's current directory (:0, )
[INFO] Matched "20180129_152217.mp4" relative to project's current directory (:0, )
[INFO] Matched "20180129_152206.mp4" relative to project's current directory (:0, )
[INFO] Matched "20180129_152149.mp4" relative to project's current directory (:0, )
[INFO] Matched "20180129_152128.mp4" relative to project's current directory (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Finished initializing effects (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing custom cursors (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )

Thanks Glenn

**Comment by itsmattkc** [comment]
Is this fixed in ff6848d1b619f3c805ef9c038e51e79010a06f35?

**Comment by itsmattkc** [comment]
I'll assume this is corrected based on my own testing with this issue, let me know if you have any more issues
