### ISSUE TITLE
Frei0r effects has no any effect under Linux

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#663]
### System Information

**Olive version:** https://github.com/olive-editor/olive/commit/1da4a315f80e715c5756d5f66f956851e93b9b2c
**Source:** AppImage (x86_64)
**Operating system:** Debian 9.x (x86_64)

### Detailed Description

After install `frei0r-plugins` package I see *Frei0r* effects in *Olive* and could add them, BUT there no any effect — nothing changed on "Sequence Viewer"

- http://www.deb-multimedia.org/pool/main/f/frei0r-plugins-dmo/frei0r-plugins_1.5-dmo2_amd64.deb 

### Output Log

No any log messages

**Comment by itsmattkc** [comment]
No effect on what kind of clips? Frei0r effects won't affect Titles/Bars/Solids.

**Comment by eszlari** [comment]
Work here with the flatpak.

**Comment by Symbian9** [comment]
> Frei0r effects won't affect Titles/Bars/Solids.

Oh, I see this limitation now.

BTW, *Feei0r* works for video clips & pictures.
