### ISSUE TITLE
[FR] Enable 24-bit FLAC and 32-bit float PCM audio encoding

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#672]
As Olive has a very minimal set of audio mixing features, I'm leaving a lot of headroom while editing audio to be able to later determine the final loudness level without clipping.

For that I export in FLAC - though there's only 16-bit FLAC encoding available.

If I could export in 24-bit FLAC and/or 32-bit float PCM I could maintain a higher fidelity of my audio without having to risk clipping.

**Comment by RafaelLinux** [comment]
I'll add to this question .... will be added OPUS codec support?

**Comment by unfa** [comment]
Fun fact: I upload all my videos with audio in FLAC to make sure the quality is as good as possible after YouTube encodes it.

**Comment by RafaelLinux** [comment]
Personally, I prefer to upload in WebM, with vp9 codec for video and opus for audio, both are native in WebM and no need conversions, so it's my choice. Moreover, OPUS is excellent for all audio files, you can check it yourself  ;)

**Comment by itsmattkc** [comment]
This is implemented in the new rewrite.
