### ISSUE TITLE
Transform effect: scaling down causes aliasing

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#673]
If you use the transform effect to scale down an image significantly (for example a text), aliasing will occur.

Example:

![image](https://user-images.githubusercontent.com/491704/54831699-241d3500-4cbb-11e9-876e-0ee540101a89.png)

Applying a Gaussian blur on the image before scaling down acts as an anti-aliasing filter and fixes the problem:

![image](https://user-images.githubusercontent.com/491704/54831882-79594680-4cbb-11e9-8828-feafc24ee63f.png)

However - for animated transforms, the user would need to meticulously apply a blur of a variable sigma to remove any aliasing.

Could such a blur effect be automatically added to Transform when scaling down to prevent the aliasing?

**Comment by itsmattkc** [comment]
Clips should already scale with bilinear filtering. Perhaps there's something missing with the Text effect's texture. I'll look into it tomorrow.

**Comment by unfa** [comment]
Hmm. I was able to still break in  current master:
![image](https://user-images.githubusercontent.com/491704/54886911-99d8fa80-4e8d-11e9-832c-bcd2de231d30.png)

Build marked ad44b00e, built about two hours ago.

**Comment by unfa** [comment]
I can also see this problem when using the Sphere effect:

![image](https://user-images.githubusercontent.com/491704/54887227-c5a9af80-4e90-11e9-9834-c0a9039db93d.png)

**Comment by itsmattkc** [comment]
ad44b00 is older than the commit the fix is in (78fb7d11bde287a47f2ae7c838ebefe7204c77bb), try that one and see if it's any better

**Comment by unfa** [comment]
Ah, ok! Sorry!

**Comment by unfa** [comment]
Alright - I know what's up.

The PKBUILD in AUR points to commit ad44b00.
I've changed that to the latest one and now I'm up to date.

The problem is indeed gone!
