### ISSUE TITLE
Nested sequence doesn't composite as expected

### ISSUE THREAD

**Issue by mdmayfield** [olive-editor/olive#675]
**Olive version:**  cc69f5b326b7192d09b7bf1e9728c7128790403d ~~90b089a80 from git master branch (not furtherocio). Doesn't look like there have been commits since then that would affect this~~

### Detailed Description
When nesting clips into their own sequence, composition/transparency changes

### Steps to reproduce

- Open attached [nested-compositing.zip](https://github.com/olive-editor/olive/files/2997752/nested-compositing.zip)
- Open "Nested Sequence 01" sequence
- Observe the text fades in and out while color background remains constant
- Open "Sequence 01" sequence
- Observe that both text and color background fade in and out

### Output Log

N/A

### GDB/CDB Backtrace (for crashes)

N/A

Not sure if this will all "come out in the wash" with the OCIO work but thought I would report it

**Comment by itsmattkc** [comment]
Confirmed, but this issue has already been corrected with the new OpenGL pipeline in `furtherocio`.
