### ISSUE TITLE
File does not show in Project bin

### ISSUE THREAD

**Issue by MisterTeeXD** [olive-editor/olive#676]
### System Information

**Olive version:**  [cc69f5b]
**Source:** [https://www.olivevideoeditor.org/]
**Operating system:** [Windows 10]
**CPU:** [Intel i5-6400]
**RAM:** [4GB]
**GPU:** [Intel Graphics 530]

### Detailed Description

When a video clip has been imported to the project bin, it does not show the file in the project bin, only an invisible file

### Steps to reproduce

Go to the file destination of the video of the clip, click and drag the clip into the project bin, there should be an invisible file

### Output Log

```
Non
```

### GDB/CDB Backtrace (for crashes)

```
Non
```
### Notes
Here is a gif i recorded of the error : 
![Cf9OeUPZPK](https://user-images.githubusercontent.com/37266538/54859828-82c5cb80-4d1a-11e9-8611-6beea00510a1.gif)

**Comment by itsmattkc** [comment]
I can't reproduce this. Is this an issue with icon view? (i.e. does the media appear correctly in tree view?)

**Comment by BrimsonBhin** [comment]
This issue usually happens when you first use Olive immediately after installing it (on Windows 10). The issue goes away once you start Olive again

**Comment by MisterTeeXD** [comment]
Actually, it still exists when Olive is opened

**Comment by itsmattkc** [comment]
Is this an issue with icon view? (i.e. does the media appear correctly in tree view?)

**Comment by MisterTeeXD** [comment]
Yes, i drag in a file and it does not show up, it gets a temp fix when the zoom is changed

**Comment by DaniSeeh** [comment]
So updating the viewer fixes it? Maybe it isn't updating when the file is dropped?

**Comment by itsmattkc** [comment]
Qt's default icon system has been causing trouble for pretty much the whole time it's been implemented. I've instead written a custom item delegate (54518a5896efc9c9c4477a0e6ae4724d6e9e20fc) which should solve them once and for all (and is much more useful, see #175).
