### ISSUE TITLE
[BUG] Sequences don't work and other bugs

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#677]
After compiling the newest version I encountered some new bugs that I wanted to mention here:

- languages doen't show up anymore

- the default sequence settings button does nothing

- sequences do not show up in the project and timeline dialog

- after adding a sequence newly imported files dont show up as well

It would be so nice if those amazing feature would work!
Thanks in advance for the resolution of the problems and keep up the great work!

**Comment by itsmattkc** [comment]
If you're compiling from source, you need to compile the language files manually using `lrelease olive.pro`.

> sequences do not show up in the project and timeline dialog
> after adding a sequence newly imported files dont show up as well

Can you elaborate on these?

**Comment by itsmattkc** [comment]
If your sequences not appearing was related to #676, try 54518a5896efc9c9c4477a0e6ae4724d6e9e20fc

**Comment by libalis** [comment]
After a recompile

- sequences do not show up in the project and timeline dialog

- after adding a sequence newly imported files dont show up as well

were fixed!

But the other 2 are still broken!

Thank you for 54518a5!

And it would be great if the other issues would be next!

**Comment by itsmattkc** [comment]
Did you use `lrelease olive.pro` to compile the translated files?

**Comment by libalis** [comment]
How does this work?
It's not described in the compiling How-To on you site!

**Comment by itsmattkc** [comment]
It works exactly how I said: run `lrelease olive.pro` in Olive source directory.

**Comment by libalis** [comment]
Error: command lrelease not found!

**Comment by itsmattkc** [comment]
Assuming you're on Ubuntu (or a derivative), you may need to install another package:
```
sudo apt-get install qttools5-dev-tools
```

**Comment by libalis** [comment]
Ok thank you so much!
I'm on arch and had to install qt5-tools!
Wouldn't it be smart to add that to the How-To?

**Comment by itsmattkc** [comment]
@libalis Yes, I will add it to the compile instructions soon.

What's wrong with FFmpeg 3.4+?

**Comment by eszlari** [comment]
The cmake build system (https://github.com/olive-editor/olive/pull/630) checks if `lrelease` is available and runs it automatically.

**Comment by libalis** [comment]
@eszlari So I don't have to do it manualy if I installed that package?
(Still would be nice to know that this package has to be installed)
And @itsmattkc I thought Olive switched to FFmpeg 4, didn't it?

**Comment by itsmattkc** [comment]
@eszlari Wouldn't exactly help in this situation since `lrelease` wasn't installed on @libalis 's system, but running it automatically is certainly an improvement.

@libalis Olive will still run and compile with as low as 3.4. The only thing that changed was the AppImage upgraded to 4 for better format support.

**Comment by eszlari** [comment]
> @eszlari Wouldn't exactly help in this situation since lrelease wasn't installed on @libalis 's system, but running it automatically is certainly an improvement.

Of course, but it wouldn't even start to compile and he would get a nice error message.

**Comment by libalis** [comment]
So could you please add "lsrelease olive.pro" to the make command. (would make it so much easier for me ;))
And add "qttools5-dev-tools" as dependenices in the How-To.

But the problem that the defualt sequence button does nothing is still relevant!

**Comment by itsmattkc** [comment]
Believe me, if I could have automated the `lrelease` through qmake I would have. Apparently the cmake PR will do it though so you can expect it there.

That button has literally never had a function. It was added when re-laying out the Preferences dialog but it was never given a purpose. Now it has (aff3acb94ed698a94b28d953aed653651a7f055d)

**Comment by libalis** [comment]
Sorry, Didn't know that!
Thank you for everything!
