### ISSUE TITLE
[Feature Request] Motion Tracking

### ISSUE THREAD

**Issue by MisterTeeXD** [olive-editor/olive#679]
It would be great if there was a effect that allows us to have a title motion tracked to, lets say, a moving hand.

**Comment by hamzamihoub** [comment]
yes, i agree 
and some sort of video stabilization would even greater.

**Comment by MisterTeeXD** [comment]
Yep

**Comment by AGI-THB** [comment]
#452

**Comment by itsmattkc** [comment]
Indeed, duplicate of #452
