### ISSUE TITLE
My two cents. 2 Tutorials for Olive Video Editor Beginners

### ISSUE THREAD

**Issue by CyberJabba** [olive-editor/olive#683]
Hi,
I discovered Olive Video Editor only a few days ago and I've already fallen in love with it. This is only a small contribution to this great software. Thanks to the authors for carrying out this wonderful project.

Tutorial 1: https://youtu.be/IEmAnLzrrqY
Tutorial 2: https://youtu.be/2ztNV7dZJTc

Thank Yoy!
CJ

**Comment by itsmattkc** [comment]
Thank you for the kind words! I've added your videos to a new Tutorials page on the GitHub wiki: https://github.com/olive-editor/olive/wiki/Video-Tutorials
