### ISSUE TITLE
Duplicating Menu

### ISSUE THREAD

**Issue by MisterTeeXD** [olive-editor/olive#685]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:**  [86b0787]
**Source:** [zip from github]
**Operating system:** [Windows 10 64Bit]
**CPU:** [Intel i5-6400]
**RAM:** [4GB]
**GPU:** [Intel Graphics HD 530 128MB (Latest drivers)]

### Detailed Description

[When the shortcut "T" is pressed continuously, it will duplicate the Transition menu]

### Steps to reproduce

[Keep pressing T and move the mouse around]

### Output Log

```
[Non right now]
```

### GDB/CDB Backtrace (for crashes)

```
[Non right now]
```

### Note
Here is the screenshot of the error:
![Screenshot (130)](https://user-images.githubusercontent.com/37266538/54883225-4bffca80-4e6c-11e9-8df1-4488e845a30a.png)

**Comment by AGI-THB** [comment]
Confirmed... but left-clicking (a few times) makes them go away.
Shouldn't be hard to fix for Matt.
I still try to figure out why someone should press T that often.
