### ISSUE TITLE
Non-Working Fade Options

### ISSUE THREAD

**Issue by MisterTeeXD** [olive-editor/olive#686]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:**  [86b0787]
**Source:** [zip from github]
**Operating system:** [Windows OS 64bit]
**CPU:** [Intel i5-6400]
**RAM:** [4GB]
**GPU:** [Intel Graphics HD 530 128MB (Latest drivers)]

### Detailed Description

[When trying to apply a Transition form the SideMenu on the timeline, it does not work]

### Steps to reproduce

[Select the parts of the clips, then click the Transition on the Timeline sidemenu and try to use any fade option]

### Output Log

```
[None]
```

### GDB/CDB Backtrace (for crashes)

```
[None]
```

### Notes
Here is a gif i recorded showing the problem:
![YXr0nRGyhI](https://user-images.githubusercontent.com/37266538/54883580-756e2580-4e6f-11e9-8531-adc166e604b4.gif)

**Comment by NathanSalapat** [comment]
The bottom three listed fades are for audio only, so this isn't really a bug.

**Comment by MisterTeeXD** [comment]
Sorry, but i cant seem to apply them

**Comment by NathanSalapat** [comment]
You can't apply them to the audio tracks either?
I just tried on e847464 which is the latest version from the PPA. Have to click and drag, but they worked on the audio tracks.

**Comment by itsmattkc** [comment]
You can't create transitions on the end/start of a video - there's nothing to fade. You'll need to trim some of it, or alternatively if you're trying to make a "dip to black", create a fade out on the ending clip and a fade in on the starting clip.
