### ISSUE TITLE
selective bluring

### ISSUE THREAD

**Issue by NathanSalapat** [olive-editor/olive#687]
It would be nice to be able to only blur a portion of the screen. I think shape; circle or box, location, size, and of course the blur strength would be great. Currently you can use one of the render effects and put a box of color over sensitive information, but a blur would look nicer.

**Comment by oc1024** [comment]
I think this could be a general "mask for Effects" and implemented as part of masking. #121

As a workaround, you can duplicate whichever image you want to blur, use the Crop effect, and them the blur on the upper copy.

**Comment by itsmattkc** [comment]
Indeed, an offshoot of #121.

**Comment by NathanSalapat** [comment]
ah, excellent, couldn't find anything, but I failed to search for masks.
