### ISSUE TITLE
Audio output indicator freeze arter some time of playback

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#691]
### System Information

**Olive version:**
**Source:** AppImage

### Detailed Description

I detect freeze of Audio indicator on "Timeline" window for a long time.

After some time of playback Audio indicator freezed in some positions - there no any audio issues in same time.

**NOTE:** *Found that if un-pin and then pin "Timeline" window - Audio indicator start work again. But later it could freeze again. By un-pin & pin it coukd be refreshed temporary.*

### Steps to reproduce

There no 100% steps for reproduce

### Output Log

No warning messages in output log

**Comment by unfa** [comment]
I have also experienced this problem.

**Comment by NathanSalapat** [comment]
Has effected me with the PPA on Linux Mint 19.1 as well.

**Comment by itsmattkc** [comment]
I've seen this issue occur in the past but am having trouble recreating it on the latest master. Can you confirm it's still in the latest master?

**Comment by Symbian9** [comment]
> Can you confirm it's still in the latest master?

Yes, I could confirm that audio indicator still freeze in *Olive* `f47a7da`

**Comment by itsmattkc** [comment]
This is fixed in the soon-to-be-merged `furtherocio` branch.
