### ISSUE TITLE
Random Errors From The Debug Log

### ISSUE THREAD

**Issue by MisterTeeXD** [olive-editor/olive#697]
### System Information

**Olive version:**  [675ea94]
**Source:** [zip from github]
**Operating system:** [Windows 10 64-bit]
**CPU:** [Intel i5-6400]
**RAM:** [4GB]
**GPU:** [Intel Graphics HD 530 128MB (Latest drivers)]

### Detailed Description

[There are random errors form the debug log]

### Steps to reproduce

[Start Olive and then Open the debug log]

### Output Log

```
[[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[WARNING] Received nullptr audio device. No compatible audio output was found. (:0, )
[WARNING] QAudioOutput: open error (:0, )
[WARNING] Audio format is not supported by backend, using nearest (:0, )
[INFO] Finished initializing effects (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing custom cursors (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )]
```

### GDB/CDB Backtrace (for crashes)

```
[None right now]
```

**Comment by itsmattkc** [comment]
These are not "random errors", this is normal debug information.
