### ISSUE TITLE
Appimage segfault in Debain 10 Buster SID

### ISSUE THREAD

**Issue by cgvirus** [olive-editor/olive#698]
### System Information

**Olive version:**  Olive-675ea94-x86_64.appimage
**Operating system:** Debain 10 Buster (SID)

### Detailed Description

Doesn't open.
Segmentation fault
Although building from source works. 

### Steps to reproduce

Appimage opening with terminal

### Output Log

2019-03-27T00:47:36 [INFO] Initializing custom cursors
2019-03-27T00:47:36 [INFO] Finished initializing custom cursors
2019-03-27T00:47:36 [INFO] Initializing icons
2019-03-27T00:47:36 [INFO] Finished initializing icons
2019-03-27T00:47:37 [INFO] Initializing effects...
Segmentation fault

**Comment by AGI-THB** [comment]
can you post a stacktrace

**Comment by cgvirus** [comment]
Hi building from source is working. 
The appimage in Github is giving this error:

2019-03-27T00:47:36 [INFO] Initializing custom cursors
2019-03-27T00:47:36 [INFO] Finished initializing custom cursors
2019-03-27T00:47:36 [INFO] Initializing icons
2019-03-27T00:47:36 [INFO] Finished initializing icons
2019-03-27T00:47:37 [INFO] Initializing effects...
Segmentation fault

**Comment by oc1024** [comment]
https://github.com/olive-editor/olive/wiki/How-to-get-output-logs-if-the-program-crashes-and-use-GDB-LLDB-for-more-detailed-logshttps://github.com/olive-editor/olive/wiki/How-to-get-output-logs-if-the-program-crashes-and-use-GDB-LLDB-for-more-detailed-logs

Wiki page on how to get a backtrace.

**Comment by cgvirus** [comment]
Hi with Build I get 
`Reading symbols from ./olive-editor...(no debugging symbols found)...done.`

But Building is working properly. No problem. Already done a small project as well.

Appimage is not working though. I am not sure how can I give you the stack for appimage as It doesn't start.

**Comment by itsmattkc** [comment]
@cgvirus Running GDB on the AppImage should still provide a trace up until the crash, however compiling yourself probably provides a better experience with Olive anyway.

**Comment by cgvirus** [comment]
Hi this what it says:
```
Reading symbols from ./Olive-675ea94-x86_64.AppImage...(no debugging symbols found)...done.
(gdb) 
```

**Comment by itsmattkc** [comment]
In GDB you have to type `run` to start the application, and then when it crashes go back to GDB and type `bt`. That'll print the backtrace.

**Comment by cgvirus** [comment]
Thanks @itsmattkc for the clarification.
After doing gdb olive.appimage
then typing run starts the app and these are the terminal report:

```
Starting program: /home/production/Desktop/Olive-675ea94-x86_64.AppImage 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 4299]
process 4295 is executing new program: /tmp/.mount_Olive-oRXslW/usr/bin/olive-editor
warning: Loadable section ".dynstr" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdd173700 (LWP 4304)]
[New Thread 0x7fffd7fff700 (LWP 4305)]
2019-03-27T22:07:11 [INFO] Initializing custom cursors
2019-03-27T22:07:11 [INFO] Finished initializing custom cursors
2019-03-27T22:07:11 [INFO] Initializing icons
2019-03-27T22:07:11 [INFO] Finished initializing icons
[New Thread 0x7fffd527f700 (LWP 4306)]
[New Thread 0x7fffd4a7e700 (LWP 4307)]
[New Thread 0x7fffc7fff700 (LWP 4308)]
2019-03-27T22:07:11 [INFO] Initializing effects...
2019-03-27T22:07:16 [INFO] Finished initializing effects
[Thread 0x7fffc7fff700 (LWP 4308) exited]
[New Thread 0x7fffc7fff700 (LWP 4309)]
[New Thread 0x7fffc73fd700 (LWP 4314)]
[New Thread 0x7fffc6bfc700 (LWP 4315)]
```
Hope it helps.

**Comment by cgvirus** [comment]
And my self compiled one gives this after GDB>run

```
Starting program: /home/production/olive/olive-editor 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe788d700 (LWP 4573)]
[New Thread 0x7fffe61b2700 (LWP 4574)]
[New Thread 0x7fffe59b1700 (LWP 4575)]
[New Thread 0x7fffe50d3700 (LWP 4576)]
2019-03-27T22:12:31 [WARNING] libpng warning: iCCP: known incorrect sRGB profile
2019-03-27T22:12:31 [INFO] Initializing custom cursors
2019-03-27T22:12:31 [INFO] Finished initializing custom cursors
2019-03-27T22:12:32 [INFO] Initializing icons
2019-03-27T22:12:32 [INFO] Finished initializing icons
[New Thread 0x7fffd5a62700 (LWP 4579)]
[New Thread 0x7fffd5261700 (LWP 4580)]
[New Thread 0x7fffd4a31700 (LWP 4581)]
2019-03-27T22:12:32 [INFO] Initializing effects...
[New Thread 0x7fffb8150700 (LWP 4583)]
2019-03-27T22:12:37 [INFO] Finished initializing effects
[Thread 0x7fffd4a31700 (LWP 4581) exited]
[New Thread 0x7fffd4a31700 (LWP 4584)]
[New Thread 0x7fffa794f700 (LWP 4585)]
[New Thread 0x7fffa714e700 (LWP 4586)]
2019-03-27T22:12:41 [WARNING] libpng warning: iCCP: known incorrect sRGB profile

```

**Comment by cgvirus** [comment]
I think libssl and libcrypto has some problem with it

**Comment by itsmattkc** [comment]
Did the AppImage crash? You left out the `bt` step after it crashed on the AppImage.

**Comment by cgvirus** [comment]
No it doesn't crush. After GBD>run it runs normally and closing the app exits successfully. In between running and closing I typed `bt` but doesn't give any trace then.
I am suspecting this warning:
`warning: Loadable section ".dynstr" outside of ELF segments`
Which is not present in my own build.

**Comment by sobotka** [comment]
Is this still relevant?

**Comment by cgvirus** [comment]
Relevant till Release build (0.1.0).
Let's see what happens with continuous build.
