### ISSUE TITLE
Gaussian Blur effect is nearly identical to Box Blur

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#702]
**Top: Gaussian Blur, sigma: 23
Bottom: Box Blur, radius: 23**

![image](https://user-images.githubusercontent.com/491704/55030054-cd419380-500b-11e9-800e-967a5bb8892c.png)

This is Master Branch, commit 675ea942

**Comment by unfa** [comment]
Tow passes of same Gaussian Blur seem to do a much better job:

![image](https://user-images.githubusercontent.com/491704/55030340-7ab4a700-500c-11e9-874c-f985f5b41e1a.png)

**Comment by BrimsonBhin** [comment]
I believe Gaussian blur's purpose is to smooth the edginess you see in box blur. I notice a sizable difference between the `s` and the `m`.

[2006 article concerning box vs gaussian in After Effects](https://prolost.com/blog/2006/3/2/a-tale-of-three-blurs.html)
[2018 rewrite of the previous article](https://prolost.com/blog/fiveblurs)

According to #376, Gaussian blur is based off of a perfect formula (it's slower). Maybe there should a parameter that addresses the amount of iterations the blurs.

**Comment by unfa** [comment]
An Iterations control would be nice indeed. And maybe it should default to *2*?

**Comment by unfa** [comment]
@BrimsonBhin I've just read both articles - very interesting! I wonder if since Gaussian and Box blur are so similar - if we shouldn't just have a single "Blur" effect with all the features?

**Comment by itsmattkc** [comment]
The gaussian blur used to have "sigma" and "radius" controls, but a few weeks ago I tried automating the radius control to try making the effect "simpler", but I think in actuality that was a bad impulse, and having control over both is crucial to generating a smoother gaussian blur. If you try 1adca7f, experiment with a small sigma and large radius and you should be able to get much more pleasing effects.

**Comment by itsmattkc** [comment]
Turns out my formula for generating the gaussian blur radius was wrong - the gaussian blur in c468d023b01dbabbb1ff9b42319c158bb14937be should be much smoother.

**Comment by alcomposer** [comment]
@itsmattkc Gaussian blur in Olive does not extend to edges, it gradually becomes less blurred. There should be a toggle for `extend to edges`.
