### ISSUE TITLE
Swirl effect removes transparency

### ISSUE THREAD

**Issue by hellocatfood** [olive-editor/olive#703]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:**  675ea94
**Source:** PPA
**Operating system:** Ubuntu 18.10 64-bit
**CPU:** Intel i7
**RAM:** 8GB
**GPU:** NVIDIA Geforce GT 1030 2GB

### Detailed Description

Adding a swirl effect to an transparent image removes transparency of the image. See gif below

![Peek 2019-03-27 00-09](https://user-images.githubusercontent.com/151947/55041634-d3446e00-5025-11e9-855d-85d695a537ec.gif)

### Steps to reproduce

Add a video/image.
Overlay a transparent png
Add a swirl effect to the transparent image
Adjust the settings

**Comment by alcomposer** [comment]
The shader also needs to work on the alpha:
```
#version 110

// Swirl effect parameters
uniform float radius;
uniform float angle;
uniform float center_x;
uniform float center_y;
uniform vec2 resolution;

uniform sampler2D myTexture;
varying vec2 vTexCoord;

void main(void) {
	vec2 center = vec2((resolution.x*0.5)+center_x, (resolution.y*0.5)+center_y);

	vec2 uv = vTexCoord.st;

	vec2 tc = uv * resolution;
	tc -= center;
	float dist = length(tc);
	if (dist < radius) {
		float percent = (radius - dist) / radius;
		float theta = percent * percent * (-angle*0.05) * 8.0;
		float s = sin(theta);
		float c = cos(theta);
		tc = vec2(dot(tc, vec2(c, -s)), dot(tc, vec2(s, c)));
	}
	tc += center;
	vec4 color = texture2D(myTexture, tc / resolution).rgba;  //<-- working on alpha as well
	gl_FragColor = color;
}
```

**Comment by itsmattkc** [comment]
I legitimately just discovered this yesterday, I have no idea why it was written like that.
