### ISSUE TITLE
Changing crop values creates alpha ghosts and strange patterns in proceeding effects

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#704]
Issue found on both GPU: 
* GeForce MX150/PCIe/SSE2 v: 4.6.0 NVIDIA 418.56 
* Mesa DRI Intel UHD Graphics 620 (Kabylake GT2)  v: 4.5 Mesa 19.0.0 

Issue found due to discussion on #703

__Checkerboard -> Crop -> Swirl__

Here is what happens when a user puts the above chain together and then adjusts the crop values:
### Alpha drawing issue in current `furtherocio`
![glitch](https://user-images.githubusercontent.com/12004932/55055615-7099b380-50b3-11e9-852f-37d4adec66f3.png)

As in discussion #703, the issue is present in `master` branch when the `swirl.frag` is modified to process alpha channel as well.

**Comment by DaniSeeh** [comment]
Also getting strange outcome.
![Screenshot from 2019-03-28 02-17-47](https://user-images.githubusercontent.com/46905995/55137753-c5fbb200-50ff-11e9-9d31-3ceeab8239ed.png)

**Comment by alcomposer** [comment]
Looks like this is fixed in 4e0188fd3a0d280c89820b45fa43ff158d7ed618
