### ISSUE TITLE
[FR] Autoduck audio filter

### ISSUE THREAD

**Issue by RafaelLinux** [olive-editor/olive#705]
Feature request.
I'm Kdenlive user and one of the functionalities I miss in it is the "Autoduck" audio effect. This effect let you take two audio tracks (usually background music and narrator voice) and automatically decrease music track volume when narrator talks and vice versa, modifying the music volume envelope. Actually I need to do it externally, with the tool "Autoduck" of "Audacity", export the result and then import in KDEnlive.

I wouldn't mind if Olive will require Audacity to be installed and called it in background if process were in the background, if at least user would not need to do nothing outside Olive.

Thank you

**Comment by frink** [comment]
This is a sidechain compressor in audio terms. Ducking is pretty important for several workflows. Mostly, when the editor needs to rough something out quickly. But we need to be able to export the audio sans effects for the audio workflow on larger projects...

Remember this is targeted at pro workflows first-off. But yes ducking can be very helpful when you're trying to edit quickly. I just wouldn't want to leave any of my production the ducking as the final output. But I'm an audio snob running a pro studio so... Take the comment FWIW...

**Comment by RafaelLinux** [comment]
IMO, even the tool for "Speed/Duration", that let user even change the audio pitch, could be considered as an audio compressor. And yes, the "Speed/Duration" could be done outside Olive, but it is not.
I think Olive is not intended only for larger projects, but even for 7 minutes pills that requires a lot of creativity and resources, not necessarily edit quickly. So I was thinking that a pro video editor should let user the possibility to do all non-destructive processes - as ducking is - just without exiting from Olive. The ability to proxy processes will avoid a excessive CPU comsuption. 

Thank you anyway for your reply

**Comment by frink** [comment]
I see.

**Comment by frink** [comment]
@sobotka Could you please add a verdict if you're closing.

It's hard to tell what you're thinking without context... ;-)
