### ISSUE TITLE
Not whole space of viewers area used if zoom in media or sequence

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#706]
### System Information

**Olive version:** https://github.com/olive-editor/olive/commit/675ea942f1cb18261637e30f17eeca814a6501d3
**Source:** AppImage

### Detailed Description

![pic.1](https://i.imgur.com/e2GaPqb.png)

**Comment by BrimsonBhin** [comment]
Zoom: Fit means that the video's width (not height) fits the sequence viewer

The space is not used because your sequence's aspect ratio differs from your window size.

**Comment by Symbian9** [comment]
*Olive* should ignore "aspect ratio cutout" if «Fit» is disabled (if Zoom In or Zoom Out)
