### ISSUE TITLE
blend modes doesn't work anymore

### ISSUE THREAD

**Issue by learntobealright** [olive-editor/olive#711]
**Olive version:** march  e04c9c6
**Source:** [PPA]
**Operating system:** Linux mint 19.1 64-bit]

The blend mode under transform doesn't work anymore .
![Bildschirmfoto vom 2019-03-28 11-18-21](https://user-images.githubusercontent.com/49024323/55149946-65926200-514b-11e9-996d-2d9ed28d59a3.png)

**Comment by itsmattkc** [comment]
Blend modes are being rewritten at the moment. A new set will return shortly.

**Comment by learntobealright** [comment]
:)
