### ISSUE TITLE
Sequence is fully "white" if set frame size 1280x2049

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#716]
### System Information

**Olive version:** 
**Source:** AppImage
**Operating system:** Debian 9.x, 64-bit

### Detailed Description

If set/create sequence with frame size 1280x2049 - in "Sequence Viewer" it return only "white blank" frame.

![pic.1](https://i.imgur.com/HZxWS39.png)

If set sequence frame size to 1280x2048 all seems work as expected.

![pic.2](https://i.imgur.com/OxOeuU9.png)

**Comment by itsmattkc** [comment]
This is a limitation of your graphics hardware - your hardware doesn't support odd numbered texture sizes (or perhaps it doesn't support textures larger than 2048 in general)
