### ISSUE TITLE
Olive editor shows white screen when opening it but I can access the options in it

### ISSUE THREAD

**Issue by 32-bit-link** [olive-editor/olive#718]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:** March 2019 Alpha f47a7dad
**Source:** Website
**Operating system:** Windows 10 1809 (64 bit)
**CPU:** AMD A6-1450
**RAM:**  4GB
**GPU:** AMD Radeon HD 8250

So Today I decided to install the olive video editor after I heard a lot of good things about it. But when I installed it and opened it all I got was a white screen, I was able to access the menu bar but I couldn't see that also.

Screenshot of what I see:

![olive white screen](https://user-images.githubusercontent.com/49044214/55194546-6bef0100-5180-11e9-816a-c9e9ebe73678.JPG)

**Comment by itsmattkc** [comment]
Olive is heavily reliant on OpenGL. Are your graphics drivers up to date?
