### ISSUE TITLE
Dubug Log messages order inverted?

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#719]
### System Information

**Olive version:** `f47a7da`
**Source:** AppImage

### Detailed Description

Messages in "Debug Log" window added in inverted order — latest/newest log message is first (ontop of previous messages)

Is it OK?

**Comment by itsmattkc** [comment]
Indeed it was written to be like this, but I'm not sure why - I think it'd be better not inverted (ce047dd60f70b31150551e78def2bdb0e70366d4)
