### ISSUE TITLE
Giving local access to install effects in Linux [Enhancement]

### ISSUE THREAD

**Issue by cgvirus** [olive-editor/olive#721]
Hi, as we were discussing to give path access to the users:

After line 81 in path.cpp
```
//get homepath
  QString homePath = QDir::homePath();
  effects_paths.append(homePath + "/.local/share/olive-editor/effects");
```
can give access to custom effects library in Linux in this given path.

**Comment by itsmattkc** [comment]
Done in a581d36bcc830bf81bcb2526596b0d0ff44e7768
