### ISSUE TITLE
Add "Font" option for "Timecode" effect

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#723]

**Comment by frink** [comment]
@Symbian9 Not sure what you mean. Could you explain a little? Thanks.

**Comment by alcomposer** [comment]
I think the idea is to allow different fonts for the display of timecode & the text that is prepended.
Having original worked on the Timecode burn-in effect, it is mainly used for technical reasons, hence there is no choice for font. Also remember, as it is rendering numbers, you would want a mono-space font.

**Comment by Symbian9** [comment]
> I think the idea is to allow different fonts for the display of timecode & the text that is prepended.
> 
> Having worked on the original Timecode burn-in effect, it is mainly used for technical reasons, hence there is no choice for font. Also remember, as it is rendering numbers, you would want a mono-space font.

Exactly.

**Comment by itsmattkc** [comment]
I'm pretty sure he's providing a reason why the timecode should _not_ have a font field. Regardless, I think the real solution is providing some sort of time formatting for text generation rather then adding more features to the timecode effect.

**Comment by frink** [comment]
Agreed.
