### ISSUE TITLE
Add "Countdown" type for "Timecode"

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#724]
### Actual behaviour

*"Timecode > Sequence"* and *"Timecode > Media"* types of "Timecode" effect work only as 'timepiece'.

### Expected behaviour

There should be also 'countdown' type of timecode:

![pic.1](https://i.imgur.com/RosXGYj.png)

### "Clip", NOT "Media"

Propose rename *"Media"* to *"Clip"* (for "Timecode"), as "Media" term used for imported media files.

Clip could has linked media file, but also there could be clips without media files (for example, such as "Title" clip)

**Comment by alcomposer** [comment]
*sequence* = sequence timecode
*media* = media in sequence timecode
*clip* = timecode of footage (what is burned into media from camera)

**Comment by Symbian9** [comment]
> media = media in sequence timecode

media linked to clips, so "media in sequence" is not clear.

@alcomposer Could you draw what you mean?

**Comment by alcomposer** [comment]
When you drag media into the project, it is imported as footage, which normally already has its own timecode. When that footage gets dragged into a sequence it has both it's footage timecode, and the timecode of the footage container (which would stat from 0). Maybe it should be renamed to be clear.

**Comment by alcomposer** [comment]
Sorry, I got it backwards!

* __Sequence__ TC = Timeline TC
* __Clip__ TC = Clip in Timeline TC
* __Media__ TC = Original Footage TC 

Does this make more sense?  This will also get more complex, as Footage could have either none or all of the below:
* Metadata TC
* LTC (embedded in audio track)
* User set TC

_Obviously only media with attached audio streams - or audio files can contain LTC_

**Comment by itsmattkc** [comment]
Same with #723
