### ISSUE TITLE
[FR] Allow recording audio in higher PCM bit-depths than 16-bit

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#728]
Right now Olive can capture audio in 16-bit PCM.
It'd be nice to also enable 24-bit, or even 32-bit float sample formats.

It's not of high priority - as I only use that for drafting, but that feature could make it more feasible for actual production :)

:man:  :heart:  :microphone:  :sound: :inbox_tray:  :green_apple:

**Comment by AGI-THB** [comment]
related to #672

**Comment by itsmattkc** [comment]
I see this as the same as #672 so I'll roll this into that one.
