### ISSUE TITLE
Few questions for localization

### ISSUE THREAD

**Issue by MassiminoilTrace** [olive-editor/olive#729]
I have some questions. I need to know what these options do to translate correctly.
In the settings, what `Effect Textbox Lines:` exactly does?

The string `Clear Undo` only appears inside a QT_DEBUG ifdef.
Where does it appear in the gui? How I make it appear?

Thank you in advance.
You can check the progress in my fork at https://github.com/MassiminoilTrace/olive/tree/italian_localization

**Comment by itsmattkc** [comment]
"Effect Textbox Lines" is the height of a textbox in the Effect Controls in "lines". It defaults to 3 lines of height.

"Clear Undo" is a debugging option for testing undo commands. It clears the entire undo stack (i.e. any commands in the undo stack are deleted so the user can't undo/redo anymore). As I said, it's only for testing.
