### ISSUE TITLE
Freeze when exporting audio-only

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#732]
### System Information

**Olive version:** a581d36bcc830bf81bcb2526596b0d0ff44e7768
**Source:** Github
**Operating system:** Manjaro
**CPU:** Rzyen 7 1700
**RAM:** 32 GB
**GPU:** NVIDIA Geforce GTX 1060 8GB (Driver ver 418.43)

### Detailed Description

Olive freezes during exporting. Nothing seems to show up in the terminal output, it just stops.

### Steps to reproduce

1. Create a project.
2. Export audio-only: WAVE or Ogg

It doesn't happen every time, only most of the times.

### Output Log + Backtrace
[Backtrace.txt](https://github.com/olive-editor/olive/files/3025376/Backtrace.txt)

**Comment by itsmattkc** [comment]
Can you clarify "freezing"? i.e. does Olive become unresponsive or does the export stop? Also does this freeze occur at the beginning of an export or part-way through?

**Comment by unfa** [comment]
Olive stops responding or redrawing it's UI, I can still close the Export dialog, but that's it. It happens randomly mid-export and results in truncated audio files.

**Comment by itsmattkc** [comment]
Should be fixed in a0f6299
