### ISSUE TITLE
[Feature Request] Support for Blackmagic Raw

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#733]
This [FR] is potentially relatable to #237 and #696.

This format is relatively new and its been out on the lnternet for quite some time, but from I've looked into this is interesting.

https://www.blackmagicdesign.com/products/blackmagicraw

Some of the features such as dynamic color range, GPU wotkflow, cross platform support, and licence free!

There is also sample files on the Blackmagic Raw page which in theory be used to test the implementation of the Blackmagic Raw SDK, a development kit that can be used to be coded in any developer's software.

Blackmagic Raw support for Olive is farfetched, not to mention that there's bound to bring forth interesting arguments about it, but I find it facinating for this format.

With the format implementation it could be used in the HDR/ Color Management workflow: #237.

**Comment by frink** [comment]
As long as there is SDK to support it this is probably right along the lines of Olives goals. We're focused on a professional grade editor and there is no denying that Blackmagic is one of the large players in this space. I think formats like Blackmagic and Redd are essential to providing a pro-grade experience.

**Comment by Corruptinator** [comment]
I won't deny the fact its up to @itsmattkc's decision to determine whether it should be implemented or not.

**Comment by frink** [comment]
Several trendsetters in the open source world have complained openly about linux video editors not supporting proprietary formats. The above and ProRes are the main ones I hear mentioned.

**Comment by sobotka** [comment]
I believe BlackMagickRaw is encumbered via an SDK. Will repopen if the status changes.
