### ISSUE TITLE
Canceling Export Causes Olive Becoming Non-Responsive

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#734]
### System Information

**Olive version:**  [a581d36b]
**Source:** [zip from github]
**Operating system:** [Windows 10 64-bit]
**CPU:** [Intel i5-6400]
**RAM:** [4GB]
**GPU:** [Intel Graphics HD 530 128MB (Latest Drivers)]

### Detailed Description

[When canceling an export, Olive will become non-responsive and forces exiting]

### Steps to reproduce

1: Go to File>Export and click the export button
2: While exporting, click the "x" button to cancel exporting and Olive should become non-responsive

### Output Log

```
[Nothing]
```

### GDB/CDB Backtrace (for crashes)

```
[Nothing]
```

**Comment by qubodup** [comment]
Confirmed solved, thanks!
