### ISSUE TITLE
Audio pitch shifts on export.

### ISSUE THREAD

**Issue by NathanSalapat** [olive-editor/olive#735]
### System Information

**Olive version:**  a581d36
**Source:** PPA
**Operating system:** Linux Mint 19.1 64-bit
**CPU:** Intel i7-8700K
**RAM:** 32GB
**GPU:** Nvidia GeForce GTX 1060 6GB VRAM, driver version 390.116 

### Detailed Description

Exported audio pitch shifts during the first few seconds sometimes. I've only experienced this with .ogg audio, and exporting as libx264 H.264 and AAC audio. I changed the settings to use H.265 and the problem was gone. This time the audio pitched down, but on older versions I had a problem with it pitching up.

**Comment by itsmattkc** [comment]
Can you provide an example of this?

**Comment by NathanSalapat** [comment]
I can re-export a bad clip and upload it.
https://youtu.be/QhMPI_iFTWI
Here's what the timeline looks like.
![audio-pitch](https://user-images.githubusercontent.com/8930456/55282911-3848de00-531c-11e9-903f-cf7472cacf9f.png)

I've used this same audio file in the past with no issues.

**Comment by itsmattkc** [comment]
Does 3251a420c066c093a54673304be89397287744e8 fix this?

**Comment by NathanSalapat** [comment]
Well if the PPA was working I would know. ;)
I will try and build from source and see if I have any trouble with it.

**Comment by NathanSalapat** [comment]
I got lucky, or unlucky I guess, the first test I exported still had the error. It's rather hit and miss though. I edit lots of gaming videos and rarely experience this, but for some reason when I'm dealing with lots of video clips and audio clips it seems to happen.

**Comment by itsmattkc** [comment]
While trying to diagnose this, there have been a couple workarounds that should help:

* Check if your export audio frequency is equal to the output device's (in Preferences > Audio). If they're equal this glitch shouldn't occur.
* Move the playhead beyond very end of the sequence (a few seconds after the last clip ends) before exporting.

**Comment by NathanSalapat** [comment]
The audio frequency was different so I changed them, that didn't help, but moving the playhead did, so I'll just keep that in mind for future exports.

**Comment by NathanSalapat** [comment]
I've found that adding several seconds of silences to the end of the audio clip also keeps the audio from pitch shifting. This has proven to be more reliable than other things I've tried. I'll leave the issue open because this shouldn't be the solution, but for me I'm always using a single clip for an intro on my videos, so I've just edited that clip and have had no trouble with it since.
