### ISSUE TITLE
No languages available in preferences other than English

### ISSUE THREAD

**Issue by qubodup** [olive-editor/olive#737]
### System Information

**Olive version:** a581d36b
**Source:** Official
**Operating system:** Windows-x86_64 10
**CPU:** i5-6600
**RAM:** 32
**GPU:** gtx 970

### Detailed Description

Only English is available. I was told on Discord there are many languages available.
![image](https://user-images.githubusercontent.com/18312/55281587-dfd30a00-5336-11e9-8e40-66aa335e4385.png)

### Steps to reproduce

Open preferences (ctrl + ,), click English.

Expect: long list of languages.

Actual result: only English available.

### Output Log

```[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing custom cursors (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[WARNING] QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )```

**Comment by itsmattkc** [comment]
Should be fixed in current Windows release.

**Comment by qubodup** [comment]
Confirmed, thanks!
