### ISSUE TITLE
The xml for effect doesn't support field type int

### ISSUE THREAD

**Issue by cgvirus** [olive-editor/olive#738]
Olive version: [a581d36]
The xml for effect doesn't support `field` type `int` .

**Comment by itsmattkc** [comment]
What is your use-case for `int` over `double`?

**Comment by cgvirus** [comment]
Needed to do sample and loop
Current hack I have done is with typecasting here an example:
https://github.com/cgvirus/Olive-Editor-Community-Effects/blob/master/bokehBlur/bokehBlur.frag

**Comment by itsmattkc** [comment]
This will be addressed in the node rewrite.
