### ISSUE TITLE
If disable "Enable Drag Files to Timeline" still possible drag files on "Timeline"

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#742]
### System Information

**Olive version:** https://github.com/olive-editor/olive/commit/a581d36bcc830bf81bcb2526596b0d0ff44e7768
**Source:** AppImage
**Operating system:** Debian 9.x 64-bit

### Detailed Description

It is possible drag files from "Project" to "Timeline" if option "Enable Drag Files to Timeline" disabled.

### Steps to reproduce

1. Disable "Preferences > Behavior > Enable Drag Files to Timeline";
2. Try drag imported files from "Project" to "Timeline".

### Output Log

**Comment by itsmattkc** [comment]
That's not what that option does. It disables dragging files from outside of Olive (e.g. a file manager) directly into the Timeline.

**Comment by Symbian9** [comment]
> That's not what that option does.

Then need rename it for better clarification
