### ISSUE TITLE
 multi-language

### ISSUE THREAD

**Issue by yoyling** [olive-editor/olive#744]
I feel it is necessary to achieve multi-language thanks.

**Comment by yoyling** [comment]
I feel it is necessary to implement multi-language including Simplified Chinese. Thank you.

**Comment by AGI-THB** [comment]
You can translate the files by yourself if you speak that language.
[click here](https://github.com/olive-editor/olive/wiki/Translations)

**Comment by AGI-THB** [comment]
#478

**Comment by itsmattkc** [comment]
Olive is already multi-language, but translations are provided by the community. As @AGI-THB says, you can work on the translation yourself if you're knowledgeable in both languages.
