### ISSUE TITLE
My nested Sequence is semi-transarent, but should be fully opaque

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#745]
**Olive version:** a0f629906194623dd29bb277e81266eab8fd031e (Git master)

This is what the insides of my sequence look like:
![02](https://user-images.githubusercontent.com/491704/55290760-853dba80-53d7-11e9-918f-caa3b1ba5561.png)

This is the desired look - I had this in my master sequence but wanted to nest it in order to make cutting easier.

However after nesting, the whole thing becomes semi-transparent:
![01](https://user-images.githubusercontent.com/491704/55290746-460f6980-53d7-11e9-8010-e28339d9e40d.png)

As you can see a text from below is visible. I can't change this in any way.

Here's the whole project (without media files, with all history - the newest is 07.ove):
[Editing.zip](https://github.com/olive-editor/olive/files/3026745/Editing.zip)

**Comment by AGI-THB** [comment]
related? #675

**Comment by unfa** [comment]
Could be. If I use the Further OCIO branch - will that be fixed?

**Comment by unfa** [comment]
I've found that a workaround is to use three stacked copies of the same sequence to get visually pleasing results - though then in editing the image flickers black, so that's not nice :/

![03](https://user-images.githubusercontent.com/491704/55290849-c387a980-53d8-11e9-8fdf-de033b7e0709.png)

Could the fix from FurtherOCIO be ported back to the Master branch?

**Comment by itsmattkc** [comment]
Try running Olive with `--disable-blend-modes` and see if that helps.

Unfortunately the fix in `furtherocio` is not easily ported back because there was a fairly sweeping rewrite of the OpenGL backend involved in that branch. I also wouldn't recommend using that branch for any serious work just yet. If the above switch doesn't work, I can maybe see if there's a simple fix in the current master.

**Comment by unfa** [comment]
Thanks, @itsmattkc ! I'll try that, though for now I managed to complete the project without using Nested Sequences or stacking them to workaround.

**Comment by cgvirus** [comment]
I think it has been fixed in current OCIO branch. Just tested

**Comment by itsmattkc** [comment]
It has, so I'll close this now
