### ISSUE TITLE
[furtherocio]: Build from source with various issues

### ISSUE THREAD

**Issue by sobotka** [olive-editor/olive#746]
Summary: When building from the `furtherocio` branch, various issues arise:

- "Enable Colormanagement" unchecked by default, and a configuration is not set by default.
- Setting a configuration doesn't list Views until subsequent opening of the Preferences. Looks and Displays appear fine, which seems odd that an "OK" is required, and preferences to be opened again?
![Screenshot from 2019-03-31 14-29-14](https://user-images.githubusercontent.com/59577/55295433-cf1ba600-53c1-11e9-94a1-f5287b651d3a.png)
- View doesn't appear to refresh when changed via Preferences.
- Display / View / Look should be located in the viewer due to the fact that the View and Look is likely needed to be changed frequently during work, as well as the ability to move it across different displays?
- Changing the transform for media creates a segfault with no output via CLI:
```
#0  0x00005555555e9b00 in Sequence::Close() ()
#1  0x0000555555614f6f in OliveAction::redo() ()
#2  0x0000555555667625 in ComboAction::redo() ()
#3  0x00007ffff5ed5f03 in QUndoStack::push(QUndoCommand*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00005555556261f7 in MediaPropertiesDialog::accept() ()
#5  0x00007ffff507e906 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff5cf92f0 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff507e906 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff5c59642 in QAbstractButton::clicked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff5c5985a in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
```
1. Load an OCIO configuration
2. Set colourspace on properties via media selection
3. Click OK to segfault

**Comment by AGI-THB** [comment]
This Branch is far from finished and should not be used for serious work, he said that a while ago. He is rewriting a lot of stuff to keep the program maintainable while adding new features afterwards. 

You can look it up here: [project progress](https://github.com/olive-editor/olive/projects)

Thanks for your feedback, though. ;)

**Comment by sobotka** [comment]
Aware thanks. The reason the branch exists is because of #237, and I'm relatively sure that Matt probably wants those issues listed here.

**Comment by alcomposer** [comment]
I am able to confirm all of Troy's findings. Segfault is reproducible, and backtrace is identical.

**Comment by itsmattkc** [comment]
I believe most of these have been addressed or in the process of being addressed.
