### ISSUE TITLE
Texture Wrapping  and Filter parameters for Effects

### ISSUE THREAD

**Issue by cgvirus** [olive-editor/olive#748]
Hi, it seems most of the effects involved with for example Blur or Kernel needs 
`Gl_Clamp_To_Edge` enabled. 
How can we do that? Is it implemented yet?

Currently all kind of blur effects are I believe using `Clamp_To_Border`. It would be better if we could enable/disable `edge clamp` from Olive interface with XML.

**Comment by cgvirus** [comment]
Proposal: Like OpenFX, if we can always reveal various Wrap and Filter modes for all effects in effects panels with a drop down, users can test their own use for these. Although edge clamp bool option is enough for now.

**Comment by itsmattkc** [comment]
You can do this in the shader by clamping your texture coordinates between `vec2(0.0)` and `vec2(1.0)`. I think that's a much less breakable solution than maintaining an API in the XML.

**Comment by cgvirus** [comment]
Hi it may not be suitable if tex2D has `float bias` for mipmap and I believe it's a hacky solution which can become a problem in future.
I could not made the mipmap working for bookeh noise. The hack could be more simpler like : 
`tex2D (tex,frac(texcordinate))`
But makes the code non stable and also non-standard. I will ask to reconsider if something can be done.
Thanks.

**Comment by itsmattkc** [comment]
This will be addressed in the node rewrite.
