### ISSUE TITLE
Hardcoded tool shortcut

### ISSUE THREAD

**Issue by MassiminoilTrace** [olive-editor/olive#749]
The keyboard shortcut in all tools is hardcoded. If the user changes the shortcut for a tool, that string remains the same.
In the example below, if I change the pointer tool shortcut from 'V' to something else, the 'V' in this text doesn't change.
![hardcoded shortcut](https://user-images.githubusercontent.com/24638827/55361869-b4882080-54d8-11e9-838b-fe7528e6229d.png)

**Comment by ufrshubham** [comment]
Nice find. I checked and found that it gets updated in tools tab. Seems like the problem is only with tooltip.
![Cropped](https://user-images.githubusercontent.com/33748002/55820111-f25bf900-5b17-11e9-94fe-a50a8430d701.jpg)
