### ISSUE TITLE
[BUG] Windows 7: While Trimming or Dragging info box is black

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#750]
If you are dragging the clip around or want to trim it the info box underneath the cursor is black.
Thank you for addressing this bug in advance and keep up the great work!

**Comment by mdmayfield** [comment]
I have occasionally seen this in Windows 10 as well. @libalis If you can, will you please post your graphics card info and exact Windows version?

Mine, on the system where I've seen this issue, is:
Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s), NVIDIA Quadro FX 380 GPU

I was not able to capture a screenshot or recording of this issue, but I have simulated it here with image editing software:
![image](https://user-images.githubusercontent.com/26154258/55495392-68d19600-5602-11e9-8458-4cf41d34cdc5.png)

**Comment by BrimsonBhin** [comment]
Seen this with a Radeon R7 250x

It usually goes away after you drag the clip around in the same place for a while

**Comment by itsmattkc** [comment]
Honestly not sure, this feels like it may be a Qt bug exclusive to Windows. Try using a "Native" style in Olive and see if it persists, that'll help narrow down if it's a CSS/palette issue or some interference from OpenGL.

**Comment by BrimsonBhin** [comment]
It is a Windows exclusive issue. I tried the appimage on Kubuntu 18.10 and the dragging went smooth as butter. The issue still persists after changing to the native style.

**Comment by itsmattkc** [comment]
Yeah, I believe this is a Qt bug. Since Olive just invokes a QToolTip (and this only seemed to appear once Windows builds updated to 5.12), it's likely the culprit is there. If so, there's not much we can do, hopefully it'll be fixed by the next update.
