### ISSUE TITLE
Wiki-page for collect info about known presets

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#755]
I would be happy to help write wiki-page where we would collect known presets.

For example, required presets for social media:

- https://blog.online-convert.com/upload-videos-to-social-media/
- https://blog.online-convert.com/optimize-your-videos-for-youtube/

**Comment by itsmattkc** [comment]
If you would like to start writing one, feel free. The Wiki is open to the public for editing.

**Comment by Symbian9** [comment]
> If you would like to start writing one, feel free

What name should I for such wiki-page?
