### ISSUE TITLE
Not showing anything!

### ISSUE THREAD

**Issue by zakaria-chahboun** [olive-editor/olive#756]
### System Information

**Olive version:**  Olive (March 2019 | Alpha | a0f62990)
**Source:** Installer from the website
**Operating system:** Windows 10
**CPU:** Intel Core 2 Duo
**RAM:** 5 GB
**GPU:** Intel Q965/Q963

### Detailed Description

When i put Image or Video into the timeline sequence .. **the view tab still black!** and the audio works fine

### Output Log

```
[ERROR] Couldn't retrieve an appropriate frame. This is an error and may mean this media is corrupt. (:0, )
[ERROR] Failed to retrieve frame for clip "001V114.mp4" (:0, )
[WARNING] Failed to create texture (:0, )
```

**Comment by oc1024** [comment]
Olive needs full OpenGL 3, unfortunately your GPU is just too old.

**Comment by Symbian9** [comment]
@zakaria-chahboun, please, upload `001V114.mp4` file for testing

**Comment by ZoomTen** [comment]
Does setting `Use software fallbacks when possible` in the Preferences fix it?

**Comment by zakaria-chahboun** [comment]
> @Symbian9 

i try a lot of videos ... with different formats (.mov .mp4 ....)
this is the link of the [VIDEO](https://drive.google.com/open?id=12smBcBGilkdmGqC2FsCEY6FvIkDGKj9-) in my google drive

**Comment by zakaria-chahboun** [comment]
its working on the same hardware but with different os - **Linux Fedora 29 - KDE PLASMA**
![image](https://user-images.githubusercontent.com/18173275/55662830-33e65e80-580f-11e9-8a48-9c12e0bf0cf0.png)

**Comment by itsmattkc** [comment]
That suggests it's a driver issue, are your graphics drivers up to date on Windows?

**Comment by zakaria-chahboun** [comment]
Yes!

**Comment by itsmattkc** [comment]
You may get better luck once the GL ES compliant pipeline is merged in, but otherwise I'm afraid this seems to be out of Olive's hands. Glad to see you found a solution though
