### ISSUE TITLE
Tile Effect black border

### ISSUE THREAD

**Issue by alcomposer** [olive-editor/olive#758]
### System Information

**Olive version:** 31bb8627
**Source:** git [tested *master* & *furtherocio*]
**Operating system:** Antergos
**CPU:** Quad Core Intel Core i7-8550U
**RAM:** 16
**GPU:** GeForce MX150/PCIe/SSE2 v: 4.6.0 NVIDIA 418.56 

### Detailed Description
Tile effect creates black boarder around tiled media, the black boarder is transparent, if I place the same color behind the tiled color the black boarders disappear.  
### Steps to reproduce
Create a solid-color-generator, add `tile effect`, decrease the scale, black lines are present in preview- and export
![Screenshot from 2019-04-05 18-09-03](https://user-images.githubusercontent.com/12004932/55611955-953a0d80-57ce-11e9-8296-c0a8334eb38d.png)

**Comment by BrimsonBhin** [comment]
I am experiencing this as well on Windows. The black borders bug can be emulated by just turning the `scale` setting to a low value

**Comment by itsmattkc** [comment]
Related to #748, allowing the effect to use GL_CLAMP_TO_EDGE will solve this.

**Comment by cgvirus** [comment]
I think GL_CLAMP_TO_EDGE should be default in Olive Editor. As Blur, Edge Finding ops like sharpen etc needs proper edge clamping. 
May be it will be a good idea to hack the frag code with a bool, only if some effects need edge black border (very unlikely).
Also I have heard GL_CLAMP_TO_BORDER is deprecated in GLSL 3 as well and OGL ES supports only GL_CLAMP_TO_EDGE.

This wrap mode is falling back many good and essential effects like Blur and Sharpen in jeopardy. I highly suggest to rethink of GL_CLAMP_TO_EDGE as default. Thanks.

**Comment by itsmattkc** [comment]
Possibly, the intention with the node structure is to allow clamping parameters so people can construct solutions that most suit the problem

**Comment by cgvirus** [comment]
That will be best
