### ISSUE TITLE
Bokeh Blur Effect

### ISSUE THREAD

**Issue by emma-15** [olive-editor/olive#760]
I think a Bokeh Blur would be a great addition to the blur effect library,
just like in [After Effects](https://youtu.be/AA2SiQEu5AA).

**Comment by Symbian9** [comment]
"Bookeh Blur" effect already added into ***«Community»*** effects repo:

- https://github.com/cgvirus/Olive-Editor-Community-Effects/tree/master/bokehBlur

Details:

- https://github.com/cgvirus/Olive-Editor-Community-Effects

**Comment by itsmattkc** [comment]
This is true, the community effects repository has such an effect (and maybe they'll be merged into Olive later if they have compatible licenses).

**Comment by emma-15** [comment]
These community effects are really excellent, thanks.
