### ISSUE TITLE
Extend Effects descriptions

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#764]
### Add/Allow descriptions for all effect

Currently only *Frei0r* effects has descriptions

![pic.1](https://i.imgur.com/cdJNruE.png)

- [ ] Add description for built-in effects;
- [ ] Add effects description API for custom/user defined effects:
  - https://github.com/cgvirus/Olive-Editor-Community-Effects
- [ ] Show Effect description if place cursor on title of added effect:

![pic.2](https://i.imgur.com/xQhZUcP.png)

**Comment by itsmattkc** [comment]
This has been addressed in the node rewrite.
