### ISSUE TITLE
"Type" options in "frei0r" effects are not clear

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#766]
Is it possible recognize all possible "Type" options operators for  "frei0r" effects and represent it as dropdown list?

![pic.1](https://i.imgur.com/nZLGCAp.png)

![pic.2](https://i.imgur.com/HjeM6mG.png)

**Comment by AGI-THB** [comment]
frei0r will be removed since it has many flaws...

[click here](https://github.com/olive-editor/olive/wiki/Frei0r-Support-EOL)

**Comment by Symbian9** [comment]
> frei0r will be removed since it has many flaws...

@itsmattkc , please, add some possibility for add "frei0r" as user defined effects!

"frei0r" currently work in *Olive* with older GPU's, where similar GLSL effects won't work...

**Comment by itsmattkc** [comment]
This is accurate to the Frei0r API - it has [no specification for a drop down list](https://frei0r.dyne.org/codedoc/html/group___p_a_r_a_m___t_y_p_e.html) so there's no way for Olive to interpret these as one. One of its many issues.
