### ISSUE TITLE
Same Image on the Sequence with different quality

### ISSUE THREAD

**Issue by zakaria-chahboun** [olive-editor/olive#768]
## System Information
**Olive version:** Olive-6264123-x86_64.AppImage
**Source:** AppImage from github
**Operating system:** Fedora 29 KDE PLASMA
**CPU:** Intel Core 2 Duo
**RAM:** 5 GB
**GPU:** Intel Q965/Q963
**OPENGL 3**

## Detailed Description
When i create a *Sequence* with 1080px all thing works fine, **but when i modified the parameter of sequence and change the quality to 720px** (for example) ... nothing is showing ... just a black screen

## LOG OUTPUT
```
[ERROR] Failed to retrieve frame for clip "Blender 2.8 Will Be A Game Changer! - EEVEE, Grease Pencil, Features, and Release Dates.mp4" (:0, )
```
![image](https://user-images.githubusercontent.com/18173275/55663202-6f832780-5813-11e9-95fe-d3f11f498e69.png)

**Comment by itsmattkc** [comment]
Probably something disagreeing between Olive's OpenGL and your GPU. We'll see if the new GL ES pipeline will help solve this in the near future.
