### ISSUE TITLE
No support for start time in MTS files

### ISSUE THREAD

**Issue by GlennWilk** [olive-editor/olive#769]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:**  Olive (March 2019 | Alpha | 6264123b)
**Source:** [Website etc. zip]
**Operating system:** [e.g. Windows 10 64-bit]
**CPU:** [e.g. Intel i5-4300U]
**RAM:** [e.g. 8GB]
**GPU:** [e.g. NVIDIA Geforce GT 7030 2GB (Driver ver xxx.xx.xx)]

### Detailed Description
When I try to open an .MTS file it stutter to try to play.  Even if I render as a proxy it will play fine but the lip sync is off by about a second.  If I don't use a proxy and export it exports with sound sync off about one second after the video plays.

Thanks
Glenn

### Output Log
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing custom cursors (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[WARNING] QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) (:0, )
[INFO] Clip opened on track 0 (took 167 ms) (:0, )
[INFO] Clip opened on track -1 (took 168 ms) (:0, )
[WARNING] Invalid values passed to get_buffer_offset_from_frame 757 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 883 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 1388 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 2271 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 3028 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 4037 
[INFO] Clip opened on track 0 (took 155 ms) (:0, )
[INFO] Clip opened on track -1 (took 168 ms) (:0, )
[WARNING] Invalid values passed to get_buffer_offset_from_frame 173 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 284 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 342 
[ERROR] Couldn't retrieve an appropriate frame. This is an error and may mean this media is corrupt. (:0, )
[WARNING] Invalid values passed to get_buffer_offset_from_frame 430 
[INFO] Auto-recovery project saved (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )

**Comment by GlennWilk** [comment]
Sorry from putting in this problem I noticed that the stuttering and lip sync was not a problem with January Alpha 87df07e - I am not sure if this is it, but the most build has a new QT added - could this cause the problem?
Again thank you for this wonderful software.

Glenn

**Comment by itsmattkc** [comment]
This is a regression from the recent rendering pipeline rewrite in February, media "start time" and deinterlacing aren't working at the moment. Stay tuned for an upcoming caching system, I'll likely address these there.

**Comment by GlennWilk** [comment]
Thanks Glenn
