### ISSUE TITLE
Move tracks by single frame

### ISSUE THREAD

**Issue by brambox** [olive-editor/olive#770]
Thank you for the really nice editor!
I'm trying to figure how to nudge tracks left and right by 1 frame but i can't seems to find how.
Can someone tell me is it possible and how  i can do that.
Thank you!

**Comment by frink** [comment]
I don't know that we have this yet. But if Scripting is added (#806) this type of thing could become extensible and trivial.

**Comment by BrimsonBhin** [comment]
1. Enable snapping
2. Use the left/right arrowkeys on your keyboard to move the timeline scroller by individual frames
3. Select and drag desired strip to the scroller
