### ISSUE TITLE
[Feature Request] Masking & Screenshot

### ISSUE THREAD

**Issue by hyblocker** [olive-editor/olive#772]
I got mainly used to video editing in Sony Vegas Pro 11. There are currently only 2 features I wish were in Olive:
Masking, meaning that you only render a part of an image, sort of like cutting it, and is animatable.
Screenshot: Renders the current frame to a png file and adds it to the imported media.

**Comment by NathanSalapat** [comment]
While it doesn't automatically add to imported media, you can save a single frame from video by right clicking on the video preview window and select save frame as image.

**Comment by AGI-THB** [comment]
#121 

#356

**Comment by qubodup** [comment]
RE: **Screenshot: Renders the current frame to a png file and adds it to the imported media.**

this exists. right-click the sequence viewer and pick save frame as image - see https://www.youtube.com/watch?v=PsiklViJCU8

I agree that it'd be convenient to be able to have it auto-added to the project after saving.

Premiere implements the feature via a camera icon button below the sequence viewer, which opens the following window when you press it. It think it picks the folder which is set in some global settings as the place to keep project files by default.

![image](https://user-images.githubusercontent.com/18312/55739555-9024ca80-5a29-11e9-95ad-69290de63ec6.png)

It remembers the "import" option for next time you use it (globally I believe).

**Comment by itsmattkc** [comment]
As people have said, this exists. A dialog like @qubodup says is somewhere in the works (also allowing different formats and settings for the output color transform).
