### ISSUE TITLE
[Feature Request] Allow CTRL+A (select all) in Project

### ISSUE THREAD

**Issue by qubodup** [olive-editor/olive#774]
It's possible to drag-select elements in Project, for example to drag them into the timeline at the same time.

It'd be nice to be able to CTRL+A instead. Useful if you select more than visible in project at a time or if you're plain lazy and like keyboards.

Nothing critical, just something that'd be nice.

**Comment by Symbian9** [comment]
Selecting all is bad, because then actual sequence also would be selected.

Think, that there no any needs for adding `Ctrl`+`A` for "Project" window.

Instead use `LMB` in combination with `Shift` and `Ctrl`

1. Select first imported file in the "Project" window using `LMB` cluck;
2. Select last imported file using `Shift`+`LMB` click (for select all files);
3. Un-Select current sequence using `Ctrl`+`LMB` click.

**Comment by qubodup** [comment]
> Selecting all is bad

It's neither positive nor negative. It is common file manager behavior, including Premiere's "Project" interface.

Side note: this makes me realize that CTRL C and CTRL V don't work in Olive either. And now I realized that CTRL D works for sequences in Olive's project interface.

**Comment by Symbian9** [comment]
> Side note: this makes me realize that CTRL C and CTRL V don't work in Olive either.

In what windows? For example, `Ctrl`+`C/`Ctrl`+`V` work in "Timeline" window for clips.

> It is common file manager behavior, including Premiere's "Project" interface.

"Project" window IS NOT file manager you expected.

**Comment by qubodup** [comment]
> > Side note: this makes me realize that CTRL C and CTRL V don't work in Olive either.
> 
> In what windows? For example, `Ctrl`+`C`/`Ctrl`+`V` work in "Timeline" window for clips.

In project. This is only about project. Project.
![project](https://user-images.githubusercontent.com/18312/55832634-4239c080-5b16-11e9-98a8-b5a9a4a33d02.png)


> > It is common file manager behavior, including Premiere's "Project" interface.
> 
> "Project" window IS NOT file manager you expected.
Please don't should I have very sensitive hearing.

I wouldn't even mention any of this if competing to Premiere Pro wasn't a mission statement.

Also this is not important or anything. Just a nice-to-have. Not worth our time debating more, forcing devs to waste more time reading more comments.

**Comment by Symbian9** [comment]
> Just a nice-to-have.

Agree. But `Ctrl`+`A` in "Project" window should not select active sequence.
