### ISSUE TITLE
Adding effect to second clip also adds it to the previous clip

### ISSUE THREAD

**Issue by qubodup** [olive-editor/olive#777]
### System Information

**Olive version:**  Olive (March 2019 | Alpha | 6264123b)
**Operating system:** Win10 64bit

### Detailed Description

Adding effect to second clip also adds it to the previous clip

### Steps to reproduce

https://youtu.be/6RxFpOxeZ2o

**Comment by AGI-THB** [comment]
#730

**Comment by psemiletov** [comment]
Sometimes it applies also to the next clip. It seems that somehow related to the method how Olive selects clips. To avoid such thing I usually make an additional click somewhere out of the clip to deselect all possibly selected clips, and then I click on the clip that I really need to select (and apply effect or resize, etc).

**Comment by unfa** [comment]
I've had this happen to me many times.
