### ISSUE TITLE
[Feature Request] Color picking and remembering save location

### ISSUE THREAD

**Issue by hyblocker** [olive-editor/olive#781]
Color Picker like this: 
![image](https://user-images.githubusercontent.com/7695629/55854903-4beb1480-5b66-11e9-9f69-88aaa8c75f5c.png)
Pretty much, you choose a pipette and can choose from any color on screen. Its useful as you dont have to take a screenshot and open it up in an image editor, when setting the chroma key color (for example).

Remember the save location, so that you don't have to navigate everytime from the olive install directory to your save location.

**Comment by BrimsonBhin** [comment]
Olive already has pipette color picking. On set color, just click the `pick screen color` button and you got a pipette on the spot

![image](https://user-images.githubusercontent.com/40442071/55856783-30f5b180-5b20-11e9-8dd9-34fdbef1a136.png)

**Comment by itsmattkc** [comment]
Unfortunately the color dialog is platform dependent, and while most platforms provide a color picker, a lot of flavors of Linux don't.

Olive will probably need a custom color picker in the future anyway for a correctly color managed workflow.

**Comment by hyblocker** [comment]
Ok, didn't notice the color picker, but what about the save location?

**Comment by Symbian9** [comment]
> a lot of flavors of Linux don't.

FTR, color picker work as expected under *Debian 9.x Xfce*.

**Comment by oc1024** [comment]
> a lot of flavors of Linux don't.
Is this a Wayland thing? I've been through Ubuntu (Unity, KDE, MATE), OpenSUSE (Cinnamon, KDE) and Arch (GNOME, KDE, XFCE, Cinnamon) and in all of them, Qt screen color picking worked properly.

**Comment by sobotka** [comment]
>Olive will probably need a custom color picker in the future anyway for a correctly color managed workflow.

This.

Great foresight, and indeed all of the pickers out there are more or less dumpster fires.

**Comment by alcomposer** [comment]
If a user is using an sRGB monitor, but delivering in rec.2020 (and viewing footage on another monitor) would the colour picker have to show (at least visually) out of gamut/colour space values? Ie: the colour picker would clearly let the user know that the chosen value on the sRGB screen is not displayable on the sRGB screen (but obviously displayable on the rec.2020 screen)?

**Comment by sobotka** [comment]
Try to keep issues to a single one. Given that the colour picker is given more depth of nuance in #914, I've flipped this request to solely be about save location.
