### ISSUE TITLE
[Feature Request] Rotoscoping & Masking

### ISSUE THREAD

**Issue by zakaria-chahboun** [olive-editor/olive#784]
For Rotoscoping Effect - This is a video - by KDENLIVE editor [HERE ♥](https://www.youtube.com/watch?v=rPQWOGDng-Q)

![image](https://user-images.githubusercontent.com/18173275/55925525-ad15f500-5c05-11e9-9ce1-fbe50a3600cc.png)

**Comment by DaniSeeh** [comment]
Already requested and on the roadmap. #121 and #772 

If you look in projects, @itsmattkc is working on it.
