### ISSUE TITLE
[Feature Request] Playback speed

### ISSUE THREAD

**Issue by hyblocker** [olive-editor/olive#785]
I wish I can play the video with a different speed, such as playback the video as if it were sped up 2.0x times. This shouldn't affect the actual video, but only the preview. This would be useful when editing long videos, and you're checking to make sure it is all good, but don't want to rewatch the entire thing for the 100th time.

**Comment by oc1024** [comment]
There's Shuttle Left and Shuttle Right shortcuts (forgot their keys)

**Comment by itsmattkc** [comment]
As @oc1024 says. Their default keyboard shortcuts are J and L.
