### ISSUE TITLE
Recording audio never starts

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#787]
When I click the Record tool, put my start on the timeline and press start on the transport - nothing happens, the start button is still blinking red. Spacebar also doesn't help.

Can anyone reproduce this?

I don't know what happened, since it was working fine before.

**Comment by unfa** [comment]
Alright, looks like it won't work unless there's another audio clip on the timeline. Strange.
When I imported something, it worked!

**Comment by MassiminoilTrace** [comment]
I also confirm this behaviour. It can't record in an empty sequence, I need to drag a clip to the timeline first, then it will record normally.
