### ISSUE TITLE
More options for recording audio in Mono

### ISSUE THREAD

**Issue by unfa** [olive-editor/olive#788]
Recording audio is possible in Mono or Stereo - however in Mono there's more than one way to deal with the inputs.

**Please allow choosing between L or R input channel.**

Often I record in mono, but it gives me exactly the *other* mic, no the one that I wanted. And swiching cables and preamp settings around just to fix that seems silly.

**Comment by MassiminoilTrace** [comment]
If I understand correctly, you have a channel in which you record and another channel which remains empty. If this is your issue, you can fill the empty channel with the other one.
1) Put the file in the timeline
2) Add a "Fill Left/Right" audio effect to the clip.
3) Set the parameters of the effect as desired.
Now you have the same audio on both channels, so you can Pan it as you wish.
Hope it helps!

**Comment by unfa** [comment]
I know this can be fixed in post with the Audio Fill effect, but if I'm goignto record many clips and then add the effect to each one - it's going to be suboptimal. Also - I'll be storing empty audio data on disk.

It's not a big deal, but something that'd be useful.

**Comment by frink** [comment]
I agree wholeheartedly with @unfa on this. WE really need to be able to choose inputs easily. Especially for users with a lot of inputs like us audio guys, this becomes a headache quickly...

**Comment by MassiminoilTrace** [comment]
I'm not an olive developer, so I wrote a workaround that came to mind in my previous answer, hoping it could help :)
I'm also curious to see how progress goes in this area.

> If I understand correctly, you have a channel in which you record and another channel which remains empty. If this is your issue, you can fill the empty channel with the other one.
> 
>     1. Put the file in the timeline
> 
>     2. Add a "Fill Left/Right" audio effect to the clip.
> 
>     3. Set the parameters of the effect as desired.
>        Now you have the audio of one channel on both channels.
>        Hope it helps!
