### ISSUE TITLE
[Bug] Preview is sped up after export with markers

### ISSUE THREAD

**Issue by ngreve** [olive-editor/olive#791]
### System Information
**Olive version:**  Olive (March 2019 | Alpha | 6264123b)
**Source:** AUR ([olive-git](https://aur.tuna.tsinghua.edu.cn/packages/olive-git/))
**Operating system:** Arch Linux: 5.0.7-arch1-1-ARCH
**CPU:** i5-5200U
**RAM:** 8GB
**GPU:** GeForce 940M

### Detailed Description
When I export my project with a range set with the In- and Out-Markers, the preview is sped up (roughly 2x) afterwards.  
The bug seems not to appear without the markers.

### Steps to reproduce
With open project:
1. Set In- and Out Marker at any point
1. Ctrl+M to export the in/out range
2. After exporting has finished, press space bar to play preview

The preview is now sped up.
After restarting olive, everything is fine again.
 I don't know if this is important, but I don't use "Shuttle Left" or "Shuttle Right" within this process.

**Comment by AntheusMG** [comment]
Yeah, I had the same bug. But by changing once the settings, and relaunching the render, without even restarting Olive and everything seem to work.
