### ISSUE TITLE
Mac OS Playback Don't work

### ISSUE THREAD

**Issue by oliwerejder** [olive-editor/olive#792]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:**  [e.g. Git hash from window title or Help > About]
Olive (March 2019 | Alpha | 6264123)
**Source:** [e.g. AppImage, Website etc.]
MacOS .app file
**Operating system:** [e.g. Ubuntu 18.04 64-bit]
Mac OS Mojave 10.14.4
**CPU:** [e.g. Intel i5-4300U]
Processor Name:	Intel Core i5
Processor Speed:	1,8 GHz (MacBook Air)
**RAM:** [e.g. 8GB]
8GB
**GPU:** [e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx)]
  Chipset Model:	Intel HD Graphics 6000
### Detailed Description
I can't preview a song, a picture can be preview / a black preview can be previewed. but the music won't play. 
[Describe the issue you're having]
I try to playback a song with 44100 HZ which is a .mp3 in olive and it does not play the music but the timeline thing moves and directly when I pause and unpause preview I hear the music for 0.5 seconds. Adding a picture to play the music with does not solve the problem with no sound. 
### Steps to reproduce
Add a song in olive via the import feature and playback the song. 
[Describe the steps to demonstrate the issue you're reporting]
Same
### Output Log

```
[Paste output log]
```

### GDB/CDB Backtrace (for crashes)

```
[If you can reproduce this issue, try running Olive through GDB and retrieving a backtrace, then paste the backtrace here. Instructions are available in the Wiki on how to acquire this backtrace.]
```

**Comment by oliwerejder** [comment]
The song does play in iTunes without any problem at all.

**Comment by sobotka** [comment]
Is there DRM on the song by chance?

**Comment by oliwerejder** [comment]
Fixed by changing audio output on mac to built in output instead of default.
