### ISSUE TITLE
[Feature Request] Batch Processing

### ISSUE THREAD

**Issue by gomezdevelopment** [olive-editor/olive#793]
It'd be awesome to use Olive to prepare editing multiple videos so I can leave my system on overnight to chug through 6-8 files at a time. Even if it is simply a CLI shortcut, to export, that's better than forcing me to use the GUI entirely and check on it every once in a while to start the next one.

**Comment by frink** [comment]
Scripting support #806 should allow something like this...

**Comment by BrimsonBhin** [comment]
And #820 as well. Will close this one for now as there is already 2 specific issues that, if solved, can allow batch processing.
