### ISSUE TITLE
[Feature Request] Default Export options in Settings

### ISSUE THREAD

**Issue by gomezdevelopment** [olive-editor/olive#794]
I would like to be able to click "settings" and have options to customize default export options (framerate, resolution, codecs, container, bitrates, CRF, etc). Or possibly a "Set as Default" option on the export screen.

**Comment by dimitarsp** [comment]
An addition to what @gomezdevelopment mentioned it would be useful to initial optimal export templates for youtube, vimeo, etc.

**Comment by jonadem** [comment]
One "low hanging fruit" is that it remembers the CRF setting from one export to the other (of the same sequence).
