### ISSUE TITLE
New release/tag for new Fedora package

### ISSUE THREAD

**Issue by bebosudo** [olive-editor/olive#795]
Hi,
I'm packaging this software as an RPM for Fedora and RH.

Could you please create a new release/tag of olive? The latest stable is now 5 months (and ~1000 commits) old and doesn't support the cmake system.
Using the new cmake build system (available in the continuous release with commit 6264123) would make the package simpler and "more standard".

Moreover, could you please add a tar.gz file to the download assets? The tarball function provided by github doesn't have the knowledge of timestamp (https://docs.fedoraproject.org/en-US/packaging-guidelines/#_timestamps).

**Comment by bebosudo** [comment]
Hi again,
I created the RPM repo containing my build of olive-editor: https://copr.fedorainfracloud.org/coprs/bebosudo/olive-editor/
All the instructions to install it on Fedora are available in the front page.

Currently, all Fedora releases are available with the latest version of olive-editor, but RHEL/CentOS 7 should be easily added (as soon as this bug is fixed: https://bugzilla.redhat.com/show_bug.cgi?id=1511892), and other RPM-based distros could be added.
Feel free to add it to the download page of Olive if you want.

A new release/tag would be appreciated, because at the moment I'm using the source with the commit of the last continuous build.

**Comment by itsmattkc** [comment]
I'll be tagging off the current master shortly for the upcoming restructuring, that should solve this issue.

**Comment by bebosudo** [comment]
Thanks @itsmattkc, I built a new RPM with 0.1.0: https://copr.fedorainfracloud.org/coprs/bebosudo/olive-editor/build/907852/

This build is still only for fedora, because olive requires a recent cmake >= 3.9, not available in RHEL like distros.

Unfortunately I had to wipe the old builds, because they were using `ISODATEgitCOMMIT` as versioning system, and they were given precedence over 0.1.0.

If you find this useful, please mention it in the download section of the olive website :)

**Comment by DaniSeeh** [comment]
Seems like this has mostly been solved. Feel free to ask me to reopen if there are more concerns.

**Comment by bebosudo** [comment]
Hi @DaniSeeh and @itsmattkc,
is a new release available? The last one (0.1.0) was released on May 2.

**Comment by itsmattkc** [comment]
@bebosudo Not for the time being, but hopefully soon
