### ISSUE TITLE
Save frame as image does not work if project has two or more sequences

### ISSUE THREAD

**Issue by enzogian** [olive-editor/olive#801]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

Olive (March 2019 | Alpha | 6264123b)
Windows 10 64 bits

### Detailed Description

When you have a project having more than one sequence, the "save frame as image" feature does not work at all (does not export the frame)

### Steps to reproduce

Create a project, then create a second sequence, import this second sequence in the main sequence overlaying it in a higher track (using the main sequence as a background) 
then try exporting (save frame as image) any frame ...

**Comment by itsmattkc** [comment]
This works correctly for me. Can you provide more details?

**Comment by enzogian** [comment]
Hi, did you try in Windows ?
I'll try to expose the steps to reproduce it:

You have to create a sequence with a video footage then create a secondary sequence and import the first sequence into the secondary one, then go to the sequence viewer and clicking the right mouse button choose save frame as image and give a name .. the file is not saved at all ... 
hope you are able to reproduce the problem .. (but have to remind you I am using windows (unfortunately, I am one of those guys still having to use windows for other work reasons though every day transferring all my files to open source software (from InDesing to Scribus, from Illustrator to Inkscape, from Photoshop to GIMP and so on... ;) hope is not a problem ;)
cheers

**Comment by enzogian** [comment]
> This works correctly for me. Can you provide more details?

Hi, did you try in Windows ?
I'll try to expose the steps to reproduce it:

You have to create a sequence with a video footage then create a secondary sequence and import the first sequence into the secondary one, then go to the sequence viewer and clicking the right mouse button choose save frame as image and give a name .. the file is not saved at all ...
hope you are able to reproduce the problem .. (but have to remind you I am using windows (unfortunately, I am one of those guys still having to use windows for other work reasons though every day transferring all my files to open source software (from InDesing to Scribus, from Illustrator to Inkscape, from Photoshop to GIMP and so on... ;) hope is not a problem ;)
cheers

**Comment by DaniSeeh** [comment]
I'm closing most bugs 0.1.0 and before because the new infrastructure is changing so much that much of this is no longer relevant. If this bug is still relevant, Matt please reopen it.
