### ISSUE TITLE
Website Additional Page

### ISSUE THREAD

**Issue by Chadt54** [olive-editor/olive#805]
Can you guys list a feature set on your website so people can see what's all possible with Olive?

For example, like this page: https://appleseedhq.net/features.html

**Comment by frink** [comment]
It's a moving target at this point and probably will be for the rest of the year. A lot of stuff is changing rapidly. We're still trying to nail down what a professional video editing means to us. At this point the best we have is a few demo videos...

**Comment by itsmattkc** [comment]
As @frink says, Olive's feature set is an extremely nebulous concept at the moment. It's probably useful to think of it as still in the design phase, so I think maintaining a list of features for users to read would not be productive at this time.

**Comment by frink** [comment]
To wit:

I'm willing to help with website maintenance when we begin to solidify things.
