### ISSUE TITLE
Scripting Support?

### ISSUE THREAD

**Issue by Chadt54** [olive-editor/olive#806]
1) Is it possible to use python to write scripts for Olive?

If not, I'd recommend you guys start implementing that earlier rather than later since it ends up becoming too difficult to implement as the program grows larger in scale and complexity.

2) Also, is it possible to execute renders from the CLI/terminal? Being able to automate with bash scripts would be super useful as well.

3) It may also be a good idea to create a python API for modifying the project file description, so projects can be automatically generated from a script.

**Comment by frink** [comment]
As far as bash automation. Haven't tried yet... Could probably be implemented. What is your use case?

**Comment by frink** [comment]
I would suggest Lua over Python for few reasons:

1. Very easy to embed (700k)
2. Most other projects that use embedded scripting goto Lua first
3. Very easy to learn syntax (21 reserved words, 14 operators, and 10 grammar marks)
4. Trivial to add C interfaces to APIs

Other strong contenders for embedding are mruby and javascript. But those are both much more complex languages both to embed and to learn. There's a reason most all enterprise software embeds Lua...

**Comment by Chadt54** [comment]
Lua is good for a start, but Hollywood grade production software all uses Python. So, if the software ever wants to be considered professional it will need to have support for Python.

See applications that use Python as their scripting langauge:
Nuke, Hiero, Maya, 3ds Max, Blender, Houdini, Shotgun Software, DaVinci Resolve (also supports Lua), DaVinci Fusion (also supports Lua), Gaffer, Natron, Autodesk Smoke, Cinema4D, GIMP, Inkscape, Modo, MotionBuilder, Softimage, etc.

It's easier to integrate with these other applications is the developers don't need to learn Lua (I haven't seen Lua be used at all where I work, although I've played with it a bit myself)

Javascript is also ok, but only After Effects, Photoshop, and Premier use it. (I don't know of any others, although I'm sure they probably exist in this field)

**Comment by Chadt54** [comment]
> As far as bash automation. Haven't tried yet... Could probably be implemented. What is your use case?

If I have 100 projects and I want to export their timeline's video, instead of opening 100 projects and clicking "export" I could just write a bash script that could point to Olive, a project file, and an export path and export all the projects in batch. Or, alternatively, allowing for bash scripting would allow the application to be deployed to a render farm via a render farm manager.

See applications like Natron's CLI interface for the basic idea.

It could also support designating sections of a timeline to export instead of the whole timeline.

**Comment by Chadt54** [comment]
This is **THE** standard that all Hollywood production software references to make sure all the various companies software's play nice with each other, and also deploy to the most used operating systems (and their versions/distros) with as little problems as possible.

https://www.vfxplatform.com/

**Comment by frink** [comment]
Very good insights. Thank you.

**Comment by frink** [comment]
So it sounds like having a generic scripting interface that is pluggable is the real desire here.

**Comment by Chadt54** [comment]
What are you meaning by pluggable? (Just not familiar with this term in terms of how it's being used here)

Or, is it exactly what's being described here already?

**Comment by frink** [comment]
Meaning each language could be chose by the user with the same scripting object model being used by each...

**Comment by blockspacer** [comment]
cling based C++ as scripting language / hot code reload
Why? Able to run C++ script in runtime or compile it for max speed ( as in example https://github.com/derofim/cling-cmake )
Also: May be used to improve modules compile time 

> **HOT code reload**
> possible approaches:
> 
> store app state
> fix cling undo for files
> https://root-forum.cern.ch/t/loading-unloading-class-as-interpreted-macro-in-cling-multiple-times/32976/2
> 
> execute cling code to change callbacks & variables
> nested cling::Interpreter with multiple cling::MetaProcessor
> IDK how to do it, but you can create child cling::Interpreter
