### ISSUE TITLE
Moving target clip that is in between two other clips ontop of eachother and then undo-ing, crashes

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#81]
Something to do with how the clips recombine or adjust after an edit or undo.

![ScreenShot](https://user-images.githubusercontent.com/9098202/41651739-9dbe1d5e-74c4-11e8-8446-4fb809735750.PNG)

Moving the middle clip to the left so that it is on top of the other (making the left clip shorten) and then press undo. (note: it seems to work fine if you move the right most clip to the left. It has to be the clip in the middle).

Logs:
[olive - move a clip ontop of another, undo.txt](https://github.com/olive-editor/olive/files/2118782/olive.-.move.a.clip.ontop.of.another.undo.txt)
[olive - move a clip ontop of another, undo 2.txt](https://github.com/olive-editor/olive/files/2118783/olive.-.move.a.clip.ontop.of.another.undo.2.txt)

**Comment by itsmattkc** [comment]
This is somewhat expected, the undo/redo code is very unstable and will likely need a complete rewrite at some point (see #72)

**Comment by itsmattkc** [comment]
This has been patched quick n dirty in 937f714183c70a55dcdf221d7e8d17338fec07cf, but the undo system really needs rewriting because there are countless issues with it like this.
