### ISSUE TITLE
[Feature Request] Title Templates

### ISSUE THREAD

**Issue by Nordy13** [olive-editor/olive#811]
Shotcut and Openshot already has this feature, but it would be cool to see Olive with title templates. For example, the image below is showing openshot with titles to choose from.
![image](https://user-images.githubusercontent.com/49649429/56141743-0910ae80-5f63-11e9-9972-98842057e27a.png)
Just think of what it would be like if Olive had an feature like that. So that is it. Please add this feature.

**Comment by oc1024** [comment]
This could be handled by Project Imports, though a specific interface for templates could be more friendly for casual users.

**Comment by BrimsonBhin** [comment]
I do not know the worth of this FR (it pushes Olive to being a kitchen sink application).

Other Libre software can do the title templates fine.

**Comment by benrob0329** [comment]
Being able to save clips into a global bin or to a file would be far more useful while allowing the same thing.

**Comment by oc1024** [comment]
@benrob0329 That's what I said; Olive is already able to import project files.

**Comment by BrimsonBhin** [comment]
There are other applications that can do this. Olive may allow users to make more sophisticated introductions without the need for templates in the future. Will close this for now
