### ISSUE TITLE
why you should at least fix blend mode and add wipe transition (flexible) [logical request]

### ISSUE THREAD

**Issue by iqrulltion** [olive-editor/olive#813]
first thanks for Olive .. 

second after testing the alpha, i understand it is alpha .. but from my view i think adding this specific 2 features to the "alpha as soon you can" is so basic,important and logical etc .. this is not an random request i mean it .. 

1-  **wipe transition** because it is flexible of course if it supports templates so in short it is more than one transition .. 

2-  **blend mode** i think you know already what blend mode can do and how important is it you  already added it to the software .. so please just fix it

again i am talking here about basic and logical not advanced features for the near or distant future, so hope i am clear ..
thanks  .
waiting for answer ..

**Comment by NathanSalapat** [comment]
You can currently create wipes by animating one of the clips.

**Comment by DaniSeeh** [comment]
Blend modes were disabled for a specific reason. There used to be like a dozen of them. If you roll back the master to an older build you will find them. They were disabled in preparation of merging in furtherocio, because they would be incompatible.

**Comment by GUY-BBS** [comment]
Wipes are possible in Olive already, using a combination of key-frame animation and chroma-key.  This video shows some of the possibilities.  
https://vimeo.com/330188430
It is part of a video I was creating to demonstrate the potential of Olive, but I thought that I would upload the first part now to show you.  What I find remarkable that I was able to make this using a cheap laptop with only 4GB of RAM.

**Comment by iqrulltion** [comment]
> You can currently create wipes by animating one of the clips.
> Wipes are possible in Olive already, using a combination of key-frame animation and chroma-key.
 
**you can even do more advanced transitions as long you have keyframes**  **i am talking about built-in 
 wipe transition** that support templates by one click and that might save time if you deal with many or even less clips or pics whatever  .. look at kdenlive for example to see what i am talking about for this specific point  .. please understand that we are talking here about basics .. even who put a dislike it is your right but please just ask before you act ..

**Comment by iqrulltion** [comment]
> Blend modes were disabled for a specific reason. There used to be like a dozen of them

that is why i said **fix** it not adding it (with Priority in this period)  **because it is a request it is not an order** it is a free and open software .. and that is why it called request..

**Comment by itsmattkc** [comment]
I think it's exactly the importance of blending modes that requires us to get it right. "Fixing" blending modes now means writing code that will be completely unusable within a month. I apologize that it's taking time, but I promise you they're coming.

**Comment by iqrulltion** [comment]
Thanks , no problem!  as i said literally  " as soon you can " i did not say now if you noticed .. it was just some kind of Proposal to arrange priority (as start)  .. and please do not forget the wipe transitions with ( templates and controls) see kdenlive transitions to see that ( _if you did not see it is free open source so no harm)_
done closed.
