### ISSUE TITLE
System keyboard layout is not used with AppImage on Wayland

### ISSUE THREAD

**Issue by jooert** [olive-editor/olive#816]
### System Information

**Olive version:**  8cef5ce
**Source:** AppImage
**Operating system:** Arch Linux

### Detailed Description

When using Olive with a German keyboard layout, I still have to use keys for shortcuts as they were on an English keyboard. For example, `Z` and `Y` are switched on a German keyboard in comparison to an English one. So to use the undo shortcut with a German keyboard layout I actually have to press `Ctrl` + `Y` (which is where `Z` is with an English keyboard layout) instead of `Ctrl`+ `Z` (as it says in the menu).

**Comment by Simran-B** [comment]
On Windows 10 with Olive version 56680ff4 Ctrl+Z works fine and the menu displays Ctrl+Z. Perhaps a Linux only problem?

**Comment by jooert** [comment]
This seems to affect not only shortcuts but keyboard input in general: Typing text in any text input field also uses an English keyboard layout. FWIW, this is on Gnome/Wayland 3.32.1.

**Comment by AGI-THB** [comment]
I don't have this problem on Linux Mint with a german layout. 
I use the Appimage, too

**Comment by jooert** [comment]
So, after further investigation, this seems to be related to me running a Gnome on Wayland session. When I log into a "Gnome on Xorg" session, everything works fine. There seem to be several other people having similar problems with other applications (e.g. keepassxreboot/keepassxc#1293 or LibrePCB/LibrePCB#360; the first one is also running an AppImage). Interestingly, it works fine, too, when I build Olive myself instead of using the AppImage; so the issue seems to be related to the packaging of that (see also probonopd/linuxdeployqt#189).

@AGI-THB Are you running on Wayland or X11?

**Comment by AGI-THB** [comment]
X11

**Comment by itsmattkc** [comment]
I don't think the AppImage packages any Wayland plugins at all. Would installing QtWayland address this?

**Comment by jooert** [comment]
Do you mean in the AppImage? I think so, but I'm not sure.
