### ISSUE TITLE
PPA not updating

### ISSUE THREAD

**Issue by NathanSalapat** [olive-editor/olive#818]
It looks like the build system for the PPA's isn't working. I have the PPA added on my system and the lastest version shows 2019-03-31. On Launchpad it looks like most builds have been failing recently.
https://launchpad.net/~olive-editor/+archive/ubuntu/olive-editor/+builds?build_text=&build_state=all

I'm running Linux Mint 19.1

**Comment by itsmattkc** [comment]
This is a known issue. The PPA (using debhelper) has automatically opted for the cmake script instead of the qmake script which seems to be throwing an error. It hasn't been a priority because `master` hasn't received any major updates lately, but maybe @eszlari knows what's going wrong from the log.

**Comment by eszlari** [comment]
Please merge PR https://github.com/olive-editor/olive/pull/821 and let's if this fixes it.

**Comment by itsmattkc** [comment]
@eszlari No change. Unfortunately the buildlog is not very descriptive: https://launchpadlibrarian.net/419710908/buildlog_ubuntu-bionic-i386.olive-editor_201904172354-35e0cb4+1039~ubuntu18.04.1_BUILDING.txt.gz

**Comment by eszlari** [comment]
I think, I found it in the log:
```
CMake Error at /usr/lib/i386-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:22 (find_package)


-- Configuring incomplete, errors occurred!
```
Apparently, `qttools5-dev` needs to be added to `debian/control`.

**Comment by NathanSalapat** [comment]
PPA is updating! Just installed the latest version.
Thank you for getting this fixed.
