### ISSUE TITLE
Question: Proxy in Exported Video?

### ISSUE THREAD

**Issue by Simon-Laux** [olive-editor/olive#819]
When I export my project with a video, for which I generated a proxy, the video is exported in the low proxy quality.
I expected export/render would use the original file rather than the proxy in the exported video.
**Is this a bug or intentional behavior?**

Olive Version: 56680ff AppImage 64bit

**Comment by itsmattkc** [comment]
Neither, it's more of an incomplete feature. This behavior has been addressed in the soon-to-be-merged `furtherocio` branch.
