### ISSUE TITLE
Dots don't render in 'Text' object

### ISSUE THREAD

**Issue by tree786** [olive-editor/olive#823]
### System Information

**Olive version:**  64-bit download for Windows from www.olivevideoeditor.org
**Source:** Website
**Operating system:** Win 10 64-bit

### Detailed Description
I don't know if a similar issue has been raised here before.
Dots (**...**) don't show up in `Text` objects (I've attached an image which should clarify the issue).

![Untitled](https://user-images.githubusercontent.com/40580296/56298162-956cce00-6129-11e9-8eee-ab1aa1f2042a.png)

### Steps to reproduce

1. Add a `Text` object
2. Add dots (...) as input to the text field

**Comment by itsmattkc** [comment]
Use a different font.
