### ISSUE TITLE
Allow copying and pasting keyframes

### ISSUE THREAD

**Issue by iqrulltion** [olive-editor/olive#825]
The best part of this software is the compositing part , it is a video editor but its compositing part is advanced, I was worried that i will not find "anchor point "control" but i found it , so please just do not give up on the compositing part and keyframe what can be keyframed  ..

advanced feature request for the near or distant future i can wait for it ..

as start i will start with keyframes (on the timeline)
1-copy, paste the keyframes (_on the same line , so it just copying the value of effect and changes the time of "start and end" on the timeline due to the timeline location you copied on ,  just ignore that you know what i am talking about_) and  reverse the keyframes  (_that will save time_ (_in and out_) ) .. but notice you can ignore that it can be done manually easily anyway just focus on the copying and pasting it is the main process .. 

2-  motion blur for animations and movements as option .. i had to edit the" second and merge the first"  just to make a stronger example or guideline or whatever because this post is not about only specific feature ..

3- i am leaving the third and what following to your imagination and ability to make the whole compositing part goes far as can it be ..

thanks.

**Comment by bobpatraque** [comment]
I am also a big Keyframe lover... I hope your node work will be as "user friendly" as the actual keyframe system !

**Comment by BrimsonBhin** [comment]
The 2nd request was addressed in #634

**Comment by iqrulltion** [comment]
> The 2nd request was addressed in #634
thanks for linking and the notice . i did not see it , and does not matter if the second repeated because i added just for example and made clear that is " post " is not asking for specific feature as it is about focus and not giving up on developing and upgrading  the whole compositing part ..
