### ISSUE TITLE
[Feature Request] Auto Build OpenColorIO with CMake

### ISSUE THREAD

**Issue by DeveloperPaul123** [olive-editor/olive#826]
It would be good to auto build OpenColorIO via CMake to ensure reliable and repeatable builds. To that end, it would be good to know how OpenColorIO _should_ be built (i.e. which options should be turned on/off so that the proper flags can be set via CMake before building. 

There are multiple approaches to accomplish this:
1. Use [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html) via CMake. This will create a custom target to build the project dependency.
2. Use [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html). This will add the entire OpenColorIO project to `olive` and everything will be built together at once. The advantage with this is that you'll have direct control over OpenColorIO options via cmake since all it's options will be in the `CMakeCache.txt`. You'll also be able to directly use any targets that the OpenColorIO project has.

**Comment by itsmattkc** [comment]
This is probably a good idea considering the correct version of OCIO is not always available everywhere

**Comment by sobotka** [comment]
I believe OCIO is currently resting at v1.1.1, and it's worth keeping on the v1.x branch until the dust settles on the rather awesome v2 branch. The v2 branch brings in some _significant_ upgrades to the GPU implementation, however, so perhaps we can work in a hybrid state once things get more into ship shape around these parts.

**Comment by DeveloperPaul123** [comment]
Is there a preference over the approaches to this? (FetchContent versus ExternalProject)

**Comment by sobotka** [comment]
I’d wager if you used your experience to arrive at a decent solution, Matt would like merge.

I know from experience that OCIO can be a bit of a wobbling house of cards to build on some configurations because of the internal vs external YAML. Having a streamlined CMake would probably be a great addition here, given OCIO is no longer an optional component.

**Comment by DeveloperPaul123** [comment]
@sobotka Ok that's fair enough. I've used both approaches in a variety of projects. FetchContent has the advantage that you get to build the library project as part of the main project, but it also exposes the various CMake flags for OpenColorIO to developers when building `olive` (unless you force the options in CMake). 

And yes, if we wanted to support an external build of OpenColorIO that the user already has, we'd have to have a file module for OpenColorIO. One approach would be to add an option like `OLIVE_USE_EXTERNAL_OCIO` to indicate that the dev would like to build with an external OpenColorIO build.
