### ISSUE TITLE
add rendering formate for Youtube videos.

### ISSUE THREAD

**Issue by gireesanmkg** [olive-editor/olive#828]
[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear this template.]

### System Information

**Olive version:**  [Olive(january2019 | alpha)]
**Source:** [Website]
**Operating system:** [Ubuntu 18.04 64-bit]
**CPU:** [e.g. Intel i3
**RAM:** [e.g. 8GB]
**GPU:** [e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx)]

### Detailed Description

please add a rendering for youtube videos.

### Steps to reproduce

[Describe the steps to demonstrate the issue you're reporting]

### Output Log

```
[Paste output log]
```

### GDB/CDB Backtrace (for crashes)

```
[If you can reproduce this issue, try running Olive through GDB and retrieving a backtrace, then paste the backtrace here. Instructions are available in the Wiki on how to acquire this backtrace.]
```

**Comment by AGI-THB** [comment]
why are you requesting the same feature twice?

#829

**Comment by itsmattkc** [comment]
It wouldn't be any different from exporting normally. The export parameters are automatically set to your sequence's dimensions with a sane quality level. What difference would a YouTube preset make?

**Comment by gireesanmkg** [comment]
Sorry for that.i am new to github.And actually I don't know what to do...
In openshot there is a direct rendering profile for YouTube videos. I wish
to see that feature in olive too. A am a student from India so,if anything
hurt you please pardon me. Thanks for your reply.

**Comment by dimitarsp** [comment]
Just to chip in, I've exported a 30 minute video at settings 16 of quality that I am unable to play on my computer and it takes 15 minutes to process once uploaded to youtube. The file size is about 280mb. It would be useful to have youtube optimized settings
