### ISSUE TITLE
add title templets

### ISSUE THREAD

**Issue by gireesanmkg** [olive-editor/olive#829]
please add title templets like in openshot

**Comment by gireesanmkg** [comment]
add more transitional effects for better experience

**Comment by gireesanmkg** [comment]
need rendering profile for youtube videos

**Comment by gireesanmkg** [comment]
key board shorcuts for editing..

**Comment by AGI-THB** [comment]
#811 
#813
There are already shortcuts for editing...
Use the search function next time.

**Comment by itsmattkc** [comment]
What @AGI-THB said, most of your requests have already been requested or Olive already does them.
