### ISSUE TITLE
Audio Level Meter Freezes Sometimes

### ISSUE THREAD

**Issue by benrob0329** [olive-editor/olive#830]
### System Information

**Olive version:**  35e0cb4
**Source:** Appimage
**Operating system:** Debian 9
**CPU:** Intel i5930k
**RAM:** 16gb
**GPU:** Nvidia 980ti
### Detailed Description

Occasionally the audio level meter will freeze, resulting in whatever the last working audio levels to be to be "frozen" onto it. Cause is currently unknown (will continue to investigate).

**Comment by AGI-THB** [comment]
Can you use the search function next time? Thanks.

#691

**Comment by benrob0329** [comment]
Would seen I did not search hard enough, sorry!
