### ISSUE TITLE
360 VR video contribution

### ISSUE THREAD

**Issue by MassiminoilTrace** [olive-editor/olive#832]
My goal is to let edit 360 equirectangular videos.
To cut them, there's no need of other tools.
I am creating a shader effect to change the default viewing direction, really useful during editing this type of video.
Here's my olive shader.
https://github.com/MassiminoilTrace/olivevideoeditor-VR-360-rotation

I write this here to ask a question.
Are you interested to put this in the default effects or in the community developed ones?
Is there a place where all this external repos are collected?

I could license this under GPLv3, so that it's compatible with Olive's license. I only would like to have my name in the file as I am the original author. I'm now searching for license details to find the one that best suits my case.

Hope it could be useful!
Thank for your work and your amazing software!

**Comment by sobotka** [comment]
Not colour managed.

**Comment by MassiminoilTrace** [comment]
Just to clarify, I only am a student, so there could be many errors :)
Feel free to give me tips to improve if you have idea!

**Comment by KristijanZic** [comment]
I'm working a lot with 360 panoramic images and videos. I'd find any 360 video editing features very very useful and I'm sure others would as well since we are headed fast into 360 video age.

**Comment by MassiminoilTrace** [comment]
Here's a small demo of the current state if you're interested https://youtu.be/ygNV69hfs1U

**Comment by KristijanZic** [comment]
It's keyframable too :DD Oh MAN! :DDDD
That's a real feature :D
One day maybe there could be a stabilisation effect for the shaky footage so that the projection is moving position but the view appears to stay in place.

It's very nice job man!

**Comment by AGI-THB** [comment]
Looks good. 
The Repo is here https://github.com/cgvirus/Olive-Editor-Community-Effects
Also try to get colormanagement right, if you can.
thanks.

**Comment by MassiminoilTrace** [comment]
Thank you for the repo!
I have not so much knowledge in the color management area. Could you give some tips to point me in the right direction so I can try to study and implement it?

> Looks good.
> The Repo is here https://github.com/cgvirus/Olive-Editor-Community-Effects
> Also try to get colormanagement right, if you can.
> thanks.

**Comment by BrimsonBhin** [comment]
Will close this issue for now. Feel free to make changes in your effect and link it in the wiki if you want
