### ISSUE TITLE
[Feature Request] Seperate Window

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#834]
Hello, can you make this area a seperate dock because it takes up alot of space and theres no way of Moving it seperately
![Window](https://user-images.githubusercontent.com/37266538/56372182-ccf97a00-61fe-11e9-89b8-a099982b1b09.PNG)

**Comment by itsmattkc** [comment]
You can shrink it down using the splitter to the left. It's a fairly integral part of that panel so I don't think separating is a good idea.
