### ISSUE TITLE
Add "Render > CAM Overlay Display" effect

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#835]
Add "CAM Overlay Display" ("Screen Overlay", "HUD") effect 

- Templates;
- Customized animated elements/indicators (connected to sequence properties & time position);
  - Volume indicator;
- Other useful features.

![pic.1](https://cdn140.picsart.com/274583463011211.png?r1024x1024)

![pic.2](https://images.pond5.com/factory-camcorder-rec-overlay-footage-048875603_iconl.jpeg)

**Comment by oc1024** [comment]
Project/Image imports can already do this, why make effect specifically for it?

**Comment by Symbian9** [comment]
Because "CAM Overlay" is common video effect.

**Comment by benrob0329** [comment]
That's not an excuse for something that is also commonly done using an image, heck you even posted one!

**Comment by elsandosgrande** [comment]
It would only really be worth it when you want an animated one, but even so, it's not something to ask for this early in the development process. itsmattkc might start looking into effects like these after Olive reaches beta, but I bet that somebody will have made this effect as some sort of plugin by the time that happens (I'm not sure about the details, but, from what I understand, support for plugins or something similar is being worked on at the moment).

**Comment by itsmattkc** [comment]
I don't think Olive is the right program for this, this is a very specific preset with a very specific style and I think most Olive users would probably prefer to make their own overlay that suited their needs if they needed such a thing.
