### ISSUE TITLE
Add "Render > Geometric Shapes" effect

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#836]
Add effect for create basic geometric shapes:

- Line (length + width + angle);
- Circle (radius; filled/unfilled + border width);
- Rectangle (height + width; filled/unfilled + border width);
- etc.

**Comment by BrimsonBhin** [comment]
This idea should be shelved until Olive completes its roadmap on how effects get done.

**Comment by Simran-B** [comment]
SVG as mask would be possible solution, maybe even with animation support?

**Comment by Symbian9** [comment]
> SVG as mask would be possible solution

For SVG support we has anotger request:

- https://github.com/olive-editor/olive/issues/458

But for creating & editing SVG we need external vector editor.

General idea of "Geometric Shapes" is something like *'built-in basic vector editor'*.

**Comment by Simran-B** [comment]
Well, Olive could ship with some pre-made SVGs. But if you want to be able to define e.g. how many edges you want in a star-like shape then SVG wouldn't be the best option perhaps.

**Comment by Symbian9** [comment]
FTR, what you think about implementing "SVG Native" for this feature?

- https://medium.com/adobetech/svg-native-open-sourcing-svg-native-viewer-988125328a07

> ...
>
> ***SVG Native*** is an upcoming W3C specification and a narrow collection of the most commonly used primitives of SVG. This subset brings vector graphics to native applications and draws resolution independent icons or sharp color fonts like for OpenType-SVG fonts.
> 
> ...
>
> ### The subset in SVG Native
>
> The new subset in SVG Native consists of the following categories and elements:
> 
> - Shapes: `<circle>`, `<ellipse>`, `<rect>`, `<path>`, `<polygon>`, `<polyline>`, `<line>`
> - Groups: `<defs>`, `<g>`
> - Information: `<desc>`, `<title>`
> - Gradients: `<linearGradient>`, `<radialGradient>`, `<stop>`
> - Clipping: `<clipPath>` (with limitations)
> 
> ...

GitHub repo:

- https://github.com/adobe/svg-native-viewer

**Comment by Simran-B** [comment]
SVG Native seems like a good candidate for the proposed feature - nothing really fancy is needed here. However, as a user you probably want to tweak the shape inside of Olive, which would have to generate SVG code on the fly then I guess? At least from in my current understanding of SVG Native, it isn't an API for generating SVGs, but rather a parser and rasterizer mainly for UIs.
