### ISSUE TITLE
Add Solus OS to the supported platforms

### ISSUE THREAD

**Issue by Neobrand** [olive-editor/olive#839]
I'm using Solus OS, which is a 64-bits Linux distribution, and your soft works fine on it. It would be great if you could add olive to the package manager of Solus OS named eopkg.

**Comment by itsmattkc** [comment]
Generally I leave these up to PRs or other people to manage. There are so many Linux distributions that setting up and supporting each one would become a huge burden on development time. Feel free to set it up and make PRs if necessary.

**Comment by oc1024** [comment]
Pretty much what MattKC said, this is usually up to distro maintainers. For example, an Arch Linux user is maintaining an Olive package.

**Comment by MikeWallaceDev** [comment]
Another Solus user here. Then could you please update the snap?
