### ISSUE TITLE
[Feature Request] Auto Ripple

### ISSUE THREAD

**Issue by Masken8** [olive-editor/olive#840]
As someone coming from Vegas Movie Studio, I'm used to Automatic Ripple, Olive lacks this, therefore, I wrote this feature request. Please add this.

**Comment by alcomposer** [comment]
Have you tried `Ripple Delete`?
![ripple_delete](https://user-images.githubusercontent.com/12004932/56480869-45ac4f00-64fb-11e9-83e2-9c4a9e83f4ae.png)

If so then this feature is already in Olive, please close this issue.

**Comment by Masken8** [comment]
Does it do it automatically tho?

**Comment by Traxalter** [comment]
um

**Comment by DoctorAK** [comment]
I use Vegas too,the auto ripple feature is very awesome. Davinci resolve also has this feature . I hope olive will add this feature.  don't learn from PR ,its logic is  too complex. Btw,The interface could be more beautiful.

**Comment by DoctorAK** [comment]
Not ripple delete but trim and ripple at the same time .
The Q and W shortcut has an issue.When I q to trim the front end,it did a good job,but if I put the playhead at the front and q ,it will cut one frame, The front end is the front end,don't cut it please, You guys can reference by Vegas and Davinci,their Trim tools are good to use .If I put the playhead at the backend ,the viewer display nothing,but I want it should be the last frame ,Please.
