### ISSUE TITLE
[Feature Request] Edit Text In Preview

### ISSUE THREAD

**Issue by Masken8** [olive-editor/olive#841]
A lot of video editors let you double click on the text in the preview and edit the contents(text) of it. I think this would be nice to have in Olive that way you see where the text will go.

Edit:
Preview = Sequence Viewer

**Comment by BrimsonBhin** [comment]
This looks like a lot of work for little benefit

**Comment by Masken8** [comment]
Yeah, it kinda does.

**Comment by itsmattkc** [comment]
I think the current text effect(s) in general need some overhauling so they're easier to develop. Expect something along those lines soon (check Projects tab)

**Comment by CodigoCristo** [comment]
.Edit text directly on screen
![image](https://user-images.githubusercontent.com/34531165/65833760-3810a780-e299-11e9-91f4-aa03f8ae890f.png)
