### ISSUE TITLE
olive development road map ..

### ISSUE THREAD

**Issue by iqrulltion** [olive-editor/olive#842]
>And new features are being added every day. Even if Olive is missing something you need, come back in a month or two and it's possible it will have been implemented.

that what you can  see  on the olive site , and  you can see lot of features requests  here..
so i am thinking how you handle all this requests and do you write it on paper or what .. so to make that efficient and make waiting easier .. there is a solution but it is not my idea i took it from the free and open 
 source software **GIMP**! https://wiki.gimp.org/wiki/Roadmap ..
so i think most if not all olive users want you to take this step .. and i might personally suggest and encourage open source softwares to take this step with start with  "olive" .. 

but to be logical and reasonable : i do not know if you ready to take this step now , but at least you should take that in mind With a desire to do when you can and when that happens do not  skimp on users with info can make waiting easier ..  

sub-note : i am not sure what you mean with " access to developer blogs and detailed updates for Olive's development " on patreon, i think you are taking about daily ..  if the road map does not contradict with that .. please take that in mine ..

**Comment by itsmattkc** [comment]
Check the GitHub projects page for a basic version of this. The main priority is the core rewrite which will need to be done before other features can be considered as part of the design. In the future, there will probably be a more explicit roadmap elsewhere but for now that'll be where to find it.

**Comment by iqrulltion** [comment]
done , thanks ..
closed.
