### ISSUE TITLE
qmake error Library 'libatomic' is not defined

### ISSUE THREAD

**Issue by grash54** [olive-editor/olive#845]
### System Information
**Olive version:**  Latest git
**Source:** latest git
**Operating system:** Ubuntu 18.04 64-bit
**CPU:** Intel i7-8700k
**RAM:** 16GB]
**GPU:** NVIDIA Geforce GTX 1018 Ti 11 GB (Driver ver 418.56-0ubuntu0~gpu18.04.1)

### Detailed Description
When executing qmake the following error occurs:
Project ERROR: Library 'libatomic' is not defined.

### Steps to reproduce
Go into olive directory and execute qmake

### Output Log
Can't find any logs

[Paste output log]
Can't find any logs

### GDB/CDB Backtrace (for crashes)
Not running trying to build

**Comment by itsmattkc** [comment]
Apparently a Qt/KDE bug: https://forum.qt.io/topic/99507/project-error-library-libatomic-is-not-defined
