### ISSUE TITLE
[UI] Auto Update

### ISSUE THREAD

**Issue by Masken8** [olive-editor/olive#848]
Auto Update doesn't seem to be available. This would be a very nice thing to have or even just a way to check for new releases and download them if you'd like with an option to download the latest continuous build if you so desire. This would take away the time needed to open your browser, go to the site and download the latest release.

**Comment by elsandosgrande** [comment]
I already asked this in ticket #461. This is a duplicate.

**Comment by Masken8** [comment]
@elsandosgrande that isn't possible on windows tho

**Comment by DaniSeeh** [comment]
Olive is Alpha. You may think you want auto update right now, but the first time it updates and breaks your project file (this happened to me once already when I updated) you are going to regret it.

This is a feature for when Olive reaches maturity and might, if Matt chooses, switch from a rolling release method to distinct versions.

Right now, bleeding edge Olive builds are dangerous. Use at your own risk.
