### ISSUE TITLE
Left panel to control status of tracks

### ISSUE THREAD

**Issue by enzogian** [olive-editor/olive#849]
Hi there,

Talking about interface, I was wondering about making the audio levels at the right of the timeline a bit slimmer so leaving some space to make (slim either) an area in which you can control tracks properties like on off audio, or show if is active etc ... see attached draft for visualization ;)
PS: sorry for the low quality draft but is was mainly to express the idea of where the space for such a strip of controls (at the left of each track, could be taken (reducing the audio level bars)
what do you think ? (I know you have disable and enable in the right click button on the track but having some indicators at left might help to verify the status of certain things like if is turned off or on audio, video effects etc.. or any other feature you consider is pertinent to the general status of the track in the timeline.. 

Hope it makes sense ;)
Thanks for any feedback might want to add to this suggestion ... 
![Untitled-1](https://user-images.githubusercontent.com/43185336/56425470-c4637b00-62b4-11e9-8b71-fc4fbf7f85a5.jpg)

**Comment by benrob0329** [comment]
I honestly cannot tell what's being suggested here.

Please clearly explain exactly what you'd like changed, then the explanation for why in a separate sentence.

**Comment by enzogian** [comment]
> I honestly cannot tell what's being suggested here.
> 
> Please clearly explain exactly what you'd like changed, then the explanation for why in a separate sentence.

oops, sorry I recon the explanation has been quite messy. I'll try my best then, but still quite hard for me to explain...

**Suggested change:**
a small change in the interface by adding a space to the left in order to insert kind of controls or indicators to show the status (on/off) of certain features of the track like audio, effects, active track (where things would be pasted etc..

I can see the image I've attached is not clear either (sorry for that), but was trying to show where the space for such a thin "strip" to display those controls could be taken from. I was thinking that the right audio bars could be less thick (that's why the right audio bars has been signed with a minus symbol (where space could be taken from by reducing the thickness of those bars) and the area at the left is signed with the plus symbol to shows the space could be gained in order to add such a strip of controls or whatever should be called...

**Why do I suggest such a change in the interface ?**
Sometimes users are not totally aware of the status of the track, lets say when audio of a particular track is off or on, or if you want to turn off all effects in that track etc.. and even to know what track is active when pasting a cut element . I think an extra strip (like having some controls or indicators to show such a kind of status) might be useful.

PS: not sure if this is quite a subjective perception for being using Premiere (perhaps that's why I keep looking for those indicators at the left of the tracks' timeline (?)  but I want to make clear the reason I expose it here is to see if some other users might experience the need or convenience for displaying these controls .. I expose it mainly to discuss such a thing if others find it as something needed or convenient to have (perhaps could be to show the status of other features I have not considered either ? and not those I've mentioned ? in my case for the sort of videos I do those aspects I've mentioned make the job but perhaps others would like it display other things (not sure and that's why I was thinking it would be great having some feedback so don't take it as straight feature request 
(hope it makes sense)

**Comment by DaniSeeh** [comment]
This is already being addressed in the nodes branch. It required a significant timeline rewrite. Repeat of #420

**Comment by itsmattkc** [comment]
Addressed in upcoming node restructure.
