### ISSUE TITLE
"Procedural" animation modifier

### ISSUE THREAD

**Issue by tree786** [olive-editor/olive#850]
Feature request
I don't know if this (or a similar request) has been raised before.

It would be really handy to have  a way of "procedurally" animating keyframed properties. I've used the Blender VSE, and a way of achieving this would be to apply a 'Noise' modifier (highlighted by the green box, see the attached img) to the animated property under question. Implementing something similar to this would allow effects such as camera shake, film grain (varying contracts/brightness), light dispersion 'glitchy' effects, and so on. 

![noise_modif](https://user-images.githubusercontent.com/40580296/56428674-1eb20b00-62b8-11e9-9abe-88740633aa26.png)

**Comment by benrob0329** [comment]
This is very much dependant on the upcoming nodes UI, so should wait until that is usable.

**Comment by oc1024** [comment]
@benrob0329 The fact it's done by Blender doesn't mean it requires nodes to be useful. Having this sort of thing + the stock transform effect would simplify Olive by eliminating the need for a separate shake effect.

**Comment by benrob0329** [comment]
I'm saying that implementing this will have to wait, as the nodes branch is a huge redactor. Plus this sort of data routing is exactly where nodes shine above other data abstractions.

**Comment by itsmattkc** [comment]
I also think this is a thing to look at nodes for, if there's a random generator node, sine node, etc. that can be plugged into the values, that largely addresses this request.

**Comment by oc1024** [comment]
Maybe also add simple operation nodes, like Add, Subtract, Interpolation?
Could partially address #472.

**Comment by itsmattkc** [comment]
@oc1024 Precisely the plan, it also addresses blend modes in the process.
