### ISSUE TITLE
[Bug] Keyframes do not scroll properly

### ISSUE THREAD

**Issue by ngreve** [olive-editor/olive#851]
### System Information

**Olive version:**  Olive (March 2019 | Alpha | 35e0cb4f)
**Source:** AUR ([olive-git](https://aur.tuna.tsinghua.edu.cn/packages/olive-git/))
**Operating system:** Arch Linux: 5.0.7-arch1-1-ARCH
**CPU:** i5-5200U
**RAM:** 8GB
**GPU:** GeForce 940M

### Detailed Description

When scrolling in the effects window, the keyframes to not match the scroll position of the effects.
Doesn't matter if you use the mouse wheel or the scrollbar.
But when resizing the effects window, the keyframes are snapping to the correct position.

![keyframes](https://user-images.githubusercontent.com/18660100/56432046-4c08b400-62cc-11e9-889d-dc5f89467fc8.gif)

Keyframes should always be next to the corresponding effect.

**Comment by DaniSeeh** [comment]
I'm not able to recreate this bug in 0ac9dd9, which is also from the AUR. If it is still present in the most recent continuous build we will reopen. Please comment if so.
