### ISSUE TITLE
[Bug] Keyframe appears on wrong position / shows wrong value

### ISSUE THREAD

**Issue by ngreve** [olive-editor/olive#859]
### System Information

**Olive version:**  Olive (March 2019 | Alpha | 35e0cb4f)
**Source:** AUR ([olive-git](https://aur.tuna.tsinghua.edu.cn/packages/olive-git/))
**Operating system:** Arch Linux: 5.0.7-arch1-1-ARCH
**CPU:** i5-5200U
**RAM:** 8GB
**GPU:** GeForce 940M

### Detailed Description

When setting the positioning marker and changing an effect, the keyframes appears on the wrong position.
Furthermore, the displayed values in the effect window do not match the value shown by the graph. 

**[Update / Edit ]:** It seems that this is happening primarily when keyframes are used on videos. Keyframes on e.g. Title elements seem to work fine.

### Steps to reproduce
![keyframes1](https://user-images.githubusercontent.com/18660100/56455546-c3d3ee80-635f-11e9-9786-513d54c86813.gif)

**Comment by DaniSeeh** [comment]
I wasn't able to recreate this on 0ac9dd9, please comment if it is still present on the most recent continuous build or 0.1.0 and we will reopen.

**Comment by jarro2783** [comment]
I'm seeing this on the latest master for 0.2 007b9f287cad7d3b0785e8aeb242b3293f9e9b44.

**Comment by jarro2783** [comment]
I did a bit of fiddling, it reproduces for me on "Video 2", but doesn't seem to do it for tracks 1 or 3. If I add an Orthographic Matrix to a video track that doesn't start at frame zero, and then just add a keyframe to any of the parameters, it seems to be off by the frame that the video track starts on.
Example, if the video on track 2 starts at 3 seconds, the keyframe is off by 3 seconds.
