### ISSUE TITLE
Graph Editor Bug

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#860]
### System Information

**Olive version:**  [56e2c097]

**Source:** [zip from github]

**Operating system:** [Windows 10 64-bit]

**CPU:** [Intel i5-6400]

**RAM:** [4GB]

**GPU:** [Intel Graphics HD 530 128MB(Latest Drivers)]

### Detailed Description

[The graph editor window looks broken]

### Steps to reproduce

[Just show the graph editor]

### Output Log

```
[Nothing]
```

### GDB/CDB Backtrace (for crashes)

```
[Nothing]
```

### Screenshot
![Screenshot (89)](https://user-images.githubusercontent.com/37266538/56459954-8a20d900-639b-11e9-886f-6713036b878d.png)

**Comment by NathanSalapat** [comment]
The graph editor won't show anything if you don't have any keyframes selected. After you add keyframes to  a property the property values should show up in the bottom along with the clips name, effect, and 'sub effect'
![graph editor](https://user-images.githubusercontent.com/8930456/56460323-ae15f780-6366-11e9-854c-0970533f93fb.png)

**Comment by MrTeeXD** [comment]
Thats not what i meant, the window border around the Graph Editor is the issue, its suppose to have the Windows Border around

**Comment by BrimsonBhin** [comment]
It's because you locked the panels.

**Comment by MrTeeXD** [comment]
I see, closing this issue right now
