### ISSUE TITLE
[Feature Request] Change default duration of images

### ISSUE THREAD

**Issue by 32-bit-link** [olive-editor/olive#861]
[**Copied from my Reddit post read it here**](https://www.reddit.com/r/olive/comments/bdzuy2/change_the_default_duration_of_an_image/)

So I'm making a video in the olive video editor and I have a batch of images in it but I found that the default (around 6 seconds) to short so I decided to extend them to 15 seconds but then all the images would overlap so how would I be able to change the default duration of an image to 15 seconds?

The reason I think this would be useful to Olive is that whenever I put a batch of images into olive I would need them to be longer as 6 seconds is too short.

**Comment by DaniSeeh** [comment]
You want to be able to set the default image length for a project?

**Comment by Simran-B** [comment]
An adjustable default for image duration would be useful, but stretching the entire selection while maintaining relative lengths would also work.

**Comment by 32-bit-link** [comment]
> You want to be able to set the default image length for a project?

Yes because 6 seconds is too short or too long in most cases

**Comment by Simran-B** [comment]
BTW. creating a nested sequence and changing its duration (40% speed) doesn't stretch each image to 15 seconds. It just adds black at the end.

**Comment by freshstudio** [comment]
I'm working on it. Would you like to set the default duration in frames or in a HH:mm:ss.zzz time format?

**Comment by Simran-B** [comment]
Rather the latter, as the typical use case will be users who want n seconds duration as default. With frames you would have to calculate the duration based on the sequence's FPS...

A label next to an input box for the duration in frames could display the duration in seconds, but then the user would have to tweak the value until it matches the desired duration.

![image](https://user-images.githubusercontent.com/7819991/56577937-9d66bb00-65cc-11e9-8c96-95d97ffc6108.png)

The other way around, displaying the duration in frames next to the input box doesn't seem very useful to me...

![image](https://user-images.githubusercontent.com/7819991/56577722-0437a480-65cc-11e9-88d6-1c197ac2f480.png)

However, I wouldn't mind if a tooltip contained this information. Seems like a reasonable idea in general, to display the value in another format on demand should anyone be interested in it.

![image](https://user-images.githubusercontent.com/7819991/56578641-6a252b80-65ce-11e9-81a5-9821e345a75e.png)

**Comment by 32-bit-link** [comment]
Sorry for ignoring this, but this looks great! I would love to have this in

**Comment by Simran-B** [comment]
PR: https://github.com/olive-editor/olive/pull/872
