### ISSUE TITLE
After Razor tool use, both resulting clips are selected

### ISSUE THREAD

**Issue by psemiletov** [olive-editor/olive#863]
If I use the razor tool on clip A and have resulting clips B and C, both of them are becomes selected (because A was selected). The next  logical action after razor is to resize B or C, so user need to do the additional two clicks - to deselect clips and to select B or C.

**Comment by benrob0329** [comment]
Most editors leave the smaller clip selected AFAIK. This is so that you can quickly delete the trimmed off parts.
