### ISSUE TITLE
Complete localization of the effects

### ISSUE THREAD

**Issue by MassiminoilTrace** [olive-editor/olive#864]
### I have read the following
- .ts localization files
- individual .xml and .frag files of the effects

### Problem
-The effects in `/effects/internal/` such as Transform are mostly localized(except for the title of the effect itself). I suppose this is possible thanks to the .cpp tr() they're originated from.
-The effects in `effects/shaders/` are NOT translated. There are no entries of this strings in any place I searched for. (see "directional blur" as an example in the screenshot).
![immagine](https://user-images.githubusercontent.com/24638827/56470654-14734680-6449-11e9-9292-0479d9ef0a23.png)

### Request
Is there any way I could already contribute translating these strings or this feature has not yet been implemented?

**Comment by itsmattkc** [comment]
There has been work towards this in the new effects structure in `furtherocio`. Because they're all modular/external files, the standard Qt translation methods don't apply to them. The plan is to extend the XML format to allow for various strings for various languages.

**Comment by Simran-B** [comment]
Is the XML format to be discussed or does it need someone to write code to make use of translations in the UI? Just wondering if translations can already be contributed.

**Comment by MassiminoilTrace** [comment]
I'm wondering about this issue. I'm thinking about an approach similar to the `strings.xml` in android studio, using key-value elements: keys in the code and values in each xml file. In this way we could have a general "strings.xml" as a fallback and single files for each language.
Other key-value file, as json, could work either.
I think this is better than the approach of linux `.desktop` files, in which all translations are in the same file.
Having different files lets different localization volunteers work on their own file only.
What do you think?
