### ISSUE TITLE
Unresponsive Audio Meter

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#865]
### System Information

**Olive version:**  [c5f63ec2]

**Source:** [zip from github]

**Operating system:** [Windows 10 64-bit]

**CPU:** [Intel i5-6400]

**RAM:** [4GB]

**GPU:** [e.g. NVIDIA Geforce GT 1030 2GB (Latest Driver Version)]

### Detailed Description

[Sometimes the audio meter does not respond to audio being played by the clip in the timeline]

### Steps to reproduce

[Playing the clip and make some edits or 2]

### Output Log

```
[Nothing]
```

### GDB/CDB Backtrace (for crashes)

```
[Nothing]
```

**Comment by AGI-THB** [comment]
#830
#691

**Comment by AGI-THB** [comment]
You can close this issue too since its a repost.
