### ISSUE TITLE
[EDIT] Select Everything In Front/Behind Playhead Option

### ISSUE THREAD

**Issue by emma-15** [olive-editor/olive#866]
The title is pretty self-explanatory, but I'll try to give a detailed description.
With this feature after right-clicking the red cursor
 you'll see the options:
- **Select all clips after** (selects every clip in front of red cursor)
- **Select all clips before** (selects every clip in behind red cursor)

This saves a ton of time for me.

**Comment by Simran-B** [comment]
Do you want to move everything on one side of the cursor? Or do something else with the selection?

If it is only about moving, then a tool for that purpose might be another option.

Should it select/move clips which are under the cursor but on the "wrong" side as well?

**Comment by emma-15** [comment]
All I want is an option that will **select all clips in front of the red line**, "![Red Cursor](https://user-images.githubusercontent.com/48891420/56476756-7a1ffc80-6462-11e9-92eb-62529fe72da5.JPG)"
and an option that will **select all 
clips in behind the red line**.
I am gitting tired of shift clicking.

**Comment by Simran-B** [comment]
This clip is partially before and partially after the cursor:

![image](https://user-images.githubusercontent.com/7819991/56504815-11945680-651a-11e9-9079-d862c40b22a8.png)

Should "select all clips in front of red line" only select clips which are fully in front (start and end), or should it also select clips which have the starting point before the cursor, but may or may not end after the cursor?

**Comment by emma-15** [comment]
Probably the, "only select clips which are fully in front (start and end)" one.

**Comment by NathanSalapat** [comment]
You should be able to box select by clicking and dragging in the timeline, as long as you don't start over a clip. Obviously not as fast as your request, but better than shift clicking every clip.

**Comment by emma-15** [comment]
Box select is a little hard when you have 10+ tracks stacked on top of each other.

**Comment by Simran-B** [comment]
The tracks can be made smaller, but that's kinda annoying too. An action to reduce the track size vertically to a minimum would be useful for such a scenario... Anyway, I still see a use for the requested selection actions.
