### ISSUE TITLE
Cannot Export To MP3

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#867]
### System Information

**Olive version:**  [c5f63ec2]

**Source:** [zip form github]

**Operating system:** [Windows 10 64-bit]

**CPU:** [Intel i5-6400]

**RAM:** [4GB]

**GPU:** [Intel Graphics HD 530 128MB (Latest driver version)]

### Detailed Description

[When trying to export into other audio formats, it will only export into .m4a]

### Steps to reproduce

[Got to File, click export, disable video, change the format to something else and then export]

### Output Log

```
[Nothing]
```

### GDB/CDB Backtrace (for crashes)

```
[Nothing]
```

**Comment by AGI-THB** [comment]
I tried it and it worked fine for me on linux mint.
Either its a problem on windows or you did something wrong while selecting the settings.

**Comment by MrTeeXD** [comment]
I did nothing wrong, i selected libmp3lame MP3 for .mp3 but its the same

**Comment by AGI-THB** [comment]
which format did you select? libmp3 is the codec, not the format

**Comment by MrTeeXD** [comment]
Apparently i was blinded by my own stupedity and did not notice the Format Option at the top of the Export dialog

**Comment by AGI-THB** [comment]
Alright, close the issue then.

**Comment by MrTeeXD** [comment]
Alright
