### ISSUE TITLE
Menus don't show up in full screen

### ISSUE THREAD

**Issue by rtakehara** [olive-editor/olive#868]
### System Information
**Olive version:**  Olive (March 2019 | Alpha | c5f63ec2)
**Source:** Website
**Operating system:** Windows 10 Pro 64-bit
**CPU:** Intel i5-7670K
**RAM:** 8GB
**GPU:** NVIDIA Geforce GT 770 2GB (Driver ver 425.31)

### Detailed Description

Menus don't show in Full Screen mode. I can click on the items and blindly select them but I can't see them, same with keyboard shortcuts, so I guess the menus are rendering behind  the panels?

Also this is more of a request but couldn't the menu bar be the same color as the the rest of the  theme?

### Steps to reproduce

-Enter Full Screen either via View>Full Screen or pressing F11
-Interact with the menus via mouse or keyboard shortcut

### Output Log

Is this it? not sure if its useful
```
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing custom cursors (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )

```

### GDB/CDB Backtrace (for crashes)

I have no idea what is this, I do not code
```
[If you can reproduce this issue, try running Olive through GDB and retrieving a backtrace, then paste the backtrace here. Instructions are available in the Wiki on how to acquire this backtrace.]
```

**Comment by alcomposer** [comment]
I am running Antergos, with Git build up-to-date, I can't replicate this issue. Wondering if this is Windows specific?

Here is a screenshot of what Olive looks like as fullscreen (F11) on Antergos with a menu open:
![Screenshot from 2019-04-22 12-15-32](https://user-images.githubusercontent.com/12004932/56480422-26acbd80-64f9-11e9-9a8e-6fcaddc0186d.png)

@rtakehara could you post a screenshot so we can see what is happening, or video?

**Comment by rtakehara** [comment]
Probably, and huh... even weirder, I was going to screenshot to demonstrate and the screenshot show it properly.

Here is the screenshot of what the computer think it is versus how it really is
![Olive](https://user-images.githubusercontent.com/49849179/56483664-bb83cc80-64a1-11e9-91c3-78de60e7ae6d.jpg)
