### ISSUE TITLE
Trouble with TEXT when the SIZE = 0

### ISSUE THREAD

**Issue by zakaria-chahboun** [olive-editor/olive#870]
### System Information

**Olive version:**  Alpha c5f63ec
**Source:** Ubuntu repository 

**Operating system:** KDE NEON

**CPU:** Intel i5-4300U

**RAM:** 5GB

**GPU:** Intel Corporation Xeon E3-1200 v2/3rd

### Detailed Description
When i set the **size of text to 0**, the text is **stuck** and doesn't follow the transition keys!
*(For example to create a zoom-out effects, we must move size from 0 to 50)*

![qqqqqqqqqqqqqqqqqqqqqqqq](https://user-images.githubusercontent.com/18173275/56495051-4ab5d200-64ec-11e9-9e72-6d621c65e918.png)

**Comment by AGI-THB** [comment]
[WARNING] QFont::setPointSize: Point size <= 0 (0), must be greater than 0


Steps:
1) create a keyframe with text::size=0
2) create another keyframe with text::size >> 0 a few seconds later
3) while the red arrow is behind the the second keyframe, click on the timeline / keyframe-graph to a moment BEFORE the first keyframe. The text stays the size of the second keyframe.

seems like an update problem plus the problem that people can enter values of zero, although that may not be intended.

**Comment by zakaria-chahboun** [comment]
> [WARNING] QFont::setPointSize: Point size <= 0 (0), must be greater than 0
> 
> Steps:
> 
> 1. create a keyframe with text::size=0
> 2. create another keyframe with text::size >> 0 a few seconds later
> 3. while the red arrow is behind the the second keyframe, click on the timeline / keyframe-graph to a moment BEFORE the first keyframe. The text stays the size of the second keyframe.
> 
> seems like an update problem plus the problem that people can enter values of zero, although that may not be intended.

**Comment by zakaria-chahboun** [comment]
Sorry!

I already use this trick, but in the most of times, the TEXT still stuck :cactus: :  !

**Comment by AGI-THB** [comment]
@itsmattkc You have merged a PR that adressed this problem. I think this can be closed here.
