### ISSUE TITLE
(nodes branch) Color Management LOOK selection bar goes up one increment after clicking OK.

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#871]
### System Information

**Olive version: 616e2b47** 
**Source: Git source code download**
**Operating system: Windows 10 Pro 64 Bit**
**CPU: Intel i7-5557U**
**RAM: 16GB** 
**GPU: Intel Iris 6100**

### Detailed Description

In the nodes branch, when adjusting the _Look_ in the **Color Management** window, the selection indent goes up one increment after clicking OK:

![Bug_Demo](https://user-images.githubusercontent.com/5027750/56544710-1a8d2400-652a-11e9-9796-612b94106937.gif)
(GIF visual demonstration of Base Contrast unexpectedly going up to Medium High Contrast)

### Steps to reproduce

1. Start a new project in the nodes branch, import any footage into any new sequence.
2. Open up Preferences under the Tools window tab. Go to Color Management.
3. Import any OCIO config file and leave everything but the Look sub-selection part.
4. Change the Look choice to anything. Click Ok. Then return back to Color Management.

(If you notice a different _look_ choice when returning to the color management tab in preferences, you'll see why. Hopefully the GIF visual demo explains better)

**Comment by Simran-B** [comment]
Sounds like an off-by-1 error? It seems to either store a wrong entry or read it back in incorrectly. What happens if you select the top most entry?

Is it off because the first entry `(None)` is artificial and not accounted for in some piece of code?

**Comment by Corruptinator** [comment]
I do believe that (none) is for if you don't want to choose a contrast, which I did want to use cause it helps add clarity to some raw footage that has dynamic color range encoded.

**Comment by Simran-B** [comment]
```cpp
    // Populate the look menu
    ocio_look->clear();
    ocio_look->addItem(tr("(None)"), QString());
    for (int i=0;i<config->getNumLooks();i++) {
      const char* look = config->getLookNameByIndex(i);

      ocio_look->addItem(look, look);

      if (look == olive::config.ocio_look) {
        ocio_look->setCurrentIndex(i);
      }
    }
```

*(None)* is indeed an artificial entry. Then there is a loop over the available looks to also add them to the dropdown menu. In the loop, there is a check if the currently processed look is equal to the configured look, and if so, the `i` counter variable is re-used to set the current index - but the first entry is *(None)* and not the first actual look.

https://github.com/olive-editor/olive/blob/nodes/dialogs/preferencesdialog.cpp#L214

Here is a patch: https://github.com/olive-editor/olive/pull/883. Can you confirm that it works?

**Comment by Corruptinator** [comment]
Just tested Patch #883, it does work. Thanks!

**Comment by Corruptinator** [comment]
Hope the patch can get applied in a timely manner.

**Comment by sobotka** [comment]
I’ve sort of been addressing “None” in my fork with the ClassColourManager. When a variable is not set / undefined, it defaults to the OCIO return form of returning -1.

**Comment by Corruptinator** [comment]
Uh, the Master branch is having the same problem again, look option is going up by one increment.

**Comment by Simran-B** [comment]
Bug was re-introduced with the pipeline merge, but already fixed again:
https://github.com/olive-editor/olive/commit/127a773c54ddb37b99ebfecb2f76c2a68c37f1af#diff-1487d24f5789d470084328f76d847351
