### ISSUE TITLE
General Frame Rate ingest / export issues

### ISSUE THREAD

**Issue by mivoligo** [olive-editor/olive#874]
### System Information

**Olive version:**  Olive (March 2019 | Alpha | c5f63ec)

**Source:** from PPA

**Operating system:**  Ubuntu 18.04

**CPU:** Intel® Xeon(R) CPU W3690 @ 3.47GHz × 12 

**RAM:** 24GB

**GPU:** GeForce GTX 1060 3GB/PCIe/SSE2

### Detailed Description

I've got some videos recorded with GoPro Hero 6. The videos are recorded in 200 fps. I've opened one in Olive, edited a bit and tried to export. In the Export settings the max frame rate I can set is 60. I've exported the video with that settings but the quality is very very low, hard to say what's on the video.

**Comment by Simran-B** [comment]
> the quality is very very low, hard to say what's on the video

sounds like the compression settings aren't right for you (too low bitrate?), but is it actually related to the framerate cap?

**Comment by mivoligo** [comment]
I've experimented with various compression values but still without success. If I use a video with 50fps or 25fps everything looks fine.

**Comment by mivoligo** [comment]
Short example how it looks when used quality 15: https://youtu.be/aWoFe7OcEYc

**Comment by Simran-B** [comment]
CRF 15 that is?

It looks to me more like broken encoding or decoding rather than a quality setting issue to be honest. Maybe such high frame rates aren't supported (yet) or there's some issue with e.g. ffmpeg?

**Comment by mivoligo** [comment]
Yes, CFR 15.
I've no idea about decoding/encoding. I assume the issue is somehow related
to the frame rate.
In the Shotcut video editor I was able to export in 200 fps without any
problems in quality. But I'm not sure if the encoding is working similarly
to Olive.

**Comment by Simran-B** [comment]
I've seen similar artifacts in VLC when my computer couldn't cope with a video. It was raw footage with an extremely high bitrate (not compressed at all), for which there wasn't enough CPU power to decode it in real time, or it surpassed the disk throughput perhaps. Rendering a video is not a real time process however, but it could still be somewhat related - perhaps some kind of throttling is missing in Olive's implementation?

**Comment by arthur109** [comment]
I'm having the same issue also
