### ISSUE TITLE
Scrolling title shadow issue

### ISSUE THREAD

**Issue by lutusp** [olive-editor/olive#875]
### System Information

**Olive version:**  [e.g. Git hash from window title or Help > About]

Olive (March 2019 | Alpha | c5f63ec)

**Source:** [e.g. AppImage, Website etc.]

Ubuntu repository: olive-editor/bionic,now 201904210746-c5f63ec+1038~ubuntu18.04.1 amd64

**Operating system:** [e.g. Ubuntu 18.04 64-bit]

Ubuntu 18.04 64-bit

**CPU:** [e.g. Intel i5-4300U]

Intel Core i7-8809G 

**RAM:** [e.g. 8GB]

32GB

**GPU:** [e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx)]

GPU: Advanced Micro Devices [AMD/ATI] Polaris 22 [Radeon RX Vega M GH]

Driver: AMD VEGAM (DRM 3.26.0, 4.18.0-041800-generic, LLVM 7.0.1)

### Detailed Description

[Describe the issue you're having]

The title drop-shadow feature only covers one frame -- if the title is allowed to scroll, the text past one vertical frame height doesn't get the programmed shadow. As the title scrolls, a non-shadow appears, as shown in this image:

https://i.imgur.com/y8m9CK9.png

My tests show that this effect is processor and GPU independent.

### Steps to reproduce

[Describe the steps to demonstrate the issue you're reporting]

* Open an empty project.

* Insert a lengthy text block into the title feature.

* Choose a suitably large text point size, like 40.

* Enable title scrolling.

### Output Log

```
[Paste output log] : N/A for this bug
```

### GDB/CDB Backtrace (for crashes)

```
[If you can reproduce this issue, try running Olive through GDB and retrieving a backtrace, then paste the backtrace here. Instructions are available in the Wiki on how to acquire this backtrace.]
```

**Comment by Kliurka** [comment]
Same problem and for me

**Comment by DaniSeeh** [comment]
This was fixed it seems.
