### ISSUE TITLE
Limit autorecovery files storing

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#879]
Currently *Olive* store all autorecovery files in `~/.local/share/olivevideoeditor.org/Olive/`

![pic.1](https://i.imgur.com/LVKxLwV.png)

There should be an option in "Prefernces" dialog for:

- limit number of recent autorecovery file;
- remove autorecovery files older than `defined` days or hours (based on timestamps stored in autorecovery file names).

**Comment by itsmattkc** [comment]
Olive automatically manages and cleans this folder and it takes up a few megabytes at most.
