### ISSUE TITLE
Add an "Invert" option to Vignette Effect

### ISSUE THREAD

**Issue by emma-15** [olive-editor/olive#881]
Just like the crop effect (#789), the vignette effect needs a invert option.

**Comment by cgvirus** [comment]
have created a pull request.
You can test it here:
https://github.com/cgvirus/olive/blob/master/effects/shaders/vignette.frag
https://github.com/cgvirus/olive/blob/master/effects/shaders/vignette.xml

**Comment by emma-15** [comment]
Thanks!  :smiley:

**Comment by itsmattkc** [comment]
See comment on #789 for the planned long term solution.
