### ISSUE TITLE
[Issue] GIF exports have strange artefacts

### ISSUE THREAD

**Issue by libalis** [olive-editor/olive#885]
### System Information

**Olive version:** c5f63ec2

**Source:** Compiled from 'master' branch

**Operating system:** Arch Linux

**CPU:** Intel Core i7-6700HQ

**RAM:** 16GB

**GPU:** NVIDIA 960M (Driver version: 418.56)

### Detailed Description

Every time I export a clip as a GIF file, it's full of artefacts.
I tried this with several clips and settings, but no luck.

### Steps to reproduce

1. Import Clip
2. Export as GIF

### Output Log

```
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing custom cursors (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Clip opened on track 0 (took 52 ms) (:0, )
[INFO] Clip opened on track -1 (took 53 ms) (:0, )
[INFO] Clip closed on track 0 (:0, )
[INFO] Clip closed on track -1 (:0, )
[INFO] Auto-recovery project saved (:0, )
[INFO] Clip opened on track 0 (took 70 ms) (:0, )
[INFO] Clip opened on track -1 (took 53 ms) (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[WARNING] "ES BRENNT!.mp4" frame had no PTS value (:0, )
[INFO] Clip closed on track -1 (:0, )
[WARNING] QObject::startTimer: Timers cannot be started from another thread (:0, )
[INFO] Clip closed on track 0 (:0, )
```

### Example
![ES BRENNT](https://user-images.githubusercontent.com/45124869/56853452-7a1f7100-6928-11e9-80e3-0a39d1f73e1b.gif)

### Ending
Thank you for addressing this issue report in advance and keep up the great work!

**Comment by Simran-B** [comment]
Still frame:
![image](https://user-images.githubusercontent.com/7819991/56870298-afea5580-6a0d-11e9-9f51-ea55613a8d62.png)

**Comment by libalis** [comment]
Thank you Simran-B for the help

**Comment by enzogian** [comment]
Yes I am having the same problems when exporting animated gifs:
1- first of all it inserts a black frame interrupting the smooth flow loop effect
2- another concern is the huge file size resulting when exporting an animated gif (not sure on how to play wiht compressions or frames per second but when reducing the amount of frames the images is extremely poor ..
(on the second aspect I wonder how programs like gimp can export animaged gifs that are just some hundreds of kbites while when editing in Olive it exports to a huge file size (11 megas or so.. ?)
hope it makes sense, 
It would be wonderful if OLive could be a wonderful solution for all video needs comprising the animated gifs which are so popular and sometimes useful even though not as demanding as professional video editing ;)

**Comment by Simran-B** [comment]
@enzogian Does GIMP really produce GIFs at the same dimension and framerate as well as the same amount of colors as Olive? There aren't many ways to reduce the file size of GIFs because the format uses lossless compression. Also, a bad compression ratio is inherent to the format. You are way better off with video compression codecs, but they are lossy for the most part. The visual quality can still be much better compared to a GIF which can only have up to 256 colors.

**Comment by frink** [comment]
I believe the problem here is the glitch in the loop which isn't really a GIMP vs. Olive discussion point...

**Comment by enzogian** [comment]
> I believe the problem here is the glitch in the loop which isn't really a GIMP vs. Olive discussion point...

I did not want to make it sound as a Gimp vs Olive not at all really.. I just was mentioning the issue related to the file size in the black frame in teh loop but perhaps I did not expose it correctly 
thanks ;)

**Comment by musaire** [comment]
In my experience I get usable file sizes for GIFs when using ca. 320px widths only and 64 colors and 6FPS is enough. Not sure what settings Olive has for GIFs, I used Camtasia for GIFs (edit clips in Sony Vegas).
I am still to try GIFs in Olive. Looking forward!!! :)
