### ISSUE TITLE
`makeCurrent()` call with no surface argument causes black/blank Viewers

### ISSUE THREAD

**Issue by follower** [olive-editor/olive#892]
I was wondering if the following `makeCurrent()` call with no surface argument is intentional?

https://github.com/olive-editor/olive/blob/963a20af37d78f038b69591f7879c84f744c9df2/ui/viewerwidget.cpp#L548

The docs for `makeCurrent(...)` mention:

> `bool QOpenGLContext::makeCurrent(QSurface *surface)`
> Makes the context current in the current thread, against the given surface. [...]
> **If surface is 0 this is equivalent to calling `doneCurrent()`.**
> -- <https://doc.qt.io/qt-5/qopenglcontext.html#makeCurrent>

While the docs for `doneCurrent()` mention:

> `void QOpenGLContext::doneCurrent()`
> Convenience function for calling `makeCurrent` with a 0 surface.
> **This results in no context being current in the current thread.**
> -- <https://doc.qt.io/qt-5/qopenglcontext.html#doneCurrent>

Additionally the docs for `paintGL()` mention:

> `void QOpenGLWidget::paintGL()`
> [...] **There is no need to call `makeCurrent()` because this has already been done when this function is called.**
> -- <https://doc.qt.io/qt-5/qopenglwidget.html#paintGL>

#### Impact and solution

Based on the assumption that other people have Olive running successfully, it seems like the effect of having no current OpenGL context may be undefined/system-dependent but in my case the call to `makeCurrent()` with no argument causes the "Media Viewer" and "Sequence Viewer" to not render anything other than solid black.

Removing the call to `makeCurrent()` appears to fix the issue--and takes a *very* long time to discover even if one's dealt with the "interesting" design & documentation choices of Qt's OpenGL support before. :) Which I've had the misfortune to have...

This may not be of the greatest concern because the platform it occured on is Mac OS X 10.9 with Qt 5.6 but I thought I'd at least mention it as it might cause issues elsewhere too.

This appears to be the commit where this code was introduced: https://github.com/olive-editor/olive/commit/e1ec2f6fbe26112c6cc8f7530a56d5a7da5b8a18#diff-25489ab39aa89c80d97e7872276716a7R450

#### Potential related issue

On a semi-related note, I noticed this documentation regarding `swapBuffers()` (which Olive doesn't seem to use?) and vague "To be able to support certain platforms" remark:

>When OpenGL rendering is done, call `swapBuffers()` to swap the front and back buffers of the surface, so that the newly rendered content becomes visible. To be able to support certain platforms, `QOpenGLContext` requires that you call `makeCurrent()` again before starting rendering a new frame, after calling `swapBuffers()`.
> -- <https://doc.qt.io/qt-5/qopenglcontext.html#details>

Not sure if there's a particular reason Olive doesn't currently use `swapBuffers()` but in case it changes in future I thought I'd mention it. :)

*Edit:* Here's a link to <https://github.com/apitrace/apitrace/> which I used to investigate this and other OpenGL/Qt-related issues in case it's also useful for others.

**Comment by itsmattkc** [comment]
Interesting, you're correct `makeCurrent()` appears to not be necessary, though the fact that it breaks things I'm thinking is a Qt bug. It's supposed to be "valid" to call it on the QOpenGLWidget with no arg (see https://doc.qt.io/qt-5/qopenglwidget.html#makeCurrent), but I would expect it to be a no-op if the context was already set.

Regardless, I'm happy to merge your PR to fix this issue.

**Comment by follower** [comment]
Oh, I've just realised after reading your comment that the call seems to be to [`void QOpenGLWidget::makeCurrent()`](https://doc.qt.io/qt-5/qopenglwidget.html#makeCurrent) (i.e. `Widget`) *not* [`bool QOpenGLContext::makeCurrent(QSurface *surface)`](https://doc.qt.io/qt-5/qopenglcontext.html#makeCurrent) (i.e. `Context`).

Which is odd because I thought I'd checked what was subclassed but I guess I misread it:

https://github.com/olive-editor/olive/blob/c5f63ec2c5511e4af0f4a5a839dbfd995bd77fd4/ui/viewerwidget.h#L44

(Or maybe I just got confused by not recalling there were two (actually, *multiple*) different methods named `makeCurrent`.)

So, you're right that *is* weird that the call to `makeCurrent()` makes a difference.

Although, I've just noticed that in a *third* method named [`makeCurrent()` in `QOpenGLWindow`](https://doc.qt.io/qt-5/qopenglwindow.html#makeCurrent) it says:

> It is not necessary to call this function in most cases, because it is called automatically before invoking `paintGL().` **It is provided nonetheless to support advanced, multi-threaded scenarios where a thread different than the GUI or main thread may want to update the surface or framebuffer contents.** See `QOpenGLContext` for more information on threading related issues.

So that might be why we're seeing issues.

From the `apitrace` OpenGL recordings and debug logging it did seem like an issue related to texture binding...

My impression is that correctly understanding/implementing OpenGL contexts is non-trivial even before adding threading & Qt to the mix. (Not least because Qt's own windows are actually rendered via OpenGL.)

Thanks for being open to merging the PR even though I my understanding of the situation wasn't entirely correct. :) (I guess we might need to be prepared that the change *might* break something on some other platforms if its original use isn't necessarily incorrect.)

**Comment by itsmattkc** [comment]
Heh that's okay, it's definitely confusing. Indeed, multithreading the GL leads to an unfortunate mess of `doneCurrent()`s and `makeCurrent()`s and I was the redundant `makeCurrent()` at the top of `paintGL()` was probably me being overly careful. Still strange that it would break things, but I don't think there's any need for it. I've merged your PR.
