### ISSUE TITLE
Download page states Mac OS X 10.7+ supported but binary requires 10.12+

### ISSUE THREAD

**Issue by follower** [olive-editor/olive#894]
### System Information

**Olive version:**  `Olive-c5f63ec-macOS.zip` 

**Source:**  via <https://olivevideoeditor.org/download.php>

**Operating system:** Mac OS X 10.9

**CPU:** Intel Core i7

**RAM:** N/A

**GPU:** N/A

### Detailed Description

The Olive download listed as supporting Mac OS X 10.7+ doesn't run on Mac OS X 10.9.

### Steps to reproduce

* Visit <https://olivevideoeditor.org/download.php>.
* Download & extract  `Olive-c5f63ec-macOS.zip` on Mac OS X 10.9.
* Note icon has a "forbidden" crossed circle sign and the `Contents/Info.plist` file has this section:
```
        <key>LSMinimumSystemVersion</key>
        <string>10.12</string>
```

It appears Mac OS X 10.9 was previously supported (in December 2018) as there was discussion & logs mentioned in this resolved issue: #188.

My assumption is that the change in version support is due to the use of Homebrew to install Qt and the Travis CI configuration:

 * This appears to be the first Mac Travis build: https://travis-ci.org/olive-editor/olive/jobs/491378870

 * And, this is a recent build which shows configuration including `-isysroot /Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.12 [...] -F/usr/local/Cellar/qt/5.12.2/lib`: https://travis-ci.org/olive-editor/olive/jobs/522622908#L3200

### Proposed initial solution

Replace `OS X 10.7+` text on download page with `macOS 10.12+`--at least as long as the continuous builds are linked.

**Comment by itsmattkc** [comment]
True, the website text is old. I'll fix that soon.

**Comment by itsmattkc** [comment]
Fixed now
