### ISSUE TITLE
No support for 120 fps

### ISSUE THREAD

**Issue by swingonaset** [olive-editor/olive#895]
[If you are requesting a feature, please try to fill out all the information below. If you are reporting a bug, you can clear the template below.]

### I have read the following

- [x] The [Olive Wiki](https://github.com/olive-editor/olive/wiki)

- [ ] Previous issues that include ["FR"](https://github.com/olive-editor/olive/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+FR)or ["Feature Request"](https://github.com/olive-editor/olive/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+Feature+Request)

- [ ] Olive's [Project Goals](https://github.com/olive-editor/olive/projects)

### Detailed description of the feature request

I LOVE OLIVE!!! I have been using it for about 2 weeks now and then this morning I tried to use a 120fps video. Upon importing it into the browser, the fps of the video was automatically reset to 99.99 fps. I was unable to exceed 100 fps by manually inputing the frame rate.

There are, of course, work arounds but it would be nice to have 120 and even 240 fps support at some point.

Thanks so much!

### Why should Olive include the feature? What are the benefits?

120 and 240 fps are industry standard frame rates for high speed video capture. Adding this support would greatly improve Olive's editing experience because the editor would not have to play with the speed factor of the clip to get the right speed for the clip if they wanted to play the clip back normally.

---

[If you are reporting a bug, please try to fill out all the information below. If you are requesting a feature, you can clear the template above.]

### System Information

**Olive version:**  Olive (March 2019 | Alpha | c5f63ec)

**Source:** linux repository

**Operating system:** Ubuntu 18.04 64-bit

**CPU:** i5 3317U

**RAM:** 4GB

**GPU:** none

### Detailed Description

[Describe the issue you're having]

### Steps to reproduce

[Describe the steps to demonstrate the issue you're reporting]

### Output Log

```
[Paste output log]
```

### GDB/CDB Backtrace (for crashes)

```
[If you can reproduce this issue, try running Olive through GDB and retrieving a backtrace, then paste the backtrace here. Instructions are available in the Wiki on how to acquire this backtrace.]
```

**Comment by itsmattkc** [comment]
Related to #874

**Comment by sobotka** [comment]
Merged with previous frame rate related issues in #874.
