### ISSUE TITLE
[Feature Request] Add more plugins! That's the point!

### ISSUE THREAD

**Issue by zakaria-chahboun** [olive-editor/olive#897]
In My Experience, with After Effects and Premiere Pro (and so on ..), **the plugins** have a **big powerful effects** on the program, because it's **keeping time!**
and you can **get the idea** by looking at this project named [**Mister Horse**](https://misterhorse.tv/) (it's the most beautiful/powerful plugins used for **After Effects**)

**Olive Editor** has also this step by the **"[Olive-Editor-Community-Effects](https://github.com/cgvirus/Olive-Editor-Community-Effects)"**, and thanks to the creator **"cgvirus"** for that!

So my request is to keep update this effects and **support it, by adding more!**
(just trust me, Olive can be the best video editors on Linux! and more **useful for the youtubers**)

Also, **don't forget** to put some tutorials (may be a playlist videos) for helping **programmers** to create more plugins!

Thank You! :heart: 

## Screenshots
Exapmple:

*Without any quick effects (Normal Image)*
![image](https://user-images.githubusercontent.com/18173275/57008866-01037080-6beb-11e9-8fb5-9d557c927482.png)

*With* ***Barrel Distortion*** *effect from the community!*
![ggf](https://user-images.githubusercontent.com/18173275/57009078-5e4bf180-6bec-11e9-805c-1a943d8434bd.png)

**Comment by sobotka** [comment]
This perfectly sums up everything wrong with open source design. Well done.

**Comment by BrimsonBhin** [comment]
Please read the projects pane. The Olive Team considered support for OpenFX and LV2 plugins.

cgvirus' effects repository is more or less a concept on how to get custom effects working in Olive. The custom-effects repo is on a haitus because the Olive project is undergoing major transitions (look at Olive's other branches).

If people are working on effects/plugins right now, they are either:
- Wasting their time making something that will not work
- Laying down a concept
- Or testing/debugging Olive

I'm fine with plugins. However, Olive is at a state where it is counterproductive to make more plugins and effects.

**Comment by zakaria-chahboun** [comment]
@BrimsonBhin That's Right!
But i mean in the **future** **(more quick plugins = less time to do thing = great editor)!**

**Comment by sobotka** [comment]
There are plenty of projects with canned plugins. Use them.

**Comment by zakaria-chahboun** [comment]
@sobotka Sorry! What's Wrong?

**Comment by itsmattkc** [comment]
Rest assured, a lot of effort is going towards having the most flexible pixel pipeline possible.

**Comment by sobotka** [comment]
A core issue with plugins is that they are designed to meet a particular need for a particular context. TL;DR: You cannot simply migrate a plug-in and expect it to work. A core design tenet of Olive is scene linear managed manipulations, which flies in the face of slap-together plugins designed for YouTube.

[Current state of OFX plugins regarding pixel management is unresolved.](https://github.com/ofxa/openfx/issues/46) This includes some extremely capable people such as Dennis contributing.

If OFX gets it wrong, so you believe including more plugins from random internet peeps will get it right?

**Comment by zakaria-chahboun** [comment]
The *Quick Plugins Concept* is to get **"native effects"** and **mixed them** in one box!
Like for example to get a **transition** with **(Zoom-Out with some Blur & Color effects)**
So this 3 effects is a **native effects!** and to do this transition, you have to play with 3 tabs **separately ** every time!
So the concept is to create some plugins, **to help people to do quick effects!**
Same as [Mister-Horse](https://misterhorse.tv/) plugins on After Effects (The most used!)

Just take a look on it, and you can get the IDEA!

**Comment by benrob0329** [comment]
Please don't abuse formatting, its very distracting to read.
