### ISSUE TITLE
[Bug] macOS app won't open "because it may be damaged or incomplete"

### ISSUE THREAD

**Issue by BenBergman** [olive-editor/olive#906]
**Describe the bug**
When I try to open the the app available on the website for macOS I get the following error:

```
You can’t open the application “Olive.app” because it may be damaged or incomplete.
```

The md5 sum of the zip file matches the md5 sum listed on the web page.

**To Reproduce**
1. Download the app for macOS
2. Unzip the app
3. Double click `Olive.app` and see the error message

**Expected behavior**
This error should not be here and the app should launch.

**Screenshots**
The error message is "You can’t open the application “Olive.app” because it may be damaged or incomplete."

**Desktop (please complete the following information):**
- Olive version:  Can't get into the app to check, but based on the site this is March 2019 version with md5 sum 04cd2711c9e8b5c4985d3af9b89fc9ea 
- Source: Website
- Operating system: macOS 10.14.4
- CPU: i7-6820HQ
- RAM: 16GB
- GPU: Radeon Pro 455 2 GB / Intel HD Graphics 530 1536 MB

**Comment by BrimsonBhin** [comment]
The compilation for the continuous builds are broken for now. No builds for Linux or Windows either

**Comment by itsmattkc** [comment]
Yeah I'm surprised the macOS CI built anything to upload... The website was set up to auto-update from CI which is why that got updated with the broken copy. I've disabled the auto-update and restored a functional copy of Olive for macOS on the website.
