### ISSUE TITLE
[Feature Request] Screenshot Icon

### ISSUE THREAD

**Issue by Nordy13** [olive-editor/olive#908]
I know that you can already screenshot a frame by right-clicking the screen, but I think it would be better to have a screenshot icon than right-clicking the screen.
This is how I picture it:
![Screenshot Icon](https://user-images.githubusercontent.com/49649429/57182576-4384b180-6e66-11e9-893d-0ce13be0a543.png)

**Comment by MaGaRCaN** [comment]
Thats a very good idea, and seems easy ti implement

**Comment by Fatih20** [comment]
I agree with this.
