### ISSUE TITLE
Translation help of OCIO settings panel

### ISSUE THREAD

**Issue by MassiminoilTrace** [olive-editor/olive#909]
Hi! I would like to ask more details of the parts in red.
In order to translate in a better way, I decided to ask what's the exact purpose and function of each non-translated string. (Display, view, look, playback(offline), export(online))
 ![Screenshot_20190504_211745](https://user-images.githubusercontent.com/24638827/57183826-c7648b00-6eb2-11e9-9fc0-6feabb92c52e.png)
Thank you in advance.
I hope this issue helps other translators too.

**Comment by sobotka** [comment]
While most of this is in deep flux, I can give you an idea of the labels. They are likely to move around in a significant manner.
* Display: Describes the display colorimetry that a particular window is being used on.
* View: A particular rendering of the internal data, designed for the display chosen above.
* Look: A creative / aesthetic twist on the view above.
* Offline: In editorial / post production terminology, a lower quality version of the internal data that reasonably depicts the data, but with trade offs made to accommodate realtime design needs. This is _opposite_ to the terminology laid out by rendering engines, where offline indicates highest, non-realtime quality.
* Online: In editorial / post production terminology, the highest possible quality version of the internal data. This may result in a trade off of quality over realtime design needs. This is _opposite_ to the terminology laid out by rendering engines, where online indicates a lower quality, realtime quality approximation.

**Comment by sobotka** [comment]
Updated the [Glossary WIP](Glossary WIP)  to reflect these terms.
