### ISSUE TITLE
Image glitch

### ISSUE THREAD

**Issue by Gdies420** [olive-editor/olive#910]
(all on ubuntu 18.04.2 LTS)

i am in the january 2019 c8ae c60 version of the editor even though i updated it and when i drag an image (specifically a png file with a transparent backround) it doesnt show up in the video when i play it back or export it and watch it. and whenever i playback a short video in the editor with only 3 or so clips, the frame rate slows to a crawl and it stops frequently. (it didn't do this before) 
please help!

**Comment by itsmattkc** [comment]
January 2019 is very old. Try the latest. If you can't get the latest through apt, try the AppImage.

**Comment by DaniSeeh** [comment]
Please also fill out the issue template.

**Comment by DaniSeeh** [comment]
I'm closing all bugs prior to the current infrastructure rewrite (0.1.0 and before) as they are clogging the tracker and none of the bugs are likely to be relevant once the core infrastructure has been rewritten.

**Comment by BrimsonBhin** [comment]
@DaniSeeh I believe the ones that did not provide further information should be closed
