### ISSUE TITLE
Crash double-clicking empty timeline  

### ISSUE THREAD

**Issue by edsonmedina** [olive-editor/olive#915]
**Describe the bug**
Application crashes when double clicking an empty timeline

**To Reproduce**
1. Open application
2. Double click any point in the (empty) timeline
3. Application crashes

**Expected behavior**
Nothing should happen

**Desktop (please complete the following information):**
- Olive version:  c8aec60
- Source: snap
- Operating system: Ubuntu 18.04.2 LTS 64-bit
- CPU: Intel Core i7-8550U - 1.8Ghz x 8
- RAM: 16Gb
- GPU: Intel UHD Graphics 620 (Kabylake GT2)

### Output Log
```
[1]    27166 segmentation fault (core dumped)  olive-editor
```

**Comment by BrimsonBhin** [comment]
Update to 0.1.0. This was fixed months ago

**Comment by edsonmedina** [comment]
Snap still has this version... Are you planning to update soon?

**Comment by BrimsonBhin** [comment]
Up to @itsmattkc to decide

**Comment by edsonmedina** [comment]
The deb packages are a bit more recent (April 2019 - 1e3cf53) and I can confirm the bug is gone.

What's the most updated releases for linux?

**Comment by itsmattkc** [comment]
Pretty much any except the snap honestly. The snap's been neglected because (afaik) it's the only one that can't update automatically from Git (it probably needs to be added to another CI for that).

**Comment by edsonmedina** [comment]
Thanks! I'm using the AppImage version now.
You guys are doing an amazing work!
