### ISSUE TITLE
[Feature Request] gaffer support 

### ISSUE THREAD

**Issue by DGMurdockIII** [olive-editor/olive#917]
Can we get support for gaffer http://www.gafferhq.org

**Comment by sobotka** [comment]
Last I looked, Gaffer didn’t support any form of interchange? Would seem difficult to support without interchange.

**Comment by Chadt54** [comment]
I have used gaffer a lot, so I can answer questions about gaffer.

But, I don't see what this user means by having gaffer support. The request doesn't make sense to me.

**Comment by sobotka** [comment]
I’m going to close this, as it is essentially in the domain of interchange.
