### ISSUE TITLE
[Bug] Cannot play MTS file

### ISSUE THREAD

**Issue by leminhfsd** [olive-editor/olive#919]
[ERROR] Failed to retrieve frame for clip "00070.MTS" (:0, )
[WARNING] Failed to create texture (:0, )
[ERROR] Failed to retrieve frame for clip "00070.MTS" (:0, )
[WARNING] Failed to create texture (:0, )
[INFO] Auto-recovery project saved (:0, )

**Comment by AGI-THB** [comment]
There is an ISSUE TEMPLATE for a reason.

Use it.

**Comment by DaniSeeh** [comment]
This gives almost no info. If you update with more info and a filled out issue template, we can reopen it.

**Comment by leminhfsd** [comment]
Sorry for "no info" but how can I describe how they can't play mts file?

Vào Th 7, 11 thg 5, 2019 vào lúc 05:45 DaniSeeh <notifications@github.com>
đã viết:

**Comment by BrimsonBhin** [comment]
@leminhfsd This is already a known issue in https://github.com/olive-editor/olive/issues/769

**Comment by leminhfsd** [comment]
Thank you so much!
I wish I can help Olive much more

Vào CN, 12 thg 5, 2019 vào lúc 09:16 BrimsonBhin <notifications@github.com>
đã viết:

**Comment by DaniSeeh** [comment]
When you first fill out an issue, a template appears. Please fill out that template in the future. OS, Hardware, driver versions, descriptions of the problem and how to reproduce it all help the bug be fixed.

**Comment by leminhfsd** [comment]
Yeah, Sorry for the lack because I dind see all of those information.
Thank you for your note.

Vào Th 3, 14 thg 5, 2019 vào lúc 14:20 DaniSeeh <notifications@github.com>
đã viết:

**Comment by MarvinRomeo** [comment]
did you fix the problems with mts file? I have the same problem

**Comment by leminhfsd** [comment]
I have to convert to mp4 before edit. Quite waste time

**Comment by MarvinRomeo** [comment]
Wow, olive look good, hope in the futures Olive support more formats and
codec
