### ISSUE TITLE
[Feature Request] Link Discord in the website

### ISSUE THREAD

**Issue by MaGaRCaN** [olive-editor/olive#922]
**Is your feature request related to a problem? Please describe.**
Can't find any raeason why Discord isn't linked from the wesite

**Describe the solution you'd like**
I'd like it to be added

**Describe alternatives you've considered**
![Sin título](https://user-images.githubusercontent.com/1155927/57291478-d53b2b80-70bf-11e9-91c1-4a41a815c062.png)

**Comment by oc1024** [comment]
Placing it after _before_ Report Bugs and along with other social media would make more sense.

**Comment by MaGaRCaN** [comment]
Well, te idea is this to appeard somewherein the site. I did not think in the proper place.
