### ISSUE TITLE
[Bug] Travis CI failed except for Mac

### ISSUE THREAD

**Issue by Symbian9** [olive-editor/olive#923]
**Describe the bug**

After merging `furtherocio` into `master` there are NO nightly builds for Linux & Windows.

1.1. https://travis-ci.org/olive-editor/olive/builds/528017796?utm_source=github_status&utm_medium=notification
1.2. https://ci.appveyor.com/project/itsmattkc/olive/builds/24298694
2.1. https://travis-ci.org/olive-editor/olive/builds/529071030?utm_source=github_status&utm_medium=notification
2.2. https://ci.appveyor.com/project/itsmattkc/olive/builds/24349753

**Additional context**

- https://github.com/olive-editor/olive/releases/tag/continuous

**Comment by ZoomTen** [comment]
Codebase right now is very unstable, and I believe the nightly builds are paused for the time being

**Comment by itsmattkc** [comment]
This is not a bug. Don't expect CI builds for some time.
