### ISSUE TITLE
[Feature Request] Including community effects and make some tutorials on how to add you own effect

### ISSUE THREAD

**Issue by malnaanah** [olive-editor/olive#924]
I was surprised to find some community effects for olive in this link 

https://github.com/cgvirus/Olive-Editor-Community-Effects

I suggest to include these effect in the program and hopefully make some tutorials on how to make your own effects. 

Regards

**Comment by cgvirus** [comment]
It should be maintained by community. Maintaining extra things are exhaustive for the core team and harmful for core development. That's why it is named with community. Core team should not be bugged with it.

**Comment by malnaanah** [comment]
I don't think including community effects requires hard efforts, but it will be helpful for users that may not even know about those effects, also a platform for collaboration could be arranged.

What about writing tutorials to make your own effects, that will be helpful.

**Comment by cgvirus** [comment]
It is indeed hard to maintain. I have to chunk my daily routine just to size it up. Just like all Open source efforts people will know about these repos via google/social interaction or maybe via Olive website when it gets mature.
If someone know basic GLSL programming or C++ I believe they don't need tutorial to follow as programming depends on necessity. The base templates are all exposed so it's easier for coders to follow.

**Comment by DaniSeeh** [comment]
Many of these effects are about to need to be rewritten because of the major rewrites occurring to the core of Olive, and committing Matt and the rest of the main dev team to rewriting them is unreasonable to expect. Obviously the work done on that repo of effects is deeply appreciated, but they won't be included in Olive by default.

**Comment by frink** [comment]
It needs to be a separate repo. Whether or not it is maintained by the same team is at the sole discretion of the team. We should not push them to maintain more code than they already do. It's tough to keep things relevant.

Most of the cool transitions I've seen in Olive have come from playing with two clips and many keyframes. Now if there were a way to gather these keyframes and export them into transition effects, that would be very cool. I also suggested gl-transitions.com as a source of some amazing effects.

If the community transition library (which is probably the right place to start with effects) is a set of scripts exported either as GLSL or some DSL format containing the keyframes then it might be maintainable provided that the underlying script interpreter is backwards compatible.

Scripting is probably as far as the original maintainers should go in providing these tools. That and perhaps allowing easy submission and curation of a community library...

**Comment by frink** [comment]
OBS is still trying to figure out how to do this right. not as easy done as said. Requires a commitment to a certain API. Not likely to be there for a while...
