### ISSUE TITLE
[Feature Request] Layout Profiles

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#927]
**I have read the following**
- [x] The Olive Wiki
- [x] Previous issues that include "FR" or "Feature Request"
- [x] Olive's Project Tab

**Is your feature request related to a problem? Please describe.**
When spending to much time moving around your layout to your liking and you accidently hit the reset button, can lead to stress to recreating the exact same layout as the previous one

**Describe the solution you'd like**
A menu should be implemented in the Window Tab where you can create multiple profiles of layout positions so you can easily load up a layout position you havve saved and created

**Describe alternatives you've considered**
There are no alternatives to this unfortunately

**Do you know any libraries or sources that can help the Olive Team include the feature?**
None that i know of.

**Additional context**
None to add here unfortunately

**Comment by sobotka** [comment]
Rolling this into #587.
