### ISSUE TITLE
[Bug] Double Click To Unlock The Layout

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#928]
**Describe the bug**
As the Layout that refuses to lock after restarting the software got fixed, it introduced a new problem, you now need to double click to unlock the layout to move

**To Reproduce**
1. Go to 'Window'
2. Click on 'Lock Layout'
3. You can see that you need to double click on the option to unlock the layout

**Expected behavior**
You only need click once to unlock the layout

**Screenshots**
![olive-editor_7sGvSdhxwt](https://user-images.githubusercontent.com/37266538/57388455-7c9b8980-71b8-11e9-8e07-36a7b1783e55.png)

**Desktop (please complete the following information):**
- Olive version:  [99b6bab6]
- Source: [zip from github]
- Operating system: [Windows 10 64-bit]
- CPU: [Intel i5-6400]
- RAM: [4GB]
- GPU: [Intel Graphics HD 530 128MB (Latest Drivers)]

### Output Log

```
[Nothing]
```

### GDB/CDB Backtrace (for crashes)

```
[Nothing]
```

**Additional context**
No context

**Comment by itsmattkc** [comment]
Unfortunately I don't see that I need to double click it. Can you elaborate further?

**Comment by MrTeeXD** [comment]
Here is a gif of the problem : 
![GlMtkUgSMA](https://user-images.githubusercontent.com/37266538/57397650-77950500-71cd-11e9-836f-b512d1799190.gif)
