### ISSUE TITLE
I can't install olive from aur

### ISSUE THREAD

**Issue by RezaSh13** [olive-editor/olive#930]
Hi, when i wanna install olive from aur :(
(olive-git  is unstable)

 plasma  ~  1 :( yay -S olive 
:: There are 2 providers available for olive:
:: Repository AUR
    1) olive 2) olive-git 

Enter a number (default=1): 1
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  olive-0.1.0-1

:: Parsing SRCINFO (1/1): olive
==> Making package: olive 0.1.0-1 (Wed 08 May 2019 10:04:13 PM +0430)
==> Retrieving sources...
  -> Found 0.1.0.tar.gz
==> Validating source files with sha512sums...
    0.1.0.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
Error downloading sources: olive

**Comment by itsmattkc** [comment]
Hi, sorry you're having trouble with this, but I didn't set up and don't maintain the AUR. Please contact the maintainer to try to fix this.
