### ISSUE TITLE
[Bug] Crash when confirming Image Sequence Detected dialog

### ISSUE THREAD

**Issue by sc3sc3** [olive-editor/olive#933]
**Describe the bug**
Application crashes

**To Reproduce**
1. dragndrop a folder with still images ( +/- 3000 images, total 250MB ) into Project/Name
component of application
2. Click 'OK' in Image Sequence Detected dialog

**Desktop (please complete the following information):**
- Olive version:  Olive (April 2019 | Alpha | 99b6ba6)
- Source: AppImage ( downloaded from website )
- Operating system: Ubuntu 16.04 64-bit
- CPU:  Intel i7
- RAM: 16GB
- GPU: NVIDIA Geforce GTX 1060 3GB

**Comment by itsmattkc** [comment]
Can you recreate this with GDB output?

**Comment by sc3sc3** [comment]
I get "no debugging symbols found"
