### ISSUE TITLE
Cannot compile anymore - Qmake 

### ISSUE THREAD

**Issue by grash54** [olive-editor/olive#935]
**Describe the bug**
After cloning and going into olive folder then typing 'qmake' it just brings up the help screen.

**To Reproduce**
1. Go into 'olive folder'
2. Type in 'qmake.'
3. See error

**Expected behavior**
qmake actually performs its task

**Screenshots**
n/a

**Desktop (please complete the following information):**
- Olive version:  any from 2 weeks ago and current
- Source: git
- Operating system: Debian Sid
- CPU: i7-8700k
- RAM: 16GB
- GPU: EVGA GeForce GTX 1080 Ti 1030 11GB (Driver ver 418.56)

### Output Log

```
[Paste output log]
```

### GDB/CDB Backtrace (for crashes)

```
[If you can reproduce this issue, try running Olive through GDB and retrieving a backtrace, then paste the backtrace here. Instructions are available in the Wiki on how to acquire this backtrace.]
```

**Additional context**

**Comment by itsmattkc** [comment]
The `qmake` system was removed. Use `cmake` instead.
