### ISSUE TITLE
[Bug] Export freezes at 67%

### ISSUE THREAD

**Issue by RezaSh13** [olive-editor/olive#936]
The rendering will go up to 67% and will stop
![image](https://user-images.githubusercontent.com/22277992/57470169-76330d80-729d-11e9-8f8b-a853fa36167b.png)
![image](https://user-images.githubusercontent.com/22277992/57470222-906ceb80-729d-11e9-94e3-6cfb5c177215.png)

![image](https://user-images.githubusercontent.com/22277992/57470331-cad68880-729d-11e9-92c6-5c7f5ad20992.png)

**Comment by AGI-THB** [comment]
Fill out the issue template.

**Comment by BrimsonBhin** [comment]
Does it only happen on h264 or other codecs as well? Try MPEG-4

**Comment by itsmattkc** [comment]
It indeed would help if you hadn't ignored the template. We'll need the following information to help you:

- Olive version:
- Source (AppImage/PPA/AUR/etc):
- Operating system:
- CPU:
- GPU:

**Comment by RezaSh13** [comment]
aur/olive 0.1.0-2
manjaro

 plasma  ~  inxi -Fx
System:    Host: plasma Kernel: 5.1.0-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.1 Desktop: KDE Plasma 5.15.4 
           Distro: Manjaro Linux 
Machine:   Type: Desktop Mobo: Gigabyte model: G41MT-S2 serial: <root required> BIOS: Award v: F4 date: 01/05/2011 
CPU:       Topology: Dual Core model: Pentium E5700 bits: 64 type: MCP arch: Penryn rev: A L2 cache: 2048 KiB 
           flags: lm nx pae sse sse2 sse3 ssse3 vmx bogomips: 12005 
           Speed: 1968 MHz min/max: 1200/3000 MHz Core speeds (MHz): 1: 1968 2: 1984 
Graphics:  Device-1: Intel 4 Series Integrated Graphics vendor: Gigabyte driver: i915 v: kernel bus ID: 00:02.0 
           Display: x11 server: X.Org 1.20.4 driver: intel unloaded: modesetting resolution: 1360x768~60Hz 
           OpenGL: renderer: Mesa DRI Intel G41 v: 2.1 Mesa 19.0.3 direct render: Yes 
Audio:     Device-1: Intel NM10/ICH7 Family High Definition Audio vendor: Gigabyte driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 
           Device-2: Microdia type: USB driver: hid-generic,snd-usb-audio,usbhid,uvcvideo bus ID: 1-6:3 
           Sound Server: ALSA v: k5.1.0-1-MANJARO 
Network:   Device-1: Qualcomm Atheros AR8151 v1.0 Gigabit Ethernet vendor: Gigabyte driver: atl1c v: 1.0.1.1-NAPI port: df00 
           bus ID: 02:00.0 
           IF: enp2s0 state: up speed: 100 Mbps duplex: full mac: 1c:6f:65:ec:9a:3b 
Drives:    Local Storage: total: 931.51 GiB used: 705.50 GiB (75.7%) 
           ID-1: /dev/sda vendor: Western Digital model: WD10EZEX-00BN5A0 size: 931.51 GiB 
Partition: ID-1: / size: 31.54 GiB used: 16.15 GiB (51.2%) fs: ext4 dev: /dev/sda6 
           ID-2: /home size: 760.88 GiB used: 689.35 GiB (90.6%) fs: ext4 dev: /dev/sda9 
Sensors:   System Temperatures: cpu: 45.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 148 Uptime: 1h 25m Memory: 3.82 GiB used: 2.34 GiB (61.2%) Init: systemd Compilers: gcc: 8.3.0 
           Shell: bash v: 5.0.3 inxi: 3.0.33
