### ISSUE TITLE
[Bug] Parse error when loading project

### ISSUE THREAD

**Issue by MassiminoilTrace** [olive-editor/olive#939]
**Describe the bug**
XML parse error while trying to open a project.

**To Reproduce**
1. Create a new project, for example importing one video in a new sequence
2. Save the newly created project
3. Close Olive, reopen it
4. Load the project

**Expected behavior**
Normally open the project

**Screenshots**
![Errore_apertura_progetto_20190509_203315](https://user-images.githubusercontent.com/24638827/57478005-2b63c680-729a-11e9-85da-139b2518d18e.png)

**Desktop (please complete the following information):**
- Olive version:   3fe0d1c
- Source: Compiled source code.
- Operating system: Fedora Linux 29 KDE
- CPU:Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
- RAM: 16 GB
- GPU: NVIDIA Geforce GTX 940MX

### Output Log
See the screenshot above.
The part of the error message in Italian means "Premature end of the file".
In total, two error windows like the one in the screenshot are opened one on top of the other.

Here's the created project file
```
<?xml version="1.0" encoding="UTF-8"?>
<project>
    <version>190219</version>
    <url>/home/rosto/Scrivania/new project.ove</url>
    <elements>2</elements>
    <footage id="0" name="Urban Downhill Biancheri 2019.mp4" url="../Video/Urban Downhill Biancheri 2019.mp4" duration="132539000" using_inout="0" in="0" out="0" speed="1" alphapremul="1" startnumber="0" colorspace="raw" proxy="0" proxypath="">
        <video id="0" width="640" height="360" framerate="30.0000000000" infinite="0"/>
        <audio id="1" channels="2" layout="3" frequency="44100"/>
    </footage>
    <sequence id="1" name="Sequence 1" width="640" height="360" framerate="30.0000000000" afreq="44100" alayout="3" open="1" workarea="0" workareaIn="0" workareaOut="0"/>
</project>

```
**Additional context**
I tried to remove all Olive files in .local and .config to make sure there isn't any conflict with previously existing ones.

**Comment by itsmattkc** [comment]
Saving/loading is broken in `master`. Please stick to 0.1.0.

**Comment by DaniSeeh** [comment]
Repeat of #937.

Please read through issue tracker search when possible to prevent repeat issues.
