### ISSUE TITLE
[Bug] Huge Memory Leak

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#945]
**Your Setup:**
- Olive version (99b6ba6b):
- Source: (zip from Github)
- Operating system: (Windows 10 64-bit)
- CPU: (Intel i5-6400)
- RAM: (4GB)
- GPU: (Intel Graphics HD 530 128MB (Latest Drivers))

**Describe the Bug**
Olive has a huge memory leak when playing back a video

**To Reproduce**
1. Just add a video and try to play it back

**Screenshots**
![Huge](https://user-images.githubusercontent.com/37266538/57557267-be276280-7379-11e9-85da-3b7f844746ae.PNG)

** Debug Log and/or Crash Report **

```
[Nothing]
```

**Additional Details**
This is also related to issue #1

**Comment by sobotka** [comment]
Are you certain this is a leak? Is the memory growing with every scrub?

**Comment by MrTeeXD** [comment]
Yes, even when i apply a cut on one end if the clip, the Memory Usage Spikes up and rendering the preview takes awhile instead of being instantly rendered

**Comment by sobotka** [comment]
“Spiking up” doesn’t necessarily indicate a leak. If you can demonstrate how it allocates say, 16 gigs moving a sequence around, that’s a leak. Cutting is creating duplicates, so potentially not a leak.

**Comment by MrTeeXD** [comment]
I understand, what i also think the problem could be is the way the Video was Encoded

**Comment by sobotka** [comment]
It’s not a “problem” per de. Remember, NLEs are the most notorious memory gobblers on the planet next to compositors. This comes with good reason; the decoding process alone requires enough frames kept in volatile memory to decode the current frame, then a number of frames after it to hold sync.

I’m not suggesting there might not be a memory leak, but glancing down and seeing that a codec / cache / whatever is gobbling up a gig of memory isn’t a leak, doubly so given the context of an NLE.

If you scrub a single sequence, and memory constantly climbs, that may be a leak.
If you cut a sequence, and then delete the result, and repeat the process and the memory is never freed, that may be a leak.

I’m skeptical this is a leak with the current information.

**Comment by ShaneMilton** [comment]
I just edited a video on Arch Linux in Olive 4k h264 file while editing it starts out using 6GB but as I edit and ripple delete  the memory use keeps growing so I save a lot and when I hit 25GB I close the program and re launch to get memory back.  I watch my memory use with htop on my second monitor.

**Comment by crispycookies** [comment]
Well there certainly are memleaks. Considering the current NoTrack-Branch, i already get a few when just starting and closing the Software.

```
Leak_DefinitelyLost
vg_replace_malloc.c
24 bytes in 1 blocks are definitely lost in loss record 106 of 622
302 (256 direct, 46 indirect) bytes in 1 blocks are definitely lost in loss record 465 of 622
831 (16 direct, 815 indirect) bytes in 1 blocks are definitely lost in loss record 533 of 622
```
```
Leak_PossiblyLost
vg_replace_malloc.c
1,584 bytes in 22 blocks are possibly lost in loss record 562 of 622
1,584 bytes in 22 blocks are possibly lost in loss record 563 of 622
1,998 bytes in 212 blocks are possibly lost in loss record 573 of 622
10 bytes in 5 blocks are possibly lost in loss record 22 of 622
110 bytes in 55 blocks are possibly lost in loss record 378 of 622
144 bytes in 2 blocks are possibly lost in loss record 413 of 622
...
```
And many, many more...

Tested with Valgrind on Arch-Linux(KDE)

**Comment by sobotka** [comment]
Good information. If the functions can be traced, all the better for @itsmattkc to investigate when the appropriate time arrives.

**Comment by crispycookies** [comment]
@sobotka i´ll take a look at it. Probably in the next few days.
I am gonna send you guys a XML-File Containing the Memleaks + Read/Write Misbehaviour(which there is a lot). Hopefully you can trace back those errors then. I know that one of them is in grapheditor.cpp.

Anyway, you are doing no one a favor by writing by 300+ Line Functions(like in cacher.cpp) - makes it harder to trace those errors.

**Comment by sobotka** [comment]
>Anyway, you are doing no one a favor by writing 300+ Line Functions(like in cacher.cpp) - makes it harder to trace those errors.

The person doing the heavy lifting does what they deem acceptable for the context.

Bear in mind that nothing works, and the software is pre-pre-alpha.

**Comment by itsmattkc** [comment]
@crispycookies First of all, thank you for the effort and information, though you should know the whole codebase is getting rewritten more or less from scratch (see `rewrite` branch). You are correct that the codebase is messy and suffers from widespread bad design and poor practices. I'm in the process of addressing that there (along with the new infrastructure I've mentioned elsewhere).

You can still compile the information if you want, though it may be a waste of time now. Feel free to compile information on the `rewrite` branch though, I'd be very interested in what you find.

**Comment by crispycookies** [comment]
[Valgrind-XML(GDrive)](https://drive.google.com/file/d/1M1bv3tKPlojjYtNQXf8pn4VNHz2slx4C/view?usp=sharing)
Sadly, the current `rewrite`- Branch is not compileable on my end(Cast  from  `rational` to `long` cause errors).
Therefore, the XML-File only displays the memory mismanagment in the former `NoTrack`-Branch. Still hope that it may be usefull.
