### ISSUE TITLE
[Bug] Olive Crashes When Adding Node

### ISSUE THREAD

**Issue by DaniSeeh** [olive-editor/olive#946]
**Your Setup:**
- Olive version (window title or Help > About): 3fe0d1cd
- Source: Aur
- Operating system: Manjaro Linux x86_64
- CPU: Ryzen 1700x
- RAM: 32gb
- GPU: NVIDIA Geforce GTX 1070 8GB (Driver ver 418.56)

**Describe the Bug**
Olive crashed when right clicking in the node editor and adding a box blur

**To Reproduce**
1. Open Node Editor
2. Right Click on Empty area of Node Editor
3. Scroll down to Box Blur
4. Olive Crashes

** Debug Log and/or Crash Report **

```
Version: 3fe0d1cd
Operating System: Manjaro Linux x86_64
Build ABI: x86_64-little_endian-lp64

Signal: 11

olive-editor(_Z7handleri+0x2e) [0x55e7021ac99e]
/usr/lib/libc.so.6(+0x378b0) [0x7f61288d68b0]
olive-editor(_ZN12EffectsPanel4LoadEv+0x1a3) [0x55e702110ca3]
olive-editor(_ZN12EffectsPanel8SetClipsEv+0xe1) [0x55e702111311]
olive-editor(_Z9update_uib+0x89) [0x55e702115289]
olive-editor(_ZN11OliveGlobal16EffectMenuActionEP7QAction+0x255) [0x55e7020fa915]
/usr/lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x777) [0x7f6128ff81d7]
/usr/lib/libQt5Widgets.so.5(_ZN5QMenu9triggeredEP7QAction+0x43) [0x7f6129b0f7b3]
/usr/lib/libQt5Widgets.so.5(+0x2cf3d6) [0x7f6129b113d6]
/usr/lib/libQt5Widgets.so.5(+0x2d6b22) [0x7f6129b18b22]
```

**Comment by oc1024** [comment]
I've already reported this bug to Matt via Discord, and it is to be expected until GLSL effects are finished and ported.

**Comment by DaniSeeh** [comment]
Does another issue exist? Should I close this one?
