### ISSUE TITLE
[Bug] Getting Freeze between two tracks

### ISSUE THREAD

**Issue by MosesSunny** [olive-editor/olive#949]
Increasing the length of Cyclic videos by duplicating the tracks. While Playing two consecutive tracks at real-time, everytime it freezes for some mili-seconds, which is by the way noticeable. But after exporting the video, it doesn't freezes. This is not a big issue. But playing the cyclic video, it doesn't look playing smoothly.

**Comment by AGI-THB** [comment]
Fill out the Issue Template.

**Comment by itsmattkc** [comment]
Known issue. Wait for the next cached update.
