### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by OhioVR** [olive-editor/olive#950]
I cannot seem to find any project settings that would allow me to select portrait mode for cell phone video. 

A projects setting area where you could set

I can set the output resolution but when I position in 3d, a video that is portrait mode, select 1080x1920 as the output resolution the image is squashed on the horizontal axis.

**Comment by ZoomTen** [comment]
Try:
* Dragging the Sequence Viewer window away, it'll detach it and let you resize the viewer window so it doesn't look squished. Make sure "Window -> Lock Panel" is unticked.
* Adjusting the scale of the video in the Transform effects.

**Comment by DaniSeeh** [comment]
This is not the place to ask for help. Please use the discord for that.
