### ISSUE TITLE
[Feature Request] Automatically Import Image Into Project After Using "Save Frame As Image"

### ISSUE THREAD

**Issue by emma-15** [olive-editor/olive#951]
The title says it all...

**Comment by sobotka** [comment]
Seems a bit wonky, no? I can’t imagine having auto import after an export terribly wise design?

**Comment by DaniSeeh** [comment]
Yeah... Why? If you are trying to export a still frame, why do you want that frame clogging your project pane?

**Comment by itsmattkc** [comment]
I think this would be fine, I imagine the mechanism would be the same as recording audio in the timeline

**Comment by Nordy13** [comment]
I Like the idea. That would be great with a [screenshot icon](https://github.com/olive-editor/olive/issues/908) as well.

**Comment by sobotka** [comment]
I can’t lie... this strikes me as bonkers. I simply don’t understand why on earth you would be integrating a “screenshot” (already sort of bonkers given the OS handles this) into a project.

Imagine cutting a short film and screaming out “I absolutely need a screenshot of this inserted automatically into the timeline!!1!1” It is bananas.

**Comment by alcomposer** [comment]
Obviously this would be for static frames. Would it not be better to do this with clip speed value?

**Comment by emma-15** [comment]
> 
> 
> I can’t lie... this strikes me as bonkers. I simply don’t understand why on earth you would be integrating a “screenshot” (already sort of bonkers given the OS handles this) into a project.
> 
> Imagine cutting a short film and screaming out “I absolutely need a screenshot of this inserted automatically into the timeline!!1!1” It is bananas.

Actually, I meant project pane, not timeline.

It's just something windows movie maker could do and olive can't 

(even though windows movie maker automatically imports the image into the timeline instead of project pane because windows movie maker has no project pane)

**Comment by sobotka** [comment]
Sounds like a terrific thing to do in Windows Movie Maker, then. ;)

**Comment by frink** [comment]
I'm trying to understand the use case as well... How would this be useful?

What would someone use this auto-import thingy for...?

**Comment by Fatih20** [comment]
I think instead of doing this, the dev should add a feature "Save image to the project".

**Comment by sobotka** [comment]
This is ridiculous.
