### ISSUE TITLE
How to import/covert .kdenlive projects?

### ISSUE THREAD

**Issue by zenny** [olive-editor/olive#955]
Hi,

I have a lot of projects created in kdenlive, but do not want to redo all the again. Simply stating I could not find something of that kind?

Is there a way to import .kdenlive projects to olive's .ove?

Thanks and cheers,
/z

**Comment by sobotka** [comment]
If they support interchange, and when interchange lands in Olive, you'd be fine. If they don't, you're hooped. Interchange is a high value target for NLEs.
