### ISSUE TITLE
[Bug] olive-editor not available on Debian Stable

### ISSUE THREAD

**Issue by narcisgarcia** [olive-editor/olive#956]
**Your Setup:**
- Operating system: Debian 9 (stable)
- CPU: amd64
- RAM: 16GiB
- GPU: Intel

**Describe the Bug**
At Linux donwloads page it says "Olive is available through Debian packages" but it's not true.

**To Reproduce**
$ apt-cache search Olive
ballview - free molecular modeling and molecular graphics tool
libball1.4 - Biochemical Algorithms Library
libball1.4-data - Biochemical Algorithms Library (data files)
libball1.4-dev - Header files for the Biochemical Algorithms Library
libballview1.4 - Biochemical Algorithms Library, VIEW framework
gem-extra - Graphics Environment for Multimedia - extra objects
golang-gopkg-olivere-elastic.v2-dev - Elasticsearch client for Golang
olive - console RSS reader
zfsnap - Automatic snapshot creation and removal for ZFS

**Comment by itsmattkc** [comment]
You may also notice it's under "unofficial" meaning we have no control over that package. If you follow the link, it leads to this (I guess it's only on sid): https://packages.debian.org/sid/olive-editor
