### ISSUE TITLE
[Bug] olive-editor not available as AppImage

### ISSUE THREAD

**Issue by narcisgarcia** [olive-editor/olive#957]
**Your Setup:**
- Operating system: Debian 9 (stable)
- CPU: Intel i5
- RAM: 16GiB
- GPU: Intel

**Describe the Bug**
At Linux downloads page it says "Olive is available as an AppImage on GitHub" but it's not true

**To Reproduce**
1. Follow link

**Comment by AGI-THB** [comment]
The Developer knows about this already.
It doesnt make sense to waste time fixing the build system while the big refactoring has not been finished.

**Comment by itsmattkc** [comment]
It should probably link to here instead, which does have an AppImage: https://github.com/olive-editor/olive/releases (now it does)
