### ISSUE TITLE
[Feature Request] Complete 'About' page at website

### ISSUE THREAD

**Issue by narcisgarcia** [olive-editor/olive#958]
Olive project website should include an "About" link to a documentation page, describing not only the software but also license and any else basics to know before downloading packages.

**Comment by itsmattkc** [comment]
I don't really think there's much to document before downloading packages

**Comment by narcisgarcia** [comment]
- What is the project
- Software features
- Software license
- Hardware and OS requirements

...those are all basics to present to the public & community!
