### ISSUE TITLE
Snap is outdated

### ISSUE THREAD

**Issue by narcisgarcia** [olive-editor/olive#959]
**Your Setup:**
- Olive version (window title or Help > About): N.A.
- Source: sudo snap install --edge olive-editor
- Operating system: Debian 9 (stable)
- CPU: Intel-i5
- RAM: 16GiB
- GPU: Intel

**Describe the Bug**
"About" dialog is not showing application version

**To Reproduce**
1. Go to "Help" menu
2. Click on "About" option

**Additional Details**
I suggest to include GNU GPL license there too (full offline text)

**Comment by AGI-THB** [comment]
This Software is in (pre-) alpha state.
It has no real version number yet.

**Comment by DaniSeeh** [comment]
The title bar lists the build number if you need it.

**Comment by narcisgarcia** [comment]
I have my doubts about being the right place, the title bar, to application version be shown instead on focusing on current project.
Anyway, 'About' dialog is the necessary place for all applications.

**Comment by itsmattkc** [comment]
It's fairly common for the title bar to contain the application version. Regardless, the real issue here is the snap is painfully out of date and may as well be updated since we had a release recently.

**Comment by frink** [comment]
For pre-alpha the titlebar hash makes sense. Once we have a refined beta that's the time to start working on an about page and arguing where to show the version number...

**Comment by pixelr0** [comment]
please update the snap :(

**Comment by MikeWallaceDev** [comment]
+1 for updating the snap, please :)
