### ISSUE TITLE
Time Warping

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#962]
**Is your feature request related to a problem? Please describe.**

Not related to a problem. Folks in the Olive Subreddit, Discord, and (unofficial) Facebook group discussed about time-warping.

**Describe the solution you'd like**

Keyframeable clip speed. I believe Blender's sequencer is the only NLE out there with time-warping with its source code available.

This feature could solve https://github.com/olive-editor/olive/issues/902 too if one keyframes the speed to `0`?

**Describe alternatives you've considered**

The current method for "keyframing speed" is to have multiple, split fragments of a clip with different speeds. Not a productive and performant solution.

**Additional Notes**
I opened this issue because Olive users from different platforms discussed about this feature.

**Comment by bobpatraque** [comment]
It would definitely make Olive the coolest NLE EVER !

**Comment by frink** [comment]
I wonder if librubberband could be hijacked here. It's audio specific, but allows keyframe type stretching in non-linear fashion. I'm not sure how one would go about applying this to 2D graphics though...
