### ISSUE TITLE
[Feature Request] Add Outline of Title Text Back to Current Version

### ISSUE THREAD

**Issue by WolfPack30156** [olive-editor/olive#963]
**Is your feature request related to a problem? Please describe.**
When I was using an earlier version of Olive I was using the outline feature to give my text on screen a border for consistency and color contrast to that of the back ground. I no longer see this in the gui as a feature but I can see that it is able to render in the most recent version of Olive without struggle, by opening a file made with a previous version of olive.

**Describe the solution you'd like**
I would like the development team or another who's more skilled and knowledgeable about the projects's innards to add the outline feature back. I believe it would be adding back the graphical user interface options for outline, and making them add the same entries into the ove file. I will supply examples of this below.

**Describe alternatives you've considered**
Copy pasting the same lines as previous that allowed outlines which only revealed that it doesn't work. I believe based upon my research and looking only at the ove files generated by the Olive Version I have that the text rendering is done in something that appears to be similar to HTML and CSS so maybe we could use CSS' `text-shadow` with +\- 1 or variable around the text or with the web-kit method with `webkit-text-fill-color`, `webkit-text-stroke-width`, and `webkit-text-stroke-color`

**Do you know any libraries or sources that can help the Olive Team include the feature?**
List open-source libraries related to the feature.
I'm not aware of libraries by name; though I am aware that the above mentioned webkit works with Firefox and I believe it's opensource. 

**Additional context**
I have the following screenshots to add:
[Screenshot from Current Version Version# 190219](https://pbs.twimg.com/media/D62Bhl2XsAA5VDG.png) 

[Gist Of Excerpt of OVE file](https://gist.github.com/WolfPack30156/650d4485307307fd54953c35811a618f)

[Screenshot from Current Version but File made in Version# 190201](https://pbs.twimg.com/media/D62B6dOWsAEx47L.png)

[Gist Of Excerpt of OVE File](https://gist.github.com/WolfPack30156/3474effea42e93ca2f7a10ca032b3c99)

I tweeted them to the OliveTeam twitter account before remembering you have an github and I could supply a bunch more context and potentially even suggestions on how to re-add it to the project. Apologies if this isn't to your standard or specifications of reporting or request. 
Links to the web kit tools I found [here.](https://css-tricks.com/adding-stroke-to-web-text/)

Olive Version: March 2019 | Alpha | c5f63ec2
OS: Windows 10 x64

Additional notes; the version number in the OVE file doesn't reference to the checksum so I am unable to recall the checksum off of my head as I just recall it was approx Jan/Feb of 2019 for this feature, it might've been as late as Dec2018 and I was just using a depreciated version. 

I hope that this reaches your team well and I've made it clear enough to everyone the details that I'd like to see back in the editor. I know potentially you're working on over-hauling titles either way with the Feature request: #783 but this is just trying to get something to return to Olive that was in previous version. 
#257 I'd also say that this while I understand we're using the hashing because of rapid development, if you're going to need to reference this specifically I'd suggest adding it into the OVE file generated as like an extra xml line because above I had to use the version number given for an older file, and I'm not sure if this would be something useful for the team or just trivial information. 

Thank you for your time and consideration with this. 

Kindest Regards
-Jacob

**Comment by itsmattkc** [comment]
The outline isn't technically gone, it's still in the legacy "Text" effect. However "Rich Text" is currently the default (which is missing the outline for technical reasons). See #523 for plans to merge these and both of their advantages into one effect.

**Comment by WolfPack30156** [comment]
Thanks for your comment I wasn't aware of that plan.
