### ISSUE TITLE
Website links

### ISSUE THREAD

**Issue by enzogian** [olive-editor/olive#964]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Do you know any libraries or sources that can help the Olive Team include the feature?**
List open-source libraries related to the feature.

**Additional context**

**Comment by DaniSeeh** [comment]
You seem to have made some mistake with the formatting of this issue. If you edit it to explain what you desire, it can be reopened.

**Comment by enzogian** [comment]
Hello there to all developers,
I just would like to inform (I dont find other way to communicate this message at the moment) that we (some OLIVE users) have opened a Facebook group and page, and even a Telegram community group, it would be great seeing some of you around our groups and even better if at some point these links could be included on some section of the website like community links or something like that ??  -  Here is a list with the links of the spaces mentioned above:

**Fb page (we invite you like it at least ;)**
https://www.facebook.com/olivevideoeditor/

**Fb group:**
https://www.facebook.com/groups/olivevideoeditor/

**TELEGRAM community:**
https://t.me/joinchat/I4MhmRWpQ_sfwC4gJduzmg  

**and we have recently opened a space in the new decentralized and open source social network called MINDS.com (here the link):**
https://www.minds.com/groups/profile/974740405659222016/feed

Hope these spaces might help to grow up the users community sharing tips, tutorials and promoting the use of the tool in general ..

Thanks to you all,
regards and cheers,
Enzo

**Comment by DaniSeeh** [comment]
Discord
https://discord.gg/RmxSe5J

**Comment by enzogian** [comment]
wow thanks a lot
i did not know about this resource of communication called discord
how does it work ?
I'll try my best to keep updated this via either

**Comment by enzogian** [comment]
hello there, I wanted to invite some of the developers (if possible) to join our Telegram community of OLIVE Video Editor in order to add some other administrator to teh group. I personally have created but there is not to much I can inform on features or things to improve etc as I am not involved on development .. so could you please help us somehow to spread teh word among the developers community in order to invite them taking part in teh group (in this way I could even assign to some of them the admin role ??  hope it makes sense ..  
the link of the telegram community is:
https://t.me/joinchat/I4MhmRWpQ_sfwC4gJduzmg  

Thanks a lot and regards,
