### ISSUE TITLE
[Bug] Audio does not play at the start of long audio tracks

### ISSUE THREAD

**Issue by SuperRiderTH** [olive-editor/olive#967]
**Your Setup:**
- Olive version: Olive (April 2019 | Alpha | 1e3cf53)
- Source: PPA
- Operating system: elementary / Ubuntu 18.04 64-bit
- CPU: Intel Core i7-3820 CPU
- RAM: 16GB
- GPU: NVIDIA GeForce GTX TITAN X (430.14)

**Describe the Bug**
If an audio track is on the timeline that is approximately over three hours long, the beginning of that audio track will not play in the timeline.

**To Reproduce**
1. Have an audio track longer than three hours
2. Place in timeline
3. Attempt playing from beginning of timeline
4. Hear nothing

** Debug Log and/or Crash Report **

```
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing custom cursors (:0, )
[INFO] Finished initializing custom cursors (:0, )
[INFO] Initializing icons (:0, )
[INFO] Finished initializing icons (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Matched "../../mnt/Data/CFC Drive/720_blue.png" with absolute path (:0, )
[INFO] Matched "audio0.wav" with absolute path (:0, )
[WARNING] QObject::connect: Cannot queue arguments of type 'QVector' (Make sure 'QVector' is registered using qRegisterMetaType().) (:0, )
[INFO] Clip opened on track 0 (took 12 ms) (:0, )
[INFO] Clip opened on track -1 (took 11 ms) (:0, )
```

**Additional Details**
On a .wav file that is 3:10:30 long, audio does not play unless the playback is started around 4:10. Happens regardless if the audio track is from a video file, or audio file. If the audio track is split using the razor tool, audio playback works fine from the beginning.

**Comment by BrimsonBhin** [comment]
Pure speculation, but I think this could either be some hard-coded limitation in length or Olive's too busy rendering the audio waveforms for it to be playable

**Comment by LittleStinky123** [comment]
I also get this error with my 05:59:54 long hevc video with mp4a audio.
It only play back audio after 02:53:50.
