### ISSUE TITLE
[Bug] Transitions do not copy between sequences

### ISSUE THREAD

**Issue by SuperRiderTH** [olive-editor/olive#968]
**Your Setup:**
- Olive version: Olive (April 2019 | Alpha | 1e3cf53)
- Source: PPA
- Operating system: elementary / Ubuntu 18.04 64-bit
- CPU: Intel Core i7-3820 CPU
- RAM: 16GB
- GPU: NVIDIA GeForce GTX TITAN X (430.14)

**Describe the Bug**
Attempting to copy an item with transitions to another sequence only copies the item without the transitions.

**To Reproduce**
1. Copy an item with a transition
2. Open new sequence
3. Paste item

**Comment by emma-15** [comment]
I have this problem too, it's not only through sequences, it happens any time I paste a clip with a transition anywhere. Also when clips with transitions are nested the transitions dissappear  :disappointed_relieved: .

**Comment by dimitarsp** [comment]
I've also experienced this issue. When working with a nested sequence that has transitions, once I copy the whole nested sequence and enter inside the new one, all the transitions are gone.
