### ISSUE TITLE
Project Window Management: Rename, delete, duplicate, folders etc

### ISSUE THREAD

**Issue by SebastianTheFish** [olive-editor/olive#97]

**Comment by itsmattkc** [comment]
Added in ae13ccfbd1ec2fc2ad423d06123babea3242c8ac :
- Renaming
- Deleting
Yet to add:
- Cut/copy/paste
- Undo/redo
- Folders

**Comment by itsmattkc** [comment]
All of these have now been added, except for undo/redo which has its own issue #72 so I'm closing this one.
