### ISSUE TITLE
Audio issues when using razor tool

### ISSUE THREAD

**Issue by johnmichael0611** [olive-editor/olive#971]
**Your Setup:**
- Olive version (window title or Help > About): Olive (April 2019 | Alpha | 1e3cf533)
- Source: (e.g. AppImage, PPA, AUR, website etc.)
- Operating system: Windows 10
- CPU: i3 7th gen
- RAM: 4GB
- GPU: Nvidia GEForce 940mx

**Describe the Bug**
when you use the razor tool on an audio track, even without moving both of the resulting tracks, there is a slight pause between them, it is really hard to retime music because there is a very noticeable stop.

**To Reproduce**
1. import an audio track
2. Click on the razor tool
3. cut the audio track and don't move it
4. playback the track
5. you'll hear a pause on the cut

**Comment by DaniSeeh** [comment]
The caching rewrite will likely fix a lot of these audio issues, but Matt isn't spending time trying to dust up 0.1.0's issues in the meantime. Every moment he spends on that is a moment he doesn't spend paving the path to the future. If this issue still exists post-caching update, please make another issue or comment on this one to have it reopened. Thanks!

**Comment by johnmichael0611** [comment]
Ok thank you! i'm a bit new to Olive, where can I find the cache rewrite?
