### ISSUE TITLE
Multiple trackname

### ISSUE THREAD

**Issue by saileshkush95** [olive-editor/olive#972]
I display multiple video file name in the  media viewer like shown in below figure:-
![DeepinScreenshot_select-area_20190522171034](https://user-images.githubusercontent.com/28560875/58171103-e89be880-7cb4-11e9-854e-b22da5f65f60.png)

**Comment by AGI-THB** [comment]
I don't understand what you try to point out here.

**Comment by frink** [comment]
I think @saileshkush95 is trying to show that there can be multiple focuses. The effect window is focused on one clip while the media viewer is focused on the other. Isn't this a feature instead of a fault?

**Comment by AGI-THB** [comment]
@frink Looks like normal behavior for me. I don't see why that is a problem.


@saileshkush95 Fill out the issue template next time, please. I have told you before about that.

**Comment by frink** [comment]
@AGI-THB looks normal to me too... I'm scratching my head.

**Comment by DaniSeeh** [comment]
This is not an issue. If you double click in the project pane, you open something in the media viewer. If you click a clip on the timeline, you edit its properties and keyframes. As @AGI-THB pointed out, fill out the template next time. This also isn't a bug, but an intended behavior.
