### ISSUE TITLE
[Bug] Effect sliders causes crash

### ISSUE THREAD

**Issue by ahellqui** [olive-editor/olive#974]
**Your Setup:**
- Olive version: Olive (May 2019 | Alpha | 5e0e0334)
- Source: AUR
- Operating system: Arch linux
- CPU: Intel i5 4460
- RAM: 8GB
- GPU: NVIDIA Geforce GTX 750 TI 2GB (430.14)

**Describe the Bug**
Changing any value in the effects tab causes a crash

**To Reproduce**
1. Import a video file
2. Drag the file to the timeline
3. Click on the video on the timeline
4. Click on the effects tab
5. Change any value by dragging or clicking
6. See error

** Debug Log and/or Crash Report **

```
Version: 5e0e0334
Operating System: Arch Linux x86_64
Build ABI: x86_64-little_endian-lp64

Signal: 11

olive-editor(_Z7handleri+0x4c) [0x55bda6cb827c]
/usr/lib/libc.so.6(+0x378b0) [0x7fe7c94c68b0]
olive-editor(_ZN9NodeGraph4TimeEv+0) [0x55bda6cc6760]
olive-editor(_ZN11DoubleField16UpdateFromWidgetEd+0x71) [0x55bda6ca0181]
/usr/lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x777) [0x7fe7c9be81d7]
olive-editor(_ZN11LabelSlider12valueChangedEd+0x41) [0x55bda6c66871]
olive-editor(_ZN11LabelSlider14mouseMoveEventEP11QMouseEvent+0xf5) [0x55bda6d36ad5]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x1d8) [0x7fe7ca5cbaf8]
/usr/lib/libQt5Widgets.so.5(_ZN6QFrame5eventEP6QEvent+0x1f) [0x7fe7ca67371f]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x84) [0x7fe7ca58ada4]
```

**Comment by sobotka** [comment]
libc.so.6 suggests this could be quite a low level bug related to GPU. I'll close this for now given core is undergoing a significant rewrite. If you can duplicate with other graphics cards and isolate the issue, feel free to reopen a more clear and concise bug.
