### ISSUE TITLE
[Bug] Olive crashes when importing multiple videos from Google Drive File Stream

### ISSUE THREAD

**Issue by Czechball** [olive-editor/olive#976]
**Your Setup:**
- April 2019 | Alpha | 1e3cf533
- Source: Website
- Operating system: Windows 10 Home ver 1809, build 17763.503
- CPU: Intel i5 7600k
- RAM: 16GB
- GPU: Nvidia GTX 460 (Driver ver 23.21.13.9135)

**Describe the Bug**
While trying to open multiple videos from my offline-stored Google Drive Stream folder, and then saving the project, Olive crashes and the whole system becomes unresponsive. I had to hard-reset the PC to get it to work again.

**To Reproduce**
1. Go to any Google Drive File Stream folder and import multiple videos to Olive
2. Save the project

**Screenshots**
[Video 1](https://streamable.com/gx798)
*This is a screencap of the described crash.*
[Video 2](https://streamable.com/s8xgy)
*In this screencap, I import the videos one-by-one and succesfully save the project.*

** Debug Log and/or Crash Report **

```
[This crash won't generate any reports as it halts the whole OS]
```

**Additional Details**
Apparently adding the videos one-by-one ~~and waiting for their thumbnails to load~~ allows the user to save the project.

**Comment by sobotka** [comment]
Google drive isn't in scope at the moment. If this applies to proper network drives, feel free to reopen a proper issue.
