### ISSUE TITLE
no puedo descargarlo y ejecutarlo en osx el capitan [Bug]

### ISSUE THREAD

**Issue by pablishogarcia68** [olive-editor/olive#977]
**Your Setup:**
- Olive version (window title or Help > About):
- Source: (e.g. AppImage, PPA, AUR, website etc.)
- Operating system: (e.g. Ubuntu 18.04 64-bit)
- CPU: (e.g. Intel i5-4300U)
- RAM: (e.g. 8GB)
- GPU: (e.g. NVIDIA Geforce GT 1030 2GB (Driver ver xxx.xx.xx))

**Describe the Bug**

**To Reproduce**

**Screenshots**

** Debug Log and/or Crash Report **

```
[Paste log/report]
```

**Additional Details**
Add any other information about the problem here.

**Comment by sobotka** [comment]
You'll have to compile.

**Comment by pablishogarcia68** [comment]
Gracias 

Pablo r garcía 
11 64670047
