### ISSUE TITLE
[Feature Request] RGB Vectorscope

### ISSUE THREAD

**Issue by MrTeeXD** [olive-editor/olive#979]
**Is your feature request related to a problem? Please describe.**
Sometimes we never know how RGB Correct our videos are and thats where this feature comes in

**Describe the solution you'd like**
This feature allows the user to monitor the RGB of the video and therefor using Effects to correctly balance the colors of the video to perfection.

**Describe alternatives you've considered**
Now you could go and use the Project Monitor to look at the colors but this should be useful

**Do you know any libraries or sources that can help the Olive Team include the feature?**
None that i know

**Additional context**
This is what a RGB Vectorscope looks like : 
![rgb](https://user-images.githubusercontent.com/37266538/58439049-cf82a580-80c1-11e9-9696-3dd671f35726.png)

**Comment by sobotka** [comment]
1. This isn’t a vectorscope. This is a waveform.
2. Vectorscopes are extremely challenging to handle properly in a managed pipeline.
3. “Balancing” is also a little tricky, given that proper pixel handling on your input imagery, from something such as a GH5, an X-T3, an A6500 etc. is handled via the proper colour transform at ingestion.

It’s a kettle of fish to handle properly and correctly.

RGB waveform is the easiest target here. The rest require a little more flexible development and options.

**Comment by MrTeeXD** [comment]
Alright Understood

**Comment by davej453** [comment]
That's an RGB parade. Waveform monitor is slightly different.

I really hope scopes do get implemented into Olive. This is a major feature
for professional editors and most if not all NLEs have advanced color
monitoring tools.

Kdenlive currently has the main ones implemented. Could this be used as a
source for something in Olive?

[image: Screenshot_2019-05-28_06-47-23.png]

**Comment by sobotka** [comment]
Go to B&H and buy and RGB Parade monitor. Or would you be buying a waveform monitor? Or wait, is a waveform capable of displaying both RGB and luma off the SDI? Asking for a friend.

**Comment by davej453** [comment]
RGB Parade and waveform scopes have different utilities in the context of
software NLEs. Olive needs these before it can really be considered
complete.

**Comment by sobotka** [comment]
Please do go on...
