### ISSUE TITLE
[CODEC] To Import Image Layers Across Tracks

### ISSUE THREAD

**Issue by libreartist** [olive-editor/olive#982]
**Is your feature request related to a problem? Please describe.**
Hi,
PSD files import as single images only. PS: I benefitted from layered PSD imports in (earlier) Vegas Pro and Adobe video tools.

**Describe the solution you'd like**
 it would be much edit friendlier, if there's an alternate option like "import as layers". PS: Especially, useful for simple animations (which Olive does great already) :-)

**Describe alternatives you've considered**
Or, using OpenRaster maybe even more open-collaboration friendlier (with good documentation for code, unlike PSD).

**Do you know any libraries or sources that can help the Olive Team include the feature?**
Not a library, but, the official website per se: https://www.openraster.org/

**Additional context**
It is much similar to one of the other [Feature Request] which mentions layered import of SVG. :-)

**Comment by sobotka** [comment]
I loathe this idea largely for encoding / footage reasons.

Multilayer EXR sure. PSD and the rest of the garbage, please no.
