### ISSUE TITLE
[Feature Request] Koblo-like features

### ISSUE THREAD

**Issue by forart** [olive-editor/olive#986]
Ten years ago a project called Koblo launched some innovative ideas:

> Koblo is a new online music collaboration site that utilizes CC licensing on tracks and song stems to promote community remixing and reuse. Uniquely, Koblo exists beyond the web in the form of **Koblo Studio, a free and opensource software DAW** that has the ability to upload projects to Koblo’s community site with all the tracks prepped and ready for remixing. It is during this upload process that a CC license can be chosen for the project.

Source: https://creativecommons.org/2009/02/02/koblo-online-music-collaboration/

It would be great to "import" some of these features - license embedding, for example - into Olive to make it unique compared to its competitors.

Here's a Koblo Studio sources backup: 
https://github.com/grimtraveller/koblo_software

Dunno if this can help in any way (I'm not a dev), but hope that inspires.

Marco Ravich

**Comment by DaniSeeh** [comment]
How would this even work? Are there any video formats that support license embedding? And what would be the goal of such a thing? Most licenses require you display them openly, and I suspect that embedding it in a file where it can't easily be seen wouldn't count.

**Comment by BrimsonBhin** [comment]
Olive has shifted into another direction of being an **NLE**. It is no longer focused on being a "swiss knife" between a pseudo-DAW, image editor, and a simple NLE. I don't mine plugin support, but some features from a DAW might not fit well into an NLE.

Koblo is also from 2009 so I assume its dead (as in no development or support). Therefore, it would be difficult for MattKC to ask for support on how things work and where they should be.
