### ISSUE TITLE
[Bug] Compilation mistake

### ISSUE THREAD

**Issue by reynum2** [olive-editor/olive#987]
**Your Setup:**
- Olive version : d3b00ef
- Source: Github
- Operating system: Debian Buster
- CPU: AMD Ryzen 7 1700X
- RAM: 16GB
- GPU: [AMD/ATI] Ellesmere [Radeon RX 470/480] (rev ef)

**Describe the Bug**
- The olive version from Debian repo is very old (december 2018)
- I try the appimage (v 0.1.0) but I experiment a segfault : the same describe here https://github.com/olive-editor/olive/issues/960
- So try to compile : Follow the page https://olivevideoeditor.org/compile.php#linux install all dependencies but when I try to qmake nothing append it could be nice to change qmake to cmake in the documentation page :-) https://github.com/olive-editor/olive/issues/935
- Then I had a first crash at line 25 (OpenColorIO)
so I install : 
> sudo apt install opencolorio-dev 

(dependency to add to the documentation)

- and now I am locked at line 27 (Qt5LinguistTools)
Try to install the package which contain the linguist tool

> sudo apt install qttools5-dev-tools 

But it not solved my problem

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:27 (find_package)
```
[CMakeOutput.log](https://github.com/olive-editor/olive/files/3243617/CMakeOutput.log)

**To Reproduce**
1. Try to compil form a new Debian Buster

PS : Thanks a lot for this software which is (will be) the only NLVE powerfull on Linux

**Comment by tecnotercio** [comment]
Have you installed the "qttools5-dev" package?
It contains the file "Qt5LinguistToolsConfig.cmake".

https://packages.debian.org/jessie/amd64/qttools5-dev/filelist

**Comment by reynum2** [comment]
Thanks a lot !
I can compile now.
qttools5-dev is another dependency to add to the documentation page :-)
