### ISSUE TITLE
[Bug] Source code: newlines are CR LF (0x0D 0x0A) but should be canonical LF (0x0a)

### ISSUE THREAD

**Issue by hzeller** [olive-editor/olive#995]
When checking out the project, it seems that about half the files I was looking at so far all had DOS line-endings (CR LF, \r\n), but the canonical way to store these would be as LF (\n).

```
find . -name "*.cpp" -o -name "*.h" | xargs file | awk '{total++} /CRLF/ {crlf++} END {printf("%d crlf out of %d\n", crlf, total)}'
229 crlf out of 453
```

I'd like to contribute, but this makes it a little harder. It would be nice if all source-files would have the canonical \n format.

I know it would be some large change now, but probably better now then later when more people start sending pull requests and a newline-change then would make it harder.

Thanks!

**Comment by Simran-B** [comment]
I agree that the line endings should be normalized to Unix `\n` in Git, and now is actually a good time - there are only a few open PRs, and half of them was created for <=0.1.0 and need to be rebased anyway. Furthermore, master doesn't even compile.

**Comment by itsmattkc** [comment]
I'm actually surprised, I'd thought all my Git setups (even on Windows) were set to commit LFs at all times. I'll try to address this at some point.

**Comment by itsmattkc** [comment]
Fixed in most recent master
