### ISSUE TITLE
[Bug] blend mode not working

### ISSUE THREAD

**Issue by oluja1973** [olive-editor/olive#998]
**Your Setup:**
- Olive (April 2019 | Alpha | 1e3cf533)
- Website
- Windows 10
- i7-3520M
- 12 GB
- GPU: Onboard Intel

**Describe the Bug**
Blend mode not working in Windows version

**To Reproduce**
Just drag a file to the timeline, mark the clip, click on effects panel and then blend mode. You cant choose another blend mode then normal.

**Screenshots**
See hare showcase:
https://www.youtube.com/watch?v=mK0dApbwyFY&feature=youtu.be

** Debug Log and/or Crash Report **

```
[Paste log/report]
```

**Additional Details**
Add any other information about the problem here.

**Comment by kniddl** [comment]
It seems the blend modes are disabled:
https://github.com/olive-editor/olive/search?q=blend&type=Commits

**Comment by sobotka** [comment]
Most of the blend modes are based on the rather legacy display referred blend modes outlined in the Adobe PDF specification. As such, they are fundamentally incompatible beyond the more math-pure versions such as multiply, add, subtract, divide, etc.

**Comment by oluja1973** [comment]
> It seems the blend modes are disabled:
> https://github.com/olive-editor/olive/search?q=blend&type=Commits

Yes, you are right. Seems to be disabled temporarely since march. :-)

**Comment by oluja1973** [comment]
> Most of the blend modes are based on the rather legacy display referred blend modes outlined in the Adobe PDF specification. As such, they are fundamentally incompatible beyond the more math-pure versions such as multiply, add, subtract, divide, etc.

Im sorry, but dont understand what you wanne say with this.

**Comment by sobotka** [comment]
I don’t “wanna say” anything.

It’s an explanation as to why the blend modes are disabled. Some of them will not be back.

Until the core is settled, the decision was made to shelve the non-essential design needs.

**Comment by vdmokstati** [comment]
@sobotka  "non-essential design needs." ? I'd like them 1000%. ;)

**Comment by sobotka** [comment]
That’s nice.

The thing still doesn’t work and you want some feature back, a large part of which are entirely incompatible with the current design.
